import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Master Band B — B1–B2 TCF / DELF thematic breadth. Curated for NCLC 7. */
export const MASTER_B: LemmaRow[] = [
  ["Recovery", "la convalescence", "Le médecin recommande une période de convalescence d'au moins trois semaines."],
  ["Sponsored content label", "la mention de contenu commandité", "La mention de contenu commandité doit être clairement affichée par les créateurs sur YouTube."],
  ["Outcome", "le résultat", "Le résultat des élections sera annoncé tard dans la soirée de lundi."],
  ["Grocery shopping", "l'épicerie", "Je fais l'épicerie tous les samedis matin au marché du quartier."],
  ["Tax return", "la déclaration de revenus", "N'oubliez pas d'envoyer votre déclaration de revenus avant la fin avril."],
  ["Open-fire restriction", "l'interdiction de feux en plein air", "Une interdiction de feux en plein air est en vigueur dans tous les parcs nationaux."],
  ["Harmful", "nuisible", "L'utilisation excessive de pesticides est nuisible pour notre environnement local."],
  ["Strategy", "la stratégie", "L'entreprise doit revoir sa stratégie de marketing pour attirer une clientèle plus jeune."],
  ["To encourage", "encourager", "Les subventions gouvernementales visent à encourager l'achat de véhicules électriques par les particuliers."],
  ["Sky glow", "la pollution lumineuse", "La pollution lumineuse nous empêche d'admirer les étoiles depuis notre balcon en ville."],
  ["Soil decontamination", "la décontamination des sols", "La ville prévoit la décontamination des sols de cet ancien terrain industriel."],
  ["Convincing", "convaincant", "Son argumentaire pour obtenir le financement de notre projet n'était pas très convaincant."],
  ["Mayor", "le maire", "Le maire a prononcé un discours lors de l'inauguration de la nouvelle bibliothèque municipale."],
  ["Degree", "le diplôme", "Il possède un diplôme en génie mécanique de l'Université de Sherbrooke."],
  ["Deadline", "la date limite", "La date limite pour déposer une demande d'admission a été repoussée de quelques jours."],
  ["Clickbait headline", "le titre putaclic", "Ce journal utilise beaucoup de titres putaclics pour attirer plus de lecteurs sur son site."],
  ["Carbon sequestration", "la séquestration du carbone", "Planter des arbres est une excellente méthode pour la séquestration du carbone."],
  ["Terms-of-use update", "la mise à jour des conditions d'utilisation", "La plateforme a envoyé un courriel concernant sa récente mise à jour des conditions d'utilisation."],
  ["Assignment", "le travail pratique", "Le travail pratique sur l'histoire du Canada doit être remis avant la semaine d'examens."],
  ["Off-the-record briefing", "la déclaration officieuse", "Le ministre a fait une déclaration officieuse aux journalistes après la conférence de presse."],
  ["Essential", "essentiel", "Il est essentiel de respecter les consignes de sécurité sur le chantier."],
  ["Domestic violence hotline", "la ligne d'écoute pour la violence conjugale", "N'hésitez pas à appeler la ligne d'écoute pour la violence conjugale si vous ne vous sentez pas en sécurité."],
  ["Internship stipend", "la bourse de stage", "L'université offre une bourse de stage pour aider les étudiants pendant l'été."],
  ["Decision", "la décision", "La décision de fermer l'usine aura un impact dévastateur sur l'économie de la petite ville industrielle."],
  ["Consensus", "le consensus", "Il est souvent difficile d'atteindre un consensus lors des réunions du conseil municipal."],
  ["To advise", "conseiller", "Le spécialiste m'a conseillé de faire vérifier l'isolation de ma toiture."],
  ["Management", "la direction", "La direction a décidé de modifier l'horaire d'ouverture du magasin."],
  ["Community land trust", "la fiducie foncière communautaire", "La création d'une fiducie foncière communautaire permettra de protéger des logements abordables à perpétuité."],
  ["Work experience", "l'expérience de travail", "Une expérience de travail préalable est exigée pour poser sa candidature."],
  ["Priority", "la priorité", "La sécurité des piétons devrait toujours être la priorité des planificateurs urbains municipaux."],
  ["Development", "le développement", "Le développement économique de la région repose principalement sur l'industrie touristique et les ressources naturelles locales."],
  ["Grade", "la note", "Elle était déçue de sa note en mathématiques malgré toutes ses heures d'étude."],
  ["To congratulate", "féliciter", "Le directeur l'a appelée pour la féliciter de sa promotion."],
  ["Currently", "actuellement", "L'entreprise est actuellement à la recherche de nouveaux talents en informatique."],
  ["Seminar", "le séminaire", "Le séminaire de recherche permet des échanges plus approfondis entre les participants."],
  ["Consequence", "la conséquence", "La conséquence la plus grave de cette décision politique sera l'augmentation de la pauvreté chez les personnes âgées vulnérables."],
  ["Dune restoration", "la restauration des dunes", "Un projet communautaire vise la restauration des dunes le long de la plage."],
  ["Behavior", "le comportement", "Le comportement inacceptable de ce joueur a entraîné sa suspension pour le reste de la saison sportive."],
  ["Gradually", "progressivement", "Les nouvelles mesures de sécurité seront introduites progressivement d'ici la fin du mois."],
  ["Delivery", "la livraison", "La livraison de nos nouveaux meubles est prévue pour jeudi après-midi entre treize et quinze heures."],
  ["Connection", "le lien", "Le journaliste a établi un lien clair entre la pollution industrielle et les problèmes respiratoires des résidents locaux."],
  ["Distance", "la distance", "La distance entre Montréal et Québec se parcourt en un peu moins de trois heures de route automobile environ."],
  ["Child poverty rate", "le taux de pauvreté infantile", "Des organismes communautaires luttent sans relâche pour réduire le taux de pauvreté infantile dans la métropole."],
  ["Attention", "l'attention", "La question du logement abordable retient de plus en plus l'attention des différents paliers de gouvernement."],
  ["Restorative justice circle", "la justice réparatrice", "Les approches de justice réparatrice mettent l'accent sur la guérison plutôt que sur la simple punition."],
  ["Ad-blocker usage", "le bloqueur de publicités", "J'utilise un bloqueur de publicités pour naviguer plus rapidement sur le Web."],
  ["Parking lot", "le stationnement", "Il est très difficile de trouver une place dans le stationnement du centre commercial aujourd'hui."],
  ["Vaccine", "le vaccin", "La campagne de vaccination contre la grippe saisonnière débutera au début de l'automne."],
  ["Overtime bank", "la banque d'heures", "J'ai accumulé assez de temps dans ma banque d'heures pour prendre un congé vendredi prochain."],
  ["Volunteer retention", "la rétention des bénévoles", "La reconnaissance du travail accompli est la clé d'une bonne rétention des bénévoles."],
  ["Wind turbine", "l'éolienne", "Le nouveau parc comprendra plus de cinquante éoliennes de dernière génération."],
  ["Circumstance", "la circonstance", "Vu la circonstance exceptionnelle, le directeur a accordé un congé payé à toute son équipe de travail."],
  ["Lease", "le bail", "Nous avons signé un bail d'un an pour ce bel appartement du Plateau."],
  ["Network", "le réseau de contacts", "Il est important de développer son réseau de contacts dès l'université."],
  ["To attend", "assister à", "Tous les employés sont invités à assister à la conférence annuelle."],
  ["Soup kitchen shift", "la soupe populaire", "Il fait du bénévolat à la soupe populaire tous les jeudis soirs après le travail."],
  ["Succession planning", "la planification de la relève", "La planification de la relève est cruciale puisqu'un tiers de nos directeurs partiront bientôt à la retraite."],
  ["Minimum wage", "le salaire minimum", "Le gouvernement provincial a annoncé une hausse du salaire minimum à partir de mai."],
  ["Resume", "le curriculum vitae", "N'oubliez pas d'apporter une copie imprimée de votre curriculum vitae."],
  ["Strict", "strict", "Les règlements sur la sécurité des chantiers de construction sont devenus très stricts au fil des ans."],
  ["Colleague", "le collègue", "Mes collègues ont organisé une petite fête pour mon anniversaire au bureau."],
  ["Demand", "la demande", "La demande pour les voitures électriques dépasse largement l'offre disponible chez la plupart des concessionnaires automobiles de la région."],
  ["Driver's license", "le permis de conduire", "Vous devez renouveler votre permis de conduire avant la date de votre anniversaire."],
  ["Renewable energy", "l'énergie renouvelable", "L'hydroélectricité est la principale source d'énergie renouvelable utilisée dans la province."],
  ["Contribution", "la contribution", "La généreuse contribution de la fondation permettra de financer l'achat de nouveaux équipements pour le département de pédiatrie."],
  ["Moving house", "le déménagement", "Notre déménagement est prévu pour le premier juillet, comme beaucoup de Québécois."],
  ["Discount", "le rabais", "Le commerçant nous a offert un rabais de vingt pour cent sur les articles d'hiver."],
  ["Requirement", "l'exigence", "Posséder un permis de conduire valide est une exigence de base pour cet emploi."],
  ["Court", "le tribunal", "L'affaire sera jugée devant le tribunal la semaine prochaine après de multiples reports."],
  ["Lecture", "le cours magistral", "Le professeur donne un cours magistral devant plus de deux cents étudiants à l'auditorium."],
  ["Factor", "le facteur", "Le taux d'inflation élevé est un facteur déterminant dans la hausse vertigineuse du coût des aliments à l'épicerie du coin."],
  ["Innovation", "l'innovation", "Le gouvernement investit massivement pour encourager l'innovation dans le secteur des technologies de l'information."],
  ["Safe injection site", "le centre d'injection supervisée", "Le quartier accueillera un nouveau centre d'injection supervisée pour prévenir les surdoses."],
  ["Impact", "l'impact", "L'impact de la nouvelle loi sur les entreprises locales sera évalué attentivement par un comité d'experts indépendants l'année prochaine au printemps."],
  ["Prime-time slot", "l'heure de grande écoute", "Cette émission est diffusée à l'heure de grande écoute, ce qui garantit de bonnes cotes d'écoute."],
  ["Ergonomics assessment", "l'évaluation ergonomique", "J'ai demandé une évaluation ergonomique de mon poste de travail parce que j'avais mal au dos."],
  ["Asbestos removal", "le désamiantage", "Les travaux de désamiantage de l'école primaire débuteront pendant les vacances d'été."],
  ["Defamation lawsuit", "la poursuite en diffamation", "Le politicien menace d'intenter une poursuite en diffamation contre le journal de la ville."],
  ["Caregiver burnout", "l'épuisement des proches aidants", "L'épuisement des proches aidants est un enjeu de santé publique souvent négligé."],
  ["Drought emergency", "l'état de sécheresse", "La municipalité a déclaré l'état de sécheresse et interdit l'arrosage des pelouses."],
  ["Grievance procedure", "la procédure de grief", "Si vous croyez que vos droits ne sont pas respectés, vous pouvez entamer une procédure de grief."],
  ["Pedestrian", "le piéton", "Les conducteurs doivent toujours céder le passage au piéton qui s'engage sur le passage clouté."],
  ["Pollution", "la pollution", "La pollution de la rivière a causé la mort de centaines de poissons cette semaine."],
  ["Emergency room", "l'urgence", "Le temps d'attente à l'urgence de l'hôpital dépassait les dix heures cette nuit."],
  ["Cover letter", "la lettre de présentation", "Sa lettre de présentation expliquait parfaitement pourquoi elle voulait ce poste."],
  ["Deposit-refund program", "le programme de consigne", "Le programme de consigne sera étendu aux bouteilles d'eau en plastique l'an prochain."],
  ["Dessert", "le dessert", "Je n'ai plus faim pour un dessert, mais je prendrais volontiers un bon café noir."],
  ["Growth", "la croissance", "La croissance économique de la province a été freinée par la pénurie importante de main-d'œuvre qualifiée dans de multiples secteurs clés de l'industrie."],
  ["Cover-crop planting", "la culture de couverture", "La culture de couverture aide à protéger le sol pendant l'hiver."],
  ["Income inequality gap", "l'écart de richesse", "Les statistiques montrent que l'écart de richesse a continué à se creuser au cours de la dernière décennie."],
  ["Tip", "le pourboire", "Il est de coutume de laisser un pourboire d'environ quinze pour cent au restaurant."],
  ["Hybrid work model", "le modèle de travail hybride", "Notre entreprise a définitivement adopté le modèle de travail hybride après la pandémie."],
  ["Oven", "le four", "Préchauffez le four à trois cent cinquante degrés avant d'enfourner le gâteau au chocolat."],
  ["Post office", "le bureau de poste", "Je suis passé au bureau de poste pour récupérer un colis qui m'attendait."],
  ["Appetizer", "l'entrée", "Nous avons partagé une assiette de calmars frits comme entrée avant le plat principal."],
  ["To solve", "résoudre", "Le technicien a finalement réussi à résoudre le problème de connexion internet après plusieurs heures."],
  ["Warranty", "la garantie", "La réparation de la laveuse était couverte par la garantie du fabricant d'électroménagers."],
  ["Business trip", "le voyage d'affaires", "Il est parti en voyage d'affaires à Toronto pour toute la semaine."],
  ["Intergenerational housing", "le logement intergénérationnel", "Le projet de logement intergénérationnel favorise les échanges entre les jeunes étudiants et les personnes âgées."],
  ["Overwhelming", "accablant", "La quantité de courriels à traiter le lundi matin peut être accablante."],
  ["Tuition fee", "les frais de scolarité", "Les frais de scolarité universitaires augmenteront encore à la prochaine rentrée académique."],
  ["Shift work", "le travail par quarts", "Le travail par quarts peut être très exigeant pour le rythme de sommeil."],
  ["Category", "la catégorie", "Ce document doit être classé dans la catégorie des archives confidentielles de l'entreprise."],
  ["Appointment", "le rendez-vous", "J'ai un rendez-vous chez le dentiste mardi prochain à quatorze heures."],
  ["Kindergarten", "la maternelle", "Les enfants commencent généralement la maternelle à l'âge de cinq ans au Québec."],
  ["Barrier", "l'obstacle", "La barrière de la langue est un obstacle important pour de nombreux immigrants récents."],
  ["Telework agreement", "l'entente de télétravail", "Mon entente de télétravail me permet de travailler de la maison trois jours par semaine."],
  ["Laundry", "la lessive", "Il faut que je fasse la lessive ce soir, je n'ai plus de chemises propres."],
  ["Insurance", "les assurances", "Nos assurances couvrent les dégâts causés par les inondations récentes."],
  ["Bill", "l'addition", "Nous avons demandé au serveur de séparer l'addition en trois parties égales pour notre groupe."],
  ["Goal", "l'objectif", "L'objectif de cette campagne de sociofinancement est d'amasser cinquante mille dollars pour rénover la cour de récréation de l'école primaire du quartier."],
  ["Withdrawal", "le retrait", "J'ai dû faire un retrait au guichet automatique pour payer le taxi."],
  ["Full-time job", "le poste à temps plein", "Il cherche un poste à temps plein dans le domaine de la construction."],
  ["Public consultation backlash", "la consultation publique", "Les citoyens ont exprimé leur mécontentement lors de la dernière consultation publique sur le projet de loi."],
  ["Diversity", "la diversité", "La diversité culturelle est l'une des grandes forces de notre société moderne."],
  ["Welfare", "le bien-être", "Le bien-être des employés a un impact direct sur la productivité de toute l'entreprise."],
  ["Climate change", "les changements climatiques", "Les effets des changements climatiques sont de plus en plus visibles dans le Grand Nord."],
  ["Prescription", "l'ordonnance", "Le pharmacien m'a remis mes médicaments après avoir vérifié mon ordonnance médicale."],
  ["Allergy", "l'allergie", "Le cuisinier fait très attention car j'ai une grave allergie aux arachides et aux noix."],
  ["Ballot", "le bulletin de vote", "J'ai déposé mon bulletin de vote dans la boîte après avoir coché mon choix."],
  ["Gender pay gap study", "l'écart salarial entre les sexes", "Un récent rapport souligne que l'écart salarial entre les sexes persiste dans de nombreuses professions."],
  ["Workplace investigation", "l'enquête en milieu de travail", "Une enquête en milieu de travail a été ouverte à la suite d'une plainte de harcèlement."],
  ["Bank account", "le compte bancaire", "J'ai ouvert un nouveau compte bancaire au centre-ville hier."],
  ["Police officer", "le policier", "Un policier dirigeait la circulation à l'intersection en raison d'une panne des feux de signalisation."],
  ["Global warming", "le réchauffement climatique", "Le réchauffement climatique menace directement la survie des ours polaires sur la banquise."],
  ["Cooperative grocery", "l'épicerie coopérative", "Je suis membre d'une épicerie coopérative où les produits locaux sont mis en valeur."],
  ["Alarm clock", "le réveille-matin", "J'ai oublié de régler mon réveille-matin et j'ai manqué le début de mon premier cours."],
  ["Resignation", "la démission", "Il a remis sa lettre de démission à son superviseur vendredi matin."],
  ["Law", "la loi", "Une nouvelle loi interdit désormais l'utilisation du téléphone cellulaire au volant d'une voiture."],
  ["Treatment", "le traitement", "Ce nouveau traitement semble très prometteur pour soulager les douleurs chroniques."],
  ["Example", "l'exemple", "Le professeur a donné un exemple très concret pour illustrer la théorie économique complexe qu'il venait d'expliquer au tableau."],
  ["Error", "l'erreur", "L'erreur informatique a causé l'envoi de factures erronées à des milliers de clients de l'entreprise de télécommunications."],
  ["Amount", "le montant", "Le montant total de la facture s'élève à plus de trois cents dollars canadiens."],
  ["Workout", "l'entraînement", "Je fais une séance d'entraînement de trente minutes à la maison tous les matins."],
  ["Environment", "l'environnement", "Il est de notre responsabilité de protéger l'environnement pour assurer un avenir meilleur aux prochaines générations de Canadiens."],
  ["Crowdfunding campaign", "la campagne de sociofinancement", "Notre campagne de sociofinancement a permis de récolter assez d'argent pour acheter de nouveaux uniformes."],
  ["Firefighter", "le pompier", "L'intervention rapide du pompier a permis d'éviter que l'incendie ne se propage aux bâtiments voisins."],
  ["Two-factor login", "l'authentification à deux facteurs", "Pour plus de sécurité, il est conseillé d'activer l'authentification à deux facteurs."],
  ["Shelter bed shortage", "le manque de lits d'hébergement", "Le manque de lits d'hébergement force certains refuges à refuser des personnes durant l'hiver."],
  ["To subscribe", "s'abonner", "Je vais m'abonner à ce magazine car ses articles sur la nature sont fascinants."],
  ["Neighborhood", "le quartier", "C'est un quartier résidentiel très calme avec beaucoup d'arbres matures."],
  ["Lawyer", "l'avocat", "L'avocat de la défense a présenté d'excellents arguments lors de sa plaidoirie finale devant jury."],
  ["Pay equity audit", "l'équité salariale", "La loi exige que les grandes entreprises maintiennent l'équité salariale entre les hommes et les femmes."],
  ["Symptom", "le symptôme", "Si vous présentez plus d'un symptôme grippal, il vaut mieux rester à la maison."],
  ["Health card", "la carte d'assurance maladie", "N'oubliez pas de présenter votre carte d'assurance maladie à la réception de la clinique."],
  ["Appointment book", "l'agenda", "Je dois consulter mon agenda avant de vous confirmer ma présence à cette réunion."],
  ["Disease", "la maladie", "La recherche progresse rapidement pour trouver un remède efficace contre cette maladie neurodégénérative rare chez les enfants."],
  ["Menu", "le menu", "Le menu de ce bistro change chaque saison selon les produits disponibles sur le marché."],
  ["Avalanche bulletin", "le bulletin d'avalanche", "Consultez toujours le bulletin d'avalanche avant de faire du ski hors-piste."],
  ["Fact-checking label", "la mention de vérification des faits", "Ce message sur Facebook s'est vu ajouter une mention de vérification des faits."],
  ["Indoor pollutant", "le polluant intérieur", "Un manque de ventilation favorise l'accumulation de plus d'un polluant intérieur."],
  ["Sign-language interpreter", "l'interprète en langue des signes", "Un interprète en langue des signes traduit les conférences de presse du gouvernement en direct."],
  ["Judge", "le juge", "Le juge a rendu un verdict de culpabilité après avoir entendu tous les témoins à charge."],
  ["Area", "la région", "La région de Montréal attire chaque année de nombreux étudiants internationaux venus poursuivre leurs études universitaires."],
  ["Single-parent household", "la famille monoparentale", "Gérer un budget serré est un défi de taille pour de nombreuses familles monoparentales."],
  ["Constraint", "la contrainte", "La principale contrainte de ce projet est le manque de budget disponible."],
  ["Maternity leave", "le congé de maternité", "Elle reviendra au bureau au printemps prochain après son congé de maternité."],
  ["Toll", "le péage", "Le paiement du péage sur cette autoroute se fait uniquement de façon électronique."],
  ["Newsletter signup", "l'inscription à l'infolettre", "L'inscription à l'infolettre vous permet de recevoir un résumé des nouvelles locales chaque vendredi."],
  ["DIY/repairs", "le bricolage", "Il passe ses fins de semaine à faire du bricolage dans le garage."],
  ["Luggage", "les bagages", "Nous avons dû payer des frais supplémentaires car nos bagages étaient trop lourds."],
  ["Challenge", "le défi", "Gérer cette équipe en période de crise a été un défi de taille."],
  ["Supermarket", "le supermarché", "Je dois m'arrêter au supermarché en rentrant du bureau pour acheter des légumes frais."],
  ["Flash flooding", "l'inondation éclair", "Une inondation éclair a forcé la fermeture de l'autoroute pendant plusieurs heures."],
  ["Community", "la communauté", "La communauté francophone de cette province minoritaire milite activement pour la défense de ses droits linguistiques fondamentaux."],
  ["Diagnosis", "le diagnostic", "Le spécialiste a confirmé le diagnostic après avoir analysé les résultats des prises de sang."],
  ["Agreement", "l'accord", "Un accord a finalement été conclu après de longues semaines de négociations ardues entre les parties."],
  ["Mandatory", "obligatoire", "Le port du casque protecteur est obligatoire sur tous les chantiers de construction de la province."],
  ["Painkiller", "l'analgésique", "Il prend un analgésique léger pour faire passer ses violents maux de tête."],
  ["Platform outage", "la panne de plateforme", "La panne de plateforme a empêché des milliers d'usagers de se connecter pendant des heures."],
  ["Prison reintegration program", "la réinsertion sociale", "Ce programme vise à faciliter la réinsertion sociale des détenus après leur libération."],
  ["Renovation", "la rénovation", "La rénovation de la cuisine a coûté beaucoup plus cher que prévu initialement."],
  ["Comparison", "la comparaison", "La comparaison entre les deux modèles de voitures montre que le plus récent consomme moins d'essence sur la route."],
  ["Citizen", "le citoyen", "Il a obtenu sa citoyenneté canadienne après avoir réussi l'examen de citoyenneté avec brio."],
  ["Bus stop", "l'arrêt d'autobus", "Il y a toujours beaucoup de gens qui attendent à l'arrêt d'autobus sous la pluie."],
  ["Assessment", "l'évaluation", "L'évaluation de votre rendement aura lieu à la fin du mois prochain."],
  ["Approximately", "environ", "Le trajet en autobus prendra environ quarante minutes avec la circulation."],
  ["Speed limit", "la limite de vitesse", "La limite de vitesse a été abaissée près des zones scolaires pour des raisons de sécurité."],
  ["Lock", "la serrure", "La serrure de la porte principale est un peu capricieuse en hiver à cause du gel."],
  ["From now on", "désormais", "Désormais, toutes les réunions d'équipe se tiendront en mode hybride."],
  ["Bullying prevention week", "l'intimidation", "L'école a mis en place de nouvelles mesures strictes pour contrer l'intimidation dans la cour de récréation."],
  ["Mortgage", "l'hypothèque", "La banque a finalement approuvé notre demande d'hypothèque pour le condo."],
  ["Transfer", "le virement", "Je vous ferai un virement Interac pour rembourser ma part du repas."],
  ["Debit card", "la carte de débit", "Le commerçant n'accepte que la carte de débit ou l'argent comptant."],
  ["Election", "l'élection", "La prochaine élection provinciale se tiendra au mois d'octobre de cette année."],
  ["Extracurricular", "parascolaire", "Il participe à plusieurs activités parascolaires, dont le club de théâtre de l'école."],
  ["Graduation", "la collation des grades", "Toute la famille assistera à sa collation des grades prévue au mois de juin."],
  ["Phishing email", "le courriel d'hameçonnage", "Faites attention à ne pas cliquer sur le lien dans ce courriel d'hameçonnage."],
  ["Supply shortage delay", "les retards d'approvisionnement", "Les travaux ont été retardés à cause des problèmes fréquents de retards d'approvisionnement."],
  ["Balance", "l'équilibre", "Il est parfois difficile de trouver le bon équilibre entre la vie professionnelle et la vie personnelle."],
  ["To apologize", "s'excuser", "Il a dû s'excuser auprès de ses collègues pour son retard à la réunion."],
  ["Main course", "le plat principal", "Pour le plat principal, je prendrai le filet de saumon grillé avec des légumes de saison."],
  ["Continuing education leave", "le congé de formation", "J'ai demandé un congé de formation pour terminer ma maîtrise en administration."],
  ["City council", "le conseil municipal", "Le conseil municipal se réunit tous les premiers mardis du mois à l'hôtel de ville."],
  ["Mortgage payment", "le paiement hypothécaire", "Notre paiement hypothécaire a considérablement augmenté depuis la hausse des taux."],
  ["Promotion", "la promotion", "Ses efforts ont été récompensés par une belle promotion le mois dernier."],
  ["Fortunately", "heureusement", "Heureusement, personne n'a été blessé lors de l'accident impliquant trois véhicules sur l'autoroute enneigée hier soir."],
  ["Taxes", "les taxes", "Le prix affiché n'inclut pas les taxes de vente provinciale et fédérale."],
  ["Urban tree planting", "la plantation urbaine d'arbres", "La ville finance la plantation urbaine d'arbres pour réduire les îlots de chaleur."],
  ["Opportunity", "l'opportunité", "Ce stage représente une excellente opportunité de lancer ma carrière professionnelle."],
  ["Metadata verification", "la vérification des métadonnées", "La vérification des métadonnées de cette photo prouve qu'elle n'a pas été prise hier."],
  ["Invoice payment term", "le délai de paiement", "Le délai de paiement de cette facture est fixé à trente jours après sa réception."],
  ["Plumbing", "la plomberie", "Nous avons dû engager un expert en plomberie pour réparer la fuite d'eau."],
  ["Dismissal", "le renvoi", "Le renvoi de trois employés a causé un certain malaise dans le département."],
  ["Conclusion", "la conclusion", "La conclusion du rapport d'enquête recommande de mettre à jour les protocoles de sécurité du laboratoire de recherche."],
  ["Community health center", "le CLSC", "Vous pouvez vous rendre au CLSC pour faire vacciner votre bébé."],
  ["Sustainable", "durable", "Le développement durable doit être au cœur des décisions économiques du gouvernement pour les années futures."],
  ["Fine particulate pollution", "la pollution aux particules fines", "La pollution aux particules fines affecte particulièrement les personnes souffrant d'asthme."],
  ["Passport", "le passeport", "N'oubliez pas de vérifier la date d'expiration de votre passeport avant de réserver votre voyage."],
  ["Context", "le contexte", "Il faut absolument replacer cette citation dans son contexte original pour bien en comprendre tout le sens profond."],
  ["Receipt", "le reçu", "Gardez bien votre reçu au cas où vous voudriez retourner ou échanger cet article."],
  ["Gentrification pressure", "l'embourgeoisement", "L'embourgeoisement du quartier fait augmenter le prix des loyers de manière fulgurante."],
  ["Neighbor", "le voisin", "Mon voisin m'a gentiment aidé à pelleter mon entrée ce matin."],
  ["Discussion", "la discussion", "La discussion a été très animée, mais les membres du comité ont finalement réussi à s'entendre sur un plan d'action commun."],
  ["Possibly", "éventuellement", "Nous pourrions éventuellement déménager dans une plus grande maison l'année prochaine."],
  ["Savings", "les économies", "Il est important de placer ses économies dans un compte avantageux."],
  ["To ban", "interdire", "Le règlement municipal vient d'interdire l'utilisation des sacs en plastique à usage unique dans les commerces."],
  ["Electric vehicle", "le véhicule électrique", "Les ventes de véhicules électriques ont bondi grâce aux subventions gouvernementales généreuses."],
  ["To cancel", "annuler", "Nous avons dû annuler notre réservation à l'hôtel en raison d'un imprévu de dernière minute."],
  ["Advantage", "l'avantage", "Travailler de la maison présente un avantage indéniable pour concilier le travail et la famille."],
  ["Efficient", "efficace", "Cette nouvelle méthode de travail est beaucoup plus efficace qu'avant."],
  ["Trend", "la tendance", "La tendance actuelle du marché est d'acheter des produits fabriqués localement."],
  ["Awareness", "la sensibilisation", "La campagne de sensibilisation vise à réduire le gaspillage alimentaire dans les écoles."],
  ["Rural depopulation", "l'exode rural", "L'exode rural menace la survie de nombreux petits villages de l'est de la province."],
  ["Disability inclusion plan", "l'inclusion des personnes handicapées", "L'inclusion des personnes handicapées en milieu de travail bénéficie à l'ensemble de la société."],
  ["Stamp", "le timbre", "Le prix d'un timbre pour envoyer une lettre au pays a encore augmenté récemment."],
  ["Tenant strike", "la grève des loyers", "Des locataires en colère ont organisé une grève des loyers pour protester contre les hausses abusives."],
  ["Unemployment", "le chômage", "Le taux de chômage a légèrement baissé dans notre région ce mois-ci."],
  ["Night shift premium", "la prime de nuit", "Les infirmières reçoivent une prime de nuit pour les encourager à prendre ces quarts difficiles."],
  ["Train station", "la gare", "Le train pour Ottawa quittera la gare centrale d'ici exactement une demi-heure."],
  ["Effect", "l'effet", "L'effet des changements climatiques se fait déjà ressentir sur l'écosystème fragile de la toundra arctique canadienne."],
  ["Noise", "le bruit", "Le bruit des travaux dans la rue voisine commence vraiment à me déranger."],
  ["Endangered species", "l'espèce menacée", "Le caribou forestier est malheureusement considéré comme une espèce menacée d'extinction au Canada."],
  ["Reservation", "la réservation", "Il vaut mieux faire une réservation si vous voulez manger ici un samedi soir."],
  ["Refund", "le remboursement", "La politique du magasin n'accorde aucun remboursement sur les sous-vêtements achetés en solde."],
  ["Salary negotiation", "la négociation salariale", "La négociation salariale s'est bien déroulée et j'ai obtenu une augmentation intéressante."],
  ["Obviously", "évidemment", "Il est évidemment plus facile d'apprendre une langue en la pratiquant avec des locuteurs natifs tous les jours."],
  ["Solar panel", "le panneau solaire", "De nombreux citoyens installent un panneau solaire sur leur toit pour économiser sur leur facture."],
  ["Shop steward", "le délégué syndical", "Si vous avez un problème avec la direction, vous devriez en parler à votre délégué syndical."],
  ["Mental health", "la santé mentale", "Il est tout aussi important de prendre soin de sa santé mentale que de sa santé physique."],
  ["Airport", "l'aéroport", "Nous devons arriver à l'aéroport au moins trois heures avant notre vol international."],
  ["Traffic jam", "le bouchon de circulation", "Il y avait un énorme bouchon de circulation sur le pont Champlain ce matin."],
  ["Feedback", "la rétroaction", "La rétroaction constructive du superviseur m'a permis d'améliorer mon travail."],
  ["Campus", "le campus", "Le campus universitaire est très vaste et compte de nombreuses résidences pour étudiants."],
  ["Subway", "le métro", "La nouvelle ligne de métro reliera l'aéroport directement au centre-ville d'ici quelques années."],
  ["Strike mandate vote", "le vote de grève", "Les enseignants ont approuvé le vote de grève à 95 % lors de l'assemblée générale."],
  ["Closed captioning", "le sous-titrage codé", "Le sous-titrage codé est disponible pour toutes nos émissions en direct."],
  ["Description", "la description", "La description de poste indique que le candidat doit maîtriser le français et l'anglais parlés et écrits parfaitement."],
  ["Social mobility", "la mobilité sociale", "L'accès à une éducation de qualité est le meilleur moteur de la mobilité sociale."],
  ["Echo chamber effect", "la chambre d'écho", "Les algorithmes des réseaux sociaux ont tendance à créer un effet de chambre d'écho."],
  ["Restaurant", "le restaurant", "Nous avons découvert un excellent restaurant italien dans notre nouveau quartier hier soir."],
  ["Housework", "le ménage", "Nous nous partageons les tâches de ménage chaque fin de semaine."],
  ["Candidate", "le candidat", "Le candidat de notre circonscription a fait du porte-à-porte pour rencontrer les citoyens du quartier."],
  ["Figure", "le chiffre", "Le chiffre d'affaires de la compagnie a atteint un niveau record lors du dernier trimestre de l'année financière en cours."],
  ["Target", "la cible", "La cible de vente pour le dernier trimestre n'a malheureusement pas été atteinte."],
  ["Victim support service", "l'aide aux victimes", "Le centre offre divers services d'aide aux victimes d'actes criminels sans aucun frais."],
  ["Capacity", "la capacité", "La capacité de la salle de spectacle a été réduite pour respecter les nouvelles normes de sécurité incendie."],
  ["Side effect", "l'effet secondaire", "La fatigue extrême est un effet secondaire fréquent de ce type de médicament."],
  ["Blended family", "la famille recomposée", "L'organisation des vacances est parfois complexe au sein d'une grande famille recomposée."],
  ["Part-time job", "le travail à temps partiel", "Ce travail à temps partiel me permet de continuer mes études universitaires."],
  ["Advantageous", "avantageux", "Ce forfait téléphonique est plus avantageux si vous voyagez souvent à l'étranger."],
  ["Yard/garden", "la cour", "Les enfants adorent jouer dans la cour arrière pendant la saison estivale."],
  ["Warning", "l'avertissement", "L'avertissement de neige abondante est maintenu pour toute la région jusqu'à demain midi."],
  ["Background", "le parcours", "Son parcours professionnel impressionnant lui a permis de décrocher ce poste de haute direction sans grande difficulté."],
  ["Biodiversity", "la biodiversité", "La protection des zones humides est essentielle pour maintenir la biodiversité de notre région."],
  ["Paywalled article", "l'article payant", "Malheureusement, c'est un article payant et je n'ai pas d'abonnement au journal."],
  ["Fine", "la contravention", "J'ai reçu une contravention car j'étais stationné devant une borne-fontaine."],
  ["Social housing waitlist", "la liste d'attente pour un logement social", "Il faut parfois patienter plusieurs années sur la liste d'attente pour un logement social abordable."],
  ["Podcast transcript", "la transcription du balado", "Vous pouvez lire la transcription du balado si vous n'avez pas le temps de l'écouter."],
  ["Composting", "le compostage", "La municipalité fournit désormais un bac brun pour encourager le compostage des résidus alimentaires."],
  ["Pride parade route", "le défilé de la Fierté", "Des dizaines de milliers de personnes ont participé au défilé de la Fierté sous un soleil radieux."],
  ["Retirement", "la retraite", "Elle prendra une retraite bien méritée après trente ans de service."],
  ["Push notification alert", "la notification push", "J'ai désactivé les notifications push sur mon téléphone car je recevais trop de messages inutiles."],
  ["To avoid", "éviter", "Il faut absolument éviter de circuler sur le pont pendant l'heure de pointe de l'après-midi."],
  ["Library", "la bibliothèque", "La bibliothèque municipale offre un environnement calme pour réviser ses leçons."],
  ["Clear-cut moratorium", "le moratoire sur la coupe à blanc", "Les écologistes réclament un moratoire sur la coupe à blanc dans la région."],
  ["Importance", "l'importance", "L'importance de bien s'hydrater pendant les périodes de canicule est rappelée quotidiennement par la Direction de la santé publique de la province."],
  ["Parental leave extension", "le congé parental", "La province offre un des régimes de congé parental les plus généreux au pays."],
  ["Secularism debate", "le débat sur la laïcité", "Le projet de loi a relancé le débat sur la laïcité de l'État dans l'espace public."],
  ["Cash register", "la caisse", "Il y avait une longue file d'attente à la caisse du magasin lors des soldes."],
  ["Water table decline", "la baisse de la nappe phréatique", "La baisse de la nappe phréatique inquiète les agriculteurs de la région."],
  ["Boarding pass", "la carte d'embarquement", "N'oubliez pas d'imprimer votre carte d'embarquement ou de l'enregistrer sur votre téléphone intelligent."],
  ["Application", "la demande", "Votre demande d'emploi a été reçue et sera évaluée par notre service des ressources humaines."],
  ["Community guidelines", "les règles de la communauté", "Ce commentaire agressif a été supprimé car il enfreignait les règles de la communauté."],
  ["Compromise", "le compromis", "Les deux parties ont dû faire un compromis pour signer l'entente collective."],
  ["To volunteer", "faire du bénévolat", "Elle a décidé de faire du bénévolat dans un centre d'hébergement pour personnes âgées le dimanche."],
  ["Vegetarian", "végétarien", "Le menu propose plusieurs excellentes options de repas pour quelqu'un de végétarien."],
  ["School dropout prevention", "le décrochage scolaire", "Les programmes de tutorat parascolaires sont très efficaces pour lutter contre le décrochage scolaire."],
  ["Feature", "la caractéristique", "La caractéristique principale de ce nouveau logiciel de montage vidéo est sa très grande simplicité d'utilisation pour les débutants."],
  ["Scholarship", "la bourse d'études", "Ses excellentes notes lui ont permis d'obtenir une bourse d'études très généreuse."],
  ["Customer complaint escalation", "l'escalade d'une plainte", "J'ai dû demander l'escalade de ma plainte à un superviseur car l'agent ne pouvait pas m'aider."],
  ["Optional", "facultatif", "La participation à l'activité parascolaire de vendredi après-midi est totalement facultative pour les élèves de l'école."],
  ["Birth rate decline", "la baisse de la natalité", "La baisse de la natalité explique en partie le manque de main-d'œuvre dans certains secteurs."],
  ["Public transport", "le transport en commun", "Utiliser le transport en commun au lieu de sa voiture aide à réduire la pollution atmosphérique."],
  ["Remote work", "le télétravail", "Le télétravail nous permet de sauver beaucoup de temps dans les transports en commun."],
  ["Ransomware attack", "l'attaque par rançongiciel", "L'hôpital a été victime d'une grave attaque par rançongiciel la nuit dernière."],
  ["To thank", "remercier", "Je tiens à vous remercier pour votre aide précieuse dans ce dossier."],
  ["To improve", "améliorer", "La ville prévoit d'améliorer le déneigement des trottoirs dans les quartiers résidentiels cet hiver."],
  ["Property tax", "la taxe foncière", "La taxe foncière de la municipalité augmentera de deux pour cent l'année prochaine."],
  ["Ingredient", "l'ingrédient", "Il me manque un ingrédient important pour préparer le repas de ce soir."],
  ["Difference", "la différence", "La principale différence entre ces deux forfaits téléphoniques réside dans la quantité de données mobiles offertes mensuellement."],
  ["Significantly", "considérablement", "Le coût de la vie a considérablement augmenté dans les grandes villes canadiennes."],
  ["Unfortunately", "malheureusement", "Malheureusement, le budget alloué à la culture sera réduit de dix pour cent lors du prochain exercice financier."],
  ["Recipe", "la recette", "Cette délicieuse recette de tarte aux pommes vient de ma grand-mère maternelle."],
  ["Form", "le formulaire", "Veuillez remplir ce formulaire en lettres moulées et le retourner à la réception avant votre rendez-vous avec le spécialiste de la santé."],
  ["Zero-waste target", "l'objectif zéro déchet", "Notre famille a adopté l'objectif zéro déchet depuis près de deux ans."],
  ["Panel interview", "l'entrevue devant jury", "J'étais un peu nerveux lors de l'entrevue devant jury, mais je crois avoir bien répondu aux questions."],
  ["Key", "la clé", "J'ai perdu la clé de mon appartement, je vais devoir appeler un serrurier d'urgence."],
  ["Truth and reconciliation event", "la vérité et réconciliation", "Le gouvernement a promis de mettre en œuvre les appels à l'action pour la vérité et réconciliation."],
  ["Rush hour", "l'heure de pointe", "Je préfère prendre le métro plutôt que de conduire pendant l'heure de pointe."],
  ["Initiative", "l'initiative", "Cette belle initiative citoyenne a permis de nettoyer les berges de la rivière locale."],
  ["Family doctor", "le médecin de famille", "C'est difficile de trouver un médecin de famille qui prend de nouveaux patients."],
  ["Hot-desking policy", "le bureau partagé", "Avec le système de bureau partagé, je dois réserver mon espace avant d'arriver au travail."],
  ["Debt", "la dette", "Il espère rembourser sa dette d'études avant l'âge de trente ans."],
  ["To support", "soutenir", "Le gouvernement promet de soutenir les petites entreprises affectées par la fermeture des routes cet été."],
  ["Tenant", "le locataire", "Les droits du locataire sont protégés par le Tribunal administratif du logement."],
  ["Flight", "le vol", "Notre vol de retour a été annulé à cause d'une forte tempête de neige."],
  ["Integration", "l'intégration", "Les cours de francisation facilitent l'intégration des nouveaux arrivants sur le marché du travail."],
  ["Cookie consent banner", "la bannière de consentement aux témoins", "Chaque fois que je visite un nouveau site, je dois fermer la bannière de consentement aux témoins."],
  ["Onboarding buddy", "le parrain d'intégration", "Mon parrain d'intégration m'a fait visiter les bureaux et m'a présenté au reste de l'équipe."],
  ["Urban sprawl", "l'étalement urbain", "L'étalement urbain cause de sérieux problèmes de congestion sur les routes de banlieue."],
  ["Recycling", "le recyclage", "Le taux de recyclage a considérablement augmenté depuis l'installation des nouveaux bacs bleus."],
  ["Collective bargaining round", "la ronde de négociation collective", "La nouvelle ronde de négociation collective entre le syndicat et l'employeur débute aujourd'hui."],
  ["Bicycle lane", "la piste cyclable", "La ville aménage une nouvelle piste cyclable protégée le long de la rue principale."],
  ["Budget", "le budget", "Nous devons revoir notre budget mensuel pour réduire nos dépenses superflues."],
  ["Conflict-of-interest disclosure", "la déclaration de conflit d'intérêts", "Chaque employé doit signer une déclaration de conflit d'intérêts au moment de l'embauche."],
  ["Diet", "le régime alimentaire", "Son régime alimentaire est très strict car elle souffre de plusieurs allergies sévères."],
  ["Background screening", "la vérification des antécédents", "L'offre d'emploi est conditionnelle à une vérification des antécédents judiciaires."],
  ["Income tax", "les impôts", "Cette année, je dois payer des impôts supplémentaires sur mes revenus de pigiste."],
  ["Return-to-work plan", "le plan de retour au travail", "Son médecin a préparé un plan de retour au travail progressif après son congé de maladie."],
  ["Voter", "l'électeur", "Chaque électeur doit présenter une pièce d'identité valide avec photo avant de pouvoir voter."],
  ["Cold snap", "la vague de froid", "Préparez-vous à une importante vague de froid la semaine prochaine."],
  ["Carpooling", "le covoiturage", "Le système de covoiturage que nous utilisons nous fait économiser beaucoup d'argent sur l'essence."],
  ["Concept", "le concept", "Le concept de ville intelligente repose sur l'utilisation des technologies pour améliorer la vie urbaine des citoyens."],
  ["Heatwave warning", "l'alerte canicule", "Les autorités ont lancé une alerte canicule pour le sud du Québec ce week-end."],
  ["Pharmacy", "la pharmacie", "Je dois passer à la pharmacie du quartier pour renouveler ma prescription de pilules."],
  ["Commute", "le trajet domicile-travail", "Son trajet domicile-travail prend moins de vingt minutes depuis qu'elle a déménagé."],
  ["Workspace", "l'espace de travail", "Je trouve que mon nouvel espace de travail est beaucoup plus lumineux et agréable."],
  ["Dog park etiquette", "le parc à chiens", "Il est important de ramasser les besoins de votre animal lorsque vous visitez le parc à chiens."],
  ["Sick leave", "le congé de maladie", "J'ai dû prendre un congé de maladie car j'avais une forte fièvre."],
  ["Experience", "l'expérience", "Son expérience dans le domaine du commerce de détail lui sera très utile pour gérer cette nouvelle boutique du centre-ville."],
  ["Microwave", "le four à micro-ondes", "Je réchauffe souvent mes restes de repas au four à micro-ondes pour aller plus vite."],
  ["Disappointing", "décevant", "Le service au restaurant hier soir était malheureusement très décevant."],
  ["Basement", "le sous-sol", "Ils ont aménagé une grande salle familiale dans le sous-sol de la résidence."],
  ["Convenience store", "le dépanneur", "Je vais juste faire un saut au dépanneur pour acheter du lait."],
  ["Live broadcast feed", "le flux en direct", "Vous pouvez suivre la conférence du premier ministre grâce au flux en direct sur le site Web."],
  ["Interest", "l'intérêt", "L'intérêt pour l'achat local a connu une forte croissance depuis le début de la pandémie et les problèmes d'approvisionnement mondiaux qui ont suivi."],
  ["Frequently", "fréquemment", "Cette question revient très fréquemment lors des examens oraux pour l'évaluation des compétences linguistiques des candidats."],
  ["Homelessness count", "le dénombrement des personnes itinérantes", "Le dernier dénombrement des personnes itinérantes révèle une hausse inquiétante au centre-ville."],
  ["Effort", "l'effort", "L'effort collectif de tous les employés a permis de terminer le projet deux semaines avant la date prévue initialement."],
  ["Screen-time limit", "la limite de temps d'écran", "Nous avons instauré une limite de temps d'écran pour nos enfants la semaine."],
  ["Eviction", "l'éviction", "L'avis d'éviction doit respecter plusieurs conditions strictes prévues par la loi."],
  ["Down payment", "la mise de fonds", "Ils ont réussi à économiser une mise de fonds suffisante pour acheter une maison."],
  ["Consumer rights", "les droits des consommateurs", "L'Office de la protection du consommateur veille au respect des droits des consommateurs."],
  ["To manage", "gérer", "Il n'est pas toujours facile de bien gérer son temps quand on étudie à temps plein."],
  ["Real estate agent", "l'agent immobilier", "L'agent immobilier nous a fait visiter cinq propriétés différentes samedi dernier."],
  ["Accommodation request", "la demande d'accommodement", "L'employeur doit traiter rapidement votre demande d'accommodement liée à votre handicap."],
  ["Viral misinformation", "la désinformation virale", "Il est difficile de freiner la désinformation virale sur les médias sociaux."],
  ["Benefit", "le bénéfice", "Le bénéfice net de la compagnie a augmenté de quinze pour cent au cours de la dernière année financière."],
  ["Standard", "la norme", "Les produits doivent respecter une norme de qualité très stricte avant d'être vendus."],
  ["Credit card", "la carte de crédit", "Ma carte de crédit a été bloquée après un achat inhabituel."],
  ["Community fridge", "le frigo communautaire", "Le frigo communautaire du quartier permet aux résidents de partager de la nourriture gratuitement."],
  ["Police oversight board", "la surveillance policière", "Un comité indépendant est désormais chargé de la surveillance policière dans la municipalité."],
  ["Senior isolation program", "l'isolement des aînés", "La pandémie a malheureusement aggravé le problème de l'isolement des aînés dans notre communauté."],
  ["Job interview", "l'entrevue d'embauche", "Préparez-vous bien pour votre entrevue d'embauche de demain matin."],
  ["Air conditioning", "la climatisation", "La climatisation est presque indispensable lors des journées chaudes et humides de juillet."],
  ["Trade", "le métier", "L'école offre d'excellentes formations professionnelles pour apprendre un métier manuel."],
  ["Independent outlet", "le média indépendant", "Je préfère m'informer auprès d'un média indépendant plutôt que par les journaux traditionnels."],
  ["To negotiate", "négocier", "C'est toujours une bonne idée de négocier son salaire lors de l'embauche."],
  ["Landlord", "le propriétaire", "Notre propriétaire a rapidement fait réparer le chauffage quand il est tombé en panne."],
  ["Account", "le compte", "Je dois vérifier le solde de mon compte avant de faire cet achat important."],
  ["Breaking-news banner", "le bandeau d'actualité", "J'ai lu la nouvelle sur le bandeau d'actualité de la chaîne télévisée d'information en continu."],
  ["Producer take-back rule", "la responsabilité élargie du producteur", "Cette loi applique la responsabilité élargie du producteur pour le recyclage des appareils électroniques."],
  ["Reliable", "fiable", "Ce modèle de voiture est très fiable et nécessite peu de réparations selon les experts automobiles."],
  ["Living wage pledge", "le salaire viable", "De plus en plus d'employeurs s'engagent à offrir un salaire viable à leurs employés."],
  ["Wheelchair access ramp", "la rampe d'accès", "L'installation d'une rampe d'accès est obligatoire pour rendre le bâtiment accessible aux fauteuils roulants."],
  ["Package", "le colis", "Le livreur a laissé le colis sur la galerie devant la porte de la maison."],
  ["Seldom", "rarement", "Je prends très rarement le train pour me déplacer car les billets coûtent souvent très cher."],
  ["Fridge", "le réfrigérateur", "N'oublie pas de ranger le lait dans le réfrigérateur pour ne pas qu'il tourne."],
  ["Paramedic", "l'ambulancier", "Les deux ambulanciers sont arrivés sur les lieux de l'accident en moins de dix minutes."],
  ["Heating", "le chauffage", "Le coût du chauffage électrique est très élevé pendant les mois d'hiver les plus froids."],
  ["Tabloid press", "la presse à sensation", "La presse à sensation se concentre souvent sur la vie privée des célébrités."],
  ["Difficulty", "la difficulté", "L'étudiant éprouve de la difficulté à comprendre les concepts complexes enseignés dans ce cours de mathématiques avancées."],
  ["Greenhouse gas", "les gaz à effet de serre", "Le gouvernement veut réduire les émissions de gaz à effet de serre du secteur industriel."],
  ["Affordable", "abordable", "Le manque de logements locatifs abordables est un problème majeur dans plusieurs grandes villes du pays."],
  ["Cégep", "le cégep", "Après le secondaire, ma fille souhaite poursuivre ses études au cégep."],
  ["Update", "la mise à jour", "La mise à jour du système informatique prendra environ deux heures ce soir."],
  ["Accessible", "accessible", "Ce nouveau parc public est entièrement accessible aux personnes se déplaçant en fauteuil roulant motorisé."],
  ["Function", "la fonction", "La fonction principale de cet appareil est de purifier l'air ambiant dans les espaces clos et mal ventilés des vieux bâtiments."],
  ["Exam", "l'examen", "Les étudiants sont très stressés à l'approche de la session d'examens finaux."],
  ["Termination package", "l'indemnité de départ", "L'entreprise lui a offert une généreuse indemnité de départ après ses dix ans de service."],
  ["Wildfire haze", "la brume d'incendie de forêt", "La qualité de l'air est mauvaise à cause de la brume d'incendie de forêt ce matin."],
  ["Block party permit", "la fête de quartier", "La rue sera fermée à la circulation dimanche prochain pour notre fête de quartier annuelle."],
  ["Argument", "l'argument", "L'argument principal du candidat repose sur la création de nouveaux emplois payants dans notre municipalité."],
  ["To complain", "se plaindre", "Les résidents n'arrêtent pas de se plaindre du manque de stationnement."],
  ["Bookstore", "la librairie", "J'ai passé des heures dans la librairie à chercher le dernier roman de cet auteur."],
  ["Shopping cart", "le panier d'épicerie", "N'oubliez pas de ramener votre panier d'épicerie à l'endroit désigné sur le stationnement."],
  ["Deforestation", "la déforestation", "La déforestation massive entraîne la destruction de l'habitat naturel de plusieurs animaux sauvages."],
  ["Non-compete clause", "la clause de non-concurrence", "Il n'a pas pu travailler pour le concurrent à cause de sa clause de non-concurrence."],
  ["Information", "l'information", "L'information circulait rapidement sur les médias sociaux, ce qui a causé un mouvement de panique injustifié au sein de la population locale inquiète."],
  ["Condition", "la condition", "La principale condition pour obtenir cette subvention est de créer au moins cinq emplois locaux à temps plein."],
  ["Surgery", "la chirurgie", "Sa chirurgie au genou s'est bien déroulée et il pourra rentrer chez lui demain."],
  ["Ageing population", "le vieillissement de la population", "Le vieillissement de la population met une pression importante sur notre système de santé public."],
  ["Written warning", "l'avertissement écrit", "Après trois retards injustifiés, elle a reçu un avertissement écrit de la part des ressources humaines."],
  ["Student loan", "le prêt étudiant", "Il devra rembourser son prêt étudiant sur une période de dix ans."],
  ["Rent", "le loyer", "Le coût du loyer représente souvent la plus grande dépense mensuelle d'un ménage."],
  ["Inclusive hiring practice", "l'embauche inclusive", "Notre organisation promeut des pratiques d'embauche inclusive pour diversifier nos équipes."],
  ["Balcony", "le balcon", "Nous adorons prendre notre café sur le balcon pendant la belle saison."],
  ["Freelance contract", "le contrat de pigiste", "J'ai décroché un excellent contrat de pigiste pour concevoir le nouveau site Web du festival."],
  ["Anti-racism training", "la formation sur l'antiracisme", "Tous les employés de la fonction publique devront suivre une formation sur l'antiracisme obligatoire cette année."]
,
  ["Issue", "l'enjeu", "Cet enjeu politique divisera sans doute les électeurs lors du prochain scrutin provincial."],
  ["Knowledge", "les connaissances", "Les connaissances techniques requises pour ce poste sont très spécifiques et complexes."],
  ["Lack", "le manque", "Le manque de personnel infirmier force la fermeture partielle de l'urgence de notre hôpital local de banlieue."],
  ["Level", "le niveau", "Le niveau d'eau du fleuve Saint-Laurent est exceptionnellement bas pour cette période précise de l'année estivale."],
  ["Majority", "la majorité", "La majorité des résidents du quartier s'opposent fermement à la construction de cette nouvelle tour à condos luxueux."],
  ["Market", "le marché", "Le marché de l'immobilier connaît enfin un léger ralentissement après plusieurs années de surchauffe fulgurante et inquiétante."],
  ["Material", "le matériel", "Le matériel informatique de l'école primaire sera entièrement renouvelé avant la rentrée scolaire d'automne prochain."],
  ["Matter", "le sujet", "Nous devons absolument discuter de ce sujet important lors de notre prochaine réunion d'équipe mensuelle du département."],
  ["Meaning", "la signification", "La signification de cette ancienne coutume locale s'est malheureusement perdue au fil des nombreuses générations passées."],
  ["Measure", "la mesure", "Cette nouvelle mesure de sécurité routière vise principalement à réduire le nombre d'accidents mortels chez les jeunes conducteurs inexpérimentés."],
  ["Method", "la méthode", "La méthode d'enseignement de ce professeur d'histoire est très originale et captive l'attention de tous ses élèves universitaires."],
  ["Model", "le modèle", "Le modèle économique actuel basé sur la consommation à outrance n'est plus viable à long terme selon ces experts environnementaux réputés."],
  ["Movement", "le mouvement", "Le mouvement de grève des travailleurs du secteur public s'étendra bientôt à l'ensemble du territoire de la vaste province canadienne."],
  ["Need", "le besoin", "Le besoin de logements sociaux abordables est de plus en plus criant dans la grande région métropolitaine ces temps-ci."],
  ["Number", "le nombre", "Le nombre de cas d'infections respiratoires virales augmente de façon inquiétante depuis le retour du temps très froid hivernal."],
  ["Objective", "l'objectif", "L'objectif principal du gouvernement est d'atteindre la carboneutralité complète d'ici l'année deux mille cinquante au plus tard possible."],
  ["Opinion", "l'opinion", "L'opinion publique semble avoir complètement basculé en faveur du projet de loi controversé depuis la semaine dernière."],
  ["Option", "l'option", "La meilleure option serait de reporter l'événement extérieur à la semaine prochaine en raison des très mauvaises prévisions météorologiques annoncées."],
  ["Organization", "l'organisation", "L'organisation de ce grand festival de musique en plein air nécessite le travail dévoué de centaines de bénévoles motivés chaque année."],
  ["Part", "la partie", "Une grande partie du budget municipal provincial est consacrée à la réfection urgente des infrastructures routières vieillissantes de la métropole."],
  ["Performance", "le rendement", "Le rendement de notre équipe de vente régionale a largement dépassé toutes les attentes de la direction cette année encore."],
  ["Perspective", "la perspective", "Cette étude sociologique récente nous offre une perspective tout à fait nouvelle sur les problèmes d'intégration des immigrants récents."],
  ["Phase", "la phase", "La première phase des travaux de construction du nouvel hôpital pédiatrique devrait enfin s'achever au début du printemps prochain."],
  ["Plan", "le plan", "Le plan d'urbanisme de la municipalité favorise dorénavant le développement de quartiers résidentiels beaucoup plus denses et écologiques."],
  ["Policy", "la politique", "La nouvelle politique de l'entreprise permet désormais à tous les employés de faire du télétravail trois jours par semaine."],
  ["Position", "le poste", "Ce poste de cadre supérieur exige une excellente maîtrise du français et de l'anglais parlés et écrits au quotidien."],
  ["Possibility", "la possibilité", "Il y a une forte possibilité que les écoles de la région soient fermées demain en raison de la tempête hivernale annoncée."],
  ["Practice", "la pratique", "La pratique régulière d'une activité physique intense est essentielle pour maintenir une bonne santé cardiovasculaire à long terme."],
  ["Pressure", "la pression", "La pression exercée par les groupes écologistes a finalement forcé le gouvernement provincial à reculer sur ce dossier épineux."],
  ["Price", "le prix", "Le prix de l'essence à la pompe a encore bondi de façon spectaculaire juste avant le long congé férié du mois de mai."],
  ["Principle", "le principe", "Le principe de précaution devrait toujours s'appliquer lorsqu'il s'agit d'approuver de nouveaux produits chimiques industriels potentiellement dangereux."],
  ["Problem", "le problème", "Le problème de pénurie de places en garderie subventionnée cause de nombreux maux de tête aux jeunes parents de la région."],
  ["Process", "le processus", "Le processus d'embauche gouvernemental peut parfois prendre plusieurs mois avant d'aboutir à une véritable offre d'emploi concrète."],
  ["Product", "le produit", "Ce produit de nettoyage écologique est fabriqué au Québec à partir d'ingrédients entièrement naturels et non toxiques pour l'environnement."],
  ["Program", "le programme", "Le programme d'aide financière aux étudiants universitaires sera bonifié dès le début de la prochaine session d'automne académique."],
  ["Project", "le projet", "Le projet d'expansion de la ligne bleue du métro de Montréal suscite beaucoup d'enthousiasme chez les citoyens de l'Est."],
  ["Property", "la propriété", "La valeur de sa propriété immobilière a presque doublé depuis qu'il l'a achetée il y a seulement cinq petites années."],
  ["Purpose", "le but", "Le but principal de cet exercice de simulation est de préparer les employés à réagir adéquatement en cas d'incendie majeur."],
  ["Quality", "la qualité", "La qualité de l'air dans la région métropolitaine s'est grandement détériorée à cause des violents feux de forêt de cet été."],
  ["Question", "la question", "La question de l'identité nationale québécoise refait régulièrement surface lors des campagnes électorales provinciales au Canada francophone."],
  ["Range", "la gamme", "Cette compagnie technologique propose une vaste gamme d'appareils intelligents pour faciliter la gestion quotidienne de votre maison connectée."],
  ["Rate", "le taux", "Le taux directeur de la banque centrale canadienne a été maintenu intact pour le troisième mois consécutif afin de stabiliser l'économie."],
  ["Reason", "la raison", "La principale raison de son départ précipité de l'entreprise demeure encore inconnue de la plupart de ses anciens collègues."],
  ["Record", "le dossier", "Son dossier scolaire impeccable lui a permis d'être admise sans difficulté dans le programme contingenté de médecine universitaire."],
  ["Region", "la région", "L'économie de cette magnifique région éloignée repose presque exclusivement sur l'industrie forestière et minière traditionnelle."],
  ["Relationship", "la relation", "La relation complexe entre le gouvernement fédéral et les provinces canadiennes fait souvent les manchettes des journaux nationaux."],
  ["Report", "le rapport", "Le rapport du vérificateur général souligne de très nombreuses lacunes graves dans la gestion de ce programme d'aide gouvernemental."],
  ["Research", "la recherche", "La recherche scientifique démontre clairement les bienfaits considérables de la méditation quotidienne sur la réduction du stress au travail."],
  ["Resource", "la ressource", "L'eau potable est une ressource naturelle précieuse que nous devons apprendre à gérer beaucoup plus prudemment à l'avenir."],
  ["Response", "la réponse", "La réponse très rapide et efficace des services d'urgence locaux a permis de sauver plusieurs vies lors de cet accident tragique."],
  ["Result", "le résultat", "Le résultat final de l'élection municipale serrée ne sera connu que tard dans la nuit à cause du recomptage demandé par un candidat."],
  ["Review", "la révision", "La révision en profondeur des programmes scolaires primaires et secondaires suscite un vif débat chez les enseignants de la province."],
  ["Risk", "le risque", "Le risque d'inondation printanière est particulièrement élevé cette année en raison des précipitations de neige record cet hiver passé."],
  ["Role", "le rôle", "Le rôle des médias d'information indépendants est absolument crucial pour assurer le bon fonctionnement de notre démocratie moderne actuelle."],
  ["Rule", "la règle", "La règle d'or dans ce milieu de travail hautement compétitif est de toujours respecter les échéances serrées fixées par les clients exigeants."],
  ["Safety", "la sécurité", "La sécurité dans les transports en commun urbains est devenue une grande priorité pour la nouvelle administration municipale élue récemment."],
  ["Scale", "l'échelle", "Le projet sera d'abord testé à petite échelle locale avant d'être déployé à travers toute la province canadienne l'année prochaine."],
  ["Scene", "la scène", "Les enquêteurs de la police sont restés sur la scène de crime toute la nuit pour recueillir de précieux indices matériels."],
  ["Section", "la section", "La section nord de l'autoroute provinciale sera complètement fermée à la circulation routière pendant toute la durée de la fin de semaine."],
  ["Sector", "le secteur", "Le secteur manufacturier de la province connaît actuellement une forte relance économique inattendue depuis le début de la nouvelle année."],
  ["Security", "la sécurité", "La sécurité des données personnelles des utilisateurs est la préoccupation principale de notre grande entreprise de commerce électronique."],
  ["Sense", "le sens", "Ce nouveau règlement municipal complexe n'a aucun sens d'un point de vue purement logique et pratique selon de nombreux observateurs avisés."],
  ["Series", "la série", "La ville a organisé une série de consultations publiques estivales pour recueillir l'avis des citoyens sur ce projet de développement controversé."],
  ["Service", "le service", "Le service à la clientèle de cette compagnie de télécommunications laisse malheureusement beaucoup à désirer ces derniers temps incertains."],
  ["Situation", "la situation", "La situation économique précaire actuelle force de nombreuses familles vulnérables à recourir aux banques alimentaires locales pour survivre."],
  ["Skill", "la compétence", "La capacité à bien communiquer est une compétence transversale très recherchée par la plupart des employeurs du marché du travail actuel."],
  ["Society", "la société", "L'intégration réussie des nouveaux arrivants est absolument essentielle pour assurer l'harmonie sociale de notre société québécoise diversifiée."],
  ["Solution", "la solution", "La solution à ce problème complexe de congestion routière nécessitera des investissements massifs dans les infrastructures de transport en commun."],
  ["Source", "la source", "Le journaliste d'enquête a refusé catégoriquement de révéler l'identité de sa source confidentielle d'information au grand public."],
  ["Space", "l'espace", "L'aménagement de cet espace de travail partagé favorise grandement la collaboration informelle entre les différents départements de l'entreprise."],
  ["State", "l'état", "L'état déplorable de nos routes de banlieue fait l'objet de nombreuses plaintes répétées de la part des automobilistes de la région."],
  ["Statement", "la déclaration", "La déclaration du premier ministre provincial lors de son point de presse a semé une grande confusion parmi la population inquiète."],
];
