import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

export const TCF_LISTENING_P4: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "Clinique médicale",
    audioScript: "Bonjour. Je voudrais prendre un rendez-vous avec le docteur Bernard, s'il vous plaît. J'ai de la fièvre depuis deux jours. Est-ce qu'il y a une place demain matin ?",
    question: "Pourquoi le patient appelle-t-il ?",
    options: ["Pour annuler un rendez-vous.", "Pour renouveler une ordonnance.", "Pour avoir un rendez-vous à cause de fièvre.", "Pour demander les résultats d'analyse."],
    correctIndex: 2,
    explanation: "Le patient appelle pour prendre un rendez-vous car il a de la fièvre depuis deux jours.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Coiffeur",
    audioScript: "Bonjour madame. Je voudrais une coupe et un brushing. Pas trop court, juste une légère coupe aux pointes. Et si possible, une coloration légère.",
    question: "Qu'est-ce que la cliente ne veut pas ?",
    options: ["Un brushing.", "Une coloration.", "Une coupe très courte.", "Couper les pointes."],
    correctIndex: 2,
    explanation: "La cliente ne veut pas une coupe trop courte, seulement couper les pointes légèrement.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Accueil d'hôtel",
    audioScript: "Bienvenue à l'Hôtel Lumière. Le petit-déjeuner est servi de sept heures à dix heures dans la salle au rez-de-chaussée. La piscine est ouverte de neuf heures à vingt heures.",
    question: "À quelle heure ferme la piscine ?",
    options: ["À 18h.", "À 19h.", "À 20h.", "À 22h."],
    correctIndex: 2,
    explanation: "La piscine est ouverte jusqu'à 20h selon les informations de l'accueil de l'hôtel.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Supermarché",
    audioScript: "Attention clients. Aujourd'hui, tous les yaourts sont à moins cinquante pour cent. Et ce week-end, le rayon boulangerie propose du pain frais à partir de six heures du matin.",
    question: "Quelle est la promotion annoncée au supermarché ?",
    options: ["Les fromages à -50%.", "Les yaourts à -50%.", "Les fruits à -30%.", "Le pain gratuit le matin."],
    correctIndex: 1,
    explanation: "L'annonce informe que tous les yaourts sont à -50% aujourd'hui.",
  },
  {
    id: 5,
    level: "A1",
    topic: "Piscine municipale",
    audioScript: "La piscine municipale est fermée pour entretien les mardis et jeudis matin de six heures à neuf heures. Elle est ouverte tous les autres jours de sept heures à vingt et une heures.",
    question: "Quand la piscine est-elle fermée pour entretien ?",
    options: ["Le lundi et mercredi matin.", "Le mardi et jeudi matin.", "Le week-end.", "Tous les vendredis."],
    correctIndex: 1,
    explanation: "La piscine est fermée pour entretien les mardis et jeudis matin de 6h à 9h.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Voisinage",
    audioScript: "Bonjour voisin. Je pars en vacances deux semaines à partir de lundi. Est-ce que vous pouvez arroser mes plantes et récupérer mon courrier ? Je vous laisse ma clé. Merci beaucoup.",
    question: "Que demande le voisin de faire pendant ses vacances ?",
    options: ["Garder son chien.", "Arroser ses plantes et récupérer le courrier.", "Nettoyer son appartement.", "Surveiller ses enfants."],
    correctIndex: 1,
    explanation: "Le voisin demande d'arroser ses plantes et de récupérer son courrier pendant ses deux semaines de vacances.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Ciné-club",
    audioScript: "Le ciné-club universitaire projette ce vendredi le film Amélie Poulain à vingt heures. L'entrée est libre pour les étudiants sur présentation de la carte étudiant. Pour les autres, c'est cinq euros.",
    question: "Quelle est la condition pour que les étudiants entrent gratuitement ?",
    options: ["Réserver en avance.", "Présenter leur carte étudiant.", "Venir accompagnés.", "S'inscrire en ligne."],
    correctIndex: 1,
    explanation: "Les étudiants entrent gratuitement s'ils présentent leur carte étudiante.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Plombier",
    audioScript: "Bonjour monsieur. J'ai une fuite d'eau sous l'évier de la cuisine depuis hier soir. C'est assez urgent. Pouvez-vous passer aujourd'hui ou demain matin au plus tard ?",
    question: "Quel est le problème dans la cuisine ?",
    options: ["Le robinet ne fonctionne plus.", "La cuisinière est en panne.", "Il y a une fuite d'eau sous l'évier.", "Le chauffage ne marche pas."],
    correctIndex: 2,
    explanation: "Il y a une fuite d'eau sous l'évier de la cuisine depuis hier soir.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Enquête de satisfaction",
    audioScript: "Bonjour, je suis de la mairie. Nous réalisons une enquête de satisfaction sur les services publics de votre ville. Cela prend environ cinq minutes. Est-ce que vous avez le temps de répondre à quelques questions ?",
    question: "Combien de temps dure l'enquête de satisfaction ?",
    options: ["Deux minutes.", "Cinq minutes.", "Dix minutes.", "Un quart d'heure."],
    correctIndex: 1,
    explanation: "L'enquête de satisfaction prend environ cinq minutes selon l'enquêteur.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Jardinerie",
    audioScript: "Bienvenue à la Jardinerie du Soleil. Ce mois-ci, achetez deux plantes d'intérieur et obtenez la troisième à moitié prix. Nos horticulteurs sont disponibles pour vous conseiller de neuf heures à dix-huit heures.",
    question: "Quelle est la promotion proposée par la jardinerie ?",
    options: ["La troisième plante gratuite.", "La troisième plante à moitié prix.", "Deux plantes achetées, une offerte.", "Un pot acheté, un pot offert."],
    correctIndex: 1,
    explanation: "En achetant deux plantes d'intérieur, la troisième est à moitié prix.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Parentalité moderne",
    audioScript: "Le congé parental partagé, adopté dans plusieurs pays scandinaves, a montré des effets positifs sur l'égalité professionnelle. Lorsque les pères prennent activement leur congé, les mères reviennent plus tôt au travail et leur évolution de carrière est moins pénalisée. Ce modèle commence à influencer les politiques familiales dans d'autres pays européens.",
    question: "Quel est l'effet du congé parental partagé sur l'égalité professionnelle ?",
    options: ["Il augmente le chômage des pères.", "Il réduit le nombre d'enfants par famille.", "Il permet aux mères de revenir plus tôt au travail sans pénaliser leur carrière.", "Il augmente les dépenses publiques sans bénéfice mesurable."],
    correctIndex: 2,
    explanation: "Quand les pères prennent le congé, les mères reviennent plus tôt au travail avec moins d'impact sur leur carrière.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Micro-entreprise",
    audioScript: "Le statut d'auto-entrepreneur, rebaptisé micro-entrepreneur, permet de créer une activité très facilement. L'immatriculation se fait en ligne en quelques minutes. Les charges sociales sont calculées directement sur le chiffre d'affaires, avec un taux variant selon la nature de l'activité, entre douze et vingt-deux pour cent.",
    question: "Quel est l'avantage principal du statut de micro-entrepreneur ?",
    options: ["Aucune cotisation sociale requise.", "Les charges sont calculées sur le chiffre d'affaires, sans complexité.", "Il offre les mêmes droits qu'un salarié.", "Il permet d'embaucher des salariés sans charges."],
    correctIndex: 1,
    explanation: "Le micro-entrepreneur paye des charges calculées directement sur son chiffre d'affaires, ce qui simplifie la gestion.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Accessibilité",
    audioScript: "La loi sur l'accessibilité universelle impose aux établissements recevant du public de se mettre aux normes pour accueillir les personnes handicapées. Les ramps d'accès, les ascenseurs adaptés et la signalétique en braille sont parmi les aménagements obligatoires. Des sanctions financières s'appliquent aux établissements en infraction.",
    question: "Que prévoit la loi sur l'accessibilité universelle ?",
    options: ["Des avantages fiscaux pour les établissements conformes.", "Des normes obligatoires et des sanctions pour les établissements en infraction.", "La fermeture immédiate des établissements non conformes.", "Des subventions automatiques pour tous les travaux d'accessibilité."],
    correctIndex: 1,
    explanation: "La loi impose des normes d'accessibilité et prévoit des sanctions financières pour les établissements non conformes.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Alimentation locale",
    audioScript: "Les circuits courts alimentaires, qui réduisent le nombre d'intermédiaires entre producteur et consommateur, gagnent en popularité. Les marchés paysans, les AMAP et les épiceries coopératives permettent aux consommateurs d'acheter des produits frais et locaux tout en soutenant directement les agriculteurs de leur région.",
    question: "Que sont les circuits courts alimentaires ?",
    options: ["Des supermarchés spécialisés en produits bio.", "Des réseaux réduisant les intermédiaires entre producteur et consommateur.", "Des services de livraison de repas à domicile.", "Des restaurants proposant des menus locaux."],
    correctIndex: 1,
    explanation: "Les circuits courts limitent les intermédiaires, permettant des échanges directs entre agriculteurs et consommateurs.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Médias et information",
    audioScript: "Face à la prolifération des fausses informations sur les réseaux sociaux, plusieurs pays ont développé des programmes d'éducation aux médias dans les écoles. L'objectif est d'apprendre aux élèves à vérifier les sources, à distinguer information et opinion, et à détecter les manipulations visuelles et textuelles.",
    question: "Quel est l'objectif des programmes d'éducation aux médias à l'école ?",
    options: ["Encourager les élèves à créer des contenus numériques.", "Apprendre à vérifier les sources et à détecter les fausses informations.", "Limiter le temps passé sur les réseaux sociaux.", "Promouvoir la presse écrite plutôt que numérique."],
    correctIndex: 1,
    explanation: "Ces programmes visent à développer l'esprit critique face à l'information en apprenant à vérifier sources et contenus.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Sport et santé",
    audioScript: "L'Organisation mondiale de la santé recommande au moins cent cinquante minutes d'activité physique modérée par semaine pour les adultes. La sédentarité est désormais reconnue comme un facteur de risque majeur pour les maladies cardiovasculaires, le diabète et certains cancers. La marche rapide, le vélo ou la natation sont des activités facilement intégrables au quotidien.",
    question: "Combien de minutes d'activité physique l'OMS recommande-t-elle par semaine pour les adultes ?",
    options: ["100 minutes.", "120 minutes.", "150 minutes.", "200 minutes."],
    correctIndex: 2,
    explanation: "L'OMS recommande au moins 150 minutes d'activité physique modérée par semaine pour les adultes.",
  },
  {
    id: 17,
    level: "B2",
    topic: "Économie solidaire",
    audioScript: "L'économie sociale et solidaire regroupe des entreprises dont l'objectif n'est pas le profit maximal mais la réalisation d'un projet utile collectivement. Les coopératives, les mutuelles et les associations employeuses en font partie. Ce secteur représente environ dix pour cent de l'emploi en France et connaît une croissance régulière depuis la dernière crise financière.",
    question: "Qu'est-ce qui distingue les entreprises de l'économie sociale et solidaire ?",
    options: ["Elles ne paient pas d'impôts.", "Elles privilégient un projet collectif plutôt que le profit maximal.", "Elles n'embauchent que des personnes en difficulté.", "Elles sont toutes subventionnées par l'État."],
    correctIndex: 1,
    explanation: "L'ESS regroupe des structures dont l'objectif premier est l'utilité collective plutôt que la maximisation du profit.",
  },
  {
    id: 18,
    level: "B2",
    topic: "Vieillissement de la population",
    audioScript: "Le vieillissement démographique pose des défis majeurs aux systèmes de retraite et de santé. D'ici deux mille cinquante, le ratio actifs-retraités pourrait atteindre un pour un dans certains pays d'Europe. Des solutions sont discutées : immigration de travail, hausse de la productivité, ou ajustement des prestations sociales.",
    question: "Quel ratio actifs-retraités est prévu pour certains pays européens d'ici 2050 ?",
    options: ["Deux pour un.", "Un pour deux.", "Un pour un.", "Trois pour un."],
    correctIndex: 2,
    explanation: "Le ratio actifs-retraités pourrait atteindre 1 pour 1 dans certains pays d'Europe d'ici 2050.",
  },
  {
    id: 19,
    level: "B2",
    topic: "Langue des signes",
    audioScript: "La reconnaissance officielle de la langue des signes française dans les établissements scolaires a marqué une avancée importante pour la communauté sourde. Cependant, le manque d'enseignants formés et l'insuffisance des interprètes dans les services publics restent des obstacles à une inclusion réelle des personnes sourdes dans la société.",
    question: "Quel obstacle principal à l'inclusion des sourds est mentionné ?",
    options: ["Le refus des familles entendantes.", "Le manque d'enseignants formés et d'interprètes dans les services publics.", "Le coût trop élevé des aides techniques.", "L'absence de financement pour les associations de sourds."],
    correctIndex: 1,
    explanation: "Le manque d'enseignants formés et d'interprètes dans les services publics freine l'inclusion réelle des personnes sourdes.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Travail hybride",
    audioScript: "Le modèle hybride, combinant travail en présentiel et télétravail, s'est imposé comme la nouvelle norme dans de nombreuses entreprises. S'il améliore l'équilibre vie professionnelle-vie privée, il génère aussi des risques d'isolement, de surcharge informationnelle et d'effacement des frontières entre travail et vie personnelle.",
    question: "Quel risque le travail hybride peut-il engendrer selon ce reportage ?",
    options: ["Une baisse de productivité systématique.", "Un isolement social et un effacement des frontières vie privée-travail.", "Des conflits entre collègues en présentiel.", "Une augmentation des accidents du travail."],
    correctIndex: 1,
    explanation: "Le travail hybride peut entraîner isolement, surcharge informationnelle et effacement des frontières vie privée-travail.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Gestion de l'eau",
    audioScript: "La raréfaction de l'eau douce est l'un des défis environnementaux les plus urgents. L'agriculture consomme environ soixante-dix pour cent de l'eau douce mondiale. Des technologies comme le goutte-à-goutte ou la réutilisation des eaux usées traitées permettent de réduire significativement cette consommation sans compromettre les rendements.",
    question: "Quel pourcentage de l'eau douce mondiale l'agriculture consomme-t-elle ?",
    options: ["40%", "60%", "70%", "80%"],
    correctIndex: 2,
    explanation: "L'agriculture représente environ 70% de la consommation d'eau douce mondiale.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Patrimoine mondial",
    audioScript: "L'UNESCO a classé cette année quinze nouveaux sites au patrimoine mondial de l'humanité. Ce label protège les sites d'une valeur universelle exceptionnelle mais entraîne aussi des défis de gestion : la sur-fréquentation touristique peut paradoxalement menacer les sites qu'elle est censée valoriser.",
    question: "Quel paradoxe le classement UNESCO peut-il créer ?",
    options: ["Il interdit tout développement économique autour des sites.", "La sur-fréquentation touristique peut menacer les sites classés.", "Il crée des tensions entre pays voisins.", "Il rend les sites inaccessibles aux populations locales."],
    correctIndex: 1,
    explanation: "La sur-fréquentation touristique générée par le label UNESCO peut paradoxalement endommager les sites protégés.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Startup et innovation",
    audioScript: "L'écosystème des startups français, surnommé la French Tech, a produit plusieurs licornes valorisées à plus d'un milliard de dollars. Cependant, les entrepreneurs soulignent la difficulté à lever des fonds en Europe au-delà des premières étapes. Beaucoup choisissent de s'installer aux États-Unis ou en Asie pour accéder à des marchés de capitaux plus profonds.",
    question: "Quel défi principal les entrepreneurs de la French Tech rencontrent-ils ?",
    options: ["Le manque de talents techniques en France.", "La difficulté à lever des fonds importants en Europe.", "L'insuffisance des aides publiques à l'innovation.", "Les réglementations trop strictes sur les nouvelles technologies."],
    correctIndex: 1,
    explanation: "Les startups françaises peinent à lever des capitaux importants en Europe et doivent parfois s'installer à l'étranger.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Langue française en Afrique",
    audioScript: "Le français en Afrique subsaharienne n'est pas simplement la langue de l'ancienne puissance coloniale : c'est souvent la langue de la mobilité sociale, de l'administration et de la scolarisation. Des linguistes comme Alain Bentolila soulignent que la maîtrise du français ouvre des portes économiques dans les pays francophones africains, tout en questionnant la place des langues nationales dans l'éducation.",
    question: "Quel rôle joue le français dans les pays d'Afrique subsaharienne selon ce reportage ?",
    options: ["C'est uniquement un héritage colonial sans utilité pratique.", "C'est un outil de mobilité sociale, administrative et éducative.", "C'est une langue étrangère que peu de gens maîtrisent.", "C'est une langue concurrente aux langues nationales officielles."],
    correctIndex: 1,
    explanation: "En Afrique subsaharienne, le français est associé à la mobilité sociale, à l'administration et à la scolarisation.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Économie de la connaissance",
    audioScript: "Dans l'économie de la connaissance, le capital humain — éducation, compétences, capacité d'adaptation — est devenu le principal facteur de compétitivité. Les pays investissant massivement dans la recherche et l'enseignement supérieur tendent à mieux résister aux chocs économiques et à générer davantage d'innovations à forte valeur ajoutée.",
    question: "Qu'est-ce que le capital humain dans l'économie de la connaissance ?",
    options: ["Le nombre de travailleurs dans un pays.", "L'éducation, les compétences et la capacité d'adaptation des individus.", "Les ressources naturelles d'un territoire.", "Le stock de machines et d'équipements industriels."],
    correctIndex: 1,
    explanation: "Le capital humain englobe l'éducation, les compétences et la capacité d'adaptation, principaux moteurs de la compétitivité.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    topic: "Linguistique — relativismedu langage",
    audioScript: "L'hypothèse de Sapir-Whorf, dans sa version forte, postule que la langue que nous parlons détermine notre façon de penser. Des expériences récentes sur la perception des couleurs montrent que les locuteurs de langues disposant de plus de termes pour distinguer les nuances de bleu perçoivent effectivement ces nuances plus rapidement. Ces travaux revitalisent un débat longtemps considéré comme clos.",
    question: "Quelle expérience illustre l'hypothèse de Sapir-Whorf dans cet extrait ?",
    options: ["Les locuteurs multilingues ont plus de mémoire.", "Les locuteurs avec plus de termes pour le bleu perçoivent les nuances plus vite.", "Les enfants apprennent les langues plus vite que les adultes.", "Les langues tonales développent une meilleure oreille musicale."],
    correctIndex: 1,
    explanation: "L'expérience sur les nuances de bleu montre que le vocabulaire d'une langue influence la perception visuelle.",
  },
  {
    id: 27,
    level: "C1",
    topic: "Démographie et immigration",
    audioScript: "Face au déclin démographique de nombreux pays industrialisés, l'immigration apparaît comme l'une des réponses possibles. Toutefois, les économistes soulignent que l'intégration réussie des migrants dépend moins de leur nombre que de la qualité des politiques d'accueil, de formation et d'accès au marché du travail développées par les pays hôtes.",
    question: "Selon les économistes, de quoi dépend principalement le succès de l'intégration des migrants ?",
    options: ["Du niveau d'éducation des migrants avant leur arrivée.", "Des politiques d'accueil, de formation et d'accès au travail dans les pays hôtes.", "Du nombre de migrants accueillis chaque année.", "De la proximité culturelle entre migrants et société d'accueil."],
    correctIndex: 1,
    explanation: "L'intégration réussie dépend de la qualité des politiques d'accueil et d'insertion, pas uniquement du nombre de migrants.",
  },
  {
    id: 28,
    level: "C1",
    topic: "Roman québécois contemporain",
    audioScript: "L'œuvre de Kim Thúy, notamment Ru et Vi, explore avec une prose poétique remarquable la mémoire fragmentée des réfugiés vietnamiens au Québec. L'auteure tisse une réflexion sur la double appartenance, la transmission intergénérationnelle du traumatisme, et la possibilité de reconstruire une identité à travers le langage dans une langue d'adoption.",
    question: "Quel thème central traverse l'œuvre de Kim Thúy ?",
    options: ["La critique du colonialisme français en Asie.", "La reconstruction identitaire dans une langue d'adoption et la mémoire du trauma.", "La difficulté à apprendre le français comme langue seconde.", "L'intégration économique des immigrants qualifiés."],
    correctIndex: 1,
    explanation: "L'œuvre de Kim Thúy traite de la reconstruction identitaire, de la mémoire traumatique et de l'appartenance à travers le langage.",
  },
  {
    id: 29,
    level: "C1",
    topic: "Bioéthique — fin de vie",
    audioScript: "Le débat sur l'aide médicale à mourir oppose des conceptions profondes de la dignité humaine. Pour ses partisans, la dignité requiert une autonomie jusqu'au dernier instant ; pour ses opposants, elle implique un accompagnement inconditionnel sans précipitation de la mort. Les législations nationales reflètent ces tensions philosophiques fondamentales.",
    question: "Quel est le cœur du désaccord sur l'aide médicale à mourir ?",
    options: ["Le coût pour les systèmes de santé publique.", "Deux conceptions opposées de la dignité : autonomie face à accompagnement inconditionnel.", "La formation insuffisante des médecins.", "Les abus potentiels sur les personnes vulnérables."],
    correctIndex: 1,
    explanation: "Le débat oppose deux visions de la dignité : l'autonomie jusqu'au bout pour les partisans, l'accompagnement inconditionnel pour les opposants.",
  },
  {
    id: 30,
    level: "C1",
    topic: "Géopolitique de la langue",
    audioScript: "Le soft power linguistique désigne la capacité d'un État à exercer une influence culturelle et politique via sa langue. La diffusion du français dans le monde ne repose pas uniquement sur l'action de l'Institut français ou de l'Alliance française, mais aussi sur la vitalité de la création culturelle francophone — cinéma, littérature, musique — capable d'attirer des apprenants par désir plutôt que par obligation.",
    question: "Qu'est-ce qui nourrit le soft power linguistique selon cet extrait ?",
    options: ["Les accords commerciaux entre pays francophones.", "La vitalité de la création culturelle francophone qui attire les apprenants.", "L'obligation de parler français dans les organisations internationales.", "Le nombre de locuteurs natifs dans le monde."],
    correctIndex: 1,
    explanation: "Le soft power linguistique repose sur l'attrait de la création culturelle — cinéma, littérature, musique — qui suscite le désir d'apprendre la langue.",
  },
  {
    id: 31,
    level: "C1",
    topic: "Anthropologie de l'alimentation",
    audioScript: "Le sociologue Claude Fischler a montré que manger est un acte à la fois biologique et symbolique. L'incorporation alimentaire ne se résume pas à l'ingestion de nutriments : elle engage l'identité, les appartenances culturelles et les représentations du bien et du mal. Ce que nous choisissons de manger dit qui nous sommes et à quels groupes sociaux nous appartenons.",
    question: "Selon Fischler, que révèle notre alimentation ?",
    options: ["Notre état de santé physique.", "Notre identité et nos appartenances culturelles.", "Notre niveau de revenu.", "Nos préférences esthétiques."],
    correctIndex: 1,
    explanation: "Pour Fischler, les choix alimentaires révèlent l'identité et les appartenances culturelles d'un individu.",
  },
  {
    id: 32,
    level: "C2",
    topic: "Philosophie politique — Arendt",
    audioScript: "Hannah Arendt distingue travail, œuvre et action comme les trois activités fondamentales de la vita activa. L'action, qui s'exerce dans l'espace public entre les hommes, est la seule activité proprement politique. Elle est imprévisible, irréversible, et crée de la natalité — la capacité humaine à commencer quelque chose de radicalement nouveau. Cette conception s'oppose aux régimes totalitaires qui cherchent à éliminer la pluralité et la contingence.",
    question: "Qu'est-ce que la « natalité » dans la pensée d'Arendt ?",
    options: ["Le taux de naissance dans une société.", "La capacité humaine à initier quelque chose de radicalement nouveau.", "La transmission des valeurs entre générations.", "Le droit à la citoyenneté par la naissance."],
    correctIndex: 1,
    explanation: "La natalité chez Arendt désigne la capacité humaine à inaugurer quelque chose d'entièrement nouveau — fondement de la liberté politique.",
  },
  {
    id: 33,
    level: "C2",
    topic: "Linguistique critique — Fairclough",
    audioScript: "L'analyse critique du discours, développée par Norman Fairclough, examine comment le langage reproduit et légitime les rapports de pouvoir dans la société. Les textes médiatiques, politiques ou institutionnels ne sont pas neutres : ils construisent des identités sociales, définissent ce qui est normal ou déviant, et naturalisent des inégalités qui sont en réalité historiquement contingentes.",
    question: "Que montre l'analyse critique du discours de Fairclough ?",
    options: ["Que le langage est un outil neutre de communication.", "Que les textes médiatiques et politiques reproduisent et légitiment les inégalités de pouvoir.", "Que les langues minoritaires doivent être préservées.", "Que la grammaire structure la pensée."],
    correctIndex: 1,
    explanation: "Fairclough montre que le discours n'est pas neutre : il reproduit et naturalise des rapports de pouvoir et des inégalités sociales.",
  },
  {
    id: 34,
    level: "C2",
    topic: "Économie du bien-être",
    audioScript: "Amartya Sen a profondément renouvelé la mesure du développement en proposant l'approche par les capabilités. Plutôt que de mesurer le bien-être par le revenu ou l'utilité, Sen invite à considérer ce que les individus sont réellement capables de faire et d'être. Cette approche est à la base de l'Indice de Développement Humain du Programme des Nations Unies pour le Développement.",
    question: "Sur quoi repose l'approche par les capabilités d'Amartya Sen ?",
    options: ["Sur la maximisation du revenu national brut.", "Sur ce que les individus sont réellement capables de faire et d'être.", "Sur la mesure de la satisfaction subjective des individus.", "Sur le niveau de consommation moyen par habitant."],
    correctIndex: 1,
    explanation: "Sen mesure le bien-être par les capabilités réelles des individus — ce qu'ils peuvent faire et être — et non par le revenu.",
  },
  {
    id: 35,
    level: "C2",
    topic: "Droit international — réfugiés",
    audioScript: "La Convention de Genève de mille neuf cent cinquante et un définit le réfugié comme toute personne craignant avec raison d'être persécutée en raison de sa race, de sa religion, de sa nationalité, de son appartenance à un groupe social particulier ou de ses opinions politiques. Les crises climatiques et économiques soulèvent aujourd'hui la question d'un élargissement de cette définition aux déplacés environnementaux.",
    question: "Quel débat contemporain la Convention de Genève n'anticipe-t-elle pas ?",
    options: ["Le statut des apatrides.", "Le cas des déplacés environnementaux et climatiques.", "La protection des réfugiés de guerre.", "Les droits des demandeurs d'asile."],
    correctIndex: 1,
    explanation: "La Convention de 1951 n'inclut pas les déplacés climatiques ou environnementaux, ce qui crée un vide juridique contemporain.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Philosophie de la technique",
    audioScript: "Martin Heidegger soutient dans La Question de la technique que la technique moderne n'est pas un simple outil neutre mais un mode de dévoilement du monde qui réduit la nature à un fonds d'énergie exploitable. Ce que Heidegger nomme le Gestell, ou l'arraisonnement, désigne la tendance totalitaire de la technique à soumettre tout étant à l'impératif de disponibilité et d'optimisation.",
    question: "Comment Heidegger conçoit-il la technique moderne ?",
    options: ["Comme un progrès libérateur pour l'humanité.", "Comme un mode de dévoilement qui réduit la nature à un fonds exploitable.", "Comme un danger uniquement nucléaire et militaire.", "Comme une extension naturelle des outils artisanaux."],
    correctIndex: 1,
    explanation: "Heidegger voit dans la technique moderne un mode de dévoilement qui impose un rapport d'exploitation à la nature et à tout étant.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Mémoire collective — Nora",
    audioScript: "Pierre Nora a forgé le concept de lieux de mémoire pour désigner ces sites, symboles, pratiques ou textes où s'ancre la mémoire collective d'une nation. En France, le coq gaulois, Verdun, ou la Marseillaise sont de tels lieux. Nora soutient que leur prolifération signale paradoxalement une rupture avec une mémoire vivante : on crée des lieux de mémoire là où la mémoire s'efface.",
    question: "Que signale selon Nora la prolifération des lieux de mémoire ?",
    options: ["Une nation en pleine confiance dans son identité.", "Une rupture paradoxale avec une mémoire vivante qui s'efface.", "Un renouveau de l'intérêt pour l'histoire nationale.", "La résistance des citoyens à l'oubli imposé."],
    correctIndex: 1,
    explanation: "Pour Nora, les lieux de mémoire surgissent là où la mémoire vivante se retire — leur multiplication signale une fracture mémorielle.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Économie comportementale",
    audioScript: "Richard Thaler et Cass Sunstein ont développé le concept de nudge, ou coup de pouce, pour désigner des architectures de choix qui orientent les comportements sans contraindre ni interdire. En plaçant les légumes avant les desserts dans une cafétéria scolaire, on augmente leur consommation sans supprimer le choix. Cette approche paternaliste libérale interroge les frontières entre manipulation bienveillante et autonomie individuelle.",
    question: "Qu'est-ce qu'un nudge selon Thaler et Sunstein ?",
    options: ["Une contrainte légale sur les comportements nuisibles.", "Une incitation financière à adopter un comportement souhaitable.", "Une architecture de choix orientant le comportement sans contraindre.", "Une campagne publicitaire de sensibilisation."],
    correctIndex: 2,
    explanation: "Le nudge est une architecture de choix qui oriente les comportements de façon non coercitive, en jouant sur l'environnement décisionnel.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Transition énergétique",
    audioScript: "La transition énergétique vers les renouvelables soulève la question des dépendances aux matières premières critiques. Les batteries des voitures électriques nécessitent du lithium, du cobalt et du manganèse, souvent extraits dans des conditions environnementales et sociales problématiques. Certains critiques ironisent sur une transition verte reposant sur une extraction brune — révélant les contradictions inhérentes à notre modèle de développement.",
    question: "Quelle contradiction la transition énergétique révèle-t-elle selon cet extrait ?",
    options: ["Les renouvelables coûtent plus cher que les énergies fossiles.", "La transition verte dépend de matières premières dont l'extraction est souvent destructrice.", "Les voitures électriques sont moins efficaces que les voitures thermiques.", "Les États ne tiennent pas leurs engagements climatiques."],
    correctIndex: 1,
    explanation: "La transition vers les renouvelables crée une dépendance à des matières premières dont l'extraction peut être environnementalement et socialement problématique.",
  },
];
