import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Batch 7 — TCF Canada breadth: environment, health, housing, mobility, education, society, community; EO/EE frames. */
export const BATCH7_A: LemmaRow[] = [
  ["Bank statement", "le relevé bancaire", "Consultez le relevé bancaire en ligne chaque mois."],
  ["Chequing account", "le compte chèques", "Le compte chèques reçoit votre paie par dépôt direct."],
  ["Chequebook", "le chéquier", "Commandez un nouveau chéquier à la succursale."],
  ["Overdraft protection", "la protection contre les découverts", "La protection contre les découverts évite les frais."],
  ["Coin roll", "le rouleau de pièces", "Achetez un rouleau de pièces pour la laverie."],
  ["Exact change", "l'appoint", "Le conducteur n'a pas toujours l'appoint."],
  ["Tip jar", "le pourboire volontaire", "Un pourboire volontaire se trouve près de la caisse."],
  ["Table reservation", "la réservation de table", "Prenez une réservation de table pour six personnes."],
  ["Takeout order", "la commande à emporter", "La commande à emporter sera prête dans vingt minutes."],
  ["Dine-in", "sur place", "Préférez-vous manger sur place ou à emporter?"],
  ["Doggy bag", "les restes à emporter", "Demandez les restes à emporter si vous n'avez pas fini."],
  ["Daily special", "le plat du jour", "Le plat du jour est indiqué sur l'ardoise."],
  ["Vegetarian option", "l'option végétarienne", "Le menu propose une option végétarienne."],
  ["Gluten-free meal", "le repas sans gluten", "Signalez un repas sans gluten au serveur."],
  ["Food allergy card", "la fiche d'allergie", "Remettez la fiche d'allergie à la cuisine."],
  ["Parking validation", "la validation de stationnement", "Demandez la validation de stationnement à la caisse."],
  ["Coat check", "le vestiaire", "Déposez votre manteau au vestiaire."],
  ["Lost receipt", "le reçu perdu", "Sans reçu perdu, le remboursement est impossible."],
  ["Gift card balance", "le solde de carte-cadeau", "Vérifiez le solde de carte-cadeau à la caisse."],
  ["Exchange within 30 days", "l'échange sous trente jours", "L'échange sous trente jours exige le reçu original."],
  ["Damaged packaging", "l'emballage endommagé", "Signalez l'emballage endommagé avant l'achat."],
  ["Rain check voucher", "le bon de report", "Le bon de report vaut pour une autre date."],
  ["Refill request", "la demande de renouvellement", "Soumettez une demande de renouvellement par l'application de la pharmacie."],
  ["Generic medication", "le médicament générique", "Le médicament générique coûte moins cher."],
  ["Dosage instructions", "la posologie", "Suivez la posologie indiquée sur l'étiquette."],
  ["Side effect warning", "l'effet secondaire", "L'effet secondaire disparaît souvent après quelques jours."],
  ["Blood pressure kiosk", "la borne de tension artérielle", "Mesurez votre tension à la borne de tension artérielle."],
  ["Post office counter", "le comptoir postal", "Le comptoir postal ferme à seize heures trente."],
  ["Certified letter", "la lettre recommandée", "Envoyez l'avis par lettre recommandée pour preuve de réception."],
  ["Express parcel", "le colis express", "Le colis express arrive demain avant midi."],
  ["Tracking number", "le numéro de suivi", "Entrez le numéro de suivi sur le site du transporteur."],
  ["Door entry PIN", "le NIP d'entrée", "Entrez le NIP d'entrée sur le clavier de la porte."],
  ["Intercom system", "l'interphone", "L'interphone ne fonctionne pas au troisième étage."],
  ["Superintendent office", "le bureau du concierge", "Le bureau du concierge est au rez-de-chaussée."],
  ["Rent cheque", "le chèque de loyer", "Postez le chèque de loyer avant le premier du mois."],
  ["Vent cleaning", "le nettoyage des conduits", "Le nettoyage des conduits améliore la qualité de l'air intérieur."],
  ["Smoke alarm test", "le test de détecteur de fumée", "Le test de détecteur de fumée est prévu mardi."],
  ["Pest control visit", "la visite de dératisation", "La visite de dératisation aura lieu jeudi matin."],
  ["Key fob", "la télécommande d'accès", "La télécommande d'accès ouvre le garage."],
  ["Gym day pass", "la passe journalière", "La passe journalière coûte douze dollars."],
  ["Library overdue fine", "l'amende de retard", "Payez l'amende de retard pour emprunter à nouveau."],
  ["Book drop slot", "la fente de retour", "Déposez le livre dans la fente de retour après les heures."],
  ["Photocopy credit", "le crédit de photocopie", "Rechargez le crédit de photocopie à l'accueil."],
  ["Wi-Fi guest network", "le réseau invité", "Le mot de passe du réseau invité est affiché à l'accueil."],
  ["Closed for lunch", "fermé pour le dîner", "Le bureau est fermé pour le dîner entre midi et treize heures."],
  ["Help wanted sign", "l'affiche d'embauche", "Une affiche d'embauche est collée sur la vitrine."],
  ["Open house viewing", "la journée portes ouvertes", "La journée portes ouvertes du logement est dimanche."],
  ["Meter reading", "la lecture du compteur", "Transmettez la lecture du compteur pour éviter une estimation."],
  ["Coin laundry card", "la carte de laverie", "Rechargez la carte de laverie au distributeur."],
  ["Parcel pickup slip", "le bordereau de cueillette", "Présentez le bordereau de cueillette au comptoir."],
];

export const BATCH7_B: LemmaRow[] = [
  ["Ecosystem", "l'écosystème", "L'écosystème du marais abrite de nombreux oiseaux."],
  ["Endangered species", "l'espèce en voie de disparition", "L'espèce en voie de disparition est protégée par la loi."],
  ["Habitat loss", "la perte d'habitat", "La perte d'habitat menace les populations locales."],
  ["Reforestation project", "le projet de reboisement", "Le projet de reboisement plante mille arbres par an."],
  ["Wetland restoration", "la restauration des milieux humides", "La restauration des milieux humides filtre l'eau de pluie."],
  ["Marshland", "le marais", "Le marais accueille des grenouilles et des hérons."],
  ["Peat bog", "la tourbière", "La tourbière stocke une grande quantité de carbone."],
  ["Glacier retreat", "le recul des glaciers", "Le recul des glaciers modifie l'approvisionnement en eau."],
  ["Sea level rise", "l'élévation du niveau de la mer", "L'élévation du niveau de la mer inquiète les côtes."],
  ["Permafrost thaw", "le dégel du pergélisol", "Le dégel du pergélisol endommage les infrastructures nordiques."],
  ["Urban heat island", "l'îlot de chaleur urbain", "L'îlot de chaleur urbain augmente les nuits chaudes."],
  ["Renewable electricity", "l'électricité renouvelable", "L'électricité renouvelable alimente la nouvelle école."],
  ["Hydroelectric dam", "le barrage hydroélectrique", "Le barrage hydroélectrique régule le débit de la rivière."],
  ["Geothermal heating", "le chauffage géothermique", "Le chauffage géothermique réduit la consommation de gaz."],
  ["Biomass plant", "la centrale à biomasse", "La centrale à biomasse utilise des résidus forestiers."],
  ["Attic insulation", "l'isolation des combles", "L'isolation des combles diminue la facture de chauffage."],
  ["Weather stripping", "le calfeutrage", "Le calfeutrage des fenêtres bloque les courants d'air."],
  ["Carbon levy", "la redevance sur les combustibles", "La redevance sur les combustibles finance la transition énergétique."],
  ["Emissions cap", "le plafond d'émissions", "Le plafond d'émissions concerne les grandes industries."],
  ["Single-use plastic ban", "l'interdiction des plastiques à usage unique", "L'interdiction des plastiques à usage unique vise les sacs et les pailles."],
  ["Microplastic pollution", "la pollution aux microplastiques", "La pollution aux microplastiques atteint les grands lacs."],
  ["Ocean acidification", "l'acidification des océans", "L'acidification des océans affecte les coquillages."],
  ["Coral bleaching", "le blanchissement des coraux", "Le blanchissement des coraux suit les vagues de chaleur."],
  ["Pollinator garden", "le jardin pollinisateur", "Le jardin pollinisateur attire abeilles et papillons."],
  ["Urban beekeeping", "l'apiculture urbaine", "L'apiculture urbaine est autorisée sur certains toits."],
  ["Pesticide runoff", "le ruissellement de pesticides", "Le ruissellement de pesticides contamme les rivières."],
  ["Organic waste bin", "le bac de matières organiques", "Déposez les épluchures dans le bac de matières organiques."],
  ["Bulky waste pickup", "la collecte des encombrants", "La collecte des encombrants passe le premier samedi du mois."],
  ["E-waste collection", "la collecte de déchets électroniques", "Apportez les vieux téléphones à la collecte de déchets électroniques."],
  ["Clothing swap event", "l'échange de vêtements", "L'échange de vêtements évite d'envoyer des textiles à la décharge."],
  ["Repair café", "le café-réparation", "Au café-réparation, des bénévoles réparent de petits appareils."],
  ["Circular economy", "l'économie circulaire", "L'économie circulaire valorise les matériaux recyclés."],
  ["Aquifer protection", "la protection de l'aquifère", "La protection de l'aquifère limite l'irrigation intensive."],
  ["Watershed council", "le comité de bassin versant", "Le comité de bassin versant planifie la qualité de l'eau."],
  ["Reservoir level", "le niveau du réservoir", "Le niveau du réservoir baisse après plusieurs semaines sèches."],
  ["Floodplain mapping", "la cartographie des plaines inondables", "La cartographie des plaines inondables guide l'urbanisme."],
  ["Evacuation order", "l'ordre d'évacuation", "L'ordre d'évacuation concerne les habitants près de la rivière."],
  ["Air quality index", "l'indice de qualité de l'air", "L'indice de qualité de l'air dépasse cent aujourd'hui."],
  ["Smog advisory", "l'avis de smog", "Un avis de smog limite les activités extérieures."],
  ["Ground-level ozone", "l'ozone troposphérique", "L'ozone troposphérique irrite les poumons en été."],
  ["Climate adaptation plan", "le plan d'adaptation climatique", "Le plan d'adaptation climatique renforce les digues."],
  ["Mitigation measure", "la mesure d'atténuation", "Chaque mesure d'atténuation réduit les gaz à effet de serre."],
  ["Net-zero pledge", "l'engagement net zéro", "La ville prend un engagement net zéro pour 2050."],
  ["Invasive plant", "la plante envahissante", "La plante envahissante étouffe les espèces indigènes."],
  ["Native species planting", "la plantation d'espèces indigènes", "La plantation d'espèces indigènes restaure la biodiversité locale."],
  ["Waiting room", "la salle d'attente", "La salle d'attente affiche un délai de quarante-cinq minutes."],
  ["Intake nurse", "l'infirmière d'évaluation", "L'infirmière d'évaluation note vos symptômes à l'arrivée."],
  ["Blood draw", "le prélèvement sanguin", "Le prélèvement sanguin dure quelques minutes seulement."],
  ["Chest X-ray", "la radiographie pulmonaire", "La radiographie pulmonaire confirme l'infection."],
  ["Ultrasound scan", "l'échographie", "L'échographie dure environ vingt minutes."],
  ["MRI appointment", "le rendez-vous d'IRM", "Le rendez-vous d'IRM exige de retirer les objets métalliques."],
  ["Specialist referral", "la référence à un spécialiste", "Le médecin envoie une référence à un spécialiste."],
  ["Follow-up visit", "la visite de suivi", "La visite de suivi est prévue dans six semaines."],
  ["Medical history form", "le questionnaire médical", "Remplissez le questionnaire médical avant la consultation."],
  ["Treatment consent", "le consentement au traitement", "Signez le consentement au traitement pour l'intervention."],
  ["Health record access", "l'accès au dossier médical", "L'accès au dossier médical est protégé par mot de passe."],
  ["Physiotherapy session", "la séance de physiothérapie", "La séance de physiothérapie améliore la mobilité du genou."],
  ["Occupational therapy session", "la séance d'ergothérapie", "La séance d'ergothérapie améliore la prise d'objets."],
  ["Speech therapy", "l'orthophonie", "L'orthophonie soutient l'enfant qui bégaie."],
  ["Midwife clinic", "la clinique de sages-femmes", "La clinique de sages-femmes suit la grossesse."],
  ["Prenatal class", "le cours prénatal", "Le cours prénatal prépare les futurs parents."],
  ["Postnatal checkup", "le suivi postnatal", "Le suivi postnatal vérifie la récupération de la mère."],
  ["Pediatric clinic", "la clinique pédiatrique", "La clinique pédiatrique accepte les nouveau-nés."],
  ["Geriatric assessment", "l'évaluation gériatrique", "L'évaluation gériatrique examine la mobilité et la mémoire."],
  ["Memory clinic", "la clinique de la mémoire", "La clinique de la mémoire propose des tests cognitifs."],
  ["Immunization record", "le carnet de vaccination", "Apportez le carnet de vaccination à la clinique."],
  ["Booster dose", "la dose de rappel", "La dose de rappel renforce la protection."],
  ["Antibiotic resistance", "la résistance aux antibiotiques", "La résistance aux antibiotiques complique certains traitements."],
  ["Medical imaging centre", "le centre d'imagerie médicale", "Le centre d'imagerie médicale confirme le rendez-vous par texto."],
  ["Emergency wait time", "le délai d'attente à l'urgence", "Le délai d'attente à l'urgence est affiché en ligne."],
  ["Ambulance bill", "la facture d'ambulance", "La facture d'ambulance peut être partiellement couverte."],
  ["First aid course", "le cours de premiers soins", "Le cours de premiers soins inclut la RCR."],
  ["CPR certification", "la certification en RCR", "La certification en RCR se renouvelle tous les trois ans."],
  ["Dietitian appointment", "le rendez-vous avec la diététiste", "Le rendez-vous avec la diététiste aide à gérer le diabète."],
  ["Nutrition workshop", "l'atelier nutrition", "L'atelier nutrition explique comment lire les étiquettes."],
  ["Mindfulness session", "la séance de pleine conscience", "La séance de pleine conscience réduit l'anxiété."],
  ["Meditation group", "le groupe de méditation", "Le groupe de méditation se réunit le lundi midi."],
  ["Anxiety screening", "le dépistage de l'anxiété", "Le dépistage de l'anxiété est anonyme au CLSC."],
  ["Depression screening", "le dépistage de la dépression", "Le dépistage de la dépression oriente vers des ressources."],
  ["Therapy appointment", "le rendez-vous de thérapie", "Le rendez-vous de thérapie est confidentiel."],
  ["Peer support meeting", "la rencontre de pairs aidants", "La rencontre de pairs aidants se tient chaque jeudi."],
  ["Workplace wellness", "le mieux-être au travail", "Le programme de mieux-être au travail offre du yoga."],
  ["Health card renewal", "le renouvellement de la carte santé", "Le renouvellement de la carte santé se fait en ligne."],
  ["Dental emergency", "l'urgence dentaire", "L'urgence dentaire traite la douleur intense."],
  ["Eye exam", "l'examen de la vue", "Prenez un rendez-vous pour un examen de la vue."],
  ["Rent control board", "le tribunal administratif du logement", "Le tribunal administratif du logement traite les hausses contestées."],
  ["Eviction notice", "l'avis d'éviction", "L'avis d'éviction respecte un préavis légal."],
  ["Landlord entry notice", "l'avis d'accès du propriétaire", "L'avis d'accès du propriétaire précise la date de visite."],
  ["Tenant association", "l'association de locataires", "L'association de locataires négocie avec la gestion."],
  ["Co-tenancy agreement", "l'entente de colocation", "L'entente de colocation répartit les charges."],
  ["Room for rent", "la chambre à louer", "La chambre à louer inclut les services publics."],
  ["Furnished rental", "le logement meublé", "Le logement meublé coûte plus cher par mois."],
  ["Unfurnished unit", "le logement non meublé", "Le logement non meublé exige d'apporter les meubles."],
  ["Thermostat setting", "le réglage du thermostat", "Le réglage du thermostat ne doit pas dépasser vingt et un degrés."],
  ["Electricity bill", "la facture d'électricité", "La facture d'électricité augmente en hiver."],
  ["Water heater tank", "le réservoir d'eau chaude", "Le réservoir d'eau chaude fuit dans le sous-sol."],
  ["Clogged drain", "le drain bouché", "Signalez le drain bouché au propriétaire."],
  ["Leaky faucet", "le robinet qui fuit", "Un robinet qui fuit gonfle la facture d'eau."],
  ["Broken window pane", "le carreau brisé", "Le carreau brisé sera remplacé demain."],
  ["Condo board meeting", "la réunion du conseil de copropriété", "La réunion du conseil de copropriété vote le budget."],
  ["Strata fees", "les frais de copropriété", "Les frais de copropriété couvrent l'entretien de la piscine."],
  ["Noise bylaw fine", "l'amende pour bruit", "L'amende pour bruit peut atteindre plusieurs centaines de dollars."],
  ["Pet deposit", "le dépôt pour animal", "Le dépôt pour animal est remboursable sans dommages."],
  ["Pet-friendly lease", "le bail acceptant les animaux", "Le bail acceptant les animaux précise le poids maximal."],
  ["No-pets clause", "la clause sans animaux", "La clause sans animaux figure au contrat de location."],
  ["Smoking ban (building)", "l'interdiction de fumer dans l'immeuble", "L'interdiction de fumer dans l'immeuble vaut pour les balcons."],
  ["Visitor parking pass", "le laissez-passer de stationnement", "Demandez un laissez-passer de stationnement pour vos invités."],
  ["Bicycle storage room", "le local à vélos", "Le local à vélos est accessible avec une clé."],
  ["Guest suite rental", "la location de suite pour invités", "La location de suite pour invités coûte cinquante dollars la nuit."],
  ["Laundry room schedule", "l'horaire de la buanderie", "Respectez l'horaire de la buanderie affiché dans l'ascenseur."],
  ["Key return form", "le formulaire de remise des clés", "Remplissez le formulaire de remise des clés au départ."],
  ["Lease break penalty", "la pénalité de rupture de bail", "La pénalité de rupture de bail équivaut à deux mois de loyer."],
  ["Sublet approval", "l'autorisation de sous-location", "Obtenez l'autorisation de sous-location par écrit."],
  ["Rent receipt request", "la demande de quittance", "Demandez une quittance de loyer pour vos dossiers."],
  ["Hydro account", "le compte d'électricité", "Ouvrez un compte d'électricité à votre nom."],
  ["Natural gas bill", "la facture de gaz naturel", "La facture de gaz naturel augmente en janvier."],
  ["Internet installation", "l'installation Internet", "L'installation Internet est prévue vendredi matin."],
  ["Cable bundle", "le forfait câble", "Le forfait câble inclut les chaînes locales."],
  ["Shared utility split", "le partage des services", "Le partage des services est indiqué sur le bail."],
  ["Roommate contract", "le contrat entre colocataires", "Le contrat entre colocataires fixe les règles communes."],
  ["House rules sheet", "la feuille de règlement intérieur", "La feuille de règlement intérieur interdit les fêtes après vingt-trois heures."],
  ["Moving truck reservation", "la réservation de camion de déménagement", "La réservation de camion de déménagement se fait en ligne."],
  ["Elevator booking (move)", "la réservation d'ascenseur pour déménagement", "Réservez l'ascenseur pour déménagement à l'accueil."],
  ["Neighbour dispute", "le conflit de voisinage", "Le conflit de voisinage peut être médité gratuitement."],
  ["Shared entrance", "l'entrée commune", "L'entrée commune doit rester dégagée en cas d'incendie."],
  ["Light rail line", "la ligne de tramway léger", "La ligne de tramway léger relie le campus au centre-ville."],
  ["Streetcar stop", "l'arrêt de tramway", "Attendez à l'arrêt de tramway sous l'abri."],
  ["Fare validator", "le valideur de titre", "Tapez votre carte sur le valideur de titre."],
  ["Transfer receipt", "le reçu de correspondance", "Conservez le reçu de correspondance pendant le trajet."],
  ["Off-peak fare", "le tarif hors pointe", "Le tarif hors pointe coûte moins cher après neuf heures."],
  ["Peak surcharge", "le supplément heure de pointe", "Un supplément heure de pointe s'applique le matin."],
  ["Park-and-ride lot", "le stationnement relais", "Garez-vous au stationnement relais et prenez l'autobus."],
  ["Bike helmet bylaw", "le règlement sur le casque", "Le règlement sur le casque oblige les cyclistes de moins de dix-huit ans."],
  ["E-scooter rental", "la location de trottinette électrique", "La location de trottinette électrique exige une application."],
  ["Transit disruption", "la perturbation de service", "Une perturbation de service affecte la ligne orange."],
  ["Shuttle replacement", "l'autobus de remplacement", "L'autobus de remplacement circule pendant les travaux."],
  ["Wheelchair ramp (bus)", "la rampe d'autobus", "Demandez au conducteur de déployer la rampe d'autobus."],
  ["Priority seating area", "l'espace prioritaire", "Cédez l'espace prioritaire aux personnes à mobilité réduite."],
  ["Stroller bay", "l'espace pour poussette", "Rangez la poussette dans l'espace pour poussette."],
  ["Ferry schedule change", "le changement d'horaire du traversier", "Le changement d'horaire du traversier est affiché au quai."],
  ["Harbour terminal", "le terminal portuaire", "Le terminal portuaire accueille les croisières estivales."],
  ["Border wait time", "le délai à la frontière", "Le délai à la frontière dépasse une heure dimanche."],
  ["Vehicle safety inspection", "l'inspection mécanique", "L'inspection mécanique est exigée avant la vente."],
  ["Emissions test", "le test d'émissions", "Le test d'émissions est obligatoire pour certains véhicules."],
  ["Carpool parking permit", "le permis de stationnement covoiturage", "Le permis de stationnement covoiturage est gratuit."],
  ["Rideshare pickup zone", "la zone de prise en charge", "Attendez dans la zone de prise en charge numéro trois."],
  ["Airport parking garage", "le stationnement de l'aéroport", "Le stationnement de l'aéroport est complet le vendredi."],
  ["Long-term parking rate", "le tarif de stationnement longue durée", "Le tarif de stationnement longue durée est moins cher par jour."],
  ["Short-term parking meter", "le parcomètre courte durée", "Le parcomètre courte durée limite à deux heures."],
  ["Valet parking service", "le service de voiturier", "Le service de voiturier est offert à l'hôtel."],
  ["Traffic congestion", "la congestion routière", "La congestion routière double le temps de trajet."],
  ["Road salt stockpile", "le stock de sel de déneigement", "Le stock de sel de déneigement est prêt pour l'hiver."],
  ["Black ice warning", "l'avertissement de verglas", "Un avertissement de verglas est émis pour les ponts."],
  ["Low visibility", "la faible visibilité", "Ralentissez en cas de faible visibilité par brouillard."],
  ["Cycling route map", "la carte des pistes cyclables", "Téléchargez la carte des pistes cyclables municipales."],
  ["Transit network map", "le plan du réseau de transport", "Le plan du réseau de transport est affiché dans chaque station."],
  ["Bike repair station", "la station de réparation de vélos", "La station de réparation de vélos offre des outils gratuits."],
  ["Car-share membership", "l'abonnement d'autopartage", "L'abonnement d'autopartage inclut l'assurance de base."],
  ["Toll transponder", "le transpondeur de péage", "Fixez le transpondeur de péage sur le pare-brise."],
  ["High-occupancy lane", "la voie réservée", "La voie réservée exige au moins deux occupants."],
  ["Preschool registration", "l'inscription à la prématernelle", "L'inscription à la prématernelle ouvre en janvier."],
  ["Nursery school", "la maternelle privée", "La maternelle privée accueille les enfants dès trois ans."],
  ["Substitute teacher", "l'enseignant suppléant", "L'enseignant suppléant couvre la classe aujourd'hui."],
  ["Field trip permission", "l'autorisation de sortie scolaire", "Signez l'autorisation de sortie scolaire avant vendredi."],
  ["School supply list", "la liste de fournitures", "La liste de fournitures est publiée sur le site de l'école."],
  ["School backpack", "le sac d'école", "Le sac d'école ne doit pas dépasser quinze kilos."],
  ["Locker combination", "la combinaison du casier", "Notez la combinaison du casier dans un endroit sûr."],
  ["Cafeteria menu", "le menu de la cafétéria", "Le menu de la cafétéria propose une option végétalienne."],
  ["School nurse office", "le bureau de l'infirmière scolaire", "Le bureau de l'infirmière scolaire distribue des pansements."],
  ["Bullying report form", "le formulaire de signalement d'intimidation", "Déposez le formulaire de signalement d'intimidation à la direction."],
  ["After-school homework help", "l'aide aux devoirs après l'école", "L'aide aux devoirs après l'école est gratuite à la bibliothèque."],
  ["Tutoring session", "la séance de tutorat", "La séance de tutorat est gratuite à la bibliothèque."],
  ["Standardized exam", "l'examen normalisé", "L'examen normalisé se tient en juin."],
  ["Graduation convocation", "la cérémonie de remise des diplômes", "La cérémonie de remise des diplômes est à la salle communale."],
  ["Scholarship application", "la demande de bourse", "La demande de bourse ferme le quinze mars."],
  ["Student bursary", "la bourse d'études", "La bourse d'études couvre les frais de scolarité."],
  ["Trade certificate", "le certificat de métier", "Le certificat de métier atteste la compétence en plomberie."],
  ["Apprenticeship contract", "le contrat d'apprentissage", "Le contrat d'apprentissage alterne cours et atelier."],
  ["Continuing education credit", "l'unité de formation continue", "Chaque unité de formation continue renouvelle la certification."],
  ["Language proficiency exam", "l'examen de compétence linguistique", "L'examen de compétence linguistique évalue l'oral et l'écrit."],
  ["Homestay host family", "la famille d'accueil", "La famille d'accueil propose une chambre pour l'année scolaire."],
  ["Student exchange program", "le programme d'échange scolaire", "Le programme d'échange scolaire dure un semestre."],
  ["Campus open day", "la journée découverte du campus", "La journée découverte du campus inclut une visite guidée."],
  ["Tuition installment plan", "le plan de paiement des frais", "Le plan de paiement des frais étale le coût sur six mois."],
  ["Course withdrawal deadline", "la date limite de désinscription", "La date limite de désinscription est le dixième jour de cours."],
  ["Extension request (school)", "la demande de prolongation", "Soumettez une demande de prolongation avant l'échéance."],
  ["Lecture hall seating", "l'amphithéâtre", "L'amphithéâtre accueille deux cents étudiants."],
  ["Lab safety goggles", "les lunettes de laboratoire", "Portez les lunettes de laboratoire pendant l'expérience."],
  ["Childcare subsidy form", "le formulaire de subvention à la garde", "Remplissez le formulaire de subvention à la garde en ligne."],
  ["Licensed day home", "la garderie en milieu familial", "La garderie en milieu familial accueille six enfants."],
  ["Early childhood educator", "l'éducatrice de la petite enfance", "L'éducatrice de la petite enfance prépare des activités sensorielles."],
  ["Babysitting course", "le cours de gardiennage", "Le cours de gardiennage inclut la RCR pour nourrissons."],
  ["School board website", "le site du conseil scolaire", "Le site du conseil scolaire publie les calendriers."],
  ["Parent volunteer form", "le formulaire de bénévolat scolaire", "Complétez le formulaire de bénévolat scolaire pour l'excursion."],
  ["Report card conference", "la rencontre de bulletin", "La rencontre de bulletin dure quinze minutes par famille."],
  ["Press briefing", "le point de presse", "Le point de presse commence à quatorze heures."],
  ["News anchor", "le présentateur de nouvelles", "Le présentateur de nouvelles résume les titres du soir."],
  ["False rumour", "la rumeur infondée", "La rumeur infondée circule sans preuve sur les réseaux."],
  ["Fact-check article", "l'article de vérification", "L'article de vérification cite ses sources officielles."],
  ["Social media campaign", "la campagne sur les réseaux sociaux", "La campagne sur les réseaux sociaux mobilise les jeunes."],
  ["Viral clip", "la vidéo virale", "La vidéo virale a été partagée des milliers de fois."],
  ["Online petition", "la pétition en ligne", "La pétition en ligne exige mille signatures."],
  ["Municipal referendum", "le référendum municipal", "Le référendum municipal porte sur le nouveau aréna."],
  ["Political party platform", "le programme électoral", "Le programme électoral promet plus de logements."],
  ["Campaign promise", "la promesse électorale", "Chaque promesse électorale sera débattue en conseil."],
  ["Coalition agreement", "l'accord de coalition", "L'accord de coalition fixe les priorités du gouvernement."],
  ["Opposition critic", "le porte-parole de l'opposition", "Le porte-parole de l'opposition critique le budget."],
  ["Public hearing session", "l'audience publique", "L'audience publique recueille les commentaires des citoyens."],
  ["Whistleblower protection", "la protection des lanceurs d'alerte", "La protection des lanceurs d'alerte encourage la transparence."],
  ["Transparency report", "le rapport de transparence", "Le rapport de transparence détaille les dépenses municipales."],
  ["Advocacy group", "le groupe de pression", "Le groupe de pression défend les droits des locataires."],
  ["Charity fundraiser", "la levée de fonds", "La levée de fonds finance la nouvelle cuisine communautaire."],
  ["Public broadcaster", "la télévision publique", "La télévision publique diffuse le débat en direct."],
  ["Paywall subscription", "l'abonnement avec mur payant", "L'abonnement avec mur payant donne accès aux archives."],
  ["Copyright notice", "l'avis de droit d'auteur", "L'avis de droit d'auteur interdit la reproduction sans permission."],
  ["Satirical cartoon", "le dessin satirique", "Le dessin satirique commente la politique locale."],
  ["Letters to the editor", "la page des lettres", "La page des lettres publie les opinions des lecteurs."],
  ["Community radio show", "l'émission de radio communautaire", "L'émission de radio communautaire invite des artistes locaux."],
  ["Podcast host", "l'animateur de balado", "L'animateur de balado pose des questions aux invités."],
  ["Museum curator talk", "la conférence du conservateur", "La conférence du conservateur explique l'exposition."],
  ["Gallery opening night", "le vernissage", "Le vernissage attire plusieurs collectionneurs."],
  ["Theatre season pass", "l'abonnement de saison", "L'abonnement de saison inclut quatre pièces."],
  ["Symphony concert", "le concert de l'orchestre", "Le concert de l'orchestre commence à dix-neuf heures trente."],
  ["Folk music festival", "le festival de musique folklorique", "Le festival de musique folklorique met en vedette des violoneux."],
  ["Street mural project", "le projet de murale", "Le projet de murale colore le mur de l'école."],
  ["Graffiti removal program", "le programme de dégraffitage", "Le programme de dégraffitage nettoie les passages souterrains."],
  ["Cultural policy plan", "le plan culturel municipal", "Le plan culturel municipal finance les arts de rue."],
  ["Language rights complaint", "la plainte pour droits linguistiques", "Déposez une plainte pour droits linguistiques si le service est refusé en français."],
  ["Citizen journalism", "le journalisme citoyen", "Le journalisme citoyen couvre les conseils municipaux en direct."],
  ["Editorial endorsement", "le soutien éditorial", "Le soutien éditorial favorise la candidate indépendante."],
  ["Town hall debate", "le débat en assemblée publique", "Le débat en assemblée publique porte sur la taxe foncière."],
  ["Civic duty", "le devoir civique", "Le devoir civique inclut de s'informer avant de voter."],
  ["Voter turnout", "la participation électorale", "La participation électorale a augmenté lors du dernier scrutin."],
  ["Electoral district", "la circonscription électorale", "Votre circonscription électorale change après le découpage."],
  ["Polling station volunteer", "le bénévole de bureau de vote", "Le bénévole de bureau de vote vérifie la liste électorale."],
  ["Democratic debate", "le débat démocratique", "Le débat démocratique respecte les règles de parole."],
  ["Civil society forum", "le forum de la société civile", "Le forum de la société civile réunit associations et citoyens."],
  ["Media literacy class", "le cours d'éducation aux médias", "Le cours d'éducation aux médias enseigne à vérifier les sources."],
  ["Public square rally", "le rassemblement sur la place publique", "Le rassemblement sur la place publique demande plus de transports."],
  ["Cultural heritage site", "le site patrimonial", "Le site patrimonial est classé depuis 1985."],
  ["Volunteer orientation", "l'accueil des bénévoles", "L'accueil des bénévoles explique les tâches du festival."],
  ["Shift signup sheet", "la feuille d'inscription aux quarts", "Inscrivez-vous sur la feuille d'inscription aux quarts."],
  ["Winter coat drive", "la collecte de manteaux", "La collecte de manteaux aide les familles sans abri."],
  ["Toy drive", "la collecte de jouets", "La collecte de jouets se termine le quinze décembre."],
  ["Food hamper program", "le panier alimentaire", "Le panier alimentaire est distribué chaque mercredi."],
  ["Youth mentoring", "le mentorat jeunesse", "Le mentorat jeunesse jumelle un adulte et un adolescent."],
  ["Seniors' visiting program", "la visite aux aînés", "La visite aux aînés réduit l'isolement."],
  ["Park cleanup day", "la journée de nettoyage du parc", "La journée de nettoyage du parc commence à neuf heures."],
  ["Tree stewardship group", "le groupe d'entretien des arbres", "Le groupe d'entretien des arbres arrose les jeunes plantations."],
  ["Adopt-a-park program", "le programme d'adoption de parc", "Le programme d'adoption de parc engage les voisins."],
  ["Festival volunteer badge", "le badge de bénévole", "Portez le badge de bénévole en tout temps sur le site."],
  ["Ticket scanning volunteer", "le bénévole à la billetterie", "Le bénévole à la billetterie scanne les codes QR."],
  ["Bake sale fundraiser", "la vente de pâtisseries", "La vente de pâtisseries finance le voyage scolaire."],
  ["Community kitchen meal", "le repas communautaire", "Le repas communautaire est servi gratuitement le jeudi."],
  ["Potluck supper", "le souper-partage", "Apportez un plat au souper-partage du centre."],
  ["Neighbourhood picnic", "le pique-nique de quartier", "Le pique-nique de quartier se tient au parc Victor."],
  ["Open mic evening", "la soirée scène ouverte", "La soirée scène ouverte accueille poètes et musiciens."],
  ["Board game night", "la soirée jeux de société", "La soirée jeux de société est réservée aux adultes."],
  ["Sewing workshop", "l'atelier de couture", "L'atelier de couture apprend à recoudre un bouton."],
  ["Knitting circle", "le cercle de tricot", "Le cercle de tricot confectionne des tuques pour le refuge."],
  ["Recreational soccer league", "la ligue de soccer récréatif", "La ligue de soccer récréatif inscrit les équipes en avril."],
  ["Pickup basketball game", "le match de basketball improvisé", "Un match de basketball improvisé se forme au gymnase."],
  ["Community choir practice", "la pratique de chorale", "La pratique de chorale prépare le concert de Noël."],
  ["Welcome committee", "le comité d'accueil", "Le comité d'accueil visite les nouveaux résidents."],
  ["Mutual aid network", "le réseau d'entraide", "Le réseau d'entraide coordonne l'aide entre voisins."],
  ["Refugee welcome dinner", "le souper de bienvenue", "Le souper de bienvenue réunit familles parrainées et parrains."],
  ["Community survey", "le sondage communautaire", "Répondez au sondage communautaire sur les priorités du quartier."],
  ["Neighbourhood newsletter", "le bulletin de quartier", "Le bulletin de quartier annonce la fête des voisins."],
  ["Block captain", "le capitaine de rue", "Le capitaine de rue relaie les avis de la ville."],
  ["Tool lending library", "la bibliothèque d'outils", "La bibliothèque d'outils prête des perceuses aux résidents."],
];

export const BATCH7_C: LemmaRow[] = [
  ["In my opinion", "à mon avis", "À mon avis, la concertation devrait précéder la décision."],
  ["From my standpoint", "de mon point de vue", "De mon point de vue, la mesure est équilibrée."],
  ["It seems to me", "il me semble", "Il me semble que le délai est trop court."],
  ["I am convinced that", "je suis convaincu que", "Je suis convaincu que l'éducation est la priorité."],
  ["I am firmly opposed", "je suis fermement opposé", "Je suis fermement opposé à la fermeture de la piscine."],
  ["I fully endorse", "je soutiens pleinement", "Je soutiens pleinement la proposition du comité."],
  ["That goes too far", "cela va trop loin", "Cela va trop loin de restreindre la liberté de la presse."],
  ["That is debatable", "c'est discutable", "C'est discutable de prétendre que le problème est résolu."],
  ["There is no doubt", "il n'y a aucun doute", "Il n'y a aucun doute que la demande de logements augmente."],
  ["Needless to say", "inutile de dire", "Inutile de dire que la ponctualité est essentielle au travail."],
  ["When all is said and done", "en fin de compte", "En fin de compte, les citoyens jugeront les résultats."],
  ["On the one hand", "d'une part", "D'une part, le coût est élevé; d'autre part, les bénéfices sont réels."],
  ["By way of illustration", "à titre d'illustration", "À titre d'illustration, citons le cas de Québec."],
  ["To take an example", "pour prendre un exemple", "Pour prendre un exemple, plusieurs villes ont réussi la transition."],
  ["Concretely speaking", "concrètement", "Concrètement, il faut ajouter des autobus sur la ligne."],
  ["In practice", "en pratique", "En pratique, peu de citoyens participent aux consultations."],
  ["In theory", "en théorie", "En théorie, la loi protège les locataires; en pratique, les délais sont longs."],
  ["Up to a point", "jusqu'à un certain point", "Jusqu'à un certain point, votre argument est convaincant."],
  ["Broadly speaking", "de manière générale", "De manière générale, les services s'améliorent."],
  ["Strictly speaking", "strictement parlant", "Strictement parlant, le règlement ne s'applique pas ici."],
  ["It is worth noting", "il est à noter", "Il est à noter que les jeunes votent davantage."],
  ["It should be stressed", "il convient de souligner", "Il convient de souligner l'effort des bénévoles."],
  ["One might object that", "on pourrait objecter que", "On pourrait objecter que le budget est insuffisant."],
  ["Admittedly", "il est vrai que", "Il est vrai que les premiers résultats sont modestes."],
  ["Granted (concession)", "soit", "Soit, la mesure coûte cher, mais elle est nécessaire."],
  ["Not only... but also", "non seulement... mais aussi", "Non seulement le parc est agrandi, mais aussi sécurisé."],
  ["The central issue is", "la question centrale est", "La question centrale est l'accès aux soins en région."],
  ["What matters most is", "ce qui compte surtout", "Ce qui compte surtout, c'est la qualité du service."],
  ["I partly agree", "je suis partiellement d'accord", "Je suis partiellement d'accord avec votre conclusion."],
  ["I tend to believe", "j'ai tendance à croire", "J'ai tendance à croire que la situation s'améliorera."],
  ["It appears that", "il appert que", "Il appert que les données ont été mal interprétées."],
  ["According to specialists", "selon les spécialistes", "Selon les spécialistes, la pollution sonore augmente."],
  ["As the data show", "comme le montrent les données", "Comme le montrent les données, la fréquentation a doublé."],
  ["This reminds us that", "cela nous rappelle que", "Cela nous rappelle que le climat change rapidement."],
  ["Similarly", "de même", "De même, d'autres municipalités ont adopté la même politique."],
  ["Unlike", "contrairement à", "Contrairement à l'an dernier, la participation a augmenté."],
  ["In comparison", "en comparaison", "En comparaison, le service est plus rapide en banlieue."],
  ["I cannot agree with", "je ne peux pas souscrire à", "Je ne peux pas souscrire à cette interprétation."],
  ["We share the view that", "nous partageons l'avis que", "Nous partageons l'avis que la transparence est essentielle."],
  ["Let us not forget that", "n'oublions pas que", "N'oublions pas que derrière chaque statistique, il y a des familles."],
];
