import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 7 — Compréhension orale. Theme: public services, citizenship and civic life in Canada.
 *
 * `audioScript` is rendered by Edge TTS, so each script is written to be read
 * aloud cleanly: no bullet points, numbers spelled where ambiguous, and
 * dialogue turns separated by em dashes.
 */
export const TCF_LISTENING_P7: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "Au bureau de poste",
    audioScript: "— Bonjour, je voudrais envoyer cette lettre au Canada. — C'est pour quand ? — En courrier prioritaire, s'il vous plaît. — Très bien, cela fait huit dollars vingt.",
    question: "Combien coûte l'envoi ?",
    options: ["Six dollars.", "Huit dollars vingt.", "Dix dollars.", "Huit dollars."],
    correctIndex: 1,
    explanation: "The clerk says eight dollars twenty.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Annonce municipale",
    audioScript: "Votre attention, s'il vous plaît. La piscine municipale sera fermée pour entretien du lundi quinze au mercredi dix-sept juillet. Elle rouvrira jeudi à huit heures. Merci de votre compréhension.",
    question: "Quand la piscine rouvrira-t-elle ?",
    options: ["Le lundi quinze.", "Le mardi seize.", "Le mercredi dix-sept.", "Le jeudi suivant."],
    correctIndex: 3,
    explanation: "It reopens on Thursday at eight o'clock.",
  },
  {
    id: 3,
    level: "A1",
    topic: "À l'accueil",
    audioScript: "— Bonjour, je cherche le service des passeports. — C'est au deuxième étage, porte deux cent quatre. Prenez l'ascenseur à droite. — Merci beaucoup.",
    question: "Où se trouve le service des passeports ?",
    options: ["Au rez-de-chaussée.", "Au premier étage.", "Au deuxième étage.", "Au troisième étage."],
    correctIndex: 2,
    explanation: "Passport service is on the second floor, room 204.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Message radio",
    audioScript: "Rappel pour les automobilistes : le stationnement est gratuit dans le centre-ville ce samedi pour la fête du quartier. À partir de dimanche, les règles habituelles s'appliquent de nouveau.",
    question: "Quand le stationnement est-il gratuit ?",
    options: ["Toute la semaine.", "Ce samedi seulement.", "Samedi et dimanche.", "À partir de dimanche."],
    correctIndex: 1,
    explanation: "Parking is free downtown this Saturday for the neighbourhood festival.",
  },
  {
    id: 5,
    level: "A2",
    topic: "Service Canada",
    audioScript: "— J'ai besoin de mon numéro d'assurance sociale. — Avez-vous pris rendez-vous en ligne ? — Non, je suis venu directement. — Sans rendez-vous, nous ne pouvons pas vous recevoir aujourd'hui. Réservez un créneau sur le site.",
    question: "Pourquoi la personne n'est-elle pas reçue ?",
    options: [
      "Parce qu'elle n'a pas les bons documents.",
      "Parce qu'elle n'a pas de rendez-vous.",
      "Parce que le bureau est fermé.",
      "Parce que le service est réservé aux citoyens.",
    ],
    correctIndex: 1,
    explanation: "Without an online appointment they cannot be seen today.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Bibliothèque",
    audioScript: "— Je voudrais prolonger ce livre. — Il a été réservé par un autre lecteur, donc le renouvellement n'est pas possible. Vous pouvez le garder jusqu'à vendredi, date de retour indiquée sur la fiche.",
    question: "Pourquoi le renouvellement est-il refusé ?",
    options: [
      "Parce que le délai de trois semaines est dépassé.",
      "Parce qu'un autre lecteur a réservé le livre.",
      "Parce que la personne a déjà dix livres.",
      "Parce que le renouvellement se fait uniquement en ligne.",
    ],
    correctIndex: 1,
    explanation: "Another reader reserved the book, so renewal is blocked.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Jour de vote",
    audioScript: "— Excusez-moi, est-ce ici le bon bureau de vote pour l'adresse rue des Érables ? — Non, vous êtes au mauvais endroit. Le vôtre est à l'école du Parc, à cinq minutes en voiture. N'oubliez pas votre pièce d'identité.",
    question: "Que doit faire l'électeur ?",
    options: [
      "Voter ici avec sa carte d'électeur seulement.",
      "Se rendre à un autre bureau de vote.",
      "Attendre la fermeture du scrutin.",
      "Demander un bulletin par correspondance.",
    ],
    correctIndex: 1,
    explanation: "They are at the wrong polling station and must go to École du Parc.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Centre communautaire",
    audioScript: "L'atelier sur les impôts pour nouveaux arrivants aura lieu mercredi prochain de dix heures à midi. L'inscription est gratuite, mais obligatoire par téléphone avant lundi, car les places sont limitées à vingt personnes.",
    question: "Que faut-il faire pour participer ?",
    options: [
      "Payer une inscription sur place.",
      "S'inscrire par téléphone avant lundi.",
      "Apporter sa déclaration déjà remplie.",
      "Arriver sans réservation le mercredi.",
    ],
    correctIndex: 1,
    explanation: "Free registration by phone before Monday is required.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Plainte municipale",
    audioScript: "— Bonjour, je voudrais signaler un nid-de-poule sur la rue Principale. — Merci. Pouvez-vous préciser le numéro civique le plus proche ? — Vers le deux cent cinquante. — Parfait, une équipe passera d'ici quarante-huit heures.",
    question: "Que va faire la municipalité ?",
    options: [
      "Envoyer une équipe dans les deux jours.",
      "Fermer la rue immédiatement.",
      "Demander une photo par courriel.",
      "Transférer l'appel à la police.",
    ],
    correctIndex: 0,
    explanation: "A crew will come within forty-eight hours.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Cérémonie citoyenne",
    audioScript: "Chers invités, la cérémonie d'accueil des nouveaux citoyens commence dans quinze minutes. Veuillez prendre place et éteindre vos téléphones. Les photos sont autorisées seulement à la fin, pendant la réception.",
    question: "Quand peut-on prendre des photos ?",
    options: [
      "Pendant la cérémonie entière.",
      "Dès l'arrivée dans la salle.",
      "À la fin, pendant la réception.",
      "Uniquement à l'extérieur du bâtiment.",
    ],
    correctIndex: 2,
    explanation: "Photos are allowed only at the end during the reception.",
  },

  // ── B1–B2 (Q11–30) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Permis de conduire",
    audioScript: "— Je viens d'arriver au Manitoba, mon permis français est-il valide ? — Oui, pendant trois mois. Ensuite, vous devrez passer un examen théorique ici. Les cours de conduite hivernale sont recommandés, mais pas obligatoires pour l'échange.",
    question: "Que devra faire la personne après trois mois ?",
    options: [
      "Repasser l'examen pratique complet.",
      "Passer un examen théorique provincial.",
      "Renouveler son permis français.",
      "Suivre obligatoirement un cours d'hiver.",
    ],
    correctIndex: 1,
    explanation: "After three months she must pass the local theory exam.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Radio locale",
    audioScript: "La ville de Saskatoon lance une consultation sur le budget des bibliothèques. Les résidents peuvent commenter en ligne jusqu'au trente avril ou assister à la séance publique jeudi soir. Les propositions retenues seront annoncées en juin.",
    question: "Comment les citoyens peuvent-ils participer ?",
    options: [
      "Uniquement en votant le jour de l'élection.",
      "En ligne ou à une séance publique.",
      "En envoyant un chèque à la bibliothèque.",
      "En signant une pétition papier en mairie.",
    ],
    correctIndex: 1,
    explanation: "They may comment online or attend the public meeting Thursday evening.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Entre voisins",
    audioScript: "— As-tu vu le dépliant sur le compost ? — Oui, la collecte passe au mercredi maintenant. — Et le bac vert ? — On le sort la veille au soir, pas le matin, sinon les écureuils l'ouvrent.",
    question: "Quand faut-il sortir le bac vert ?",
    options: [
      "Le mercredi matin.",
      "La veille au soir.",
      "Le jeudi matin.",
      "Uniquement en été.",
    ],
    correctIndex: 1,
    explanation: "The green bin goes out the evening before, not in the morning.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Reportage",
    audioScript: "Dans plusieurs provinces, les cliniques communautaires offrent des services médicaux aux personnes sans médecin de famille. Elles ne remplacent pas les urgences, mais elles réduisent les visites inutiles à l'hôpital pour des problèmes mineurs.",
    question: "Quel rôle jouent ces cliniques ?",
    options: [
      "Elles remplacent les services d'urgence.",
      "Elles prennent en charge des cas non urgents.",
      "Elles réservent les soins aux citoyens seulement.",
      "Elles emploient uniquement des médecins spécialistes.",
    ],
    correctIndex: 1,
    explanation: "They handle minor issues for people without a family doctor.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Guichet municipal",
    audioScript: "— Je voudrais un permis pour construire une clôture. — Le règlement autorise une hauteur maximale de un mètre vingt à l'avant. Vous devez joindre un plan et payer les frais de cent vingt dollars. Le délai d'analyse est de quatre semaines.",
    question: "Quelle information le fonctionnaire donne-t-il ?",
    options: [
      "La clôture est interdite à l'avant de la maison.",
      "Il faut un plan et payer cent vingt dollars.",
      "Le permis est délivré le jour même.",
      "Seul un architecte peut déposer le dossier.",
    ],
    correctIndex: 1,
    explanation: "A plan is required and the fee is one hundred twenty dollars.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Annonce d'organisme",
    audioScript: "L'organisme Accueil Plus recrute des bénévoles pour accompagner les nouveaux résidents lors de leurs premières démarches : carte santé, école des enfants, transport. Une formation de six heures est offerte le premier samedi de chaque mois.",
    question: "Que proposent les bénévoles ?",
    options: [
      "Des cours de français intensifs payants.",
      "De l'aide pour les démarches administratives de base.",
      "Un service de garde d'enfants gratuit.",
      "Des conseils juridiques pour les demandes d'asile.",
    ],
    correctIndex: 1,
    explanation: "Volunteers help with health cards, school, and transport steps.",
  },
  {
    id: 17,
    level: "B1",
    topic: "Interview citoyenne",
    audioScript: "— Pourquoi servez-vous de juré ? — Parce que c'est une responsabilité citoyenne. On ne choisit pas toujours le moment, mais sans jurés, le système s'arrête. Mon employeur est obligé de me libérer, même si ce n'est pas toujours facile pour l'équipe.",
    question: "Pourquoi la personne accepte d'être juré ?",
    options: [
      "Parce que cela augmente son salaire.",
      "Parce qu'elle considère que c'est un devoir civique.",
      "Parce que son employeur l'y oblige personnellement.",
      "Parce qu'elle prépare une carrière juridique.",
    ],
    correctIndex: 1,
    explanation: "She sees jury duty as a citizen responsibility.",
  },
  {
    id: 18,
    level: "B1",
    topic: "Service des impôts",
    audioScript: "— Je n'ai pas reçu mon avis de cotisation. — Avez-vous créé un compte Mon dossier ? Les avis sont maintenant numériques par défaut. — Non. — Je peux vous aider à l'ouvrir maintenant ; vous recevrez aussi les lettres papier si vous l'activez.",
    question: "Pourquoi la personne n'a-t-elle pas reçu de papier ?",
    options: [
      "Parce qu'elle a une dette fiscale.",
      "Parce que les avis sont numériques par défaut.",
      "Parce que sa déclaration est en retard.",
      "Parce qu'elle n'est pas citoyenne canadienne.",
    ],
    correctIndex: 1,
    explanation: "Notices are digital by default unless paper is enabled in My Account.",
  },
  {
    id: 19,
    level: "B1",
    topic: "Conseil municipal",
    audioScript: "— Cette séance est ouverte au public, mais les interventions sont limitées à trois minutes. — Puis-je parler en français ? — Oui, un interprète est disponible si vous le demandez vingt-quatre heures à l'avance.",
    question: "Que faut-il faire pour obtenir un interprète ?",
    options: [
      "Arriver une heure avant la séance.",
      "Faire la demande vingt-quatre heures à l'avance.",
      "Écrire son discours en anglais uniquement.",
      "Payer un supplément à l'entrée.",
    ],
    correctIndex: 1,
    explanation: "An interpreter is available if requested twenty-four hours ahead.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Débat radiophonique",
    audioScript: "— Le vote obligatoire augmenterait la participation. — Peut-être, mais punir l'abstention ne crée pas l'intérêt pour les enjeux. On risque surtout de remplir les urnes de bulletins au hasard. Mieux vaut investir dans l'éducation civique avant l'élection.",
    question: "Quel argument le second intervenant oppose-t-il ?",
    options: [
      "Le vote obligatoire est interdit par la Constitution.",
      "La contrainte n'engendre pas un vote réfléchi.",
      "La participation est déjà suffisamment élevée.",
      "L'éducation civique coûte trop cher.",
    ],
    correctIndex: 1,
    explanation: "Punishing abstention may fill ballots without genuine engagement.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Conférence",
    audioScript: "Les données ouvertes municipales permettent de suivre les dépenses en temps réel, mais leur format technique décourage le grand public. Sans médiation journalistique ou associative, la transparence reste théorique : les fichiers existent, peu de citoyens savent quoi en faire.",
    question: "Quel obstacle la conférencière souligne-t-elle ?",
    options: [
      "Le refus des villes de publier les données.",
      "La difficulté pour le public d'utiliser les données brutes.",
      "L'absence de loi sur la transparence.",
      "La censure des médias locaux.",
    ],
    correctIndex: 1,
    explanation: "Technical formats deter the public without mediation.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Entretien avec un ombudsman",
    audioScript: "— Que pouvez-vous faire concrètement ? — Je ne peux pas annuler une loi, mais je peux recommander qu'un ministère corrige un dossier et publier un rapport. L'effet vient surtout de la pression publique : aucun responsable n'aime apparaître comme défaillant.",
    question: "Sur quoi repose l'efficacité de l'ombudsman ?",
    options: [
      "Sur le pouvoir de modifier les lois.",
      "Sur la menace de rapports publics embarrassants.",
      "Sur des amendes payées par les citoyens.",
      "Sur le financement privé de son bureau.",
    ],
    correctIndex: 1,
    explanation: "Public reports shame ministries into correcting files.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Chronique fiscale",
    audioScript: "Beaucoup de nouveaux arrivants ignorent qu'ils doivent déclarer leurs revenus mondiaux la première année. Ce n'est pas une option : l'administration fiscale croise les données avec l'immigration. Une déclaration incomplète peut retarder des prestations familiales pourtant bienvenues.",
    question: "Quel risque la chronique mentionne-t-elle ?",
    options: [
      "Perdre automatiquement le statut de résident.",
      "Retarder l'accès à certaines prestations.",
      "Payer deux fois les mêmes impôts.",
      "Être exclu du système de santé public.",
    ],
    correctIndex: 1,
    explanation: "An incomplete return can delay family benefits.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Table ronde",
    audioScript: "— Les budgets participatifs sont démocratiques. — Ils le sont pour ceux qui ont le temps d'assister aux réunions. Les parents célibataires en horaires décalés votent rarement, donc les projets visibles — parcs, murals — gagnent, pas l'accessibilité des formulaires.",
    question: "Quelle critique est formulée ?",
    options: [
      "Les budgets participatifs coûtent plus que les élections.",
      "Ils favorisent les citoyens les plus disponibles.",
      "Ils sont interdits dans les petites villes.",
      "Ils ne concernent que les dépenses culturelles.",
    ],
    correctIndex: 1,
    explanation: "Those with time attend; visible projects beat less visible needs.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Reportage social",
    audioScript: "À Vancouver, une ligne téléphonique multilingue oriente les résidents vers les services municipaux. Les appels augmentent l'hiver, quand les personnes isolées cherchent chauffage ou nourriture. Les opérateurs ne remplacent pas les travailleurs sociaux, mais ils réduisent le temps perdu à appeler le mauvais ministère.",
    question: "Quel est l'objectif principal de cette ligne ?",
    options: [
      "Remplacer les urgences médicales.",
      "Diriger les appelants vers le bon service.",
      "Financer des repas chauds.",
      "Former des travailleurs sociaux.",
    ],
    correctIndex: 1,
    explanation: "Operators route callers to the right municipal or government service.",
  },
  {
    id: 26,
    level: "B2",
    topic: "Documentaire",
    audioScript: "Le film suit trois familles qui obtiennent la citoyenneté. Il montre la cérémonie, mais aussi les mois précédents : cours, tests, frais. L'une des mères dit que le plus difficile n'était pas l'examen, mais l'attente entre chaque étape administrative sans savoir si le dossier avancerait.",
    question: "Quelle difficulté la mère souligne-t-elle ?",
    options: [
      "La complexité des questions du test.",
      "L'incertitude pendant les longues étapes administratives.",
      "Le refus de parler français à la cérémonie.",
      "Le coût élevé des cours de préparation.",
    ],
    correctIndex: 1,
    explanation: "The hardest part was waiting between administrative steps.",
  },
  {
    id: 27,
    level: "B2",
    topic: "Interview",
    audioScript: "— Pourquoi les jeunes votent-ils moins ? — Ils ne voient pas le lien entre un bulletin et leur quotidien. Quand une campagne parle seulement de retraites, un étudiant de vingt ans se sent exclu du récit. Les candidats qui parlent logement et transport mobilisent davantage cette tranche d'âge.",
    question: "Selon l'interviewé, comment mobiliser les jeunes ?",
    options: [
      "En rendant le vote obligatoire.",
      "En abordant des enjeux qui les concernent directement.",
      "En supprimant le vote par anticipation.",
      "En organisant des concerts le jour de l'élection.",
    ],
    correctIndex: 1,
    explanation: "Talking about housing and transport connects elections to their daily lives.",
  },
  {
    id: 28,
    level: "B2",
    topic: "Débat municipal",
    audioScript: "— Taxer les sacs plastiques réduit les déchets. — Les données de Toronto le montrent, mais dans notre ville, les commerces proposent déjà des sacs réutilisables. Une taxe supplémentaire pénalise surtout les familles à bas revenu qui achètent au dépanneur du coin.",
    question: "Quel argument le second orateur utilise-t-il ?",
    options: [
      "La taxe est illégale au niveau provincial.",
      "Elle frappe surtout les ménages modestes.",
      "Les sacs réutilisables sont dangereux pour la santé.",
      "Les déchets plastiques ne posent plus de problème.",
    ],
    correctIndex: 1,
    explanation: "An extra tax mainly hurts low-income families shopping at corner stores.",
  },
  {
    id: 29,
    level: "B2",
    topic: "Chronique",
    audioScript: "Servir de bénévole dans un refuge d'urgence m'a appris plus sur la citoyenneté que n'importe quel manuel. On voit comment les subventions fédérales et provinciales se croisent, où les filets se déchirent. La politique n'est plus abstraite quand on aide quelqu'un à remplir un formulaire avant la fermeture du guichet.",
    question: "Qu'apprend l'auteur en faisant du bénévolat ?",
    options: [
      "Que les manuels civiques sont inutiles.",
      "Comment les politiques publiques affectent des situations concrètes.",
      "Que les refuges sont entièrement financés par Ottawa.",
      "Que les bénévoles remplacent les travailleurs sociaux.",
    ],
    correctIndex: 1,
    explanation: "Volunteering shows how policies intersect in real people's lives.",
  },
  {
    id: 30,
    level: "B2",
    topic: "Analyse institutionnelle",
    audioScript: "Quand un citoyen se plaint que « l'État » l'a mal traité, il mélange souvent trois niveaux : fédéral, provincial, municipal. Les guichets uniques avancent lentement parce que chaque administration garde ses bases de données. Clarifier qui fait quoi est déjà un progrès civique majeur.",
    question: "Quel problème le commentateur décrit-il ?",
    options: [
      "L'absence totale de services en ligne.",
      "La confusion entre les niveaux de gouvernement.",
      "Le refus des citoyens d'utiliser Internet.",
      "La suppression des mairies de quartier.",
    ],
    correctIndex: 1,
    explanation: "Citizens confuse federal, provincial, and municipal responsibilities.",
  },

  // ── C1–C2 (Q31–39) ─────────────────────────────────────────────
  {
    id: 31,
    level: "C1",
    topic: "Conférence universitaire",
    audioScript: "La citoyenneté numérique ne se réduit pas à repérer les fausses nouvelles. Elle suppose de comprendre quels renseignements un ministère peut exiger, comment contester une décision et quels courriels conserver. Sans ces compétences, l'accès aux droits reste théorique pour des citoyens pourtant connectés.",
    question: "Quelle définition la conférencière propose-t-elle ?",
    options: [
      "Savoir utiliser les réseaux sociaux sans se faire arnaquer.",
      "Maîtriser les démarches et droits liés aux services publics en ligne.",
      "Refuser toute communication numérique avec l'État.",
      "Créer des comptes sur toutes les plateformes gouvernementales.",
    ],
    correctIndex: 1,
    explanation: "Digital citizenship includes navigating official portals and rights.",
  },
  {
    id: 32,
    level: "C1",
    topic: "Séminaire de droit",
    audioScript: "La Charte autorise des limites raisonnables aux libertés. En matière scolaire, les exemptions religieuses illustrent ce compromis : l'État protège la conscience, mais impose parfois des règles communes. Chaque province interprète cet équilibre différemment, d'où la confusion des familles qui déménagent.",
    question: "Quel phénomène l'intervenant souligne-t-il ?",
    options: [
      "L'interdiction des exemptions partout au Canada.",
      "Des règles variables selon les provinces.",
      "La suppression des écoles publiques.",
      "L'obligation de suivre un enseignement religieux.",
    ],
    correctIndex: 1,
    explanation: "Each province interprets reasonable limits differently.",
  },
  {
    id: 33,
    level: "C1",
    topic: "Débat éthique",
    audioScript: "— Le vote par correspondance élargit la participation. — À quel prix ? Le secret du scrutin suppose une cabine isolée. Chez soi, la pression familiale ou conjugale est réelle. Les fraudes restent rares, mais l'égalité devant l'urne est une valeur qu'on ne mesure pas seulement en taux de participation.",
    question: "Quel argument le second intervenant développe-t-il ?",
    options: [
      "Le vote par correspondance est toujours frauduleux.",
      "Le scrutin à domicile peut compromettre le secret du vote.",
      "La participation électorale est trop élevée.",
      "Les bureaux de vote doivent être supprimés.",
    ],
    correctIndex: 1,
    explanation: "Home voting risks pressure that undermines ballot secrecy.",
  },
  {
    id: 34,
    level: "C1",
    topic: "Cours de sociologie",
    audioScript: "Les enquêtes sur la confiance institutionnelle montrent un effet de halo : une mauvaise expérience avec un ministère colore la perception de tous les autres, même sans contact direct. Les réformes ciblées peinent donc à restaurer la confiance globale, car le problème est symbolique autant qu'administratif.",
    question: "Pourquoi les réformes ciblées sont-elles limitées ?",
    options: [
      "Parce que les citoyens ne lisent pas les rapports.",
      "Parce que la méfiance se propage entre institutions.",
      "Parce que les ministères refusent toute critique.",
      "Parce que les sondages sont illégaux.",
    ],
    correctIndex: 1,
    explanation: "Distrust spreads in a halo across institutions beyond direct experience.",
  },
  {
    id: 35,
    level: "C1",
    topic: "Exposé économique",
    audioScript: "Comparer l'efficacité de deux politiques sociales exige un scénario de ce qui se serait passé sans elles. Or ce contrefactuel est invisible. Une aide qui ralentit un déclin peut paraître inutile si l'on ne mesure que l'état final, pas la trajectoire. L'évaluation devient alors un débat sur des fantômes.",
    question: "Quel obstacle méthodologique l'intervenant décrit-il ?",
    options: [
      "L'absence de données sur les bénéficiaires.",
      "L'impossibilité d'observer la situation sans la politique.",
      "Le refus des gouvernements de publier les chiffres.",
      "La fraude massive dans les déclarations.",
    ],
    correctIndex: 1,
    explanation: "Without a counterfactual, slowing decline looks like failure.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Conférence de philosophie",
    audioScript: "Obéir par crainte de la sanction diffère d'obéir parce qu'on reconnaît une règle comme sienne. Les administrations publiques supposent souvent le premier cas : formulaires, menaces, délais. La civilité démocratique naît quand l'institution cesse de croire que sans contrainte visible, le citoyen déserterait.",
    question: "Quel décalage le philosophe décrit-il ?",
    options: [
      "Entre citoyens nés au pays et naturalisés.",
      "Entre citoyen autonome et administration coercitive.",
      "Entre vote municipal et vote fédéral.",
      "Entre services en ligne et guichets physiques.",
    ],
    correctIndex: 1,
    explanation: "Institutions assume coercion while democratic civility expects internalized rules.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Séminaire d'histoire",
    audioScript: "Demander aux nouveaux citoyens de jurer allégeance tout en leur apprenant plus tard les chapitres sombres du passé national crée deux registres : la célébration et la lucidité. Peu de discours officiels articulent ces deux exigences, ce qui laisse un sentiment de double langage.",
    question: "Quelle tension le séminariste souligne-t-il ?",
    options: [
      "Entre français et anglais dans les cérémonies.",
      "Entre célébration de l'appartenance et critique historique.",
      "Entre monarchie et république.",
      "Entre vote obligatoire et volontaire.",
    ],
    correctIndex: 1,
    explanation: "Ceremonies celebrate belonging while later teaching demands critical lucidity.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Colloque sur la démocratie",
    audioScript: "Les référendums figent une question que la délibération continue aurait transformée. Plus une société revendique la participation, plus elle utilise des outils binaires qui appauvrissent l'échange. Le paradoxe n'est pas technique, il est politique : on mesure la démocratie par des instruments qui réduisent sa profondeur.",
    question: "Quel paradoxe est présenté ?",
    options: [
      "La participation augmente mais les électeurs sont moins nombreux.",
      "On promeut la délibération tout en utilisant des votes oui-non.",
      "Les référendums sont interdits au Canada.",
      "Les assemblées publiques remplacent les élections.",
    ],
    correctIndex: 1,
    explanation: "Deliberative ideals clash with binary referendums that shrink debate.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Conférence sur la citoyenneté",
    audioScript: "Réduire la citoyenneté au statut juridique ou au geste du vote oublie la pratique distribuée : payer ses impôts, servir de juré, respecter les règles du voisinage. La démocratie se maintient entre deux élections par ces actes ordinaires, rarement célébrés mais essentiels.",
    question: "Quelle conception de la citoyenneté l'intervenant défend-il ?",
    options: [
      "Une citoyenneté limitée au droit de vote.",
      "Une citoyenneté faite d'actes civiques quotidiens.",
      "Une citoyenneté réservée aux personnes nées au pays.",
      "Une citoyenneté fondée uniquement sur le paiement d'impôts.",
    ],
    correctIndex: 1,
    explanation: "Citizenship is practiced through everyday civic acts, not only voting.",
  },
];
