import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

export const TCF_READING_P5: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "CENTRE D'ACCUEIL DES IMMIGRANTS\nServices gratuits :\n• Aide à la traduction\n• Orientation vers les services publics\n• Cours de langue\nLundi–vendredi 9h–17h · Sans rendez-vous",
    question: "Faut-il prendre rendez-vous pour se rendre au centre d'accueil ?",
    options: ["Oui, obligatoirement.", "Oui, sauf le vendredi.", "Non, le centre reçoit sans rendez-vous.", "Seulement pour les cours de langue."],
    correctIndex: 2,
    explanation: "Le panneau précise que le centre reçoit les personnes sans rendez-vous.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Email",
    passage: "Bonjour Monsieur Ndiaye,\nVotre contrat de travail est prêt. Merci de passer le signer à nos bureaux avec une pièce d'identité. Nous sommes disponibles du lundi au vendredi de 9h à 12h et de 14h à 17h.\nCordialement, RH",
    question: "Que doit apporter M. Ndiaye pour signer son contrat ?",
    options: ["Son diplôme.", "Ses références professionnelles.", "Une pièce d'identité.", "Un relevé bancaire."],
    correctIndex: 2,
    explanation: "M. Ndiaye doit apporter une pièce d'identité pour signer son contrat de travail.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Affiche",
    passage: "CONCERT DE BIENVENUE\nOrchestre symphonique de Montréal\nSamedi 10 mai · 20h\nGrande Salle Wilfrid-Pelletier\nEntrée libre pour les nouveaux résidents sur présentation du permis de séjour",
    question: "Qui peut assister gratuitement au concert ?",
    options: ["Tous les étudiants.", "Les membres de l'orchestre.", "Les nouveaux résidents avec un permis de séjour.", "Les enfants de moins de 12 ans."],
    correctIndex: 2,
    explanation: "Les nouveaux résidents peuvent assister gratuitement sur présentation de leur permis de séjour.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Message",
    passage: "Chers habitants du 25 rue Voltaire,\nLes travaux dans la cage d'escalier commenceront lundi matin. Ils dureront environ une semaine. L'accès au parking reste possible. Merci de votre compréhension.\nLe Syndic",
    question: "Pendant combien de temps les travaux vont-ils durer ?",
    options: ["Deux jours.", "Trois jours.", "Une semaine.", "Deux semaines."],
    correctIndex: 2,
    explanation: "Les travaux dureront environ une semaine selon la note du syndic.",
  },
  {
    id: 5,
    level: "A1",
    passageType: "Menu",
    passage: "MENU VÉGÉTARIEN DU JOUR\n🥗 Entrée : Salade de lentilles et feta\n🌿 Plat : Curry de légumes, riz basmati\n🍮 Dessert : Panna cotta à la vanille\n12 € · Boisson non comprise",
    question: "Qu'est-ce qui n'est pas compris dans le prix du menu ?",
    options: ["L'entrée.", "Le dessert.", "Le plat.", "La boisson."],
    correctIndex: 3,
    explanation: "Le menu coûte 12 €, boisson non comprise.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Règlement",
    passage: "RÈGLEMENT DU GYMNASE\n• Tenue de sport obligatoire\n• Chaussures de sport uniquement (pas de crampons)\n• Douches disponibles après 17h uniquement\n• Réservation des courts de badminton en ligne\n• Interdit aux moins de 16 ans non accompagnés",
    question: "À partir de quel âge peut-on utiliser le gymnase seul ?",
    options: ["12 ans.", "14 ans.", "16 ans.", "18 ans."],
    correctIndex: 2,
    explanation: "Les moins de 16 ans ne peuvent pas utiliser le gymnase sans être accompagnés.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Article court",
    passage: "La fondue savoyarde est un plat traditionnel des Alpes françaises. Elle est préparée avec du fromage fondu dans du vin blanc. On y trempe des morceaux de pain avec une fourchette à long manche. Si on perd son pain dans le fromage, on offre un verre de vin à la table !",
    question: "Quelle est la coutume si on perd son pain dans la fondue ?",
    options: ["On doit refaire toute la fondue.", "On offre un verre de vin à la table.", "On quitte la table.", "On paie un supplément."],
    correctIndex: 1,
    explanation: "Si on perd son pain dans le fromage, on offre un verre de vin à tous les convives.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "Email",
    passage: "Objet : Changement d'adresse\n\nBonjour,\nJe vous informe que je déménage le 1er mars. Ma nouvelle adresse sera : 45 avenue des Tilleuls, 69003 Lyon. Merci de mettre à jour mes coordonnées dans votre système.\nCordialement, Mme Kowalski",
    question: "Pourquoi Mme Kowalski envoie-t-elle cet email ?",
    options: ["Pour annuler son abonnement.", "Pour signaler un problème de livraison.", "Pour informer d'un changement d'adresse.", "Pour demander un remboursement."],
    correctIndex: 2,
    explanation: "Mme Kowalski informe de son déménagement et demande de mettre à jour son adresse.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Affiche",
    passage: "JOURNÉE PORTES OUVERTES\nUniversité du Québec à Montréal\nSamedi 25 novembre · 10h–16h\nDécouvrez nos 300 programmes\nRencontrez des étudiants et professeurs\nTransport gratuit depuis la station Berri-UQAM",
    question: "Comment peut-on se rendre gratuitement à l'université lors de la journée portes ouvertes ?",
    options: ["En réservant un covoiturage.", "Avec un bus spécial gratuit.", "Depuis la station Berri-UQAM.", "En vélo via les pistes cyclables."],
    correctIndex: 2,
    explanation: "Un transport gratuit est offert depuis la station de métro Berri-UQAM.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Formulaire",
    passage: "DEMANDE DE CARTE DE BIBLIOTHÈQUE\nPièces requises :\n• Pièce d'identité en cours de validité\n• Justificatif de domicile (- de 3 mois)\n• 1 photo d'identité\nCoût : Gratuit pour les résidents | 10 € pour les non-résidents\nValidité : 1 an renouvelable",
    question: "Combien coûte la carte de bibliothèque pour un résident ?",
    options: ["5 €.", "10 €.", "Gratuit.", "15 €."],
    correctIndex: 2,
    explanation: "La carte de bibliothèque est gratuite pour les résidents.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Le bénévolat de compétences consiste à mettre son expertise professionnelle au service d'une association ou d'une ONG. Contrairement au bénévolat classique, il mobilise des compétences spécifiques — juridiques, comptables, informatiques ou managériales. Ce type de bénévolat est de plus en plus valorisé par les entreprises dans le cadre de leur responsabilité sociale.",
    question: "Qu'est-ce qui distingue le bénévolat de compétences du bénévolat classique ?",
    options: ["Il est rémunéré symboliquement.", "Il mobilise des expertises professionnelles spécifiques.", "Il dure moins longtemps.", "Il s'adresse uniquement aux retraités."],
    correctIndex: 1,
    explanation: "Le bénévolat de compétences se distingue par l'apport d'une expertise professionnelle spécifique.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Article",
    passage: "Le programme Erasmus+ permet aux jeunes Européens de partir en stage dans un pays membre de l'UE avec une aide financière. Cette mobilité professionnelle, au-delà de l'expérience linguistique, développe des compétences transversales très valorisées par les employeurs : adaptabilité, gestion de l'incertitude, et intelligence interculturelle.",
    question: "Quelles compétences transversales Erasmus+ développe-t-il selon l'article ?",
    options: ["Compétences techniques et informatiques.", "Adaptabilité, gestion de l'incertitude, intelligence interculturelle.", "Leadership et management d'équipe.", "Rédaction professionnelle et présentation orale."],
    correctIndex: 1,
    explanation: "Erasmus+ développe l'adaptabilité, la gestion de l'incertitude et l'intelligence interculturelle.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Article",
    passage: "Le télétravail généralisé a bouleversé les habitudes des entreprises et des salariés. Si beaucoup apprécient la flexibilité et la réduction du temps de trajet, d'autres souffrent de l'isolement et de la difficulté à séparer vie professionnelle et personnelle. Les entreprises cherchent désormais un équilibre entre présentiel et distanciel adapté à chaque métier.",
    question: "Quel problème certains télétravailleurs rencontrent-ils ?",
    options: ["Des difficultés techniques liées aux outils numériques.", "L'isolement et la confusion entre vie professionnelle et personnelle.", "Un manque de reconnaissance de leur travail.", "Une réduction de leur salaire."],
    correctIndex: 1,
    explanation: "Certains télétravailleurs souffrent d'isolement et de difficultés à séparer vie pro et personnelle.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Article",
    passage: "Le Canada a mis en place un système d'immigration à points, Entrée express, qui sélectionne les candidats selon leur âge, leur niveau d'études, leur expérience professionnelle et leur maîtrise du français ou de l'anglais. Ce système vise à attirer des travailleurs qualifiés capables de contribuer rapidement à l'économie canadienne.",
    question: "Quels critères le système Entrée express évalue-t-il ?",
    options: ["La fortune personnelle et l'investissement prévu.", "L'âge, les études, l'expérience et la maîtrise du français ou de l'anglais.", "La nationalité et les liens familiaux au Canada.", "Le niveau de revenus et les économies disponibles."],
    correctIndex: 1,
    explanation: "Entrée express évalue l'âge, le niveau d'études, l'expérience professionnelle et la maîtrise linguistique.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Le mouvement pour la santé mentale positive cherche à dépasser la définition de la santé mentale comme simple absence de maladie. Il insiste sur le bien-être subjectif, la résilience, et la capacité à mener une vie épanouissante. Des initiatives comme les semaines de la santé mentale visent à déstigmatiser les troubles psychologiques et encourager les personnes à chercher de l'aide.",
    question: "Comment le mouvement pour la santé mentale positive définit-il la santé mentale ?",
    options: ["Comme l'absence de tout trouble psychologique.", "Comme le bien-être subjectif, la résilience et la capacité à s'épanouir.", "Comme la prise régulière de médicaments préventifs.", "Comme la fréquentation régulière d'un thérapeute."],
    correctIndex: 1,
    explanation: "La santé mentale positive dépasse l'absence de maladie pour inclure le bien-être, la résilience et l'épanouissement.",
  },
  {
    id: 16,
    level: "B2",
    passageType: "Article",
    passage: "La sobriété numérique désigne la réduction volontaire de l'empreinte environnementale du numérique. Contrairement à une idée reçue, Internet n'est pas immatériel : il repose sur des centres de données énergivores, des milliers de kilomètres de câbles et des terminaux qui nécessitent des matières premières rares. La consommation numérique mondiale représente environ 4 % des émissions mondiales de gaz à effet de serre.",
    question: "Quelle idée reçue sur Internet cet article réfute-t-il ?",
    options: ["Qu'Internet est gratuit pour les utilisateurs.", "Qu'Internet est immatériel et sans impact environnemental.", "Qu'Internet favorise la désinformation.", "Qu'Internet est accessible à tous."],
    correctIndex: 1,
    explanation: "L'article réfute l'idée qu'Internet est immatériel en montrant son impact environnemental concret.",
  },
  {
    id: 17,
    level: "B2",
    passageType: "Article",
    passage: "Le modèle québécois de garde d'enfants à contribution réduite (CPE) est souvent cité comme exemple de politique familiale efficace. En offrant des places en garderie à 10 $ par jour, le Québec a permis à davantage de mères de retourner sur le marché du travail, réduisant ainsi la pauvreté des familles monoparentales. Les études montrent que ce programme génère plus de revenus fiscaux qu'il ne coûte.",
    question: "Quel impact économique principal le programme CPE a-t-il eu ?",
    options: ["Il a réduit les dépenses de santé des familles.", "Il a permis à plus de mères de travailler, générant plus de recettes fiscales qu'il ne coûte.", "Il a stimulé l'industrie de la petite enfance.", "Il a réduit les inégalités entre régions du Québec."],
    correctIndex: 1,
    explanation: "Le CPE a permis le retour des mères au travail et génère des recettes fiscales supérieures à son coût.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Éditorial",
    passage: "La désinformation en ligne n'est pas un phénomène nouveau mais la vitesse de propagation des réseaux sociaux lui confère une dimension inédite. Les « infodémies » — épidémies d'informations fausses — peuvent paralyser les politiques de santé publique, comme on l'a vu durant la pandémie de COVID-19. Former les citoyens à la vérification des sources est une nécessité démocratique urgente.",
    question: "Qu'est-ce qu'une « infodémie » selon cet éditorial ?",
    options: ["Une épidémie causée par la désinformation médicale.", "Une épidémie de fausses informations qui peut paralyser des politiques publiques.", "Une étude statistique sur les effets de l'information.", "Une campagne de communication gouvernementale en période d'épidémie."],
    correctIndex: 1,
    explanation: "Une infodémie est une épidémie de fausses informations pouvant paralyser les politiques publiques.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement des Autochtones au Canada réclame la mise en œuvre des 94 appels à l'action de la Commission Vérité et Réconciliation. Ces recommandations portent notamment sur l'éducation, la justice, la santé et la langue. Malgré des progrès ponctuels, les organisations autochtones dénoncent la lenteur des gouvernements à honorer ces engagements.",
    question: "Que dénoncent les organisations autochtones au Canada ?",
    options: ["L'absence de représentation dans les médias.", "La lenteur des gouvernements à mettre en œuvre les appels à l'action.", "Le refus d'accorder la citoyenneté aux Autochtones.", "Le manque de terres accordées aux communautés."],
    correctIndex: 1,
    explanation: "Les organisations autochtones dénoncent la lenteur des gouvernements à mettre en œuvre les 94 appels à l'action.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "La médiation pénale offre une alternative aux poursuites judiciaires pour des infractions mineures. Elle met face à face l'auteur des faits et la victime, permettant une réparation directe et une prise de responsabilité. Si cette approche restauratrice est plébiscitée par certains juristes, elle suscite des inquiétudes concernant la protection des victimes et les risques de pression informelle.",
    question: "Quelles inquiétudes la médiation pénale suscite-t-elle ?",
    options: ["Son coût élevé pour le système judiciaire.", "La protection des victimes et les risques de pression informelle.", "Le manque de formation des médiateurs.", "La durée excessive des procédures de médiation."],
    correctIndex: 1,
    explanation: "La médiation pénale suscite des inquiétudes sur la protection des victimes et le risque de pression informelle.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Article",
    passage: "La francophonie numérique fait face à un défi de taille : le français ne représente que 3 % du contenu en ligne, contre plus de 55 % pour l'anglais. Cette sous-représentation numérique menace à terme la vitalité de la langue dans les espaces où elle s'exprime. Des initiatives comme le Plan pour la langue française cherchent à encourager la création de contenus francophones de qualité.",
    question: "Quel défi la francophonie numérique doit-elle relever ?",
    options: ["Le coût élevé des connexions internet dans les pays francophones.", "La faible représentation du français en ligne, seulement 3% du contenu web.", "La traduction automatique qui menace la qualité du français.", "Le manque de programmeurs et développeurs francophones."],
    correctIndex: 1,
    explanation: "Le français ne représente que 3% du contenu en ligne, ce qui menace sa vitalité dans les espaces numériques.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Article",
    passage: "La revitalisation des langues autochtones est un enjeu culturel majeur au Canada. Sur les 70 langues autochtones encore parlées, la majorité sont menacées de disparition. Des programmes d'immersion comme les nids de langue permettent aux enfants d'apprendre leur langue ancestrale dès le plus jeune âge, avec des résultats encourageants en Nouvelle-Zélande et à Hawaï.",
    question: "Quelle approche est citée comme modèle pour la revitalisation des langues autochtones ?",
    options: ["L'enseignement universitaire spécialisé.", "Les nids de langue — programmes d'immersion dès le jeune âge.", "La traduction de livres en langues autochtones.", "Les médias en langues autochtones."],
    correctIndex: 1,
    explanation: "Les nids de langue, programmes d'immersion dès le très jeune âge, sont cités comme modèle efficace de revitalisation.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Article",
    passage: "Le burn-out des soignants, exacerbé par la pandémie de COVID-19, révèle des failles structurelles dans les systèmes de santé. Le manque de personnel, la bureaucratisation des soins et l'absence de reconnaissance symbolique poussent de nombreux professionnels à quitter leur métier. La pénurie qui en résulte crée un cercle vicieux aggravant les conditions de travail des soignants restants.",
    question: "Qu'est-ce qui aggrave le cercle vicieux du burn-out des soignants ?",
    options: ["Le manque de formation initiale des infirmiers.", "Les départs créent une pénurie qui aggrave les conditions de travail de ceux qui restent.", "La mauvaise image des métiers de soin dans les médias.", "Les conflits entre médecins et infirmiers."],
    correctIndex: 1,
    explanation: "Les départs liés au burn-out créent une pénurie qui aggrave les conditions de travail des soignants restants — un cercle vicieux.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Article",
    passage: "La notion de « quatrième âge » désigne les personnes de plus de 80 ans, souvent en situation de dépendance. Le maintien à domicile, plébiscité par les personnes âgées elles-mêmes, nécessite des services d'aide adaptés et un soutien aux aidants familiaux. En France, un plan Grand Âge cherche à professionnaliser ce secteur et à améliorer les conditions de travail des aides à domicile.",
    question: "Qu'est-ce qui est plébiscité par les personnes du « quatrième âge » ?",
    options: ["L'hébergement en maison de retraite médicalisée.", "Le maintien à domicile avec des services d'aide adaptés.", "Le déménagement chez les enfants.", "Les résidences seniors autonomes."],
    correctIndex: 1,
    explanation: "Les personnes âgées plébiscitent le maintien à domicile, qui nécessite des services adaptés et du soutien pour les aidants.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement pour la justice alimentaire relie les inégalités d'accès à une alimentation saine aux inégalités socio-spatiales. Les « déserts alimentaires » — zones urbaines ou rurales dépourvues de commerces proposant des aliments frais et abordables — touchent disproportionnellement les quartiers défavorisés et les communautés racisées. Des jardins communautaires et épiceries solidaires cherchent à pallier ces inégalités.",
    question: "Qu'est-ce qu'un « désert alimentaire » selon cet article ?",
    options: ["Une région touchée par la sécheresse et la famine.", "Une zone dépourvue de commerces proposant des aliments frais et abordables.", "Un marché uniquement dédié aux produits importés.", "Un quartier où la restauration rapide domine."],
    correctIndex: 1,
    explanation: "Un désert alimentaire est une zone sans accès à des aliments frais et abordables, touchant disproportionnellement les quartiers défavorisés.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    passageType: "Extrait philosophique — Camus",
    passage: "L'absurde, chez Camus, n'est pas dans le monde ni dans l'homme mais dans leur confrontation : il naît du face-à-face entre le désir humain de clarté et le silence irrationnel du monde. L'absurde reconnu et maintenu — ni résolu par le suicide ni transcendé par le saut dans la foi — est la condition de la révolte : cet acte par lequel l'homme se dresse contre sa condition tout en l'acceptant.",
    question: "Comment Camus définit-il l'absurde ?",
    options: ["Comme l'irrationalité fondamentale du monde.", "Comme la confrontation entre le désir humain de clarté et le silence irrationnel du monde.", "Comme la conviction que la vie n'a aucun sens.", "Comme l'impossibilité de communiquer avec autrui."],
    correctIndex: 1,
    explanation: "L'absurde camusien naît de la confrontation entre le désir humain de sens et le silence muet du monde.",
  },
  {
    id: 27,
    level: "C1",
    passageType: "Article académique",
    passage: "La théorie des jeux, développée par Von Neumann et Morgenstern et popularisée par Nash, modélise les situations d'interaction stratégique entre agents rationnels. L'équilibre de Nash désigne une situation où aucun joueur n'a intérêt à modifier unilatéralement sa stratégie, les stratégies de tous étant des réponses optimales à celles des autres. Ce concept explique paradoxalement pourquoi des agents rationnels peuvent atteindre des équilibres sous-optimaux collectivement.",
    question: "Quel paradoxe l'équilibre de Nash illustre-t-il ?",
    options: ["Des agents irrationnels peuvent atteindre des résultats optimaux.", "Des agents rationnels peuvent atteindre des équilibres collectivement sous-optimaux.", "La rationalité est impossible en situation d'incertitude.", "Les marchés libres produisent toujours des équilibres inefficaces."],
    correctIndex: 1,
    explanation: "L'équilibre de Nash montre que des agents rationnels individuellement peuvent aboutir à des résultats collectivement sous-optimaux.",
  },
  {
    id: 28,
    level: "C1",
    passageType: "Extrait littéraire — Romain Gary",
    passage: "Il avait compris très tôt que les identités sont des fictions nécessaires, des vêtements qu'on revêt selon les saisons de l'existence. Il avait été plusieurs hommes dans une seule vie, non par instabilité mais par nécessité : la survie exige parfois qu'on se défasse de soi-même pour recommencer ailleurs. Chaque nouvelle identité portait en elle le deuil de la précédente et l'espoir ténu d'une continuité souterraine.",
    question: "Comment l'identité est-elle conçue dans cet extrait ?",
    options: ["Comme un héritage génétique immuable.", "Comme une fiction nécessaire, multiple et transformable selon les circonstances.", "Comme une construction sociale imposée par la société.", "Comme une quête spirituelle vers un moi authentique."],
    correctIndex: 1,
    explanation: "L'identité est une fiction nécessaire que l'on revêt et abandonne selon les circonstances de l'existence.",
  },
  {
    id: 29,
    level: "C1",
    passageType: "Article académique",
    passage: "La pensée décoloniale distingue deux formes de domination coloniale persistantes : la colonialité du pouvoir, qui structure les hiérarchies globales entre peuples, et la colonialité du savoir, qui impose une épistémologie occidentale comme référence universelle. Décoloniser les savoirs implique de reconnaître la pluralité des formes de connaissance et de leurs conditions de production situées.",
    question: "Que signifie décoloniser les savoirs ?",
    options: ["Traduire les textes académiques occidentaux en langues du Sud.", "Reconnaître la pluralité des formes de connaissance et de leurs conditions de production situées.", "Interdire les références aux penseurs occidentaux dans les universités.", "Créer des universités séparées pour chaque culture."],
    correctIndex: 1,
    explanation: "Décoloniser les savoirs signifie reconnaître la pluralité épistémique et les conditions situées de production de la connaissance.",
  },
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "La sociolinguistique variationnelle, fondée par William Labov, étudie comment les variations linguistiques — prononciation, lexique, syntaxe — corrèlent avec les variables sociales comme la classe, l'âge, le genre et l'ethnicité. Labov a montré que ces variations ne sont pas des « erreurs » mais des systèmes cohérents reflétant les identités sociales des locuteurs. Toute langue est donc intrinsèquement variable et sociale.",
    question: "Quelle conception des variations linguistiques Labov remet-il en question ?",
    options: ["Que les variations sont propres aux langues non standardisées.", "Que les variations linguistiques sont des « erreurs » en montrant qu'elles sont des systèmes cohérents.", "Que les variations sont uniquement liées à la géographie.", "Que les enfants apprennent les variétés standard avant les variétés populaires."],
    correctIndex: 1,
    explanation: "Labov montre que les variations linguistiques ne sont pas des erreurs mais des systèmes cohérents liés aux identités sociales.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Article académique",
    passage: "Le concept d'intersectionnalité, forgé par Kimberlé Crenshaw, désigne l'imbrication des systèmes de domination — race, classe, genre, sexualité — qui produisent des expériences d'oppression spécifiques et non réductibles à leur somme. Une femme noire n'est pas simplement femme + noire : elle occupe une position sociale singulière que ni le féminisme blanc ni l'antiracisme masculin ne permettent de saisir pleinement.",
    question: "Pourquoi l'intersectionnalité propose-t-elle une analyse différente des discriminations ?",
    options: ["Parce qu'elle hiérarchise les formes d'oppression.", "Parce que les oppressions s'imbriquent et produisent des expériences non réductibles à leur somme.", "Parce qu'elle s'applique uniquement aux femmes de couleur.", "Parce qu'elle remplace les catégories de race et de genre."],
    correctIndex: 1,
    explanation: "L'intersectionnalité montre que les oppressions s'imbriquent pour produire des expériences singulières irréductibles à leur addition.",
  },
  {
    id: 32,
    level: "C2",
    passageType: "Extrait philosophique — Sartre",
    passage: "L'existentialisme de Sartre part du principe que l'existence précède l'essence : l'homme n'est pas d'abord défini par une nature ou une essence préalable — il se fait en existant, en choisissant, en agissant. Cette liberté radicale est vertigineuse : elle s'accompagne d'une responsabilité totale, car en choisissant pour soi, l'homme choisit pour tous les hommes. La mauvaise foi consiste à fuir cette liberté en se réfugiant dans des rôles ou des déterminismes fictifs.",
    question: "Qu'est-ce que la mauvaise foi chez Sartre ?",
    options: ["Le mensonge délibéré envers autrui.", "La fuite de la liberté en se réfugiant dans des rôles ou des déterminismes fictifs.", "L'incapacité à distinguer le bien du mal.", "Un refus de la responsabilité collective."],
    correctIndex: 1,
    explanation: "La mauvaise foi sartrienne est une fuite de la liberté et de la responsabilité, en se réfugiant dans des rôles ou des déterminismes.",
  },
  {
    id: 33,
    level: "C2",
    passageType: "Article académique",
    passage: "La théorie queer, héritière des Cultural Studies et de Foucault, refuse toute naturalisation des identités sexuelles et de genre. Elle postule que l'hétérosexualité est un régime normalisateur qui produit et contrôle les corps, pas une donnée naturelle. Les travaux de Eve Kosofsky Sedgwick sur le placard et les épistémologies de l'ignorance montrent comment la dissimulation des identités queer structure la culture mainstream.",
    question: "Quelle est la thèse centrale de la théorie queer sur l'hétérosexualité ?",
    options: ["Elle est une orientation biologique parmi d'autres.", "C'est un régime normalisateur qui produit et contrôle les corps, non une donnée naturelle.", "Elle est une construction culturelle positive à préserver.", "Elle est inévitable dans toutes les cultures humaines."],
    correctIndex: 1,
    explanation: "La théorie queer démontre que l'hétérosexualité est un régime normalisateur — non une donnée naturelle — qui contrôle les corps.",
  },
  {
    id: 34,
    level: "C2",
    passageType: "Essai",
    passage: "L'éthique du care, développée par Carol Gilligan en réaction au modèle kohlbergien de justice, valorise les relations, la dépendance et la sollicitude comme fondements moraux souvent ignorés par les éthiques universalistes. Joan Tronto a élargi cette perspective pour en faire une critique politique : le care est un travail socialement nécessaire mais systématiquement dévalorisé et assigné aux femmes et aux classes subalternes.",
    question: "Quelle critique politique Joan Tronto adresse-t-elle au care ?",
    options: ["Il est trop coûteux pour les États providence.", "Il est un travail nécessaire mais systématiquement dévalorisé et assigné aux femmes et aux classes subalternes.", "Il ne peut pas fonder une éthique universelle.", "Il est incompatible avec les exigences de la vie professionnelle moderne."],
    correctIndex: 1,
    explanation: "Tronto critique la dévalorisation systématique du care et son assignation aux femmes et aux classes subalternes.",
  },
  {
    id: 35,
    level: "C2",
    passageType: "Article académique",
    passage: "La notion de performativité appliquée au langage par Austin a été étendue par Derrida à l'écriture. Pour Austin, certains énoncés font ce qu'ils disent dans des conditions institutionnelles précises. Derrida montre que cette force performative dépend de la citabilité du signe — sa capacité à être répété dans d'autres contextes — introduisant ainsi une instabilité constitutive dans tout acte de langage.",
    question: "Quelle instabilité Derrida introduit-il dans la théorie des actes de langage ?",
    options: ["Les locuteurs ne comprennent jamais exactement ce qu'ils disent.", "La force performative dépend de la citabilité du signe, instabilité constitutive de tout acte de langage.", "Les actes de langage sont inefficaces dans des contextes non institutionnels.", "La performativité n'est possible qu'à l'oral, pas à l'écrit."],
    correctIndex: 1,
    explanation: "Derrida montre que la citabilité du signe introduit une instabilité constitutive dans tout acte de langage, déstabilisant la théorie austinienne.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Essai",
    passage: "La dialectique du maître et de l'esclave chez Hegel illustre comment la conscience de soi ne peut se constituer que dans la reconnaissance de l'autre. Le maître, reconnu par l'esclave, finit par dépendre de cette reconnaissance pour sa propre certitude de soi. L'esclave, en revanche, en travaillant la nature, développe une conscience médiatisée par l'objet — plus riche et autonome que celle du maître.",
    question: "Quel renversement paradoxal la dialectique de Hegel illustre-t-elle ?",
    options: ["Le maître est plus heureux que l'esclave.", "L'esclave, en travaillant, développe une conscience plus riche et autonome que celle du maître.", "Le travail aliène l'homme et l'empêche de se reconnaître.", "Le maître et l'esclave atteignent finalement la même conscience."],
    correctIndex: 1,
    explanation: "Le paradoxe hégélien : l'esclave qui travaille développe une conscience plus riche que le maître qui dépend de la reconnaissance de l'autre.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "La translittérature, terme forgé pour désigner les œuvres qui circulent entre langues et cultures par la traduction, pose la question de l'original et de la copie. Pour Walter Benjamin, la traduction révèle la vie seconde d'une œuvre : elle n'en est pas la reproduction fidèle mais la survie dans une autre langue. La traduction n'est donc pas une perte mais l'actualisation d'un potentiel latent dans le texte source.",
    question: "Comment Walter Benjamin conçoit-il la traduction ?",
    options: ["Comme une reproduction fidèle de l'original.", "Comme la survie d'une œuvre dans une autre langue, révélant sa vie seconde.", "Comme une trahison nécessaire du texte source.", "Comme un exercice purement technique et mécanique."],
    correctIndex: 1,
    explanation: "Pour Benjamin, la traduction révèle la vie seconde d'une œuvre — sa survie et actualisation dans une autre langue.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai",
    passage: "L'espace narratif postcolonial est souvent caractérisé par ce que Homi Bhabha nomme le tiers-espace : un lieu hybride, ambigu, entre la culture coloniale et la culture colonisée, où ni l'une ni l'autre ne peut s'affirmer dans sa pureté. C'est dans ce tiers-espace que se négocient les identités et que peuvent émerger des pratiques culturelles subversives échappant aux assignations binaires.",
    question: "Qu'est-ce que le tiers-espace selon Homi Bhabha ?",
    options: ["Un espace géographique entre deux nations.", "Un lieu hybride entre cultures coloniale et colonisée où se négocient les identités.", "Un espace numérique de résistance culturelle.", "Un troisième mouvement littéraire au-delà du modernisme et du postmodernisme."],
    correctIndex: 1,
    explanation: "Le tiers-espace de Bhabha est un lieu hybride et ambigu entre cultures coloniale et colonisée, où se négocient les identités.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article académique",
    passage: "L'anthropologie symétrique de Bruno Latour cherche à sortir de la « Grande Séparation » entre nature et culture propre à la modernité occidentale. Les modernes, selon Latour, ont produit des hybrides — objets mêlant nature, technique et société — tout en maintenant théoriquement la séparation entre ces domaines. Nous n'avons jamais été modernes parce que nous avons toujours produit ces entités mixtes que notre discours théorique refuse.",
    question: "Qu'est-ce que les « hybrides » chez Bruno Latour ?",
    options: ["Des espèces génétiquement modifiées.", "Des objets mêlant nature, technique et société que la modernité produit mais théoriquement refuse.", "Des individus biculturels entre deux mondes.", "Des institutions mixtes entre public et privé."],
    correctIndex: 1,
    explanation: "Les hybrides latouriens sont des entités mêlant nature, technique et société — produits par la modernité mais théoriquement niés par elle.",
  },
];
