import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

export const TCF_LISTENING_P5: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "Gare ferroviaire",
    audioScript: "Mesdames et messieurs, le train en provenance de Lyon, arrivant voie cinq, est retardé de quinze minutes. Nous nous excusons pour ce désagrément.",
    question: "Sur quelle voie arrive le train en provenance de Lyon ?",
    options: ["Voie 3.", "Voie 4.", "Voie 5.", "Voie 6."],
    correctIndex: 2,
    explanation: "L'annonce indique que le train de Lyon arrive voie 5 avec 15 minutes de retard.",
  },
  {
    id: 2,
    level: "A1",
    topic: "À la boulangerie",
    audioScript: "Bonjour madame. Je voudrais deux baguettes tradition, une tarte aux pommes, s'il vous plaît. Vous avez du pain de seigle aussi ? Oui, parfait, j'en prends un.",
    question: "Combien de baguettes la cliente commande-t-elle ?",
    options: ["Une.", "Deux.", "Trois.", "Quatre."],
    correctIndex: 1,
    explanation: "La cliente commande deux baguettes tradition, une tarte aux pommes et un pain de seigle.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Cours de natation",
    audioScript: "Les cours de natation pour enfants ont lieu le mercredi après-midi et le samedi matin. Les enfants doivent apporter leur maillot, leur bonnet de bain et leurs lunettes de piscine.",
    question: "Quels jours ont lieu les cours de natation pour enfants ?",
    options: ["Lundi et jeudi.", "Mardi et vendredi.", "Mercredi après-midi et samedi matin.", "Samedi et dimanche."],
    correctIndex: 2,
    explanation: "Les cours de natation pour enfants ont lieu le mercredi après-midi et le samedi matin.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Magasin de vêtements",
    audioScript: "Excusez-moi. Est-ce que ce manteau existe en bleu marine ? Je fais du quarante-deux. Non ? Et en vert kaki, vous l'avez en quarante-quatre ?",
    question: "Quelle est la première couleur demandée par le client ?",
    options: ["Vert kaki.", "Bleu ciel.", "Bleu marine.", "Gris foncé."],
    correctIndex: 2,
    explanation: "Le client demande d'abord le manteau en bleu marine, puis en vert kaki.",
  },
  {
    id: 5,
    level: "A1",
    topic: "Centre culturel",
    audioScript: "Le centre culturel propose des ateliers de peinture le mardi soir à dix-huit heures trente. L'inscription est ouverte en ligne sur notre site internet. Les places sont limitées à douze personnes par groupe.",
    question: "Quel est le nombre maximum de personnes par groupe d'atelier de peinture ?",
    options: ["Dix personnes.", "Douze personnes.", "Quinze personnes.", "Vingt personnes."],
    correctIndex: 1,
    explanation: "Les ateliers de peinture sont limités à 12 personnes par groupe.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Déménagement",
    audioScript: "Bonjour. Je cherche des cartons pour déménager. J'ai besoin d'environ vingt grands cartons et dix petits. Est-ce que vous avez ça en stock ? Quel est le prix à l'unité ?",
    question: "Combien de grands cartons la personne cherche-t-elle ?",
    options: ["Dix.", "Quinze.", "Vingt.", "Trente."],
    correctIndex: 2,
    explanation: "La personne cherche environ 20 grands cartons et 10 petits pour son déménagement.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Médecin — suivi",
    audioScript: "Suite à votre visite de la semaine dernière, vos analyses de sang sont revenues normales. Votre cholestérol est légèrement élevé. Je vous recommande de réduire les graisses saturées et de faire du sport deux à trois fois par semaine.",
    question: "Qu'est-ce qui est légèrement élevé dans les analyses du patient ?",
    options: ["La glycémie.", "La tension artérielle.", "Le cholestérol.", "Les globules blancs."],
    correctIndex: 2,
    explanation: "Le médecin indique que le cholestérol du patient est légèrement élevé et recommande de changer ses habitudes.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Agence immobilière",
    audioScript: "Bonjour. Je cherche un appartement à louer, idéalement deux pièces, pas loin du centre-ville. Mon budget maximum est de sept cents euros par mois, charges comprises. J'ai besoin de quelque chose de disponible à partir du premier du mois prochain.",
    question: "Quel est le budget maximum du locataire ?",
    options: ["600 euros.", "650 euros.", "700 euros.", "750 euros."],
    correctIndex: 2,
    explanation: "Le budget maximum du locataire est de 700 euros par mois, charges comprises.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Restaurant scolaire",
    audioScript: "Chers parents, le menu du restaurant scolaire est disponible chaque mois sur le site de l'école. Pour cette semaine, les enfants auront le choix entre une entrée, un plat chaud et un dessert. Le repas coûte trois euros cinquante par enfant.",
    question: "Où les parents peuvent-ils consulter le menu du restaurant scolaire ?",
    options: ["À l'entrée de l'école.", "Sur le site internet de l'école.", "Dans le carnet de correspondance.", "À la cantine directement."],
    correctIndex: 1,
    explanation: "Le menu mensuel est disponible sur le site internet de l'école.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Parc naturel",
    audioScript: "Bienvenue dans le Parc naturel régional du Vercors. Il est interdit de faire du feu, d'emmener des chiens sans laisse, et de cueillir les plantes protégées. Respectez la nature et ne laissez aucun déchet.",
    question: "Quelle est une des règles du parc naturel ?",
    options: ["Les chiens sont interdits.", "Il faut payer un droit d'entrée.", "Il est interdit de faire du feu.", "Le camping est autorisé partout."],
    correctIndex: 2,
    explanation: "Il est interdit de faire du feu dans le parc naturel régional.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Apprentissage des langues",
    audioScript: "Les recherches montrent que l'immersion totale reste la méthode la plus efficace pour apprendre une langue. Cependant, pour ceux qui ne peuvent pas voyager, les applications mobiles, les échanges tandem avec des locuteurs natifs, et le visionnage de films en version originale constituent d'excellentes alternatives.",
    question: "Selon les recherches, quelle est la méthode la plus efficace pour apprendre une langue ?",
    options: ["Les cours dans une école de langues.", "L'apprentissage par applications mobiles.", "L'immersion totale.", "La lecture de livres en langue étrangère."],
    correctIndex: 2,
    explanation: "L'immersion totale est la méthode la plus efficace selon les recherches sur l'apprentissage des langues.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Jardinage urbain",
    audioScript: "Les jardins partagés se multiplient dans les grandes villes. Ces espaces permettent aux habitants, souvent sans jardin, de cultiver des fruits et légumes, de créer du lien social et de reconnecter avec la nature. La ville de Paris compte aujourd'hui plus de cent jardins partagés gérés par des associations.",
    question: "Quel est l'un des avantages des jardins partagés en ville ?",
    options: ["Réduire le coût des logements.", "Créer du lien social et reconnecter avec la nature.", "Produire des aliments pour les restaurants locaux.", "Former des jardiniers professionnels."],
    correctIndex: 1,
    explanation: "Les jardins partagés permettent de créer du lien social et de reconnecter les citadins avec la nature.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Formation continue",
    audioScript: "La formation tout au long de la vie est devenue une nécessité dans un monde du travail en constante évolution. En France, chaque salarié dispose d'un Compte Personnel de Formation alimenté en heures chaque année. Il peut l'utiliser pour se former à de nouvelles compétences en dehors de ses heures de travail.",
    question: "Comment le Compte Personnel de Formation est-il alimenté ?",
    options: ["Par une cotisation mensuelle du salarié.", "Par les bénéfices de l'entreprise.", "En heures chaque année.", "Par une allocation unique à l'embauche."],
    correctIndex: 2,
    explanation: "Le CPF est alimenté en heures chaque année, permettant au salarié de financer des formations.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Architecture durable",
    audioScript: "Les bâtiments passifs ou à énergie positive représentent l'avenir de la construction. Ces constructions produisent autant, voire plus, d'énergie qu'elles n'en consomment grâce à une isolation optimale et des panneaux solaires intégrés. Bien que leur coût de construction soit plus élevé, leurs propriétaires réalisent des économies sur le long terme.",
    question: "Qu'est-ce qu'un bâtiment à énergie positive ?",
    options: ["Un bâtiment alimenté uniquement par le vent.", "Un bâtiment qui produit autant ou plus d'énergie qu'il n'en consomme.", "Un bâtiment construit avec des matériaux recyclés.", "Un bâtiment connecté à un réseau intelligent."],
    correctIndex: 1,
    explanation: "Un bâtiment à énergie positive produit autant ou plus d'énergie qu'il ne consomme.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Économie du partage",
    audioScript: "L'économie collaborative transforme notre rapport à la propriété. Plutôt que de posséder un bien rarement utilisé, de plus en plus de personnes préfèrent le louer ou l'emprunter. Des plateformes numériques facilitent ces échanges entre particuliers pour des voitures, des outils, ou même des compétences professionnelles.",
    question: "Quelle transformation l'économie collaborative apporte-t-elle ?",
    options: ["Elle encourage à posséder davantage de biens.", "Elle facilite le financement des petites entreprises.", "Elle transforme notre rapport à la propriété en favorisant le partage.", "Elle remplace le commerce traditionnel."],
    correctIndex: 2,
    explanation: "L'économie collaborative transforme le rapport à la propriété en encourageant la location et le partage plutôt que la possession.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Mobilité internationale",
    audioScript: "Le programme Erasmus a permis à des millions d'étudiants européens d'étudier à l'étranger depuis sa création en mille neuf cent quatre-vingt-sept. Ses effets vont au-delà de la simple amélioration linguistique : les anciens Erasmus sont statistiquement plus susceptibles d'avoir des partenaires de nationalité différente et de travailler dans un autre pays après leurs études.",
    question: "Quels sont les effets d'Erasmus au-delà de l'amélioration linguistique ?",
    options: ["Obtenir de meilleures notes universitaires.", "Obtenir un emploi mieux rémunéré dans son pays.", "Être plus ouvert à des partenaires d'autres nationalités et travailler à l'étranger.", "Accéder à des bourses supplémentaires."],
    correctIndex: 2,
    explanation: "Les anciens Erasmus sont plus enclins à avoir des partenaires étrangers et à travailler dans d'autres pays.",
  },
  {
    id: 17,
    level: "B2",
    topic: "Bien-être au travail",
    audioScript: "Le syndrome d'épuisement professionnel, ou burnout, est désormais reconnu par l'Organisation mondiale de la santé comme un phénomène lié au travail. Il se manifeste par un sentiment d'épuisement intense, une distance croissante avec son emploi et une efficacité réduite. Sa prévention passe par un management bienveillant et une meilleure organisation du travail.",
    question: "Comment se manifeste le burnout selon l'OMS ?",
    options: ["Par des douleurs physiques uniquement.", "Par un épuisement intense, une distance avec son emploi et une efficacité réduite.", "Par une hyperactivité et un surinvestissement au travail.", "Par une prise de risques excessifs dans les décisions professionnelles."],
    correctIndex: 1,
    explanation: "Le burnout se manifeste par épuisement intense, distance avec son travail et efficacité réduite.",
  },
  {
    id: 18,
    level: "B2",
    topic: "Pollution lumineuse",
    audioScript: "La pollution lumineuse affecte non seulement les observations astronomiques mais perturbe aussi les rythmes biologiques des animaux et des humains. L'excès de lumière artificielle nocturne désynchronise les cycles circadiens, perturbe la migration des oiseaux et menace les espèces nocturnes. Des villes pionnières ont déjà adopté des chartes pour limiter l'éclairage la nuit.",
    question: "Quels sont les effets de la pollution lumineuse mentionnés dans ce reportage ?",
    options: ["Elle détériore uniquement les observations astronomiques.", "Elle perturbe les rythmes biologiques des animaux et des humains et menace les espèces nocturnes.", "Elle augmente la consommation d'énergie électrique de façon non rentable.", "Elle cause des accidents de la circulation nocturne."],
    correctIndex: 1,
    explanation: "La pollution lumineuse perturbe les rythmes biologiques, la migration des oiseaux et menace les espèces nocturnes.",
  },
  {
    id: 19,
    level: "B2",
    topic: "Diplomatie culturelle",
    audioScript: "La diplomatie culturelle consiste à utiliser la culture — arts, langue, sport, éducation — comme outil de rayonnement et d'influence internationale. La France, avec son réseau d'Alliances françaises et d'Instituts français dans le monde entier, investit massivement dans cette stratégie. Cependant, certains analystes s'interrogent sur le retour sur investissement de ces politiques face à la concurrence du soft power américain.",
    question: "Quel outil principal la France utilise-t-elle pour sa diplomatie culturelle ?",
    options: ["Les accords commerciaux bilatéraux.", "Le réseau des Alliances françaises et des Instituts français.", "Les programmes d'aide au développement.", "La participation aux compétitions sportives internationales."],
    correctIndex: 1,
    explanation: "La France s'appuie sur son réseau d'Alliances françaises et d'Instituts français à travers le monde.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Santé et alimentation",
    audioScript: "Le régime méditerranéen, classé au patrimoine immatériel de l'UNESCO, est reconnu par les scientifiques comme l'un des plus bénéfiques pour la santé. Riche en légumes, légumineuses, huile d'olive et poisson, il réduit le risque de maladies cardio-vasculaires, de certains cancers et de maladies neurodégénératives. Sa convivialité est aussi soulignée comme un facteur de bien-être.",
    question: "Pourquoi le régime méditerranéen est-il considéré comme bénéfique ?",
    options: ["Parce qu'il est peu calorique et favorise la perte de poids.", "Parce qu'il réduit le risque de plusieurs maladies graves et favorise le bien-être social.", "Parce qu'il est économiquement accessible à tous.", "Parce qu'il est facile à préparer en moins de 30 minutes."],
    correctIndex: 1,
    explanation: "Le régime méditerranéen réduit le risque de maladies graves et sa convivialité favorise le bien-être.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Intelligence artificielle et éducation",
    audioScript: "L'intégration de l'intelligence artificielle dans l'éducation soulève des questions fondamentales sur le rôle de l'enseignant. Si les outils d'IA peuvent personnaliser les parcours d'apprentissage et automatiser les exercices répétitifs, la dimension humaine de l'enseignement — la transmission des valeurs, l'encouragement, la relation pédagogique — reste irremplaçable.",
    question: "Quelle dimension de l'enseignement l'IA ne peut-elle pas remplacer selon ce reportage ?",
    options: ["La correction des exercices de mathématiques.", "La transmission des valeurs et la relation pédagogique humaine.", "L'évaluation des compétences linguistiques.", "La gestion administrative des classes."],
    correctIndex: 1,
    explanation: "La relation pédagogique humaine, la transmission des valeurs et l'encouragement restent irremplaçables par l'IA.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Architecture mémorielle",
    audioScript: "Les mémoriaux et musées consacrés aux génocides et crimes contre l'humanité jouent un rôle éducatif crucial dans la prévention de la répétition de l'histoire. Cependant, des questions se posent sur la muséification de la souffrance et les risques d'une mise en spectacle qui pourrait trivialiser les atrocités au lieu de les commémorer dignement.",
    question: "Quelle critique est formulée à l'égard des mémoriaux dans ce reportage ?",
    options: ["Ils coûtent trop cher à entretenir.", "Ils risquent de banaliser la souffrance en la muséifiant et mettant en spectacle.", "Ils attirent trop peu de visiteurs pour être efficaces.", "Ils représentent un point de vue partial sur l'histoire."],
    correctIndex: 1,
    explanation: "Le risque est que la muséification transforme la souffrance en spectacle, ce qui pourrait trivialiser les atrocités.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Entrepreneuriat social",
    audioScript: "L'entrepreneuriat social vise à résoudre des problèmes sociaux par des solutions économiques innovantes. Contrairement aux ONG qui dépendent des dons, les entreprises sociales cherchent un modèle économique viable qui leur permette de pérenniser leur impact. Des figures comme Muhammad Yunus, créateur de la Grameen Bank, ont inspiré un mouvement mondial.",
    question: "En quoi l'entrepreneuriat social diffère-t-il des ONG traditionnelles ?",
    options: ["Il vise uniquement le profit.", "Il cherche un modèle économique viable plutôt que de dépendre des dons.", "Il fonctionne exclusivement dans les pays en développement.", "Il ne s'implique pas dans des problèmes politiques."],
    correctIndex: 1,
    explanation: "L'entrepreneuriat social se distingue par sa recherche d'un modèle économique durable plutôt que par la dépendance aux dons.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Sport et identité nationale",
    audioScript: "Les grandes compétitions sportives internationales sont des moments de forte mobilisation identitaire nationale. Mais ce patriotisme sportif peut aussi être instrumentalisé par les gouvernements pour masquer des difficultés internes ou pour afficher une puissance symbolique sur la scène mondiale. Le lien entre sport et politique a toujours existé, des Jeux olympiques antiques aux Coupes du monde contemporaines.",
    question: "Comment les gouvernements peuvent-ils instrumentaliser le sport selon ce reportage ?",
    options: ["Pour améliorer la santé publique de leur population.", "Pour masquer des difficultés internes et afficher une puissance symbolique.", "Pour financer la construction d'infrastructures sportives.", "Pour former des athlètes de haut niveau."],
    correctIndex: 1,
    explanation: "Les gouvernements peuvent utiliser le succès sportif pour détourner l'attention des difficultés internes et projeter de la puissance.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Ville intelligente",
    audioScript: "Les smart cities utilisent les données en temps réel pour optimiser la gestion des services urbains : trafic, énergie, déchets, et sécurité. Si ces technologies promettent une meilleure qualité de vie, elles soulèvent des préoccupations sur la surveillance de masse et la vie privée des citoyens. La gouvernance de ces données reste un enjeu démocratique majeur.",
    question: "Quelle préoccupation les smart cities soulèvent-elles ?",
    options: ["Le coût prohibitif des infrastructures numériques.", "La surveillance de masse et la protection de la vie privée.", "L'exclusion numérique des personnes âgées.", "La dépendance aux entreprises technologiques étrangères."],
    correctIndex: 1,
    explanation: "Les smart cities soulèvent des préoccupations importantes sur la surveillance de masse et la vie privée des citoyens.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    topic: "Sociolinguistique — diglossie",
    audioScript: "Charles Ferguson a défini la diglossie comme la coexistence de deux variétés d'une même langue dans une communauté : une variété haute, utilisée dans les contextes formels comme l'école et la religion, et une variété basse, réservée à la vie quotidienne et informelle. Cette distinction ne reflète pas une hiérarchie de valeur mais une répartition fonctionnelle des usages.",
    question: "Qu'est-ce que la diglossie selon Ferguson ?",
    options: ["L'alternance entre deux langues différentes dans une même conversation.", "La coexistence de deux variétés d'une langue avec des usages sociaux différents.", "La dégradation progressive d'une langue sous l'influence d'une autre.", "L'apprentissage simultané de deux langues dès l'enfance."],
    correctIndex: 1,
    explanation: "La diglossie désigne la coexistence de deux variétés d'une même langue avec des fonctions sociales distinctes.",
  },
  {
    id: 27,
    level: "C1",
    topic: "Philosophie de l'histoire",
    audioScript: "Walter Benjamin, dans ses Thèses sur la philosophie de l'histoire, propose une conception du temps historique radicalement différente du progressisme hégélien. L'ange de l'histoire qu'il décrit voit une catastrophe accumulée là où nous percevons un progrès. Benjamin invite à réhabiliter les vaincus de l'histoire, ceux dont le témoignage a été écrasé par la narration des vainqueurs.",
    question: "Comment Benjamin remet-il en question la vision progressiste de l'histoire ?",
    options: ["En affirmant que l'histoire n'a aucun sens.", "En montrant que le progrès cache une accumulation de catastrophes et en réhabilitant les vaincus.", "En proposant un retour aux sociétés traditionnelles.", "En rejetant toute forme de philosophie de l'histoire."],
    correctIndex: 1,
    explanation: "Benjamin oppose au progressisme une vision de l'histoire comme accumulation de catastrophes et revendique la mémoire des vaincus.",
  },
  {
    id: 28,
    level: "C1",
    topic: "Droit constitutionnel — fédéralisme",
    audioScript: "Le fédéralisme canadien se distingue par sa nature asymétrique. Le Québec, en vertu de ses compétences exclusives en matière de langue, d'éducation et de droit civil, occupe une position constitutionnelle singulière. Le principe de dualité linguistique, enchâssé dans la Charte canadienne des droits et libertés, tente de concilier l'unité nationale et la diversité des identités provinciales.",
    question: "Qu'est-ce qui rend le fédéralisme canadien asymétrique ?",
    options: ["Des provinces plus grandes que d'autres.", "Des compétences exclusives accordées au Québec en langue, éducation et droit civil.", "Un financement inégal entre les provinces.", "Des gouvernements provinciaux plus puissants que le gouvernement fédéral."],
    correctIndex: 1,
    explanation: "Le fédéralisme canadien est asymétrique notamment parce que le Québec dispose de compétences exclusives en langue, éducation et droit civil.",
  },
  {
    id: 29,
    level: "C1",
    topic: "Anthropologie — rituels de passage",
    audioScript: "Arnold van Gennep a montré que les rituels de passage suivent une structure universelle en trois phases : séparation, marge ou liminalité, et agrégation. Dans la phase liminale, l'individu se trouve dans un état ambigu, ni dans son ancien ni dans son nouvel état. Ces rituels — de naissance, d'initiation, de mariage ou de mort — permettent aux sociétés de gérer les transitions identitaires.",
    question: "Qu'est-ce que la phase liminale dans les rituels de passage ?",
    options: ["La célébration finale du passage.", "L'état ambigu où l'individu n'est plus dans son ancien état mais pas encore dans le nouveau.", "La préparation rituelle avant la cérémonie.", "La période de deuil après une perte."],
    correctIndex: 1,
    explanation: "La phase liminale est un état de transition ambigu, entre l'ancien statut et le nouveau.",
  },
  {
    id: 30,
    level: "C1",
    topic: "Économie du droit",
    audioScript: "L'analyse économique du droit, associée à l'École de Chicago et à des juristes comme Richard Posner, applique les outils de la microéconomie à l'analyse des règles juridiques. Elle cherche à évaluer l'efficacité économique des normes en termes d'incitation des acteurs et d'allocation optimale des ressources. Cette approche est influente en droit des contrats, de la responsabilité civile et de la propriété.",
    question: "Quel est le principal objectif de l'analyse économique du droit ?",
    options: ["Réduire le coût des procédures judiciaires.", "Évaluer l'efficacité économique des règles juridiques.", "Promouvoir la justice sociale dans le système légal.", "Simplifier la rédaction des contrats."],
    correctIndex: 1,
    explanation: "L'analyse économique du droit cherche à évaluer l'efficacité économique des normes juridiques et leurs effets incitatifs.",
  },
  {
    id: 31,
    level: "C1",
    topic: "Linguistique appliquée — fossilisation",
    audioScript: "La fossilisation linguistique désigne le phénomène par lequel certaines erreurs ou structures incorrectes persistent de façon permanente dans la langue d'un apprenant, résistant à l'instruction et à l'exposition. Elle touche plus souvent la phonologie et certains aspects morphosyntaxiques que le lexique. Comprendre ses mécanismes est crucial pour la didactique des langues secondes.",
    question: "Qu'est-ce que la fossilisation linguistique ?",
    options: ["L'oubli progressif d'une langue peu utilisée.", "La persistance permanente d'erreurs chez un apprenant malgré l'instruction.", "L'adoption d'une langue morte comme langue officielle.", "Le ralentissement de l'apprentissage après un certain âge."],
    correctIndex: 1,
    explanation: "La fossilisation désigne la persistance d'erreurs linguistiques qui résistent à l'instruction et à l'exposition continue.",
  },
  {
    id: 32,
    level: "C2",
    topic: "Phénoménologie — Merleau-Ponty",
    audioScript: "Maurice Merleau-Ponty a renversé le dualisme cartésien en faisant du corps le sujet de la perception. Dans la Phénoménologie de la perception, il montre que nous ne sommes pas des consciences qui habitent des corps mais des êtres incarnés dont l'expérience du monde passe irréductiblement par le corps vécu. Cette perspective a profondément influencé la psychologie clinique, la réhabilitation et les sciences cognitives.",
    question: "Quelle thèse centrale défend Merleau-Ponty dans sa phénoménologie ?",
    options: ["La conscience est totalement indépendante du corps.", "L'expérience du monde passe irréductiblement par le corps vécu.", "La perception est une construction purement intellectuelle.", "Le corps est un obstacle à la connaissance rationnelle."],
    correctIndex: 1,
    explanation: "Merleau-Ponty montre que notre expérience du monde est fondamentalement incarnée — nous sommes des êtres corporels, pas des consciences désincarnées.",
  },
  {
    id: 33,
    level: "C2",
    topic: "Sociologie des organisations",
    audioScript: "Michel Crozier a montré dans L'Acteur et le système que les organisations ne fonctionnent pas selon une logique de rationalité instrumentale pure. Les acteurs y développent des stratégies pour maximiser leur autonomie en jouant sur les zones d'incertitude. Le pouvoir, chez Crozier, n'est pas une propriété mais une relation contingente qui se négocie dans des interactions situées.",
    question: "Comment Crozier définit-il le pouvoir dans les organisations ?",
    options: ["Comme une propriété hiérarchique stable.", "Comme une relation contingente négociée autour des zones d'incertitude.", "Comme un outil de coercition exercé par la direction.", "Comme l'accès aux ressources financières de l'organisation."],
    correctIndex: 1,
    explanation: "Pour Crozier, le pouvoir est une relation négociée, pas une propriété — il s'exerce en contrôlant les zones d'incertitude.",
  },
  {
    id: 34,
    level: "C2",
    topic: "Précariat et travail",
    audioScript: "Guy Standing a forgé le concept de précariat pour désigner une nouvelle classe sociale définie non pas par son rapport aux moyens de production comme le prolétariat, mais par son rapport à l'insécurité. Le précariat est caractérisé par l'absence de sécurité de l'emploi, de carrière prévisible, d'identité professionnelle stable, et de droits sociaux consolidés. C'est selon Standing la classe dangereuse du XXIe siècle.",
    question: "Comment Guy Standing définit-il le précariat ?",
    options: ["Comme les travailleurs pauvres dans les pays en développement.", "Comme une classe définie par son rapport à l'insécurité professionnelle et sociale.", "Comme les chômeurs de longue durée.", "Comme les travailleurs non syndiqués dans les grandes entreprises."],
    correctIndex: 1,
    explanation: "Le précariat est défini par l'insécurité professionnelle, l'absence de carrière prévisible et la précarité des droits sociaux.",
  },
  {
    id: 35,
    level: "C2",
    topic: "Critique littéraire — intertextualité",
    audioScript: "Julia Kristeva a introduit le concept d'intertextualité pour signifier qu'aucun texte n'est une île : tout texte se construit en absorbant et en transformant d'autres textes. Ce concept, développé à partir de Bakhtine, remet en question la notion d'originalité absolue et ouvre une conception dialogique de la littérature où le sens naît des relations entre textes plutôt que d'une intention auctoriale unitaire.",
    question: "Que révèle le concept d'intertextualité sur la nature des textes ?",
    options: ["Que les grands auteurs écrivent sans influence extérieure.", "Que tout texte se construit en absorbant et transformant d'autres textes.", "Que le sens d'un texte est uniquement dans l'intention de l'auteur.", "Que la littérature contemporaine est supérieure à la littérature classique."],
    correctIndex: 1,
    explanation: "L'intertextualité montre qu'aucun texte n'est original en soi : il dialogue toujours avec d'autres textes.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Géopolitique et ressources",
    audioScript: "La compétition pour les ressources stratégiques — terres rares, eau, terres agricoles — redéfinit les équilibres géopolitiques mondiaux. La Chine, qui contrôle environ soixante pour cent de la production mondiale de terres rares, dispose d'un levier considérable sur les industries technologiques occidentales. Cette dépendance oblige les démocraties à repenser leur souveraineté industrielle et technologique.",
    question: "Quel avantage géopolitique la Chine détient-elle concernant les terres rares ?",
    options: ["Elle est le premier importateur mondial.", "Elle contrôle environ 60% de leur production mondiale.", "Elle possède les plus grandes réserves inexploitées.", "Elle a breveté les techniques d'extraction les plus efficaces."],
    correctIndex: 1,
    explanation: "La Chine contrôle environ 60% de la production mondiale de terres rares, lui conférant un levier stratégique majeur.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Théologie politique — sécularisme",
    audioScript: "Charles Taylor, dans L'Âge séculier, distingue trois sens de la sécularisation : la disparition de la religion de l'espace public, le déclin de la pratique religieuse, et la transformation de la croyance en option parmi d'autres. Sa thèse principale est que la modernité occidentale n'a pas éliminé la religion mais l'a rendue vulnérable, une possibilité parmi d'autres dans un espace de quête spirituelle pluriel.",
    question: "Quelle est la thèse principale de Charles Taylor sur la sécularisation ?",
    options: ["La religion a disparu de l'espace public occidental.", "La modernité a transformé la croyance en option parmi d'autres, sans éliminer la religion.", "Le retour du religieux est une réaction contre la modernité.", "La sécularisation est un processus inévitable et universel."],
    correctIndex: 1,
    explanation: "Taylor soutient que la modernité n'a pas éliminé la religion mais en a fait une option parmi d'autres dans un espace spirituel pluralisé.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Éthique de la communication — Habermas",
    audioScript: "L'éthique de la discussion d'Habermas postule que la validité des normes morales ne se fonde pas sur une vérité abstraite mais sur un consensus obtenu dans des conditions idéales de communication : symétrie entre les participants, liberté d'expression, et orientation vers la compréhension mutuelle plutôt que vers la victoire. Cette procédure dialogique est à la fois une méthode et un idéal régulateur.",
    question: "Sur quoi repose la validité des normes morales selon l'éthique de la discussion habermasienne ?",
    options: ["Sur la tradition culturelle et religieuse d'une société.", "Sur un consensus obtenu dans des conditions idéales de communication.", "Sur les lois naturelles dérivables par la raison.", "Sur l'accord de la majorité exprimé par le vote."],
    correctIndex: 1,
    explanation: "Pour Habermas, les normes morales valides sont celles qui émergent d'un consensus dans des conditions idéales de communication symétrique.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Décolonialité et savoir",
    audioScript: "Le courant décolonial, porté par des penseurs comme Aníbal Quijano et Walter Mignolo, remet en question la prétention universelle des épistémologies occidentales. Leur notion de colonialité du savoir désigne la manière dont les systèmes de connaissance produits par la modernité européenne ont marginalisé ou effacé d'autres formes de savoir. Décoloniser le savoir, c'est reconnaître la pluralité épistémique du monde.",
    question: "Que désigne la « colonialité du savoir » dans la pensée décoloniale ?",
    options: ["L'imposition politique des langues coloniales dans les anciens empires.", "La marginalisation des autres formes de savoir par les épistémologies occidentales.", "Le contrôle des ressources naturelles par les anciennes puissances coloniales.", "La copie des systèmes éducatifs occidentaux dans les pays du Sud."],
    correctIndex: 1,
    explanation: "La colonialité du savoir désigne comment les épistémologies occidentales ont marginalisé d'autres formes de connaissance.",
  },
];
