import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 9 — Compréhension écrite. Theme: mobility, transport and urban life in Canada.
 *
 * Hand-authored to keep distractors plausible and similar in length, so no
 * surface heuristic (longest option, option B) beats reading the text.
 */
export const TCF_READING_P9: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "STATION DE MÉTRO — PARC\nAscenseur en panne jusqu'à 17 h\nAccès fauteuil roulant : entrée rue Sherbrooke\nBus de remplacement : ligne 80",
    question: "Où faut-il entrer si l'on est en fauteuil roulant ?",
    options: ["Par l'entrée habituelle.", "Par l'entrée rue Sherbrooke.", "Par la sortie ligne 80.", "Par le quai principal."],
    correctIndex: 1,
    explanation: "Wheelchair access is via Sherbrooke Street entrance while the elevator is out.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Horaires",
    passage: "AUTOBUS 24 — DIRECTION CENTRE-VILLE\nSemaine : toutes les 12 minutes (6 h – 22 h)\nSamedi : toutes les 20 minutes\nDimanche et fériés : toutes les 30 minutes",
    question: "Quelle est la fréquence le dimanche ?",
    options: ["Toutes les 12 minutes.", "Toutes les 20 minutes.", "Toutes les 30 minutes.", "Un bus par heure seulement."],
    correctIndex: 2,
    explanation: "On Sundays and holidays buses run every 30 minutes.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Salut Nina,\nLe train de 7 h 15 est annulé à cause de la neige. Prends le bus 901 devant la gare ; il passe à 7 h 25. J'ai réservé deux places assises pour nous.\n— Omar",
    question: "Que doit faire Nina ?",
    options: ["Attendre le train de 7 h 15.", "Prendre le bus 901 à 7 h 25.", "Rester à la gare jusqu'à midi.", "Annuler la réservation."],
    correctIndex: 1,
    explanation: "Omar tells her to take bus 901 at 7:25 in front of the station.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "PARC VÉLO SÉCURISÉ — GARE CENTRALE\nOuvert 5 h – 1 h\nAbonnement mensuel : 25 $\nCasier individuel avec cadenas fourni\nVélos électriques interdits dans les casiers",
    question: "Quel véhicule ne peut pas aller dans un casier ?",
    options: ["Un vélo classique.", "Un vélo pliant.", "Un vélo électrique.", "Un vélo pour enfant."],
    correctIndex: 2,
    explanation: "Electric bikes are not allowed in the lockers.",
  },
  {
    id: 5,
    level: "A2",
    passageType: "Courriel",
    passage: "Objet : Confirmation — cours de conduite hivernale\n\nBonjour,\nVotre séance est confirmée samedi 8 février, 9 h, au centre de formation Nord. Apportez votre permis d'apprenti, des bottes chaudes et des lunettes. Le véhicule est fourni.\nÉcole Conduite Plus",
    question: "Que doit apporter l'élève ?",
    options: [
      "Son propre véhicule et une assurance.",
      "Son permis d'apprenti, des bottes et des lunettes.",
      "Uniquement une pièce d'identité.",
      "Un chèque pour le véhicule.",
    ],
    correctIndex: 1,
    explanation: "The email lists learner's permit, warm boots, and glasses; the car is provided.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Note d'information",
    passage: "STATIONNEMENT RÉSIDENTIEL — SECTEUR EST\nPermis annuel obligatoire du 1er avril au 31 mars\nDeux visiteurs max. : vignette gratuite de 2 h\nSans permis : amende de 65 $",
    question: "Combien de temps un visiteur peut-il stationner avec la vignette gratuite ?",
    options: ["Une heure.", "Deux heures.", "Toute la journée.", "Une semaine."],
    correctIndex: 1,
    explanation: "The free visitor pass allows two hours.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Affiche",
    passage: "JOURNÉE SANS VOITURE — 22 SEPTEMBRE\nRues piétonnes de 10 h à 16 h : rue du Commerce et place du Marché\nVélos en libre-service gratuits pendant l'événement\nTransports en commun à tarif réduit",
    question: "De quoi parle l'affiche ?",
    options: [
      "D'une fermeture définitive des rues au trafic.",
      "D'une journée promotionnelle pour marcher, vélo et transit.",
      "D'une interdiction permanente des vélos en libre-service.",
      "D'une augmentation des tarifs de bus.",
    ],
    correctIndex: 1,
    explanation: "Car-free day with pedestrian streets, free bikes, and reduced transit fares.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "SMS",
    passage: "Alerte STM : interruption ligne orange entre Jean-Talon et Rosemont jusqu'à 14 h. Bus substituts 31 et 161. Prévoyez 20 min de plus pour votre trajet.",
    question: "Quel est l'objet de ce message ?",
    options: [
      "Une grève générale du métro.",
      "Un tronçon fermé avec bus de remplacement.",
      "La fin des lignes 31 et 161.",
      "Un retard de 20 minutes sur toutes les lignes.",
    ],
    correctIndex: 1,
    explanation: "Orange line segment closed until 2 p.m. with substitute buses.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Formulaire",
    passage: "DEMANDE DE PASS TRANSPORT\nÉtape 1 : photo en ligne\nÉtape 2 : paiement par carte\nÉtape 3 : retrait de la carte en agence\nDélai : cinq jours ouvrables après le retrait",
    question: "Quand la carte est-elle utilisable ?",
    options: [
      "Dès le paiement en ligne.",
      "Environ cinq jours ouvrables après le retrait en agence.",
      "Le jour même de la photo.",
      "Un mois après la demande.",
    ],
    correctIndex: 1,
    explanation: "Five business days after pickup at the agency.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Courriel",
    passage: "Bonjour M. Singh,\nVotre demande de place au stationnement vélo de l'immeuble est acceptée. Numéro de rack : B-14. La clé sera remise lundi au gardien. Frais mensuels : 15 $ sur votre compte de charges.\nSyndicat Les Érables",
    question: "Où M. Singh récupérera-t-il la clé ?",
    options: ["Au bureau de poste.", "Chez le gardien lundi.", "Par courrier recommandé.", "À la régie de transport."],
    correctIndex: 1,
    explanation: "The key will be handed over Monday to the building caretaker.",
  },

  // ── B1–B2 (Q11–29) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "À Calgary, beaucoup de familles possèdent deux voitures faute d'alternative fiable. Les quartiers construits après les années 1980 sont pensés pour l'automobile : grandes distances entre services, trottoirs parfois absents l'hiver. Les nouvelles lignes de tramway changent lentement cette donne, surtout près du centre.",
    question: "Pourquoi possède-t-on souvent deux voitures selon le texte ?",
    options: [
      "Parce que le permis est moins cher qu'ailleurs.",
      "Parce que les quartiers sont mal desservis sans voiture.",
      "Parce que le transport en commun est interdit en hiver.",
      "Parce que les vélos sont interdits sur les grands axes.",
    ],
    correctIndex: 1,
    explanation: "Car-oriented suburbs lack reliable alternatives and walking access.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Chronique",
    passage: "On présente Montréal comme une ville de métro, mais hors des axes centraux, le bus reste roi — et il subit la circulation. Un trajet de 8 km peut prendre autant de temps à l'autobus qu'à vélo en heure de pointe. Améliorer la mobilité, ce n'est pas seulement creuser des tunnels ; c'est aussi des voies réservées visibles dès le matin.",
    question: "Quel problème l'auteur souligne-t-il ?",
    options: [
      "Le métro ferme trop tôt le week-end.",
      "Les bus périphériques restent ralentis par le trafic.",
      "Les vélos sont plus rapides que le métro partout.",
      "Les tunnels coûtent moins cher que les voies de bus.",
    ],
    correctIndex: 1,
    explanation: "Outside central corridors, buses sit in congestion like cars.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Guide pratique",
    passage: "Au Québec, les pneus d'hiver sont obligatoires du 1er décembre au 15 mars. Conduire avec des pneus été expose à une amende et peut invalider une assurance en cas d'accident. Les résidents récents doivent aussi vérifier si leur permis étranger est reconnu temporairement selon leur province d'accueil.",
    question: "Que risque-t-on avec des pneus été en janvier ?",
    options: [
      "Une amende et des problèmes d'assurance possibles.",
      "La confiscation automatique du véhicule.",
      "L'interdiction de quitter la province.",
      "Un renouvellement obligatoire du permis.",
    ],
    correctIndex: 0,
    explanation: "Winter tires are mandatory; summer tires risk fines and insurance issues.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Reportage",
    passage: "À Vancouver, le « Vancouverism » combine tours minces et rez-de-chaussée actifs le long du SkyTrain. Les commerces de proximité visent les piétons sortant du train, pas les automobilistes. Le modèle séduit les planificateurs, mais les loyers près des stations restent hors de portée pour une partie des travailleurs du secteur service.",
    question: "Quelle limite le reportage mentionne-t-il ?",
    options: [
      "Le SkyTrain ne fonctionne pas la nuit.",
      "Le logement près des stations reste trop cher pour certains.",
      "Les tours minces sont interdits en centre-ville.",
      "Les commerces refusent les piétons.",
    ],
    correctIndex: 1,
    explanation: "Rents near stations stay unaffordable for some service workers.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Les villes canadiennes testent des feux qui priorisent les bus : le véhicule approche, le signal passe au vert plus longtemps. Les gains de temps sont modestes isolément, mais cumulés sur une ligne entière, ils améliorent la ponctualité. Les automobilistes voient parfois l'effet comme une injustice, surtout aux heures de pointe.",
    question: "Quel avantage ces feux apportent-ils ?",
    options: [
      "Ils suppriment tous les embouteillages pour les voitures.",
      "Ils améliorent la régularité des lignes de bus.",
      "Ils interdisent les voitures en centre-ville.",
      "Ils réduisent le prix des titres de transport.",
    ],
    correctIndex: 1,
    explanation: "Small delays saved per intersection add up to better bus punctuality.",
  },
  {
    id: 16,
    level: "B1",
    passageType: "Courrier des lecteurs",
    passage: "Votre article vante les trottinettes électriques en libre-service, mais oublie les aînés qui marchent lentement. Sur les trottoirs étroits, la cohabitation devient dangereuse. Réglementer la vitesse et réserver des bandes n'est pas « anti-innovation » : c'est reconnaître que la rue appartient aussi aux piétons fragiles.",
    question: "Que reproche le lecteur à l'article ?",
    options: [
      "D'avoir critiqué les transports en commun.",
      "D'avoir ignoré la sécurité des piétons vulnérables.",
      "D'avoir surestimé le coût des trottinettes.",
      "D'avoir omis les statistiques sur le métro.",
    ],
    correctIndex: 1,
    explanation: "He says the piece overlooked elderly pedestrians on narrow sidewalks.",
  },
  {
    id: 17,
    level: "B1",
    passageType: "Note de service",
    passage: "À compter du 1er mai, le stationnement des visiteurs à l'hôpital sera payant après la première heure. Les patients en chimiothérapie conservent la gratuité sur présentation de carte clinique. Les dossiers sans numéro de dossier médical ne seront pas remboursés.",
    question: "Qui garde le stationnement gratuit ?",
    options: [
      "Tous les visiteurs le week-end.",
      "Les patients en chimiothérapie avec carte clinique.",
      "Le personnel de nuit uniquement.",
      "Les résidents du quartier.",
    ],
    correctIndex: 1,
    explanation: "Chemotherapy patients with a clinic card keep free parking.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Analyse",
    passage: "La « loi de l'offre induite » en transport suggère qu'élargir une autoroute attir bientôt plus de trajets : le gain de vitesse disparaît. Plusieurs villes canadiennes constatent que de nouveaux ponts saturent en quelques années. Sans pricing de la congestion ou alternatives crédibles, construire plus de bitume reproduit le problème à plus grande échelle.",
    question: "Quel paradoxe l'auteur décrit-il ?",
    options: [
      "Les ponts neufs sont toujours inutilisés.",
      "Augmenter la capacité routière peut recréer l'embouteillage.",
      "Les autoroutes coûtent moins cher que le métro.",
      "Les conducteurs préfèrent les embouteillages.",
    ],
    correctIndex: 1,
    explanation: "Expanded road capacity induces traffic until congestion returns.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Éditorial",
    passage: "Opposer « amateurs de voiture » et « écolos du vélo » masque une réalité : au Canada, beaucoup conduisent faute d'option, surtout en banlieue et la nuit. Pénaliser le stationnement sans renforcer le bus nocturne pousse les ménages modestes à payer des amendes ou à renoncer à des emplois éloignés. La transition mobilité exige des deux côtés : contrainte et service.",
    question: "Quel équilibre l'éditorial recommande-t-il ?",
    options: [
      "Interdire toutes les voitures en banlieue.",
      "Combiner restrictions et amélioration des alternatives.",
      "Supprimer les amendes de stationnement.",
      "Réserver le bus nocturne aux étudiants.",
    ],
    correctIndex: 1,
    explanation: "Policy must pair constraints with credible alternatives for car-dependent households.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "Les First Nations éloignées dépendent souvent de routes non goudronnées et de vols subventionnés pour les soins. Quand le pont seasonal ferme au printemps, les produits frais et les pièces mécaniques arrivent en retard. Les plans urbains de Toronto ou Montréal peinent à intégrer cette géographie : la mobilité « nationale » reste inégale entre métropole et territoires nordiques.",
    question: "Quelle inégalité le texte met-il en évidence ?",
    options: [
      "Les métropoles n'ont pas de métro.",
      "L'accès aux déplacements diffère fortement selon les régions.",
      "Les vols subventionnés sont interdits.",
      "Les ponts saisonniers n'existent qu'en Ontario.",
    ],
    correctIndex: 1,
    explanation: "Remote communities face seasonal infrastructure unlike major cities.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Enquête",
    passage: "Une étude à Ottawa compare deux quartiers : l'un reçoit une piste cycliste protégée, l'autre une simple signalisation. Après un an, le premier voit davantage de femmes et d'adolescents à vélo ; le second, surtout des hommes déjà cyclistes confirmés. La sécurité perçue modifie qui ose pédaler, pas seulement combien de kilomètres sont parcourus.",
    question: "Quel effet la piste protégée produit-elle ?",
    options: [
      "Elle interdit les vélos aux adolescents.",
      "Elle élargit le profil des personnes qui osent circuler à vélo.",
      "Elle réduit le nombre total de cyclistes.",
      "Elle supprime les autobus de la rue.",
    ],
    correctIndex: 1,
    explanation: "Protected lanes bring more women and teens, not just existing cyclists.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "Les « villes intelligentes » déploient capteurs et applications pour optimiser feux et stationnement. Pourtant, sans gouvernance claire, les données de déplacement deviennent un produit vendu à des annonceurs. Une mobilité numérique utile commence par la transparence : qui collecte, qui décide, et comment un citoyen peut contester une amende générée par caméra.",
    question: "Quelle condition l'auteur pose-t-il ?",
    options: [
      "Interdire toute technologie dans la rue.",
      "Garantir transparence et recours sur les données.",
      "Confier les capteurs aux entreprises privées seules.",
      "Supprimer les caméras de stationnement.",
    ],
    correctIndex: 1,
    explanation: "Smart mobility requires clear governance and contestability of automated fines.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Reportage",
    passage: "À Halifax, un programme jumelle nouveaux arrivants et cyclistes locaux pour une première sortie en ville. On apprend où garer le vélo, comment signaler un autobus, quels axes éviter l'hiver. Les participants disent avoir compris des règles non écrites — distance de sécurité, clignotants manuels — qu'aucune brochure ne détaillait.",
    question: "Qu'apprennent surtout les participants ?",
    options: [
      "Les horaires théoriques du métro.",
      "Des pratiques concrètes de circulation locale.",
      "Le coût des permis internationaux.",
      "L'histoire du port de Halifax.",
    ],
    correctIndex: 1,
    explanation: "They learn unwritten local cycling and transit habits on guided rides.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Analyse urbaine",
    passage: "Densifier près du transit réduit les trajets moyens, mais peut accélérer la gentrification si les nouvelles tours n'incluent pas de logements abordables liés. Toronto exige parfois des contributions en nature ; l'efficacité varie selon l'arrondissement. Sans quota social, la « ville du quart d'heure » profite surtout à ceux qui peuvent déjà payer le loyer près de la station.",
    question: "Quel risque la densification présente-t-elle ?",
    options: [
      "La suppression du transport en commun.",
      "Le déplacement des ménages modestes malgré la proximité du transit.",
      "L'interdiction des tours en centre-ville.",
      "La baisse automatique des loyers.",
    ],
    correctIndex: 1,
    explanation: "Without affordable units, transit-oriented growth can gentrify.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Le télétravail a creusé les pics de transport : certains jours, les autoroutes restent fluides, d'autres saturées. Les réseaux de bus calibrés sur un modèle pré-pandémique manquent de flexibilité. Les planificateurs expérimentent des titres « flex » valables hors heure de pointe, espérant étaler la demande sans construire de nouvelles voies.",
    question: "Quelle adaptation est testée ?",
    options: [
      "La gratuité totale du métro le week-end.",
      "Des titres incitant à voyager hors pointe.",
      "La fin du télétravail dans la fonction publique.",
      "L'interdiction des voitures les lundis.",
    ],
    correctIndex: 1,
    explanation: "Flexible passes aim to spread demand outside peak hours.",
  },
  {
    id: 26,
    level: "B2",
    passageType: "Chronique",
    passage: "Comparer Montréal et Winnipeg sur le « même » indicateur de part modale du vélo trompe : le climat, la topographie et la culture automobile diffèrent. Winnipeg progresse avec des pistes protégées modestes ; Montréal débat encore du déneigement des pistes. Une politique mobilité crédible reconnaît le contexte régional au lieu d'importer un classement européen.",
    question: "Que critique l'auteur ?",
    options: [
      "L'absence totale de pistes au Canada.",
      "Les comparaisons qui ignorent les contextes locaux.",
      "Le déneigement parfait à Montréal.",
      "L'interdiction du vélo en hiver.",
    ],
    correctIndex: 1,
    explanation: "Headline modal-share comparisons ignore climate and car culture.",
  },
  {
    id: 27,
    level: "B2",
    passageType: "Dossier",
    passage: "Plusieurs provinces subventionnent l'achat de véhicules électriques, mais le réseau de bornes reste clairsemé hors des corridors Toronto-Ottawa ou Vancouver-Victoria. Les ménages ruraux hésitent : l'autonomie annoncée chute par grand froid. L'aide à l'achat sans bornes rapides le long des routes secondaires reproduit l'inégalité spatiale des décennies précédentes.",
    question: "Quelle lacune le dossier souligne-t-il ?",
    options: [
      "Les VE sont interdits en hiver.",
      "L'infrastructure de recharge hors grands corridors.",
      "L'absence de subventions fédérales.",
      "Le refus des villes d'installer des feux.",
    ],
    correctIndex: 1,
    explanation: "Purchase incentives outpace charging along secondary rural routes.",
  },
  {
    id: 28,
    level: "B2",
    passageType: "Rapport",
    passage: "L'étude mesure le bruit ferroviaire près de nouvelles tours à Toronto : les résidents acceptaient le train en échange de la proximité du centre, mais les fenêtres mal isolées transforment le compromis en plainte. Les recommandations couvrent l'isolation obligatoire et des horaires de maintenance nocturne limités — deux leviers moins visibles que les grands projets de tunnel.",
    question: "Quelle solution le rapport privilégie-t-il ?",
    options: [
      "Déplacer toutes les voies ferrées.",
      "Améliorer l'isolation et réguler les travaux nocturnes.",
      "Interdire les tours près des gares.",
      "Supprimer le train de banlieue.",
    ],
    correctIndex: 1,
    explanation: "Mandatory insulation and limits on night maintenance address noise.",
  },
  {
    id: 29,
    level: "B2",
    passageType: "Essai",
    passage: "La mobilité n'est pas seulement technique : c'est une question de temps disponible. Un parent célibataire en horaires décalés peut préférer la voiture, même chère, parce que le bus de nuit est rare et le trajet piéton mal éclairé. Parler de « choix » sans voir les contraintes de garde et de sécurité réduit la politique urbaine à un catalogue de modes, déconnecté des vies réelles.",
    question: "Quelle conception de la mobilité l'auteur défend-il ?",
    options: [
      "Une mobilité centrée uniquement sur les statistiques de trafic.",
      "Une mobilité comprise à travers les contraintes de temps et de sécurité.",
      "Une mobilité réservée aux centres-villes denses.",
      "Une mobilité fondée sur l'interdiction de la voiture.",
    ],
    correctIndex: 1,
    explanation: "Travel choices reflect care schedules and night safety, not mode catalogs.",
  },

  // ── C1–C2 (Q30–39) ─────────────────────────────────────────────
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "Les politiques de « tarification de la congestion » visent l'efficacité économique, mais leurs effets distributifs divergent : les hauts revenus paient sans changer de comportement, les autres reportent des soins ou des études. Mesurer le succès uniquement par la vitesse moyenne des voitures occulte qui absorbe le coût de la rareté de l'espace public.",
    question: "Quelle critique l'auteur adresse-t-il aux indicateurs ?",
    options: [
      "Ils surestiment le nombre de cyclistes.",
      "Ils ignorent les effets inégaux sur les usagers modestes.",
      "Ils interdisent toute voiture en centre-ville.",
      "Ils suppriment les données de transport.",
    ],
    correctIndex: 1,
    explanation: "Average speed metrics hide who bears congestion pricing costs.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Analyse politique",
    passage: "La gouvernance des transports au Canada fragmente compétences : provinces pour les routes, villes pour le stationnement, fédéral pour le rail interurbain. Cette mosaïque n'est pas un accident ; elle reflète des fédérations historiques. Elle produit pourtant des projets bloqués — une ligne de banlieue attend un financement dont personne ne veut être seul garant.",
    question: "Quel effet cette fragmentation a-t-elle ?",
    options: [
      "Elle supprime les différentes entre villes.",
      "Elle paralyse certains grands projets de liaison.",
      "Elle interdit les transports en commun.",
      "Elle réduit le nombre de ministères.",
    ],
    correctIndex: 1,
    explanation: "Split authority stalls projects when no level wants sole funding risk.",
  },
  {
    id: 32,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Chaque matin, elle comptait les minutes entre le métro, le bus et la garderie. Un retard sur la ligne orange n'était pas un désagrément : c'était une amende à la garderie, un reproche au travail, une soirée écourtée. La ville parlait de « vision mobilité » ; elle vivait une équation où le moindre incident technique devenait une dette familiale.",
    question: "Quel rapport le personnage entretient-il avec les transports ?",
    options: [
      "Il les considère comme un loisir dominical.",
      "Il y voit une chaîne de conséquences sociales et financières.",
      "Il refuse d'utiliser le métro par principe.",
      "Il ignore les horaires de la garderie.",
    ],
    correctIndex: 1,
    explanation: "Transit delays cascade into childcare fees and work tensions.",
  },
  {
    id: 33,
    level: "C1",
    passageType: "Article académique",
    passage: "Les consultations sur les grands projets routiers produisent parfois l'illusion d'un débat ouvert. Les tracés sont présentés comme contraints par des études antérieures ; les citoyens commentent des variantes marginales. Clarifier ce qui est encore négociable — vitesse, bruit, traversées piétonnes — conditionne la confiance, faute de quoi la consultation alimente la défiance.",
    question: "Quelle critique l'auteur adresse-t-il aux consultations ?",
    options: [
      "Elles coûtent trop cher pour les régions rurales.",
      "Elles laissent croire à un choix déjà largement figé.",
      "Elles interdisent les projets cyclables.",
      "Elles retardent toujours les autobus.",
    ],
    correctIndex: 1,
    explanation: "Citizens tweak margins while core routing is already settled.",
  },
  {
    id: 34,
    level: "C1",
    passageType: "Essai",
    passage: "Parler de « justice spatiale » en transport, c'est reconnaître que l'accès à l'emploi dépend de qui peut se loger près du réseau. Subventionner l'essence atténue le choc inflationniste, mais renforce la dépendance automobile ; investir dans le bus régional lie des villages à des pôles sans exiger une voiture par adulte. Les deux mesures coûtent ; elles orientent des trajectoires différentes sur vingt ans.",
    question: "Quel choix de politique le texte oppose-t-il ?",
    options: [
      "Entre métro aérien et tramway.",
      "Entre soutien à la conduite et lien par transport collectif.",
      "Entre vélo et trottinette.",
      "Entre taxe carbone et taxe foncière.",
    ],
    correctIndex: 1,
    explanation: "Fuel subsidies vs regional bus investment shape long-term car dependence.",
  },
  {
    id: 35,
    level: "C1",
    passageType: "Article académique",
    passage: "Le concept de « mobilité comme service » promet un abonnement unique couvrant vélo, taxi et métro. Les plateformes privées captent la relation client ; les données de déplacement deviennent stratégiques. Sans cadre public sur l'interopérabilité et la protection des données, la promesse de simplicité peut se transformer en dépendance à un opérateur unique.",
    question: "Quel risque le texte identifie-t-il ?",
    options: [
      "La disparition des vélos mécaniques.",
      "La concentration du pouvoir chez un opérateur privé.",
      "L'interdiction des abonnements.",
      "La fin du transport public.",
    ],
    correctIndex: 1,
    explanation: "MaaS without public interoperability rules risks vendor lock-in.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Extrait philosophique",
    passage: "La modernité automobile a naturalisé la vitesse privée : posséder une carrosserie fermée, c'est acheter une bulle de temps. Quand la ville resserre l'espace — pistes, trottoirs élargis — certains y voient une perte de liberté. Pourtant la rue a toujours été un bien commun rival ; reconnaître cette rivalité, c'est cesser de présenter le stationnement gratuit comme un droit naturel.",
    question: "Quel décalage l'auteur décrit-il ?",
    options: [
      "Entre trains de banlieue et métro.",
      "Entre liberté perçue de la voiture et rareté réelle de l'espace public.",
      "Entre provinces francophones et anglophones.",
      "Entre vélo électrique et vélo musculaire.",
    ],
    correctIndex: 1,
    explanation: "Car culture treats private speed as natural; street space is always contested.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "Les modèles prédictifs de trafic supposent un agent rationnel minimisant le temps. Les ethnographies du quotidien montrent des trajets « ancrés » : déposer un enfant, éviter un axe où l'on a vécu une agression, rendre visite à un aîné. Un plan de transport calibré uniquement sur des isochrones théoriques sous-estime ces détours chargés de sens — et surinvestit dans des gaines de vitesse peu utilisées par certains quartiers.",
    question: "Quel paradoxe le texte met-il en évidence ?",
    options: [
      "Les modèles surestiment toujours le vélo.",
      "La planification optimisée ignore des logiques de déplacement vécues.",
      "Les isochrones sont illégaux au Canada.",
      "Les agressions n'influencent jamais les trajets.",
    ],
    correctIndex: 1,
    explanation: "Rational time-minimization models miss care and safety detours.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai critique",
    passage: "On célèbre les « smart cities » tout en laissant les autobus surchargés l'hiver ; on photographie les trottinettes flambant neuves devant des arrêts sans abri. Le discours technologique peut devenir une parure qui déplace l'attention des investissements lents — garages de bus, personnel de maintenance, déneigement — vers des gadgets visibles dans les rapports annuels.",
    question: "Quelle tension le texte souligne-t-il ?",
    options: [
      "Entre français et anglais dans les annonces métro.",
      "Entre innovation visible et entretien invisible du transport.",
      "Entre taxis et Uber uniquement.",
      "Entre avions et trains.",
    ],
    correctIndex: 1,
    explanation: "Smart-city branding overshadows mundane but vital transit maintenance.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article spécialisé",
    passage: "Mesurer la « accessibilité » par le nombre de lignes desservant un quartier masque la fréquence réelle et la fiabilité en neige. Les travaux comparatifs montrent un effet de halo : une amélioration sur un axe central améliore la perception globale du réseau, même là où rien n'a changé. Les réformes ciblées peinent à restaurer la confiance si l'expérience quotidienne reste aléatoire.",
    question: "Pourquoi les réformes ciblées ont-elles un effet limité ?",
    options: [
      "Parce que les usagers ignorent les numéros de ligne.",
      "Parce que la perception globale dépasse les améliorations localisées.",
      "Parce que la neige n'affecte pas le transport.",
      "Parce que l'accessibilité ne se mesure pas.",
    ],
    correctIndex: 1,
    explanation: "Halo effects tie network trust to daily reliability, not line counts.",
  },
];
