import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Master Band C — C1–C2 argumentation, connectors & formal register. Curated for NCLC 7. */
export const MASTER_C: LemmaRow[] = [
  ["Indeed", "en effet", "En effet, la récente réforme fiscale désavantage considérablement les ménages de la classe moyenne."],
  ["In fact", "en fait", "En fait, les statistiques de l'emploi démontrent une réalité bien plus préoccupante cette année."],
  ["As a matter of fact", "en réalité", "En réalité, le gouvernement provincial n'a pas alloué les fonds nécessaires à cette initiative."],
  ["Thus", "ainsi", "Ainsi, la métropole devrait sérieusement repenser sa stratégie d'aménagement du territoire urbain et commercial."],
  ["For this reason", "pour cette raison", "Pour cette raison, le syndicat des travailleurs exige un moratoire immédiat sur les licenciements."],
  ["That is why", "c'est pourquoi", "C'est pourquoi la tenue d'une vaste consultation publique demeure une étape absolument indispensable."],
  ["On this basis", "sur cette base", "Sur cette base, le comité d'experts pourra enfin formuler des recommandations véritablement applicables."],
  ["In this regard", "à cet égard", "À cet égard, le cadre législatif actuel comporte d'importantes lacunes qu'il faut corriger rapidement."],
  ["With regard to", "en ce qui concerne", "En ce qui concerne le transport en commun, les attentes des usagers sont immenses."],
  ["As regards", "quant à", "Quant au financement des infrastructures scolaires, les municipalités attendent toujours des réponses claires."],
  ["Concerning", "concernant", "Concernant l'intégration des nouveaux arrivants, les organismes communautaires déploient des efforts absolument remarquables."],
  ["Meanwhile", "pendant ce temps", "Pendant ce temps, la spéculation immobilière continue de sévir dans de nombreux quartiers montréalais."],
  ["In the meantime", "entre-temps", "Entre-temps, les patients confrontés aux listes d'attente s'impatientent face à l'inaction du ministère."],
  ["Subsequently", "par la suite", "Par la suite, l'administration a dû justifier le dépassement budgétaire de cet ambitieux chantier."],
  ["Thereafter", "dès lors", "Dès lors, les municipalités environnantes ont imposé des restrictions strictes sur l'utilisation de l'eau."],
  ["Afterwards", "ensuite", "Ensuite, le conseil d'agglomération devra ratifier cet accord environnemental pour qu'il entre en vigueur."],
  ["At first", "d'abord", "D'abord, il convient d'analyser les retombées économiques de ce projet de loi controversé."],
  ["First and foremost", "avant tout", "Avant tout, le système de justice doit garantir l'impartialité de l'ensemble de ses procédures."],
  ["Ultimately", "en définitive", "En définitive, la relance de l'industrie touristique reposera sur le soutien accordé aux entrepreneurs."],
  ["Eventually", "finalement", "Finalement, sous la pression des groupes écologistes, la compagnie pétrolière a abandonné son forage."],
  ["In a nutshell", "en somme", "En somme, les mesures d'austérité annoncées risquent d'étouffer la reprise économique amorcée cet hiver."],
  ["To sum up", "pour résumer", "Pour résumer la situation, la crise du logement nécessite une intervention étatique plus musclée."],
  ["On this point", "sur ce point", "Sur ce point précis, les conclusions du vérificateur général sont accablantes pour l'ancienne administration."],
  ["That said", "cela dit", "Cela dit, la piétonnisation du centre-ville apporte également des défis logistiques aux commerçants locaux."],
  ["Having said that", "toutefois", "Toutefois, une refonte complète du mode de scrutin semble prématurée dans le contexte actuel."],
  ["Be that as it may", "quoi qu'il en soit", "Quoi qu'il en soit, le fardeau fiscal pesant sur les contribuables dépasse l'entendement."],
  ["In any event", "en tout état de cause", "En tout état de cause, l'hôpital de la région conservera ses services d'urgence ouverts."],
  ["After all", "après tout", "Après tout, la protection du patrimoine architectural relève de notre devoir collectif envers l'histoire."],
  ["Either way", "dans les deux cas", "Dans les deux cas, la transition énergétique imposera des sacrifices à l'industrie manufacturière québécoise."],
  ["Still", "pourtant", "Pourtant, de multiples rapports scientifiques contredisent ouvertement les prétentions de ce lobby industriel."],
  ["Yet", "cependant", "Cependant, la francisation des milieux de travail continue de se heurter à des obstacles chroniques."],
  ["Nonetheless", "il n'en demeure pas moins que", "Il n'en demeure pas moins que l'endettement étudiant atteint des sommets véritablement inquiétants."],
  ["Despite this", "malgré cela", "Malgré cela, le promoteur immobilier maintient son intention de raser ce boisé centenaire."],
  ["Likewise", "de même", "De même, la prolifération des plateformes de location à court terme aggrave la crise locative."],
  ["Equally", "également", "Également, l'essor de l'intelligence artificielle soulève des questions éthiques qui méritent une profonde réflexion."],
  ["In the same vein", "dans le même ordre d'idées", "Dans le même ordre d'idées, la censure sur les réseaux sociaux menace la liberté d'expression."],
  ["In turn", "à son tour", "À son tour, le gouvernement fédéral devra clarifier sa position sur l'exploitation minière."],
  ["On the whole", "dans l'ensemble", "Dans l'ensemble, les syndicats ont salué cette entente de principe avec le secteur patronal."],
  ["Overall", "globalement", "Globalement, la densification urbaine freine l'étalement mais exerce une forte pression sur les infrastructures existantes."],
  ["Partly", "en partie", "En partie, cet exode rural s'explique par la dévitalisation des régions les plus éloignées."],
  ["Namely", "à savoir", "Le programme cible deux enjeux majeurs, à savoir le décrochage scolaire et l'isolement social."],
  ["Not least", "entre autres", "L'investissement vise, entre autres, à consolider le réseau cyclable des différents arrondissements montréalais."],
  ["Provided that", "à condition que", "Les subventions seront octroyées à condition que les entreprises respectent des normes écologiques strictes."],
  ["So that", "de sorte que", "L'arrêté municipal a été modifié de sorte que les terrasses puissent rester ouvertes plus tard."],
  ["So as to", "afin de", "Le ministère a décentralisé ses services afin de mieux répondre aux besoins des communautés autochtones."],
  ["In order that", "afin que", "Un médiateur fut nommé afin que les négociations aboutissent avant le déclenchement de la grève."],
  ["Seeing that", "étant donné que", "Étant donné que l'inflation persiste, la banque centrale maintiendra probablement son taux directeur."],
  ["Given that", "vu que", "Vu que le nombre d'inscriptions diminue, l'université devra rationaliser son offre de cours."],
  ["Now that", "maintenant que", "Maintenant que la commission a remis ses recommandations, l'assemblée législative doit légiférer rapidement."],
  ["Once", "une fois que", "Une fois que le viaduc sera rénové, la circulation périphérique retrouvera enfin sa fluidité."],
  ["Before", "avant que", "Avant que cette directive ne soit appliquée, une étude d'impact environnemental sera rigoureusement menée."],
  ["Since (because)", "puisque", "Puisque l'urgence climatique nous guette, la complaisance politique n'a plus sa place au parlement."],
  ["If only", "si seulement", "Si seulement les dirigeants avaient anticipé la saturation de notre réseau de la santé."],
  ["Whether or not", "que ce soit ou non", "Que le projet soit approuvé ou non, le tollé populaire aura marqué les esprits."],
  ["No matter what", "quoi qu'il arrive", "Quoi qu'il arrive, le maintien des subventions aux agriculteurs locaux s'avère stratégiquement incontournable."],
  ["Insofar as possible", "dans la mesure du possible", "Dans la mesure du possible, privilégions les chaînes d'approvisionnement courtes pour stimuler l'économie locale."],
  ["To that end", "à cette fin", "À cette fin, un fonds de relève d'urgence vient d'être débloqué par le secrétariat."],
  ["For that matter", "d'ailleurs", "D'ailleurs, la tarification sociale de l'électricité soulève de vifs débats depuis plusieurs années."],
  ["By contrast", "à l'opposé", "À l'opposé, la métropole voisine privilégie une approche foncièrement différente concernant l'itinérance."],
  ["By comparison", "comparativement", "Comparativement aux trimestres précédents, l'indice de confiance des consommateurs s'est fortement dégradé."],
  ["Relative to", "par rapport à", "Par rapport aux nations scandinaves, nos politiques familiales présentent un retard assez flagrant."],
  ["Aside from", "mis à part", "Mis à part le déficit structurel de l'État, le bilan gouvernemental comporte des succès indéniables."],
  ["Apart from", "en dehors de", "En dehors de ce scandale financier, le dirigeant jouissait d'une excellente réputation publique."],
  ["Instead of", "au lieu de", "Au lieu de subventionner des industries polluantes, investissons massivement dans les technologies vertes innovantes."],
  ["Rather than", "plutôt que", "Plutôt que d'imposer unilatéralement cette réforme, la ministre aurait dû consulter les principaux intéressés."],
  ["As opposed to", "contrairement à", "Contrairement aux prévisions alarmistes, le marché de l'emploi a encaissé le choc avec résilience."],
  ["As well as", "ainsi que", "L'accord commercial bénéficiera au secteur forestier ainsi que, dans une moindre mesure, au secteur manufacturier."],
  ["Both... and", "à la fois... et", "Le candidat a su rallier à la fois l'aile modérée et l'aile radicale du parti."],
  ["Either... or", "soit... soit", "Soit l'exécutif recule sur l'âge de la retraite, soit il affrontera une grève générale illimitée."],
  ["Neither... nor", "ni... ni", "Ni le premier ministre ni son cabinet n'ont souhaité commenter ces allégations troublantes."],
  ["Simply put", "en clair", "En clair, le pouvoir d'achat des travailleurs précaires s'est drastiquement érodé depuis deux décennies."],
  ["To my mind", "à mon sens", "À mon sens, la privatisation d'une société d'État aussi vitale constituerait une erreur historique."],
  ["I hold the view that", "je considère que", "Je considère que la gratuité scolaire au niveau universitaire dynamiserait considérablement la mobilité sociale."],
  ["I maintain that", "je maintiens que", "Je maintiens que la désinformation représente la plus grave menace pour nos processus démocratiques."],
  ["I would argue that", "je soutiens que", "Je soutiens que la désobéissance civile demeure légitime face à une loi fondamentalement inique."],
  ["It strikes me that", "il me frappe que", "Il me frappe que la crise des médias traditionnels indiffère une grande partie de la population."],
  ["One might say that", "on pourrait affirmer que", "On pourrait affirmer que la mondialisation a exacerbé les inégalités de revenus à l'échelle planétaire."],
  ["One could argue that", "on pourrait soutenir que", "On pourrait soutenir que ce protectionnisme tarifaire relève davantage d'une stratégie purement électoraliste."],
  ["It is often said that", "il est souvent dit que", "Il est souvent dit que l'éducation constitue le meilleur rempart contre les discours populistes."],
  ["It is widely held that", "il est largement admis que", "Il est largement admis que la transition numérique bouscule les paradigmes économiques de longue date."],
  ["There is reason to believe", "il y a lieu de croire", "Il y a lieu de croire que le taux d'inflation amorcera une lente redescente cet automne."],
  ["It is fair to say", "il est juste de dire", "Il est juste de dire que le filet social canadien requiert une profonde modernisation."],
  ["It would be unfair to say", "il serait injuste de dire", "Il serait injuste de dire que la jeunesse se désintéresse complètement de la chose publique."],
  ["Far from it", "loin de là", "La controverse est loin d'être apaisée ; de nombreuses manifestations sont d'ailleurs prévues ce week-end."],
  ["Not necessarily", "pas nécessairement", "Un investissement étranger ne se traduit pas nécessairement par des créations d'emplois locaux durables."],
  ["By no means", "nullement", "L'argumentaire de la partie plaignante n'est nullement étayé par des preuves tangibles ou empiriques."],
  ["Under no circumstances", "en aucun cas", "En aucun cas la souveraineté alimentaire de notre nation ne devrait dépendre d'accords bilatéraux précaires."],
  ["I wholeheartedly support", "je cautionne sans réserve", "Je cautionne sans réserve l'initiative visant à décriminaliser la possession de certaines substances."],
  ["I strongly disagree", "je suis en profond désaccord", "Je suis en profond désaccord avec la banalisation de la violence dans l'espace public."],
  ["I remain unconvinced", "je reste sceptique", "Je reste sceptique quant à la capacité de cette technologie à réduire réellement notre empreinte carbone."],
  ["I am in two minds", "je suis partagé", "Je suis partagé entre la nécessité de sécuriser les frontières et le devoir d'accueillir les réfugiés."],
  ["The fact remains that", "il n'en reste pas moins que", "Il n'en reste pas moins que l'urgence dans les hôpitaux frôle constamment le point de rupture."],
  ["It bears emphasizing that", "il importe de souligner que", "Il importe de souligner que la pénurie de main-d'œuvre ralentit considérablement la croissance économique régionale."],
  ["What is at stake", "ce qui est en jeu", "Ce qui est en jeu, c'est la survie de milliers de petites exploitations agricoles indépendantes."],
  ["The crux of the matter", "le nœud du problème", "Le nœud du problème réside dans l'incapacité chronique à attirer et retenir le personnel infirmier."],
  ["The issue boils down to", "la question se résume à", "La question se résume à l'équilibre périlleux entre développement économique et préservation des écosystèmes."],
  ["Make no mistake", "ne nous y trompons pas", "Ne nous y trompons pas : cette réforme fiscale frappera d'abord les foyers monoparentaux."],
  ["Let me be clear", "soyons clairs", "Soyons clairs : le financement de nos infrastructures culturelles ne doit plus être traité comme facultatif."],
  ["I wish to stress", "je tiens à insister sur", "Je tiens à insister sur le courage indéniable dont ont fait preuve les lanceurs d'alerte."],
  ["We must not lose sight of", "il ne faut pas perdre de vue", "Il ne faut pas perdre de vue l'impact dévastateur de ces politiques sur l'itinérance urbaine."],
  ["It is high time", "il est grand temps", "Il est grand temps de réviser nos méthodes d'évaluation au sein du parcours scolaire provincial."],
  ["There is little doubt that", "il ne fait guère de doute que", "Il ne fait guère de doute que l'intelligence artificielle redéfinira le marché du travail d'ici dix ans."],
  ["Speaking personally", "à titre personnel", "À titre personnel, l'idée d'un revenu de base universel me semble être une solution d'avenir."],
  ["From our perspective", "de notre point de vue", "De notre point de vue, le monopole de cette entreprise étouffe complètement l'innovation dans le secteur."],
  ["As far as I am concerned", "en ce qui me concerne", "En ce qui me concerne, l'inaction climatique des pays industrialisés s'apparente à une faute morale."],
  ["It seems fair to assume", "il est raisonnable de supposer", "Il est raisonnable de supposer que l'adoption des véhicules électriques s'accélérera de manière exponentielle."],
  ["I take the view that", "j'estime que", "J'estime que la liberté de la presse est systématiquement érodée par la concentration des conglomérats médiatiques."],
  ["I would go so far as to say", "j'irais jusqu'à dire", "J'irais jusqu'à dire que l'ubérisation de l'économie menace l'essence même de nos acquis sociaux."],
  ["It goes without saying that", "il va de soi que", "Il va de soi que l'indépendance de la magistrature constitue un pilier de notre démocratie."],
  ["Many would agree that", "beaucoup conviendront que", "Beaucoup conviendront que la dépendance aux énergies fossiles fragilise considérablement notre géopolitique actuelle."],
  ["Few would deny that", "peu nieront que", "Peu nieront que le télétravail a bouleversé en profondeur nos habitudes de vie et de transport."],
  ["It is no secret that", "ce n'est un secret pour personne que", "Ce n'est un secret pour personne que les infrastructures hydrauliques de la métropole nécessitent d'immenses chantiers."],
  ["It is hardly surprising that", "il n'est guère surprenant que", "Il n'est guère surprenant que l'annonce de ce mégaprojet ait suscité une vive levée de boucliers."],
  ["To be honest", "pour être franc", "Pour être franc, le discours inaugural manquait cruellement de vision stratégique sur le long terme."],
  ["Frankly speaking", "franchement", "Franchement, cet amendement ressemble davantage à une manœuvre partisane qu'à une véritable volonté de réforme."],
  ["Understandably", "on comprend bien que", "On comprend bien que les résidents craignent la dévaluation de leurs propriétés suite au nouveau zonage."],
  ["Regrettably", "malheureusement", "Malheureusement, le comité éthique s'est prononcé en faveur de l'exploitation forestière de ce territoire protégé."],
  ["Fortunately", "heureusement", "Heureusement, une injonction de la cour supérieure a temporairement freiné l'avancée de ce projet destructeur."],
  ["Ideally", "idéalement", "Idéalement, une telle politique publique exigerait l'assentiment des Premières Nations concernées par le tracé."],
  ["Theoretically speaking", "en théorie", "En théorie, cette redistribution des richesses devrait combler le fossé grandissant entre les classes sociales."],
  ["Practically speaking", "en pratique", "En pratique, l'obtention d'un permis de construire dans cet arrondissement relève souvent du parcours du combattant."],
  ["In principle", "en principe", "En principe, la Charte des droits garantit une parfaite égalité de traitement envers chaque citoyen."],
  ["In reality", "dans les faits", "Dans les faits, la bureaucratie entrave souvent les initiatives entrepreneuriales au niveau des start-ups."],
  ["To defend", "défendre", "L'avocate a brillamment su défendre le principe de proportionnalité devant les juges de la Cour Suprême."],
  ["To denounce", "dénoncer", "L'éditorialiste n'a pas hésité à dénoncer la complaisance des autorités face au lobby pharmaceutique."],
  ["To deplore", "déplorer", "Le regroupement des locataires déplore l'éviction massive survenue récemment dans ce quartier traditionnellement ouvrier."],
  ["To invoke", "invoquer", "L'opposition compte invoquer l'article constitutionnel protégeant le droit d'association afin d'annuler cette loi."],
  ["To cite", "citer", "Pour étayer son propos, la chercheuse n'a pas manqué de citer les récentes données de Statistique Canada."],
  ["To refer to", "se référer à", "Le traité de libre-échange se réfère expressément aux normes de l'Organisation mondiale du travail."],
  ["To allude to", "faire allusion à", "Durant la conférence, le recteur a clairement fait allusion aux coupes budgétaires prévues par le ministère."],
  ["To formulate", "formuler", "La commission d'enquête prendra encore six mois avant de pouvoir formuler un acte d'accusation précis."],
  ["To articulate", "articuler", "Le parti peine désespérément à articuler une vision cohérente concernant l'accueil des demandeurs d'asile."],
  ["To spell out", "préciser", "Il incombe à l'Ordre des médecins de préciser les balises encadrant la télémédecine."],
  ["To elaborate on", "développer", "Pourriez-vous développer votre argument concernant les répercussions de l'intelligence artificielle sur l'emploi local?"],
  ["To expand on", "approfondir", "Le séminaire permettra d'approfondir les théories postcoloniales qui influencent actuellement la sociologie moderne."],
  ["To point out", "faire remarquer", "Il est crucial de faire remarquer que ces statistiques omettent une part significative de l'économie souterraine."],
  ["To note", "noter", "Notons que la transition vers une flotte automobile électrique exigera un investissement massif en infrastructures."],
  ["To remind", "rappeler", "Je me dois de rappeler que le mandat de la commission d'éthique arrivera très bientôt à échéance."],
  ["To warn", "mettre en garde", "Le regroupement des scientifiques a tenu à mettre en garde contre les dérives potentielles du clonage."],
  ["To urge", "exhorter", "L'ONU continue d'exhorter les pays signataires à respecter scrupuleusement leurs engagements climatiques de l'Accord de Paris."],
  ["To call for", "réclamer", "Les étudiants en grève réclament une refonte majeure du mode d'attribution des bourses de recherche."],
  ["To appeal for", "appeler à", "Le maire sortant n'a pas hésité à appeler à la solidarité envers les victimes de l'ouragan."],
  ["To accuse", "accuser", "Certaines associations n'hésitent plus à accuser les multinationales technologiques d'évasion fiscale massive et systémique."],
  ["To blame", "blâmer", "Il serait simpliste de blâmer l'immigration pour les pénuries endémiques de logements abordables en région urbaine."],
  ["To hold responsible", "tenir responsable", "La société civile exige de tenir le gouvernement responsable du laxisme régnant dans les CHSLD."],
  ["To commend", "saluer", "Il convient de saluer l'ingéniosité des chercheurs montréalais dans la lutte contre ce nouveau pathogène."],
  ["To endorse publicly", "cautionner", "Aucun leader politique ne peut décemment cautionner les actes de vandalisme survenus durant l'émeute d'hier soir."],
  ["To uphold", "maintenir", "Le tribunal d'appel a décidé de maintenir la lourde peine infligée au dirigeant de l'entreprise pharmaceutique."],
  ["To dispute / To contest", "contester", "Le syndicat patronal prévoit de contester vigoureusement la constitutionnalité de cette nouvelle norme du travail."],
  ["To retort", "répliquer", "La ministre a vivement répliqué en exposant le bilan comptable désastreux de la précédente administration libérale."],
  ["To counter", "contre-argumenter", "Pour contre-argumenter, la défense s'est appuyée sur des précédents juridiques internationaux fort complexes."],
  ["To assess", "évaluer", "Une agence indépendante sera prochainement mandatée pour évaluer la rentabilité de ce prolongement du métro."],
  ["To weigh up", "peser", "Avant d'entériner cette alliance commerciale, il nous faudra peser minutieusement les avantages et les inconvénients stratégiques."],
  ["To take into account", "tenir compte de", "L'urbanisme de demain devra impérativement tenir compte de la multiplication des événements météorologiques extrêmes."],
  ["To ignore / To overlook", "ignorer", "Ignorer le décrochage scolaire chez les garçons hypothèque gravement l'avenir économique de toute une génération."],
  ["To bear in mind", "garder à l'esprit", "Il faut garder à l'esprit que l'industrie manufacturière représente toujours le poumon économique de cette province."],
  ["To adopt", "adopter", "Le conseil de l'agglomération a décidé d'adopter un ambitieux plan directeur en matière de mobilité durable."],
  ["To espouse", "épouser", "Ce courant philosophique pousse la jeunesse à épouser des idéaux écologistes plus radicaux et revendicateurs."],
  ["To renounce", "renoncer à", "Face à la levée de boucliers, le promoteur immobilier a préféré renoncer à ce mégaprojet d'enfouissement."],
  ["To violate / To breach", "enfreindre", "Quiconque osera enfreindre cette ordonnance sanitaire s'exposera à de très sévères amendes pénales."],
  ["To comply with", "se conformer à", "Toute entreprise forestière exploitant ce domaine public devra se conformer à la nouvelle législation environnementale rigoureuse."],
  ["To trigger", "déclencher", "La brutalité de l'intervention policière a suffi à déclencher des émeutes incontrôlables en plein centre-ville."],
  ["To spark", "susciter", "Le documentaire choc sur l'agro-industrie promet de susciter un vif débat lors de sa diffusion télévisuelle."],
  ["To fuel", "alimenter", "L'absence cruelle de transparence tend inévitablement à alimenter le cynisme des électeurs envers la classe politique."],
  ["To bolster", "renforcer", "Ce nouveau financement fédéral viendra grandement renforcer le pôle de recherche en aérospatiale de l'université locale."],
  ["To shore up", "consolider", "La fusion des deux chaînes de télécommunications vise manifestement à consolider leur hégémonie sur le marché nord-américain."],
  ["To underpin", "sous-tendre", "Les principes d'équité intergénérationnelle doivent sous-tendre chaque décision budgétaire concernant l'exploitation de nos ressources minières."],
  ["To hamper / To hinder", "entraver", "Le manque criant de garderies subventionnées ne cesse d'entraver le retour au travail de nombreuses mères."],
  ["To curb", "freiner", "La banque du pays a procédé à une hausse des taux d'intérêt dans l'espoir de freiner l'inflation galopante."],
  ["To foster", "favoriser", "Les coopératives d'habitation s'imposent comme un excellent moyen de favoriser la cohésion sociale dans les grands centres urbains."],
  ["To stem from", "provenir de", "L'essentiel de la dette accumulée semble provenir de déficits d'opération structurels non résolus depuis la dernière décennie."],
  ["To derive from", "découler de", "La frustration des contribuables découle directement de la hausse brutale et inexpliquée des tarifs d'électricité."],
  ["To give rise to", "donner lieu à", "L'attribution douteuse de ces lucratifs contrats publics a donné lieu à une vaste enquête anti-corruption provinciale."],
  ["To entail", "entraîner", "Une telle déréglementation du marché financier pourrait potentiellement entraîner une crise économique sans précédent."],
  ["To amount to", "équivaloir à", "Le silence assourdissant des instances diplomatiques équivaut, à bien des égards, à de la complicité implicite."],
  ["To hinge on", "dépendre de", "Le succès de ce vaste plan de relance va grandement dépendre de la collaboration du secteur privé."],
  ["To revolve around", "s'articuler autour de", "Le roman postmoderne s'articule brillamment autour de la quête identitaire d'un immigrant de la deuxième génération."],
  ["To touch on", "aborder", "Le conférencier a osé aborder le sujet délicat du financement occulte des partis politiques fédéraux."],
  ["To raise awareness", "sensibiliser", "La campagne nationale vise avant tout à sensibiliser la jeunesse aux dangers de la cyberintimidation chronique."],
  ["To disclose", "divulguer", "La fuite de documents confidentiels a contraint le ministère à divulguer l'étendue réelle du scandale écologique."],
  ["To uncover", "mettre au jour", "L'enquête journalistique indépendante a finalement mis au jour un vaste réseau de prête-noms au sein de l'industrie de la construction."],
  ["To shed light on", "éclairer", "Les archives récemment déclassifiées permettent enfin d'éclairer les circonstances obscures entourant cette célèbre crise diplomatique."],
  ["To cast doubt on", "jeter le doute sur", "La rétractation inattendue de ce témoin clé est venue jeter le doute sur toute l'accusation pénale."],
  ["To bear witness to", "témoigner de", "Ces ruines patrimoniales majestueuses témoignent de l'essor industriel flamboyant qu'a connu cette région au siècle dernier."],
  ["To contradict", "contredire", "Les projections démographiques de l'institut viennent formellement contredire le narratif véhiculé par le chef de l'opposition officielle."],
  ["To clash with", "se heurter à", "La volonté du législateur s'est heurtée à la réalité du terrain et aux contraintes opérationnelles locales."],
  ["To align with", "concorder avec", "La plateforme électorale du candidat semble parfaitement concorder avec les attentes des syndicats de l'enseignement."],
  ["To differ from", "différer de", "Le mode de scrutin proportionnel diffère considérablement du système uninominal actuellement en vigueur dans nos élections canadiennes."],
  ["To resonate with", "trouver un écho chez", "Ce puissant discours sur la réconciliation a immédiatement trouvé un écho favorable chez les peuples autochtones."],
  ["To echo", "faire écho à", "L'explosion de la pauvreté urbaine fait dramatiquement écho aux sombres prédictions formulées par les économistes hétérodoxes."],
  ["To typify", "illustrer", "La déroute boursière de cette jeune pousse technologique illustre bien les dangers liés à la surspéculation financière."],
  ["To embody", "incarner", "La jeune militante écologiste est rapidement parvenue à incarner les profondes inquiétudes climatiques de toute sa génération."],
  ["To dismiss", "rejeter", "Le comité de déontologie n'a eu d'autre choix que de rejeter ces plaintes qu'il jugeait frivoles et malveillantes."],
  ["To shrug off criticism", "balayer du revers de la main", "Le président du conseil d'administration a balayé du revers de la main les préoccupations des actionnaires minoritaires."],
  ["Compelling", "convaincant", "La thèse soutenue par l'auteur offre un argumentaire hautement convaincant contre la surconsommation de viande rouge."],
  ["Persuasive", "persuasif", "Grâce à son discours persuasif, l'avocate de la défense est parvenue à semer le doute dans l'esprit des jurés."],
  ["Sound", "solide", "Le plan d'affaires de la coopérative est particulièrement solide et repose sur des prévisions financières extrêmement rigoureuses."],
  ["Flawed", "lacunaire", "La méthodologie lacunaire employée par ce laboratoire de recherche remet sérieusement en question la validité des résultats obtenus."],
  ["Well-founded", "bien fondé", "Le mécontentement de la population concernant l'état du réseau routier apparaît comme étant tout à fait bien fondé."],
  ["Well-argued", "bien argumenté", "Ce mémoire doctoral s'avère non seulement bien argumenté, mais il offre également des pistes de solution novatrices."],
  ["Coherent", "cohérent", "La restructuration ministérielle proposée permettra d'établir un organigramme plus cohérent au sein de la fonction publique d'État."],
  ["Inconsistent", "contradictoire", "Le témoignage contradictoire du suspect principal a lourdement pesé dans la décision finale rendue par le juge d'instruction."],
  ["Irrelevant", "hors sujet", "Votre digression sur l'histoire ancienne s'avère manifestement hors sujet dans le cadre de ce débat sur l'intelligence artificielle."],
  ["Appropriate", "approprié", "Le recours au fonds d'urgence semble particulièrement approprié face à l'ampleur inédite des dégâts causés par les inondations printanières."],
  ["Adequate", "adéquat", "Le personnel des urgences manque cruellement de matériel adéquat pour faire face aux multiples vagues pandémiques successives."],
  ["Disappointing", "décevant", "Le bilan environnemental du gouvernement sortant s'avère profondément décevant au regard de ses ambitieuses promesses électorales initiales."],
  ["Encouraging", "encourageant", "La diminution graduelle du taux de chômage des jeunes diplômés constitue un signal macroéconomique extrêmement encourageant."],
  ["Alarming", "alarmant", "Le déclin alarmant de la biodiversité dans les zones humides du grand nord canadien requiert une intervention immédiate."],
  ["Promising", "prometteur", "Le recours à la thérapie génique représente une avenue de recherche exceptionnellement prometteuse pour le traitement des maladies rares."],
  ["Significant", "significatif", "La municipalité vient d'annoncer un investissement particulièrement significatif destiné à l'amélioration du réseau de traitement des eaux usées."],
  ["Substantial", "substantiel", "L'adoption de ce projet de loi entraînera un transfert substantiel de responsabilités vers les diverses administrations municipales québécoises."],
  ["Moderate", "modéré", "Malgré les craintes d'une récession imminente, le marché immobilier national n'a connu qu'un ralentissement somme toute modéré."],
  ["Excessive", "excessif", "Le recours excessif au temps supplémentaire obligatoire épuise dangereusement les effectifs infirmiers du réseau public de santé provincial."],
  ["Balanced", "équilibré", "Ce journal indépendant se targue d'offrir une couverture médiatique toujours équilibrée lors des périodes de campagnes électorales fédérales."],
  ["Biased", "biaisé", "Le sondage d'opinion s'avère fondamentalement biaisé en raison d'un échantillonnage qui ne représente pas adéquatement la diversité démographique canadienne."],
  ["Objective", "objectif", "Le commissaire à l'éthique a rédigé un rapport purement objectif, exempt de toute interférence politique ou d'idéologie partisane."],
  ["Justified", "justifié", "Le recours à la clause dérogatoire demeure justifié par la nécessité de protéger le caractère exceptionnel du patrimoine linguistique."],
  ["Reasonable", "raisonnable", "Il apparaît tout à fait raisonnable d'exiger des grandes plateformes de diffusion qu'elles contribuent financièrement à la création culturelle locale."],
  ["Sensible", "sensé", "La mise en place d'une tarification dynamique de l'électricité semble être le moyen le plus sensé pour réduire notre consommation d'énergie hivernale."],
  ["Pragmatic", "pragmatique", "La diplomatie canadienne a adopté une approche nettement plus pragmatique concernant les accords de libre-échange avec les nations émergentes d'Asie."],
  ["Idealistic", "idéaliste", "La vision idéaliste de ce manifeste politique se heurte brutalement aux impératifs économiques actuels et aux lourdes contraintes budgétaires gouvernementales."],
  ["Feasible", "réalisable", "L'électrification complète des transports en commun urbains s'avère dorénavant un projet politiquement et technologiquement réalisable d'ici l'horizon de 2035."],
  ["Timely", "opportun", "L'intervention rapide de la banque centrale fut un geste opportun ayant empêché un effondrement complet du système bancaire commercial canadien."],
  ["Crucial", "crucial", "L'adoption rapide de cette charte sur la laïcité a constitué un enjeu électoral crucial lors des dernières élections provinciales québécoises."],
  ["Essential", "essentiel", "Le réseau ferroviaire pancanadien a joué un rôle absolument essentiel dans le développement industriel et démographique de notre vaste pays nord-américain."],
  ["Indispensable", "indispensable", "L'apport des travailleurs étrangers temporaires s'avère désormais indispensable pour pallier la pénurie de main-d'œuvre chronique qui afflige le secteur agricole québécois."],
  ["Mandatory", "obligatoire", "Le port du casque protecteur est devenu strictement obligatoire sur l'ensemble des vastes chantiers de construction sous juridiction provinciale."],
  ["Equitable", "équitable", "La péréquation financière vise à garantir un financement équitable des divers services sociaux entre toutes les provinces constitutives de la fédération canadienne."],
  ["Proportionate", "proportionné", "La cour suprême a dû vérifier si les restrictions imposées par décret gouvernemental constituaient un moyen proportionné d'atteindre cet objectif sanitaire vital."],
  ["Measured", "modéré", "Un ton modéré et rassembleur favorise davantage la résolution de conflits syndicaux qu'une approche dogmatique et continuellement agressive de confrontation publique."],
  ["Thoughtful", "réfléchi", "Le dépôt de ce livre blanc représente l'aboutissement d'un processus démocratique particulièrement réfléchi, rigoureux et largement consultatif mené à l'échelle nationale."],
  ["Oversimplified", "simpliste", "Il serait tristement simpliste de réduire la crise actuelle de l'itinérance à une simple question de toxicomanie ou de désinvestissement institutionnel."],
  ["Reductionist", "réductionniste", "La sociologie contemporaine critique vivement la vision réductionniste qui attribue systématiquement l'échec scolaire au seul milieu socioéconomique défavorisé d'origine de l'élève."]
];
