import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 6 — Compréhension orale. Theme: settling into working life in Canada.
 *
 * `audioScript` is rendered by Edge TTS, so each script is written to be read
 * aloud cleanly: no bullet points, numbers spelled where ambiguous, and
 * dialogue turns separated by em dashes.
 */
export const TCF_LISTENING_P6: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "À la boulangerie",
    audioScript: "— Bonjour, je voudrais deux croissants et une baguette, s'il vous plaît. — Voilà. Cela fait six dollars cinquante. — Tenez. — Merci, bonne journée !",
    question: "Combien le client doit-il payer ?",
    options: ["Deux dollars.", "Six dollars cinquante.", "Sept dollars.", "Cinq dollars cinquante."],
    correctIndex: 1,
    explanation: "The baker says the total is six dollars fifty.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Annonce en gare",
    audioScript: "Votre attention, s'il vous plaît. Le train à destination de Québec partira du quai numéro trois à quatorze heures vingt. Nous vous remercions de votre patience.",
    question: "De quel quai le train part-il ?",
    options: ["Du quai numéro deux.", "Du quai numéro trois.", "Du quai numéro quatre.", "Du quai numéro cinq."],
    correctIndex: 1,
    explanation: "The announcement gives platform number three.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Au téléphone",
    audioScript: "— Allô, bonjour, je voudrais parler à madame Roy. — Elle est en réunion jusqu'à midi. Voulez-vous laisser un message ? — Oui, dites-lui que Samuel a appelé.",
    question: "Que fait madame Roy en ce moment ?",
    options: ["Elle déjeune.", "Elle est en réunion.", "Elle est en congé.", "Elle est au téléphone."],
    correctIndex: 1,
    explanation: "She is in a meeting until noon.",
  },
  {
    id: 4,
    level: "A1",
    topic: "La météo",
    audioScript: "Voici la météo pour demain. Le matin, il fera froid, moins cinq degrés, avec un ciel dégagé. L'après-midi, la neige commencera vers seize heures et continuera toute la soirée.",
    question: "Quand la neige commencera-t-elle ?",
    options: ["Le matin très tôt.", "Vers midi.", "Vers seize heures.", "Pendant la nuit."],
    correctIndex: 2,
    explanation: "Snow starts around four in the afternoon.",
  },
  {
    id: 5,
    level: "A2",
    topic: "Au bureau",
    audioScript: "— Tu as terminé le rapport ? — Presque. Il me manque les chiffres du mois de mars. Sonia devait me les envoyer hier, mais je n'ai rien reçu. — Je la vois cet après-midi, je lui rappellerai.",
    question: "Pourquoi le rapport n'est-il pas terminé ?",
    options: [
      "Parce que la personne manque de temps.",
      "Parce qu'il manque les chiffres de mars.",
      "Parce que Sonia est absente cette semaine.",
      "Parce que le sujet a changé récemment.",
    ],
    correctIndex: 1,
    explanation: "The March figures are missing; Sonia was supposed to send them.",
  },
  {
    id: 6,
    level: "A2",
    topic: "À la pharmacie",
    audioScript: "— Ce sirop, je le prends combien de fois par jour ? — Deux fois, le matin et le soir, après les repas. Et surtout, ne dépassez pas cinq jours de traitement sans revoir votre médecin.",
    question: "Quand faut-il prendre ce sirop ?",
    options: [
      "Avant les repas, trois fois par jour.",
      "Après les repas, matin et soir.",
      "Uniquement le soir avant de dormir.",
      "À n'importe quel moment de la journée.",
    ],
    correctIndex: 1,
    explanation: "Twice a day, morning and evening, after meals.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Message vocal",
    audioScript: "Bonjour, c'est le garage Tremblay. Votre voiture est prête, mais nous avons dû changer aussi les plaquettes de frein. Le montant final est donc plus élevé que prévu. Rappelez-nous avant de passer.",
    question: "Pourquoi le garage demande-t-il de rappeler ?",
    options: [
      "Parce que la voiture n'est pas encore prête.",
      "Parce que le prix a augmenté par rapport au devis.",
      "Parce qu'une pièce doit encore être commandée.",
      "Parce que le garage ferme plus tôt aujourd'hui.",
    ],
    correctIndex: 1,
    explanation: "Extra work on the brake pads made the final amount higher than expected.",
  },
  {
    id: 8,
    level: "A2",
    topic: "À la bibliothèque",
    audioScript: "— Je peux emprunter combien de livres à la fois ? — Dix, pour trois semaines. Vous pouvez renouveler une seule fois en ligne, sauf si un autre lecteur a réservé le livre.",
    question: "Dans quel cas le renouvellement est-il impossible ?",
    options: [
      "Si le lecteur a déjà dix livres.",
      "Si un autre lecteur a réservé le livre.",
      "Si le délai de trois semaines est dépassé.",
      "Si le renouvellement est demandé en ligne.",
    ],
    correctIndex: 1,
    explanation: "Renewal is blocked when another reader has reserved the book.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Invitation",
    audioScript: "— On organise un souper pour le départ de Malik, vendredi soir. Tu viens ? — Vendredi, je travaille jusqu'à vingt heures. — Ce n'est pas grave, on commence à vingt heures trente.",
    question: "Que décide-t-on finalement ?",
    options: [
      "La personne ne pourra pas venir au souper.",
      "Le souper est reporté à un autre jour.",
      "La personne pourra venir car le souper commence plus tard.",
      "Le souper commencera juste après le travail.",
    ],
    correctIndex: 2,
    explanation: "The dinner starts at eight thirty, after the person finishes work at eight.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Consigne de sécurité",
    audioScript: "Avant de quitter le laboratoire, éteignez les appareils, rangez les produits dans l'armoire fermée à clé et signez le registre à l'entrée. La clé se dépose au poste de sécurité, jamais dans un tiroir.",
    question: "Où faut-il laisser la clé ?",
    options: [
      "Dans un tiroir du laboratoire.",
      "Dans l'armoire fermée à clé.",
      "Au poste de sécurité.",
      "Près du registre à l'entrée.",
    ],
    correctIndex: 2,
    explanation: "The key must be left at the security desk, never in a drawer.",
  },

  // ── B1–B2 (Q11–30) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Entretien d'embauche",
    audioScript: "— Votre parcours m'intéresse, mais le poste demande de travailler un samedi sur deux. Est-ce compatible avec votre situation ? — Cela ne me pose pas de problème, à condition de connaître le planning un mois à l'avance, parce que je dois organiser la garde de ma fille.",
    question: "Quelle condition la candidate pose-t-elle ?",
    options: [
      "Ne pas travailler le samedi.",
      "Recevoir le planning un mois à l'avance.",
      "Obtenir une augmentation de salaire.",
      "Travailler uniquement à distance le samedi.",
    ],
    correctIndex: 1,
    explanation: "She accepts Saturday work provided she gets the schedule a month ahead for childcare.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Radio locale",
    audioScript: "La ville lance ce printemps un service de navettes gratuites entre les quartiers résidentiels et la zone industrielle. L'objectif n'est pas seulement écologique : plusieurs entreprises peinaient à recruter parce que leurs sites étaient inaccessibles sans voiture.",
    question: "Pourquoi la ville met-elle en place ces navettes ?",
    options: [
      "Pour réduire le nombre d'accidents de la route.",
      "Pour faciliter le recrutement d'entreprises mal desservies.",
      "Pour remplacer les lignes de bus existantes.",
      "Pour encourager les habitants à déménager.",
    ],
    correctIndex: 1,
    explanation: "Companies struggled to recruit because their sites were unreachable without a car.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Conversation entre collègues",
    audioScript: "— Tu as suivi la formation sur le nouveau logiciel ? — Oui, mais franchement, trois heures de théorie sans jamais toucher au programme, ça ne sert pas à grand-chose. J'ai appris davantage en une demi-heure avec Karine à mon poste.",
    question: "Que reproche-t-il à la formation ?",
    options: [
      "Elle était trop courte pour le sujet traité.",
      "Elle ne comportait aucune mise en pratique.",
      "Elle était animée par une personne peu compétente.",
      "Elle portait sur un logiciel déjà connu de tous.",
    ],
    correctIndex: 1,
    explanation: "Three hours of theory without ever touching the software — no hands-on practice.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Reportage",
    audioScript: "Depuis deux ans, cette épicerie vend uniquement des produits invendus récupérés chez les grossistes, à moitié prix. La clientèle a changé : au début, surtout des personnes en difficulté, aujourd'hui des familles de tous milieux qui viennent autant pour le prix que par refus du gaspillage.",
    question: "Comment la clientèle a-t-elle évolué ?",
    options: [
      "Elle est devenue plus âgée qu'au début.",
      "Elle s'est élargie à des familles de tous milieux.",
      "Elle s'est réduite aux personnes en difficulté.",
      "Elle vient désormais surtout des quartiers voisins.",
    ],
    correctIndex: 1,
    explanation: "It broadened from people in difficulty to families from all backgrounds.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Chez le conseiller",
    audioScript: "— Avec votre diplôme, vous pourriez viser un poste de technicien supérieur. — Mais je n'ai jamais travaillé au Canada. — Justement, commencez par un contrat de six mois. Ce n'est pas une régression, c'est ce qui rendra crédible tout le reste de votre parcours.",
    question: "Que conseille le conseiller ?",
    options: [
      "De reprendre des études avant de postuler.",
      "D'accepter un contrat court pour crédibiliser son parcours.",
      "De postuler directement à des postes de direction.",
      "De faire traduire officiellement son diplôme.",
    ],
    correctIndex: 1,
    explanation: "He advises a six-month contract to make the rest of her background credible.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Annonce d'entreprise",
    audioScript: "À partir du mois prochain, les réunions du lundi matin passeront de soixante à trente minutes. Nous demandons à chacun d'envoyer son point d'avancement par écrit la veille. La réunion sera réservée aux décisions et aux blocages, pas aux informations que tout le monde peut lire.",
    question: "Que doivent faire les employés avant la réunion ?",
    options: [
      "Préparer une présentation de trente minutes.",
      "Envoyer leur point d'avancement par écrit la veille.",
      "Signaler leur présence auprès de la direction.",
      "Proposer des sujets à inscrire à l'ordre du jour.",
    ],
    correctIndex: 1,
    explanation: "Each person sends a written progress update the day before.",
  },
  {
    id: 17,
    level: "B1",
    topic: "Interview",
    audioScript: "— Vous avez appris le français à quarante ans. Qu'est-ce qui a le plus aidé ? — Ni les manuels ni les applications. Ce sont les commerçants de mon quartier. Ils me corrigeaient sans jamais s'arrêter de me parler, et c'est exactement ce dont on a besoin.",
    question: "Qu'est-ce qui l'a le plus aidée à apprendre ?",
    options: [
      "Les manuels de grammaire consultés régulièrement.",
      "Les applications d'apprentissage sur téléphone.",
      "Les échanges quotidiens avec les commerçants.",
      "Les cours du soir suivis dans son quartier.",
    ],
    correctIndex: 2,
    explanation: "She credits the shopkeepers in her neighbourhood, not books or apps.",
  },
  {
    id: 18,
    level: "B1",
    topic: "Service client",
    audioScript: "— Mon abonnement a été prélevé deux fois ce mois-ci. — Je vois l'erreur, elle vient d'un changement de carte bancaire. Le remboursement partira aujourd'hui, mais comptez cinq jours ouvrables avant de le voir sur votre compte.",
    question: "Quand le client verra-t-il le remboursement ?",
    options: [
      "Le jour même de l'appel.",
      "Après environ cinq jours ouvrables.",
      "À la fin du mois en cours.",
      "Lors du prochain prélèvement.",
    ],
    correctIndex: 1,
    explanation: "The refund is sent today but takes about five working days to appear.",
  },
  {
    id: 19,
    level: "B1",
    topic: "Vie de quartier",
    audioScript: "Le conseil de quartier a rejeté le projet de terrasse permanente devant le café. Ce n'est pas le bruit qui a posé problème, mais la largeur du trottoir : il serait resté moins d'un mètre cinquante pour les piétons et les poussettes.",
    question: "Pourquoi le projet a-t-il été rejeté ?",
    options: [
      "À cause du bruit pour les riverains.",
      "À cause du passage trop étroit laissé aux piétons.",
      "À cause du coût des travaux prévus.",
      "À cause de l'opposition des commerçants voisins.",
    ],
    correctIndex: 1,
    explanation: "Less than a metre fifty would have remained for pedestrians and pushchairs.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Débat radiophonique",
    audioScript: "— Il faudrait imposer le français dans toutes les réunions internes de ces entreprises. — Attendez. Une obligation sans accompagnement produira l'inverse de ce que vous cherchez : les employés qui hésitent se tairont, et les décisions se prendront après la réunion, en anglais, dans le couloir. Formez d'abord, imposez ensuite.",
    question: "Quelle est la position du second intervenant ?",
    options: [
      "Il s'oppose à l'usage du français dans les réunions internes.",
      "Il juge qu'une obligation sans formation préalable serait contre-productive.",
      "Il propose de laisser chaque entreprise décider librement.",
      "Il estime que les décisions doivent se prendre en dehors des réunions.",
    ],
    correctIndex: 1,
    explanation: "He warns an unsupported obligation backfires and calls for training first, obligation after.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Conférence",
    audioScript: "On présente souvent le télétravail comme une conquête des salariés. Historiquement, c'est inexact. Les premières expériences, dans les années soixante-dix, répondaient à une crise pétrolière et visaient à réduire les déplacements. Le confort des employés n'était pas l'objectif, il en a été la conséquence involontaire.",
    question: "Que souligne l'intervenant sur l'origine du télétravail ?",
    options: [
      "Il est né d'une revendication des syndicats de salariés.",
      "Il répondait d'abord à une contrainte énergétique.",
      "Il a été rendu possible par les progrès de l'informatique.",
      "Il visait à réduire le coût des locaux d'entreprise.",
    ],
    correctIndex: 1,
    explanation: "The first experiments answered an oil crisis, aiming to cut travel; employee comfort was a side effect.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Entretien professionnel",
    audioScript: "— Vous dirigez une équipe de douze personnes réparties sur trois fuseaux horaires. Comment gérez-vous cela ? — En acceptant de perdre la réunion quotidienne. Nous écrivons beaucoup plus qu'avant. C'est plus lent au début, mais tout le monde finit par disposer de la même information, ce qui n'était jamais le cas à l'oral.",
    question: "Quel bénéfice tire-t-elle de ce fonctionnement écrit ?",
    options: [
      "Un gain de temps immédiat pour toute l'équipe.",
      "Une information réellement partagée par tous.",
      "Une réduction du nombre de réunions imposées.",
      "Une meilleure autonomie des membres les plus expérimentés.",
    ],
    correctIndex: 1,
    explanation: "Everyone ends up with the same information, which oral meetings never achieved.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Chronique économique",
    audioScript: "Le crédit d'impôt pour la rénovation énergétique a été massivement utilisé, ce que le gouvernement présente comme un succès. Les évaluations disponibles sont plus prudentes : une part importante des travaux subventionnés auraient été réalisés de toute façon. L'argent public a donc surtout financé des décisions déjà prises.",
    question: "Quelle réserve l'évaluation formule-t-elle ?",
    options: [
      "Le dispositif a été trop peu utilisé par les ménages.",
      "Les travaux financés étaient de mauvaise qualité.",
      "Beaucoup de travaux auraient eu lieu sans la subvention.",
      "Le budget alloué a été dépassé dès la première année.",
    ],
    correctIndex: 2,
    explanation: "A large share of the subsidised work would have happened anyway.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Table ronde",
    audioScript: "— Vos étudiants trichent-ils davantage avec ces outils ? — La question est mal posée. Ce que nous appelons tricher dépend de ce que nous évaluons. Tant que nous demandons un texte produit à la maison, l'outil fera le travail. Changeons l'exercice, et le problème disparaît de lui-même.",
    question: "Que propose l'intervenante ?",
    options: [
      "De renforcer la surveillance des travaux rendus à la maison.",
      "De modifier la nature des exercices demandés.",
      "D'interdire l'usage de ces outils aux étudiants.",
      "De sanctionner plus sévèrement les cas de fraude.",
    ],
    correctIndex: 1,
    explanation: "She argues changing the exercise makes the problem disappear on its own.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Reportage social",
    audioScript: "Ce programme d'accompagnement affiche un taux de retour à l'emploi de soixante-dix pour cent. Le chiffre impressionne, mais il faut préciser que les candidats sont sélectionnés à l'entrée sur leur motivation et leur mobilité. Comparé à un public équivalent non accompagné, l'écart réel tombe à douze points.",
    question: "Pourquoi le taux annoncé doit-il être nuancé ?",
    options: [
      "Parce qu'il porte sur un échantillon trop réduit.",
      "Parce que les participants sont sélectionnés à l'entrée.",
      "Parce qu'il inclut des emplois de très courte durée.",
      "Parce qu'il n'a pas été vérifié par un organisme externe.",
    ],
    correctIndex: 1,
    explanation: "Selection on motivation and mobility inflates the figure; the real gap is twelve points.",
  },
  {
    id: 26,
    level: "B2",
    topic: "Documentaire",
    audioScript: "Restaurer une forêt ne consiste pas à planter le maximum d'arbres. Sur les parcelles où l'on a planté dense et vite, la mortalité atteint parfois la moitié des sujets en trois ans. Les projets qui réussissent plantent moins, choisissent des essences locales et acceptent qu'une partie du terrain se régénère seule.",
    question: "Qu'est-ce qui caractérise les projets de restauration efficaces ?",
    options: [
      "Une densité de plantation élevée dès la première année.",
      "Le recours à des essences importées plus résistantes.",
      "Une plantation modérée laissant place à la régénération naturelle.",
      "Un arrosage régulier pendant les trois premières années.",
    ],
    correctIndex: 2,
    explanation: "Successful projects plant less, use local species, and let part of the land regenerate itself.",
  },
  {
    id: 27,
    level: "B2",
    topic: "Interview scientifique",
    audioScript: "— Le manque de sommeil rend-il vraiment moins performant ? — Oui, mais le plus inquiétant n'est pas la baisse de performance. C'est que les personnes privées de sommeil évaluent leur propre niveau comme normal. Elles perdent en même temps la capacité et le moyen de s'en rendre compte.",
    question: "Quel aspect le chercheur juge-t-il le plus préoccupant ?",
    options: [
      "La baisse mesurable des performances cognitives.",
      "L'incapacité des personnes à percevoir leur propre déficit.",
      "La difficulté à retrouver un rythme de sommeil normal.",
      "Les conséquences du manque de sommeil sur la santé.",
    ],
    correctIndex: 1,
    explanation: "Sleep-deprived people rate their own level as normal, losing the means to notice the deficit.",
  },
  {
    id: 28,
    level: "B2",
    topic: "Débat municipal",
    audioScript: "— Cette consultation citoyenne a coûté cher pour un taux de participation de quatre pour cent. — Le taux est faible, je vous l'accorde. Mais ceux qui se sont exprimés sont précisément les usagers quotidiens du quartier concerné. Une participation massive et diffuse nous aurait donné moins d'informations utiles.",
    question: "Comment la seconde personne défend-elle la consultation ?",
    options: [
      "Elle conteste le taux de participation avancé.",
      "Elle souligne la pertinence du profil des participants.",
      "Elle rappelle que le coût réel a été surestimé.",
      "Elle annonce une nouvelle consultation plus large.",
    ],
    correctIndex: 1,
    explanation: "She concedes the low rate but values that respondents were the neighbourhood's daily users.",
  },
  {
    id: 29,
    level: "B2",
    topic: "Chronique culturelle",
    audioScript: "Le succès des podcasts en français au Canada tient à un malentendu heureux. Les diffuseurs pensaient toucher un public jeune et urbain. Or les statistiques d'écoute montrent une audience largement composée de personnes de plus de cinquante ans, souvent en région, qui écoutent en voiture ou en travaillant.",
    question: "En quoi consiste le malentendu évoqué ?",
    options: [
      "Les podcasts sont écoutés par un public plus âgé que prévu.",
      "Les podcasts en français attirent surtout un public anglophone.",
      "Les diffuseurs avaient sous-estimé le nombre total d'auditeurs.",
      "Les auditeurs préfèrent des formats plus courts qu'annoncé.",
    ],
    correctIndex: 0,
    explanation: "Broadcasters expected a young urban audience; listeners are largely over fifty and often rural.",
  },
  {
    id: 30,
    level: "B2",
    topic: "Analyse du travail",
    audioScript: "On mesure la productivité d'un service d'assistance au nombre d'appels traités par heure. Ce choix a un effet immédiat : les conseillers apprennent à clore vite plutôt qu'à résoudre. Le même client rappelle trois fois, et chaque appel compte comme une réussite. L'indicateur ne mesure plus le travail, il le déforme.",
    question: "Quel effet l'indicateur produit-il selon l'intervenant ?",
    options: [
      "Il pousse les conseillers à clore les appels sans résoudre le problème.",
      "Il permet de repérer les conseillers les plus efficaces.",
      "Il augmente la charge de travail de chaque conseiller.",
      "Il décourage les clients de rappeler le service.",
    ],
    correctIndex: 0,
    explanation: "Advisers learn to close quickly rather than resolve, and repeat calls each count as successes.",
  },

  // ── C1–C2 (Q31–39) ─────────────────────────────────────────────
  {
    id: 31,
    level: "C1",
    topic: "Conférence universitaire",
    audioScript: "La notion d'insertion suppose un dedans et un dehors, une société stable dans laquelle il s'agirait d'entrer. Or les travaux récents décrivent des trajectoires bien plus instables, où les personnes déjà installées connaissent elles aussi des ruptures d'emploi et de logement. Parler d'insertion revient alors à mesurer les nouveaux venus à l'aune d'une stabilité que plus personne ne connaît.",
    question: "Quelle critique l'intervenant adresse-t-il à la notion d'insertion ?",
    options: [
      "Elle néglige les efforts fournis par les personnes concernées.",
      "Elle suppose une stabilité que la société n'offre plus à personne.",
      "Elle s'applique uniquement aux populations récemment arrivées.",
      "Elle repose sur des indicateurs statistiques peu fiables.",
    ],
    correctIndex: 1,
    explanation: "It measures newcomers against a stability that no longer exists for anyone.",
  },
  {
    id: 32,
    level: "C1",
    topic: "Séminaire de linguistique",
    audioScript: "L'accent n'est pas une propriété de celui qui parle, mais une relation entre lui et celui qui écoute. Chacun de nous a un accent ; nous cessons simplement de l'entendre lorsqu'il coïncide avec celui de notre entourage. Ce qu'on appelle parler sans accent désigne en réalité une position sociale, non une caractéristique phonétique.",
    question: "Que soutient l'intervenante à propos de l'accent ?",
    options: [
      "Il constitue un trait phonétique mesurable objectivement.",
      "Il correspond à une relation d'écoute et à une position sociale.",
      "Il tend à disparaître avec une exposition prolongée à la langue.",
      "Il révèle la région d'origine plus que le milieu social.",
    ],
    correctIndex: 1,
    explanation: "Accent is relational; 'speaking without an accent' names a social position, not a phonetic fact.",
  },
  {
    id: 33,
    level: "C1",
    topic: "Débat éthique",
    audioScript: "— Ces algorithmes de tri des candidatures seraient plus neutres que les recruteurs humains. — Ils sont surtout plus réguliers, ce qui n'est pas la même chose. Un recruteur partial se contredit, se ravise, laisse passer des exceptions. Un système partial applique le même biais des milliers de fois sans jamais douter. La régularité aggrave le préjudice au lieu de le corriger.",
    question: "Quel argument le second intervenant développe-t-il ?",
    options: [
      "Les algorithmes reproduisent exactement les biais humains connus.",
      "La constance d'un système biaisé amplifie le préjudice causé.",
      "Les recruteurs humains restent plus performants que les algorithmes.",
      "Les biais algorithmiques sont impossibles à détecter après coup.",
    ],
    correctIndex: 1,
    explanation: "Consistency, unlike human inconsistency, applies the same bias thousands of times, worsening harm.",
  },
  {
    id: 34,
    level: "C1",
    topic: "Cours de sociologie",
    audioScript: "Les enquêtes déclaratives sur les pratiques culturelles souffrent d'un biais bien identifié : les personnes interrogées surestiment les activités socialement valorisées et minorent les autres. Le nombre de livres lus augmente ainsi mystérieusement dès que l'enquêteur est présent. Ce n'est pas du mensonge, c'est un ajustement à ce que la situation d'enquête paraît attendre.",
    question: "Comment l'intervenant explique-t-il ce biais ?",
    options: [
      "Par une volonté délibérée de tromper l'enquêteur.",
      "Par un ajustement inconscient aux attentes perçues de l'enquête.",
      "Par une mauvaise formulation des questions posées.",
      "Par une difficulté à se souvenir précisément de ses pratiques.",
    ],
    correctIndex: 1,
    explanation: "It is not lying but adjustment to what the survey situation appears to expect.",
  },
  {
    id: 35,
    level: "C1",
    topic: "Exposé économique",
    audioScript: "Le salaire minimum illustre la difficulté de raisonner toutes choses égales par ailleurs. Une hausse peut détruire des emplois dans un marché concurrentiel, et en créer dans un marché où quelques employeurs fixent les salaires. Les études aboutissent à des résultats contradictoires non par incompétence, mais parce qu'elles observent des marchés dont la structure diffère.",
    question: "Pourquoi les études sur le salaire minimum divergent-elles ?",
    options: [
      "Parce que les méthodes statistiques employées sont défaillantes.",
      "Parce que la structure des marchés étudiés n'est pas la même.",
      "Parce que les périodes observées sont trop courtes.",
      "Parce que les chercheurs défendent des positions idéologiques.",
    ],
    correctIndex: 1,
    explanation: "Contradictory results follow from differing market structures, not incompetence.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Conférence de philosophie",
    audioScript: "Nous tenons l'oubli pour une défaillance de la mémoire. C'est l'inverse qu'il faudrait soutenir. Une mémoire qui conserverait tout serait inutilisable : se souvenir suppose de hiérarchiser, donc d'effacer. Les rares personnes incapables d'oublier décrivent une expérience insupportable, où chaque perception réveille indistinctement mille traces anciennes. L'oubli n'est pas le contraire de la mémoire, il en est la condition.",
    question: "Quelle thèse l'intervenant défend-il ?",
    options: [
      "L'oubli résulte d'un défaut d'attention au moment de l'encodage.",
      "L'oubli constitue la condition même du fonctionnement de la mémoire.",
      "L'oubli protège l'individu des souvenirs douloureux.",
      "L'oubli s'aggrave avec l'accumulation d'informations nouvelles.",
    ],
    correctIndex: 1,
    explanation: "Remembering requires hierarchy and therefore erasure: forgetting is memory's condition.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Séminaire d'anthropologie",
    audioScript: "Le don, tel que l'analysait Mauss, n'a rien de gratuit. Il ouvre une obligation de rendre, différée et jamais chiffrée, qui institue une relation durable. C'est précisément l'imprécision de la dette qui la rend féconde : rembourser exactement, ce serait clore l'échange et congédier l'autre. La générosité comptable est une forme polie de rupture.",
    question: "Pourquoi rendre l'exacte valeur d'un don pose-t-il problème ?",
    options: [
      "Cela révèle que le donateur attendait une contrepartie.",
      "Cela met fin à l'échange et donc à la relation.",
      "Cela oblige le donateur à offrir de nouveau.",
      "Cela dévalorise symboliquement le don initial.",
    ],
    correctIndex: 1,
    explanation: "Exact repayment closes the exchange and dismisses the other — a polite rupture.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Colloque sur les médias",
    audioScript: "La vérification des faits repose sur un présupposé fragile : que l'erreur naîtrait d'un déficit d'information. Les travaux en psychologie politique suggèrent autre chose. Une correction bien documentée modifie rarement l'opinion lorsqu'elle contredit une appartenance. L'individu ne défend pas une information, il défend le groupe auquel cette information l'attache. Corriger le fait sans toucher à l'appartenance revient à parler dans le vide.",
    question: "Pourquoi la vérification des faits est-elle souvent inefficace ?",
    options: [
      "Parce que les corrections circulent moins que les fausses informations.",
      "Parce que l'individu défend une appartenance et non une information.",
      "Parce que les sources des corrections sont jugées peu crédibles.",
      "Parce que le public ne consulte pas les articles de vérification.",
    ],
    correctIndex: 1,
    explanation: "People defend the group the claim attaches them to, so correcting the fact alone changes nothing.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Conférence sur la traduction",
    audioScript: "Traduire un texte littéraire suppose de renoncer, et de choisir ce à quoi l'on renonce. Le rythme, la densité sonore, le réseau des connotations ne survivent jamais tous ensemble au passage d'une langue à l'autre. Le traducteur médiocre croit tout conserver et perd l'essentiel ; le bon traducteur sacrifie délibérément, et rend au lecteur une œuvre qui respire encore.",
    question: "Qu'est-ce qui distingue le bon traducteur selon l'intervenant ?",
    options: [
      "Sa capacité à préserver l'ensemble des effets du texte source.",
      "Le caractère délibéré et assumé des pertes qu'il consent.",
      "Sa connaissance approfondie de la culture d'origine.",
      "Sa fidélité au rythme et à la sonorité de la langue de départ.",
    ],
    correctIndex: 1,
    explanation: "The good translator sacrifices deliberately, whereas the mediocre one believes nothing is lost.",
  },
];
