import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Master C — connectors, opinion frames, argument verbs, evaluation (TCF Q30-39, EE/EO). */
export const MASTER_C: LemmaRow[] = [
  ["Indeed", "en effet", "En effet, les résultats confirment la tendance observée l'an dernier."],
  ["In fact", "en fait", "En fait, la réforme touche plus de citoyens qu'on ne le pensait."],
  ["As a matter of fact", "en réalité", "En réalité, peu de familles ont profité de la mesure."],
  ["Thus", "ainsi", "Ainsi, la ville doit revoir son plan de transport."],
  ["For this reason", "pour cette raison", "Pour cette raison, le comité recommande un report."],
  ["That is why", "c'est pourquoi", "C'est pourquoi la consultation publique est indispensable."],
  ["On this basis", "sur cette base", "Sur cette base, nous pouvons formuler des recommandations."],
  ["In this regard", "à cet égard", "À cet égard, la loi manque de précision."],
  ["With regard to", "en ce qui concerne", "En ce qui concerne le logement, les besoins augmentent."],
  ["As regards", "quant à", "Quant au financement, aucune décision n'a été prise."],
  ["Regarding", "au sujet de", "Au sujet de la sécurité, des améliorations sont attendues."],
  ["Concerning", "concernant", "Concernant les délais, le maire reste optimiste."],
  ["Meanwhile", "pendant ce temps", "Pendant ce temps, les travaux se poursuivent dans le quartier."],
  ["In the meantime", "entre-temps", "Entre-temps, les citoyens attendent une réponse claire."],
  ["Subsequently", "par la suite", "Par la suite, plusieurs commerces ont fermé."],
  ["Thereafter", "dès lors", "Dès lors, les règles de stationnement ont changé."],
  ["Afterwards", "ensuite", "Ensuite, le conseil a voté la motion à la majorité."],
  ["Next", "à la suite de cela", "À la suite de cela, une enquête a été ouverte."],
  ["Then", "puis", "Puis, les parties ont négocié un accord provisoire."],
  ["Initially", "au départ", "Au départ, le projet semblait peu coûteux."],
  ["Ultimately", "en définitive", "En définitive, la priorité reste l'accès aux soins."],
  ["Eventually", "finalement", "Finalement, les deux camps ont trouvé un terrain d'entente."],
  ["At first", "d'abord", "D'abord, clarifions les objectifs de la réforme."],
  ["First and foremost", "avant tout", "Avant tout, il faut garantir la transparence."],
  ["To begin with", "pour commencer", "Pour commencer, examinons les chiffres disponibles."],
  ["Last but not least", "pour finir", "Pour finir, saluons l'engagement des bénévoles."],
  ["In a nutshell", "en un mot", "En un mot, la mesure est utile mais incomplète."],
  ["To sum up", "pour résumer", "Pour résumer, trois problèmes restent à régler."],
  ["On this point", "sur ce point", "Sur ce point, les avis des experts divergent."],
  ["On that note", "pour en revenir à", "Pour en revenir à la participation, elle a doublé."],
  ["That said", "cela dit", "Cela dit, les coûts demeurent élevés."],
  ["Having said that", "toutefois", "Toutefois, l'expérience pilote est encourageante."],
  ["Be that as it may", "quoi qu'il en soit", "Quoi qu'il en soit, le débat mérite d'être mené."],
  ["In any case", "dans tous les cas", "Dans tous les cas, les citoyens doivent être informés."],
  ["In any event", "en tout état de cause", "En tout état de cause, le service restera ouvert."],
  ["At any rate", "de toute façon", "De toute façon, il faudra revoir le calendrier."],
  ["After all", "après tout", "Après tout, la décision appartient aux élus."],
  ["Either way", "dans les deux cas", "Dans les deux cas, la qualité du service est en jeu."],
  ["Still", "pourtant", "Pourtant, plusieurs études contredisent cette affirmation."],
  ["Yet", "cependant", "Cependant, la participation reste insuffisante."],
  ["Nonetheless", "n'en demeure pas moins", "N'en demeure pas moins que la réforme est nécessaire."],
  ["Despite this", "malgré cela", "Malgré cela, le projet avance selon l'échéancier."],
  ["For all that", "malgré tout", "Malgré tout, l'opinion publique reste divisée."],
  ["Likewise", "de même", "De même, d'autres villes ont adopté la même approche."],
  ["Equally", "également", "Également, le coût de la vie pèse sur les familles."],
  ["In the same way", "de la même manière", "De la même manière, l'école encourage le dialogue."],
  ["By the same token", "dans le même ordre d'idées", "Dans le même ordre d'idées, la culture mérite un soutien."],
  ["In turn", "à son tour", "À son tour, le gouvernement a annoncé des mesures."],
  ["On the whole", "dans l'ensemble", "Dans l'ensemble, les services se sont améliorés."],
  ["Overall", "globalement", "Globalement, la fréquentation du parc a augmenté."],
  ["As a whole", "dans son ensemble", "Dans son ensemble, le programme répond aux besoins."],
  ["Partly", "en partie", "En partie, le succès tient à la mobilisation locale."],
  ["Namely", "à savoir", "Deux secteurs sont visés, à savoir la santé et l'éducation."],
  ["Not least", "entre autres", "Entre autres, le transport collectif doit être renforcé."],
  ["Provided that", "à condition que", "Le permis sera accordé à condition que les normes soient respectées."],
  ["On condition that", "pourvu que", "Pourvu que les règles soient claires, le projet peut avancer."],
  ["So that", "de sorte que", "La loi a été modifiée de sorte que tous puissent comprendre leurs droits."],
  ["So as to", "afin de", "Le guide a été rédigé afin de simplifier les démarches."],
  ["In order that", "afin que", "Des séances sont prévues afin que chacun puisse s'exprimer."],
  ["Seeing that", "étant donné que", "Étant donné que le budget est limité, il faut prioriser."],
  ["Given that", "vu que", "Vu que la demande augmente, la ville doit réagir."],
  ["Now that", "maintenant que", "Maintenant que les données sont publiées, le débat peut commencer."],
  ["Once", "une fois que", "Une fois que l'enquête sera terminée, nous publierons le rapport."],
  ["Before", "avant que", "Avant que la décision soit prise, consultez les résidents."],
  ["Since (because)", "puisque", "Puisque les besoins sont urgents, agissons sans tarder."],
  ["Because", "car", "La mesure est contestée, car elle touche les plus modestes."],
  ["If only", "si seulement", "Si seulement la concertation avait commencé plus tôt."],
  ["Whether or not", "que ce soit ou non", "Que ce soit ou non retenu, le débat aura eu lieu."],
  ["No matter what", "quoi qu'il arrive", "Quoi qu'il arrive, la sécurité des usagers prime."],
  ["Insofar as possible", "dans la mesure du possible", "Dans la mesure du possible, réduisons les délais d'attente."],
  ["To that end", "à cette fin", "À cette fin, un comité citoyen a été créé."],
  ["For that matter", "d'ailleurs", "D'ailleurs, la question du bruit reste ouverte."],
  ["By contrast", "à l'opposé", "À l'opposé, la banlieue connaît une forte croissance."],
  ["By comparison", "comparativement", "Comparativement, les tarifs restent abordables."],
  ["Relative to", "par rapport à", "Par rapport à l'an dernier, la pollution a diminué."],
  ["Compared with", "comparé à", "Comparé à d'autres régions, notre taux de chômage est bas."],
  ["Aside from", "mis à part", "Mis à part le coût, le projet présente des avantages."],
  ["Apart from", "en dehors de", "En dehors de ce détail, l'accord semble équilibré."],
  ["Instead of", "au lieu de", "Au lieu de fermer le centre, la ville pourrait le moderniser."],
  ["Rather than", "plutôt que", "Plutôt que d'imposer une solution, écoutons les citoyens."],
  ["As opposed to", "contrairement à", "Contrairement à ce qu'on affirme, le service s'est amélioré."],
  ["Unlike previously", "contrairement à avant", "Contrairement à avant, les délais sont respectés."],
  ["Much like", "tout comme", "Tout comme l'an dernier, l'événement attire des milliers de visiteurs."],
  ["Just as", "tout comme", "Tout comme ses voisins, le quartier manque de logements."],
  ["As well as", "ainsi que", "La réforme vise la santé ainsi que l'éducation."],
  ["Both... and", "à la fois... et", "Le plan répond à la fois aux besoins économiques et sociaux."],
  ["Either... or", "soit... soit", "Soit on reporte le projet, soit on augmente le budget."],
  ["Neither... nor", "ni... ni", "Ni la ville ni la province n'ont confirmé la date."],
  ["Simply put", "en termes simples", "En termes simples, le budget ne suit pas la demande."],
  ["As I see it", "comme je le vois", "Comme je le vois, la concertation doit précéder la décision."],
  ["If you ask me", "si vous me demandez mon avis", "Si vous me demandez mon avis, il faut agir maintenant."],
  ["To my mind", "à mon sens", "À mon sens, l'équilibre proposé est raisonnable."],
  ["I hold the view that", "je considère que", "Je considère que la transparence renforce la confiance."],
  ["I maintain that", "je maintiens que", "Je maintiens que le délai annoncé est réaliste."],
  ["I submit that", "je soumets que", "Je soumets que la mesure mérite un essai pilote."],
  ["I would argue that", "j'avancerais que", "J'avancerais que le coût social est sous-estimé."],
  ["It strikes me that", "il me frappe que", "Il me frappe que si peu de jeunes participent."],
  ["One might say that", "on pourrait dire que", "On pourrait dire que le débat manque de nuance."],
  ["One could argue that", "on pourrait soutenir que", "On pourrait soutenir que l'alternative est plus juste."],
  ["It is often said that", "on dit souvent que", "On dit souvent que la technologie résout tout."],
  ["It is widely held that", "on estime généralement que", "On estime généralement que l'éducation est la clé."],
  ["There is reason to believe", "il y a lieu de croire", "Il y a lieu de croire que la situation s'améliorera."],
  ["It is fair to say", "il est juste de dire", "Il est juste de dire que les efforts sont visibles."],
  ["It would be unfair to say", "il serait injuste de dire", "Il serait injuste de dire que rien n'a changé."],
  ["Far from it", "loin de là", "Loin de là : plusieurs problèmes persistent."],
  ["Not necessarily", "pas nécessairement", "Une hausse des taxes n'entraîne pas nécessairement de meilleurs services."],
  ["By no means", "nullement", "Le rapport n'est nullement définitif."],
  ["Under no circumstances", "en aucun cas", "En aucun cas la sécurité ne doit être compromise."],
  ["I wholeheartedly support", "je soutiens sans réserve", "Je soutiens sans réserve la proposition du comité."],
  ["I strongly disagree", "je suis en profond désaccord", "Je suis en profond désaccord avec cette interprétation."],
  ["I remain unconvinced", "je ne suis toujours pas convaincu", "Je ne suis toujours pas convaincu par ces arguments."],
  ["I am skeptical about", "je suis sceptique quant à", "Je suis sceptique quant à l'efficacité de la mesure."],
  ["I am in two minds", "je suis partagé", "Je suis partagé entre les avantages et les risques."],
  ["I am torn", "je suis déchiré", "Je suis déchiré entre la rapidité et la prudence."],
  ["The truth is", "la vérité, c'est que", "La vérité, c'est que le budget est très serré."],
  ["The fact remains that", "il n'en reste pas moins que", "Il n'en reste pas moins que la demande augmente."],
  ["It bears emphasizing that", "il importe de souligner que", "Il importe de souligner que les familles sont concernées."],
  ["What is at stake", "ce qui est en jeu", "Ce qui est en jeu, c'est l'accès à l'eau potable."],
  ["The crux of the matter", "le cœur du problème", "Le cœur du problème, c'est le manque de personnel."],
  ["The issue boils down to", "la question se résume à", "La question se résume à un choix de priorités."],
  ["Mind you", "notez bien", "Notez bien que le règlement s'applique dès lundi."],
  ["Make no mistake", "ne vous y trompez pas", "Ne vous y trompez pas : la décision est politique."],
  ["Let me be clear", "je tiens à être clair", "Je tiens à être clair : nous refusons toute fermeture."],
  ["I wish to stress", "je tiens à insister", "Je tiens à insister sur le rôle des écoles."],
  ["I would like to point out", "je voudrais signaler", "Je voudrais signaler une erreur dans le tableau."],
  ["We must not lose sight of", "nous ne devons pas perdre de vue", "Nous ne devons pas perdre de vue les personnes âgées."],
  ["It is high time", "il est grand temps", "Il est grand temps d'investir dans les transports."],
  ["There is little doubt that", "il y a peu de doute que", "Il y a peu de doute que la pollution augmente."],
  ["Speaking personally", "à titre personnel", "À titre personnel, je préfère la solution locale."],
  ["Speaking for myself", "pour ma part", "Pour ma part, je voterai en faveur de la motion."],
  ["From our perspective", "de notre point de vue", "De notre point de vue, le délai est trop court."],
  ["As far as I am concerned", "pour ce qui me concerne", "Pour ce qui me concerne, l'accord est acceptable."],
  ["As far as we know", "pour autant que nous sachions", "Pour autant que nous sachions, aucun incident n'est signalé."],
  ["So far as I can tell", "autant que je puisse en juger", "Autant que je puisse en juger, les chiffres sont fiables."],
  ["It seems fair to assume", "il semble raisonnable de supposer", "Il semble raisonnable de supposer une hausse modérée."],
  ["I take the view that", "j'estime que", "J'estime que la concertation a été insuffisante."],
  ["We are led to believe", "on nous laisse croire", "On nous laisse croire que tout est réglé."],
  ["I dare say", "j'oserais dire", "J'oserais dire que l'opinion a évolué."],
  ["I would go so far as to say", "j'irais jusqu'à dire", "J'irais jusqu'à dire que la réforme est urgente."],
  ["It goes without saying that", "il va de soi que", "Il va de soi que la sécurité est non négociable."],
  ["Need I remind you that", "ai-je besoin de rappeler que", "Ai-je besoin de rappeler que le délai est légal?"],
  ["Let there be no doubt", "qu'il n'y ait aucun doute", "Qu'il n'y ait aucun doute : nous soutenons la mesure."],
  ["I am not alone in thinking", "je ne suis pas le seul à penser", "Je ne suis pas le seul à penser que le tarif est élevé."],
  ["Many would agree that", "beaucoup conviendront que", "Beaucoup conviendront que le service doit s'améliorer."],
  ["Few would deny that", "peu nieront que", "Peu nieront que le climat influence l'agriculture."],
  ["It is no secret that", "ce n'est un secret pour personne que", "Ce n'est un secret pour personne que les loyers augmentent."],
  ["It is hardly surprising that", "il n'est guère surprenant que", "Il n'est guère surprenant que les citoyens réagissent."],
  ["It is hardly an exaggeration to say", "ce n'est pas exagérer que de dire", "Ce n'est pas exagérer que de dire que la situation est critique."],
  ["To be honest", "pour être honnête", "Pour être honnête, je ne partage pas cette analyse."],
  ["Frankly speaking", "franchement", "Franchement, le document manque de clarté."],
  ["Honestly", "honnêtement", "Honnêtement, nous avons besoin de plus de temps."],
  ["Personally", "personnellement", "Personnellement, je préfère une approche graduelle."],
  ["Officially", "officiellement", "Officiellement, le projet est toujours à l'étude."],
  ["Unofficially", "officieusement", "Officieusement, plusieurs élus sont favorables."],
  ["Apparently", "apparemment", "Apparemment, la réunion a été reportée."],
  ["Evidently", "évidemment", "Évidemment, il faut respecter le budget."],
  ["Presumably", "probablement", "Probablement, le vote aura lieu en juin."],
  ["Supposedly", "soi-disant", "Soi-disant, le service est gratuit pour tous."],
  ["Allegedly", "prétendument", "Prétendument, les coûts ont été maîtrisés."],
  ["Arguably", "on peut soutenir que", "On peut soutenir que la mesure est disproportionnée."],
  ["Understandably", "on comprend que", "On comprend que les parents s'inquiètent."],
  ["Regrettably", "malheureusement", "Malheureusement, plusieurs séances ont été annulées."],
  ["Fortunately", "heureusement", "Heureusement, aucun blessé n'est à déplorer."],
  ["Ideally", "idéalement", "Idéalement, la concertation précéderait toute décision."],
  ["Realistically", "réalistement", "Réalistement, il faudra plusieurs années."],
  ["Hypothetically", "hypothétiquement", "Hypothétiquement, que se passerait-il sans subvention?"],
  ["Theoretically speaking", "en théorie", "En théorie, la loi protège les locataires."],
  ["Practically speaking", "en pratique", "En pratique, les délais sont souvent longs."],
  ["In principle", "en principe", "En principe, je suis d'accord avec l'objectif."],
  ["In reality", "dans la réalité", "Dans la réalité, peu de places sont disponibles."],
  ["For my part", "de mon côté", "De mon côté, je propose un report de deux mois."],
  ["On my part", "pour ce qui est de moi", "Pour ce qui est de moi, je reste ouvert au dialogue."],
  ["On our part", "de notre côté", "De notre côté, nous avons transmis toutes les données."],
  ["As for me", "quant à moi", "Quant à moi, je privilégie la solution la plus simple."],
  ["As for us", "quant à nous", "Quant à nous, nous attendons une réponse écrite."],
  ["This is how", "voici comment", "Voici comment nous pouvons réduire les déchets."],
  ["That is how", "c'est ainsi que", "C'est ainsi que la confiance se reconstruit."],
  ["To defend", "défendre", "Elle défend une réforme plus progressive du système."],
  ["To denounce", "dénoncer", "Les associations dénoncent le manque de consultation."],
  ["To deplore", "déplorer", "Le maire déplore la lenteur des travaux."],
  ["To invoke", "invoquer", "L'avocat invoque un précédent juridique."],
  ["To cite", "citer", "Le rapport cite plusieurs études récentes."],
  ["To quote", "citer", "Il cite un passage du discours du premier ministre."],
  ["To refer to", "se référer à", "Le texte se réfère à une loi de 2019."],
  ["To allude to", "faire allusion à", "L'orateur fait allusion aux difficultés économiques."],
  ["To formulate", "formuler", "Il faut formuler des objectifs mesurables."],
  ["To articulate", "articuler", "Elle articule clairement sa position dans le débat."],
  ["To spell out", "préciser", "Le ministère doit préciser les critères d'éligibilité."],
  ["To elaborate on", "développer", "Pouvez-vous développer votre argument sur le transport?"],
  ["To expand on", "approfondir", "L'article approfondit la question du logement."],
  ["To point out", "faire remarquer", "Je fais remarquer que les chiffres datent de 2022."],
  ["To note", "noter", "Notons que la participation varie selon les quartiers."],
  ["To remark", "remarquer", "Plusieurs citoyens remarquent une hausse des taxes."],
  ["To remind", "rappeler", "Je rappelle que le délai légal est de trente jours."],
  ["To warn", "avertir", "Les experts avertissent contre une généralisation hâtive."],
  ["To urge", "exhorter", "Le comité exhorte la ville à agir rapidement."],
  ["To call for", "réclamer", "Les parents réclament plus de places en garderie."],
  ["To appeal for", "lancer un appel pour", "L'organisme lance un appel pour la solidarité."],
  ["To accuse", "accuser", "L'opposition accuse le gouvernement de manquer de transparence."],
  ["To blame", "blâmer", "Il ne sert à rien de blâmer uniquement les élus."],
  ["To hold responsible", "tenir responsable", "On ne peut pas tenir une seule personne responsable."],
  ["To commend", "féliciter", "Le journal félicite l'initiative des jeunes."],
  ["To endorse publicly", "approuver publiquement", "Trois partis approuvent publiquement la motion."],
  ["To uphold", "maintenir", "Le tribunal maintient la décision de première instance."],
  ["To dispute", "contester", "Les riverains contestent la légalité du projet."],
  ["To contest", "contester", "Plusieurs candidats contestent les résultats du vote."],
  ["To retort", "répliquer", "Elle réplique que les données sont incomplètes."],
  ["To counter", "contre-argumenter", "Il contre-argumente en citant un rapport indépendant."],
  ["To assess", "évaluer", "Une commission évalue l'impact de la réforme."],
  ["To weigh up", "peser", "Il faut peser les avantages et les inconvénients."],
  ["To take into account", "tenir compte de", "Tenez compte de l'avis des résidents."],
  ["To overlook", "négliger", "Ne négligez pas l'effet sur les petits commerces."],
  ["To ignore", "ignorer", "Ignorer les avertissements serait imprudent."],
  ["To disregard", "ne pas tenir compte de", "Ne pas tenir compte des données fausse l'analyse."],
  ["To bear in mind", "garder à l'esprit", "Gardez à l'esprit que le budget est limité."],
  ["To keep in mind", "garder en tête", "Gardez en tête les besoins des familles."],
  ["To adopt", "adopter", "Le conseil adopte un nouveau règlement de zonage."],
  ["To embrace", "adopter", "La ville adopte une politique zéro déchet."],
  ["To espouse", "défendre", "Il défend une vision inclusive de l'intégration."],
  ["To renounce", "renoncer à", "L'entreprise renonce à son projet d'expansion."],
  ["To violate", "enfreindre", "La décision pourrait enfreindre le règlement municipal."],
  ["To breach", "violer", "Violer le contrat entraîne des sanctions."],
  ["To comply with", "se conformer à", "Les commerces doivent se conformer aux normes."],
  ["To abide by", "respecter", "Tous doivent respecter les règles de sécurité."],
  ["To trigger", "déclencher", "L'incident a déclenché un large débat public."],
  ["To spark", "susciter", "La proposition suscite de vives réactions."],
  ["To fuel", "alimenter", "Les rumeurs alimentent la méfiance des citoyens."],
  ["To bolster", "renforcer", "Le sondage renforce la position du comité."],
  ["To shore up", "consolider", "Des investissements visent à consolider le réseau."],
  ["To underpin", "sous-tendre", "Des valeurs communes sous-tendent l'accord."],
  ["To hamper", "entraver", "Le manque de personnel entrave le service."],
  ["To hinder", "gêner", "Les travaux gênent l'accès au centre-ville."],
  ["To curb", "freiner", "La ville veut freiner la hausse des loyers."],
  ["To restrain", "contenir", "Il faut contenir la hausse des prix."],
  ["To foster", "favoriser", "L'école favorise l'esprit critique chez les élèves."],
  ["To nurture", "cultiver", "Cultiver le dialogue évite les malentendus."],
  ["To stem from", "provenir de", "Le retard provient d'une panne informatique."],
  ["To derive from", "découler de", "Plusieurs problèmes découlent du vieillissement."],
  ["To arise from", "naître de", "Le conflit naît d'un manque de communication."],
  ["To give rise to", "donner lieu à", "La réforme donne lieu à de nombreuses questions."],
  ["To entail", "entraîner", "La fermeture entraîne des pertes d'emploi."],
  ["To presuppose", "présupposer", "Cette solution présuppose une volonté politique forte."],
  ["To amount to", "équivaloir à", "Le refus équivaut à un rejet du compromis."],
  ["To hinge on", "dépendre de", "Le succès dépend de la mobilisation citoyenne."],
  ["To revolve around", "tourner autour de", "Le débat tourne autour du coût de la vie."],
  ["To center on", "porter sur", "L'enquête porte sur la qualité de l'eau."],
  ["To dwell on", "s'attarder sur", "Ne vous attardez pas sur des détails secondaires."],
  ["To touch on", "aborder", "Le discours aborde brièvement la question climatique."],
  ["To broach", "aborder", "Il ose aborder un sujet sensible en séance."],
  ["To raise awareness", "sensibiliser", "La campagne sensibilise le public au recyclage."],
  ["To alert", "alerter", "Les médecins alertent sur la pénurie de personnel."],
  ["To disclose", "divulguer", "La ville divulgue enfin le coût réel du projet."],
  ["To expose", "dénoncer", "Le journal dénonce des pratiques discriminatoires."],
  ["To uncover", "mettre au jour", "L'enquête met au jour des irrégularités."],
  ["To shed light on", "éclairer", "Ce rapport éclaire les causes du retard."],
  ["To cast doubt on", "jeter le doute sur", "Les nouvelles données jettent le doute sur l'étude."],
  ["To bear witness to", "témoigner de", "Les statistiques témoignent d'une reprise lente."],
  ["To attest", "attester", "Plusieurs témoins attestent de la qualité du service."],
  ["To confirm", "confirmer", "Le ministre confirme le calendrier annoncé."],
  ["To contradict", "contredire", "Les faits contredisent l'affirmation du porte-parole."],
  ["To clash with", "entrer en conflit avec", "Le projet entre en conflit avec le plan local."],
  ["To align with", "concorder avec", "La mesure concorde avec les objectifs climatiques."],
  ["To coincide with", "coïncider avec", "La réunion coïncide avec la fête nationale."],
  ["To differ from", "différer de", "Cette approche diffère de celle des voisins."],
  ["To diverge from", "diverger de", "Son analyse diverge de la majorité des experts."],
  ["To depart from", "s'écarter de", "Le texte s'écarte de la tradition législative."],
  ["To resonate with", "résonner auprès de", "Le message résonne auprès des jeunes électeurs."],
  ["To echo", "faire écho à", "Ses propos font écho aux préoccupations des parents."],
  ["To reflect", "refléter", "Le vote reflète une profonde division sociale."],
  ["To typify", "typifier", "Ce cas typifie les difficultés du secteur."],
  ["To exemplify", "illustrer", "Cet exemple illustre bien le problème du bruit."],
  ["To embody", "incarner", "Elle incarne l'engagement citoyen dans son quartier."],
  ["To characterize", "caractériser", "Qu'est-ce qui caractérise cette politique?"],
  ["To portray", "dépeindre", "Le film dépeint la vie dans un village rural."],
  ["To depict", "représenter", "Le graphique représente l'évolution sur dix ans."],
  ["To dismiss", "rejeter", "Le comité rejette l'idée d'une taxe supplémentaire."],
  ["To shrug off criticism", "ne pas tenir compte des critiques", "Il ne tient pas compte des critiques répétées."],
  ["Compelling", "convaincant", "Un argument convaincant repose sur des preuves solides."],
  ["Persuasive", "persuasif", "Son discours persuasif a changé plusieurs opinions."],
  ["Unconvincing", "peu convaincant", "Le rapport reste peu convaincant sur le financement."],
  ["Sound", "solide", "C'est une analyse solide, mais incomplète."],
  ["Flawed", "lacunaire", "Une méthode lacunaire fausse les conclusions."],
  ["Well-founded", "bien fondé", "C'est un reproche bien fondé, selon le comité."],
  ["Ill-founded", "mal fondé", "L'accusation est mal fondée et doit être retirée."],
  ["Well-argued", "bien argumenté", "L'éditorial est bien argumenté et accessible."],
  ["Coherent", "cohérent", "Le plan proposé est cohérent avec les objectifs."],
  ["Incoherent", "incohérent", "Un message incohérent trouble les citoyens."],
  ["Consistent", "constant", "Un service constant rassure les usagers."],
  ["Inconsistent", "contradictoire", "Des chiffres contradictoires affaiblissent le dossier."],
  ["Irrelevant", "sans rapport", "Cette remarque est sans rapport avec le sujet."],
  ["Appropriate", "approprié", "Un délai approprié laisse le temps de consulter."],
  ["Inappropriate", "inapproprié", "Un ton inapproprié nuit au débat public."],
  ["Adequate", "adéquat", "Un budget adéquat est indispensable pour réussir."],
  ["Inadequate", "inadéquat", "La réponse est inadéquate face à l'ampleur du problème."],
  ["Disappointing", "décevant", "Le taux de participation est décevant cette année."],
  ["Encouraging", "encourageant", "Les premiers résultats sont encourageants."],
  ["Worrying", "inquiétant", "La hausse des prix est inquiétante pour les locataires."],
  ["Alarming", "alarmant", "La situation sanitaire est alarmante dans certains quartiers."],
  ["Reassuring", "rassurant", "Le message du maire est rassurant pour les parents."],
  ["Promising", "prometteur", "Le projet pilote est prometteur, mais fragile."],
  ["Remarkable", "remarquable", "C'est un effort remarquable de la part des bénévoles."],
  ["Noteworthy", "digne d'attention", "Un détail digne d'attention figure page douze."],
  ["Significant", "significatif", "Une hausse significative touche les frais de scolarité."],
  ["Insignificant", "négligeable", "L'écart reste négligeable à l'échelle nationale."],
  ["Substantial", "substantiel", "Un investissement substantiel est annoncé."],
  ["Negligible", "infime", "L'impact sur les tarifs est infime pour l'instant."],
  ["Moderate", "modéré", "Une hausse modérée était attendue par les experts."],
  ["Excessive", "excessif", "Le bruit nocturne est excessif selon les voisins."],
  ["Balanced", "équilibré", "Le compromis proposé semble équilibré."],
  ["One-sided", "partial", "Un débat partial n'avance pas la réflexion."],
  ["Biased", "biaisé", "Un échantillon biaisé fausse le sondage."],
  ["Impartial", "impartial", "Un médiateur impartial facilite la négociation."],
  ["Objective", "objectif", "Un compte rendu objectif aide les citoyens."],
  ["Subjective", "subjectif", "Le jugement reste subjectif sans données."],
  ["Neutral", "neutre", "Un ton neutre convient mieux à la consultation."],
  ["Justified", "justifié", "Le report est justifié par les conditions météo."],
  ["Unjustified", "injustifié", "Une telle hausse serait injustifiée."],
  ["Reasonable", "raisonnable", "Une demande raisonnable mérite une réponse rapide."],
  ["Unreasonable", "déraisonnable", "Exiger une réponse en vingt-quatre heures est déraisonnable."],
  ["Sensible", "sensé", "C'est une mesure sensée à moyen terme."],
  ["Absurd", "absurde", "L'idée d'annuler toute aide est absurde."],
  ["Pragmatic", "pragmatique", "Une approche pragmatique évite l'impasse."],
  ["Idealistic", "idéaliste", "Un discours idéaliste sans financement convainc peu."],
  ["Feasible", "réalisable", "Le calendrier proposé est réalisable."],
  ["Unworkable", "irréalisable", "Le plan est irréalisable avec le budget actuel."],
  ["Workable", "viable", "Une solution viable existe si chacun cède un peu."],
  ["Timely", "opportun", "Un rappel opportun évite les erreurs de procédure."],
  ["Untimely", "inopportun", "Une annonce inopportune alimente la polémique."],
  ["Urgent", "urgent", "Un besoin urgent de logements se fait sentir."],
  ["Pressing", "pressant", "La question du climat est pressante."],
  ["Crucial", "crucial", "La concertation est cruciale pour la réussite."],
  ["Vital", "vital", "L'accès à l'eau est vital pour la communauté."],
  ["Essential", "essentiel", "Un transport fiable est essentiel aux banlieusards."],
  ["Superfluous", "superflu", "Ce détail est superflu dans un résumé court."],
  ["Indispensable", "indispensable", "La participation citoyenne est indispensable."],
  ["Optional", "facultatif", "Le module de formation est facultatif."],
  ["Mandatory", "obligatoire", "Le port du casque est obligatoire sur le chantier."],
  ["Just", "juste", "Une répartition juste des coûts est attendue."],
  ["Unjust", "injuste", "Une sanction injuste provoque la colère."],
  ["Equitable", "équitable", "Un accès équitable aux soins reste un défi."],
  ["Inequitable", "inéquitable", "Une tarification inéquitable frappe les familles."],
  ["Proportionate", "proportionné", "Une réponse proportionnée calme le débat."],
  ["Disproportionate", "disproportionné", "Une amende disproportionnée est contestée."],
  ["Measured", "mesuré", "Un ton mesuré favorise le dialogue."],
  ["Restrained", "retenu", "Un commentaire retenu évite l'escalade."],
  ["Hasty", "précipité", "Un vote précipité manque de légitimité."],
  ["Rash", "téméraire", "Une promesse téméraire engage mal la ville."],
  ["Thoughtful", "réfléchi", "Un plan réfléchi tient compte des contraintes."],
  ["Oversimplified", "simpliste", "Une explication simpliste masque la complexité."],
  ["Reductionist", "réductionniste", "Une lecture réductionniste du problème est risquée."],
];
