import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 8 — Compréhension orale. Theme: family, early childhood and social services in Canada.
 *
 * `audioScript` is rendered by Edge TTS, so each script is written to be read
 * aloud cleanly: no bullet points, numbers spelled where ambiguous, and
 * dialogue turns separated by em dashes.
 */
export const TCF_LISTENING_P8: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "À la garderie",
    audioScript: "— Bonjour, je voudrais visiter la garderie pour mon fils de deux ans. — Les visites sont le mardi à dix heures. Apportez son certificat de vaccination. — Merci, je note.",
    question: "Quand peut-on visiter la garderie ?",
    options: ["Le lundi matin.", "Le mardi à dix heures.", "Le vendredi après-midi.", "N'importe quel jour."],
    correctIndex: 1,
    explanation: "Visits are on Tuesday at ten o'clock.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Annonce scolaire",
    audioScript: "Attention parents : la sortie école demain est annulée à cause de la tempête. Les élèves restent en classe jusqu'à quinze heures. Le bus scolaire circule normalement à cette heure.",
    question: "Qu'est-ce qui est annulé ?",
    options: ["Les cours de la matinée.", "La sortie école de demain.", "Le bus scolaire.", "La cantine."],
    correctIndex: 1,
    explanation: "Tomorrow's school outing is cancelled due to the storm.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Au centre communautaire",
    audioScript: "— Où est le cours de yoga pour femmes enceintes ? — Salle trois, au fond du couloir. Ça commence à dix-huit heures. — Merci beaucoup.",
    question: "Où se déroule le cours ?",
    options: ["Salle un.", "Salle trois.", "Dans le gymnase.", "À l'extérieur."],
    correctIndex: 1,
    explanation: "The prenatal yoga class is in room three.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Message radio",
    audioScript: "Rappel pour les familles : la clinique de vaccination gratuite pour les enfants aura lieu samedi de neuf heures à treize heures au centre sportif du quartier Est.",
    question: "Quand a lieu la clinique ?",
    options: ["Vendredi soir.", "Samedi matin et midi.", "Dimanche toute la journée.", "Lundi prochain."],
    correctIndex: 1,
    explanation: "Saturday from nine to one at the East neighbourhood sports centre.",
  },
  {
    id: 5,
    level: "A2",
    topic: "Ressources humaines",
    audioScript: "— Je voudrais prendre mon congé parental en octobre. — Avez-vous rempli le formulaire sur le portail ? — Pas encore. — Sans formulaire trois semaines avant le départ, nous ne pouvons pas garantir le remplacement.",
    question: "Que doit faire l'employée ?",
    options: [
      "Demander un congé sans solde seulement.",
      "Remplir le formulaire sur le portail à l'avance.",
      "Attendre la naissance pour prévenir l'employeur.",
      "Payer des frais de remplacement.",
    ],
    correctIndex: 1,
    explanation: "She must submit the portal form three weeks before leave.",
  },
  {
    id: 6,
    level: "A2",
    topic: "École primaire",
    audioScript: "— Bonjour, j'inscris ma fille en première année. — Très bien. Apportez son certificat de naissance, une preuve d'adresse et votre carte d'assurance maladie. — Et si nous venons d'arriver au Canada ? — Ajoutez aussi les documents d'immigration de l'enfant.",
    question: "Que faut-il en plus pour une famille récemment arrivée ?",
    options: [
      "Un certificat de français.",
      "Les documents d'immigration de l'enfant.",
      "Une lettre de l'ancienne école seulement.",
      "Un dépôt de cinq cents dollars.",
    ],
    correctIndex: 1,
    explanation: "Newcomers must also bring the child's immigration documents.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Maison des aînés",
    audioScript: "Le club des jeudis propose un déjeuner commun et des jeux de cartes de dix heures à midi. L'inscription est gratuite, mais il faut réserver par téléphone la veille, car les places sont limitées à vingt personnes.",
    question: "Que faut-il faire pour participer ?",
    options: [
      "Payer dix dollars sur place.",
      "Réserver par téléphone la veille.",
      "Apporter son propre repas obligatoirement.",
      "Arriver sans réservation.",
    ],
    correctIndex: 1,
    explanation: "Free registration by phone the day before is required.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Liste d'attente garderie",
    audioScript: "— Où en est ma demande de place en CPE ? — Vous êtes numéro quarante-sept sur la liste. Nous vous écrirons par courriel quand une place se libère. — Puis-je accélérer le processus ? — Non, l'ordre suit la date d'inscription complète.",
    question: "Comment la personne sera-t-elle contactée ?",
    options: [
      "Par un appel téléphonique chaque semaine.",
      "Par courriel lorsqu'une place se libère.",
      "Par lettre recommandée uniquement.",
      "En se présentant sur place chaque matin.",
    ],
    correctIndex: 1,
    explanation: "They will be emailed when a spot opens.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Aide à domicile",
    audioScript: "— Mon père a besoin d'aide pour les repas. — Commencez par l'évaluation téléphonique. Ensuite une infirmière visitera le domicile. Comptez six à huit semaines avant le début des services. — Et les coûts ? — Une partie peut être couverte selon le revenu familial.",
    question: "Combien de temps avant le début des services ?",
    options: [
      "Quarante-huit heures.",
      "Environ six à huit semaines.",
      "Un an complet.",
      "Le lendemain de l'appel.",
    ],
    correctIndex: 1,
    explanation: "Six to eight weeks elapse before services start.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Réunion de parents",
    audioScript: "Rappel : la réunion des parents de la classe de madame Lavoie est reportée à mardi prochain, dix-neuf heures, en salle douze. Nous parlerons du voyage scolaire et des allergies alimentaires à la cantine.",
    question: "Quels sujets seront abordés ?",
    options: [
      "Les résultats du test de maths seulement.",
      "Le voyage scolaire et les allergies à la cantine.",
      "Le changement de directeur.",
      "La fermeture de l'école en hiver.",
    ],
    correctIndex: 1,
    explanation: "The meeting covers the field trip and cafeteria allergies.",
  },

  // ── B1–B2 (Q11–30) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Congé parental",
    audioScript: "Au Québec, le congé parental peut être partagé entre les deux parents, mais beaucoup de pères ne prennent que les semaines réservées par la loi. Les employeurs doivent garder le poste, pourtant la culture d'entreprise décourage encore les longs absences masculines.",
    question: "Pourquoi les pères prennent-ils souvent peu de congé ?",
    options: [
      "Parce que la loi leur en refuse la majeure partie.",
      "Parce que la culture d'entreprise décourage les longues absences.",
      "Parce que les prestations sont nulles pour les hommes.",
      "Parce que le poste n'est pas protégé.",
    ],
    correctIndex: 1,
    explanation: "Workplace culture still discourages long paternal leave.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Coût de la garde",
    audioScript: "On calcule le prix d'une place en garderie, mais rarement le salaire que une mère renonce si elle reste à la maison faute de place. Perdre des années de cotisations retraite, ce n'est pas gratuit, même quand la garderie semble trop chère.",
    question: "Quel coût l'intervenant mentionne-t-il ?",
    options: [
      "Le prix des jouets pour enfants.",
      "La perte de revenus et de cotisations retraite.",
      "Les frais de transport scolaire.",
      "Le coût des livres scolaires.",
    ],
    correctIndex: 1,
    explanation: "Staying home costs foregone wages and pension contributions.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Inscription scolaire",
    audioScript: "— Notre bail est au nom de mon épouse, est-ce suffisant pour prouver la résidence ? — Oui, avec une pièce d'identité et le bail signé. Si l'enfant est né à l'étranger, apportez aussi sa preuve de statut de résident permanent.",
    question: "Que faut-il pour un enfant né à l'étranger ?",
    options: [
      "Uniquement le bail au nom d'un parent.",
      "La preuve de statut de résident permanent.",
      "Un certificat de vaccination seulement.",
      "Une lettre du consulat.",
    ],
    correctIndex: 1,
    explanation: "Proof of permanent resident status is also required.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Groupe de parents",
    audioScript: "Chaque mercredi, des parents nouvellement arrivés se retrouvent au centre communautaire pour parler en français et en arabe. Ce n'est pas une thérapie, mais l'animatrice oriente vers des services de santé mentale si besoin.",
    question: "Quel est l'objectif principal de ces rencontres ?",
    options: [
      "Remplacer les psychologues scolaires.",
      "Créer du lien entre parents et orienter vers des services.",
      "Distribuer des bourses d'études.",
      "Former des éducatrices en garderie.",
    ],
    correctIndex: 1,
    explanation: "Peer support and referral, not formal therapy.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Cantine scolaire",
    audioScript: "Les repas subventionnés exigent un formulaire renouvelé chaque automne. Dans notre école, le document n'existe qu'en anglais ; les familles francophones le remplissent moins souvent, même si leurs enfants auraient droit à l'aide.",
    question: "Quel problème est décrit ?",
    options: [
      "Les repas sont trop chers pour tous.",
      "La barrière linguistique réduit l'accès à la subvention.",
      "La cantine refuse les régimes végétariens.",
      "Les enseignants mangent gratuitement.",
    ],
    correctIndex: 1,
    explanation: "English-only forms reduce uptake among francophone families.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Travail de nuit",
    audioScript: "— Je travaille de vingt-deux heures à six heures ; aucune garderie n'accueille mon enfant. — Les CPE du quartier ferment à dix-huit heures. Essayez une gardienne en milieu familial, mais les places sont rares pour les nuits.",
    question: "Quel problème la mère souligne-t-elle ?",
    options: [
      "Elle ne veut pas payer la garderie.",
      "Aucune garde adaptée à son horaire de nuit.",
      "Son enfant est trop âgé pour la garderie.",
      "Les CPE sont gratuits mais fermés le week-end seulement.",
    ],
    correctIndex: 1,
    explanation: "Daycare hours do not match her night-shift schedule.",
  },
  {
    id: 17,
    level: "B1",
    topic: "Portail municipal",
    audioScript: "À partir de septembre, les demandes de place en garderie municipale passent uniquement par Internet. Un numéro d'assistance reste ouvert pour ceux sans connexion. Les dossiers incomplets seront refusés sans suite.",
    question: "Que arrive-t-il à un dossier incomplet ?",
    options: [
      "La ville le complète gratuitement.",
      "Il est refusé sans suite.",
      "Il passe en tête de liste.",
      "Les frais sont remboursés.",
    ],
    correctIndex: 1,
    explanation: "Incomplete online applications are closed.",
  },
  {
    id: 18,
    level: "B1",
    topic: "École et langue",
    audioScript: "Pour l'école francophone minoritaire, il faut prouver que un parent a étudié en français ou l'a appris ici. Deux familles du même immeuble peuvent donc avoir des droits différents selon leur histoire scolaire.",
    question: "Qu'est-ce qui varie entre les familles ?",
    options: [
      "Le prix des livres scolaires.",
      "L'admissibilité à l'école francophone selon le parcours linguistique.",
      "L'âge d'entrée à l'école.",
      "L'obligation de porter l'uniforme.",
    ],
    correctIndex: 1,
    explanation: "Minority-language school rights depend on parents' language background.",
  },
  {
    id: 19,
    level: "B1",
    topic: "Club des grands-parents",
    audioScript: "Le club accueille les aînés chaque mardi pour du bénévolat de lecture à l'école voisine. Le transport est gratuit sur réservation. Plusieurs participants disent combattre ainsi la solitude après la perte du conjoint.",
    question: "Pourquoi les participants viennent-ils au club ?",
    options: [
      "Pour recevoir un salaire de lecture.",
      "Pour sortir de l'isolement tout en étant utiles.",
      "Pour obtenir une place en résidence.",
      "Pour suivre des cours de informatique obligatoires.",
    ],
    correctIndex: 1,
    explanation: "Volunteer reading fights loneliness after bereavement.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Semaines non transférables",
    audioScript: "Quand cinq semaines de congé sont réservées au père et ne peuvent pas être données à la mère, les ménages les utilisent davantage. Sinon, c'est encore souvent la mère qui reste à la maison, même si elle gagne moins.",
    question: "Quel effet ont les semaines réservées au père ?",
    options: [
      "Elles augmentent le salaire des mères.",
      "Elles incitent les pères à prendre plus de congé.",
      "Elles suppriment le congé maternel.",
      "Elles sont automatiquement perdues.",
    ],
    correctIndex: 1,
    explanation: "Non-transferable father weeks raise paternal leave uptake.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Listes d'attente",
    audioScript: "Baisser le tarif des CPE à dix dollars a soulagé les budgets familiaux, mais les listes d'attente n'ont pas disparu. Sans plus d'éducatrices formées et de locaux, on peut payer une place qui n'existe pas encore.",
    question: "Quel paradoxe est mentionné ?",
    options: [
      "Les CPE sont plus chers qu'avant.",
      "Des tarifs bas sans plus de places disponibles.",
      "Les parents refusent les places subventionnées.",
      "Les éducatrices sont en surplus.",
    ],
    correctIndex: 1,
    explanation: "Lower fees did not create more spots or staff.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Aide et immigration",
    audioScript: "— Ma mère a besoin d'une infirmière à domicile. — C'est un service de santé, séparé de l'immigration. — Ma sœur craint que ça nuise au regroupement familial. — C'est une crainte fréquente, mais juridiquement ce n'est pas lié.",
    question: "De quoi la sœur a-t-elle peur ?",
    options: [
      "De payer trop cher les soins.",
      "Que l'aide à domicile affecte un dossier de regroupement.",
      "Que l'infirmière parle seulement anglais.",
      "Que la mère doive entrer en résidence.",
    ],
    correctIndex: 1,
    explanation: "They fear home care could harm a sponsorship application.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Proches aidants",
    audioScript: "L'indemnité pour proche aidant couvre à peine l'essence et les médicaments, alors que la fille a réduit son temps de travail de moitié. Le formulaire de renouvellement fait quarante pages ; beaucoup abandonnent avant la fin.",
    question: "Quelle limite du programme est soulignée ?",
    options: [
      "Il est réservé aux citoyens nés au Canada.",
      "Faible compensation et paperasse lourde.",
      "Il remplace entièrement les soins en résidence.",
      "Il est interdit en milieu rural.",
    ],
    correctIndex: 1,
    explanation: "Low pay and forty-page renewals discourage caregivers.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Modèles de garde",
    audioScript: "— Faut-il tout mettre dans les CPE ? — Non, les garderies familiales offrent des horaires flexibles pour les parents à quarts. Le problème, c'est qu'on les paie mal. Une bonne politique subventionnerait les deux modèles.",
    question: "Quelle solution l'intervenante propose-t-elle ?",
    options: [
      "Fermer les garderies familiales.",
      "Subventionner CPE et garderies familiales équitablement.",
      "Supprimer toute subvention publique.",
      "Réserver les CPE aux familles monoparentales.",
    ],
    correctIndex: 1,
    explanation: "She wants both centre-based and family daycare subsidized.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Jumelage intergénérationnel",
    audioScript: "Le programme relie des grands-parents immigrants et des familles locales pour des sorties à la bibliothèque. On parle des vaccins scolaires et des droits des aînés, pas dans une salle de cours, mais en marchant dans le parc.",
    question: "Comment se déroule l'apprentissage ?",
    options: [
      "Par des examens écrits chaque mois.",
      "Par des échanges informels lors d'activités communes.",
      "Par des vidéos envoyées par courriel.",
      "Par des cours payants le soir.",
    ],
    correctIndex: 1,
    explanation: "Learning happens informally during shared outings.",
  },
  {
    id: 26,
    level: "B2",
    topic: "Résidences et soins",
    audioScript: "La liste publique pour une chambre en CHSLD peut durer trois ans. Le privé coûte parfois cinq mille dollars par mois. Entre temps, c'est souvent une fille qui cesse de travailler à temps plein sans être payée pour les soins.",
    question: "Qui assume souvent les soins en attendant ?",
    options: [
      "Des infirmières embauchées par la ville.",
      "Une fille ou une proche non rémunérée.",
      "Uniquement des agences privées.",
      "Les voisins bénévoles remplacés par l'État.",
    ],
    correctIndex: 1,
    explanation: "Daughters often provide unpaid care during long waits.",
  },
  {
    id: 27,
    level: "B2",
    topic: "Congé paternel",
    audioScript: "Deux semaines de congé pour le père, ce n'est pas du partage réel, c'est un symbole. Tant qu'on considère la garde comme affaire de mères et qu'il n'y a pas de places en CPE, les semaines « pour papa » restent cosmétiques.",
    question: "Que critique l'auteur ?",
    options: [
      "La durée du congé maternel.",
      "Le caractère symbolique du court congé paternel sans garde.",
      "Le coût des couches.",
      "L'absence de congé pour les oncles.",
    ],
    correctIndex: 1,
    explanation: "Short father leave stays symbolic without daycare infrastructure.",
  },
  {
    id: 28,
    level: "B2",
    topic: "Hub familial",
    audioScript: "Le hub regroupe santé, garde de dépannage et conseil logement. Les rendez-vous manqués ont baissé, mais le bail expire dans deux ans et trois financeurs différents doivent renégocier. Personne ne sait encore qui paiera la suite.",
    question: "Quel risque menace le hub ?",
    options: [
      "Le refus des familles d'y entrer.",
      "L'incertitude du financement après l'échéance du bail.",
      "Une interdiction provinciale de mélanger les services.",
      "Un manque total de personnel.",
    ],
    correctIndex: 1,
    explanation: "Mixed funders must renegotiate when the lease ends.",
  },
  {
    id: 29,
    level: "B2",
    topic: "Dépistage",
    audioScript: "La campagne en milieu scolaire a augmenté les signalements en classe, tandis que celle dans les centres communautaires a touché des familles récentes isolées. Aucune des deux n'a couvert les deux groupes seule.",
    question: "Quelle leçon tire-t-on de la comparaison ?",
    options: [
      "Il faut supprimer les campagnes scolaires.",
      "Il faut combiner plusieurs canaux de sensibilisation.",
      "Les enseignants signalent trop de cas.",
      "Les centres communautaires sont inutiles.",
    ],
    correctIndex: 1,
    explanation: "Complementary channels are needed to reach different families.",
  },
  {
    id: 30,
    level: "B2",
    topic: "Travail invisible",
    audioScript: "Traduire une lettre médicale pour sa mère, conduire son père à la dialyse, préparer les lunchs : ce travail ne figure pas dans les statistiques d'emploi, mais il permet à d'autres membres de la famille de garder leur emploi payé.",
    question: "Quel rôle ce travail joue-t-il ?",
    options: [
      "Il remplace entièrement les services publics.",
      "Il soutient l'emploi des autres membres de la famille.",
      "Il est toujours rémunéré par la province.",
      "Il concerne seulement les familles riches.",
    ],
    correctIndex: 1,
    explanation: "Unpaid care enables other family members to keep paid jobs.",
  },

  // ── C1–C2 (Q31–39) ─────────────────────────────────────────────
  {
    id: 31,
    level: "C1",
    topic: "Évaluation des politiques",
    audioScript: "Mesurer le succès d'une politique de garde seulement par l'emploi des mères ignore si le père partage les tâches. On peut augmenter le taux d'activité tout en déplaçant les soins vers les grands-parents non payés.",
    question: "Quelle erreur d'évaluation est dénoncée ?",
    options: [
      "Compter uniquement le nombre de CPE.",
      "Utiliser l'emploi maternel comme seul indicateur d'égalité.",
      "Ignorer les listes d'attente.",
      "Refuser toute enquête auprès des pères.",
    ],
    correctIndex: 1,
    explanation: "Female employment alone misses unpaid grandparent care and father sharing.",
  },
  {
    id: 32,
    level: "C1",
    topic: "Niveaux de gouvernement",
    audioScript: "Après une naissance, les parents naviguent entre prestations fédérales, congés provinciaux, inscription municipale à la garderie et vaccins gérés par la santé provinciale. Savoir qui fait quoi devient une compétence en soi, surtout pour les familles migrantes.",
    question: "Quel défi les familles rencontrent-elles ?",
    options: [
      "L'absence totale de services en ligne.",
      "La complexité de répartir les démarches entre plusieurs niveaux.",
      "Le refus des hôpitaux d'accueillir les nouveau-nés.",
      "L'interdiction des garderies privées.",
    ],
    correctIndex: 1,
    explanation: "They must navigate federal, provincial, and municipal systems.",
  },
  {
    id: 33,
    level: "C1",
    topic: "Débat sur la gratuité",
    audioScript: "— La garde à dix dollars libère les mères pour travailler. — Oui, mais une subvention unique favorise le modèle urbain en CPE. Les familles rurales et les horaires de nuit ont besoin d'aide directe, pas seulement de places en centre.",
    question: "Quel argument le second intervenant développe ?",
    options: [
      "La garde devrait coûter encore plus cher.",
      "L'aide devrait être flexible selon les modèles de garde.",
      "Les mères ne devraient pas travailler.",
      "Les CPE sont illégaux hors Québec.",
    ],
    correctIndex: 1,
    explanation: "Direct flexible aid suits rural and night-shift families better.",
  },
  {
    id: 34,
    level: "C1",
    topic: "Confiance et services",
    audioScript: "Une mauvaise expérience avec l'aide à domicile peut colorer la perception de toute la santé publique, même sans autre contact. Les réformes ciblées peinent à restaurer la confiance, car le problème est symbolique autant qu'administratif.",
    question: "Pourquoi les réformes ciblées sont-elles limitées ?",
    options: [
      "Parce que les familles ne lisent pas les brochures.",
      "Parce que la méfiance se propage à l'ensemble du système.",
      "Parce que les infirmières refusent les visites.",
      "Parce que les sondages sont interdits.",
    ],
    correctIndex: 1,
    explanation: "One bad experience taints trust across the health system.",
  },
  {
    id: 35,
    level: "C1",
    topic: "Évaluation sociale",
    audioScript: "Comparer deux politiques de garde exige d'imaginer ce qui se serait passé sans elles. Une aide qui ralentit la baisse d'emploi maternel peut paraître inutile si l'on ne mesure que le chiffre final, pas la trajectoire.",
    question: "Quel obstacle méthodologique est décrit ?",
    options: [
      "L'absence de données sur les enfants.",
      "L'impossibilité d'observer le scénario sans la politique.",
      "Le refus des parents de répondre aux enquêtes.",
      "La fraude dans les déclarations de revenu.",
    ],
    correctIndex: 1,
    explanation: "Without a counterfactual, slowing decline looks like failure.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Philosophie du care",
    audioScript: "Aimer son enfant et absorber seule quinze ans de rendez-vous scolaires ne sont pas la même chose. Les institutions supposent encore une adulte disponible, souvent la mère, pour combler les trous du calendrier scolaire sans la payer.",
    question: "Quel décalage le philosophe décrit-il ?",
    options: [
      "Entre école publique et privée.",
      "Entre amour parental et travail domestique non reconnu imposé aux femmes.",
      "Entre congé parental et maladie.",
      "Entre ville et campagne.",
    ],
    correctIndex: 1,
    explanation: "School schedules assume unpaid maternal availability.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Solidarité intergénérationnelle",
    audioScript: "Les budgets comptent les pensions versées aux aînés, mais pas les heures où un grand-père garde un petit-enfant pour que la mère travaille. Cette économie de care circule dans les deux sens et reste invisible dans les débats sur la productivité.",
    question: "Quel angle mort budgétaire est souligné ?",
    options: [
      "Les pensions sont trop élevées.",
      "Le care non rémunéré qui soutient l'emploi des parents.",
      "Les grands-parents refusent de garder les enfants.",
      "Les CPE coûtent trop cher aux municipalités.",
    ],
    correctIndex: 1,
    explanation: "Unpaid grandparent childcare enables maternal employment but is uncounted.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Intégration et parentalité",
    audioScript: "On invite les familles immigrées à confier leurs enfants à des garderies dont les règles diffèrent de celles du pays d'origine, tout en leur demandant de transmettre la culture à la maison. Peu de politiques articulent ces deux exigences contradictoires.",
    question: "Quelle tension est présentée ?",
    options: [
      "Entre français et anglais à l'école.",
      "Entre normes institutionnelles et transmission culturelle familiale.",
      "Entre congé parental et garde.",
      "Entre vaccins obligatoires et optionnels.",
    ],
    correctIndex: 1,
    explanation: "Institutional norms clash with home cultural transmission.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Qualité en petite enfance",
    audioScript: "Réduire la qualité à un ratio adultes-enfants oublie la stabilité des éducatrices et le lien avec les familles. Financer seulement des places sans formation continue améliore les statistiques, pas nécessairement l'expérience vécue par l'enfant.",
    question: "Pourquoi les réformes centrées sur les ratios sont limitées ?",
    options: [
      "Parce que les parents ne visitent jamais les CPE.",
      "Parce que la qualité relationnelle dépasse les ratios.",
      "Parce que les éducatrices refusent toute formation.",
      "Parce que la qualité est impossible à définir.",
    ],
    correctIndex: 1,
    explanation: "Relational stability and family links exceed staffing ratios.",
  },
];
