import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 9 — Compréhension orale. Theme: mobility, transport and urban life in Canada.
 *
 * `audioScript` is rendered by Edge TTS, so each script is written to be read
 * aloud cleanly: no bullet points, numbers spelled where ambiguous, and
 * dialogue turns separated by em dashes.
 */
export const TCF_LISTENING_P9: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "À la gare",
    audioScript: "— Excusez-moi, le train pour Québec part d'où ? — Voie sept, dans dix minutes. — Merci. — Attention, voie sept, pas voie neuf.",
    question: "De quelle voie part le train ?",
    options: ["Voie cinq.", "Voie sept.", "Voie neuf.", "Voie onze."],
    correctIndex: 1,
    explanation: "The clerk says platform seven, not nine.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Annonce dans le métro",
    audioScript: "Votre attention, s'il vous plaît. Station Berri-UQAM : correspondance ligne orange et ligne verte. Prochain métro direction Honoré-Beaugrand dans deux minutes.",
    question: "Quelles lignes peut-on prendre à cette station ?",
    options: ["Seulement la ligne jaune.", "Les lignes orange et verte.", "Uniquement la ligne bleue.", "Aucune correspondance."],
    correctIndex: 1,
    explanation: "Berri-UQAM offers orange and green line connections.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Location de vélo",
    audioScript: "— Bonjour, je voudrais un vélo pour deux heures. — Voici le casque et le cadenas. C'est vingt-deux dollars. Rendez-le avant dix-sept heures au même kiosque.",
    question: "Quand faut-il rendre le vélo ?",
    options: ["À midi.", "Avant dix-sept heures.", "Demain matin.", "Dans une semaine."],
    correctIndex: 1,
    explanation: "Return before five p.m. at the same kiosk.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Message radio trafic",
    audioScript: "Circulation dense sur l'autoroute quarante est entre boulevard Pie-IX et boulevard Saint-Michel. Prévoyez vingt minutes de retard. Aucun incident majeur signalé pour l'instant.",
    question: "Que recommande l'annonce ?",
    options: ["Éviter complètement l'autoroute.", "Prévoir plus de temps sur ce tronçon.", "Rouler plus vite que d'habitude.", "Sortir à Pie-IX immédiatement."],
    correctIndex: 1,
    explanation: "Drivers should expect about twenty minutes extra delay.",
  },
  {
    id: 5,
    level: "A2",
    topic: "Guichet transport",
    audioScript: "— Je voudrais un pass mensuel étudiant. — Montrez votre carte d'étudiant en cours de validité et une pièce d'identité. Le tarif réduit s'applique seulement si vous avez moins de vingt-cinq ans.",
    question: "Que doit présenter la personne ?",
    options: [
      "Uniquement un relevé de notes.",
      "Une carte d'étudiant valide et une pièce d'identité.",
      "Un permis de conduire seulement.",
      "Un chèque de garantie.",
    ],
    correctIndex: 1,
    explanation: "Valid student card and ID are required for the reduced monthly pass.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Stationnement",
    audioScript: "— Est-ce que le stationnement est gratuit le dimanche ? — Oui, dans ce secteur, du samedi vingt heures au lundi sept heures. En semaine, c'est trois dollars l'heure avec le parcomètre.",
    question: "Combien coûte le stationnement en semaine ?",
    options: ["Gratuit toute la journée.", "Trois dollars l'heure.", "Dix dollars la journée.", "Uniquement le vendredi."],
    correctIndex: 1,
    explanation: "Weekday parking is three dollars per hour at the meter.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Taxi",
    audioScript: "— Pouvez-vous me déposer à l'aéroport ? — Bien sûr. Avec les travaux sur le boulevard, comptez environ quarante-cinq minutes. Le tarif est affiché sur le compteur, plus les frais de bagages si vous en avez.",
    question: "Qu'est-ce qui peut augmenter le prix ?",
    options: [
      "Le choix de la radio.",
      "Les frais de bagages.",
      "Le paiement en espèces seulement.",
      "La couleur du taxi.",
    ],
    correctIndex: 1,
    explanation: "Meter fare plus baggage fees if applicable.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Piste cyclable",
    audioScript: "Rappel de la ville : la piste du parc Lafontaine est fermée pour réparation jusqu'à jeudi. Les cyclistes doivent emprunter la rue Rachel, où une voie temporaire est aménagée.",
    question: "Que doivent faire les cyclistes ?",
    options: [
      "Arrêter de circuler à vélo.",
      "Utiliser la voie temporaire sur Rachel.",
      "Rouler sur le trottoir du parc.",
      "Attendre jusqu'à dimanche.",
    ],
    correctIndex: 1,
    explanation: "Use the temporary lane on Rachel while the park path is closed.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Autobus retard",
    audioScript: "— Le bus quarante-cinq est en retard à cause de la neige. — Savez-vous de combien ? — Environ quinze minutes. Le prochain devrait arriver dans cinq minutes si le trajet reste dégagé.",
    question: "Quel retard annonce-t-on pour le bus quarante-cinq ?",
    options: ["Cinq minutes.", "Quinze minutes.", "Une heure.", "Aucun retard."],
    correctIndex: 1,
    explanation: "Bus 45 is about fifteen minutes late due to snow.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Covoiturage",
    audioScript: "Chers collègues, le stationnement du bureau sera fermé mardi pour l'épandage de sel. Merci de privilégier le covoiturage ou le métro station Laurier. Le télétravail est autorisé pour ceux qui n'ont pas d'option.",
    question: "Pourquoi le stationnement est-il fermé ?",
    options: [
      "Pour une grève des employés.",
      "Pour l'épandage de sel.",
      "Pour un concert dans le quartier.",
      "Pour des travaux de métro.",
    ],
    correctIndex: 1,
    explanation: "Parking closes Tuesday for salt spreading.",
  },

  // ── B1–B2 (Q11–30) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Permis et hiver",
    audioScript: "— Je viens de l'Ontario avec mon permis. — Vous pouvez conduire ici avec votre permis provincial tant qu'il est valide, mais vérifiez votre assurance. Dès décembre, les pneus d'hiver sont obligatoires au Québec, même pour les visiteurs.",
    question: "Que doit vérifier la personne ?",
    options: [
      "Repasser l'examen pratique immédiatement.",
      "Son assurance et les règles sur les pneus d'hiver.",
      "Renoncer à sa voiture.",
      "Obtenir un permis international en vingt-quatre heures.",
    ],
    correctIndex: 1,
    explanation: "Keep valid provincial licence and insurance; winter tires mandatory in Quebec from December.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Radio locale",
    audioScript: "La ville de Edmonton consulte les résidents sur le plan de transport dix ans. Les séances publiques ont lieu en mars ; les commentaires en ligne restent ouverts jusqu'au trente avril. Les priorités retenues seront annoncées en juin.",
    question: "Comment peut-on participer ?",
    options: [
      "Uniquement en votant aux élections fédérales.",
      "En séance publique ou en ligne jusqu'au trente avril.",
      "En payant une taxe spéciale.",
      "En signant une pétition papier en mairie seulement.",
    ],
    correctIndex: 1,
    explanation: "Public meetings in March and online comments until April 30.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Entre voisins",
    audioScript: "— As-tu vu le plan pour la rue piétonne l'été prochain ? — Oui, les livraisons seront autorisées avant huit heures seulement. — Et les résidents ? — Ils pourront garer dans le stationnement souterrain avec une vignette.",
    question: "Quand les livraisons seront-elles permises ?",
    options: ["Toute la journée.", "Avant huit heures seulement.", "Uniquement le dimanche.", "Jamais."],
    correctIndex: 1,
    explanation: "Deliveries allowed only before eight a.m.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Reportage",
    audioScript: "À Saskatoon, une navette gratuite relie le centre aux hôpitaux les week-ends. Elle ne remplace pas les ambulances, mais elle aide les familles sans voiture à des rendez-vous non urgents. Le service est financé par la région sanitaire.",
    question: "Quel rôle joue cette navette ?",
    options: [
      "Elle remplace les urgences.",
      "Elle facilite des déplacements non urgents le week-end.",
      "Elle transporte uniquement le personnel médical.",
      "Elle est réservée aux touristes.",
    ],
    correctIndex: 1,
    explanation: "Weekend shuttle helps carless families reach non-urgent appointments.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Guichet municipal",
    audioScript: "— Je voudrais une vignette de stationnement pour mon déménagement. — Vous pouvez réserver deux places devant l'immeuble pour quarante-huit heures. Le coût est de trente-cinq dollars. Déposez la demande au moins trois jours à l'avance.",
    question: "Quelle condition le fonctionnaire mentionne-t-il ?",
    options: [
      "La vignette est gratuite.",
      "Il faut demander trois jours à l'avance.",
      "Une seule place est possible.",
      "Le déménagement doit avoir lieu un dimanche.",
    ],
    correctIndex: 1,
    explanation: "Moving parking spots must be booked at least three days ahead for thirty-five dollars.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Organisme communautaire",
    audioScript: "Mobilité Plus accompagne les nouveaux résidents pour leur première carte de transport, l'achat d'un vélo d'occasion sécurisé et la lecture des plans de quartier. Atelier gratuit samedi prochain, inscription par courriel.",
    question: "Que propose l'organisme ?",
    options: [
      "Des cours de conduite payants pour débutants.",
      "De l'aide pour le transport et le vélo au quotidien.",
      "Des permis de stationnement gratuits à vie.",
      "Des voitures de location subventionnées.",
    ],
    correctIndex: 1,
    explanation: "Help with transit cards, safe used bikes, and neighbourhood maps.",
  },
  {
    id: 17,
    level: "B1",
    topic: "Interview citoyenne",
    audioScript: "— Pourquoi avez-vous vendu votre voiture ? — Le métro et le vélo suffisent près du centre. L'assurance et le stationnement coûtaient plus cher que l'abonnement annuel. L'hiver, j'utilise parfois l'autopartage.",
    question: "Pourquoi la personne a-t-elle vendu sa voiture ?",
    options: [
      "Parce qu'elle a perdu son permis.",
      "Parce que le transit et le vélo coûtent moins cher au centre-ville.",
      "Parce que les voitures sont interdites.",
      "Parce qu'elle déménage à la campagne.",
    ],
    correctIndex: 1,
    explanation: "Insurance and parking exceeded annual transit pass cost downtown.",
  },
  {
    id: 18,
    level: "B1",
    topic: "Application mobile",
    audioScript: "— L'application ne montre pas le bus soixante-dix. — Avez-vous activé la localisation ? Sans elle, les horaires en temps réel ne s'affichent pas. — Ah, d'accord. — Vous pouvez aussi recevoir une alerte si votre ligne est retardée.",
    question: "Pourquoi les horaires en temps réel ne s'affichent pas ?",
    options: [
      "Parce que la ligne soixante-dix n'existe plus.",
      "Parce que la localisation n'est pas activée.",
      "Parce que l'application est payante.",
      "Parce qu'il n'y a pas de réseau le soir.",
    ],
    correctIndex: 1,
    explanation: "Real-time data requires location enabled in the app.",
  },
  {
    id: 19,
    level: "B1",
    topic: "Conseil municipal",
    audioScript: "— Cette séance porte sur la voie réservée aux bus. — Puis-je intervenir en français ? — Oui, un technicien traduit les slides. Les questions du public sont limitées à trois minutes chacune.",
    question: "Que précise le modérateur ?",
    options: [
      "La séance est privée.",
      "Chaque intervention publique dure au maximum trois minutes.",
      "Seuls les automobilistes peuvent parler.",
      "La traduction est interdite.",
    ],
    correctIndex: 1,
    explanation: "Public comments are limited to three minutes each; slides are translated.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Débat radiophonique",
    audioScript: "— Élargir l'autoroute soulagera le trafic. — Pendant quelques mois, peut-être. L'expérience montre que de nouveaux trajets remplissent la capacité. Sans bus rapide en parallèle, on reconstruit le même embouteillage, plus large.",
    question: "Quel argument le second intervenant oppose-t-il ?",
    options: [
      "Les autoroutes sont interdites au Canada.",
      "Plus de voies attire plus de trafic sans solution durable.",
      "Les bus rapides coûtent moins que l'entretien.",
      "Personne n'utilise l'autoroute actuelle.",
    ],
    correctIndex: 1,
    explanation: "Induced demand fills new lanes without parallel rapid transit.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Conférence",
    audioScript: "Les données de comptage vélo sont publiées en open data, mais au format technique. Sans association de quartier ou média local pour visualiser les chiffres, peu de citoyens participent au débat sur les pistes. La transparence reste théorique.",
    question: "Quel obstacle la conférencière souligne-t-elle ?",
    options: [
      "Le refus de compter les cyclistes.",
      "La difficulté du public à utiliser les données brutes.",
      "L'interdiction des pistes protégées.",
      "L'absence de vélos en hiver.",
    ],
    correctIndex: 1,
    explanation: "Raw open data needs mediation for citizens to engage.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Responsable transport",
    audioScript: "— Pourquoi le bus de nuit est-il si rare ? — Le budget couvre trois lignes seulement, là où la demande est mesurée la plus forte. Étendre le service exigerait une taxe ou un transfert provincial. Nous présentons un plan progressif en automne.",
    question: "Qu'est-ce qui limite le bus de nuit ?",
    options: [
      "Un manque de conducteurs uniquement.",
      "Un budget qui ne finance que trois lignes pour l'instant.",
      "Une interdiction légale le week-end.",
      "L'absence de routes goudronnées.",
    ],
    correctIndex: 1,
    explanation: "Budget covers only three night routes where demand is highest.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Chronique urbaine",
    audioScript: "Comparer le pourcentage de cyclistes de Montréal à celui d'une ville néerlandaise sans parler du déneigement, c'est une caricature. Ici, une piste non déneigée pousse les gens vers le métro bondé ou la voiture. La qualité hivernale compte autant que les kilomètres peints.",
    question: "Quelle critique la chronique formule-t-elle ?",
    options: [
      "Le vélo est impossible au Canada.",
      "Les comparaisons ignorent l'entretien hivernal des pistes.",
      "Le métro est toujours vide.",
      "Les Pays-Bas n'ont pas de neige.",
    ],
    correctIndex: 1,
    explanation: "International bike-share comparisons ignore snow clearing quality.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Table ronde",
    audioScript: "— Les zones à faibles émissions améliorent l'air. — Oui, mais sans renfort du bus regional, ceux qui habitent loin paient la taxe et n'ont pas d'alternative. Il faut coupler restriction et service, sinon on punit la géographie.",
    question: "Quelle critique est formulée ?",
    options: [
      "Les zones à faibles émissions sont gratuites.",
      "La mesure frappe des ménages sans option de transport.",
      "L'air ne s'améliore jamais.",
      "Les bus régionaux sont interdits en ville.",
    ],
    correctIndex: 1,
    explanation: "Low-emission zones hurt distant households without transit alternatives.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Reportage social",
    audioScript: "À Toronto, une ligne d'information multilingue explique comment contester une amende de stationnement reçue par courrier. Beaucoup d'appelants confondent amende municipale et infraction provinciale. Les conseillers orientent vers le bon formulaire en ligne.",
    question: "Quel est l'objectif principal de cette ligne ?",
    options: [
      "Payer les amendes à la place des citoyens.",
      "Aider à comprendre et contester les bonnes procédures.",
      "Supprimer toutes les amendes.",
      "Vendre des permis de stationnement.",
    ],
    correctIndex: 1,
    explanation: "Advisors clarify which agency issued the fine and how to contest it.",
  },
  {
    id: 26,
    level: "B2",
    topic: "Documentaire",
    audioScript: "Le film suit une famille qui déménage en banlieue pour un loyer moins cher. Le père passe deux heures par jour en autobus et correspondance. La mère dit que le « bargain » locatif disparaît quand on compte le temps perdu et les garderies prolongées.",
    question: "Quelle difficulté la mère souligne-t-elle ?",
    options: [
      "Le refus du propriétaire de louer.",
      "Le coût caché du long trajet quotidien.",
      "L'interdiction du télétravail.",
      "L'absence de métro en banlieue seulement en été.",
    ],
    correctIndex: 1,
    explanation: "Cheaper rent is offset by commute time and extended childcare.",
  },
  {
    id: 27,
    level: "B2",
    topic: "Interview",
    audioScript: "— Pourquoi les jeunes utilisent-ils peu le train interurbain ? — Les tarifs flexibles manquent : ils voyagent un mardi à quatorze heures, pas un vendredi à dix-sept heures. Quand le prix reflète la demande, les sièges vides deviennent abordables.",
    question: "Selon l'interviewé, comment attirer les jeunes ?",
    options: [
      "En supprimant le train.",
      "En proposant des tarifs adaptés aux heures creuses.",
      "En interdisant les voitures.",
      "En rendant tous les billets identiques.",
    ],
    correctIndex: 1,
    explanation: "Off-peak pricing could fill empty seats and suit youth schedules.",
  },
  {
    id: 28,
    level: "B2",
    topic: "Débat municipal",
    audioScript: "— Taxer le stationnement rue finance le tramway. — Dans notre quartier, beaucoup de commerçants n'ont pas de stationnement arrière. Une taxe élevée pousse les clients vers les centres commerciaux en périphérie avec parking gratuit.",
    question: "Quel argument le second orateur utilise-t-il ?",
    options: [
      "Le tramway est illégal.",
      "La taxe peut nuire aux commerces sans parking privé.",
      "Les clients ne viennent jamais en voiture.",
      "Le stationnement rue est déjà gratuit.",
    ],
    correctIndex: 1,
    explanation: "Street parking fees may shift customers to malls with free lots.",
  },
  {
    id: 29,
    level: "B2",
    topic: "Chronique",
    audioScript: "Conduire un bus scolaire m'a appris où les stops manquent de trottoirs. Les enfants descendent dans la neige sur la chaussée parce que la municipalité n'a jamais terminé le réseau piéton. La sécurité scolaire, ce n'est pas seulement la vitesse des automobilistes.",
    question: "Qu'apprend l'auteur en conduisant le bus scolaire ?",
    options: [
      "Que les enfants refusent l'autobus.",
      "Que l'infrastructure piétonne est incomplète dans certains arrêts.",
      "Que la neige n'affecte pas les trajets.",
      "Que les municipalités interdisent les bus.",
    ],
    correctIndex: 1,
    explanation: "Missing sidewalks force children onto the road at stops.",
  },
  {
    id: 30,
    level: "B2",
    topic: "Analyse institutionnelle",
    audioScript: "Quand un usager se plaint du « transport », il mélange souvent la régie municipale, la société de train provincial et les routes fédérales. Harmoniser les billets intermodal avance lentement parce que chaque acteur protège son système de paiement.",
    question: "Quel problème le commentateur décrit-il ?",
    options: [
      "L'absence totale de trains.",
      "La fragmentation des responsabilités et des titres.",
      "Le refus des usagers de payer.",
      "La suppression des autobus urbains.",
    ],
    correctIndex: 1,
    explanation: "Split agencies block integrated ticketing and confuse riders.",
  },

  // ── C1–C2 (Q31–39) ─────────────────────────────────────────────
  {
    id: 31,
    level: "C1",
    topic: "Conférence universitaire",
    audioScript: "La mobilité durable ne se mesure pas seulement aux émissions du véhicule. Il faut intégrer le coût du stationnement subventionné, la taille des routes entretenues et le temps de garde d'enfants lié aux longs trajets. Sans ces externalités, comparer voiture et métro trompe les décideurs.",
    question: "Quelle définition la conférencière propose-t-elle ?",
    options: [
      "Compter uniquement les kilomètres parcourus à vélo.",
      "Inclure coûts cachés comme stationnement et temps de garde.",
      "Ignorer les émissions des autobus.",
      "Privilégier les indicateurs automobile.",
    ],
    correctIndex: 1,
    explanation: "Sustainable mobility metrics must include parking subsidies and care time.",
  },
  {
    id: 32,
    level: "C1",
    topic: "Séminaire d'urbanisme",
    audioScript: "Densifier près du transit augmente la demande sur les lignes existantes. Si la fréquence bus ne suit pas, les ascenseurs de station saturent et les piétons envahissent les trottoirs étroits. Le bâtiment monte avant que le réseau absorbe les flux.",
    question: "Quel phénomène l'intervenant souligne-t-il ?",
    options: [
      "La baisse automatique des loyers.",
      "Un décalage entre construction immobilière et capacité transport.",
      "La fin du métro en centre-ville.",
      "L'interdiction des tours.",
    ],
    correctIndex: 1,
    explanation: "Transit-oriented towers arrive before network capacity catches up.",
  },
  {
    id: 33,
    level: "C1",
    topic: "Débat éthique",
    audioScript: "— Les caméras de stationnement automatisées sont efficaces. — Efficaces pour la caisse, oui. Mais qui vérifie les erreurs de plaque ? Un parent en garde alternée peut recevoir trois amendes pour un même stationnement légal mal scanné. L'efficacité sans recours accessible n'est pas justice.",
    question: "Quel argument le second intervenant développe-t-il ?",
    options: [
      "Les caméras sont toujours fausses.",
      "L'automatisation sans recours équitable pose problème.",
      "Le stationnement devrait être gratuit partout.",
      "Les plaques d'immatriculation sont inutiles.",
    ],
    correctIndex: 1,
    explanation: "Automated enforcement needs accessible error correction.",
  },
  {
    id: 34,
    level: "C1",
    topic: "Cours de géographie",
    audioScript: "Les cartes d'isochrones montrent où l'on peut aller en trente minutes en transit. Elles masquent la fiabilité : un bus en retard compresse le cercle réel. Dans les quartiers nordiques, une tempête peut annuler une journée de déplacements alors que la carte reste verte.",
    question: "Quelle limite des cartes est présentée ?",
    options: [
      "Elles interdisent le vélo.",
      "Elles ignorent retards et aléas climatiques.",
      "Elles sont illégales au Canada.",
      "Elles ne concernent que Toronto.",
    ],
    correctIndex: 1,
    explanation: "Isochrones assume reliability; storms shrink real accessibility.",
  },
  {
    id: 35,
    level: "C1",
    topic: "Exposé économique",
    audioScript: "Subventionner l'essence réduit la facture immédiate, mais verrouille l'étalement urbain : les ménages s'éloignent, les kilomètres augmentent. Investir dans le bus regional coûte aussi cher politiquement, mais il lie des villages sans imposer une voiture par adulte.",
    question: "Quel choix l'intervenant oppose-t-il ?",
    options: [
      "Entre tramway et métro aérien.",
      "Entre subvention carburant et lien collectif régional.",
      "Entre vélo et trottinette.",
      "Entre taxi et limousine.",
    ],
    correctIndex: 1,
    explanation: "Fuel subsidies vs regional bus shape sprawl and car dependence.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Conférence de philosophie",
    audioScript: "Présenter la voiture comme libération individuelle oublie que la rue est un bien rival. Chaque place stationnée gratuite est un morceau de trottoir ou de piste non construit. Reconnaître cette rivalité, c'est cesser de traiter le gratuité comme neutre.",
    question: "Quel décalage le philosophe décrit-il ?",
    options: [
      "Entre train et avion.",
      "Entre liberté automobile perçue et rareté de l'espace public.",
      "Entre rural et urbain seulement en été.",
      "Entre camion et autobus.",
    ],
    correctIndex: 1,
    explanation: "Free parking trades off pedestrian and bike space on rival street space.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Séminaire de sociologie",
    audioScript: "Les modèles de trafic supposent un conducteur rationnel. Les trajets réels incluent déposer un enfant, éviter une rue où l'on a été harcelé, chercher un commerce ouvert tard. Planifier uniquement sur la vitesse théorique sous-estime ces détours chargés de sens.",
    question: "Quelle tension le séminariste souligne-t-il ?",
    options: [
      "Entre français et anglais dans les annonces.",
      "Entre modèles rationnels et pratiques vécues.",
      "Entre hommes et femmes au volant seulement.",
      "Entre jour et nuit sur l'autoroute.",
    ],
    correctIndex: 1,
    explanation: "Rational speed models miss care and safety detours in real trips.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Colloque smart city",
    audioScript: "Installer des capteurs de stationnement attire les headlines, mais si les garages de bus manquent de personnel, la ponctualité s'effondre. Le gadget visible remplace parfois l'entretien invisible dans les budgets. Les usagers se souviennent du bus en retard, pas de l'appli.",
    question: "Quel paradoxe est présenté ?",
    options: [
      "Les capteurs suppriment les autobus.",
      "L'investissement tech masque le sous-financement de l'entretien.",
      "Les applications sont interdites.",
      "Les usagers ne possèdent pas de téléphone.",
    ],
    correctIndex: 1,
    explanation: "Visible smart-city tech overshadows bus maintenance staffing.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Conférence mobilité",
    audioScript: "Réduire la mobilité au mode de transport oublié les contraintes de temps : gardes, horaires décalés, peur de marcher la nuit. La politique crédible combine service nocturne, éclairage et tarification juste, au lieu de moraliser le choix automobile sans alternative.",
    question: "Quelle conception de la mobilité l'intervenant défend-il ?",
    options: [
      "Une mobilité centrée sur la vitesse maximale.",
      "Une mobilité intégrant contraintes sociales et alternatives réelles.",
      "Une mobilité réservée aux centres denses.",
      "Une mobilité fondée sur l'interdiction du bus.",
    ],
    correctIndex: 1,
    explanation: "Policy must address care schedules and night safety, not just modes.",
  },
];
