import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 8 — Compréhension écrite. Theme: family, early childhood and social services in Canada.
 *
 * Hand-authored to keep distractors plausible and similar in length, so no
 * surface heuristic (longest option, option B) beats reading the text.
 */
export const TCF_READING_P8: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "GARDERIE LES PETITS ÉRABLES\nOuverture : lundi au vendredi, 7 h 30 – 17 h 30\nFermé les jours fériés\nInscription sur rendez-vous au 514-555-0123",
    question: "Quand la garderie est-elle ouverte ?",
    options: ["Le samedi matin seulement.", "Du lundi au vendredi.", "Tous les jours de la semaine.", "Uniquement sur rendez-vous."],
    correctIndex: 1,
    explanation: "The sign says Monday to Friday, 7:30–17:30.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Horaires",
    passage: "ÉCOLE PRIMAIRE RIVERSIDE\nCour de récréation : 10 h 15 – 10 h 30\nDéjeuner : 11 h 45 – 12 h 45\nFin des cours : 15 h 20\nBus scolaire : porte principale",
    question: "À quelle heure finissent les cours ?",
    options: ["À 10 h 30.", "À 12 h 45.", "À 15 h 20.", "À 17 h."],
    correctIndex: 2,
    explanation: "Classes end at 15:20.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Salut Amina,\nLe cours de préparation à la naissance est reporté à jeudi, 18 h, au centre communautaire. Apporte une bouteille d'eau et un coussin si tu en as un.\nÀ bientôt,\nSophie",
    question: "Qu'est-ce que Sophie demande à Amina ?",
    options: ["D'apporter de l'eau et éventuellement un coussin.", "D'annuler le cours.", "De venir avec son conjoint.", "De payer l'inscription sur place."],
    correctIndex: 0,
    explanation: "Sophie asks her to bring water and a pillow if she has one.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "CLINIQUE DE VACCINATION — FAMILLES\nSamedi 4 mai, 9 h – 14 h\nGymnase de l'école Saint-Joseph\nGratuit pour les enfants de 0 à 5 ans\nCarte d'assurance maladie requise",
    question: "Pour qui la vaccination est-elle gratuite ?",
    options: ["Pour tous les adultes.", "Pour les enfants de 0 à 5 ans.", "Pour les résidents permanents seulement.", "Pour les personnes sans carte."],
    correctIndex: 1,
    explanation: "Vaccination is free for children aged 0 to 5.",
  },
  {
    id: 5,
    level: "A2",
    passageType: "Courriel",
    passage: "Objet : Congé parental\n\nBonjour M. Tran,\nVotre demande de congé parental de dix semaines est acceptée à compter du 3 septembre. Votre employeur versera les prestations selon le régime en vigueur. Conservez une copie de cette confirmation pour votre dossier.\nService des ressources humaines",
    question: "Que confirme ce courriel ?",
    options: [
      "Le refus de la demande de congé.",
      "L'acceptation d'un congé parental de dix semaines à partir du 3 septembre.",
      "Le versement d'un bonus de naissance.",
      "La fin du contrat de travail.",
    ],
    correctIndex: 1,
    explanation: "Ten weeks of parental leave is approved starting September 3.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Note d'information",
    passage: "INSCRIPTION À LA GARDERIE MUNICIPALE\nLes parents doivent fournir le certificat de naissance de l'enfant, une preuve de résidence et le numéro d'assurance sociale du parent demandeur. Sans ces documents, le dossier ne sera pas traité.",
    question: "Que faut-il pour inscrire un enfant ?",
    options: [
      "Uniquement le certificat de naissance.",
      "Le certificat de naissance, une preuve de résidence et le NAS du parent.",
      "Un certificat médical et deux photos.",
      "Une lettre de l'employeur seulement.",
    ],
    correctIndex: 1,
    explanation: "Birth certificate, proof of residence, and parent's SIN are required.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Affiche",
    passage: "MAISON DES AÎNÉS — CLUB DU MERCREDI\nJeux de société, café et aide pour remplir les formulaires\nMercredi 14 h – 16 h\nEntrée libre — transport adapté sur demande",
    question: "Quel service l'affiche propose-t-elle ?",
    options: [
      "Des cours de natation pour seniors.",
      "Des activités sociales et une aide administrative le mercredi après-midi.",
      "Une vente de médicaments sur ordonnance.",
      "Un service de repas livrés à domicile.",
    ],
    correctIndex: 1,
    explanation: "Wednesday club offers games, coffee, and help with forms.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "SMS",
    passage: "Rappel : réunion des parents d'élèves de la 3e année, mardi 19 h, salle 12. Ordre du jour : sortie scolaire et budget cantine. Enfants non admis.",
    question: "Quel est l'objet de ce message ?",
    options: [
      "L'annulation de la sortie scolaire.",
      "Une réunion de parents sur la sortie et la cantine.",
      "L'inscription à la cantine uniquement.",
      "Un changement d'horaire des cours.",
    ],
    correctIndex: 1,
    explanation: "Parents' meeting covers the field trip and cafeteria budget.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Formulaire",
    passage: "DEMANDE D'AIDE À DOMICILE — PERSONNE ÂGÉE\nÉtape 1 : évaluation téléphonique\nÉtape 2 : visite à domicile par une infirmière\nÉtape 3 : plan de services approuvé\nDélai moyen entre l'étape 1 et 3 : six à huit semaines",
    question: "Combien de temps dure en général la procédure complète ?",
    options: [
      "Quarante-huit heures.",
      "Environ six à huit semaines.",
      "Un an minimum.",
      "Le jour même de l'appel.",
    ],
    correctIndex: 1,
    explanation: "Average delay from step 1 to 3 is six to eight weeks.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Courriel",
    passage: "Bonjour Mme Osei,\nVotre enfant est inscrit sur la liste d'attente pour la garderie du quartier Nord. Nous vous contacterons par courriel dès qu'une place se libère. En attendant, consultez la carte des garderies familiales sur le site de la ville.\nCordialement,\nLe service de la petite enfance",
    question: "Que doit faire Mme Osei en attendant ?",
    options: [
      "Relancer le bureau chaque semaine par téléphone.",
      "Consulter la carte des garderies familiales en ligne.",
      "Payer un dépôt pour garder sa priorité.",
      "Retirer sa demande et réinscrire plus tard.",
    ],
    correctIndex: 1,
    explanation: "She should use the city's map of family daycares while waiting.",
  },

  // ── B1–B2 (Q11–29) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Au Canada, le congé parental est souvent partagé entre les deux parents, mais les hommes prennent encore en moyenne moins de semaines que les femmes. Les employeurs doivent réserver le poste, mais rien n'oblige les salariés à utiliser leur quota. Beaucoup de pères citent la culture d'entreprise et la peur de ralentir leur carrière.",
    question: "Pourquoi les pères utilisent-ils moins le congé parental selon le texte ?",
    options: [
      "Parce que la loi leur en refuse l'accès.",
      "Parce que le poste n'est pas protégé pendant leur absence.",
      "Parce qu'ils craignent les conséquences sur leur carrière et la culture du travail.",
      "Parce que les prestations sont plus faibles pour les hommes.",
    ],
    correctIndex: 2,
    explanation: "Fathers cite workplace culture and career fears.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Chronique",
    passage: "On parle beaucoup du « coût de la garderie », mais moins du coût de ne pas en avoir. Une mère qui renonce à un emploi à temps plein perd des cotisations retraite, des années d'expérience et parfois l'accès à une assurance collective. Le prix affiché d'une place en CPE n'épuise pas l'équation familiale.",
    question: "Quel argument l'auteur développe ?",
    options: [
      "Les garderies publiques sont toujours moins chères que les privées.",
      "Ne pas trouver de garde a aussi un coût économique pour la famille.",
      "Les pères devraient payer plus de taxes pour la petite enfance.",
      "Les CPE ferment trop tôt pour les parents qui travaillent.",
    ],
    correctIndex: 1,
    explanation: "Giving up work has hidden costs beyond daycare fees.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Guide pratique",
    passage: "Pour inscrire un enfant à l'école publique, les parents doivent prouver qu'ils résident dans la zone du conseil scolaire. Un bail, une facture d'électricité ou une déclaration d'impôt au nom du parent suffit souvent. Les enfants nés à l'étranger doivent aussi présenter leur statut de résident ou de citoyen.",
    question: "Que mentionne le guide pour les familles récemment arrivées ?",
    options: [
      "Qu'aucun document d'immigration n'est nécessaire.",
      "Que les enfants doivent parler anglais avant l'inscription.",
      "Qu'il faut montrer le statut de résident ou de citoyen pour les enfants nés à l'étranger.",
      "Que l'inscription se fait uniquement en janvier.",
    ],
    correctIndex: 2,
    explanation: "Children born abroad need proof of resident or citizen status.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Reportage",
    passage: "À Halifax, un centre communautaire propose des groupes de parole pour parents isolés. Les animateurs ne sont pas thérapeutes, mais ils orientent vers des services de santé mentale et des banques alimentaires. Les participants disent apprécier surtout de rencontrer d'autres parents dans la même situation linguistique.",
    question: "Quel besoin ces groupes comblent-ils surtout ?",
    options: [
      "Le remplacement des services psychologiques spécialisés.",
      "La solitude et le manque de pairs qui partagent la même langue.",
      "Le financement des études des enfants.",
      "L'obtention automatique de la citoyenneté.",
    ],
    correctIndex: 1,
    explanation: "Parents value meeting others in the same linguistic situation.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Les programmes de repas scolaires subventionnés visent les familles à revenu modeste, mais l'inscription passe souvent par un formulaire que les parents doivent renouveler chaque année. Les écoles qui envoient le document seulement en anglais voient moins de demandes de familles francophones ou allophones.",
    question: "Quel obstacle à l'accès est souligné ?",
    options: [
      "Le coût élevé des repas même subventionnés.",
      "La complexité administrative et la barrière linguistique.",
      "L'interdiction de repas végétariens.",
      "Le refus des écoles d'accueillir les nouveaux arrivants.",
    ],
    correctIndex: 1,
    explanation: "Annual forms and English-only communication reduce uptake.",
  },
  {
    id: 16,
    level: "B1",
    passageType: "Courrier des lecteurs",
    passage: "Votre article sur les CPE oublie les travailleuses de nuit. Une place de 7 h à 18 h ne sert à rien quand on termine à minuit. Les garderies en milieu familial ferment aussi tôt. On parle d'égalité hommes-femmes, mais sans garde adaptée, ce sont encore les mères qui renoncent aux quarts de soir.",
    question: "Que reproche le lecteur à l'article ?",
    options: [
      "D'avoir critiqué le rôle des CPE.",
      "D'avoir ignoré les familles aux horaires de travail atypiques.",
      "D'avoir surestimé le coût des garderies privées.",
      "D'avoir omis les statistiques sur la natalité.",
    ],
    correctIndex: 1,
    explanation: "The piece overlooks parents who work nights and need non-standard hours.",
  },
  {
    id: 17,
    level: "B1",
    passageType: "Note de service",
    passage: "À compter du 1er septembre, les demandes de place en garderie municipale se feront uniquement par le portail en ligne. Un guichet téléphonique reste ouvert pour les personnes sans accès Internet. Les dossiers incomplets seront classés sans suite ; aucune priorité ne sera accordée aux courriels de rappel.",
    question: "Que se passe-t-il si le dossier est incomplet ?",
    options: [
      "La ville contacte le parent pour compléter le dossier.",
      "Le dossier est classé sans suite.",
      "Le parent conserve sa place sur la liste d'attente.",
      "Les frais d'inscription sont remboursés.",
    ],
    correctIndex: 1,
    explanation: "Incomplete applications are closed with no follow-up priority.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Analyse",
    passage: "Les politiques de congé parental « utilisable par l'un ou l'autre parent » visent l'égalité, mais les données montrent que les ménages optimisent souvent le revenu le plus élevé. Si le père gagne davantage, c'est encore la mère qui reste à la maison, sauf lorsque des semaines réservées au père ne sont pas transférables et se perdent sinon.",
    question: "Quand l'égalité formelle produit-elle un partage réel selon le texte ?",
    options: [
      "Lorsque les deux parents ont le même salaire.",
      "Lorsque certaines semaines sont réservées au père et non transférables.",
      "Lorsque l'employeur impose le partage égal.",
      "Lorsque les prestations dépassent le salaire habituel.",
    ],
    correctIndex: 1,
    explanation: "Use-it-or-lose-it weeks for fathers change household decisions.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Éditorial",
    passage: "Subventionner les CPE réduit la facture pour les familles, mais ne crée pas de places instantanément. Les files d'attente reflètent un manque de personnel formé et de locaux. Baisser le prix sans augmenter l'offre déplace la frustration : on peut se permettre une place qui n'existe pas encore.",
    question: "Quel paradoxe l'auteur décrit-il ?",
    options: [
      "Les CPE coûtent plus cher que les garderies privées.",
      "Rendre la garde abordable n'augmente pas le nombre de places disponibles.",
      "Les parents préfèrent les garderies non subventionnées.",
      "Le personnel des CPE est trop nombreux.",
    ],
    correctIndex: 1,
    explanation: "Lower fees do not create more spots or trained staff.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "Les travailleuses sociales constatent que des familles immigrées refusent l'aide à domicile pour les aînés par crainte que cela nuise à une future demande de regroupement familial. Les brochures précisent que ces services sont distincts de l'immigration, mais la méfiance persiste lorsque l'évaluateur entre dans le salon sans médiation culturelle.",
    question: "Pourquoi certaines familles refusent-elles l'aide ?",
    options: [
      "Parce que les services ne sont pas traduits.",
      "Parce qu'elles ignorent l'existence des programmes.",
      "Parce qu'elles craignent un impact sur un dossier d'immigration.",
      "Parce que l'aide est réservée aux citoyens nés au Canada.",
    ],
    correctIndex: 2,
    explanation: "Fear of harming sponsorship files keeps families from accepting help.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Enquête",
    passage: "Dans deux provinces, des proches aidants peuvent recevoir un petit indemnité si l'aîné est évalué comme « dépendant ». Le montant reste inférieur au salaire d'une aide-soignante à temps partiel, et la paperasse décourage les familles qui travaillent déjà à temps plein tout en prodiguant des soins le soir.",
    question: "Quelle limite du programme est soulignée ?",
    options: [
      "Il est réservé aux résidents urbains.",
      "La compensation est faible et les démarches lourdes pour les aidants actifs.",
      "Il remplace entièrement les soins en résidence.",
      "Il est interdit aux personnes non citoyennes.",
    ],
    correctIndex: 1,
    explanation: "Low pay and heavy paperwork burden working family caregivers.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "On oppose garderie collective et garde en milieu familial comme si l'une devait éliminer l'autre. Les CPE offrent stabilité et pédagogie, les garderies familiales flexibilité pour les horaires irréguliers. Une politique cohérente subventionnerait les deux et rémunérerait correctement les gardennes à domicile, souvent invisibles dans les statistiques.",
    question: "Quelle conception de la politique familiale l'auteur défend-il ?",
    options: [
      "Fermer les garderies familiales au profit des CPE uniquement.",
      "Soutenir plusieurs modèles de garde et les travailleuses du secteur.",
      "Laisser le marché privé sans subvention.",
      "Réserver la garde subventionnée aux familles monoparentales.",
    ],
    correctIndex: 1,
    explanation: "He advocates subsidizing both CPEs and family daycare with fair pay.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Reportage",
    passage: "À Edmonton, un programme jumelle des grands-parents récemment immigrés avec des familles locales pour des sorties à la bibliothèque et au parc. Aucun curriculum formel : on échange sur les devoirs, les vaccins scolaires et les droits des aînés. Les participants disent avoir compris plus en une matinée qu'en lisant cinq dépliants.",
    question: "Qu'est-ce qui rend ce jumelage efficace ?",
    options: [
      "Les cours magistraux sur le système de santé.",
      "L'apprentissage concret entre pairs lors d'activités simples.",
      "La distribution de subventions en argent comptant.",
      "L'obligation de suivre un test de citoyenneté.",
    ],
    correctIndex: 1,
    explanation: "Practical peer learning during outings beats reading brochures.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Analyse juridique",
    passage: "Le droit à l'instruction en langue minoritaire au Canada protège certaines familles, mais les critères d'admissibilité varient selon que le parent a étudié en français ou l'a appris au Canada. Deux enfants du même quartier peuvent donc être orientés vers des écoles différentes, ce que les nouveaux parents peinent à anticiper lors de l'achat d'une maison.",
    question: "Quel problème ce passage met-il en évidence ?",
    options: [
      "L'interdiction totale des écoles francophones hors Québec.",
      "Des règles d'admissibilité complexes qui varient selon le parcours linguistique.",
      "Le refus d'inscrire les enfants immigrants.",
      "L'absence de droit à l'instruction en français dans la Charte.",
    ],
    correctIndex: 1,
    explanation: "Eligibility rules vary, producing unpredictable school assignments.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Les maisons de retraite publiques affichent des listes d'attente de plusieurs années, tandis que le secteur privé facture parfois plus de cinq mille dollars par mois. Les familles du milieu voient leurs économies fondre en finançant un parent à domicile puis une résidence. Le système suppose souvent qu'une fille réduira ses heures de travail sans compensation.",
    question: "Quelle injustice structurelle le texte souligne-t-il ?",
    options: [
      "Les aînés refusent toute forme d'aide publique.",
      "Le coût et l'attente poussent les filles à assumer les soins sans salaire.",
      "Les résidences privées sont toujours de mauvaise qualité.",
      "Les maisons publiques sont gratuites pour tous.",
    ],
    correctIndex: 1,
    explanation: "The gap between wait lists and private fees falls on unpaid female caregivers.",
  },
  {
    id: 26,
    level: "B2",
    passageType: "Chronique",
    passage: "Le « congé parental » ne devrait pas s'appeler ainsi pour les pères qui prennent deux semaines : c'est un congé de naissance déguisé. Tant que la société considère la garde des jeunes enfants comme une affaire de mères, les politiques qui réservent des semaines au père resteront symboliques. Le vrai changement passe par des places en garderie et des salaires équitables.",
    question: "Que critique l'auteur ?",
    options: [
      "La durée excessive du congé parental pour les mères.",
      "Le caractère symbolique des congés paternels sans infrastructure de garde.",
      "Le coût des places en garderie pour les célibataires.",
      "L'absence de congé pour les grands-parents.",
    ],
    correctIndex: 1,
    explanation: "Short father leaves stay symbolic without daycare and wage equality.",
  },
  {
    id: 27,
    level: "B2",
    passageType: "Dossier",
    passage: "Plusieurs villes testent des « hubs familiaux » où santé, garde temporaire et conseil en logement cohabitent sous un même toit. Les évaluations préliminaires montrent moins de rendez-vous manqués, mais le financement mêle fonds fédéraux, provinciaux et municipaux, ce qui complique la pérennité lorsque un bail arrive à échéance.",
    question: "Quel défi les hubs familiaux rencontrent-ils ?",
    options: [
      "Le refus des familles d'y entrer.",
      "La difficulté à maintenir le financement à long terme.",
      "L'interdiction légale de mélanger santé et garde.",
      "L'absence de personnel qualifié dans toutes les villes.",
    ],
    correctIndex: 1,
    explanation: "Mixed funding streams threaten sustainability when leases end.",
  },
  {
    id: 28,
    level: "B2",
    passageType: "Rapport",
    passage: "L'étude compare deux campagnes de dépistage de la maltraitance infantile : l'une ciblait les écoles, l'autre les centres communautaires. La première a augmenté les signalements en milieu scolaire, la seconde chez les familles récentes isolées linguistiquement. Aucune stratégie seule n'a couvert les deux publics, ce qui plaide pour des réseaux coordonnés.",
    question: "Quelle conclusion le rapport suggère-t-il ?",
    options: [
      "Il faut abandonner les campagnes en milieu scolaire.",
      "Il faut combiner plusieurs canaux pour toucher des familles différentes.",
      "Les centres communautaires sont inefficaces pour le dépistage.",
      "Les enseignants signalent trop de cas sans fondement.",
    ],
    correctIndex: 1,
    explanation: "Neither channel alone reached both groups; coordination is needed.",
  },
  {
    id: 29,
    level: "B2",
    passageType: "Essai",
    passage: "La famille n'est pas seulement un refuge privé : c'est un lieu où se distribuent les soins que l'État ne assume pas entièrement. Préparer les repas, accompagner aux rendez-vous, traduire les lettres officielles pour un parent âgé sont des travaux invisibles, surtout chez les migrantes. Parler de « conciliation famille-travail » sans les compter, c'est oublier la moitié de l'économie domestique.",
    question: "Quelle conception du rôle familial l'auteur défend-il ?",
    options: [
      "La famille doit rester totalement séparée de l'État.",
      "La famille fournit des soins essentiels que les politiques publiques sous-estiment.",
      "Seules les familles riches peuvent assumer les soins aux aînés.",
      "Le travail domestique n'a aucune valeur économique.",
    ],
    correctIndex: 1,
    explanation: "Families perform unpaid care that public policy fails to account for.",
  },

  // ── C1–C2 (Q30–39) ─────────────────────────────────────────────
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "Les politiques de garde subventionnée visent l'égalité d'accès et l'égalité femmes-hommes, mais les évaluations longitudinales les mesurent souvent avec le même indicateur : taux d'emploi féminin. Or une mère peut travailler plus sans que le père partage les tâches domestiques, et inversement. Confondre emploi et répartition des soins conduit à déclarer victorieuse une réforme qui déplace seulement la charge vers les grands-parents immigrés.",
    question: "Quelle erreur méthodologique l'auteur dénonce-t-il ?",
    options: [
      "L'absence de données sur les salaires masculins.",
      "L'usage du seul emploi féminin pour juger l'égalité au sein du foyer.",
      "Le refus de subventionner les garderies privées.",
      "L'ignorance totale des listes d'attente.",
    ],
    correctIndex: 1,
    explanation: "Female employment alone does not measure sharing of care within households.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Analyse politique",
    passage: "La compétence fédérale-provinciale en matière sociale fait de chaque parent un interlocuteur multiple : Ottawa pour certaines prestations, la province pour la santé et l'éducation, la ville pour les loisirs et parfois la garde. Cette fragmentation n'est pas un accident : elle reflète des compromis constitutionnels. Elle produit pourtant une charge cognitive élevée lors d'une naissance ou d'un déclin de santé d'un aîné.",
    question: "Quel effet cette fragmentation a-t-elle sur les familles ?",
    options: [
      "Elle supprime les différences entre provinces.",
      "Elle exige de naviguer entre plusieurs niveaux de gouvernement en période de crise.",
      "Elle réduit le nombre de services offerts aux enfants.",
      "Elle interdit les recours contre les décisions scolaires.",
    ],
    correctIndex: 1,
    explanation: "Families must navigate many government levels during births or elder care crises.",
  },
  {
    id: 32,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Elle rangeait les formulaires de garderie à côté des biberons, comme si les deux nourrissaient l'enfant. Chaque case cochée était une promesse que quelqu'un, quelque part, lui permettrait de retrouver son bureau. Quand le courriel de refus arriva, ce n'était pas une place qui manquait : c'était un morceau de son nom de famille qu'on lui demandait encore de suspendre.",
    question: "Quel rapport le personnage entretient-il avec la démarche de garderie ?",
    options: [
      "Elle la considère comme une formalité sans importance émotionnelle.",
      "Elle y voit la condition de préserver son identité professionnelle et familiale.",
      "Elle refuse d'inscrire son enfant par principe politique.",
      "Elle a déjà obtenu une place et ignore le courriel.",
    ],
    correctIndex: 1,
    explanation: "Daycare paperwork represents her hold on work and family identity.",
  },
  {
    id: 33,
    level: "C1",
    passageType: "Article académique",
    passage: "Les consultations sur de nouveaux quartiers « familiaux » présentent souvent des plans déjà arrêtés : nombre de CPE, largeur des trottoirs, mixité locative. Les parents peuvent commenter, non décider. L'enjeu n'est pas de supprimer la concertation, mais de clarifier ce qu'elle peut modifier, faute de quoi elle transforme la colère des listes d'attente en défiance envers toute planification urbaine.",
    question: "Quelle critique l'auteur adresse-t-il aux consultations ?",
    options: [
      "Elles coûtent trop cher pour les municipalités.",
      "Elles créent l'illusion d'une influence réelle sur des décisions déjà prises.",
      "Elles sont interdites lorsque des écoles sont concernées.",
      "Elles retardent toujours inutilement la construction de logements.",
    ],
    correctIndex: 1,
    explanation: "Parents can comment but not change plans, fuelling distrust.",
  },
  {
    id: 34,
    level: "C1",
    passageType: "Essai",
    passage: "Parler de « choix » en matière de garde suppose que les parents disposent d'options comparables. Les revenus du travail sont stables ; ceux de la garde en milieu familial dépendent de subventions retardées et de quotas d'enfants. Tant que la structure publique traite différemment ces flux, défendre la liberté de choix sans harmoniser les compensations revient à valoriser surtout les familles qui peuvent attendre une place subventionnée.",
    question: "Quel obstacle à un vrai « choix » le texte souligne-t-il ?",
    options: [
      "Le refus des parents d'utiliser les CPE.",
      "Le traitement inégal des revenus salariaux et des revenus de garde subventionnée.",
      "L'absence totale de garderies privées.",
      "La complexité des formulaires pour les petits enfants.",
    ],
    correctIndex: 1,
    explanation: "Unequal treatment of wage and caregiving income limits real choice.",
  },
  {
    id: 35,
    level: "C1",
    passageType: "Article académique",
    passage: "Le concept de « reconnaissance » des aidants familiaux ne désigne pas seulement un chèque mensuel. Il concerne la capacité d'un État à dire que ces heures de soin comptent dans le récit national du travail. Refuser une indemnité significative, ce n'est pas nier l'amour familial ; c'est signaler que ce travail reste hors de l'histoire officielle de la contribution citoyenne.",
    question: "Que signifie une indemnité faible selon le texte ?",
    options: [
      "Qu'on interdit aux familles de soigner leurs proches.",
      "Qu'on exclut ce travail du récit officiel de la contribution sociale.",
      "Qu'on reconnaît pleinement la valeur des aidants.",
      "Qu'on transfère tous les soins au secteur privé.",
    ],
    correctIndex: 1,
    explanation: "Low pay signals unpaid care stays outside the official story of work.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Extrait philosophique",
    passage: "Aimer son enfant et assumer seule quinze ans de logistique scolaire ne sont pas la même vertu. La mère moderne est censée incarner les deux, mais les services publics supposent encore qu'une adulte « disponible » absorbera les créneaux que l'école ne couvre pas. La justice familiale naît lorsque l'institution cesse de naturaliser cette disponibilité comme un don gratuit du genre féminin.",
    question: "Quel décalage l'auteur décrit-il ?",
    options: [
      "Entre écoles publiques et écoles privées.",
      "Entre l'idéal du soin parental choisi et l'attente implicite de travail domestique féminin non payé.",
      "Entre congé parental et congé de maladie.",
      "Entre citoyens nés au pays et immigrés.",
    ],
    correctIndex: 1,
    explanation: "Institutions assume women's unpaid availability for school logistics.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "La solidarité intergénérationnelle est souvent pensée comme un transfert d'argent public vers les retraités. Les théories du care rappellent qu'elle circule aussi en sens inverse : grands-parents qui gardent les petits-enfants, enfants qui traduisent les formulaires médicaux. Un budget qui ne comptabilise que les pensions oublie cette économie invisible qui soutient pourtant l'emploi des parents actifs.",
    question: "Quel angle mort budgétaire le texte met-il en évidence ?",
    options: [
      "Les retraités paient trop d'impôts.",
      "Le travail de care non rémunéré qui permet aux parents de travailler.",
      "Les pensions sont trop élevées pour les jeunes.",
      "Les grands-parents refusent de garder les enfants.",
    ],
    correctIndex: 1,
    explanation: "Unpaid intergenerational care enables parents' paid work but is omitted from budgets.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai critique",
    passage: "On demande aux nouvelles familles immigrées de confier leurs enfants à des institutions dont les règles de discipline et de nutrition diffèrent de celles du pays d'origine, tout en leur rappelant que l'intégration passe par l'école. La garderie célèbre l'adaptation ; le foyer exige la transmission. Tenir les deux registres sans les confronter, c'est offrir une parentalité publique normée et une parentalité privée héritée que peu de politiques articulent.",
    question: "Quelle tension le texte souligne-t-il ?",
    options: [
      "Entre l'apprentissage du français et de l'anglais à l'école.",
      "Entre normes institutionnelles de garde et transmission culturelle familiale.",
      "Entre congé parental et retour au travail.",
      "Entre garderies urbaines et rurales.",
    ],
    correctIndex: 1,
    explanation: "Public daycare norms clash with private cultural transmission at home.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article spécialisé",
    passage: "Évaluer la « qualité » des services à la petite enfance par des ratios d'encadrement suppose que la relation éducative se réduit à un nombre d'adultes par enfant. Les études ethnographiques montrent plutôt un effet de contexte : stabilité des éducatrices, langue d'accueil, lien avec les familles. Les réformes qui ne financent que les places sans la formation continue peinent à améliorer l'expérience réelle, car ce n'est pas un indicateur qui est en cause, mais la conception même de la qualité.",
    question: "Pourquoi les réformes centrées sur les ratios ont-elles un effet limité ?",
    options: [
      "Parce que les parents ne visitent jamais les CPE.",
      "Parce que la qualité dépend de facteurs relationnels que les ratios ne capturent pas.",
      "Parce que les éducatrices refusent toute formation.",
      "Parce que la qualité ne peut jamais être mesurée.",
    ],
    correctIndex: 1,
    explanation: "Relational factors exceed staffing ratios as measures of quality.",
  },
];
