import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 10 — Compréhension écrite. Theme: culture, leisure and social integration in Canada.
 *
 * Hand-authored to keep distractors plausible and similar in length, so no
 * surface heuristic (longest option, option B) beats reading the text.
 */
export const TCF_READING_P10: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "FESTIVAL D'ÉTÉ — PARC RIVERSIDE\nEntrée gratuite — 14 h à 23 h\nScène principale : musique locale\nStands : nourriture et artisanat\nApportez votre chaise pliante",
    question: "À quelle heure se termine le festival ?",
    options: ["À midi.", "À 18 h.", "À 23 h.", "À minuit."],
    correctIndex: 2,
    explanation: "The sign runs until 11 p.m. (23 h).",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Horaires",
    passage: "PATINOIRE MUNICIPALE — HIVER\nLundi au jeudi : 12 h – 21 h\nVendredi et samedi : 10 h – 22 h\nDimanche : 11 h – 20 h\nLocation de patins : cinq dollars l'heure",
    question: "Quand la patinoire ouvre-t-elle le dimanche ?",
    options: ["À 10 h.", "À 11 h.", "À 12 h.", "À 21 h."],
    correctIndex: 1,
    explanation: "Sunday hours start at 11 a.m.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Salut Priya,\nLe club de course du quartier s'entraîne samedi à 8 h au parc Maple. C'est gratuit pour les nouveaux membres ce mois-ci. Apporte des chaussures confortables et une bouteille d'eau.\nMarc",
    question: "Que doit apporter Priya ?",
    options: ["Des patins à glace.", "Des chaussures confortables et de l'eau.", "Une inscription payante.", "Un certificat médical."],
    correctIndex: 1,
    explanation: "Marc asks for comfortable shoes and a water bottle.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "BIBLIOTHÈQUE — SOIRÉE JEUX DE SOCIÉTÉ\nMercredi 19 h – 21 h, salle des loisirs\nTous les âges — accueil bilingue français-anglais\nInscription sur place, places limitées",
    question: "Quelle langue est mentionnée à l'accueil ?",
    options: ["Uniquement le français.", "Le français et l'anglais.", "Uniquement l'anglais.", "L'espagnol et le français."],
    correctIndex: 1,
    explanation: "The event offers bilingual French-English welcome.",
  },
  {
    id: 5,
    level: "A2",
    passageType: "Courriel",
    passage: "Objet : Confirmation — bénévolat au festival\n\nBonjour,\nMerci pour votre candidature. Vous êtes assigné au stand d'information le samedi 8 juin de 13 h à 17 h. Une formation de trente minutes aura lieu à 12 h 30 devant la tente jaune. Prévoyez un vêtement chaud pour la soirée.\nÉquipe des loisirs",
    question: "Où la formation aura-t-elle lieu ?",
    options: ["À la bibliothèque municipale.", "Devant la tente jaune.", "Au stand de nourriture.", "Dans la salle des loisirs."],
    correctIndex: 1,
    explanation: "Training is at 12:30 in front of the yellow tent.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Note d'information",
    passage: "CENTRE COMMUNAUTAIRE — COURS DE SKI DE FOND\nInitiation pour débutants — samedis en janvier\nÉquipement en prêt gratuit (réservation obligatoire)\nPlaces : quinze personnes par groupe\nInscription en ligne ou par téléphone",
    question: "Comment obtenir l'équipement ?",
    options: ["En l'achetant sur place.", "En le réservant à l'avance.", "En apportant le sien uniquement.", "En payant un dépôt de cent dollars."],
    correctIndex: 1,
    explanation: "Free loan equipment requires advance reservation.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Affiche",
    passage: "MATCH BENEVOLE — LIGUE AMATEUR DE SOCCER\nRecrutement d'arbitres et d'accueil\nFormation offerte — aucune expérience requise\nEngagement : un match par semaine, mai à août\nContact : loisirs@ville.ca",
    question: "De quoi l'affiche parle-t-elle ?",
    options: ["D'un tournoi professionnel payant.", "D'une recherche de bénévoles pour le soccer.", "D'une vente de maillots officiels.", "D'un cours de natation estival."],
    correctIndex: 1,
    explanation: "The poster recruits volunteer referees and greeters.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "SMS",
    passage: "Rappel Ville de Moncton : la patinoire extérieure ferme si la température dépasse cinq degrés au-dessus de zéro. Vérifiez le site avant de vous déplacer ce week-end.",
    question: "Pourquoi la patinoire pourrait-elle fermer ?",
    options: ["Par manque de bénévoles.", "Si la température est trop douce.", "À cause d'un match de hockey.", "Pour travaux le week-end."],
    correctIndex: 1,
    explanation: "It closes when temperature goes above five degrees Celsius.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Formulaire",
    passage: "INSCRIPTION — CLUB DE LECTURE BILINGUE\nÉtape 1 : remplir le formulaire en ligne\nÉtape 2 : choisir un créneau (mardi ou jeudi soir)\nÉtape 3 : assister à la rencontre d'accueil du 3 octobre\nParticipation gratuite — carte de bibliothèque requise",
    question: "Que faut-il avoir pour participer ?",
    options: ["Une carte de bibliothèque.", "Un abonnement payant au club.", "Un certificat de français avancé.", "Une recommandation d'un professeur."],
    correctIndex: 0,
    explanation: "A library card is required.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Courriel",
    passage: "Bonjour M. Okada,\nVotre groupe de marche nordique est confirmé pour les jeudis à 18 h. Le rendez-vous est au pavillon du parc Lafontaine. En cas de pluie, la séance est reportée au gymnase voisin ; vous recevrez un courriel avant 17 h.\nCordialement,\nLe service des loisirs",
    question: "Où se tient l'activité par beau temps ?",
    options: ["Au gymnase voisin.", "Au pavillon du parc Lafontaine.", "À la bibliothèque.", "Au centre aquatique."],
    correctIndex: 1,
    explanation: "Meet at Lafontaine park pavilion; gym only if it rains.",
  },

  // ── B1–B2 (Q11–29) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Les bibliothèques canadiennes ne se limitent plus aux livres : ateliers numériques, clubs de conversation, prêt d'outils et refuges thermiques l'hiver. Pour beaucoup de nouveaux résidents, la carte de bibliothèque est le premier « abonnement » gratuit qui ouvre des portes sociales sans exiger un réseau professionnel.",
    question: "Quel rôle social les bibliothèques jouent-elles selon le texte ?",
    options: [
      "Elles remplacent les centres d'emploi.",
      "Elles offrent des activités accessibles pour élargir les contacts.",
      "Elles réservent leurs services aux citoyens canadiens.",
      "Elles ferment l'hiver faute de budget.",
    ],
    correctIndex: 1,
    explanation: "Libraries provide free activities that help newcomers meet people.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Chronique",
    passage: "On dit que le hockey unit le Canada. En réalité, c'est souvent le bénévolat dans un tournoi local qui crée les premiers liens : distribuer des dossards, guider un parent perdu dans le gymnase. Le sport spectacle reste à la télé ; le sport de quartier, lui, se vit dans les couloirs et les vestiaires.",
    question: "Selon l'auteur, où naissent surtout les liens sociaux ?",
    options: [
      "En regardant les matchs professionnels.",
      "En participant aux activités locales et bénévoles.",
      "En achetant des billets pour la LNH.",
      "En suivant des cours théoriques sur le sport.",
    ],
    correctIndex: 1,
    explanation: "Local volunteering at tournaments builds first connections.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Guide pratique",
    passage: "Pour profiter des festivals d'hiver, habillez-vous en couches, protégez vos extrémités et prévoyez une boisson chaude. Les organisateurs proposent souvent des zones chauffées et des navettes gratuites depuis certains quartiers. Consulter le programme en ligne évite les files aux guichets.",
    question: "Quel conseil le guide donne-t-il pour l'organisation ?",
    options: [
      "Arriver sans billet pour économiser.",
      "Vérifier le programme sur Internet à l'avance.",
      "Éviter les zones chauffées qui sont payantes.",
      "Ne pas utiliser les navettes municipales.",
    ],
    correctIndex: 1,
    explanation: "Checking the programme online avoids ticket lines.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Reportage",
    passage: "À Edmonton, une soirée bilingue mensuelle mêle contes pour enfants, dégustation et mini-conférences sur les traditions hivernales. Les familles allophones disent y avoir rencontré des voisins qu'elles croisent désormais à la patinoire. L'événement est gratuit, mais l'inscription permet d'ajuster la taille des groupes.",
    question: "Pourquoi l'inscription est-elle demandée ?",
    options: [
      "Pour financer les artistes invités.",
      "Pour adapter la taille des groupes.",
      "Pour limiter l'accès aux citoyens canadiens.",
      "Pour remplacer la carte de bibliothèque.",
    ],
    correctIndex: 1,
    explanation: "Registration helps organizers adjust group sizes.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Les clubs de course à pied accueillent de plus en plus de membres récents. Courir côte à côte réduit la pression de « bien parler » : le rythme et les signaux de la main suffisent au début. Plusieurs groupes proposent un parcours court pour les débutants et un café après l'effort.",
    question: "Quel avantage social la course présente-t-elle ?",
    options: [
      "Elle exige un français parfait dès la première séance.",
      "Elle permet d'échanger sans longues conversations au départ.",
      "Elle est réservée aux coureurs expérimentés.",
      "Elle remplace les cours de français officiels.",
    ],
    correctIndex: 1,
    explanation: "Running together eases contact before long conversations.",
  },
  {
    id: 16,
    level: "B1",
    passageType: "Courrier des lecteurs",
    passage: "Votre article sur les festivals d'été oublie les travailleurs de nuit. Les concerts finissent tard, mais les navettes s'arrêtent tôt. On parle d'intégration culturelle, mais on organise des horaires pour des familles qui dorment à des heures « normales ». Les loisirs publics devraient aussi penser à ceux qui vivent décalés.",
    question: "Que reproche le lecteur à l'article ?",
    options: [
      "D'avoir critiqué la musique locale.",
      "D'avoir ignoré les contraintes horaires de certains publics.",
      "D'avoir surestimé le coût des festivals.",
      "D'avoir omis les statistiques de fréquentation.",
    ],
    correctIndex: 1,
    explanation: "He says events ignore night workers when transit ends early.",
  },
  {
    id: 17,
    level: "B1",
    passageType: "Note de service",
    passage: "À compter de décembre, les prêts d'équipement hivernal (raquettes, crampons) se feront uniquement sur réservation en ligne. Le comptoir de la bibliothèque reste disponible pour les personnes sans accès Internet, sur rendez-vous. Les retards entraînent une suspension de deux semaines du prêt.",
    question: "Que se passe-t-il en cas de retard de retour ?",
    options: [
      "Une amende automatique de cent dollars.",
      "Une suspension de prêt pendant deux semaines.",
      "La perte définitive de la carte de bibliothèque.",
      "Un report gratuit sans limite.",
    ],
    correctIndex: 1,
    explanation: "Late returns trigger a two-week borrowing suspension.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Analyse",
    passage: "Les municipalités financent des festivals pour « animer » le centre-ville, mais l'effet d'intégration dépend de qui se sent invité. Des programmations uniquement en anglais, des prix élevés à la nourriture et l'absence de transports en soirée reproduisent les exclusions du marché du travail, cette fois dans l'espace festif.",
    question: "Quel argument l'auteur développe-t-il ?",
    options: [
      "Les festivals coûtent toujours plus que les bibliothèques.",
      "L'accueil festif peut exclure si langue, prix et horaires ne sont pas pensés.",
      "Les nouveaux résidents détestent les grands événements.",
      "Les transports gratuits résolvent tous les problèmes culturels.",
    ],
    correctIndex: 1,
    explanation: "Language, food prices, and transit can replicate social exclusion.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Éditorial",
    passage: "Exiger des heures de bénévolat pour accéder à certains programmes sportifs subventionnés divise les associations. D'un côté, on valorise l'engagement civique ; de l'autre, on pénalise les parents à horaires imprévisibles qui voudraient simplement inscrire un enfant. Le débat oppose mérite et disponibilité calendaire.",
    question: "Quel conflit le texte décrit-il ?",
    options: [
      "Entre sport professionnel et sport amateur.",
      "Entre valorisation du bénévolat et contraintes de temps des familles.",
      "Entre patinoires intérieures et extérieures.",
      "Entre français et anglais dans les clubs.",
    ],
    correctIndex: 1,
    explanation: "Volunteer hours as a condition clash with unpredictable work schedules.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "Les « buddy programs » jumellent un nouvel arrivant avec un résident pour assister ensemble à un match, un atelier ou une séance de patinage. Aucun curriculum formel : l'objectif est de transformer un loisir public en rituel partagé. Les évaluations montrent surtout un gain de confiance pour demander des services ensuite.",
    question: "Quel effet principal ces programmes produisent-ils ?",
    options: [
      "Une maîtrise immédiate du français écrit.",
      "Une plus grande confiance pour d'autres démarches.",
      "L'obtention automatique d'un emploi local.",
      "La fin des besoins en interprétation médicale.",
    ],
    correctIndex: 1,
    explanation: "Participants gain confidence to seek other services afterward.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Enquête",
    passage: "Dans trois villes, les bibliothèques ont testé des « passes culture » : cinq activités gratuites par an (musée, théâtre, patinoire). La fréquentation des ateliers de conversation a augmenté, car les cartes se distribuaient lors des clubs de lecture. L'effet n'est pas magique, mais il relie loisir et apprentissage linguistique.",
    question: "Comment les passes ont-elles été distribuées efficacement ?",
    options: [
      "Uniquement par courrier à domicile.",
      "Lors des clubs de lecture à la bibliothèque.",
      "À la sortie des matchs professionnels.",
      "Par les employeurs uniquement.",
    ],
    correctIndex: 1,
    explanation: "Cards were given out at library reading clubs, boosting attendance.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "On oppose parfois culture « haute » et loisirs populaires comme si les nouveaux résidents devaient choisir. Or une soirée de slam bilingue au centre communautaire peut être la porte d'entrée vers le théâtre municipal. L'intégration culturelle progresse par des échelons, pas par une hiérarchie imposée.",
    question: "Quelle conception de la culture l'auteur défend-il ?",
    options: [
      "Il faut d'abord maîtriser le théâtre classique.",
      "Les loisirs populaires peuvent mener vers d'autres formes culturelles.",
      "Seuls les festivals d'été favorisent l'intégration.",
      "La culture doit rester séparée des activités sportives.",
    ],
    correctIndex: 1,
    explanation: "Community slam can lead newcomers toward municipal theatre.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Reportage",
    passage: "À Winnipeg, un réseau de patinoires extérieures offre des « heures d'accueil » avec patins à prêter et bénévoles qui expliquent les règles de base. Les familles récentes disent avoir appris le vocabulaire du hockey en jouant, pas en regardant un cours magistral. L'hiver devient une saison de rencontres, pas seulement de froid.",
    question: "Qu'est-ce qui rend l'initiative efficace selon les familles ?",
    options: [
      "Des cours théoriques sur l'histoire du hockey.",
      "L'apprentissage pratique sur la glace avec du matériel prêté.",
      "L'obligation d'acheter un équipement complet.",
      "La fermeture des patinoires intérieures payantes.",
    ],
    correctIndex: 1,
    explanation: "They learn hockey vocabulary by skating with loaner equipment.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Analyse sociologique",
    passage: "Les associations sportives amateurs reproduisent parfois les cliques du pays d'origine : même langue dans le vestiaire, mêmes invitations. Les ligues qui imposent des tirages au sort pour former les équipes ou qui mélangent les niveaux de français réduisent ces effets, au prix d'une organisation plus lourde pour les entraîneurs bénévoles.",
    question: "Quel problème les ligues tentent-elles de limiter ?",
    options: [
      "Le manque d'équipement hivernal.",
      "La formation de groupes fermés par langue ou origine.",
      "L'absence totale de règles officielles.",
      "Le refus des municipalités de financer le sport.",
    ],
    correctIndex: 1,
    explanation: "Random team formation counters locker-room language cliques.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Les budgets participatifs municipaux laissent parfois voter pour un mural ou un skatepark, mais rarement pour prolonger les heures d'ouverture des bibliothèques le soir. Les projets visibles gagnent ; les besoins invisibles — un accueil chaleureux après le travail — peinent à mobiliser, reproduisant les biais de l'attention publique.",
    question: "Quelle limite des budgets participatifs est soulignée ?",
    options: [
      "Ils interdisent les projets culturels.",
      "Ils favorisent les aménagements visibles au détriment de services discrets.",
      "Ils excluent les personnes sans permis de conduire.",
      "Ils ne concernent que les quartiers centraux.",
    ],
    correctIndex: 1,
    explanation: "Visible projects win over less visible needs like library evening hours.",
  },
  {
    id: 26,
    level: "B2",
    passageType: "Chronique",
    passage: "Le « tourisme social » consiste à inviter des nouveaux résidents à découvrir gratuitement un musée, un match amateur ou une randonnée guidée. Ce n'est pas du loisir de luxe : c'est une politique publique qui dit « ce territoire est aussi le vôtre ». Sans suivi, l'effet s'éteint ; avec un club mensuel, il devient habitude.",
    question: "Que critique l'auteur si l'initiative s'arrête trop tôt ?",
    options: [
      "Que les musées sont trop chers.",
      "Que l'effet d'appartenance disparaît sans continuité.",
      "Que les randonnées sont dangereuses l'hiver.",
      "Que le tourisme social remplace l'emploi.",
    ],
    correctIndex: 1,
    explanation: "Without follow-up clubs, the sense of belonging fades.",
  },
  {
    id: 27,
    level: "B2",
    passageType: "Dossier",
    passage: "Plusieurs villes testent des cartes « loisirs » pour familles à bas revenu : accès réduit aux piscines, patinoires et camps d'été. Les opposants estiment que cela stigmatise ; les partisans répondent que la tarification sociale existe déjà pour le transport. Le débat porte sur la visibilité de la pauvreté dans les files d'accès.",
    question: "Quel argument les partisans utilisent-ils ?",
    options: [
      "Que les piscines devraient être entièrement gratuites pour tous.",
      "Que des tarifs sociaux existent déjà dans d'autres services publics.",
      "Que les familles riches ne utilisent pas les loisirs municipaux.",
      "Que les camps d'été sont inutiles pour l'intégration.",
    ],
    correctIndex: 1,
    explanation: "They compare to existing social pricing on transit.",
  },
  {
    id: 28,
    level: "B2",
    passageType: "Rapport",
    passage: "L'étude compare deux stratégies d'intégration par le loisir : festivals grand public et micro-activités de quartier. La première augmente la fierté locale chez les résidents de longue date ; la seconde crée plus de liens interpersonnels chez les arrivants récents. Aucune ne suffit seule ; les municipalités gagnent à les articuler.",
    question: "Quelle conclusion le rapport suggère-t-il ?",
    options: [
      "Il faut abandonner les grands festivals.",
      "Il faut combiner grands événements et activités de proximité.",
      "Les micro-activités n'intéressent pas les citoyens nés au pays.",
      "Seuls les festivals génèrent de la fierté locale.",
    ],
    correctIndex: 1,
    explanation: "Large festivals and neighbourhood activities complement each other.",
  },
  {
    id: 29,
    level: "B2",
    passageType: "Essai",
    passage: "L'intégration n'est pas seulement un parcours administratif : elle se joue dans le temps libre partagé. Refuser aux nouveaux résidents des places abordables au sport ou des horaires de bibliothèque adaptés, c'est les laisser vivre à côté de la communauté tout en portant le même titre de résident permanent.",
    question: "Quelle conception de l'intégration l'auteur défend-il ?",
    options: [
      "Une intégration limitée aux documents officiels.",
      "Une intégration qui passe aussi par l'accès aux loisirs collectifs.",
      "Une intégration réservée aux personnes bilingues.",
      "Une intégration fondée uniquement sur le marché du travail.",
    ],
    correctIndex: 1,
    explanation: "Integration includes affordable leisure and library access, not only paperwork.",
  },

  // ── C1–C2 (Q30–39) ─────────────────────────────────────────────
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "Les politiques culturelles mesurent souvent la fréquentation des institutions, pas la densité des relations nouées. Or un festival peut attirer dix mille visiteurs sans produire un seul lien durable si les interactions restent anonymes. Confondre audience et intégration conduit à financer des événements spectaculaires au détriment des espaces de répétition sociale.",
    question: "Quelle erreur les politiques commettent-elles selon l'auteur ?",
    options: [
      "Elles ignorent totalement les festivals.",
      "Elles confondent nombre de participants et liens sociaux durables.",
      "Elles réservent la culture aux universités.",
      "Elles interdisent les activités bilingues.",
    ],
    correctIndex: 1,
    explanation: "Attendance metrics miss whether relationships actually form.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Analyse culturelle",
    passage: "Le bénévolat sportif est présenté comme vecteur d'intégration, mais il suppose du temps disponible et une acceptation des hiérarchies du club. Les travailleurs précaires y participent moins, non par désintérêt, mais parce que leurs horaires ne coïncident pas avec les réunions d'entraîneurs. Mesurer l'engagement sans mesurer le temps libre réel produit des politiques aveugles.",
    question: "Quel biais l'auteur souligne-t-il ?",
    options: [
      "Les clubs sportifs refusent les immigrants.",
      "L'engagement bénévole est évalué sans tenir compte des contraintes horaires.",
      "Le sport amateur est interdit aux nouveaux arrivants.",
      "Les entraîneurs sont tous payés à plein temps.",
    ],
    correctIndex: 1,
    explanation: "Volunteer metrics ignore precarious workers' schedules.",
  },
  {
    id: 32,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Elle tenait sa carte de bibliothèque comme un talisman, plastifiée, froissée aux coins. Chaque mercredi, le club de lecture était sa preuve qu'elle habitait vraiment cette ville, pas seulement un appartement chauffé. Les romans qu'elle empruntait parlaient d'autres vies ; les voix autour de la table, de la sienne.",
    question: "Quel rapport le personnage entretient-il avec le club de lecture ?",
    options: [
      "Il le voit comme une simple formalité administrative.",
      "Il y trouve un signe d'appartenance à la ville et un espace pour sa voix.",
      "Il refuse d'emprunter des livres en français.",
      "Il préfère rester silencieux à chaque séance.",
    ],
    correctIndex: 1,
    explanation: "The club proves she truly lives in the city and lets her speak.",
  },
  {
    id: 33,
    level: "C1",
    passageType: "Article académique",
    passage: "Les soirées bilingues « célèbrent la diversité » tout en imposant parfois un rythme où l'anglais domine les annonces et le français les ateliers secondaires. L'enjeu n'est pas d'ajouter une traduction, mais de concevoir des formats où les deux langues partagent la scène et le temps de parole, faute de quoi l'intégration linguistique reste décorative.",
    question: "Quelle critique l'auteur adresse-t-il aux soirées bilingues ?",
    options: [
      "Elles coûtent trop pour les bibliothèques.",
      "Elles peuvent reproduire une hiérarchie entre langues sur scène.",
      "Elles sont interdites dans les écoles publiques.",
      "Elles retardent toujours les spectacles de musique.",
    ],
    correctIndex: 1,
    explanation: "Bilingual events may still privilege one language on stage.",
  },
  {
    id: 34,
    level: "C1",
    passageType: "Essai",
    passage: "Parler de « loisirs inclusifs » suppose que l'inclusion soit mesurable : fauteuils roulants à la patinoire, tarifs sociaux, programmation sans alcool. Pourtant l'inclusion affective — se sentir attendu, pas toléré — échappe aux checklists. Tant que les espaces festifs n'accueillent pas explicitement les corps et les accents « hors norme », les indicateurs de fréquentation masquent des silences.",
    question: "Quel obstacle à l'inclusion le texte souligne-t-il ?",
    options: [
      "Le refus des municipalités d'installer des rampes.",
      "La différence entre accessibilité matérielle et sentiment d'être réellement accueilli.",
      "L'absence totale de festivals en hiver.",
      "La complexité des formulaires de bénévolat.",
    ],
    correctIndex: 1,
    explanation: "Checklists miss whether people feel genuinely welcomed.",
  },
  {
    id: 35,
    level: "C1",
    passageType: "Article académique",
    passage: "Le concept de « capital social » en sociologie ne désigne pas seulement le nombre d'amis, mais la confiance pour mobiliser un réseau. Les activités de loisir créent ce capital lorsqu'elles se répètent et se recoupent. Un festival annuel unique peut émouvoir ; il ne remplace pas les institutions du quotidien — bibliothèque, club, patinoire — où les rencontres s'accumulent.",
    question: "Que distingue l'auteur entre festival annuel et institutions du quotidien ?",
    options: [
      "Les festivals sont toujours gratuits.",
      "Seules les institutions répétées construisent un capital social durable.",
      "Les bibliothèques ferment pendant les festivals.",
      "Le capital social ne concerne pas les immigrants.",
    ],
    correctIndex: 1,
    explanation: "Repeated everyday institutions build trust networks; one-off festivals less so.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Extrait philosophique",
    passage: "Jouer ensemble suppose accepter des règles communes, mais aussi tolérer la défaite et l'aisance d'autrui. Le loisir sportif expose ainsi une version miniature de la vie civique : on ne choisit pas toujours ses coéquipiers, on négocie, on recommence. Réduire le sport à de la consommation spectaculaire, c'est retirer cette école informelle de la coexistence.",
    question: "Quel lien l'auteur établit-il entre sport amateur et civisme ?",
    options: [
      "Le sport professionnel remplace les institutions politiques.",
      "La pratique partagée enseigne coexistence et règles comme une micro-société.",
      "Seuls les arbitres bénévoles sont de vrais citoyens.",
      "Le loisir doit être interdit aux enfants immigrés.",
    ],
    correctIndex: 1,
    explanation: "Amateur sport mirrors civic life through shared rules and negotiation.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "Les villes nordiques investissent dans le « design hivernal » pour rendre le froid habitable : lumières, abris, boissons chaudes. Cet investissement est parfois présenté comme neutre, mais il oriente qui ose sortir après le travail. Quand les femmes seules ou les familles monoparentales évitent encore les parcs glacés, le confort urbain reste une promesse inégalement reçue.",
    question: "Quel paradoxe le texte met-il en évidence ?",
    options: [
      "L'hiver disparaît avec le réchauffement climatique.",
      "Les aménagements hivernaux prétendent être neutres mais favorisent certains publics.",
      "Les patinoires sont toujours plus fréquentées que les bibliothèques.",
      "Le design hivernal interdit les festivals de nuit.",
    ],
    correctIndex: 1,
    explanation: "Winter comfort investments claim neutrality yet some groups still stay away.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai critique",
    passage: "On demande aux nouveaux résidents de « participer » à la vie locale tout en réservant les postes de direction des festivals à des bénévoles installés depuis vingt ans. La participation devient alors une présence décorative : servir le café, pas choisir la programmation. Tenir les deux registres — accueil chaleureux et pouvoir de décision — sans les confronter, c'est offrir une intégration sentimentale sans intégration politique.",
    question: "Quelle tension le texte souligne-t-il ?",
    options: [
      "Entre ski de fond et hockey sur glace.",
      "Entre participation symbolique et pouvoir réel sur la programmation.",
      "Entre bibliothèques urbaines et rurales.",
      "Entre français québécois et français international.",
    ],
    correctIndex: 1,
    explanation: "Newcomers are asked to participate but excluded from programming power.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article spécialisé",
    passage: "Évaluer l'intégration par le taux de fréquentation des loisirs publics suppose que tous partent du même point de départ culturel. Les travaux comparatifs montrent plutôt un effet de seuil : sans invitation initiale ou médiation, beaucoup n'osent pas franchir la porte d'une patinoire ou d'un théâtre, même gratuit. Les politiques qui ne financent pas cette première médiation mesurent surtout l'audace préexistante.",
    question: "Pourquoi les indicateurs de fréquentation sont-ils trompeurs ?",
    options: [
      "Parce que les loisirs publics sont toujours payants.",
      "Parce qu'ils ignorent le besoin de première invitation ou médiation.",
      "Parce que les nouveaux résidents détestent le sport.",
      "Parce que les statistiques culturelles sont illégales.",
    ],
    correctIndex: 1,
    explanation: "Without first-step mediation, metrics reflect who already dared to enter.",
  },
];
