import type { LemmaRow } from "./tcf-exam-lexique-batch2";

export const BATCH3_A: LemmaRow[] = [
  ["Street sign", "la pancarte", "La pancarte indique une zone scolaire."],
  ["Crosswalk", "le passage piéton", "Traversez au passage piéton seulement."],
  ["Speed limit", "la limite de vitesse", "La limite de vitesse est de cinquante km/h."],
  ["Seat belt", "la ceinture de sécurité", "Attachez votre ceinture de sécurité."],
  ["Luggage", "les bagages", "Vos bagages sont sur le tapis roulant."],
  ["Carry-on", "le bagage à main", "Un seul bagage à main est permis."],
  ["Boarding pass", "la carte d'embarquement", "Présentez la carte d'embarquement à la porte."],
  ["Customs declaration", "la déclaration en douane", "Remplissez la déclaration en douane."],
  ["Duty-free", "hors taxes", "Les parfums hors taxes sont moins chers."],
  ["Layover", "l'escale", "Notre escale à Montréal dure deux heures."],
  ["Gate (airport)", "la porte d'embarquement", "Le vol part de la porte douze."],
  ["Security screening", "le contrôle de sécurité", "Retirez votre ceinture au contrôle de sécurité."],
  ["Lost baggage", "les bagages perdus", "Signalez vos bagages perdus au comptoir."],
  ["Travel insurance", "l'assurance voyage", "L'assurance voyage couvre les annulations."],
  ["Itinerary", "l'itinéraire", "Vérifiez votre itinéraire avant de partir."],
  ["Hostel", "l'auberge de jeunesse", "L'auberge de jeunesse accepte les réservations en ligne."],
  ["Front desk", "la réception", "Demandez la clé à la réception."],
  ["Housekeeping", "le service d'entretien", "Le service d'entretien passe chaque matin."],
  ["Do not disturb", "ne pas déranger", "Accrochez le panneau ne pas déranger."],
  ["Check-out time", "l'heure de départ", "L'heure de départ est onze heures."],
  ["Key card", "la carte magnétique", "Votre chambre s'ouvre avec la carte magnétique."],
  ["Vending machine", "le distributeur automatique", "Le distributeur automatique accepte les pièces."],
  ["Coin laundry", "la laverie automatique", "La laverie automatique est au sous-sol."],
  ["Dry cleaning", "le nettoyage à sec", "Le nettoyage à sec sera prêt demain."],
  ["Tailor", "le tailleur", "Le tailleur raccourcit le pantalon en une heure."],
  ["Alteration", "la retouche", "La retouche coûte quinze dollars."],
  ["Fitting room", "la cabine d'essayage", "Essayez le manteau dans la cabine d'essayage."],
  ["Price tag", "l'étiquette de prix", "L'étiquette de prix indique la réduction."],
  ["Layaway", "la réserve", "Mettez le téléviseur en réserve jusqu'à vendredi."],
  ["Installment plan", "le plan de paiement", "Un plan de paiement est disponible sans intérêt."],
  ["Lay-by", "la mise de côté", "La mise de côté sécurise l'article trente jours."],
  ["Gift receipt", "le reçu-cadeau", "Demandez un reçu-cadeau pour les échanges."],
  ["Store credit", "l'avoir en magasin", "Nous offrons un avoir en magasin sans remboursement."],
  ["Rain check", "le bon de repreport", "Voici un bon de repreport pour l'article épuisé."],
  ["Backorder", "la commande en attente", "Votre commande en attente arrivera la semaine prochaine."],
  ["Pickup notice", "l'avis de ramassage", "Vous avez reçu un avis de ramassage au comptoir."],
  ["Postage", "les frais postaux", "Les frais postaux dépendent du poids."],
  ["Registered mail", "le courrier recommandé", "Envoyez le contrat en courrier recommandé."],
  ["Courier", "le messager", "Le messager livrera le colis avant midi."],
  ["Signature required", "signature requise", "Ce colis exige signature requise à la livraison."],
  ["P.O. box", "la case postale", "Écrivez votre case postale sur l'enveloppe."],
  ["Zip code", "le code postal", "N'oubliez pas le code postal sur l'adresse."],
  ["Rural route", "la route rurale", "La route rurale n'a pas de numéro civique."],
  ["Intercom", "l'interphone", "Sonnez au interphone pour entrer dans l'immeuble."],
  ["Buzz code", "le code d'accès", "Entrez le code d'accès pour ouvrir la porte."],
  ["Superintendent", "le concierge", "Le concierge répare la fuite ce soir."],
  ["Snow removal", "le déneigement", "Le déneigement de l'allée est inclus."],
  ["Ice melter", "la fonte de glace", "Épandez la fonte de glace sur les marches."],
  ["Furnace filter", "le filtre de fournaise", "Changez le filtre de fournaise chaque trimestre."],
  ["Thermostat", "le thermostat", "Baissez le thermostat la nuit pour économiser."],
  ["Circuit breaker", "le disjoncteur", "Le disjoncteur a sauté pendant la tempête."],
  ["Power outage", "la panne d'électricité", "La panne d'électricité devrait durer une heure."],
  ["Tap water", "l'eau du robinet", "L'eau du robinet est potable ici."],
  ["Boil water advisory", "l'avis d'ébullition", "Un avis d'ébullition est en vigueur jusqu'à lundi."],
  ["Water meter", "le compteur d'eau", "Le compteur d'eau est lu chaque mois."],
  ["Leak", "la fuite", "Signalez la fuite sous l'évier immédiatement."],
  ["Plumber", "le plombier", "Le plombier arrive entre treize et quinze heures."],
  ["Pest control", "la extermination", "L'extermination traite les insectes une fois par an."],
  ["Smoke detector", "le détecteur de fumée", "Testez le détecteur de fumée chaque mois."],
  ["Fire extinguisher", "l'extincteur", "L'extincteur se trouve près de la sortie."],
  ["Emergency exit", "la sortie de secours", "La sortie de secours est au fond du couloir."],
  ["First aid kit", "la trousse de premiers soins", "La trousse de premiers soins est dans la cuisine."],
  ["Stitches", "les points de suture", "Les points de suture seront retirés dans dix jours."],
  ["Sprain", "l'entorse", "Il s'est foulé la cheville, une entorse légère."],
  ["X-ray", "la radiographie", "La radiographie confirme qu'il n'y a pas de fracture."],
  ["Blood test", "la prise de sang", "La prise de sang se fait à jeun le matin."],
  ["Medical chart", "le dossier médical", "Votre dossier médical est transféré à la clinique."],
  ["Referral", "la référence médicale", "Vous avez besoin d'une référence médicale pour le spécialiste."],
  ["Follow-up appointment", "le rendez-vous de suivi", "Prenez un rendez-vous de suivi dans six semaines."],
  ["Side effect", "l'effet secondaire", "Cet effet secondaire disparaît en quelques jours."],
  ["Dosage", "la posologie", "Respectez la posologie indiquée sur l'étiquette."],
  ["Generic drug", "le médicament générique", "Le médicament générique coûte moins cher."],
  ["Parking permit", "le permis de stationnement", "Le permis de stationnement est valide un an."],
  ["Hand sanitizer", "le désinfectant pour les mains", "Utilisez le désinfectant pour les mains en entrant."],
  ["Waiting area", "la salle d'attente", "Attendez votre tour dans la salle d'attente."],
  ["Restroom", "les toilettes", "Les toilettes se trouvent au bout du couloir."],
];

export const BATCH3_B: LemmaRow[] = [
  ["Settlement services", "les services d'établissement", "Les services d'établissement aident les nouveaux arrivants."],
  ["Orientation session", "la séance d'orientation", "La séance d'orientation explique les démarches locales."],
  ["Bridging program", "le programme passerelle", "Le programme passerelle prépare la reconnaissance professionnelle."],
  ["Professional order", "l'ordre professionnel", "L'ordre professionnel délivre le permis d'exercice."],
  ["Apprenticeship", "l'apprentissage", "L'apprentissage combine cours et travail rémunéré."],
  ["Trade certification", "la certification métier", "La certification métier est exigée pour ce poste."],
  ["Safety training", "la formation en sécurité", "La formation en sécurité est renouvelée chaque année."],
  ["Harassment policy", "la politique contre le harcèlement", "La politique contre le harcèlement s'applique à tous."],
  ["Accommodation (workplace)", "l'aménagement au travail", "Demandez un aménagement au travail si nécessaire."],
  ["Parental leave", "le congé parental", "Le congé parental peut être partagé entre les parents."],
  ["Employment standards", "les normes d'emploi", "Les normes d'emploi fixent le salaire minimum."],
  ["Labour board", "la commission des relations de travail", "La commission des relations de travail tranche les conflits."],
  ["Grievance", "le grief", "Déposez un grief si la convention n'est pas respectée."],
  ["Collective agreement", "la convention collective", "La convention collective expire en décembre."],
  ["Overtime pay", "la rémunération des heures supplémentaires", "La rémunération des heures supplémentaires est de une fois et demie."],
  ["Stat holiday", "le jour férié", "Le jour férié est payé si vous avez travaillé avant."],
  ["Vacation pay", "l'indemnité de vacances", "L'indemnité de vacances apparaît sur chaque paie."],
  ["Record of employment", "le relevé d'emploi", "Le relevé d'emploi est nécessaire pour l'assurance-emploi."],
  ["Notice period", "le préavis", "Un préavis de deux semaines est courtois en démission."],
  ["Termination pay", "l'indemnité de départ", "L'indemnité de départ dépend de l'ancienneté."],
  ["Constructive dismissal", "la démission forcée", "La démission forcée peut donner droit à compensation."],
  ["Human rights complaint", "la plainte en droits de la personne", "Déposez une plainte en droits de la personne si discriminé."],
  ["Landlord", "le locateur", "Le locateur doit aviser vingt-quatre heures avant une visite."],
  ["Tenant", "le locataire", "Le locataire paie le loyer le premier du mois."],
  ["Security deposit", "le dépôt de garantie", "Le dépôt de garantie est remboursable si l'appartement est intact."],
  ["Rent tribunal", "le tribunal administratif du logement", "Le tribunal administratif du logement règle les différends."],
  ["Maintenance log", "le registre d'entretien", "Le registre d'entretien prouve les réparations demandées."],
  ["Noise complaint", "la plainte pour bruit", "Déposez une plainte pour bruit auprès de la ville."],
  ["Bed bugs", "les punaises de lit", "Signalez les punaises de lit sans délai au locateur."],
  ["Mold", "la moisissure", "La moisissure peut être un problème de santé sérieux."],
  ["Heat bylaw", "le règlement sur le chauffage", "Le règlement sur le chauffage exige vingt et un degrés en hiver."],
  ["Hydro bill", "la facture d'électricité", "La facture d'électricité arrive chaque deux mois."],
  ["Gas bill", "la facture de gaz", "La facture de gaz augmente en hiver."],
  ["Water bill", "la facture d'eau", "La facture d'eau inclut l'assainissement."],
  ["Internet plan", "le forfait Internet", "Changez de forfait Internet si la vitesse est insuffisante."],
  ["Mobile plan", "le forfait mobile", "Le forfait mobile inclut dix gigaoctets de données."],
  ["Roaming charges", "les frais d'itinérance", "Les frais d'itinérance s'appliquent hors du Canada."],
  ["Credit score", "la cote de crédit", "Une bonne cote de crédit facilite la location."],
  ["Credit report", "le rapport de crédit", "Vérifiez votre rapport de crédit chaque année."],
  ["Debt consolidation", "la consolidation de dettes", "La consolidation de dettes réduit les intérêts mensuels."],
  ["Bankruptcy", "la faillite", "La faillite a des conséquences sur le crédit longtemps."],
  ["Financial advisor", "le conseiller financier", "Un conseiller financier planifie la retraite."],
  ["Registered retirement savings", "le REER", "Contribuer au REER réduit l'impôt payable."],
  ["Tax-free savings account", "le CELI", "Le CELI permet des gains sans impôt."],
  ["Child benefit", "la prestation pour enfants", "La prestation pour enfants est versée chaque mois."],
  ["GST credit", "le crédit pour la taxe sur les produits", "Le crédit pour la taxe sur les produits est non imposable."],
  ["Provincial health card", "la carte d'assurance maladie", "Présentez votre carte d'assurance maladie à chaque visite."],
  ["RAMQ (Quebec health)", "la RAMQ", "La RAMQ couvre les soins de base au Québec."],
  ["Walk-in appointment", "la consultation sans rendez-vous", "La consultation sans rendez-vous est pour les urgences mineures."],
  ["Emergency room wait", "l'attente à l'urgence", "L'attente à l'urgence peut dépasser six heures."],
  ["Triage nurse", "l'infirmière d'accueil", "L'infirmière d'accueil évalue la gravité des cas."],
  ["Medical imaging", "l'imagerie médicale", "L'imagerie médicale confirme le diagnostic."],
  ["Physiotherapy", "la physiothérapie", "La physiothérapie est couverte partiellement par l'assurance."],
  ["Occupational therapy", "l'ergothérapie", "L'ergothérapie aide à reprendre le travail."],
  ["Dental cleaning", "le nettoyage dentaire", "Le nettoyage dentaire est recommandé deux fois par an."],
  ["Vision exam", "l'examen de la vue", "L'examen de la vue renouvelle la prescription de lunettes."],
  ["Pharmacy deductible", "la franchise médicamenteuse", "La franchise médicamenteuse s'applique aux aînés."],
  ["Generic substitution", "la substitution générique", "La substitution générique réduit le coût de l'ordonnance."],
  ["School district", "le district scolaire", "Le district scolaire assigne l'école selon l'adresse."],
  ["French immersion", "l'immersion française", "L'immersion française commence en maternelle."],
  ["Homework club", "le club de devoirs", "Le club de devoirs aide après les cours."],
  ["Bullying", "l'intimidation", "Signalez l'intimidation à la direction de l'école."],
  ["Community centre", "le centre communautaire", "Le centre communautaire propose des cours gratuits."],
  ["Food bank", "la banque alimentaire", "La banque alimentaire accueille les familles le samedi."],
  ["Transit pass", "la passe de transport", "La passe de transport mensuelle coûte moins cher."],
  ["Snow tire", "le pneu d'hiver", "Les pneus d'hiver sont obligatoires du premier décembre."],
  ["Driver's licence renewal", "le renouvellement du permis de conduire", "Le renouvellement du permis de conduire se fait en ligne."],
  ["Vehicle registration", "l'immatriculation du véhicule", "L'immatriculation du véhicule expire en mars."],
  ["Speeding ticket", "la contravention pour excès de vitesse", "La contravention pour excès de vitesse augmente l'assurance."],
  ["Demerit points", "les points d'inaptitude", "Les points d'inaptitude peuvent entraîner une suspension."],
  ["Library card", "la carte de bibliothèque", "La carte de bibliothèque est gratuite pour les résidents."],
];

export const BATCH3_C: LemmaRow[] = [
  ["Prima facie", "a prima facie", "A prima facie, les preuves soutiennent la thèse."],
  ["Prima facie case", "la présomption de bien fondé", "La présomption de bien fondé suffit pour ouvrir l'enquête."],
  ["Straw man argument", "l'homme de paille", "Il réfute un homme de paille plutôt que l'argument réel."],
  ["False dichotomy", "la fausse dichotomie", "La fausse dichotomie limite le débat à deux options."],
  ["Circular reasoning", "le raisonnement circulaire", "Le raisonnement circulaire ne convainc pas les experts."],
  ["Appeal to authority", "l'argument d'autorité", "L'argument d'autorité remplace parfois l'analyse."],
  ["Hasty generalization", "la généralisation hâtive", "La généralisation hâtive ignore les exceptions importantes."],
  ["Slippery slope", "la pente glissante", "La pente glissante exagère les conséquences futures."],
  ["Red herring", "la manœuvre dilatoire", "La manœuvre dilatoire détourne l'attention du sujet."],
  ["Ad hominem", "l'argument ad hominem", "L'argument ad hominem attaque la personne, pas l'idée."],
  ["To rebut", "rétorquer", "Elle rétorque en citant des données récentes."],
  ["To posit", "postuler", "Les auteurs postulent un lien sans le démontrer."],
  ["To extrapolate", "extrapoler", "Il est risqué d'extrapoler à partir d'un seul cas."],
  ["To corroborate", "corroborer", "Deux sources indépendantes corroborent l'affirmation."],
  ["To invalidate", "invalider", "Une erreur méthodologique peut invalider l'étude."],
  ["To nuance", "nuancer", "Il nuance sa position sans la renier complètement."],
  ["To qualify (a statement)", "qualifier", "Elle qualifie ses propos en précisant le contexte."],
  ["To stipulate", "stipuler", "Le contrat stipule un préavis de soixante jours."],
  ["To enshrine", "consacrer", "La loi consacre un droit dans la Constitution."],
  ["To curtail", "restreindre", "La mesure restreint les pouvoirs discrétionnaires."],
  ["To entrench", "enraciner", "Une pratique enracinée résiste aux réformes rapides."],
  ["To galvanize", "mobiliser", "Le scandale mobilise l'opinion publique."],
  ["To placate", "apaiser", "Le ministre tente d'apaiser les critiques sans promesse ferme."],
  ["To obfuscate", "obscurcir", "Le jargon obscurcit plus qu'il n'éclaire."],
  ["To elucidate", "élucider", "L'éditorial éclaire le sens de la réforme proposée."],
  ["To dichotomize", "dichotomiser", "Il dichotomise à tort riches et pauvres."],
  ["To instrumentalize", "instrumentaliser", "Ne pas instrumentaliser la souffrance à des fins électorales."],
  ["To legitimize", "légitimer", "La transparence légitime les décisions impopulaires."],
  ["To delegitimize", "délégitimer", "Les rumeurs cherchent à délégitimer l'institution."],
  ["To reframe", "recadrer", "Elle recadre le débat autour de l'équité."],
  ["To problematize", "problématiser", "L'article problématise l'usage du terme neutralité."],
  ["Heuristic", "l'heuristique", "Cette heuristique simplifie une décision complexe."],
  ["Epistemic", "épistémique", "La crédibilité épistémique varie selon les sources."],
  ["Normative claim", "l'énoncé normatif", "Un énoncé normatif ne se réfute pas par des faits seuls."],
  ["Descriptive claim", "l'énoncé descriptif", "Un énoncé descriptif se vérifie par observation."],
  ["Value judgment", "le jugement de valeur", "Un jugement de valeur dépasse la simple mesure."],
  ["Moral hazard", "l'aléa moral", "L'aléa moral incite à prendre plus de risques."],
  ["Opportunity cost", "le coût de renonciation", "Le coût de renonciation limite chaque choix public."],
  ["Externality", "l'externalité", "Une externalité négative n'est pas toujours internalisée."],
  ["Pareto improvement", "l'amélioration pareto", "Une amélioration pareto avantage quelqu'un sans nuire."],
  ["Zero-sum", "à somme nulle", "Voir la politique comme à somme nulle est réducteur."],
  ["Win-win", "gagnant-gagnant", "Un accord gagnant-gagnant reste difficile à négocier."],
  ["Fungible", "fongible", "Les fonds ne sont pas fongibles entre programmes."],
  ["Salient", "saillant", "Le point saillant du discours concerne la confiance."],
  ["Tacit consent", "le consentement tacite", "Le consentement tacite ne remplace pas la consultation."],
  ["Procedural justice", "la justice procédurale", "La justice procédurale exige des règles équitables."],
  ["Substantive justice", "la justice substantive", "La justice substantive regarde le résultat final."],
  ["Retroactivity", "la rétroactivité", "La rétroactivité d'une loi soulève des craintes."],
  ["Sunset clause", "la clause de temporisation", "La clause de temporisation limite la durée de la loi."],
  ["Grandfather clause", "la clause grand-père", "La clause grand-père protège les droits acquis."],
  ["Judicial review", "le contrôle judiciaire", "Le contrôle judiciaire examine la légalité des actes."],
  ["Ultra vires", "ultra vires", "Une décision ultra vires dépasse le mandat légal."],
  ["Quorum", "le quorum", "Sans quorum, l'assemblée ne peut voter valablement."],
  ["Abstention", "l'abstention", "Son abstention a fait basculer le vote."],
  ["Proxy vote", "le vote par procuration", "Le vote par procuration est autorisé pour les membres absents."],
  ["Co-optation", "la cooptation", "La cooptation des opposants modérés divise le front."],
  ["Dog whistle", "le dog whistle", "Le dog whistle parle clairement à une base sans alarmer les autres."],
  ["Overton window", "la fenêtre d'Overton", "La fenêtre d'Overton déplace ce qui est politiquement acceptable."],
  ["Manufactured consent", "le consentement fabriqué", "Le consentement fabriqué repose sur un récit médiatique unique."],
  ["Pluralism", "le pluralisme", "Le pluralisme reconnaît plusieurs visions légitimes."],
  ["Majoritarianism", "le majoritarisme", "Le majoritarisme ignore parfois les droits des minorités."],
  ["Deliberative democracy", "la démocratie délibérative", "La démocratie délibérative privilégie l'échange argumenté."],
  ["Checks and balances", "les contrepoids", "Les contrepoids limitent la concentration du pouvoir."],
  ["Separation of powers", "la séparation des pouvoirs", "La séparation des pouvoirs protège les libertés."],
  ["Rule of law", "la primauté du droit", "La primauté du droit s'impose à tous, y compris l'État."],
  ["Due process", "la garantie procédurale", "La garantie procédurale exige un procès équitable."],
  ["Habeas corpus", "l'habeas corpus", "L'habeas corpus empêche la détention arbitraire."],
  ["Amicus curiae", "l'amicus curiae", "Un amicus curiae présente un mémoire au tribunal."],
  ["Stare decisis", "le stare decisis", "Le stare decisis stabilise la jurisprudence."],
  ["Obiter dictum", "l'obiter dictum", "L'obiter dictum n'a pas force obligatoire."],
  ["Ratio decidendi", "le ratio decidendi", "Le ratio decidendi fonde la décision du juge."],
  ["Burden of proof", "la charge de la preuve", "La charge de la preuve incombe au plaignant."],
  ["Standard of proof", "le fardeau de preuve", "Le fardeau de preuve est plus élevé en criminel."],
  ["Affirmative action", "la discrimination positive", "La discrimination positive vise à corriger des inégalités historiques."],
  ["Precautionary principle", "le principe de précaution", "Le principe de précaution guide certaines politiques environnementales."],
  ["Instrumental reasoning", "le raisonnement instrumental", "Le raisonnement instrumental privilégie l'efficacité immédiate."],
];

