import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 7 — Compréhension écrite. Theme: public services, citizenship and civic life in Canada.
 *
 * Hand-authored to keep distractors plausible and similar in length, so no
 * surface heuristic (longest option, option B) beats reading the text.
 */
export const TCF_READING_P7: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "BUREAU DE VOTE — ÉCOLE LAURIER\nOuvert le jour de l'élection de 9 h à 20 h\nPièce d'identité avec photo obligatoire\nCarte d'électeur recommandée",
    question: "Quel document est obligatoire pour voter ?",
    options: ["La carte d'électeur.", "Une pièce d'identité avec photo.", "Un passeport canadien.", "Un relevé d'impôt."],
    correctIndex: 1,
    explanation: "The sign requires photo ID; the voter card is only recommended.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Horaires",
    passage: "SERVICE CANADA — SUCCURSALE CENTRE-VILLE\nLundi au vendredi : 8 h 30 – 16 h\nSamedi et dimanche : fermé\nNuméro d'assurance sociale : sur rendez-vous uniquement",
    question: "Quand le bureau est-il ouvert le samedi ?",
    options: ["De 8 h 30 à 16 h.", "De 9 h à 12 h.", "Il est fermé.", "Sur rendez-vous seulement."],
    correctIndex: 2,
    explanation: "Saturday and Sunday are closed.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Salut Marco,\nLa bibliothèque municipale ferme à 18 h aujourd'hui. J'ai réservé le roman que tu voulais ; tu peux le retirer au comptoir avec ta carte de membre.\nÀ ce soir,\nLéa",
    question: "Où Marco doit-il aller pour récupérer le livre ?",
    options: ["À la bibliothèque municipale.", "Chez Léa.", "Au centre communautaire.", "À la poste."],
    correctIndex: 0,
    explanation: "Léa reserved the book at the municipal library for pickup at the desk.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "COLLECTE DES DÉCHETS — QUARTIER NORD\nOrdures : mardi matin\nRecyclage : mardi matin\nCompost : vendredi matin\nSortez les bacs avant 7 h",
    question: "Quel jour faut-il sortir le bac de compost ?",
    options: ["Le lundi.", "Le mardi.", "Le vendredi.", "Le dimanche."],
    correctIndex: 2,
    explanation: "Compost collection is on Friday morning.",
  },
  {
    id: 5,
    level: "A2",
    passageType: "Courriel",
    passage: "Objet : Confirmation de rendez-vous\n\nBonjour,\nVotre rendez-vous pour renouveler votre carte d'assurance maladie est fixé au 12 juin à 10 h 15. Apportez votre carte actuelle, une preuve de résidence et un document d'identité.\nService de la santé",
    question: "Que doit apporter le client au rendez-vous ?",
    options: [
      "Uniquement la carte d'assurance maladie actuelle.",
      "La carte actuelle, une preuve de résidence et une pièce d'identité.",
      "Un formulaire rempli en ligne et un chèque.",
      "Un certificat médical récent.",
    ],
    correctIndex: 1,
    explanation: "The email lists the current card, proof of residence, and ID.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Note d'information",
    passage: "INSCRIPTION SUR LA LISTE ÉLECTORALE\nLes citoyens canadiens de 18 ans et plus peuvent s'inscrire en ligne, par courrier ou en personne. L'inscription prend effet après vérification de l'adresse. Sans inscription, vous ne pourrez pas voter le jour de l'élection.",
    question: "Qui peut s'inscrire sur la liste électorale selon ce texte ?",
    options: [
      "Toute personne résidant au Canada depuis un an.",
      "Les citoyens canadiens âgés d'au moins 18 ans.",
      "Les détenteurs d'un permis de travail valide.",
      "Les personnes ayant déjà voté une fois.",
    ],
    correctIndex: 1,
    explanation: "Canadian citizens aged 18 and over may register.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Affiche",
    passage: "CENTRE COMMUNAUTAIRE — AIDE AUX IMPÔTS\nBénévoles formés pour remplir votre déclaration\nSamedi 9 mars, 10 h – 16 h\nGratuit sur rendez-vous\nApportez vos feuillets T4 et Relevé 1",
    question: "De quoi l'affiche parle-t-elle ?",
    options: [
      "D'un cours de comptabilité payant.",
      "D'une aide gratuite pour la déclaration d'impôts.",
      "D'une collecte de documents pour les élections.",
      "D'une vente de matériel de bureau.",
    ],
    correctIndex: 1,
    explanation: "Volunteers help fill tax returns for free by appointment.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "SMS",
    passage: "Rappel Ville de Gatineau : la consultation sur le nouveau parc se tient ce jeudi, 19 h, à la salle polyvalente. Vous pouvez poser des questions aux élus. Entrée libre.",
    question: "Quel est l'objet de ce message ?",
    options: [
      "L'ouverture officielle d'un parc.",
      "Une réunion pour discuter d'un futur parc.",
      "La fermeture d'une salle municipale.",
      "Un changement d'horaire des élus.",
    ],
    correctIndex: 1,
    explanation: "It is a consultation about a new park on Thursday evening.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Formulaire",
    passage: "DEMANDE DE PASSEPORT\nÉtape 1 : remplir le formulaire en ligne\nÉtape 2 : payer les frais par carte\nÉtape 3 : présenter les documents en personne\nDélai moyen : dix jours ouvrables après la visite",
    question: "Quand le passeport est-il généralement prêt ?",
    options: [
      "Dès la fin du paiement en ligne.",
      "Environ dix jours ouvrables après la visite.",
      "Le jour même de la demande en personne.",
      "Trois semaines après l'envoi du formulaire.",
    ],
    correctIndex: 1,
    explanation: "Average delay is ten business days after the in-person visit.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Courriel",
    passage: "Bonjour Mme Okonkwo,\nVotre demande de subvention pour le projet de jardin communautaire est acceptée. Vous recevrez le versement en deux fois : la moitié maintenant, l'autre moitié après le rapport d'activité en septembre.\nCordialement,\nLe service des loisirs",
    question: "Quand recevra-t-on la seconde partie de la subvention ?",
    options: [
      "Dès l'acceptation de la demande.",
      "Après le rapport d'activité en septembre.",
      "Au moment de la signature du contrat.",
      "Lors de l'ouverture du jardin au public.",
    ],
    correctIndex: 1,
    explanation: "The second half comes after the activity report in September.",
  },

  // ── B1–B2 (Q11–29) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Au Canada, les impôts financent les routes, les écoles et les hôpitaux. Chaque résident doit déclarer ses revenus chaque année, même s'il n'a rien à payer. Les nouveaux arrivants reçoivent souvent des lettres leur rappelant cette obligation, car beaucoup ignorent qu'une déclaration vide peut ouvrir droit à des prestations.",
    question: "Pourquoi une déclaration sans impôt à payer peut être utile ?",
    options: [
      "Elle évite une amende automatique de l'État.",
      "Elle peut donner accès à certaines prestations.",
      "Elle remplace la carte d'assurance maladie.",
      "Elle accélère l'obtention de la citoyenneté.",
    ],
    correctIndex: 1,
    explanation: "Even a nil return can qualify you for benefits.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Chronique",
    passage: "On dit que les Canadiens ne protestent pas. En réalité, ils le font autrement : pétitions en ligne, interventions en conseil municipal, plaintes formelles auprès des ombudsmans. La rue reste rare, mais la participation institutionnelle est élevée. Comprendre ces canaux, c'est déjà une partie de l'intégration civique.",
    question: "Selon l'auteur, comment s'exprime surtout la contestation au Canada ?",
    options: [
      "Par des manifestations massives dans la rue.",
      "Par des canaux institutionnels comme les pétitions et les plaintes.",
      "Par le refus de payer certains impôts locaux.",
      "Par l'abstention systématique aux élections.",
    ],
    correctIndex: 1,
    explanation: "The text highlights petitions, council meetings, and ombudsman complaints.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Guide pratique",
    passage: "Pour devenir citoyen canadien, il faut résider légalement au Canada pendant au moins trois ans sur les cinq dernières années, passer un test sur les droits et responsabilités, et prouver sa maîtrise d'une langue officielle. Les enfants mineurs inclus dans la demande des parents n'ont pas à passer le test, mais doivent être présents à la cérémonie.",
    question: "Que mentionne le guide au sujet des enfants mineurs ?",
    options: [
      "Ils doivent passer le même test que les adultes.",
      "Ils sont exemptés du test mais doivent assister à la cérémonie.",
      "Ils ne peuvent être inclus que s'ils sont nés au Canada.",
      "Ils obtiennent automatiquement la citoyenneté sans cérémonie.",
    ],
    correctIndex: 1,
    explanation: "Minors on a parent's application skip the test but must attend the ceremony.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Reportage",
    passage: "Dans plusieurs villes de l'Ontario, les bibliothèques servent de refuges thermiques l'hiver. Elles offrent chauffage, eau et parfois une collation. Les bibliothécaires ne sont pas travailleurs sociaux, mais ils orientent les visiteurs vers les services municipaux. Le modèle séduit parce qu'il réutilise un lieu déjà fréquenté et de confiance.",
    question: "Quel rôle jouent les bibliothèques dans ce dispositif ?",
    options: [
      "Elles remplacent entièrement les centres d'hébergement.",
      "Elles accueillent et orientent vers d'autres services publics.",
      "Elles financent les repas servis aux sans-abri.",
      "Elles emploient des travailleurs sociaux à plein temps.",
    ],
    correctIndex: 1,
    explanation: "Libraries provide warmth and refer people to municipal services.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Le vote par anticipation attire de plus en plus d'électeurs. Les bureaux ouverts la semaine précédant l'élection réduisent l'affluence le jour J et permettent aux travailleurs aux horaires atypiques de participer. Les critiques estiment que l'information sur ces bureaux reste inégale d'un quartier à l'autre.",
    question: "Quel avantage du vote par anticipation est présenté ?",
    options: [
      "Il rend le dépouillement plus rapide le soir même.",
      "Il facilite la participation des personnes aux horaires difficiles.",
      "Il supprime le besoin de pièce d'identité.",
      "Il est obligatoire pour les nouveaux citoyens.",
    ],
    correctIndex: 1,
    explanation: "Advance voting helps those with atypical work schedules take part.",
  },
  {
    id: 16,
    level: "B1",
    passageType: "Courrier des lecteurs",
    passage: "Votre article sur les conseils d'école m'a interpellé, mais il oublie les parents allophones. Les réunions sont souvent annoncées seulement en anglais, les documents arrivent tard et les interprètes sont rares. On parle de participation citoyenne, mais on exclut ceux qui ne comprennent pas encore la langue dominante du quartier.",
    question: "Que reproche le lecteur à l'article ?",
    options: [
      "D'avoir critiqué le rôle des conseils d'école.",
      "D'avoir ignoré les obstacles linguistiques des parents allophones.",
      "D'avoir surestimé le pouvoir des conseils d'école.",
      "D'avoir omis les statistiques sur la fréquentation scolaire.",
    ],
    correctIndex: 1,
    explanation: "He says the piece overlooked language barriers for allophone parents.",
  },
  {
    id: 17,
    level: "B1",
    passageType: "Note de service",
    passage: "À compter du 1er avril, les demandes de permis de rénovation devront être déposées en ligne. Le guichet physique reste ouvert pour les personnes sans accès Internet, sur rendez-vous. Les dossiers incomplets seront retournés sans traitement ; aucun remboursement des frais de dépôt n'est prévu.",
    question: "Que se passe-t-il si le dossier est incomplet ?",
    options: [
      "La municipalité complète le dossier gratuitement.",
      "Le dossier est renvoyé et les frais de dépôt ne sont pas remboursés.",
      "Le demandeur dispose d'un mois supplémentaire.",
      "Le permis est accordé sous condition.",
    ],
    correctIndex: 1,
    explanation: "Incomplete files are sent back with no refund of the deposit fee.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Analyse",
    passage: "La transparence des dépenses municipales a progressé avec la publication des contrats en ligne. Pourtant, la lecture de ces données exige des compétences que peu de citoyens possèdent. Sans médiation — journalistes, associations, outils de visualisation — l'ouverture des données ne produit pas de contrôle démocratique, elle produit surtout de la paperasse consultable.",
    question: "Quel paradoxe l'auteur souligne-t-il ?",
    options: [
      "Les contrats publiés contiennent encore des informations secrètes.",
      "La transparence formelle ne suffit pas sans capacité à interpréter les données.",
      "Les municipalités publient moins de documents qu'avant.",
      "Les citoyens préfèrent ne pas connaître les dépenses locales.",
    ],
    correctIndex: 1,
    explanation: "Open data alone does not enable democratic oversight without skills and mediation.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Éditorial",
    passage: "Exiger une pièce d'identité stricte pour voter vise à prévenir la fraude, mais elle exclut aussi des électeurs âgés ou précaires qui n'ont pas de permis de conduire à jour. Le débat oppose deux visions de la citoyenneté : la sécurité du scrutin contre l'inclusion du plus grand nombre. Aucune solution ne coûte zéro.",
    question: "Quel conflit de valeurs le texte décrit-il ?",
    options: [
      "Entre le vote en ligne et le vote traditionnel.",
      "Entre la sécurité du scrutin et l'accessibilité du vote.",
      "Entre les élections fédérales et municipales.",
      "Entre le français et l'anglais dans les bureaux de vote.",
    ],
    correctIndex: 1,
    explanation: "Strict ID rules pit ballot security against including more voters.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "Les services d'urgence sociale observent une hausse des appels liés à la solitude, surtout chez les personnes récemment immigrées. Ce n'est pas un manque d'information sur les programmes : les brochures existent en plusieurs langues. Le problème est la honte de demander de l'aide et la crainte que cela nuise à un futur dossier d'immigration.",
    question: "Pourquoi les personnes concernées n'utilisent-elles pas les services ?",
    options: [
      "Parce que les documents ne sont pas traduits.",
      "Parce qu'elles ignorent l'existence des programmes.",
      "Parce qu'elles craignent les conséquences sur leur dossier.",
      "Parce que les services sont réservés aux citoyens.",
    ],
    correctIndex: 2,
    explanation: "Shame and fear of harming an immigration file keep people from seeking help.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Enquête",
    passage: "Dans trois provinces, des citoyens peuvent porter plainte auprès d'un ombudsman lorsqu'un ministère traite mal leur dossier. L'institution ne peut pas annuler une loi, mais elle peut recommander des corrections et publier des rapports. Son efficacité repose sur la honte administrative : les ministères redoutent les rapports publics défavorables.",
    question: "Sur quoi repose l'efficacité de l'ombudsman selon le texte ?",
    options: [
      "Sur son pouvoir de modifier directement les lois.",
      "Sur la pression exercée par des rapports publics embarrassants.",
      "Sur des amendes imposées aux fonctionnaires fautifs.",
      "Sur le financement privé de son bureau.",
    ],
    correctIndex: 1,
    explanation: "Effectiveness relies on ministries fearing unfavourable public reports.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "On oppose service public et efficacité comme s'il fallait choisir. Les guichets numériques ont réduit les files, mais ils ont aussi éloigné les personnes âgées et celles sans données mobiles. Un service public efficace n'est pas le plus automatisé ; c'est celui qui laisse toujours une porte humaine ouverte pour ceux que la machine exclut.",
    question: "Quelle conception du service public l'auteur défend-il ?",
    options: [
      "Un service entièrement numérique pour réduire les coûts.",
      "Un service qui combine automatisation et accès humain.",
      "Un retour aux guichets physiques sans option en ligne.",
      "Un service réservé aux citoyens les plus vulnérables.",
    ],
    correctIndex: 1,
    explanation: "Efficient public service keeps a human option for those excluded by automation.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Reportage",
    passage: "À Winnipeg, un programme jumelle des familles nouvellement arrivées avec des voisins de longue date pour une promenade mensuelle dans le quartier. Aucun curriculum civique formel : on apprend où voter, comment trier les déchets, qui appeler en cas de coupure d'eau. Les participants disent avoir appris plus en une heure qu'en lisant trois brochures.",
    question: "Qu'est-ce qui rend ce programme efficace selon les participants ?",
    options: [
      "Les cours magistraux donnés par la ville.",
      "L'apprentissage concret du quartier avec un voisin.",
      "La distribution de manuels traduits en vingt langues.",
      "Les subventions financières offertes aux familles.",
    ],
    correctIndex: 1,
    explanation: "They learn practical civic knowledge on neighbourhood walks with a neighbour.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Analyse juridique",
    passage: "La Charte canadienne garantit la liberté de conscience, mais elle autorise des limites « raisonnables ». Les exemptions scolaires pour motifs religieux en sont un exemple : l'État tente de concilier droit individuel et vie collective. Chaque arrondissement interprète cet équilibre différemment, ce qui crée une mosaïque de règles que les nouveaux parents peinent à comprendre.",
    question: "Quel problème ce passage met-il en évidence ?",
    options: [
      "L'interdiction totale des exemptions religieuses.",
      "L'application inégale des mêmes principes selon les territoires.",
      "Le refus des écoles d'accueillir des élèves immigrés.",
      "L'absence de liberté de conscience dans la Charte.",
    ],
    correctIndex: 1,
    explanation: "Local interpretation varies, producing a confusing patchwork for newcomers.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Les budgets participatifs municipaux laissent les résidents décider d'une partie des investissements. Les projets gagnants sont souvent visibles — parcs, éclairage — mais les propositions qui touchent aux services invisibles, comme l'accessibilité des formulaires, peinent à mobiliser. La démocratie directe reproduit parfois les biais de l'attention publique.",
    question: "Quelle limite des budgets participatifs est soulignée ?",
    options: [
      "Ils coûtent plus cher que les décisions prises par les élus.",
      "Ils favorisent les projets visibles au détriment des besoins moins spectaculaires.",
      "Ils excluent les personnes qui ne parlent pas anglais.",
      "Ils ne concernent que les quartiers les plus riches.",
    ],
    correctIndex: 1,
    explanation: "Visible projects win; less visible needs like accessible forms struggle.",
  },
  {
    id: 26,
    level: "B2",
    passageType: "Chronique",
    passage: "Le « civisme numérique » ne se réduit pas à signaler une arnaque en ligne. C'est aussi savoir quels renseignements personnels un ministère peut légalement exiger, conserver un courriel officiel, contester une décision par les voies prévues. Les jeunes maîtrisent les réseaux sociaux, mais ignorent souvent les portails gouvernementaux où se jouent leurs droits.",
    question: "Que critique l'auteur à propos des jeunes citoyens ?",
    options: [
      "Leur méconnaissance des arnaques sur Internet.",
      "Leur familiarité insuffisante avec les démarches administratives officielles.",
      "Leur refus de participer aux élections municipales.",
      "Leur usage excessif des réseaux sociaux au travail.",
    ],
    correctIndex: 1,
    explanation: "They know social media but not government portals where rights are exercised.",
  },
  {
    id: 27,
    level: "B2",
    passageType: "Dossier",
    passage: "Plusieurs villes testent des conseils citoyens tirés au sort, à l'image de certains jurys. L'objectif est d'entendre des voix qui ne viennent jamais aux assemblées publiques. Les sceptiques objectent que quinze personnes ne représentent pas la diversité réelle ; les partisans répondent qu'elles représentent au moins une diversité ignorée jusqu'ici.",
    question: "Quel argument les partisans utilisent-ils ?",
    options: [
      "Que le tirage au sort est moins coûteux que les élections.",
      "Que ces conseils font entendre des profils absents des débats habituels.",
      "Que les élus municipaux sont corrompus.",
      "Que les assemblées publiques sont illégales.",
    ],
    correctIndex: 1,
    explanation: "Supporters say random citizens bring voices missing from usual debates.",
  },
  {
    id: 28,
    level: "B2",
    passageType: "Rapport",
    passage: "L'étude compare deux campagnes d'inscription électorale : l'une ciblait les campus, l'autre les centres communautaires ethniques. La première a augmenté le taux chez les 18–24 ans, la seconde chez les résidents permanents récents. Aucune n'a réussi seule à toucher les deux groupes, ce qui plaide pour des stratégies complémentaires plutôt qu'un modèle unique.",
    question: "Quelle conclusion le rapport suggère-t-il ?",
    options: [
      "Il faut abandonner les campagnes sur les campus.",
      "Il faut combiner plusieurs approches pour toucher des publics différents.",
      "Les résidents permanents votent moins que les jeunes.",
      "Les centres communautaires sont inefficaces pour l'inscription.",
    ],
    correctIndex: 1,
    explanation: "Neither campaign alone reached both groups; complementary strategies are needed.",
  },
  {
    id: 29,
    level: "B2",
    passageType: "Essai",
    passage: "La citoyenneté n'est pas seulement un statut juridique : c'est une pratique distribuée dans le temps. Payer ses impôts, servir de juré, respecter les règles du voisinage sont autant d'actes civiques que voter tous les quatre ans. Réduire la citoyenneté au bulletin dans l'urne, c'est oublier que la démocratie se maintient entre deux élections.",
    question: "Quelle conception de la citoyenneté l'auteur défend-il ?",
    options: [
      "Une citoyenneté limitée au droit de vote.",
      "Une citoyenneté faite d'actes quotidiens et réguliers.",
      "Une citoyenneté réservée aux personnes nées au pays.",
      "Une citoyenneté fondée uniquement sur le paiement d'impôts.",
    ],
    correctIndex: 1,
    explanation: "Citizenship is practiced through taxes, jury duty, neighbourly rules—not only voting.",
  },

  // ── C1–C2 (Q30–39) ─────────────────────────────────────────────
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "Les politiques d'accueil des réfugiés distinguent protection et intégration, mais les mesurent souvent avec les mêmes indicateurs : emploi, logement, cours de langue. Or une personne peut être protégée sans être intégrée, et intégrée sans avoir encore obtenu un statut stable. Confondre les deux objectifs conduit à retirer des services au moment où le besoin de sécurité juridique est maximal.",
    question: "Quelle erreur les politiques commettent-elles selon l'auteur ?",
    options: [
      "Elles accordent trop de moyens aux cours de langue.",
      "Elles utilisent les mêmes critères pour des objectifs distincts.",
      "Elles ignorent totalement la question du logement.",
      "Elles réservent l'intégration aux réfugiés économiques.",
    ],
    correctIndex: 1,
    explanation: "Protection and integration are distinct but measured with the same indicators.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Analyse politique",
    passage: "La décentralisation fédérale fait du citoyen un interlocuteur multiple : Ottawa pour l'immigration, la province pour la santé, la ville pour les déchets. Cette fragmentation n'est pas un défaut de conception ; elle reflète des compromis historiques. Elle produit pourtant une charge cognitive élevée : savoir à qui s'adresser devient une compétence civique en soi, inégalement distribuée.",
    question: "Quel effet la décentralisation a-t-elle sur les citoyens ?",
    options: [
      "Elle supprime les différences entre provinces.",
      "Elle exige de maîtriser une cartographie administrative complexe.",
      "Elle réduit le nombre de services publics offerts.",
      "Elle interdit les recours contre les décisions municipales.",
    ],
    correctIndex: 1,
    explanation: "Knowing which level of government to contact becomes its own civic skill.",
  },
  {
    id: 32,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Elle brandissait sa carte de citoyenne comme on montre un permis de conduire, fière et un peu crispée. Trente ans de taxes, de jurés, de corvées d'école, résumés en un plastique laminé. Elle savait que le papier ne faisait pas la citoyenne, mais sans lui, on la renvoyait au guichet de l'étranger.",
    question: "Quel rapport le personnage entretient-il avec sa carte de citoyenne ?",
    options: [
      "Il la considère comme une simple formalité sans valeur.",
      "Il y voit la condensation d'une vie civique, indispensable pour être reconnue.",
      "Il refuse de la présenter par principe politique.",
      "Il l'a obtenue récemment et ne connaît pas encore ses usages.",
    ],
    correctIndex: 1,
    explanation: "The card condenses decades of civic life yet remains necessary for recognition.",
  },
  {
    id: 33,
    level: "C1",
    passageType: "Article académique",
    passage: "Les consultations publiques obligatoires sur les grands projets urbains produisent parfois l'illusion d'un consentement obtenu. Les promoteurs présentent des plans déjà arrêtés ; les citoyens peuvent commenter, non décider. L'enjeu n'est pas de supprimer la consultation, mais de clarifier ce qu'elle peut modifier réellement, faute de quoi elle alimente la défiance plutôt que la légitimité.",
    question: "Quelle critique l'auteur adresse-t-il aux consultations ?",
    options: [
      "Elles coûtent trop cher pour les municipalités.",
      "Elles laissent croire à une influence que les citoyens n'ont pas.",
      "Elles sont interdites pour les projets environnementaux.",
      "Elles retardent toujours inutilement les chantiers.",
    ],
    correctIndex: 1,
    explanation: "Citizens can comment but not decide, creating an illusion of consent.",
  },
  {
    id: 34,
    level: "C1",
    passageType: "Essai",
    passage: "L'impôt progressif repose sur une fiction utile : que l'on peut mesurer équitablement la capacité contributive. Les revenus du travail sont visibles ; ceux du patrimoine, souvent différés ou délocalisés, le sont moins. Tant que la structure fiscale traite différemment ces flux, parler de justice fiscale sans réformer l'assiette revient à ajuster la décoration d'un bâtiment dont les fondations sont inclinées.",
    question: "Quel obstacle à l'équité fiscale le texte souligne-t-il ?",
    options: [
      "Le refus des citoyens de déclarer leurs revenus.",
      "Le traitement inégal des revenus du travail et du patrimoine.",
      "L'absence totale d'impôt sur les grandes fortunes.",
      "La complexité des formulaires pour les petits contribuables.",
    ],
    correctIndex: 1,
    explanation: "Labour income is visible; wealth income is less so, skewing fairness.",
  },
  {
    id: 35,
    level: "C1",
    passageType: "Article académique",
    passage: "Le concept de « reconnaissance » en politique ne désigne pas seulement la visibilité des minorités. Il concerne la capacité d'un État à montrer que leurs revendications entrent dans le récit national commun. Refuser une commémoration officielle, ce n'est pas effacer un souvenir privé ; c'est signaler que ce souvenir ne fait pas partie de l'histoire que l'État choisit de raconter.",
    question: "Que signifie refuser une commémoration officielle selon le texte ?",
    options: [
      "Qu'on interdit aux citoyens de se souvenir en privé.",
      "Qu'on exclut ce souvenir du récit national promu par l'État.",
      "Qu'on reconnaît officiellement la revendication du groupe.",
      "Qu'on transfère la commémoration aux provinces uniquement.",
    ],
    correctIndex: 1,
    explanation: "It signals the memory is not part of the national story the state tells.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Extrait philosophique",
    passage: "Obéir à la loi par crainte de la sanction diffère d'obéir par respect pour une règle que l'on s'attribue. Le citoyen moderne est censé incarner la seconde attitude, mais les services publics sont conçus pour le premier : formulaires, menaces de pénalité, délais. La civilité démocratique naît lorsque l'institution cesse de supposer que sans contrainte visible, le citoyen déserterait.",
    question: "Quel décalage l'auteur décrit-il ?",
    options: [
      "Entre les lois fédérales et les règlements municipaux.",
      "Entre l'idéal du citoyen autonome et le fonctionnement coercitif des administrations.",
      "Entre le vote obligatoire et le vote volontaire.",
      "Entre les citoyens nés au pays et les naturalisés.",
    ],
    correctIndex: 1,
    explanation: "Citizens are expected to internalize rules, yet services assume fear of penalty.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "La souveraineté populaire est souvent pensée comme une volonté unifiée exprimée le jour du vote. Les théories délibératives rappellent qu'elle se construit dans le temps, par des échanges où les préférences se transforment. Un référendum fige une question ; il ne reproduit pas cette dynamique. D'où le paradoxe : plus la démocratie revendique la participation, plus elle recourt à des instruments binaires qui l'appauvrissent.",
    question: "Quel paradoxe le texte met-il en évidence ?",
    options: [
      "Les référendums augmentent la participation sans clarifier les choix.",
      "La participation délibérative est mise au service d'outils qui la réduisent.",
      "Le vote obligatoire diminue le taux de participation.",
      "Les élections municipales sont moins démocratiques que les fédérales.",
    ],
    correctIndex: 1,
    explanation: "Deliberative democracy uses binary referendums that freeze debate.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai critique",
    passage: "On demande aux nouveaux citoyens de jurer allégeance à un État dont l'histoire inclut des chapitres qu'on leur présente ensuite, dans les musées, comme des « erreurs du passé ». La cérémonie célèbre l'appartenance ; le récit national ultérieur exige la lucidité. Tenir les deux registres sans les confronter, c'est offrir une citoyenneté sentimentale et une citoyenneté critique que peu de discours officiels articulent.",
    question: "Quelle tension le texte souligne-t-il ?",
    options: [
      "Entre l'apprentissage du français et de l'anglais.",
      "Entre la célébration de l'appartenance et la reconnaissance critique de l'histoire.",
      "Entre le droit de vote et le droit de manifester.",
      "Entre les cérémonies locales et fédérales.",
    ],
    correctIndex: 1,
    explanation: "The ceremony celebrates belonging while museums demand critical lucidity about the past.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article spécialisé",
    passage: "Évaluer la « confiance institutionnelle » par sondage suppose que les citoyens distinguent les institutions entre elles. Les travaux comparatifs montrent plutôt un halo : méfiance envers un ministère se propage aux autres, indépendamment de l'expérience directe. Les réformes ciblées peinent donc à restaurer la confiance globale, car ce n'est pas une institution qui est en cause, mais le contrat symbolique entre l'État et le citoyen.",
    question: "Pourquoi les réformes ciblées ont-elles un effet limité ?",
    options: [
      "Parce que les sondages sont toujours manipulés.",
      "Parce que la méfiance se propage entre institutions au-delà de l'expérience vécue.",
      "Parce que les citoyens ne connaissent pas le nom des ministères.",
      "Parce que la confiance ne peut jamais être mesurée.",
    ],
    correctIndex: 1,
    explanation: "A halo effect spreads distrust across institutions beyond direct experience.",
  },
];
