import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

export const TCF_READING_P2: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "PISCINE MUNICIPALE\nOuverture : lundi–vendredi 7h–21h\nSamedi 8h–20h · Dimanche 9h–18h\nFermeture annuelle : 15–31 août",
    question: "Le dimanche, jusqu'à quelle heure la piscine est-elle ouverte ?",
    options: ["Jusqu'à 18h.", "Jusqu'à 20h.", "Jusqu'à 21h.", "Jusqu'à 22h."],
    correctIndex: 0,
    explanation: "Le panneau indique que la piscine ferme à 18h le dimanche.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Annonce",
    passage: "À VENDRE : Vélo de ville, 7 vitesses, bon état, couleur bleue. 150 €. Livraison non incluse. Appeler le 06 12 34 56 78 après 18h.",
    question: "Quand peut-on appeler le vendeur ?",
    options: ["Le matin avant 10h.", "Toute la journée.", "Après 18h.", "Le week-end uniquement."],
    correctIndex: 2,
    explanation: "L'annonce précise d'appeler après 18h.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Chère Fatima,\nJe ne peux pas venir dîner vendredi soir — j'ai un examen samedi matin. On reporte à la semaine prochaine ?\nBisous, Laura",
    question: "Pourquoi Laura ne peut-elle pas venir vendredi ?",
    options: ["Elle est malade.", "Elle travaille.", "Elle a un examen samedi.", "Elle voyage."],
    correctIndex: 2,
    explanation: "Laura annule parce qu'elle a un examen samedi matin et doit se préparer.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Panneau",
    passage: "BIBLIOTHÈQUE UNIVERSITAIRE\n⚠ Silence obligatoire\n📵 Téléphones en mode silencieux\n🍴 Nourriture et boissons interdites\n🐾 Animaux non admis",
    question: "Qu'est-il interdit d'apporter à la bibliothèque ?",
    options: ["Des livres personnels.", "De la nourriture et des boissons.", "Des ordinateurs portables.", "Des casques audio."],
    correctIndex: 1,
    explanation: "Le panneau interdit la nourriture et les boissons à la bibliothèque.",
  },
  {
    id: 5,
    level: "A1",
    passageType: "Formulaire",
    passage: "INSCRIPTION AU COURS DE FRANÇAIS\nNom : _______ Prénom : _______\nNiveau : □ Débutant □ Intermédiaire □ Avancé\nDisponibilités : □ Matin □ Après-midi □ Soir\nFrais d'inscription : 50 € (non remboursables)",
    question: "Les frais d'inscription sont-ils remboursables ?",
    options: ["Oui, totalement.", "Oui, partiellement.", "Non.", "Uniquement en cas d'annulation."],
    correctIndex: 2,
    explanation: "Le formulaire précise que les frais d'inscription de 50 € sont non remboursables.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Email",
    passage: "De : m.dubois@mairie-lyon.fr\nObjet : Confirmation de rendez-vous\n\nBonjour Monsieur Chen,\nVotre rendez-vous pour le renouvellement de votre titre de séjour est confirmé pour le mardi 14 mars à 14h30. Veuillez apporter votre passeport, deux photos d'identité et un justificatif de domicile de moins de 3 mois.\nCordialement,\nService des étrangers",
    question: "Que faut-il apporter au rendez-vous ?",
    options: ["Passeport et contrat de travail.", "Passeport, photos d'identité et justificatif de domicile.", "Carte d'identité et bulletin de salaire.", "Passeport et preuve d'assurance maladie."],
    correctIndex: 1,
    explanation: "Il faut apporter le passeport, deux photos d'identité et un justificatif de domicile de moins de 3 mois.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Affiche",
    passage: "FESTIVAL DE JAZZ DE MONTRÉAL\n29 juin – 8 juillet\nPlus de 300 concerts dans 10 salles\nEntrée gratuite pour les concerts en plein air\nBillets disponibles sur jazzmontreal.com\n🎵 « La plus grande fête jazz au monde »",
    question: "Quels concerts sont gratuits au festival ?",
    options: ["Tous les concerts.", "Les concerts en salle.", "Les concerts en plein air.", "Les concerts le week-end."],
    correctIndex: 2,
    explanation: "L'entrée est gratuite pour les concerts en plein air du festival.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "Note",
    passage: "Rappel — réunion parents-professeurs\nDate : jeudi 16 novembre à 18h\nLieu : Salle polyvalente du collège\nMerci de confirmer votre présence avant le 10 novembre en retournant le coupon ci-dessous.",
    question: "Avant quelle date les parents doivent-ils confirmer leur présence ?",
    options: ["Le 8 novembre.", "Le 10 novembre.", "Le 16 novembre.", "Le 20 novembre."],
    correctIndex: 1,
    explanation: "Les parents doivent confirmer leur présence avant le 10 novembre.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Menu",
    passage: "Menu du jour — 12 €\n• Entrée : Soupe à l'oignon gratinée\n• Plat : Poulet rôti, haricots verts, purée maison\n• Dessert : Tarte tatin\n☕ Café inclus",
    question: "Qu'est-ce qui est inclus dans le menu du jour ?",
    options: ["Un apéritif.", "Un café.", "Un verre de vin.", "Un jus de fruits."],
    correctIndex: 1,
    explanation: "Le menu du jour à 12€ inclut une entrée, un plat, un dessert et le café.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Règlement",
    passage: "RÈGLEMENT DE LA RÉSIDENCE UNIVERSITAIRE\n• Silence entre 22h et 8h\n• Visiteurs autorisés jusqu'à 22h uniquement\n• Animaux interdits\n• Déchets à trier dans les bacs colorés\nTout manquement peut entraîner une expulsion.",
    question: "Jusqu'à quelle heure les visiteurs sont-ils autorisés dans la résidence ?",
    options: ["Jusqu'à 20h.", "Jusqu'à 22h.", "Jusqu'à minuit.", "Jusqu'à 8h du matin."],
    correctIndex: 1,
    explanation: "Le règlement autorise les visiteurs jusqu'à 22h uniquement.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Le covoiturage en France connaît une croissance remarquable. Selon l'ADEME, trois millions de trajets longue distance sont effectués en covoiturage chaque mois. Cette pratique réduit le coût du transport, diminue les émissions de CO₂ et favorise les liens sociaux. Cependant, une enquête révèle que 60 % des utilisateurs abandonnent l'application après le premier trajet, souvent à cause de mauvaises expériences avec des inconnus.",
    question: "Quel est le principal obstacle à la fidélisation des utilisateurs de covoiturage ?",
    options: ["Le prix trop élevé.", "Les mauvaises expériences avec des inconnus.", "La lenteur des trajets.", "Le manque d'applications disponibles."],
    correctIndex: 1,
    explanation: "60% des utilisateurs abandonnent l'appli après le premier trajet, souvent à cause de mauvaises expériences.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Email professionnel",
    passage: "Objet : Modification de votre poste\n\nChère Mme Beaumont,\nSuite à la réorganisation de notre service, nous souhaitons vous proposer une nouvelle affectation au sein de l'équipe commerciale, à compter du 1er janvier. Votre salaire et vos avantages sociaux restent inchangés. Merci de nous faire part de votre accord avant le 15 décembre.",
    question: "Qu'est-ce qui change dans le nouveau poste proposé à Mme Beaumont ?",
    options: ["Son salaire augmente.", "Elle change d'équipe.", "Elle travaille dans une autre ville.", "Son contrat est modifié."],
    correctIndex: 1,
    explanation: "Mme Beaumont est affectée à une nouvelle équipe (commerciale), mais son salaire reste inchangé.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Article",
    passage: "La permaculture est une philosophie agricole inspirée des écosystèmes naturels. Elle repose sur trois éthiques : prendre soin de la terre, prendre soin des gens, et redistribuer équitablement les surplus. En imitant la diversité et la résilience de la nature, la permaculture cherche à créer des systèmes agricoles durables qui nécessitent peu d'intrants externes.",
    question: "Sur quoi la permaculture est-elle basée ?",
    options: ["L'utilisation intensive d'engrais biologiques.", "L'imitation des écosystèmes naturels.", "La monoculture intensive.", "La mécanisation agricole avancée."],
    correctIndex: 1,
    explanation: "La permaculture s'inspire des écosystèmes naturels pour créer des systèmes agricoles durables.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Lettre officielle",
    passage: "Madame, Monsieur,\nNous avons le regret de vous informer que votre dossier de demande d'allocation logement est incomplet. Il manque votre contrat de bail signé. Merci de nous l'envoyer par courrier ou de le déposer en agence sous quinze jours. Passé ce délai, votre dossier sera classé sans suite.",
    question: "Pourquoi le dossier est-il incomplet ?",
    options: ["Il manque les fiches de paie.", "Il manque le contrat de bail signé.", "Il manque les photos d'identité.", "Il manque le justificatif de domicile."],
    correctIndex: 1,
    explanation: "Le dossier est incomplet car le contrat de bail signé manque.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Les bibliothèques publiques se réinventent. Elles ne sont plus uniquement des lieux de prêt de livres : elles proposent désormais des ateliers numériques, des espaces de coworking, et des collections de jeux vidéo ou d'instruments de musique à emprunter. Cette transformation vise à attirer de nouveaux publics et à redevenir des centres de vie communautaire.",
    question: "Comment les bibliothèques publiques se transforment-elles ?",
    options: ["Elles se spécialisent dans les livres rares.", "Elles deviennent des centres de vie avec de nouveaux services.", "Elles réduisent leurs horaires d'ouverture.", "Elles se convertissent en librairies payantes."],
    correctIndex: 1,
    explanation: "Les bibliothèques se diversifient avec des ateliers, coworking et nouvelles collections pour attirer de nouveaux publics.",
  },
  {
    id: 16,
    level: "B2",
    passageType: "Article",
    passage: "Le phénomène des lanceurs d'alerte soulève des questions fondamentales sur l'équilibre entre transparence démocratique et secrets d'État. Des figures comme Edward Snowden ou Julian Assange ont révélé des informations d'intérêt public au prix de lourdes conséquences personnelles. Les législations de protection des lanceurs d'alerte restent insuffisantes dans la plupart des démocraties.",
    question: "Quelle tension principale les lanceurs d'alerte illustrent-ils ?",
    options: ["Entre liberté d'expression et droit à la vie privée.", "Entre transparence démocratique et secrets d'État.", "Entre justice internationale et souveraineté nationale.", "Entre médias et pouvoir politique."],
    correctIndex: 1,
    explanation: "Les lanceurs d'alerte illustrent la tension entre le droit du public à l'information et la protection des secrets d'État.",
  },
  {
    id: 17,
    level: "B2",
    passageType: "Article",
    passage: "La médecine personnalisée, rendue possible par les avancées en génomique, promet de révolutionner les traitements médicaux. En analysant le profil génétique d'un patient, les médecins peuvent prédire sa sensibilité à certains médicaments et adapter les traitements en conséquence. Cette approche est particulièrement prometteuse en oncologie, où les traitements ciblés remplacent peu à peu la chimiothérapie systémique.",
    question: "Dans quel domaine médical la médecine personnalisée est-elle la plus prometteuse ?",
    options: ["La chirurgie cardiaque.", "La psychiatrie.", "L'oncologie.", "La médecine d'urgence."],
    correctIndex: 2,
    explanation: "La médecine personnalisée est particulièrement prometteuse en oncologie, avec des traitements ciblés.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Éditorial",
    passage: "L'économie de l'attention est devenue le modèle dominant du numérique. Les plateformes rivalisent pour capter et retenir notre regard, transformant notre temps en marchandise vendue aux annonceurs. Cette logique a des effets délétères sur la qualité de l'information, la concentration, et le débat démocratique. Réguler ce marché de l'attention est devenu une urgence politique.",
    question: "Quelle est la critique principale formulée contre l'économie de l'attention ?",
    options: ["Elle enrichit excessivement les utilisateurs.", "Elle transforme notre attention en marchandise avec des effets négatifs sur la démocratie.", "Elle rend les médias traditionnels inutiles.", "Elle favorise les contenus étrangers au détriment des contenus locaux."],
    correctIndex: 1,
    explanation: "L'économie de l'attention marchandise notre temps et nuit à la qualité de l'information et au débat démocratique.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement des 15 minutes, popularisé par l'urbaniste Carlos Moreno, imagine une ville où tous les besoins essentiels — travail, courses, santé, loisirs, éducation — sont accessibles à pied ou à vélo en moins de 15 minutes. Cette conception urbaine centrée sur la proximité vise à réduire la dépendance à la voiture et à renforcer les liens de voisinage.",
    question: "Quel est l'objectif principal du concept de « ville des 15 minutes » ?",
    options: ["Éliminer les transports en commun.", "Rendre tous les services accessibles en 15 minutes à pied ou à vélo.", "Construire des villes plus compactes et denses.", "Supprimer les banlieues résidentielles."],
    correctIndex: 1,
    explanation: "Le concept vise à rendre accessibles tous les services essentiels en moins de 15 minutes sans voiture.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article de recherche",
    passage: "Une étude publiée dans Nature Medicine révèle que les inégalités socioéconomiques réduisent l'espérance de vie de façon significative. Dans les pays de l'OCDE, l'écart d'espérance de vie entre les quintiles les plus riches et les plus pauvres atteint en moyenne sept à dix ans. Ces inégalités de santé reflètent les conditions de vie, l'accès aux soins et les comportements liés aux ressources disponibles.",
    question: "Quelle est l'ampleur de l'écart d'espérance de vie entre riches et pauvres dans les pays de l'OCDE ?",
    options: ["2 à 3 ans.", "5 à 6 ans.", "7 à 10 ans.", "Plus de 15 ans."],
    correctIndex: 2,
    explanation: "L'écart d'espérance de vie entre les quintiles les plus riches et les plus pauvres atteint 7 à 10 ans en moyenne.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Article",
    passage: "Le tourisme médical attire chaque année des millions de patients vers des destinations comme la Thaïlande, l'Inde ou la Turquie. Les motivations sont multiples : délais d'attente réduits, coûts moins élevés, ou accès à des traitements non disponibles dans leur pays. Ce phénomène soulève des questions éthiques sur le dumping social et la fuite des cerveaux médicaux des pays en développement.",
    question: "Quelle question éthique le tourisme médical soulève-t-il ?",
    options: ["La qualité des soins dans les pays d'accueil.", "Le dumping social et la fuite des cerveaux médicaux.", "L'absence de réglementation internationale.", "Le financement des systèmes de santé des pays émetteurs."],
    correctIndex: 1,
    explanation: "Le tourisme médical soulève des questions sur le dumping social et la fuite des cerveaux médicaux des pays en développement.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "La question de la citoyenneté numérique devient urgente à l'heure où les algorithmes influencent nos opinions, nos choix de consommation et même nos votes. Former des citoyens capables de comprendre et de critiquer les systèmes algorithmiques est un impératif démocratique. L'éducation aux données doit figurer au même rang que la littératie et la numératie dans les curricula scolaires.",
    question: "Que réclame l'auteur de cette tribune ?",
    options: ["L'interdiction des algorithmes de recommandation.", "L'enseignement de la culture numérique et algorithmique à l'école.", "Un meilleur accès à internet dans les zones rurales.", "La réglementation des données personnelles par l'État."],
    correctIndex: 1,
    explanation: "L'auteur réclame l'intégration de l'éducation aux données dans les programmes scolaires, au même titre que la lecture et les mathématiques.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Article",
    passage: "L'agriculture bio a franchi la barre des 10 % de la surface agricole utile française en 2022. Si cette progression reflète une demande croissante des consommateurs, certains agriculteurs bio dénoncent la concurrence déloyale des importations de produits biologiques certifiés dans des pays aux standards moins stricts. La définition et le contrôle du label bio restent des enjeux majeurs.",
    question: "Quel problème les agriculteurs bio français soulèvent-ils ?",
    options: ["Le manque de subventions pour la conversion bio.", "La concurrence d'importations bio aux standards moins stricts.", "La difficulté à obtenir la certification bio.", "Le prix trop bas des produits bio sur les marchés."],
    correctIndex: 1,
    explanation: "Les agriculteurs bio dénoncent la concurrence d'importations certifiées dans des pays aux standards moins exigeants.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement de désinstitutionnalisation psychiatrique, amorcé dans les années 1970, a cherché à réintégrer les patients dans la communauté plutôt que de les maintenir en hôpital psychiatrique. Si cette réforme a été bénéfique pour de nombreux patients, elle a également contribué à la croissance de la population sans domicile fixe dans certaines grandes villes, faute de structures d'accompagnement suffisantes.",
    question: "Quelle conséquence involontaire la désinstitutionnalisation a-t-elle eue ?",
    options: ["Une augmentation du nombre de rechutes psychiatriques.", "Une croissance de la population SDF faute de structures d'accompagnement.", "Un refus des patients de prendre leurs médicaments.", "Une surcharge des urgences psychiatriques."],
    correctIndex: 1,
    explanation: "Sans structures d'accompagnement suffisantes, certains patients ont grossi les rangs des sans-domicile fixe.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Le Conseil de l'Europe a adopté une résolution appelant les États membres à inclure l'éducation aux droits de l'homme dans les programmes scolaires obligatoires. Cette initiative vise à contrer la montée des discours haineux, des extrémismes et du rejet de l'autre. L'éducation civique est présentée comme le premier rempart contre les dérives antidémocratiques.",
    question: "Quel est l'objectif de la résolution du Conseil de l'Europe sur l'éducation aux droits de l'homme ?",
    options: ["Former des juristes spécialisés en droits de l'homme.", "Contrer la montée des discours haineux et des extrémismes.", "Promouvoir l'entrée dans les institutions européennes.", "Harmoniser les systèmes éducatifs européens."],
    correctIndex: 1,
    explanation: "La résolution vise à contrer la montée des discours haineux et des extrémismes par l'éducation aux droits de l'homme.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    passageType: "Extrait philosophique",
    passage: "La reconnaissance, au sens hégélien, n'est pas un simple acte de politesse sociale : elle est la condition de possibilité de la conscience de soi. C'est dans l'autre, et par la médiation du regard de l'autre, que le sujet se constitue comme sujet. Axel Honneth, héritier de cette tradition, distingue trois sphères de reconnaissance : l'amour, le droit et l'estime sociale, dont la privation engendre des pathologies sociales et des luttes de reconnaissance.",
    question: "Que signifie la « reconnaissance » dans la tradition hégélienne selon ce texte ?",
    options: ["Un acte de gratitude entre individus.", "La condition par laquelle le sujet se constitue à travers le regard de l'autre.", "Un droit légal à être identifié par l'État.", "La conscience de ses propres mérites."],
    correctIndex: 1,
    explanation: "Dans la tradition hégélienne, la reconnaissance est la condition de la conscience de soi — le sujet se constitue par le regard de l'autre.",
  },
  {
    id: 27,
    level: "C1",
    passageType: "Article académique",
    passage: "La notion de résilience a migré de l'écologie vers les sciences sociales, où elle désigne la capacité d'un individu, d'un groupe ou d'un système à surmonter une adversité significative et à se réorganiser positivement. Les critiques de ce concept soulignent qu'il peut être instrumentalisé pour responsabiliser les individus de leur propre malheur, masquant les structures sociales qui produisent la vulnérabilité.",
    question: "Quelle critique est formulée à l'égard du concept de résilience ?",
    options: ["Il ne s'applique qu'aux systèmes naturels.", "Il peut servir à responsabiliser les individus tout en masquant les causes structurelles.", "Il est trop vague pour être opérationnel.", "Il néglige le rôle de la communauté dans le soutien."],
    correctIndex: 1,
    explanation: "La critique principale est que la résilience peut individualiser la responsabilité en occultant les structures sociales productrices de vulnérabilité.",
  },
  {
    id: 28,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Il avait appris deux langues simultanément, comme on apprend à nager dans deux océans différents — chacun avec ses courants, ses profondeurs et ses dangers propres. Sa langue maternelle était un pays intérieur qu'il habitait la nuit, dans ses rêves. La langue d'adoption était l'armure qu'il revêtait le matin pour affronter le monde. Entre les deux, il y avait lui — ni tout à fait l'un, ni tout à fait l'autre.",
    question: "Quelle image l'auteur utilise-t-il pour décrire la langue maternelle ?",
    options: ["Une armure protectrice.", "Un pays intérieur habité dans les rêves.", "Un océan dangereux.", "Une langue morte."],
    correctIndex: 1,
    explanation: "L'auteur décrit la langue maternelle comme un pays intérieur habité la nuit, dans les rêves.",
  },
  {
    id: 29,
    level: "C1",
    passageType: "Essai",
    passage: "La crise de la représentation politique dans les démocraties occidentales se manifeste par des taux d'abstention records et une défiance croissante envers les partis traditionnels. Mais réduire cette crise à un simple désintérêt des citoyens serait une erreur : de nombreux travaux de science politique montrent que les citoyens ne se désengagent pas de la politique mais changent de répertoire d'action — boycotts, pétitions, manifestations, hacktivisme.",
    question: "Comment les auteurs de science politique interprètent-ils la désaffection électorale ?",
    options: ["Comme une forme de résignation politique.", "Comme un changement de formes d'engagement, pas un désintérêt.", "Comme le signe d'un système politique sain.", "Comme une réaction à l'incompétence des gouvernements."],
    correctIndex: 1,
    explanation: "Les citoyens ne se désengagent pas mais changent de formes d'action politique (pétitions, manifestations, etc.).",
  },
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "Les études de genre ont montré que le langage n'est pas neutre : le générique masculin, longtemps présenté comme une convention grammaticale anodine, véhicule et renforce une vision du monde androcentrée. L'écriture inclusive, qu'il s'agisse du point médian ou des formulations épicènes, cherche à rendre visible la mixité dans le langage. Ses détracteurs y voient une complication inutile ; ses partisans, un acte politique de visibilisation.",
    question: "Que cherche à faire l'écriture inclusive selon ses partisans ?",
    options: ["Simplifier la grammaire française.", "Rendre la mixité visible dans le langage en contestant le générique masculin.", "Remplacer le français par une langue neutre.", "Faciliter l'apprentissage du français par les non-francophones."],
    correctIndex: 1,
    explanation: "L'écriture inclusive vise à rendre visible la mixité dans le langage, contestant l'androcentrisme du générique masculin.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Article de presse",
    passage: "Le concept d'appropriation culturelle fait l'objet de vifs débats. D'un côté, des militants des droits des minorités estiment que l'adoption d'éléments culturels marginalisés par des membres de groupes dominants constitue une forme d'exploitation symbolique. De l'autre, des philosophes libéraux défendent la liberté d'emprunts culturels comme condition d'un métissage culturel fécond.",
    question: "Sur quel désaccord porte le débat sur l'appropriation culturelle ?",
    options: ["Sur la définition de la culture populaire.", "Sur l'exploitation symbolique des emprunts culturels versus la liberté d'échange culturel.", "Sur la propriété légale des œuvres artistiques.", "Sur les droits des artistes en exil."],
    correctIndex: 1,
    explanation: "Le débat oppose ceux qui voient l'appropriation comme une exploitation symbolique à ceux qui défendent le droit au métissage culturel.",
  },
  {
    id: 32,
    level: "C2",
    passageType: "Extrait philosophique — Derrida",
    passage: "La déconstruction derridienne ne cherche pas à détruire les textes mais à révéler leurs contradictions internes, les hiérarchies implicites qu'ils instituent et les présupposés qu'ils naturalisent. Toute opposition binaire — présence/absence, parole/écriture, nature/culture — dissimule une hiérarchie où un terme est valorisé au détriment de l'autre. Déconstruire, c'est inverser provisoirement cette hiérarchie pour en exposer l'arbitraire.",
    question: "Quel est l'objectif de la déconstruction selon Derrida ?",
    options: ["Détruire les textes canoniques de la philosophie occidentale.", "Révéler les contradictions et hiérarchies implicites des textes en exposant leur arbitraire.", "Proposer une lecture plus objective des textes philosophiques.", "Démontrer la supériorité de l'écriture sur la parole."],
    correctIndex: 1,
    explanation: "La déconstruction vise à révéler les hiérarchies et contradictions implicites des textes pour en exposer l'arbitraire.",
  },
  {
    id: 33,
    level: "C2",
    passageType: "Extrait littéraire — Gabrielle Roy",
    passage: "Elle regardait la plaine qui s'étendait à perte de vue, cette plaine manitobaine que ses parents avaient traversée avec si peu de certitudes mais tant d'espoir. Le vent y portait encore des mots dans deux langues, comme si la terre elle-même avait absorbé les prières et les injures, les chants du soir et les silences du matin d'une humanité en transit perpétuel vers un horizon qui reculait toujours.",
    question: "Quelle image littéraire caractérise la plaine manitobaine dans cet extrait ?",
    options: ["Un désert hostile et stérile.", "Un espace absorbant les mémoires et les langues d'une humanité en transit.", "Un territoire sauvage non encore colonisé.", "Un paysage pastoral harmonieux."],
    correctIndex: 1,
    explanation: "La plaine est décrite comme un espace mémoriel absorbant les langues et l'histoire d'une humanité en passage perpétuel.",
  },
  {
    id: 34,
    level: "C2",
    passageType: "Article académique",
    passage: "Le concept de biopolitique, développé par Foucault puis repris par Agamben et Esposito, désigne les mécanismes par lesquels les États modernes exercent leur pouvoir non plus seulement sur les territoires mais sur la vie elle-même des populations. La gestion des épidémies, la démographie, les politiques de santé publique et de reproduction sont autant d'expressions de ce pouvoir sur la vie.",
    question: "Que désigne la biopolitique dans la tradition foucaldienne ?",
    options: ["La politique des partis écologistes.", "Le pouvoir des États sur la vie des populations à travers la santé, la démographie, etc.", "La résistance citoyenne aux politiques sanitaires.", "Le rôle des biologistes dans les décisions politiques."],
    correctIndex: 1,
    explanation: "La biopolitique désigne l'exercice du pouvoir étatique sur la vie des populations — santé, reproduction, démographie.",
  },
  {
    id: 35,
    level: "C2",
    passageType: "Essai",
    passage: "Le nihilisme, tel que Nietzsche l'analyse dans La Volonté de puissance, n'est pas une philosophie du néant mais un diagnostic historique : c'est le moment où les valeurs suprêmes se dévaluent elles-mêmes. La mort de Dieu n'est pas un événement théologique mais la constatation que le fondement transcendant de toute valeur s'est effondré. La question qui s'ouvre alors est de savoir si l'humanité est capable de créer de nouvelles valeurs sans cet appui.",
    question: "Comment Nietzsche définit-il le nihilisme selon cet extrait ?",
    options: ["Comme la négation de tout principe moral.", "Comme le moment historique où les valeurs suprêmes se dévaluent elles-mêmes.", "Comme une philosophie pessimiste issue du romantisme.", "Comme la conséquence logique de l'athéisme moderne."],
    correctIndex: 1,
    explanation: "Le nihilisme nietzschéen est un diagnostic historique : le moment où les valeurs fondatrices perdent leur légitimité transcendante.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Article académique",
    passage: "L'historiographie des Annales, fondée par Lucien Febvre et Marc Bloch, a opéré une révolution dans l'écriture de l'histoire en déplaçant le regard des grands hommes et événements politiques vers les structures longues, les mentalités collectives et les faits économiques et sociaux. La longue durée, notion braudélienne, désigne ces rythmes quasi immobiles de l'histoire qui échappent à la conscience des contemporains.",
    question: "Quelle révolution l'École des Annales a-t-elle opérée ?",
    options: ["Elle a introduit les méthodes quantitatives dans l'histoire.", "Elle a déplacé l'attention des événements politiques vers les structures longues et les mentalités.", "Elle a accordé la priorité aux sources orales sur les sources écrites.", "Elle a adopté une approche marxiste de l'histoire."],
    correctIndex: 1,
    explanation: "L'École des Annales a révolutionné l'historiographie en s'intéressant aux structures de longue durée et aux mentalités collectives plutôt qu'aux événements.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Essai",
    passage: "L'utilitarisme benthamien évalue la moralité d'un acte à l'aune de ses conséquences sur le bien-être collectif : est bon ce qui maximise le bonheur du plus grand nombre. Cette théorie, séduisante par sa simplicité, se heurte à de sérieux problèmes : elle peut justifier des injustices individuelles au nom de l'intérêt général, et sa mesure du bonheur reste problématique — peut-on vraiment comparer et agréger les états subjectifs ?",
    question: "Quelle est la limite principale de l'utilitarisme benthamien évoquée dans ce texte ?",
    options: ["Il ignore les droits des animaux non humains.", "Il peut justifier des injustices individuelles au nom du bien collectif.", "Il dépend d'une vision religieuse du bonheur.", "Il s'applique uniquement aux sociétés industrielles."],
    correctIndex: 1,
    explanation: "L'utilitarisme peut justifier des injustices envers des individus si cela maximise le bien-être collectif.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Article académique",
    passage: "La « nouvelle critique » des années 1950–60, notamment la lecture déconstructive et le structuralisme de Barthes, a proclamé la mort de l'auteur : l'intention de l'auteur ne saurait être un critère d'interprétation valide, car le texte, une fois produit, devient un espace pluriel où se croisent mille citations. Cette thèse a renouvelé la critique littéraire mais suscite aujourd'hui des résistances de la part des approches herméneutiques qui réhabilitent le contexte d'énonciation.",
    question: "Que signifie la « mort de l'auteur » chez Barthes ?",
    options: ["L'auteur doit rester anonyme pour que l'œuvre soit valide.", "L'intention de l'auteur ne peut être un critère d'interprétation : le texte est autonome.", "L'auteur n'est pas propriétaire de son texte.", "L'auteur doit mourir symboliquement avant de publier."],
    correctIndex: 1,
    explanation: "La mort de l'auteur signifie que l'intention de l'auteur n'est pas un critère valide d'interprétation — le texte est un espace autonome de significations.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Essai",
    passage: "L'idéologie, au sens marxiste, n'est pas un simple ensemble de fausses croyances : c'est un système de représentations qui permet aux classes dominantes de présenter leurs intérêts particuliers comme des intérêts universels, naturels et immuables. Althusser a prolongé cette analyse en distinguant les appareils idéologiques d'État — école, famille, Église, médias — des appareils répressifs, arguant que les premiers assurent la reproduction des rapports sociaux sans recours à la force.",
    question: "Comment Althusser distingue-t-il les appareils idéologiques des appareils répressifs de l'État ?",
    options: ["Les appareils idéologiques utilisent la force ; les répressifs, la persuasion.", "Les appareils idéologiques assurent la reproduction sociale sans force ; les répressifs recourent à la contrainte.", "Les appareils idéologiques sont privés ; les répressifs, publics.", "Les appareils idéologiques s'occupent de culture ; les répressifs, d'économie."],
    correctIndex: 1,
    explanation: "Les appareils idéologiques (école, famille, médias) assurent la reproduction sociale par la persuasion, les répressifs par la force.",
  },
];
