import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Mock-aligned expansion — everyday + exam-theme lexique (not IRCC admin). */
export const BATCH5_A: LemmaRow[] = [
  ["Weather forecast", "les prévisions météo", "Consultez les prévisions météo avant de sortir."],
  ["Heat wave", "la vague de chaleur", "La vague de chaleur dure trois jours."],
  ["Snowstorm", "la tempête de neige", "La tempête de neige ferme plusieurs routes."],
  ["Umbrella", "le parapluie", "N'oubliez pas votre parapluie cet après-midi."],
  ["Grocery list", "la liste d'épicerie", "Préparez la liste d'épicerie pour la semaine."],
  ["Organic food", "les aliments biologiques", "Les aliments biologiques coûtent un peu plus cher."],
  ["Expiry date", "la date de péremption", "Vérifiez la date de péremption sur le lait."],
  ["Recipe", "la recette", "Suivez la recette pas à pas."],
  ["Kitchen appliance", "l'électroménager", "L'électroménager est garanti deux ans."],
  ["Neighbourhood", "le quartier", "Notre quartier est calme et familial."],
  ["Sidewalk", "le trottoir", "Le trottoir est glissant après la pluie."],
  ["Crossing light", "le feu piéton", "Attendez le feu piéton avant de traverser."],
  ["Bike lane", "la piste cyclable", "La piste cyclable longe le parc."],
  ["Car pool", "le covoiturage", "Le covoiturage réduit les frais de transport."],
  ["Highway exit", "la sortie d'autoroute", "Prenez la sortie d'autoroute numéro douze."],
  ["Toll booth", "le péage", "Le péage accepte la carte de crédit."],
  ["Gas station", "la station-service", "La station-service est ouverte vingt-quatre heures."],
  ["Driver's licence", "le permis de conduire", "Renouvelez votre permis de conduire en ligne."],
  ["Insurance claim", "la réclamation d'assurance", "Déposez une réclamation d'assurance après l'accident."],
  ["Appointment reminder", "le rappel de rendez-vous", "Vous recevrez un rappel de rendez-vous par texto."],
  ["Waiting list", "la liste d'attente", "Votre nom est sur la liste d'attente."],
  ["Public holiday", "le jour férié", "Le jour férié tombe un lundi cette année."],
  ["Opening ceremony", "la cérémonie d'ouverture", "La cérémonie d'ouverture commence à dix heures."],
  ["Ticket office", "la billetterie", "La billetterie ferme trente minutes avant le spectacle."],
  ["Museum exhibit", "l'exposition du musée", "L'exposition du musée est gratuite le jeudi."],
  ["Guided tour", "la visite guidée", "La visite guidée dure une heure."],
  ["Souvenir shop", "la boutique de souvenirs", "La boutique de souvenirs accepte les cartes."],
  ["Campground", "le terrain de camping", "Le terrain de camping exige une réservation."],
  ["Hiking trail", "le sentier de randonnée", "Le sentier de randonnée est bien balisé."],
  ["Wildlife", "la faune", "La faune locale inclut plusieurs espèces d'oiseaux."],
  ["Pollution alert", "l'alerte à la pollution", "Une alerte à la pollution est en vigueur."],
  ["Air quality", "la qualité de l'air", "La qualité de l'air est mauvaise aujourd'hui."],
  ["Power outage", "la panne d'électricité", "La panne d'électricité devrait durer une heure."],
  ["Water restriction", "la restriction d'eau", "Une restriction d'eau est annoncée en été."],
];

export const BATCH5_B: LemmaRow[] = [
  ["Remote work", "le télétravail", "Le télétravail est autorisé deux jours par semaine."],
  ["Team meeting", "la réunion d'équipe", "La réunion d'équipe est reportée à jeudi."],
  ["Deadline", "la date limite", "La date limite est fixée au vendredi."],
  ["Job posting", "l'offre d'emploi", "L'offre d'emploi est publiée en ligne."],
  ["Salary range", "la fourchette salariale", "La fourchette salariale est indiquée dans l'annonce."],
  ["Work schedule", "l'horaire de travail", "L'horaire de travail change chaque mois."],
  ["Staff training", "la formation du personnel", "La formation du personnel a lieu en janvier."],
  ["Customer feedback", "la rétroaction client", "La rétroaction client améliore le service."],
  ["Online shopping", "les achats en ligne", "Les achats en ligne sont livrés en deux jours."],
  ["Return policy", "la politique de retour", "La politique de retour permet trente jours."],
  ["Warranty", "la garantie", "La garantie couvre les pièces et la main-d'œuvre."],
  ["Budget", "le budget", "Le budget familial inclut le loyer et l'épicerie."],
  ["Inflation", "l'inflation", "L'inflation augmente le coût de la vie."],
  ["Interest rate", "le taux d'intérêt", "Le taux d'intérêt influence les prêts hypothécaires."],
  ["Savings account", "le compte d'épargne", "Le compte d'épargne rapporte un faible intérêt."],
  ["Tax return", "la déclaration de revenus", "Déposez votre déclaration de revenus avant le trente avril."],
  ["Public transport", "les transports en commun", "Les transports en commun sont moins chers qu'une voiture."],
  ["Rush ticket", "le billet de dernière minute", "Le billet de dernière minute coûte plus cher."],
  ["Primary school", "l'école primaire", "L'école primaire accueille les enfants de six à douze ans."],
  ["Secondary school", "l'école secondaire", "L'école secondaire prépare au diplôme."],
  ["Tuition fees", "les frais de scolarité", "Les frais de scolarité augmentent chaque année."],
  ["Scholarship", "la bourse d'études", "La bourse d'études couvre une partie des frais."],
  ["Research project", "le projet de recherche", "Le projet de recherche dure dix-huit mois."],
  ["Library card", "la carte de bibliothèque", "La carte de bibliothèque est gratuite pour les résidents."],
  ["Language course", "le cours de langue", "Le cours de langue se donne le soir."],
  ["Childcare centre", "la garderie", "La garderie ouvre à sept heures du matin."],
  ["Elderly care", "les soins aux personnes âgées", "Les soins aux personnes âgées demandent de la patience."],
  ["Mental health", "la santé mentale", "La santé mentale est aussi importante que la santé physique."],
  ["Vaccination", "la vaccination", "La vaccination protège contre plusieurs maladies."],
  ["Waiting time", "le temps d'attente", "Le temps d'attente à l'urgence est long ce soir."],
  ["Social media", "les réseaux sociaux", "Les réseaux sociaux influencent l'opinion publique."],
  ["Fake news", "les fausses nouvelles", "Vérifiez la source avant de partager des fausses nouvelles."],
  ["Press conference", "la conférence de presse", "La conférence de presse commence à quatorze heures."],
  ["Public debate", "le débat public", "Le débat public porte sur le transport."],
  ["Citizen participation", "la participation citoyenne", "La participation citoyenne renforce la démocratie."],
  ["Renewable energy", "l'énergie renouvelable", "L'énergie renouvelable réduit les émissions."],
  ["Carbon footprint", "l'empreinte carbone", "Réduisez votre empreinte carbone en transport en commun."],
  ["Climate change", "le changement climatique", "Le changement climatique affecte les régions polaires."],
  ["Recycling program", "le programme de recyclage", "Le programme de recyclage accepte le verre et le plastique."],
  ["Compost bin", "le bac à compost", "Déposez les restes de fruits dans le bac à compost."],
];

export const BATCH5_C: LemmaRow[] = [
  ["Nevertheless", "néanmoins", "Néanmoins, la proposition mérite d'être examinée."],
  ["Furthermore", "de plus", "De plus, les coûts cachés augmentent le total."],
  ["On the contrary", "au contraire", "Au contraire, les résultats confirment l'hypothèse."],
  ["In contrast", "en revanche", "En revanche, la région sud connaît une sécheresse."],
  ["To highlight", "souligner", "Il importe de souligner les limites de l'étude."],
  ["To challenge", "remettre en question", "Les chercheurs remettent en question cette théorie."],
  ["To advocate", "prôner", "Plusieurs experts prônent une réforme progressive."],
  ["To undermine", "saper", "Cette erreur peut saper la crédibilité du rapport."],
  ["Widespread", "répandu", "Un malentendu répandu circule sur les réseaux."],
  ["Controversial", "controversé", "Le projet controversé divise les élus."],
  ["Ambiguous", "ambigu", "Le message ambigu prête à confusion."],
  ["Inevitable", "inévitable", "Un changement demographique inévitable est annoncé."],
  ["Plausible", "plausible", "L'explication plausible convainc le jury."],
  ["Misleading", "trompeur", "Le titre trompeur ne reflète pas le contenu."],
  ["To summarize", "résumer", "Pour résumer, trois points méritent attention."],
  ["In conclusion", "en conclusion", "En conclusion, la mesure reste nécessaire."],
  ["From my perspective", "de mon point de vue", "De mon point de vue, l'équilibre est fragile."],
  ["It goes without saying", "il va sans dire", "Il va sans dire que la sécurité est prioritaire."],
  ["All things considered", "tout bien pesé", "Tout bien pesé, les avantages l'emportent."],
  ["To a certain extent", "dans une certaine mesure", "Dans une certaine mesure, la loi répond au problème."],
  ["Public opinion", "l'opinion publique", "L'opinion publique évolue rapidement sur ce dossier."],
  ["Policy maker", "le décideur public", "Le décideur public consulte les experts."],
  ["Stakeholder", "la partie prenante", "Chaque partie prenante défend ses intérêts."],
  ["Short-sighted", "myope", "Une politique myope ignore les conséquences futures."],
  ["Long-term impact", "l'impact à long terme", "L'impact à long terme reste incertain."],
];
