import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Master A — A1–A2 lexique: services, forms, time, numbers, shopping, transport, communication. */
export const MASTER_A: LemmaRow[] = [
  ["Midnight", "minuit", "La bibliothèque ferme à minuit le vendredi."],
  ["Noon sharp", "midi pile", "Le déjeuner est servi à midi pile."],
  ["Half past two", "deux heures et demie", "Le cours reprend à deux heures et demie."],
  ["Quarter past nine", "neuf heures quinze", "Le bus part à neuf heures quinze."],
  ["Quarter to six", "six heures moins le quart", "Nous arrivons à six heures moins le quart."],
  ["On the dot", "à l'heure exacte", "Soyez à l'heure exacte pour l'examen."],
  ["Fortnight", "la quinzaine", "La quinzaine commence lundi prochain."],
  ["Weekday", "un jour de semaine", "Le service est ouvert chaque jour de semaine."],
  ["Public holiday eve", "la veille du jour férié", "La veille du jour férié, les magasins ferment tôt."],
  ["Alarm clock", "le réveil", "Réglez le réveil à six heures trente."],
  ["Wall clock", "l'horloge murale", "L'horloge murale est en retard de cinq minutes."],
  ["Digital display", "l'affichage numérique", "L'affichage numérique indique la prochaine rame."],
  ["Spring season", "le printemps", "Au printemps, les journées s'allongent."],
  ["Autumn season", "l'automne", "En automne, les feuilles tombent dans le parc."],
  ["Daybreak", "l'aube", "Nous partons à l'aube pour éviter la chaleur."],
  ["Sunset", "le coucher du soleil", "Le coucher du soleil est magnifique sur la plage."],
  ["Early morning", "le petit matin", "Le petit matin est calme dans le quartier."],
  ["Late evening", "la fin de soirée", "La fin de soirée est réservée aux adultes."],
  ["Once a week", "une fois par semaine", "Le marché a lieu une fois par semaine."],
  ["Twice a month", "deux fois par mois", "Je paie le loyer deux fois par mois par erreur non."],
  ["Every other day", "un jour sur deux", "L'infirmière passe un jour sur deux."],
  ["From time to time", "de temps en temps", "De temps en temps, le train arrive en avance."],
  ["On time", "à l'heure", "Le colis est arrivé à l'heure prévue."],
  ["Behind schedule", "en retard sur l'horaire", "Le chantier est en retard sur l'horaire."],
  ["Ahead of schedule", "en avance sur l'horaire", "Les travaux sont en avance sur l'horaire."],
  ["Local time", "l'heure locale", "L'heure locale est affichée à l'aéroport."],
  ["Duration", "la durée", "La durée du film est de deux heures."],
  ["A moment", "un instant", "Un instant, je vérifie votre dossier."],
  ["A pause", "une pause", "Faites une pause de dix minutes."],
  ["A century", "un siècle", "Ce bâtiment date du siècle dernier."],
  ["A decade", "une décennie", "Une décennie s'est écoulée depuis l'ouverture."],
  ["A dozen", "une douzaine", "J'achète une douzaine d'œufs."],
  ["A pair", "une paire", "J'ai besoin d'une paire de gants."],
  ["Half a dozen", "une demi-douzaine", "Prenez une demi-douzaine de croissants."],
  ["Even number", "le nombre pair", "Choisissez un nombre pair sur le formulaire."],
  ["Odd number", "le nombre impair", "Votre place est un nombre impair."],
  ["To count", "compter", "Comptez jusqu'à vingt avant de commencer."],
  ["To add", "additionner", "Additionnez les deux montants sur la facture."],
  ["To subtract", "soustraire", "Soustrayez la réduction du total."],
  ["Percent", "le pour cent", "Une réduction de dix pour cent est appliquée."],
  ["Fraction", "la fraction", "Indiquez la fraction sur la ligne pointillée."],
  ["Average", "la moyenne", "La moyenne des notes est affichée en bas."],
  ["Subtotal", "le sous-total", "Le sous-total apparaît avant les taxes."],
  ["Approximately", "environ", "Le trajet dure environ quarante minutes."],
  ["Exactly", "exactement", "Le prix est exactement quinze euros."],
  ["More than", "plus de", "Il reste plus de cinq places."],
  ["Less than", "moins de", "L'attente est de moins de dix minutes."],
  ["At least", "au moins", "Réservez au moins deux jours à l'avance."],
  ["At most", "au plus", "Le bagage pèse au plus vingt kilos."],
  ["Equal to", "égal à", "Le montant doit être égal à zéro."],
  ["Zero balance", "le solde zéro", "Le solde zéro est requis pour fermer le compte."],
  ["One thousand", "mille", "Le loyer est de mille dollars par mois."],
  ["First floor (EU)", "le rez-de-chaussée", "L'accueil se trouve au rez-de-chaussée."],
  ["Second floor (EU)", "le premier étage", "Mon bureau est au premier étage."],
  ["Third in line", "troisième dans la file", "Vous êtes troisième dans la file."],
  ["The previous day", "la veille", "Inscrivez-vous la veille de la visite."],
  ["The following day", "le lendemain", "Le lendemain, le bureau rouvre à huit heures."],
  ["Soon", "bientôt", "Le médecin vous recevra bientôt."],
  ["Recently", "récemment", "J'ai récemment changé d'adresse."],
  ["Already", "déjà", "Avez-vous déjà rempli le formulaire?"],
  ["Still waiting", "toujours en attente", "Je suis toujours en attente d'une réponse."],
  ["Not yet", "pas encore", "Le dossier n'est pas encore complet."],
  ["Never", "jamais", "Ne quittez jamais vos bagages sans surveillance."],
  ["Always", "toujours", "Fermez toujours la porte derrière vous."],
  ["Sometimes", "parfois", "Parfois, le guichet ferme plus tôt."],
  ["Often", "souvent", "Ce bus passe souvent en retard."],
  ["Rarely", "rarement", "Le train est rarement à l'heure l'hiver."],
  ["Seldom", "guère", "On trouve guère de places le samedi."],
  ["Yesterday morning", "hier matin", "Hier matin, la ligne était coupée."],
  ["Tomorrow afternoon", "demain après-midi", "Demain après-midi, le cours est annulé."],
  ["This weekend", "ce week-end", "Ce week-end, le musée est gratuit."],
  ["Next month", "le mois prochain", "Le renouvellement est prévu le mois prochain."],
  ["Last year", "l'année dernière", "L'année dernière, les tarifs ont augmenté."],
  ["Annual event", "l'événement annuel", "L'événement annuel attire beaucoup de visiteurs."],
  ["Daily rate", "le tarif journalier", "Le tarif journalier inclut le petit-déjeuner."],
  ["Hourly wage", "le salaire horaire", "Le salaire horaire est affiché sur l'affiche."],
  ["Per person", "par personne", "Le prix est de vingt dollars par personne."],
  ["Per night", "par nuit", "La chambre coûte quatre-vingts euros par nuit."],
  ["Free of charge", "gratuit", "L'entrée est gratuite pour les enfants."],
  ["Fixed price", "le prix fixe", "Le menu est à prix fixe le midi."],
  ["Maiden name", "le nom de jeune fille", "Inscrivez votre nom de jeune fille si demandé."],
  ["Marital status", "la situation familiale", "Cochez votre situation familiale sur le formulaire."],
  ["Place of birth", "le lieu de naissance", "Le lieu de naissance doit figurer sur l'acte."],
  ["Nationality field", "la nationalité", "Indiquez votre nationalité dans la case prévue."],
  ["Occupation field", "la profession", "Écrivez votre profession en lettres moulées."],
  ["Employer name", "l'employeur", "Le nom de l'employeur est obligatoire."],
  ["Student number", "le numéro d'étudiant", "Votre numéro d'étudiant se trouve sur la carte."],
  ["Reference number", "le numéro de référence", "Conservez le numéro de référence de votre demande."],
  ["Case file number", "le numéro de dossier", "Mentionnez le numéro de dossier dans chaque courriel."],
  ["To fill in", "remplir", "Remplissez toutes les pages du formulaire."],
  ["To print out", "imprimer", "Imprimez le reçu après le paiement en ligne."],
  ["To scan", "numériser", "Numérisez le document en couleur."],
  ["To upload", "téléverser", "Téléversez le fichier au format PDF."],
  ["To download", "télécharger", "Téléchargez le guide avant votre visite."],
  ["Blank line", "la ligne vide", "Laissez une ligne vide entre les sections."],
  ["Ballpoint pen", "le stylo à bille", "Utilisez un stylo à bille bleu ou noir."],
  ["Ink pen", "le stylo à encre", "Le stylo à encre n'est pas accepté sur ce formulaire."],
  ["Eraser", "la gomme", "Une gomme propre évite les trous dans le papier."],
  ["Ruler", "la règle", "Tracez une ligne droite avec une règle."],
  ["Stapler", "l'agrafeuse", "L'agrafeuse est prêtée à l'accueil."],
  ["Paper clip", "le trombone", "Joignez les pages avec un trombone."],
  ["File folder", "le classeur", "Rangez les originaux dans un classeur."],
  ["Envelope", "l'enveloppe", "Glissez le formulaire dans l'enveloppe fournie."],
  ["Self-addressed envelope", "l'enveloppe affranchie", "Joignez une enveloppe affranchie pour la réponse."],
  ["Witness", "le témoin", "Le témoin signe à côté de votre nom."],
  ["Guardian", "le tuteur", "Le tuteur signe pour l'enfant mineur."],
  ["Spouse", "le conjoint", "Le conjoint peut être inscrit sur la même demande."],
  ["Dependent child", "l'enfant à charge", "Indiquez chaque enfant à charge."],
  ["Next of kin", "le proche parent", "Le proche parent est contacté en cas d'urgence."],
  ["Permanent address", "l'adresse permanente", "L'adresse permanente ne doit pas être un case postal."],
  ["Temporary address", "l'adresse temporaire", "Signalez toute adresse temporaire de moins de six mois."],
  ["Proof of address", "un justificatif de domicile", "Apportez un justificatif de domicile récent."],
  ["Proof of income", "un justificatif de revenu", "Un justificatif de revenu peut être exigé."],
  ["Pay stub", "le talon de paie", "Joignez votre dernier talon de paie."],
  ["Tax slip", "le relevé d'impôt", "Le relevé d'impôt prouve vos revenus."],
  ["Multiple choice", "le choix multiple", "Répondez au choix multiple en noircissant le cercle."],
  ["True or false", "vrai ou faux", "Cochez vrai ou faux pour chaque affirmation."],
  ["Official stamp", "le cachet officiel", "Le cachet officiel valide la copie."],
  ["Certified translation", "la traduction certifiée", "Une traduction certifiée accompagne les documents étrangers."],
  ["Original required", "l'original exigé", "L'original exigé sera retourné sur place."],
  ["Photocopy accepted", "la photocopie acceptée", "Une photocopie acceptée suffit pour cette étape."],
  ["Legible writing", "l'écriture lisible", "Une écriture lisible accélère le traitement."],
  ["Block capitals", "les lettres majuscules", "Écrivez votre nom en lettres majuscules."],
  ["Date of issue", "la date d'émission", "La date d'émission figure au bas du certificat."],
  ["Place of issue", "le lieu d'émission", "Le lieu d'émission est indiqué sur le passeport."],
  ["Reason for request", "le motif de la demande", "Expliquez brièvement le motif de la demande."],
  ["Purpose of visit", "le but de la visite", "Le but de la visite doit être clair à l'accueil."],
  ["Supporting document", "la pièce justificative", "Chaque pièce justificative est listée à l'annexe."],
  ["Optional section", "la section facultative", "La section facultative peut rester vide."],
  ["Applicant signature", "la signature du demandeur", "La signature du demandeur date le formulaire."],
  ["Office stamp", "le tampon du bureau", "Le tampon du bureau confirme la réception."],
  ["Registration desk", "le bureau d'inscription", "Le bureau d'inscription ouvre à huit heures."],
  ["Waiting list", "la liste d'attente", "Votre nom est inscrit sur la liste d'attente."],
  ["Queue number", "le numéro de passage", "Prenez un numéro de passage à l'entrée."],
  ["Information leaflet", "la brochure d'information", "La brochure d'information est gratuite."],
  ["User guide", "le guide d'utilisation", "Consultez le guide d'utilisation avant d'appeler."],
  ["FAQ sheet", "la foire aux questions", "La foire aux questions répond aux demandes courantes."],
  ["Office closure", "la fermeture du bureau", "La fermeture du bureau est annoncée sur la porte."],
  ["Public notice", "l'avis public", "L'avis public est affiché dans le hall."],
  ["Building access code", "le code d'accès", "Le code d'accès change chaque mois."],
  ["Visitor badge", "le badge visiteur", "Portez le badge visiteur en permanence."],
  ["Security check", "le contrôle de sécurité", "Le contrôle de sécurité prend quelques minutes."],
  ["Bag inspection", "la fouille des sacs", "La fouille des sacs est obligatoire à l'entrée."],
  ["Prohibited items", "les objets interdits", "Les objets interdits sont confisqués à l'entrée."],
  ["Lost document", "le document perdu", "Signalez tout document perdu immédiatement."],
  ["Duplicate copy", "le duplicata", "Un duplicata peut être délivré sur demande."],
  ["Name change", "le changement de nom", "Le changement de nom exige un acte officiel."],
  ["Address change", "le changement d'adresse", "Déclarez le changement d'adresse dans les huit jours."],
  ["Phone update", "la mise à jour du téléphone", "La mise à jour du téléphone se fait en ligne."],
  ["Email update", "la mise à jour du courriel", "La mise à jour du courriel nécessite une confirmation."],
  ["Opt-in box", "la case d'acceptation", "Cochez la case d'acceptation pour recevoir les nouvelles."],
  ["Privacy notice", "l'avis de confidentialité", "L'avis de confidentialité explique l'usage des données."],
  ["Consent checkbox", "la case de consentement", "La case de consentement doit être cochée."],
  ["Minor applicant", "le demandeur mineur", "Le demandeur mineur doit être accompagné."],
  ["Legal guardian", "le représentant légal", "Le représentant légal signe à la place de l'enfant."],
  ["Power of attorney", "la procuration", "Une procuration autorisée est acceptée."],
  ["Sworn statement", "la déclaration sous serment", "La déclaration sous serment est datée et signée."],
  ["Affidavit", "l'affidavit", "L'affidavit est déposé au greffe."],
  ["Notary public", "le notaire", "Le notaire authentifie la signature."],
  ["Court clerk", "le greffier", "Le greffier enregistre votre demande."],
  ["Filing fee", "les frais de dépôt", "Les frais de dépôt sont payables comptant."],
  ["Processing time", "le délai de traitement", "Le délai de traitement est de dix jours ouvrables."],
  ["Status update", "la mise à jour du statut", "Une mise à jour du statut est envoyée par courriel."],
  ["Incomplete file", "le dossier incomplet", "Un dossier incomplet sera retourné."],
  ["Missing page", "la page manquante", "Une page manquante retarde l'étude."],
  ["Illegible scan", "la numérisation illisible", "Une numérisation illisible doit être refaite."],
  ["Wrong form version", "la mauvaise version du formulaire", "La mauvaise version du formulaire est refusée."],
  ["Office hours sign", "le panneau des heures", "Le panneau des heures est visible depuis la rue."],
  ["Appointment only", "sur rendez-vous seulement", "Ce service est sur rendez-vous seulement."],
  ["Drop-off box", "la boîte de dépôt", "Déposez l'enveloppe dans la boîte de dépôt."],
  ["Pickup hours", "les heures de cueillette", "Les heures de cueillette sont de neuf à seize heures."],
  ["Service interruption", "l'interruption de service", "Une interruption de service est prévue dimanche."],
  ["Maintenance day", "le jour d'entretien", "Le jour d'entretien, le site est hors ligne."],
  ["Technical support", "le soutien technique", "Le soutien technique répond par clavardage."],
  ["Help desk hours", "les heures du service d'aide", "Les heures du service d'aide sont affichées en ligne."],
  ["Language of correspondence", "la langue de correspondance", "Choisissez la langue de correspondance sur le profil."],
  ["Preferred contact method", "le mode de contact préféré", "Indiquez votre mode de contact préféré."],
  ["Daytime phone", "le téléphone de jour", "Laissez un téléphone de jour joignable."],
  ["Evening phone", "le téléphone de soir", "Le téléphone de soir est facultatif."],
  ["Emergency contact", "le contact d'urgence", "Inscrivez un contact d'urgence à jour."],
  ["Relationship field", "le lien de parenté", "Précisez le lien de parenté avec le contact."],
  ["Blood type field", "le groupe sanguin", "Le groupe sanguin est demandé à l'hôpital."],
  ["Height and weight", "la taille et le poids", "Indiquez la taille et le poids en unités métriques."],
  ["Gender marker", "le sexe", "Le sexe est indiqué selon votre pièce d'identité."],
  ["Preferred name", "le prénom usuel", "Vous pouvez indiquer un prénom usuel."],
  ["Middle name", "le deuxième prénom", "Le deuxième prénom figure sur certains certificats."],
  ["Suffix (Jr.)", "le suffixe", "Le suffixe distingue les homonymes dans la famille."],
  ["Apartment buzzer", "le sonnette", "Tapez le numéro sur la sonnette de l'immeuble."],
  ["Care of (c/o)", "aux soins de", "Écrivez aux soins de la personne qui reçoit le courrier."],
  ["Rural address", "l'adresse rurale", "L'adresse rurale inclut le numéro de lot."],
  ["Care facility", "l'établissement de soins", "L'établissement de soins reçoit le courrier centralisé."],
  ["General delivery", "poste restante", "Retirez le colis en poste restante avec une pièce d'identité."],
  ["Window shopping", "faire du lèche-vitrines", "Nous faisons du lèche-vitrines avant les soldes."],
  ["Bargain price", "le prix cassé", "J'ai trouvé un prix cassé sur les chaussures."],
  ["Clearance event", "la liquidation", "La liquidation commence mercredi matin."],
  ["Price markdown", "la réduction de prix", "Une réduction de prix est appliquée en caisse."],
  ["Retail price", "le prix de détail", "Le prix de détail est affiché sur l'étiquette."],
  ["Wholesale price", "le prix de gros", "Le prix de gros est réservé aux professionnels."],
  ["Cash register", "la caisse enregistreuse", "La caisse enregistreuse imprime le reçu."],
  ["Shopping tote", "le sac réutilisable", "Apportez votre sac réutilisable pour éviter les frais."],
  ["Paper sack", "le sac en papier", "Un sac en papier coûte vingt-cinq cents."],
  ["Plastic sack", "le sac en plastique", "Le sac en plastique est interdit dans cette ville."],
  ["Shelf price", "le prix en rayon", "Le prix en rayon diffère parfois du prix en ligne."],
  ["Stock shortage", "la rupture de stock", "Une rupture de stock est annoncée sur l'étagère."],
  ["New arrival", "la nouveauté", "La nouveauté est exposée près de l'entrée."],
  ["Fitting mirror", "le miroir d'essayage", "Le miroir d'essayage est derrière le rideau."],
  ["Mannequin", "le mannequin", "Le mannequin porte la veste en promotion."],
  ["Clothes hanger", "le cintre", "Remettez le cintre sur le portant."],
  ["Price label", "l'étiquette de prix", "Vérifiez l'étiquette de prix avant de payer."],
  ["Cotton fabric", "le coton", "Ce t-shirt est en coton doux."],
  ["Wool sweater", "la laine", "Ce pull en laine se lave à la main."],
  ["Leather belt", "le cuir", "La ceinture en cuir est en solde."],
  ["Synthetic material", "le synthétique", "Le synthétique sèche plus vite que la laine."],
  ["Waterproof jacket", "imperméable", "Un manteau imperméable est utile en automne."],
  ["Machine washable", "lavable en machine", "Le pantalon est lavable en machine à froid."],
  ["Dry clean only", "nettoyage à sec seulement", "Cette robe est nettoyage à sec seulement."],
  ["One size", "taille unique", "Ce modèle est taille unique."],
  ["Extra small size", "très petit", "La très petite taille est en rayon enfants."],
  ["Extra large size", "très grand", "La très grande taille est en fin de rangée."],
  ["Waist size", "le tour de taille", "Mesurez votre tour de taille en centimètres."],
  ["Sleeve length", "la longueur de manche", "La longueur de manche est indiquée sur l'étiquette."],
  ["Heel height", "la hauteur du talon", "La hauteur du talon est de cinq centimètres."],
  ["Sandals", "les sandales", "Les sandales sont pratiques en été."],
  ["Running shoes", "les chaussures de course", "Mes chaussures de course sont usées."],
  ["Winter boots", "les bottes d'hiver", "Les bottes d'hiver sont en promotion."],
  ["Wool scarf", "l'écharpe", "N'oubliez pas votre écharpe ce matin."],
  ["Winter gloves", "les gants", "Les gants sont obligatoires sur la patinoire."],
  ["Sunglasses", "les lunettes de soleil", "Les lunettes de soleil sont à l'entrée du magasin."],
  ["Raincoat", "l'imperméable", "Mon imperméable est trop grand."],
  ["Swimsuit", "le maillot de bain", "Le maillot de bain est en rayon sport."],
  ["Pajamas", "le pyjama", "J'achète un pyjama pour mon enfant."],
  ["Socks pack", "la paire de chaussettes", "Une paire de chaussettes est incluse."],
  ["Leather wallet", "le portefeuille", "J'ai perdu mon portefeuille près de la caisse."],
  ["Handbag", "le sac à main", "Le sac à main est en cuir véritable."],
  ["School backpack", "le sac à dos", "Le sac à dos a une bande réfléchissante."],
  ["Luggage tag", "l'étiquette de bagage", "Fixez une étiquette de bagage sur la valise."],
  ["Travel pillow", "le coussin de voyage", "Le coussin de voyage est en rayon accessoires."],
  ["Checkout scanner", "le lecteur de codes", "Passez l'article devant le lecteur de codes."],
  ["Self-service scale", "la balance libre-service", "Pesez les fruits sur la balance libre-service."],
  ["Deli slicer", "la trancheuse", "La trancheuse est derrière le comptoir charcuterie."],
  ["Bakery oven", "le four à pain", "Le pain sort du four à pain à huit heures."],
  ["Fish counter", "le comptoir poissonnerie", "Le comptoir poissonnerie ferme à dix-neuf heures."],
  ["Butcher counter", "la boucherie", "La boucherie propose des morceaux découpés sur place."],
  ["Organic aisle", "le rayon bio", "Le rayon bio est au fond du magasin."],
  ["Gluten-free aisle", "le rayon sans gluten", "Le rayon sans gluten est signalé en vert."],
  ["Frozen aisle", "le rayon surgelés", "Le rayon surgelés est la section la plus froide."],
  ["Household goods", "les articles ménagers", "Les articles ménagers sont au deuxième niveau."],
  ["Cleaning supplies", "les produits d'entretien", "Les produits d'entretien sont sous l'évier en magasin."],
  ["Light bulb", "l'ampoule", "J'achète une ampoule LED économique."],
  ["Extension cord", "la rallonge", "Une rallonge est nécessaire derrière le bureau."],
  ["Batteries pack", "les piles", "Les piles sont à la caisse, pas en rayon."],
  ["Gift wrapping", "l'emballage cadeau", "L'emballage cadeau coûte trois dollars."],
  ["Sales receipt", "le ticket de caisse", "Gardez le ticket de caisse pour l'échange."],
  ["Store warranty", "la garantie magasin", "La garantie magasin dure un an."],
  ["Extended warranty", "la garantie prolongée", "La garantie prolongée est optionnelle."],
  ["Installment payment", "le paiement échelonné", "Le paiement échelonné est sans intérêt."],
  ["Layaway plan", "le compte client", "Le compte client permet de payer en plusieurs fois."],
  ["Store credit note", "l'avoir", "L'avoir est valable six mois en magasin."],
  ["Price comparison", "la comparaison de prix", "Faites une comparaison de prix avant d'acheter."],
  ["Customer review", "l'avis client", "L'avis client est affiché sous le produit."],
  ["Online pickup", "la cueillette en magasin", "La cueillette en magasin est gratuite."],
  ["Home delivery slot", "le créneau de livraison", "Choisissez un créneau de livraison ce soir."],
  ["Delivery fee", "les frais de livraison", "Les frais de livraison sont ajoutés au total."],
  ["Minimum order", "la commande minimum", "La commande minimum est de vingt dollars."],
  ["Out-of-stock notice", "l'avis de rupture", "Un avis de rupture est collé sur l'étagère."],
  ["Restock date", "la date de réapprovisionnement", "La date de réapprovisionnement est vendredi."],
  ["Seasonal sale", "la vente saisonnière", "La vente saisonnière touche les manteaux."],
  ["Black Friday", "le vendredi fou", "Le vendredi fou attire beaucoup de clients."],
  ["Opening day discount", "la réduction d'ouverture", "Une réduction d'ouverture est offerte la première semaine."],
  ["Member discount", "la réduction membre", "La réduction membre s'applique à la caisse."],
  ["Senior discount", "la réduction pour aînés", "La réduction pour aînés est disponible le mardi."],
  ["Student discount card", "la carte étudiante", "Montrez votre carte étudiante pour payer moins."],
  ["Coupon code", "le code promo", "Entrez le code promo avant de valider."],
  ["Buy one get one", "un acheté un offert", "La promo un acheté un offert finit dimanche."],
  ["Two for one", "deux pour un", "Les jus sont deux pour un cette semaine."],
  ["Unit quantity", "la quantité unitaire", "Indiquez la quantité unitaire sur le bon de commande."],
  ["Bulk bin", "le vrac", "Les noix sont vendues au vrac."],
  ["Weigh station", "la station de pesée", "Pesez le sac à la station de pesée."],
  ["Barcode scanner beep", "le bip du scanner", "Un bip du scanner confirme l'article."],
  ["Shopping cart wheel", "la roue du chariot", "Une roue du chariot bloque près des fruits."],
  ["Basket handle", "l'anse du panier", "L'anse du panier est cassée; prenez un autre."],
  ["Security tag", "l'antivol", "L'antivol est retiré à la caisse."],
  ["Changing room hook", "le crochet", "Accrochez votre manteau au crochet."],
  ["Mirror sticker", "l'autocollant miroir", "L'autocollant miroir indique la taille essayée."],
  ["Return window", "le délai de retour", "Le délai de retour est de quinze jours."],
  ["Exchange policy", "la politique d'échange", "La politique d'échange exige l'emballage d'origine."],
  ["Defective item", "l'article défectueux", "Signalez l'article défectueux au service à la clientèle."],
  ["Scratch on item", "la rayure", "Une rayure sur le produit donne droit à un échange."],
  ["Opened package", "l'emballage ouvert", "Un emballage ouvert peut limiter le remboursement."],
  ["Sealed box", "la boîte scellée", "La boîte scellée ne doit pas être ouverte."],
  ["Receipt lookup", "la recherche de reçu", "La recherche de reçu se fait avec la carte bancaire."],
  ["Cash back", "le remboursement en argent", "Le remboursement en argent est limité à cinquante dollars."],
  ["Debit payment", "le paiement par débit", "Le paiement par débit demande votre NIP."],
  ["Contactless payment", "le paiement sans contact", "Le paiement sans contact est plafonné."],
  ["Split bill", "partager l'addition", "Nous allons partager l'addition entre quatre."],
  ["Tip on card", "le pourboire sur carte", "Ajoutez un pourboire sur carte à l'écran."],
  ["Rounding up", "l'arrondi", "L'arrondi au centime supérieur est proposé pour la charité."],
  ["Small change", "la petite monnaie", "Je n'ai pas de petite monnaie pour le parking."],
  ["Coin slot", "la fente à pièces", "Insérez la pièce dans la fente à pièces."],
  ["Shopping receipt email", "le reçu par courriel", "Choisissez le reçu par courriel à la caisse."],
  ["Product recall", "le rappel de produit", "Un rappel de produit concerne ce lot de yaourt."],
  ["Best before", "à consommer de préférence avant", "Regardez la mention à consommer de préférence avant."],
  ["Sell-by date", "à vendre avant", "La viande doit être à vendre avant demain."],
  ["Ingredients list", "la liste d'ingrédients", "La liste d'ingrédients est sur le dos du paquet."],
  ["Nutrition facts", "les informations nutritionnelles", "Les informations nutritionnelles sont par portion."],
  ["Allergen warning", "l'avertissement allergène", "L'avertissement allergène mentionne les arachides."],
  ["Country of manufacture", "le pays de fabrication", "Le pays de fabrication est indiqué sous le code-barres."],
  ["Customer queue", "la file clients", "La file clients avance vers la caisse trois."],
  ["Express lane", "la caisse rapide", "La caisse rapide est pour dix articles ou moins."],
  ["Closed checkout", "la caisse fermée", "Cette caisse fermée rouvrira à quatorze heures."],
  ["Price check desk", "le bureau prix", "Demandez un contrôle au bureau prix."],
  ["Store manager", "le directeur du magasin", "Le directeur du magasin peut autoriser une exception."],
  ["Mystery shopper", "le client mystère", "Un client mystère évalue la qualité du service."],
  ["Loyalty points", "les points fidélité", "Vos points fidélité apparaissent sur le reçu."],
  ["Rewards card scan", "la carte récompenses", "Scannez la carte récompenses avant de payer."],
  ["Digital receipt", "le reçu numérique", "Le reçu numérique arrive dans l'application."],
  ["Rainy day sale", "la promo jour de pluie", "Une promo jour de pluie est annoncée à la radio."],
  ["Flash sale", "la vente éclair", "La vente éclair dure seulement deux heures."],
  ["Closing sale", "la fermeture pour inventaire", "La fermeture pour inventaire est jeudi soir."],
  ["Opening gift", "le cadeau de bienvenue", "Un cadeau de bienvenue est offert aux nouveaux membres."],
  ["Sample tasting", "la dégustation", "Une dégustation gratuite est proposée à l'entrée."],
  ["Free sample", "l'échantillon gratuit", "Prenez un échantillon gratuit au comptoir."],
  ["Product demo", "la démonstration", "La démonstration du robot commence à quinze heures."],
  ["Aisle marker", "la signalétique d'allée", "La signalétique d'allée indique les boissons."],
  ["Shopping list app", "l'application liste", "Synchronisez l'application liste avec le magasin."],
  ["Click and collect", "le clic et collecte", "Le clic et collecte est prêt en deux heures."],
  ["Order number display", "l'affichage de commande", "Votre numéro clignote sur l'affichage de commande."],
  ["Pickup counter", "le comptoir de retrait", "Le comptoir de retrait est à gauche de l'entrée."],
  ["Cold storage bag", "le sac isotherme", "Un sac isotherme garde les produits frais."],
  ["Reusable cup discount", "la réduction gobelet", "La réduction gobelet s'applique si vous apportez le vôtre."],
  ["Bottle deposit", "la consigne", "La consigne sur la bouteille est remboursée au retour."],
  ["Recycling deposit", "le dépôt de recyclage", "Le dépôt de recyclage accepte le verre et le plastique."],
  ["Shopping trolley token", "le jeton de chariot", "Insérez un jeton de chariot pour débloquer le chariot."],
  ["Escalator to mall", "l'escalator du centre", "L'escalator du centre mène au niveau restaurants."],
  ["Mall directory", "le plan du centre", "Le plan du centre est près des ascenseurs."],
  ["Food court table", "la table de la place", "Une table de la place est libre près des fenêtres."],
  ["Restroom key", "la clé des toilettes", "Demandez la clé des toilettes à l'accueil."],
  ["Hand dryer", "le séchoir à mains", "Le séchoir à mains est à droite de l'évier."],
  ["Paper towel dispenser", "le distributeur d'essuie-mains", "Le distributeur d'essuie-mains est vide."],
  ["Shopping hours sign", "l'affiche des heures", "L'affiche des heures indique l'ouverture à dix heures."],
  ["Holiday hours", "les heures des fêtes", "Les heures des fêtes sont publiées en décembre."],
  ["Early bird special", "l'offre matinale", "L'offre matinale se termine à onze heures."],
  ["Late night shopping", "les achats tard le soir", "Les achats tard le soir sont possibles jeudi."],
  ["Price guarantee", "la garantie de prix", "La garantie de prix s'applique pendant sept jours."],
  ["Ad match", "l'ajustement de prix", "Demandez l'ajustement de prix avec la publicité concurrente."],
  ["Rain check (store)", "le bon de réserve", "Un bon de réserve vous réserve l'article en rupture."],
  ["Special order", "la commande spéciale", "Une commande spéciale arrive sous dix jours."],
  ["Catalog order", "la commande catalogue", "La commande catalogue se fait au comptoir service."],
  ["Tailor alteration", "la retouche", "La retouche du pantalon sera prête vendredi."],
  ["Hemming pants", "le ourlet", "Le ourlet coûte douze dollars."],
  ["Shoe polish", "le cirage", "Le cirage est vendu près des chaussures."],
  ["Shoe size chart", "le guide des pointures", "Consultez le guide des pointures au mur."],
  ["Ring size", "la taille de bague", "La taille de bague se mesure en magasin."],
  ["Jewelry counter", "le comptoir bijoux", "Le comptoir bijoux propose un nettoyage gratuit."],
  ["Perfume tester", "le testeur de parfum", "Utilisez le testeur de parfum sur la carte."],
  ["Makeup remover", "le démaquillant", "Le démaquillant est en rayon beauté."],
  ["Sunscreen lotion", "la crème solaire", "La crème solaire est recommandée à la plage."],
  ["Insect repellent", "l'anti-moustique", "L'anti-moustique se vend près du rayon camping."],
  ["Camping stove", "le réchaud de camping", "Le réchaud de camping est interdit en appartement."],
  ["Tent sale", "la promo de tentes", "La promo de tentes attire les campeurs."],
  ["Fishing license", "le permis de pêche", "Le permis de pêche s'achète en ligne."],
  ["Pet food aisle", "le rayon animaux", "Le rayon animaux est à côté des surgelés."],
  ["Baby formula", "la préparation pour bébé", "La préparation pour bébé est derrière le comptoir."],
  ["Diaper pack", "les couches", "Les couches sont en promotion cette semaine."],
  ["Stroller parking", "le parking poussettes", "Le parking poussettes est près de l'ascenseur."],
  ["Toy section", "le rayon jouets", "Le rayon jouets est bruyant le samedi."],
  ["Book section", "le rayon livres", "Le rayon livres propose des romans en français."],
  ["Stationery aisle", "le rayon papeterie", "Le rayon papeterie vend des cahiers et des stylos."],
  ["Greeting card rack", "le présentoir de cartes", "Choisissez une carte sur le présentoir de cartes."],
  ["Wrapping paper roll", "le papier cadeau", "Un rouleau de papier cadeau coûte cinq dollars."],
  ["Scotch tape", "le ruban adhésif", "Le ruban adhésif est à côté des emballages."],
  ["Gift bag", "le sac cadeau", "Un sac cadeau évite d'emballer vous-même."],
  ["Store playlist", "la musique d'ambiance", "La musique d'ambiance est très forte aujourd'hui."],
  ["Security camera", "la caméra de surveillance", "Une caméra de surveillance filme l'entrée."],
  ["Shoplifting alarm", "l'alarme antivol", "L'alarme antivol se déclenche à la sortie."],
  ["Bag check", "la consigne sacs", "Déposez vos sacs à la consigne sacs à l'entrée."],
  ["Wheelchair cart", "le chariot adapté", "Un chariot adapté est disponible à l'accueil."],
  ["Motorized scooter", "le scooter électrique", "Le scooter électrique se loue à l'accueil du magasin."],
  ["Shopping companion", "l'accompagnateur", "Un accompagnateur peut aider aux achats lourds."],
  ["Heavy item help", "l'aide au chargement", "Demandez l'aide au chargement pour les gros articles."],
  ["Loading zone", "la zone de chargement", "La zone de chargement est limitée à quinze minutes."],
  ["Parking validation machine", "le validateur", "Insérez le ticket dans le validateur avant de sortir."],
  ["Mall parking garage", "le stationnement souterrain", "Le stationnement souterrain est payant après deux heures."],
  ["Receipt survey", "le sondage sur reçu", "Répondez au sondage sur reçu pour gagner un prix."],
  ["Charity donation box", "la boîte à dons", "La boîte à dons se trouve près de la sortie."],
  ["Food bank bin", "le bac pour banque alimentaire", "Déposez des conserves dans le bac pour banque alimentaire."],
  ["Unit conversion", "la conversion d'unités", "La conversion d'unités est indiquée sur l'étiquette."],
  ["Metric label", "l'étiquette métrique", "L'étiquette métrique affiche les grammes."],
  ["Imperial label", "l'étiquette impériale", "L'étiquette impériale montre les onces."],
  ["Price per kilo", "le prix au kilo", "Le prix au kilo est plus bas en gros format."],
  ["Price per liter", "le prix au litre", "Comparez le prix au litre entre les marques."],
  ["Multipack", "le lot", "Le lot de six bouteilles coûte moins cher."],
  ["Single serving", "la portion individuelle", "La portion individuelle est pratique pour le lunch."],
  ["Family pack", "le format familial", "Le format familial suffit pour quatre personnes."],
  ["Economy size", "le grand format", "Le grand format est en haut de l'étagère."],
  ["Travel size", "le format voyage", "Le format voyage respecte les règles de l'avion."],
  ["Refill pack", "la recharge", "La recharge coûte moins que le flacon neuf."],
  ["Store brand", "la marque maison", "La marque maison est moins chère que la marque nationale."],
  ["Name brand", "la grande marque", "La grande marque est en rayon central."],
  ["Generic brand", "la marque générique", "La marque générique a le même ingrédient actif."],
  ["Limited edition", "l'édition limitée", "L'édition limitée part vite."],
  ["Collector item", "l'objet de collection", "Cet objet de collection n'est pas remboursable."],
  ["Handmade goods", "l'artisanat", "L'artisanat local est vendu au marché."],
  ["Farmers market", "le marché fermier", "Le marché fermier ouvre à sept heures le samedi."],
  ["Street vendor", "le vendeur ambulant", "Le vendeur ambulant accepte les pièces seulement."],
  ["Flea market", "le marché aux puces", "Le marché aux puces a lieu dimanche matin."],
  ["Thrift store", "la friperie", "La friperie vend des vêtements d'occasion."],
  ["Second-hand shop", "la boutique d'occasion", "La boutique d'occasion est près de la station."],
  ["Pawn shop", "le prêteur sur gages", "Le prêteur sur gages évalue les bijoux sur place."],
  ["Auction house", "la maison de vente", "La maison de vente présente les lots en ligne."],
  ["Estate sale", "la vente de succession", "La vente de succession dure tout le week-end."],
  ["Garage sale", "la vente de garage", "La vente de garage est annoncée par une affiche."],
  ["Yard sale sign", "l'affiche vente", "Suivez l'affiche vente dans la rue résidentielle."],
  ["Bargain hunter", "le chasseur de bonnes affaires", "Chaque chasseur de bonnes affaires arrive tôt."],
  ["Impulse buy", "l'achat impulsif", "Évitez l'achat impulsif près de la caisse."],
  ["Shopping budget", "le budget courses", "Respectez votre budget courses avec une liste."],
  ["Price ceiling", "le plafond de prix", "Un plafond de prix protège les consommateurs."],
  ["Sales tax line", "la ligne de taxe", "La ligne de taxe s'ajoute au sous-total."],
  ["Duty charge", "les droits de douane", "Les droits de douane s'appliquent aux colis internationaux."],
  ["Import fee", "les frais d'importation", "Les frais d'importation sont dus à la livraison."],
  ["Customs fee", "les frais de douane", "Payez les frais de douane avant de retirer le colis."],
  ["Currency exchange desk", "le bureau de change", "Le bureau de change ferme à dix-huit heures."],
  ["Exchange rate board", "le tableau des taux", "Le tableau des taux est mis à jour chaque matin."],
  ["Travel money card", "la carte de voyage", "Rechargez la carte de voyage avant le départ."],
  ["Foreign coins", "les pièces étrangères", "Les pièces étrangères ne sont pas reprises ici."],
  ["Souvenir magnet", "le magnet souvenir", "J'achète un magnet souvenir pour ma famille."],
  ["Postcard stamp", "le timbre pour carte", "Achetez un timbre pour carte à la poste."],
  ["Map souvenir", "la carte postale illustrée", "La carte postale illustrée montre le vieux port."],
  ["One-way ticket", "le billet aller simple", "Un billet aller simple coûte moins cher."],
  ["Return ticket", "le billet aller-retour", "Le billet aller-retour est valable trente jours."],
  ["Round trip fare", "le tarif aller-retour", "Le tarif aller-retour inclut la correspondance."],
  ["Weekly transit pass", "la passe hebdomadaire", "La passe hebdomadaire est économique pour les touristes."],
  ["Child fare", "le tarif enfant", "Le tarif enfant s'applique jusqu'à douze ans."],
  ["Free transfer", "la correspondance gratuite", "La correspondance gratuite dure quatre-vingt-dix minutes."],
  ["Tap-to-pay card", "la carte sans contact", "Tapez la carte sans contact sur le lecteur."],
  ["Validate ticket", "composter le billet", "Compostez le billet avant de monter."],
  ["Turnstile gate", "le tourniquet", "Le tourniquet bloque si le billet est expiré."],
  ["Fare inspector", "le contrôleur", "Le contrôleur demande votre titre de transport."],
  ["Transit fine", "l'amende de transport", "Une amende de transport peut atteindre cent dollars."],
  ["Park and ride lot", "le parc relais", "Le parc relais est gratuit pour les usagers du métro."],
  ["Bike share station", "la station de vélos", "La station de vélos est pleine ce matin."],
  ["Scooter rental", "la location de trottinette", "La location de trottinette exige une application."],
  ["Taxi meter", "le taximètre", "Le taximètre démarre à la prise en charge."],
  ["Flat taxi fare", "le forfait taxi", "Le forfait taxi s'applique vers l'aéroport."],
  ["Night bus route", "la ligne de nuit", "La ligne de nuit circule toutes les trente minutes."],
  ["Express route", "la ligne express", "La ligne express ne s'arrête pas à chaque arrêt."],
  ["Request stop", "l'arrêt sur demande", "Cet arrêt sur demande nécessite de signaler au conducteur."],
  ["Pull the cord", "tirer la corde", "Tirez la corde pour demander l'arrêt."],
  ["Get off the bus", "descendre du bus", "Descendez du bus par la porte arrière."],
  ["Board the train", "monter dans le train", "Montez dans le train dès l'ouverture des portes."],
  ["Disembark", "débarquer", "Les passagers doivent débarquer rapidement."],
  ["Subway line map", "le plan du métro", "Le plan du métro est affiché dans chaque rame."],
  ["Line number", "le numéro de ligne", "Le numéro de ligne est indiqué en orange."],
  ["Northbound train", "en direction nord", "Ce train va en direction nord."],
  ["Southbound bus", "en direction sud", "Le bus en direction sud quitte le quai B."],
  ["Traffic light", "le feu de circulation", "Le feu de circulation est rouge."],
  ["Green light", "feu vert", "Au feu vert, les piétons peuvent traverser."],
  ["Red light camera", "le radar de feu rouge", "Un radar de feu rouge est installé à l'intersection."],
  ["Jaywalking ticket", "l'infraction de traversée", "Une infraction de traversée coûte cher en ville."],
  ["Bicycle helmet law", "le casque obligatoire", "Le casque obligatoire protège les cyclistes."],
  ["Car rental desk", "le comptoir de location", "Le comptoir de location ouvre à sept heures."],
  ["Rental agreement form", "le contrat de location", "Signez le contrat de location avant de partir."],
  ["Mileage limit", "la limite de kilométrage", "La limite de kilométrage est de deux cents kilomètres par jour."],
  ["Fuel gauge", "la jauge d'essence", "La jauge d'essence est presque vide."],
  ["Gas pedal", "l'accélérateur", "Appuyez doucement sur l'accélérateur."],
  ["Brake pedal", "la pédale de frein", "La pédale de frein répond bien."],
  ["Steering wheel", "le volant", "Tenez le volant à deux mains."],
  ["Car trunk", "le coffre", "Mettez les valises dans le coffre."],
  ["Windshield wipers", "les essuie-glaces", "Allumez les essuie-glaces sous la pluie."],
  ["Rearview mirror", "le rétroviseur", "Réglez le rétroviseur avant de démarrer."],
  ["Seat belt buckle", "la ceinture de sécurité", "Attachez la ceinture de sécurité avant le départ."],
  ["Air conditioning car", "la climatisation", "La climatisation refroidit rapidement l'habitacle."],
  ["Car heater", "le chauffage", "Le chauffage met quelques minutes à chauffer."],
  ["Empty gas tank", "le réservoir vide", "Ne roulez pas avec le réservoir vide."],
  ["Gas nozzle", "la pompe à essence", "Replacez la pompe à essence après le plein."],
  ["Diesel pump", "le gazole", "Ce véhicule roule au gazole seulement."],
  ["Electric charging station", "la borne de recharge", "La borne de recharge est occupée."],
  ["Parking brake", "le frein à main", "Serrez le frein à main sur la pente."],
  ["Flat tire", "le pneu crevé", "Un pneu crevé nous retarde sur l'autoroute."],
  ["Spare tire", "la roue de secours", "La roue de secours est sous le plancher."],
  ["Roadside assistance", "l'assistance routière", "Appelez l'assistance routière en cas de panne."],
  ["Highway rest stop", "l'aire d'autoroute", "Faites une pause à l'aire d'autoroute."],
  ["Speed camera", "le radar fixe", "Un radar fixe limite la vitesse à cent."],
  ["School bus stop", "l'arrêt d'autobus scolaire", "Ralentissez à l'arrêt d'autobus scolaire."],
  ["Pedestrian zone", "la zone piétonne", "La zone piétonne est fermée aux voitures."],
  ["Bike path sign", "la piste cyclable", "Suivez le panneau piste cyclable."],
  ["Ferry schedule board", "l'horaire du traversier", "L'horaire du traversier change en hiver."],
  ["Harbor pier", "le quai du port", "Le quai du port est glissant ce matin."],
  ["Cruise ship terminal", "le terminal croisière", "Le terminal croisière est à vingt minutes en taxi."],
  ["Airport shuttle", "la navette aéroport", "La navette aéroport part toutes les heures."],
  ["Flight gate change", "le changement de porte", "Un changement de porte est annoncé pour votre vol."],
  ["Boarding group", "le groupe d'embarquement", "Le groupe d'embarquement trois peut monter."],
  ["Overhead bin", "le compartiment supérieur", "Rangez le sac dans le compartiment supérieur."],
  ["Seat assignment", "la place attribuée", "Votre place attribuée est 12C."],
  ["Train platform screen", "l'écran du quai", "L'écran du quai affiche le prochain départ."],
  ["Missed connection", "la correspondance manquée", "Une correspondance manquée entraîne un nouveau billet."],
  ["To dial a number", "composer un numéro", "Composez un numéro en incluant l'indicatif régional."],
  ["To hang up", "raccrocher", "Raccrochez après avoir laissé votre message."],
  ["To answer the phone", "décrocher", "Décrochez avant la troisième sonnerie."],
  ["Busy tone", "la tonalité occupée", "J'entends la tonalité occupée depuis dix minutes."],
];
