export type LemmaRow = [en: string, fr: string, exampleFr: string];

export const BATCH2_A: LemmaRow[] = [
  ["Business hours", "les heures d'affaires", "Les heures d'affaires sont de 8 h \u00e0 18 h."],
  ["Walk-in (no appointment)", "sans rendez-vous", "Ce service est ouvert sans rendez-vous le mardi."],
  ["To pick up (parcel)", "retirer", "Vous pouvez retirer le colis \u00e0 l'accueil."],
  ["Counter / service desk", "le comptoir", "Pr\u00e9sentez-vous au comptoir d\u00e8s votre arriv\u00e9e."],
  ["Queue / lineup", "la file d'attente", "La file d'attente avance lentement."],
  ["Out of order (machine)", "hors service", "Le guichet automatique est hors service."],
  ["PIN code", "le code NIP", "Entrez votre code NIP discr\u00e8tement."],
  ["Debit card", "la carte de d\u00e9bit", "Je paie avec ma carte de d\u00e9bit."],
  ["Cash withdrawal", "le retrait", "Le retrait est limit\u00e9 \u00e0 500 dollars."],
  ["Account balance", "le solde", "V\u00e9rifiez le solde avant le paiement."],
  ["Overdue (bill)", "en retard", "Votre facture est en retard de dix jours."],
  ["Due date (payment)", "la date d'\u00e9ch\u00e9ance", "La date d'\u00e9ch\u00e9ance est le 30 avril."],
  ["Grocery store", "l'\u00e9picerie", "L'\u00e9picerie ferme \u00e0 vingt et une heures."],
  ["Aisle", "l'all\u00e9e", "Les produits laitiers sont dans l'all\u00e9e trois."],
  ["On sale", "en solde", "Les manteaux sont en solde cette semaine."],
  ["Refund", "le remboursement", "Le remboursement sera cr\u00e9dit\u00e9 sous cinq jours."],
  ["Pharmacy", "la pharmacie", "La pharmacie d\u00e9livre l'ordonnance."],
  ["Over-the-counter", "en vente libre", "Ce m\u00e9dicament est en vente libre."],
  ["Symptom", "le sympt\u00f4me", "D\u00e9crivez chaque sympt\u00f4me au m\u00e9decin."],
  ["Allergy", "l'allergie", "Mentionnez votre allergie sur le formulaire."],
  ["Bus stop", "l'arr\u00eat d'autobus", "Descendez au prochain arr\u00eat d'autobus."],
  ["Transfer (transit)", "la correspondance", "Prenez la correspondance vers le centre-ville."],
  ["Rush hour", "l'heure de pointe", "L'heure de pointe commence \u00e0 sept heures."],
  ["Detour", "la d\u00e9viation", "Une d\u00e9viation est en place sur la route 40."],
  ["Voicemail", "la messagerie vocale", "Laissez un message sur la messagerie vocale."],
  ["Wrong number", "faux num\u00e9ro", "D\u00e9sol\u00e9, vous avez un faux num\u00e9ro."],
  ["Extension (phone)", "le poste", "Composez le poste 204 pour joindre le service."],
  ["Copy (document)", "la copie", "Joignez une copie de votre pi\u00e8ce d'identit\u00e9."],
];

export const BATCH2_B: LemmaRow[] = [
  ["Permanent residence", "la r\u00e9sidence permanente", "Il a obtenu sa r\u00e9sidence permanente l'an dernier."],
  ["Work permit", "le permis de travail", "Votre permis de travail expire en d\u00e9cembre."],
  ["Proof of funds", "la preuve de fonds", "La preuve de fonds doit couvrir douze mois."],
  ["Educational credential assessment", "l'\u00e9valuation comparative des \u00e9tudes", "L'\u00e9valuation comparative des \u00e9tudes est obligatoire."],
  ["Invitation to apply", "l'invitation \u00e0 pr\u00e9senter une demande", "Il a re\u00e7u une invitation \u00e0 pr\u00e9senter une demande."],
  ["Comprehensive ranking system", "le syst\u00e8me de classement global", "Son score dans le syst\u00e8me de classement global est \u00e9lev\u00e9."],
  ["Provincial nominee program", "le programme des candidats des provinces", "Le programme des candidats des provinces acc\u00e9l\u00e8re le processus."],
  ["Biometrics", "les donn\u00e9es biom\u00e9triques", "Prenez rendez-vous pour les donn\u00e9es biom\u00e9triques."],
  ["Background check", "la v\u00e9rification des ant\u00e9c\u00e9dents", "La v\u00e9rification des ant\u00e9c\u00e9dents peut prendre des semaines."],
  ["Citizenship application", "la demande de citoyennet\u00e9", "Elle pr\u00e9pare sa demande de citoyennet\u00e9."],
  ["Residency obligation", "l'obligation de r\u00e9sidence", "L'obligation de r\u00e9sidence exige 730 jours sur cinq ans."],
  ["Affordable housing", "le logement abordable", "Le logement abordable manque dans plusieurs villes."],
  ["Rent increase", "l'augmentation de loyer", "L'augmentation de loyer est plafonn\u00e9e par la loi."],
  ["Sublet", "sous-louer", "Il est interdit de sous-louer sans autorisation."],
  ["Roommate", "le colocataire", "Mon colocataire partage les charges."],
  ["Utilities included", "les services publics inclus", "Le bail indique les services publics inclus."],
  ["Heat included", "le chauffage inclus", "Le chauffage inclus r\u00e9duit nos factures."],
  ["Tenant insurance", "l'assurance locataire", "L'assurance locataire couvre vos biens."],
  ["Maintenance request", "la demande d'entretien", "Envoyez une demande d'entretien en ligne."],
  ["Full-time employment", "l'emploi \u00e0 temps plein", "Elle cherche un emploi \u00e0 temps plein."],
  ["Part-time", "\u00e0 temps partiel", "Il travaille \u00e0 temps partiel le soir."],
  ["Minimum wage", "le salaire minimum", "Le salaire minimum augmente au printemps."],
  ["Pay stub", "le talon de paie", "Joignez votre talon de paie r\u00e9cent."],
  ["Tax deduction", "la retenue d'imp\u00f4t", "La retenue d'imp\u00f4t appara\u00eet sur la fiche de paie."],
  ["Employment insurance", "l'assurance-emploi", "Il a d\u00e9pos\u00e9 une demande d'assurance-emploi."],
  ["Occupational health", "la sant\u00e9 au travail", "La sant\u00e9 au travail fait l'objet d'une inspection."],
  ["Skills mismatch", "le d\u00e9calage des comp\u00e9tences", "Le d\u00e9calage des comp\u00e9tences freine l'embauche."],
  ["Internship", "le stage", "Le stage dure seize semaines."],
  ["Family doctor", "le m\u00e9decin de famille", "Trouver un m\u00e9decin de famille prend du temps."],
  ["Walk-in clinic", "la clinique sans rendez-vous", "La clinique sans rendez-vous ferme \u00e0 vingt heures."],
  ["Mental health", "la sant\u00e9 mentale", "La sant\u00e9 mentale est une priorit\u00e9 au travail."],
  ["Counselling", "l'accompagnement psychologique", "L'accompagnement psychologique est confidentiel."],
  ["Burnout", "l'\u00e9puisement professionnel", "L'\u00e9puisement professionnel touche plusieurs soignants."],
  ["Daycare spot", "la place en garderie", "Une place en garderie s'est lib\u00e9r\u00e9e en septembre."],
  ["School registration", "l'inscription scolaire", "L'inscription scolaire se fait en ligne."],
  ["Report card", "le bulletin scolaire", "Le bulletin scolaire sera envoy\u00e9 vendredi."],
  ["Parent-teacher meeting", "la rencontre parents-enseignants", "La rencontre parents-enseignants est jeudi soir."],
  ["Recycling bin", "le bac de recyclage", "Sortez le bac de recyclage le mardi matin."],
  ["Heat wave", "la vague de chaleur", "La vague de chaleur dure trois jours."],
  ["Flood", "l'inondation", "L'inondation a forc\u00e9 l'\u00e9vacuation du quartier."],
  ["Artificial intelligence", "l'intelligence artificielle", "L'intelligence artificielle transforme certains emplois."],
  ["Automation", "l'automatisation", "L'automatisation r\u00e9duit les t\u00e2ches r\u00e9p\u00e9titives."],
  ["Online harassment", "le cyberharc\u00e8lement", "Le cyberharc\u00e8lement est puni par la loi."],
  ["Municipal election", "l'\u00e9lection municipale", "L'\u00e9lection municipale aura lieu en octobre."],
  ["Voting station", "le bureau de vote", "Le bureau de vote ouvre \u00e0 huit heures."],
  ["Public consultation", "la consultation publique", "La consultation publique se termine vendredi."],
  ["Official languages", "les langues officielles", "Le Canada reconna\u00eet deux langues officielles."],
  ["Indigenous reconciliation", "la r\u00e9conciliation avec les Autochtones", "La r\u00e9conciliation avec les Autochtones exige des actions concr\u00e8tes."],
  ["Diversity and inclusion", "la diversit\u00e9 et l'inclusion", "La diversit\u00e9 et l'inclusion sont des valeurs d'entreprise."],
  ["Consumer complaint", "la plainte du consommateur", "D\u00e9posez une plainte du consommateur en ligne."],
  ["Class action", "le recours collectif", "Un recours collectif a \u00e9t\u00e9 autoris\u00e9."],
  ["Small claims court", "la Cour des petites cr\u00e9ances", "La Cour des petites cr\u00e9ances traite les petits litiges."],
];

export const BATCH2_C: LemmaRow[] = [
  ["Nevertheless", "n\u00e9anmoins", "N\u00e9anmoins, la r\u00e9forme suscite des r\u00e9serves."],
  ["Conversely", "\u00e0 l'inverse", "\u00c0 l'inverse, d'autres estiment que le co\u00fbt est acceptable."],
  ["Insofar as", "dans la mesure o\u00f9", "Dans la mesure o\u00f9 les donn\u00e9es le confirment, la mesure est justifi\u00e9e."],
  ["Notwithstanding", "nonobstant", "Nonobstant ces avanc\u00e9es, des in\u00e9galit\u00e9s persistent."],
  ["To call into question", "remettre en question", "L'\u00e9tude remet en question l'hypoth\u00e8se initiale."],
  ["To highlight", "souligner", "L'auteur souligne l'importance de la transparence."],
  ["To underscore", "mettre en exergue", "Le rapport met en exergue des \u00e9carts r\u00e9gionaux."],
  ["To contend", "soutenir", "Les chercheurs soutiennent que la politique est inefficace."],
  ["To acknowledge", "reconna\u00eetre", "Il reconna\u00eet les limites de son analyse."],
  ["To downplay", "minimiser", "Certains minimisent l'impact environnemental."],
  ["Far-reaching", "de grande port\u00e9e", "Il s'agit d'une d\u00e9cision de grande port\u00e9e."],
  ["Contentious", "controvers\u00e9", "Le projet de loi reste controvers\u00e9."],
  ["Pervasive", "omnipr\u00e9sent", "Le ph\u00e9nom\u00e8ne est omnipr\u00e9sent dans les m\u00e9dias."],
  ["Inherent (to)", "inh\u00e9rent \u00e0", "Ce risque est inh\u00e9rent \u00e0 toute r\u00e9forme rapide."],
  ["Normative", "normatif", "Le cadre normatif \u00e9volue lentement."],
  ["Empirical evidence", "les preuves empiriques", "Les preuves empiriques manquent encore."],
  ["Causal link", "le lien de causalit\u00e9", "Le lien de causalit\u00e9 n'est pas \u00e9tabli."],
  ["Structural inequality", "l'in\u00e9galit\u00e9 structurelle", "L'in\u00e9galit\u00e9 structurelle se reproduit sur plusieurs g\u00e9n\u00e9rations."],
  ["Regulatory framework", "le cadre r\u00e9glementaire", "Le cadre r\u00e9glementaire doit \u00eatre clarifi\u00e9."],
  ["Civic engagement", "l'engagement civique", "L'engagement civique renforce la d\u00e9mocratie locale."],
];
