import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

export const TCF_READING_P4: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "PHARMACIE DE GARDE\nEn dehors des heures d'ouverture :\nAppelez le 3237 pour connaître la pharmacie de garde la plus proche.\nOuverte 24h/24 en cas d'urgence.",
    question: "Quel numéro faut-il appeler pour trouver une pharmacie de garde ?",
    options: ["Le 15.", "Le 18.", "Le 3237.", "Le 112."],
    correctIndex: 2,
    explanation: "Il faut appeler le 3237 pour connaître la pharmacie de garde la plus proche.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Email",
    passage: "Bonjour,\nVotre commande n° 48521 a bien été expédiée aujourd'hui. Vous recevrez votre colis dans 3 à 5 jours ouvrés. Numéro de suivi : FR78451236.\nService client",
    question: "Dans combien de jours la personne recevra-t-elle son colis ?",
    options: ["1 à 2 jours.", "2 à 3 jours.", "3 à 5 jours.", "5 à 7 jours."],
    correctIndex: 2,
    explanation: "L'email indique une livraison dans 3 à 5 jours ouvrés.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Affiche",
    passage: "ATELIER POTERIE\nPour adultes et enfants (dès 8 ans)\nSamedi 14h–17h\nMatériel fourni · 20 € par séance\nInscription : atelierceramique.fr",
    question: "Quel est le prix de l'atelier poterie par séance ?",
    options: ["15 €.", "18 €.", "20 €.", "25 €."],
    correctIndex: 2,
    explanation: "L'atelier de poterie coûte 20 € par séance, matériel fourni.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Message",
    passage: "Salut Amina !\nJ'ai trouvé ton écharpe rouge dans ma voiture. Je te la rapporte demain au bureau. À demain !\nCamille",
    question: "Qu'est-ce que Camille a trouvé dans sa voiture ?",
    options: ["Un téléphone.", "Un sac.", "Une écharpe rouge.", "Des clés."],
    correctIndex: 2,
    explanation: "Camille a trouvé l'écharpe rouge d'Amina dans sa voiture.",
  },
  {
    id: 5,
    level: "A1",
    passageType: "Panneau",
    passage: "ASCENSEUR EN PANNE\nNous nous excusons pour la gêne occasionnée.\nRéparation prévue : vendredi 15 novembre\nEn cas d'urgence, contactez le gardien au 01 23 45 67 89",
    question: "Quand l'ascenseur sera-t-il réparé ?",
    options: ["Mardi.", "Mercredi.", "Jeudi.", "Vendredi 15 novembre."],
    correctIndex: 3,
    explanation: "La réparation de l'ascenseur est prévue pour le vendredi 15 novembre.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Article court",
    passage: "Le Tour de France est la plus célèbre course cycliste au monde. Il dure 23 jours et couvre environ 3 500 kilomètres. Les coureurs traversent différentes régions de France et parfois des pays voisins comme la Belgique ou l'Espagne. Le maillot jaune est porté par le leader du classement général.",
    question: "Que représente le maillot jaune au Tour de France ?",
    options: ["Le meilleur grimpeur.", "Le leader du classement général.", "Le coureur le plus rapide du jour.", "Le meilleur jeune coureur."],
    correctIndex: 1,
    explanation: "Le maillot jaune est porté par le leader du classement général au Tour de France.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Email",
    passage: "Objet : Votre abonnement\n\nBonjour,\nVotre abonnement mensuel à notre salle de sport est arrivé à expiration. Pour le renouveler, connectez-vous à votre espace client et choisissez votre formule. Si vous ne renouvelez pas dans les 7 jours, votre accès sera suspendu.",
    question: "Que doit faire le client pour renouveler son abonnement ?",
    options: ["Appeler le service client.", "Se rendre en personne à la salle.", "Se connecter à son espace client en ligne.", "Envoyer un chèque."],
    correctIndex: 2,
    explanation: "Pour renouveler son abonnement, le client doit se connecter à son espace client en ligne.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "Annonce",
    passage: "COURS PARTICULIERS — MATHÉMATIQUES\nJe propose des cours de maths pour collégiens et lycéens.\n• Niveau : 6e–Terminale\n• À domicile ou en ligne\n• Tarif : 25 €/heure\n• Première séance d'essai gratuite\nContact : mathsavecmoi@gmail.com",
    question: "Qu'est-ce qui est offert gratuitement ?",
    options: ["Un manuel scolaire.", "La première séance.", "Un bilan de niveau.", "Deux heures de cours."],
    correctIndex: 1,
    explanation: "L'annonce propose une première séance d'essai gratuite.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Affiche",
    passage: "EXPOSITION TEMPORAIRE\n« Portraits du Monde »\nPhotographies de 40 pays\n15 octobre – 30 janvier\nEntrée libre le premier dimanche du mois\nOuverte tous les jours sauf le mardi",
    question: "Quand l'entrée est-elle gratuite à l'exposition ?",
    options: ["Tous les dimanches.", "Le samedi.", "Le premier dimanche du mois.", "Le dernier jour de chaque mois."],
    correctIndex: 2,
    explanation: "L'entrée est libre uniquement le premier dimanche du mois.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Règlement",
    passage: "CONDITIONS D'UTILISATION DU PARKING\n• Durée maximale : 3 heures\n• Tarif : 1,50 €/heure\n• Réservé aux clients du centre commercial\n• Ticket à valider en caisse\n⚠ Stationnement interdit la nuit (22h–8h)",
    question: "Combien peut-on rester maximum dans ce parking ?",
    options: ["1 heure.", "2 heures.", "3 heures.", "Sans limite pour les clients."],
    correctIndex: 2,
    explanation: "La durée maximale de stationnement est de 3 heures.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "Les espaces de coworking se multiplient dans les villes françaises. Ces bureaux partagés offrent aux indépendants et télétravailleurs un cadre professionnel sans les contraintes d'un bureau traditionnel. Les formules varient : hot-desk à la journée, poste fixe mensuel, salles de réunion à l'heure. Au-delà du cadre de travail, ces espaces favorisent les rencontres et synergies entre professionnels de secteurs variés.",
    question: "Quel avantage les espaces de coworking offrent-ils au-delà du cadre de travail ?",
    options: ["Une adresse postale professionnelle reconnue.", "Un accès à des équipements industriels spécialisés.", "Des rencontres et synergies entre professionnels de différents secteurs.", "Un statut juridique de micro-entrepreneur."],
    correctIndex: 2,
    explanation: "Les coworkings favorisent les rencontres et synergies entre professionnels de secteurs variés.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Article",
    passage: "La communication non violente (CNV), développée par Marshall Rosenberg, propose un cadre pour exprimer ses besoins sans violence verbale et pour écouter avec empathie. Elle repose sur quatre étapes : observation factuelle, expression des sentiments, identification des besoins, et formulation d'une demande concrète et réalisable. La CNV est utilisée en médiation de conflits, en éducation et en management.",
    question: "Combien d'étapes comporte la communication non violente ?",
    options: ["Deux.", "Trois.", "Quatre.", "Cinq."],
    correctIndex: 2,
    explanation: "La CNV repose sur quatre étapes : observation, sentiments, besoins, demande.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Article",
    passage: "Le chômage structurel, contrairement au chômage conjoncturel lié aux cycles économiques, reflète un décalage durable entre les qualifications disponibles et les besoins du marché du travail. Il touche particulièrement les secteurs en déclin comme l'industrie manufacturière, tandis que les secteurs numériques et de services à la personne peinent à recruter des profils adaptés.",
    question: "Qu'est-ce qui distingue le chômage structurel du chômage conjoncturel ?",
    options: ["Le chômage structurel est temporaire, le conjoncturel est durable.", "Le chômage structurel est un décalage durable entre qualifications et besoins du marché.", "Le chômage structurel touche uniquement les jeunes.", "Le chômage conjoncturel est causé par les politiques fiscales."],
    correctIndex: 1,
    explanation: "Le chômage structurel est un décalage durable entre les qualifications disponibles et les besoins du marché du travail.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Article",
    passage: "Le chèque éducation, expérimenté dans certains pays, consiste à allouer à chaque famille un bon qu'elle peut utiliser dans l'école de son choix, publique ou privée. Ses défenseurs y voient un levier d'émancipation pour les familles défavorisées. Ses critiques estiment qu'il creuse les inégalités en favorisant les familles capables de naviguer dans le système éducatif.",
    question: "Quelle critique est adressée au chèque éducation ?",
    options: ["Son coût excessif pour l'État.", "Il favorise les familles capables de faire des choix éclairés, creusant les inégalités.", "Il favorise les écoles privées de luxe.", "Il nuit à la qualité de l'enseignement public."],
    correctIndex: 1,
    explanation: "Les critiques estiment que le chèque éducation profite surtout aux familles qui savent naviguer dans le système.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Le volontourisme, contraction de « volontariat » et « tourisme », consiste à voyager dans un pays étranger tout en réalisant des actions de bénévolat. Si ce phénomène séduit beaucoup de jeunes Occidentaux, des ONG mettent en garde contre ses dérives : des projets mal conçus peuvent déstabiliser les communautés locales ou priver des travailleurs qualifiés d'emplois.",
    question: "Quelle mise en garde les ONG formulent-elles contre le volontourisme ?",
    options: ["Il coûte trop cher aux participants.", "Des projets mal conçus peuvent nuire aux communautés locales.", "Il manque de suivi et d'évaluation rigoureuse.", "Il ne développe pas les compétences professionnelles des volontaires."],
    correctIndex: 1,
    explanation: "Des projets mal conçus peuvent déstabiliser les communautés locales ou priver des travailleurs qualifiés d'emplois.",
  },
  {
    id: 16,
    level: "B2",
    passageType: "Article",
    passage: "La marchandisation de la nature soulève des débats éthiques fondamentaux. Attribuer une valeur monétaire aux services écosystémiques — purification de l'air, régulation du climat, pollinisation — permet de les intégrer dans les calculs économiques. Mais des philosophes comme Michael Sandel avertissent que mettre un prix sur la nature risque de corrompre notre rapport à elle en la réduisant à une ressource quantifiable.",
    question: "Quelle critique Michael Sandel formule-t-il contre la marchandisation de la nature ?",
    options: ["Elle sous-évalue les ressources naturelles.", "Elle corrompt notre rapport à la nature en la réduisant à une ressource quantifiable.", "Elle favorise les entreprises polluantes qui achètent des droits.", "Elle exclut les pays pauvres des marchés environnementaux."],
    correctIndex: 1,
    explanation: "Sandel craint que la marchandisation corrompe notre rapport à la nature en la transformant en marchandise calculable.",
  },
  {
    id: 17,
    level: "B2",
    passageType: "Article",
    passage: "Le déclin des abeilles, lié aux pesticides, à la perte d'habitats et aux maladies, menace la sécurité alimentaire mondiale. Un tiers de notre alimentation dépend de la pollinisation par les abeilles. Des agriculteurs et citoyens s'engagent dans l'apiculture urbaine pour pallier ce déclin, installant des ruches sur les toits des villes. Mais cette solution ne peut remplacer la préservation des habitats naturels.",
    question: "Pourquoi les abeilles sont-elles cruciales pour la sécurité alimentaire ?",
    options: ["Elles produisent du miel consommé par des milliards de personnes.", "Un tiers de notre alimentation dépend de leur action de pollinisation.", "Elles représentent un indicateur de la qualité de l'environnement.", "Elles contribuent à la décomposition des matières organiques."],
    correctIndex: 1,
    explanation: "Un tiers de notre alimentation dépend de la pollinisation par les abeilles.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Éditorial",
    passage: "L'accélération sociale, théorisée par Hartmut Rosa, se manifeste dans trois dimensions : accélération technologique, accélération du rythme de vie social, et accélération du rythme du changement culturel. Cette triple accélération engendre ce que Rosa nomme l'aliénation : une incapacité à établir des relations signifiantes avec le monde, les autres et soi-même. Le remède n'est pas le ralentissement mais la résonance — une relation vivante au monde.",
    question: "Quelle est la réponse de Rosa à l'aliénation produite par l'accélération sociale ?",
    options: ["Le ralentissement de toutes les activités.", "La déconnexion numérique.", "La résonance — une relation vivante et signifiante au monde.", "Le retour aux communautés rurales."],
    correctIndex: 2,
    explanation: "Rosa propose la résonance — une relation vivante avec le monde — et non le simple ralentissement.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Article",
    passage: "Les migrations climatiques représentent l'un des défis humanitaires majeurs du XXIe siècle. Des études projettent que 200 millions de personnes pourraient être déplacées d'ici 2050 par la montée des eaux, les sécheresses et les événements météorologiques extrêmes. Ces déplacés ne bénéficient d'aucune protection juridique internationale spécifique, car la Convention de Genève ne couvre pas les causes environnementales.",
    question: "Combien de personnes pourraient être déplacées par les changements climatiques d'ici 2050 selon les études ?",
    options: ["50 millions.", "100 millions.", "200 millions.", "500 millions."],
    correctIndex: 2,
    explanation: "Des études projettent que 200 millions de personnes pourraient être déplacées d'ici 2050.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "Le dialogue interculturel en entreprise dépasse la simple tolérance pour devenir un outil stratégique. Des études de McKinsey montrent que les équipes diversifiées prennent de meilleures décisions et innovent davantage. Cependant, la diversité non accompagnée d'inclusion — sentiment d'appartenance et valorisation des différences — peut générer tensions et incompréhensions plutôt que synergies.",
    question: "Quelle condition est nécessaire pour que la diversité génère des synergies ?",
    options: ["Que tous les membres parlent la même langue.", "L'inclusion — sentiment d'appartenance et valorisation des différences.", "La présence d'un médiateur interculturel dans l'équipe.", "Une formation préalable sur toutes les cultures représentées."],
    correctIndex: 1,
    explanation: "La diversité doit être accompagnée d'inclusion — sentiment d'appartenance et valorisation des différences — pour générer des synergies.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Article",
    passage: "La crise de la presse écrite s'accélère. La publicité, ancienne source principale de revenus des journaux, s'est massivement déplacée vers les plateformes numériques. Face à cette concurrence, les journaux se tournent vers les abonnements numériques et les modèles de financement participatif. La question de la viabilité économique du journalisme d'investigation reste entière.",
    question: "Quel est le principal défi économique de la presse écrite selon cet article ?",
    options: ["Le coût du papier et de l'impression.", "La migration de la publicité vers les plateformes numériques.", "Le manque de journalistes formés.", "La concurrence internationale."],
    correctIndex: 1,
    explanation: "Le défi principal est la migration massive des revenus publicitaires vers les plateformes numériques.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Article",
    passage: "L'intelligence artificielle générative bouleverse les industries créatives. Des outils comme Midjourney ou DALL-E peuvent produire des images de haute qualité en quelques secondes. Si certains artistes voient dans ces outils un assistant puissant, d'autres y lisent une menace existentielle pour leur métier. Le débat sur les droits d'auteur des œuvres générées par IA reste non résolu.",
    question: "Quel débat juridique l'IA générative suscite-t-elle dans les industries créatives ?",
    options: ["La responsabilité en cas d'œuvres offensantes.", "Les droits d'auteur des œuvres générées par IA.", "La fiscalité des entreprises développant des outils d'IA.", "L'accès équitable à ces outils pour tous les artistes."],
    correctIndex: 1,
    explanation: "Le débat sur les droits d'auteur des œuvres générées par IA reste non résolu.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Article",
    passage: "La politique du « zéro déchet » gagne en popularité dans plusieurs villes européennes. Ljubljana en Slovénie recycle déjà plus de 68 % de ses déchets. Cette réussite repose sur une infrastructure de tri performante, une éducation civique intensive, et un système de facturation incitant les ménages à produire moins de déchets non recyclables.",
    question: "Sur quels piliers repose le succès du zéro déchet à Ljubljana ?",
    options: ["Interdiction des emballages plastiques et amendes élevées.", "Infrastructure de tri, éducation civique et système de facturation incitatif.", "Technologie de valorisation énergétique des déchets.", "Exportation des déchets vers d'autres pays."],
    correctIndex: 1,
    explanation: "Le succès de Ljubljana repose sur l'infrastructure de tri, l'éducation civique et un système de facturation incitatif.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Article",
    passage: "La littérature de témoignage occupe une place particulière dans les corpus scolaires francophones. Des œuvres comme Si c'est un homme de Primo Levi ou La Nuit d'Elie Wiesel transmettent l'expérience des camps de concentration aux nouvelles générations. L'enjeu pédagogique est double : transmettre la mémoire et développer l'empathie face à la souffrance de l'autre.",
    question: "Quel est le double enjeu pédagogique de la littérature de témoignage à l'école ?",
    options: ["Améliorer les compétences en lecture et en écriture.", "Transmettre la mémoire historique et développer l'empathie.", "Enrichir le vocabulaire et la connaissance de l'histoire.", "Initier les élèves à la littérature classique."],
    correctIndex: 1,
    explanation: "La littérature de témoignage vise à transmettre la mémoire historique et à développer l'empathie chez les élèves.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Les villes du Grand Nord canadien font face à des défis uniques liés au réchauffement climatique : fonte du pergélisol, érosion côtière accélérée, modification des patterns de migration animale qui affectent les moyens de subsistance des communautés autochtones. Ces changements contraignent certaines communautés à envisager une relocalisation, un déchirement culturel et identitaire profond.",
    question: "Pourquoi certaines communautés autochtones du Grand Nord envisagent-elles une relocalisation ?",
    options: ["Pour accéder à de meilleurs services de santé.", "À cause des changements climatiques : fonte du pergélisol, érosion et modification de la migration animale.", "Pour fuir les conflits territoriaux avec l'industrie pétrolière.", "Pour rejoindre des centres urbains avec plus d'opportunités économiques."],
    correctIndex: 1,
    explanation: "La fonte du pergélisol, l'érosion côtière et la modification des migrations animales contraignent certaines communautés à envisager de partir.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    passageType: "Extrait philosophique — Spinoza",
    passage: "Pour Spinoza, la liberté ne consiste pas dans l'absence de nécessité mais dans l'adéquation entre notre nature et nos actes. L'homme libre n'agit pas contre sa nature mais selon elle, guidé par la raison plutôt que par les passions qui l'aliènent. Cette conception immanente de la liberté s'oppose à la liberté cartésienne du libre arbitre, conçue comme un pouvoir de la volonté indépendant de la causalité naturelle.",
    question: "Comment Spinoza définit-il la liberté humaine ?",
    options: ["Comme le libre arbitre de la volonté indépendant des causes naturelles.", "Comme l'adéquation entre notre nature et nos actes, guidée par la raison.", "Comme la capacité d'ignorer les nécessités naturelles.", "Comme l'affranchissement total des passions humaines."],
    correctIndex: 1,
    explanation: "Pour Spinoza, la liberté est l'adéquation entre notre nature et nos actes guidés par la raison, non l'absence de nécessité.",
  },
  {
    id: 27,
    level: "C1",
    passageType: "Article académique",
    passage: "Le mouvement des Cultural Studies, né en Grande-Bretagne dans les années 1960 autour du Centre for Contemporary Cultural Studies de Birmingham, a radicalement élargi le champ des études culturelles en refusant la distinction entre culture haute et culture populaire. Pour des théoriciens comme Stuart Hall, les pratiques culturelles ordinaires — la télévision, la musique populaire, la mode — sont des sites de lutte symbolique et de négociation de sens.",
    question: "Quelle rupture les Cultural Studies ont-elles opérée ?",
    options: ["Elles ont introduit la méthode ethnographique dans l'analyse littéraire.", "Elles ont refusé la hiérarchie entre culture haute et populaire, analysant les deux comme sites de luttes symboliques.", "Elles ont privilégié les cultures non occidentales par rapport aux cultures européennes.", "Elles ont remplacé l'analyse textuelle par l'analyse des industries culturelles."],
    correctIndex: 1,
    explanation: "Les Cultural Studies ont refusé la distinction entre haute culture et culture populaire, traitant les deux comme sites de luttes symboliques.",
  },
  {
    id: 28,
    level: "C1",
    passageType: "Extrait littéraire — Marie-Claire Blais",
    passage: "Dans cette ville d'hiver, les mots se figeaient avant d'atteindre leurs destinataires. Elle avait appris à parler autrement : par gestes, par silences, par la chaleur d'une main posée sur une épaule. Les langues, pensait-elle, étaient comme des maisons — on pouvait en habiter plusieurs, mais la maison de l'enfance restait celle où les rêves avaient encore leur couleur d'origine.",
    question: "Quelle métaphore l'auteure utilise-t-elle pour décrire les langues ?",
    options: ["Des instruments de musique aux tonalités différentes.", "Des maisons, dont celle de l'enfance garde une qualité irremplaçable.", "Des habits que l'on change selon les saisons.", "Des cartes géographiques du monde intérieur."],
    correctIndex: 1,
    explanation: "L'auteure compare les langues à des maisons, dont celle de l'enfance garde une qualité originelle irremplaçable.",
  },
  {
    id: 29,
    level: "C1",
    passageType: "Article académique",
    passage: "La notion de genre littéraire est à la fois un outil de classement et un horizon d'attente pour le lecteur. Gérard Genette, dans Introduction à l'architexte, montre que les genres ne sont pas des essences naturelles mais des conventions évolutives, produites par l'histoire littéraire et les institutions de légitimation. Un texte peut simultanément appartenir à plusieurs genres et les subvertir.",
    question: "Comment Genette conçoit-il les genres littéraires ?",
    options: ["Comme des catégories biologiques déterminées par la nature humaine.", "Comme des conventions évolutives produites par l'histoire littéraire, non des essences naturelles.", "Comme des structures immuables définies par Aristote.", "Comme des étiquettes commerciales créées par l'industrie éditoriale."],
    correctIndex: 1,
    explanation: "Pour Genette, les genres sont des conventions évolutives historiquement construites, non des catégories naturelles.",
  },
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "La mémoire collective, concept forgé par Maurice Halbwachs, désigne la représentation du passé partagée par un groupe social. Contrairement à la mémoire individuelle, elle est toujours présente — reconstituée en fonction des besoins et des valeurs du présent. Cette plasticité explique pourquoi les commémorations sont des enjeux politiques : elles construisent une vision du passé qui légitime des positions dans le présent.",
    question: "Pourquoi les commémorations sont-elles des enjeux politiques selon Halbwachs ?",
    options: ["Parce qu'elles coûtent cher à l'État.", "Parce qu'elles construisent une vision du passé qui légitime des positions dans le présent.", "Parce qu'elles mobilisent des communautés politiques.", "Parce qu'elles influencent les relations diplomatiques."],
    correctIndex: 1,
    explanation: "Les commémorations sont politiques car elles construisent une version du passé qui sert à légitimer des positions et des valeurs dans le présent.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Article académique",
    passage: "La créolisation, concept forgé par Édouard Glissant, désigne un processus de mélange culturel imprévisible et irréductible qui produit quelque chose de radicalement nouveau. Contrairement au métissage qui suppose des racines identifiables, la créolisation est un devenir rhizomique, sans origine assignable. Pour Glissant, c'est le modèle de la relation dans le monde actuel, s'opposant au repli identitaire.",
    question: "En quoi la créolisation se distingue-t-elle du métissage selon Glissant ?",
    options: ["Elle concerne uniquement les populations des Caraïbes.", "Elle est un devenir rhizomique sans origine assignable, produisant quelque chose de radicalement nouveau.", "Elle préserve les cultures d'origine dans leur pureté.", "Elle implique une synthèse planifiée entre deux cultures."],
    correctIndex: 1,
    explanation: "La créolisation produit quelque chose de nouveau sans origines assignables, s'opposant au métissage qui suppose des racines identifiables.",
  },
  {
    id: 32,
    level: "C2",
    passageType: "Extrait philosophique — Simone Weil",
    passage: "Pour Simone Weil, l'affliction est distincte de la simple souffrance : elle est une douleur qui détruit la personnalité même, qui brise le lien entre l'être et son existence sociale. L'affliction des opprimés est une réalité spirituelle autant que sociale : leur invisibilité aux yeux du monde reproduit leur destruction intérieure. L'attention — cette forme d'amour qui se tourne vers l'autre dans son malheur — est la seule réponse éthique authentique.",
    question: "Qu'est-ce que l'attention selon Simone Weil ?",
    options: ["Une concentration intellectuelle nécessaire à l'apprentissage.", "Une forme d'amour qui se tourne vers l'autre dans son malheur, seule réponse éthique authentique.", "Une attitude de vigilance face aux injustices sociales.", "Un exercice spirituel de méditation sur la souffrance humaine."],
    correctIndex: 1,
    explanation: "Pour Weil, l'attention est une forme d'amour tournée vers la souffrance de l'autre — seule réponse éthique à l'affliction.",
  },
  {
    id: 33,
    level: "C2",
    passageType: "Article académique",
    passage: "L'analyse des récits de migration dans la littérature francophone révèle des structures narratives récurrentes. Le récit de départ met en scène une rupture traumatique avec le monde d'origine ; le récit d'arrivée confronte le personnage à l'altérité radicale ; le récit d'installation explore la tension entre assimilation et résistance identitaire. Ces trois temps forment ce que des narratologues ont appelé le triptye migratoire.",
    question: "Que désigne le « triptye migratoire » dans l'analyse des récits de migration ?",
    options: ["Une structure narrative en trois temps : départ, arrivée, installation.", "Les trois formes grammaticales du récit de migration.", "Les trois pays traversés dans un récit de migration typique.", "Les trois générations décrites dans les romans de migration."],
    correctIndex: 0,
    explanation: "Le triptye migratoire est une structure narrative en trois temps : rupture au départ, confrontation à l'arrivée, et négociation identitaire à l'installation.",
  },
  {
    id: 34,
    level: "C2",
    passageType: "Essai",
    passage: "La distinction entre le sacré et le profane, fondamentale dans la sociologie durkheimienne de la religion, ne renvoie pas à une catégorie théologique mais sociale : est sacré ce qu'une société met à l'écart, entoure d'interdits et qui cristallise la conscience collective. Dans les sociétés sécularisées, ce sacré a migré vers des objets laïques : la nation, les droits de l'homme, la science.",
    question: "Comment Durkheim définit-il le sacré dans la sociologie de la religion ?",
    options: ["Comme ce qui transcende l'existence humaine et conduit à la divinité.", "Comme une catégorie sociale désignant ce qu'une société met à l'écart et entoure d'interdits.", "Comme ce que les individus respectent par tradition religieuse.", "Comme l'ensemble des rites et pratiques d'une religion."],
    correctIndex: 1,
    explanation: "Pour Durkheim, le sacré est une catégorie sociale — non théologique — désignant ce qu'une communauté isole et entoure d'interdits.",
  },
  {
    id: 35,
    level: "C2",
    passageType: "Article académique",
    passage: "La pragmatique linguistique s'intéresse aux actes de langage — ce que nous faisons quand nous parlons. John Austin distingue l'acte locutoire (dire quelque chose), l'acte illocutoire (faire quelque chose en disant) et l'acte perlocutoire (produire un effet sur l'interlocuteur). Promettre, ordonner, déclarer — ces actes illocutoires ne décrivent pas la réalité : ils la modifient.",
    question: "Qu'est-ce qu'un acte illocutoire selon Austin ?",
    options: ["L'énonciation d'un son ou d'une phrase.", "L'action accomplie en parlant, qui modifie la réalité.", "L'effet produit sur l'interlocuteur.", "Une faute de prononciation qui change le sens."],
    correctIndex: 1,
    explanation: "L'acte illocutoire est l'action accomplie en parlant — promettre, ordonner, déclarer — qui modifie la réalité.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Essai",
    passage: "Le concept d'habitus de Bourdieu désigne les dispositions durables et transposables acquises par la socialisation, qui orientent les pratiques et perceptions sans qu'il soit besoin d'une délibération consciente. L'habitus est à la fois structuré — produit des conditions sociales d'existence — et structurant : il génère des pratiques et des représentations adaptées aux différents champs sociaux.",
    question: "Quelle est la double nature de l'habitus selon Bourdieu ?",
    options: ["Individuel et collectif.", "Conscient et inconscient.", "Structuré par les conditions sociales et structurant des pratiques.", "Stable dans le temps et adaptable aux circonstances."],
    correctIndex: 2,
    explanation: "L'habitus est à la fois structuré (produit par les conditions sociales) et structurant (générant des pratiques et perceptions).",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "La notion de frontière en littérature postcoloniale dépasse la géographie pour devenir une métaphore épistémologique. Gloria Anzaldúa, dans Borderlands/La Frontera, décrit la frontière comme un lieu de blessure et de créativité : ceux qui l'habitent développent une conscience mestiza, une pensée plurielle capable de tenir ensemble des perspectives contradictoires. Cette posture épistémologique est à la fois une condition d'existence et une ressource intellectuelle.",
    question: "Qu'est-ce que la conscience mestiza selon Anzaldúa ?",
    options: ["Une identité culturelle mexicaine-américaine.", "Une pensée plurielle capable de tenir ensemble des perspectives contradictoires.", "Un sentiment de honte lié à l'hybridité culturelle.", "Une forme de nationalisme frontalier."],
    correctIndex: 1,
    explanation: "La conscience mestiza est une pensée plurielle capable de tenir des perspectives contradictoires — ressource de la vie aux frontières.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai",
    passage: "La pensée utopique, de Thomas More à Ernst Bloch, n'est pas une fuite de la réalité mais son approfondissement critique. L'utopie, selon Bloch, est inscrite dans la réalité comme sa dimension d'espoir non encore accompli : le principe espérance. Ce n'est pas le futur imaginé qui compte mais la force anticipatrice qui restructure le présent. L'utopie est donc moins un rêve qu'une méthode critique de dévoilement des possibles.",
    question: "Comment Ernst Bloch conçoit-il l'utopie ?",
    options: ["Comme une illusion dangereuse qui détourne de la réalité.", "Comme une dimension d'espoir inscrite dans le présent, restructurant le rapport au réel.", "Comme un modèle de société parfaite à construire.", "Comme un genre littéraire né au XVIe siècle avec Thomas More."],
    correctIndex: 1,
    explanation: "Pour Bloch, l'utopie est le principe espérance inscrit dans la réalité — une force anticipatrice qui restructure le présent.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article académique",
    passage: "L'idée de reconnaissance mutuelle entre cultures, défendue par des philosophes comme Charles Taylor et Paul Ricœur, propose de dépasser à la fois l'ethnocentrisme — qui écrase les différences — et le relativisme — qui les absolutise. L'herméneutique des cultures permet une « fusion d'horizons » (Gadamer) par laquelle on comprend l'autre sans le réduire à sa propre grille de lecture ni abandonner la sienne.",
    question: "Comment l'herméneutique des cultures propose-t-elle de dépasser l'ethnocentrisme et le relativisme ?",
    options: ["En choisissant une culture neutre comme référence commune.", "Par une fusion d'horizons permettant de comprendre l'autre sans se dissoudre ni le réduire.", "En apprenant à parler toutes les langues du monde.", "En soumettant les cultures à une évaluation éthique universelle."],
    correctIndex: 1,
    explanation: "La fusion d'horizons gadamérienne permet de comprendre l'autre sans le réduire à notre grille ni abandonner la nôtre.",
  },
];
