import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 6 — Compréhension écrite. Theme: settling into working life in Canada.
 *
 * Hand-authored to keep distractors plausible and similar in length, so no
 * surface heuristic (longest option, option B) beats reading the text.
 */
export const TCF_READING_P6: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Panneau",
    passage: "CLINIQUE SANS RENDEZ-VOUS\nOuvert du lundi au samedi\n8 h – 20 h\nFermé les jours fériés\nCarte d'assurance maladie obligatoire",
    question: "Quel jour la clinique est-elle fermée ?",
    options: ["Le samedi.", "Le dimanche.", "Le lundi.", "Le vendredi."],
    correctIndex: 1,
    explanation: "The sign lists Monday to Saturday, so Sunday is the missing day.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Étiquette",
    passage: "SOUPE AUX POIS\nÀ conserver au réfrigérateur\nRéchauffer 3 minutes avant de servir\nÀ consommer dans les 4 jours après ouverture\n450 g",
    question: "Où faut-il garder ce produit ?",
    options: ["Au congélateur.", "Dans un placard.", "Au réfrigérateur.", "Près d'une fenêtre."],
    correctIndex: 2,
    explanation: "The label says 'À conserver au réfrigérateur' — keep refrigerated.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Message",
    passage: "Salut Yann,\nJe t'attends devant le cinéma à 19 h. Le film commence à 19 h 30. N'oublie pas les billets, ils sont sur ton bureau !\nÀ tout à l'heure,\nInès",
    question: "Que Yann doit-il apporter ?",
    options: ["Les billets.", "De la monnaie.", "Un parapluie.", "Son ordinateur."],
    correctIndex: 0,
    explanation: "Inès reminds him not to forget the tickets ('les billets').",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "COURS DE NATATION\nPiscine municipale de Laval\nDébutants adultes\nMardi et jeudi, 18 h – 19 h\n60 $ pour dix séances\nInscription à l'accueil",
    question: "Combien coûtent les dix séances ?",
    options: ["18 dollars.", "19 dollars.", "50 dollars.", "60 dollars."],
    correctIndex: 3,
    explanation: "The notice states 60 $ for ten sessions.",
  },
  {
    id: 5,
    level: "A2",
    passageType: "Courriel",
    passage: "Objet : Votre commande n° 4471\n\nBonjour,\nVotre commande est prête. Vous pouvez la retirer en magasin dès demain, du lundi au vendredi entre 10 h et 18 h. Passé quinze jours, elle sera automatiquement remboursée.\nCordialement,\nService clientèle",
    question: "Que se passe-t-il si le client ne vient pas dans les quinze jours ?",
    options: [
      "La commande est envoyée à son domicile.",
      "La commande est remboursée automatiquement.",
      "La commande est conservée un mois de plus.",
      "La commande est offerte à un autre client.",
    ],
    correctIndex: 1,
    explanation: "After fifteen days the order is automatically refunded.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Note de service",
    passage: "AVIS AUX EMPLOYÉS\nL'ascenseur principal sera en réparation du 3 au 7 mars. Veuillez utiliser l'escalier ou l'ascenseur de service situé près de la cafétéria. Les livraisons se feront par l'entrée arrière.\nLa direction",
    question: "Que doivent faire les employés pendant les travaux ?",
    options: [
      "Travailler depuis chez eux.",
      "Entrer par la porte arrière.",
      "Prendre l'escalier ou l'ascenseur de service.",
      "Décaler leurs horaires de travail.",
    ],
    correctIndex: 2,
    explanation: "Employees are told to use the stairs or the service lift; the rear entrance is for deliveries.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Petite annonce",
    passage: "COLOCATION — QUARTIER SAINT-ROCH\nChambre meublée dans un appartement de trois pièces. 520 $ par mois, électricité comprise, Internet non compris. Non-fumeur. Animaux acceptés. Libre le 1er mai.",
    question: "Qu'est-ce qui n'est pas inclus dans le loyer ?",
    options: ["L'électricité.", "Les meubles.", "L'accès Internet.", "Le chauffage."],
    correctIndex: 2,
    explanation: "Electricity is included but Internet explicitly is not.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "Programme",
    passage: "SEMAINE DE LA FRANCOPHONIE\nLundi : conférence sur les accents du Québec\nMardi : atelier d'écriture\nMercredi : projection d'un documentaire\nJeudi : soirée musicale\nEntrée libre sauf le jeudi (10 $)",
    question: "Quelle activité est payante ?",
    options: ["La conférence.", "L'atelier d'écriture.", "La projection.", "La soirée musicale."],
    correctIndex: 3,
    explanation: "Entry is free except on Thursday, which is the musical evening.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Consigne",
    passage: "DEMANDE DE CARTE DE TRANSPORT\nRemplissez le formulaire en ligne, puis présentez-vous au comptoir avec une photo récente et une preuve de résidence. La carte est remise sur place en dix minutes. Aucun paiement en espèces.",
    question: "Comment le client peut-il payer sa carte ?",
    options: [
      "En espèces uniquement.",
      "Par un moyen autre que les espèces.",
      "Au moment de la demande en ligne.",
      "À la fin du premier mois d'utilisation.",
    ],
    correctIndex: 1,
    explanation: "The notice rules out cash, so payment must be by another means.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Courriel",
    passage: "Bonjour Madame Léger,\nJe vous confirme notre rendez-vous de jeudi à 14 h. Comme convenu, je vous apporterai les relevés de notes traduits. En revanche, le certificat de travail ne sera prêt que la semaine prochaine.\nBien à vous,\nOumar Diallo",
    question: "Quel document M. Diallo ne pourra-t-il pas apporter jeudi ?",
    options: [
      "Les relevés de notes traduits.",
      "Une pièce d'identité valide.",
      "Le certificat de travail.",
      "La confirmation du rendez-vous.",
    ],
    correctIndex: 2,
    explanation: "The work certificate will only be ready the following week.",
  },

  // ── B1–B2 (Q11–29) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "De plus en plus d'employeurs canadiens acceptent de reconnaître l'expérience acquise à l'étranger, à condition qu'elle soit documentée. Un ancien comptable arrivé de Tunis ne repart plus nécessairement de zéro : s'il fournit des attestations d'emploi et une équivalence de diplôme, il peut postuler à des postes intermédiaires. Le principal obstacle reste le délai administratif, souvent plusieurs mois.",
    question: "Quel est le principal frein mentionné dans le texte ?",
    options: [
      "Le refus des employeurs de recruter à l'étranger.",
      "L'absence d'équivalence pour les diplômes étrangers.",
      "La longueur des démarches administratives.",
      "Le niveau de français exigé pour ces postes.",
    ],
    correctIndex: 2,
    explanation: "The text names administrative delays of several months as the main obstacle.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Chronique",
    passage: "On répète aux nouveaux arrivants qu'il faut « réseauter ». Le conseil est juste mais mal expliqué. Réseauter ne consiste pas à distribuer son curriculum dans une salle bondée ; il s'agit de demander à quelqu'un de vous raconter son métier, sans rien attendre en retour. Les offres viennent ensuite, presque par accident, parce qu'on a laissé une bonne impression.",
    question: "Selon l'auteur, en quoi consiste vraiment le réseautage ?",
    options: [
      "À distribuer son curriculum au plus grand nombre.",
      "À s'intéresser au parcours des autres sans contrepartie immédiate.",
      "À fréquenter uniquement des personnes de son secteur.",
      "À solliciter directement un poste auprès d'un responsable.",
    ],
    correctIndex: 1,
    explanation: "The author defines it as asking others about their work without expecting anything in return.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Guide pratique",
    passage: "Avant de signer un bail au Québec, lisez attentivement la clause portant sur la sous-location. La loi autorise le locataire à sous-louer son logement, mais il doit en informer le propriétaire par écrit et attendre sa réponse pendant quinze jours. Un refus doit être motivé par un motif sérieux, faute de quoi il est considéré comme accepté.",
    question: "Que se passe-t-il si le propriétaire refuse sans motif sérieux ?",
    options: [
      "Le bail est automatiquement annulé.",
      "Le locataire doit quitter le logement.",
      "Le refus vaut acceptation de la sous-location.",
      "Le dossier est transmis à un tribunal.",
    ],
    correctIndex: 2,
    explanation: "Without a serious reason, the refusal is treated as consent.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Reportage",
    passage: "Dans les régions éloignées, le recrutement d'enseignants francophones tourne au casse-tête. Les municipalités offrent des primes d'installation, un logement à prix réduit, parfois même un emploi au conjoint. Malgré ces avantages, la moitié des recrues repartent avant la fin de leur deuxième année, invoquant surtout l'isolement social plutôt que les conditions matérielles.",
    question: "Pourquoi les enseignants recrutés quittent-ils leur poste ?",
    options: [
      "Parce que les salaires proposés restent trop bas.",
      "Parce que le logement fourni est de mauvaise qualité.",
      "Parce qu'ils souffrent avant tout de l'isolement social.",
      "Parce que leur conjoint ne trouve pas de travail.",
    ],
    correctIndex: 2,
    explanation: "They cite social isolation rather than material conditions.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Le covoiturage interurbain a changé les habitudes des étudiants québécois. Pour un trajet Montréal–Québec, il revient deux fois moins cher que le train et s'organise en quelques minutes sur une application. Les transporteurs traditionnels ont réagi en baissant leurs tarifs sur les lignes concurrencées, ce qui profite finalement à tous les voyageurs.",
    question: "Quelle a été la conséquence du covoiturage sur les transporteurs traditionnels ?",
    options: [
      "Ils ont supprimé plusieurs lignes peu rentables.",
      "Ils ont réduit leurs prix sur les lignes concurrencées.",
      "Ils ont lancé leur propre application de covoiturage.",
      "Ils ont augmenté la fréquence de leurs départs.",
    ],
    correctIndex: 1,
    explanation: "Traditional carriers responded by lowering fares on the competing routes.",
  },
  {
    id: 16,
    level: "B1",
    passageType: "Courrier des lecteurs",
    passage: "J'ai lu votre dossier sur le télétravail avec intérêt, mais il oublie une catégorie : les personnes qui vivent seules. Rester chez soi cinq jours sur cette semaine, sans échanger un mot avec un collègue, n'a rien d'un privilège. Je ne demande pas la fin du télétravail, seulement qu'on cesse de le présenter comme un avantage universel.",
    question: "Que reproche la lectrice au dossier publié ?",
    options: [
      "D'avoir critiqué le télétravail de façon excessive.",
      "D'avoir ignoré la situation des personnes vivant seules.",
      "D'avoir confondu télétravail et horaires flexibles.",
      "D'avoir interrogé uniquement des employeurs.",
    ],
    correctIndex: 1,
    explanation: "She objects that the article overlooked people who live alone.",
  },
  {
    id: 17,
    level: "B1",
    passageType: "Note d'information",
    passage: "À compter du 1er septembre, les demandes de congé devront être déposées au moins trois semaines à l'avance, sauf urgence familiale ou médicale dûment justifiée. Les demandes tardives resteront recevables, mais seront traitées après celles soumises dans les délais, sans garantie d'acceptation.",
    question: "Comment seront traitées les demandes déposées en retard ?",
    options: [
      "Elles seront systématiquement refusées.",
      "Elles seront examinées en priorité si le motif est familial.",
      "Elles seront étudiées après les demandes déposées à temps.",
      "Elles devront être transmises à la direction générale.",
    ],
    correctIndex: 2,
    explanation: "Late requests remain admissible but are processed after those filed on time.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Analyse",
    passage: "L'idée selon laquelle la maîtrise de la langue suffirait à garantir l'intégration professionnelle résiste mal à l'examen. Des enquêtes menées auprès de diplômés étrangers montrent que, à niveau de français équivalent, le taux d'embauche varie fortement selon la consonance du nom du candidat. La langue est une condition nécessaire, elle n'est manifestement pas une condition suffisante.",
    question: "Que démontrent les enquêtes citées ?",
    options: [
      "Que le niveau de français reste le premier critère d'embauche.",
      "Qu'à compétence linguistique égale, l'origine perçue influence l'embauche.",
      "Que les diplômés étrangers maîtrisent mal le français professionnel.",
      "Que les employeurs privilégient les candidats déjà expérimentés.",
    ],
    correctIndex: 1,
    explanation: "At equal French level, hiring rates vary by the perceived origin signalled by the candidate's name.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Éditorial",
    passage: "Chaque hiver, la même discussion revient : faut-il déneiger les pistes cyclables ? Les opposants y voient une dépense pour une poignée d'irréductibles. Les données municipales racontent autre chose : là où les pistes sont dégagées, la fréquentation hivernale atteint 40 % du niveau estival. Le cycliste d'hiver n'est pas un militant excentrique, c'est un usager que l'on décourage ou que l'on accompagne.",
    question: "Que montrent les données municipales évoquées ?",
    options: [
      "Que le déneigement des pistes coûte moins cher que prévu.",
      "Que la fréquentation hivernale reste marginale malgré le déneigement.",
      "Qu'une piste dégagée conserve une part importante de ses usagers.",
      "Que les cyclistes d'hiver réclament davantage d'aménagements.",
    ],
    correctIndex: 2,
    explanation: "Where paths are cleared, winter use reaches 40% of summer levels — a substantial share.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article scientifique",
    passage: "Le bilinguisme précoce ne produit pas les prodiges qu'on lui prête parfois. Les enfants bilingues disposent en moyenne d'un vocabulaire légèrement plus restreint dans chacune de leurs langues, mais leur vocabulaire total dépasse celui des monolingues. L'avantage réel se situe ailleurs : dans la capacité à ignorer une information non pertinente, entraînée par le fait de sélectionner constamment une langue.",
    question: "Où se situe le véritable avantage du bilinguisme précoce ?",
    options: [
      "Dans un vocabulaire plus riche dans chaque langue prise séparément.",
      "Dans une meilleure aptitude à écarter les informations non pertinentes.",
      "Dans une acquisition plus rapide de la lecture et de l'écriture.",
      "Dans une mémorisation supérieure des règles grammaticales.",
    ],
    correctIndex: 1,
    explanation: "The real benefit is the ability to ignore irrelevant information, trained by constant language selection.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Enquête",
    passage: "Les banques alimentaires observent un changement de profil parmi leurs usagers. Longtemps associées aux personnes sans emploi, elles accueillent désormais une majorité de ménages dont au moins un membre travaille. Le phénomène ne traduit pas une hausse du chômage mais l'écart croissant entre les salaires d'entrée et le coût du logement dans les grandes villes.",
    question: "Comment le texte explique-t-il l'évolution observée ?",
    options: [
      "Par une augmentation du nombre de personnes sans emploi.",
      "Par une baisse des dons reçus par les banques alimentaires.",
      "Par le décalage entre les bas salaires et le prix du logement.",
      "Par un élargissement des critères d'accès à ces services.",
    ],
    correctIndex: 2,
    explanation: "The cause given is the widening gap between entry-level wages and urban housing costs.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Tribune",
    passage: "On confond volontiers évaluation et notation. Noter un élève, c'est produire un chiffre qui le situe par rapport aux autres ; l'évaluer, c'est décrire ce qu'il sait faire et ce qui lui manque encore. Un bulletin peut être rempli de notes sans contenir la moindre évaluation. C'est précisément ce que reprochent les enseignants qui expérimentent d'autres formes de suivi.",
    question: "Quelle distinction l'auteur établit-il ?",
    options: [
      "La notation classe l'élève, l'évaluation décrit ses acquis.",
      "La notation est objective, l'évaluation reste subjective.",
      "La notation concerne le primaire, l'évaluation le secondaire.",
      "La notation mesure l'effort, l'évaluation mesure le résultat.",
    ],
    correctIndex: 0,
    explanation: "Marking positions the pupil relative to others; evaluation describes what they can and cannot yet do.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Reportage",
    passage: "À Sherbrooke, une ancienne usine de textile abrite désormais une trentaine d'ateliers d'artisans. Le bâtiment n'a pas été rasé puis reconstruit, mais consolidé et réaménagé, ce qui a coûté 20 % de moins qu'une construction neuve et évité l'équivalent de deux mille tonnes de gravats. Le procédé séduit d'autres municipalités confrontées à des friches industrielles.",
    question: "Quel avantage du projet est mis en avant ?",
    options: [
      "Il a permis de créer davantage d'emplois qu'une usine neuve.",
      "Il a été financé entièrement par les artisans installés.",
      "Il a coûté moins cher qu'une construction neuve et limité les déchets.",
      "Il a préservé l'activité textile d'origine du bâtiment.",
    ],
    correctIndex: 2,
    explanation: "Renovation cost 20% less than new construction and avoided two thousand tonnes of rubble.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Analyse économique",
    passage: "La pénurie de main-d'œuvre est souvent présentée comme un phénomène subi. Elle résulte pourtant en partie de choix d'entreprises : postes à horaires fractionnés, contrats courts renouvelés indéfiniment, absence de perspective d'évolution. Là où ces conditions ont été révisées, les candidatures sont revenues en quelques mois, sans que les salaires aient toujours été augmentés.",
    question: "Que suggère l'auteur au sujet de la pénurie de main-d'œuvre ?",
    options: [
      "Qu'elle s'explique uniquement par le vieillissement de la population.",
      "Qu'elle disparaîtrait si les salaires étaient nettement relevés.",
      "Qu'elle tient en partie aux conditions d'emploi proposées.",
      "Qu'elle touche surtout les secteurs exigeant peu de qualification.",
    ],
    correctIndex: 2,
    explanation: "The author attributes it partly to employers' own working conditions, since applications returned when these changed.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "Les plateformes de traduction automatique ont atteint un niveau qui rend leur usage courant en entreprise. Elles échouent pourtant sur un point précis : le registre. Un courriel poli en français devient, une fois traduit, soit sec, soit obséquieux. Cette maladresse passe inaperçue de celui qui l'envoie et rarement de celui qui la reçoit.",
    question: "Quelle limite des traducteurs automatiques est soulignée ?",
    options: [
      "Ils commettent encore de nombreuses fautes de grammaire.",
      "Ils rendent mal le niveau de politesse attendu.",
      "Ils ne traitent pas les langues peu répandues.",
      "Ils exigent une relecture par un traducteur professionnel.",
    ],
    correctIndex: 1,
    explanation: "The flaw named is register: politeness comes out either curt or obsequious.",
  },
  {
    id: 26,
    level: "B2",
    passageType: "Étude urbaine",
    passage: "Réduire la vitesse à 30 km/h dans les rues résidentielles suscite une opposition prévisible : on croit y perdre un temps considérable. Les relevés effectués dans plusieurs quartiers montrent un allongement moyen du trajet de quarante secondes. Ce chiffre, une fois connu, désamorce l'essentiel du débat ; encore faut-il qu'il soit communiqué avant la mise en place, et non après.",
    question: "Que recommande implicitement l'auteur ?",
    options: [
      "De renoncer aux limitations à 30 km/h dans les quartiers résidentiels.",
      "De réaliser des relevés de vitesse après la mise en place des mesures.",
      "D'informer les habitants des chiffres réels avant d'appliquer la mesure.",
      "D'appliquer la limitation uniquement aux abords des écoles.",
    ],
    correctIndex: 2,
    explanation: "The closing clause insists the figure must be communicated before implementation, not after.",
  },
  {
    id: 27,
    level: "B2",
    passageType: "Chronique",
    passage: "Le mot « authentique » a colonisé le vocabulaire commercial au point de ne plus rien désigner. Un restaurant authentique, un cuir authentique, une expérience authentique : le terme survit parce qu'il flatte l'acheteur sans engager le vendeur. Aucune norme ne l'encadre, aucun contrôle ne le sanctionne. Sa vacuité n'est pas un accident, elle est sa fonction.",
    question: "Selon l'auteur, pourquoi le mot « authentique » est-il si répandu ?",
    options: [
      "Parce qu'il correspond à une norme commerciale précise.",
      "Parce qu'il valorise l'acheteur sans engager le vendeur.",
      "Parce qu'il est plus court que les termes concurrents.",
      "Parce que les consommateurs en réclament l'emploi.",
    ],
    correctIndex: 1,
    explanation: "It flatters the buyer while committing the seller to nothing, and no standard governs it.",
  },
  {
    id: 28,
    level: "B2",
    passageType: "Rapport",
    passage: "Les programmes de mentorat destinés aux immigrants qualifiés affichent des résultats contrastés. Ceux qui reposent sur un simple appariement entre un mentor et un mentoré s'essoufflent au bout de trois rencontres. Ceux qui prévoient un objectif écrit, un calendrier et un bilan intermédiaire atteignent des taux de placement nettement supérieurs. La différence tient moins aux personnes qu'au cadre.",
    question: "Qu'est-ce qui distingue les programmes de mentorat efficaces ?",
    options: [
      "La qualité et l'expérience des mentors recrutés.",
      "La proximité géographique entre mentor et mentoré.",
      "L'existence d'un cadre structuré avec objectifs et bilans.",
      "La durée totale de l'accompagnement proposé.",
    ],
    correctIndex: 2,
    explanation: "The text credits the framework — written objective, schedule, interim review — rather than the individuals.",
  },
  {
    id: 29,
    level: "B2",
    passageType: "Essai",
    passage: "On oppose souvent mémoire et histoire comme le subjectif et l'objectif. La distinction est plus subtile. La mémoire est un rapport vivant au passé, porté par un groupe qui s'y reconnaît ; l'histoire est une reconstruction critique, qui accepte de contredire ce que le groupe préfère croire. L'historien ne détruit pas la mémoire, il la prive de son évidence.",
    question: "Quel rapport l'auteur établit-il entre histoire et mémoire ?",
    options: [
      "L'histoire remplace progressivement la mémoire collective.",
      "L'histoire retire à la mémoire son caractère d'évidence.",
      "L'histoire confirme le récit que le groupe porte sur lui-même.",
      "L'histoire et la mémoire relèvent de disciplines indépendantes.",
    ],
    correctIndex: 1,
    explanation: "The final sentence states the historian does not destroy memory but strips it of its self-evidence.",
  },

  // ── C1–C2 (Q30–39) ─────────────────────────────────────────────
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "La notion de « charge mentale » a connu une diffusion rapide, au risque de perdre sa précision. Elle ne désigne pas la fatigue accumulée, ni la somme des tâches accomplies, mais le travail invisible d'anticipation et de coordination qui les précède : penser à ce qui doit être fait, à quel moment, par qui. Ce travail échappe aux mesures classiques du temps domestique, précisément parce qu'il ne se traduit pas en gestes observables.",
    question: "Pourquoi la charge mentale échappe-t-elle aux mesures habituelles ?",
    options: [
      "Parce qu'elle varie fortement d'un foyer à l'autre.",
      "Parce qu'elle ne se manifeste pas par des actions observables.",
      "Parce que les personnes concernées la sous-estiment systématiquement.",
      "Parce qu'elle se confond avec la fatigue professionnelle.",
    ],
    correctIndex: 1,
    explanation: "It escapes measurement because it produces no observable gestures, being anticipation and coordination.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Analyse politique",
    passage: "L'exigence de transparence, longtemps brandie comme un remède aux dérives du pouvoir, produit des effets ambigus. Rendre publics les délibérations et les votes intermédiaires ne rend pas les acteurs plus vertueux : cela les rend plus prudents. Les négociations décisives migrent alors vers des espaces informels où aucune trace ne subsiste. La transparence ne supprime pas l'ombre, elle la déplace.",
    question: "Quel effet pervers de la transparence est décrit ?",
    options: [
      "Elle décourage les citoyens de suivre la vie politique.",
      "Elle rend les délibérations publiques excessivement longues.",
      "Elle repousse les vraies négociations vers des lieux sans trace.",
      "Elle expose les responsables à des pressions médiatiques.",
    ],
    correctIndex: 2,
    explanation: "Decisive negotiation migrates to informal spaces leaving no record — transparency displaces the shadow.",
  },
  {
    id: 32,
    level: "C1",
    passageType: "Extrait littéraire",
    passage: "Il parlait la langue du pays avec une correction qui le trahissait. Trop de subjonctifs, trop peu d'hésitations, une syntaxe polie comme un galet. Les natifs, eux, malmenaient leur langue avec l'assurance de ceux qui la possèdent. Lui la portait comme un vêtement du dimanche, impeccable et jamais tout à fait à sa taille.",
    question: "Qu'est-ce qui trahit l'origine étrangère du personnage ?",
    options: [
      "Son accent, perceptible dès les premiers mots.",
      "Sa lenteur à trouver le mot exact.",
      "La perfection excessive de sa langue.",
      "Son refus d'employer les expressions familières.",
    ],
    correctIndex: 2,
    explanation: "It is the over-correctness — too many subjunctives, too few hesitations — that gives him away.",
  },
  {
    id: 33,
    level: "C1",
    passageType: "Article académique",
    passage: "Les politiques dites fondées sur les données présupposent que la mesure précède la décision. Or l'inverse est fréquent : on décide ce qu'il vaut la peine de compter, et ce choix oriente déjà la conclusion. Comptabiliser les infractions plutôt que les conflits résolus, les places créées plutôt que les besoins couverts, ce n'est pas mesurer la réalité, c'est en privilégier une version.",
    question: "Quelle critique l'auteur adresse-t-il aux politiques fondées sur les données ?",
    options: [
      "Les données mobilisées sont souvent incomplètes ou périmées.",
      "Le choix de ce que l'on mesure oriente déjà la conclusion.",
      "Les décideurs manquent de compétences statistiques suffisantes.",
      "La collecte de données coûte plus cher qu'elle ne rapporte.",
    ],
    correctIndex: 1,
    explanation: "Deciding what is worth counting already privileges one version of reality.",
  },
  {
    id: 34,
    level: "C1",
    passageType: "Essai",
    passage: "L'hospitalité, dans son acception ancienne, comportait une part de risque assumé : accueillir sans savoir qui l'on accueille. Les dispositifs contemporains d'accueil inversent cette logique. Ils exigent d'abord l'identification, la vérification, la preuve de la vulnérabilité. L'étranger doit démontrer qu'il mérite l'hospitalité avant d'y accéder, ce qui la transforme en récompense et lui retire son sens premier.",
    question: "En quoi les dispositifs contemporains dénaturent-ils l'hospitalité ?",
    options: [
      "Ils la réservent aux personnes déjà installées dans le pays.",
      "Ils en font une récompense conditionnée à des preuves préalables.",
      "Ils la confient à des organismes privés plutôt qu'à l'État.",
      "Ils la limitent à une durée trop brève pour être utile.",
    ],
    correctIndex: 1,
    explanation: "Requiring proof of merit beforehand turns hospitality into a reward, stripping its original sense.",
  },
  {
    id: 35,
    level: "C1",
    passageType: "Article académique",
    passage: "L'effet dit de « surjustification » désigne un paradoxe robuste : récompenser une activité pratiquée par plaisir tend à réduire l'engagement qu'on lui portait. Une fois la rétribution instaurée, l'individu réinterprète sa propre motivation à la lumière de celle-ci et conclut qu'il agissait pour la récompense. Le retrait ultérieur de celle-ci laisse une motivation plus faible qu'avant son introduction.",
    question: "Quel mécanisme explique la baisse de motivation décrite ?",
    options: [
      "La récompense proposée est jugée insuffisante par l'individu.",
      "L'individu réinterprète après coup les raisons de son propre engagement.",
      "L'activité perd de son intérêt à mesure qu'elle devient routinière.",
      "La comparaison avec les autres participants décourage l'individu.",
    ],
    correctIndex: 1,
    explanation: "The person reinterprets their own motivation in light of the reward and concludes they acted for it.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Extrait philosophique",
    passage: "Dire qu'une promesse engage suppose une continuité du sujet qui n'a rien d'évident. Celui qui promet et celui qui tiendra ne coïncident pas : entre eux s'est écoulé un temps qui les rend partiellement étrangers l'un à l'autre. La promesse est donc moins la constatation d'une identité persistante que l'acte par lequel elle est instituée. On ne tient pas parole parce qu'on demeure le même ; on demeure le même parce qu'on tient parole.",
    question: "Quelle thèse l'auteur défend-il sur la promesse ?",
    options: [
      "Elle suppose une identité personnelle stable et antérieure à l'engagement.",
      "Elle institue la continuité du sujet plutôt qu'elle ne la constate.",
      "Elle perd sa valeur dès lors que les circonstances ont changé.",
      "Elle repose avant tout sur la confiance accordée par autrui.",
    ],
    correctIndex: 1,
    explanation: "The closing inversion states identity results from keeping one's word, not the reverse.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "La sociologie des professions a montré que la fermeture d'un marché du travail ne repose pas seulement sur la compétence, mais sur la capacité d'un groupe à faire reconnaître sa compétence comme irréductible. Les frontières professionnelles sont ainsi le produit d'un travail politique continu : elles se défendent devant les législateurs autant qu'elles se démontrent devant les usagers.",
    question: "Comment se constituent les frontières professionnelles selon ce texte ?",
    options: [
      "Par la seule accumulation de savoirs techniques spécialisés.",
      "Par un travail politique de reconnaissance autant que par la compétence.",
      "Par la sélection opérée lors de la formation initiale.",
      "Par la demande exprimée par les usagers des services concernés.",
    ],
    correctIndex: 1,
    explanation: "Boundaries are the product of continuous political work, defended before legislators as much as demonstrated to users.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Essai critique",
    passage: "On reproche aux algorithmes de recommandation d'enfermer l'usager dans ses préférences. Le reproche est fondé mais incomplet. Ces systèmes ne se contentent pas de refléter un goût préexistant : en le mesurant, ils le stabilisent. Un intérêt passager, capté au mauvais moment, devient une catégorie qui déterminera des années de propositions. La prophétie n'est pas seulement auto-réalisatrice, elle est rétroactive.",
    question: "Quelle nuance l'auteur ajoute-t-il à la critique habituelle ?",
    options: [
      "Les algorithmes reflètent fidèlement des goûts qui préexistent à leur mesure.",
      "En mesurant les préférences, les algorithmes contribuent à les figer.",
      "Les usagers conservent la possibilité de corriger leurs recommandations.",
      "Les catégories utilisées sont trop grossières pour cerner les goûts.",
    ],
    correctIndex: 1,
    explanation: "Measuring a preference stabilises it: a passing interest hardens into a lasting category.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article spécialisé",
    passage: "L'évaluation des politiques linguistiques bute sur un obstacle méthodologique tenace. Les indicateurs disponibles — nombre de locuteurs déclarés, résultats aux tests standardisés — mesurent des états, non des trajectoires. Or une politique peut ralentir un déclin sans l'inverser, et sera jugée inefficace faute de contrefactuel observable. L'absence d'un scénario de comparaison n'est pas une lacune passagère : elle est constitutive de l'objet étudié.",
    question: "Pourquoi une politique linguistique efficace peut-elle être jugée inefficace ?",
    options: [
      "Parce que les locuteurs déclarent mal leur véritable niveau de langue.",
      "Parce qu'on ne peut pas observer ce qui se serait produit sans elle.",
      "Parce que les tests standardisés sont révisés trop fréquemment.",
      "Parce que ses effets n'apparaissent qu'après plusieurs générations.",
    ],
    correctIndex: 1,
    explanation: "Without an observable counterfactual, slowing a decline cannot be distinguished from failure.",
  },
];
