import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Master Band A — A1–A2 essential everyday vocabulary. Curated for NCLC 7. */
export const MASTER_A: LemmaRow[] = [
  ["Subtotal", "le sous-total", "Vérifiez le sous-total avant d'ajouter les taxes."],
  ["Equal to", "égal à", "Le prix affiché est égal à votre paiement."],
  ["Zero balance", "le solde à zéro", "Votre carte de crédit a un solde à zéro."],
  ["Digital display", "l'écran numérique", "Regardez l'écran numérique pour connaître votre tour."],
  ["Third in line", "le troisième dans la file", "Vous êtes le troisième dans la file d'attente."],
  ["The previous day", "le jour précédent", "J'ai confirmé mon rendez-vous le jour précédent."],
  ["Always", "en tout temps", "Gardez vos bagages avec vous en tout temps."],
  ["Sometimes", "quelquefois", "Je prends quelquefois un taxi pour rentrer."],
  ["Seldom", "très rarement", "Il neige très rarement au mois de mai ici."],
  ["Often", "fréquemment", "Le métro s'arrête fréquemment à cette station."],
  ["Daily rate", "le tarif à la journée", "Le tarif à la journée est très abordable."],
  ["Hourly wage", "le taux horaire", "Quel est le taux horaire de ce travail ?"],
  ["Fixed price", "le prix fixe", "Ce menu a un prix fixe pour tout le monde."],
  ["Maiden name", "le nom de jeune fille", "Écrivez votre nom de jeune fille si nécessaire."],
  ["Place of birth", "le lieu de naissance", "Indiquez votre lieu de naissance sur le document."],
  ["Employer name", "le nom de l'employeur", "Le nom de l'employeur est requis pour ce formulaire."],
  ["Reference number", "le numéro de référence", "Conservez le numéro de référence de la transaction."],
  ["Blank line", "la ligne vide", "Ne laissez aucune ligne vide sur ce papier."],
  ["Ruler", "la règle", "Utilisez une règle pour tracer une ligne droite."],
  ["Stapler", "l'agrafeuse", "L'agrafeuse est sur le bureau de la réceptionniste."],
  ["Paper clip", "le trombone", "Attachez ces deux feuilles avec un trombone."],
  ["File folder", "le classeur", "Rangez ces dossiers importants dans le classeur."],
  ["Envelope", "l'enveloppe de retour", "Utilisez l'enveloppe de retour pour envoyer votre réponse."],
  ["Witness", "le témoin", "Un témoin doit signer le contrat avec vous."],
  ["Dependent child", "l'enfant à charge", "Un enfant à charge voyage gratuitement à cet âge."],
  ["Temporary address", "l'adresse temporaire", "Veuillez fournir votre adresse temporaire au Canada."],
  ["Tax slip", "le relevé d'impôt", "Vous recevrez votre relevé d'impôt par la poste."],
  ["Official stamp", "le timbre officiel", "Le timbre officiel prouve que le document est authentique."],
  ["Legible writing", "l'écriture lisible", "Une écriture lisible aide à traiter votre dossier plus vite."],
  ["Block capitals", "les lettres moulées", "Remplissez ce formulaire en lettres moulées seulement."],
  ["Date of issue", "la date de délivrance", "La date de délivrance de votre passeport est importante."],
  ["Place of issue", "le lieu de délivrance", "Vérifiez le lieu de délivrance sur votre carte d'identité."],
  ["Supporting document", "le document justificatif", "Apportez un document justificatif avec votre demande."],
  ["Office stamp", "le sceau du bureau", "Le sceau du bureau confirme la réception de l'envoi."],
  ["Registration desk", "le bureau d'inscription", "Le bureau d'inscription se trouve au premier étage."],
  ["Queue number", "le numéro d'attente", "Prenez un numéro d'attente à la machine d'accueil."],
  ["FAQ sheet", "la foire aux questions", "Lisez la foire aux questions pour plus d'informations."],
  ["Office closure", "la fermeture des bureaux", "La fermeture des bureaux aura lieu à dix-sept heures."],
  ["Security check", "le contrôle de sécurité", "Le contrôle de sécurité prend cinq minutes à l'aéroport."],
  ["Prohibited items", "les articles interdits", "Les ciseaux font partie des articles interdits en cabine."],
  ["Duplicate copy", "le duplicata", "Demandez un duplicata si vous perdez l'original."],
  ["Privacy notice", "l'avis de confidentialité", "Lisez l'avis de confidentialité avant de cliquer sur accepter."],
  ["Consent checkbox", "la case de consentement", "Cochez la case de consentement au bas de la page."],
  ["Minor applicant", "le demandeur mineur", "Le demandeur mineur doit avoir la signature d'un parent."],
  ["Legal guardian", "le représentant légal", "Le représentant légal de l'enfant doit être présent."],
  ["Processing time", "le temps d'attente", "Le temps d'attente estimé est d'environ trente minutes."],
  ["Status update", "la mise à jour du dossier", "Vous recevrez une mise à jour du dossier par courriel."],
  ["Missing page", "la page manquante", "Il y a une page manquante dans ce document."],
  ["Office hours sign", "l'affiche des heures", "L'affiche des heures se trouve sur la porte vitrée."],
  ["Pickup hours", "les heures de cueillette", "Les heures de cueillette sont de midi à seize heures."],
  ["Technical support", "le soutien technique", "Appelez le soutien technique si la machine ne fonctionne pas."],
  ["Help desk hours", "les heures du service", "Les heures du service sont de huit à vingt heures."],
  ["Preferred contact method", "le moyen de contact", "Quel est votre moyen de contact préféré ?"],
  ["Evening phone", "le numéro de soir", "Donnez un numéro de soir pour vous joindre."],
  ["Relationship field", "le lien de parenté", "Indiquez le lien de parenté avec votre contact d'urgence."],
  ["Gender marker", "le genre", "Cochez le genre qui apparaît sur votre passeport."],
  ["Preferred name", "le prénom usuel", "Vous pouvez indiquer votre prénom usuel sur ce formulaire."],
  ["Middle name", "le deuxième prénom", "Votre deuxième prénom n'est pas obligatoire ici."],
  ["Care facility", "le centre de soins", "L'adresse correspond à un centre de soins de longue durée."],
  ["General delivery", "la poste restante", "Faites envoyer votre colis à la poste restante."],
  ["Bargain price", "le bon prix", "C'est un bon prix pour ce type de vêtement."],
  ["Clearance event", "la liquidation", "C'est la vente de liquidation avant la fermeture des Fêtes."],
  ["Price markdown", "la réduction", "Cette chemise a une réduction de vingt pour cent."],
  ["Wholesale price", "le prix de gros", "Acheter au prix de gros permet de faire des économies."],
  ["Paper sack", "le sac en papier", "Voulez-vous un sac en papier pour votre achat ?"],
  ["Shelf price", "le prix en rayon", "Le prix en rayon est différent du prix à la caisse."],
  ["Mannequin", "le mannequin", "La robe sur le mannequin n'est plus en stock."],
  ["Clothes hanger", "le cintre", "Pouvez-vous me donner un cintre pour mon manteau ?"],
  ["Synthetic material", "le tissu synthétique", "Ce tissu synthétique sèche très rapidement après le lavage."],
  ["Dry clean only", "le nettoyage à sec", "Ce complet nécessite un nettoyage à sec au pressing."],
  ["Extra small size", "la très petite taille", "Il ne reste que la très petite taille pour ce modèle."],
  ["Extra large size", "la très grande taille", "Cherchez-vous une chemise de très grande taille ?"],
  ["Sleeve length", "la longueur des manches", "La longueur des manches de cette veste est parfaite."],
  ["Heel height", "la hauteur des talons", "La hauteur des talons de ces chaussures est de cinq centimètres."],
  ["Winter gloves", "les mitaines", "Les enfants préfèrent porter des mitaines en hiver."],
  ["Socks pack", "le paquet de bas", "J'ai acheté un paquet de bas pour l'hiver."],
  ["Leather wallet", "le portefeuille", "J'ai oublié mon portefeuille à la maison ce matin."],
  ["Handbag", "le sac à main", "Elle a déposé son sac à main sur la chaise."],
  ["Luggage tag", "l'étiquette de bagage", "Écrivez votre nom sur l'étiquette de bagage de la valise."],
  ["Travel pillow", "le coussin de voyage", "Un coussin de voyage est utile pour les longs vols."],
  ["Self-service scale", "la balance", "Pesez vos fruits sur la balance dans l'allée."],
  ["Bakery oven", "le four de la boulangerie", "Les pains chauds sortent du four de la boulangerie."],
  ["Fish counter", "la poissonnerie", "Allez à la poissonnerie pour acheter du saumon frais."],
  ["Gluten-free aisle", "le rayon sans gluten", "Le pain sans gluten est dans le rayon sans gluten."],
  ["Extension cord", "la rallonge", "J'ai besoin d'une rallonge pour brancher mon ordinateur portable."],
  ["Gift wrapping", "l'emballage-cadeau", "Le service d'emballage-cadeau est disponible près de l'entrée."],
  ["Extended warranty", "la garantie prolongée", "Voulez-vous acheter la garantie prolongée pour cet appareil ?"],
  ["Store credit note", "la note de crédit", "Le magasin offre une note de crédit pour les retours."],
  ["Price comparison", "la comparaison des prix", "Faites une comparaison des prix avant de faire un gros achat."],
  ["Customer review", "l'avis des clients", "L'avis des clients sur ce produit est très positif."],
  ["Online pickup", "la cueillette en magasin", "Faites vos achats en ligne et choisissez la cueillette en magasin."],
  ["Home delivery slot", "l'heure de livraison", "Choisissez une heure de livraison entre dix et quatorze heures."],
  ["Minimum order", "la commande minimale", "La commande minimale pour la livraison gratuite est de cinquante dollars."],
  ["Restock date", "la date de réapprovisionnement", "La date de réapprovisionnement de ce produit est inconnue."],
  ["Opening day discount", "le rabais d'ouverture", "Profitez du rabais d'ouverture du nouveau supermarché."],
  ["Member discount", "le rabais pour les membres", "Il y a un rabais pour les membres de la coopérative."],
  ["Senior discount", "le rabais pour les aînés", "Le rabais pour les aînés s'applique tous les mardis."],
  ["Student discount card", "le rabais étudiant", "Montrez votre carte pour obtenir le rabais étudiant de dix pour cent."],
  ["Unit quantity", "la quantité", "Sélectionnez la quantité désirée avant d'ajouter au panier."],
  ["Barcode scanner beep", "le bip de la caisse", "Attendez le bip de la caisse avant de passer le prochain article."],
  ["Shopping cart wheel", "la roulette du panier", "La roulette du panier d'épicerie est brisée."],
  ["Basket handle", "la poignée du panier", "Prenez le panier rouge par la poignée du panier."],
  ["Changing room hook", "le crochet de la cabine", "Accrochez vos vêtements sur le crochet de la cabine d'essayage."],
  ["Scratch on item", "l'égratignure", "Il y a une petite égratignure sur le meuble."],
  ["Receipt lookup", "la recherche de facture", "La recherche de facture se fait avec votre numéro de téléphone."],
  ["Contactless payment", "le paiement sans contact", "Le paiement sans contact est plus rapide à la caisse."],
  ["Coin slot", "la fente à monnaie", "Insérez deux dollars dans la fente à monnaie de la machine."],
  ["Best before", "la date de péremption", "Vérifiez la date de péremption sur le contenant de lait."],
  ["Country of manufacture", "le pays d'origine", "Le pays d'origine de ces fruits est le Mexique."],
  ["Closed checkout", "la caisse fermée", "Cette caisse est fermée, veuillez aller à la caisse suivante."],
  ["Price check desk", "le comptoir du service à la clientèle", "Allez au comptoir du service à la clientèle pour vérifier le prix."],
  ["Store manager", "le gérant du magasin", "Le gérant du magasin peut vous aider avec ce problème."],
  ["Mystery shopper", "le client mystère", "Le client mystère évalue le service de notre établissement."],
  ["Rewards card scan", "la carte de fidélité", "Scannez votre carte de fidélité pour accumuler des points."],
  ["Rainy day sale", "la vente pour jour de pluie", "Profitez de la vente pour jour de pluie pour acheter des parapluies."],
  ["Flash sale", "la vente éclair", "La vente éclair se termine ce soir à minuit."],
  ["Closing sale", "la vente de fermeture", "Les prix sont très bas lors de cette vente de fermeture."],
  ["Opening gift", "le cadeau de bienvenue", "Recevez un cadeau de bienvenue lors de votre première visite."],
  ["Sample tasting", "la dégustation", "Participez à la dégustation de nos nouveaux fromages locaux."],
  ["Product demo", "la démonstration", "Regardez la démonstration de cet appareil électroménager."],
  ["Aisle marker", "le panneau d'allée", "Le panneau d'allée indique où trouver les conserves."],
  ["Click and collect", "le service au volant", "Ramassez votre commande d'épicerie au service au volant."],
  ["Order number display", "l'écran des commandes", "Votre numéro apparaîtra sur l'écran des commandes quand ce sera prêt."],
  ["Pickup counter", "le comptoir des commandes", "Présentez-vous au comptoir des commandes pour récupérer vos achats."],
  ["Cold storage bag", "le sac isotherme", "Utilisez un sac isotherme pour garder vos produits congelés froids."],
  ["Reusable cup discount", "le rabais pour tasse réutilisable", "Obtenez un rabais pour tasse réutilisable en apportant votre propre tasse."],
  ["Bottle deposit", "la consigne pour les bouteilles", "La consigne pour les bouteilles vous sera remboursée plus tard."],
  ["Recycling deposit", "le dépôt pour le recyclage", "Le dépôt pour le recyclage aide à protéger l'environnement."],
  ["Shopping trolley token", "le jeton de chariot", "Il faut un jeton de chariot pour prendre un chariot au supermarché."],
  ["Escalator to mall", "l'escalier roulant", "Prenez l'escalier roulant pour monter au deuxième étage du centre commercial."],
  ["Mall directory", "le plan du centre d'achats", "Consultez le plan du centre d'achats pour trouver les toilettes."],
  ["Food court table", "la foire alimentaire", "Nous allons manger à la foire alimentaire ce midi."],
  ["Restroom key", "la clé des toilettes", "Demandez la clé des toilettes au comptoir du café."],
  ["Hand dryer", "le sèche-mains", "Le sèche-mains de la toilette des hommes est en panne."],
  ["Paper towel dispenser", "la distributrice de papier", "Tirez sur la distributrice de papier pour vous essuyer les mains."],
  ["Early bird special", "le rabais lève-tôt", "Profitez du rabais lève-tôt si vous arrivez avant huit heures."],
  ["Late night shopping", "les achats tardifs", "Les achats tardifs sont possibles le jeudi et le vendredi soir."],
  ["Price guarantee", "la garantie du meilleur prix", "Nous offrons la garantie du meilleur prix sur tous nos téléviseurs."],
  ["Ad match", "l'égalisation des prix", "Demandez l'égalisation des prix si vous trouvez moins cher ailleurs."],
  ["Rain check (store)", "le bon différé", "Demandez un bon différé pour acheter ce produit en solde plus tard."],
  ["Special order", "la commande spéciale", "Nous pouvons faire une commande spéciale pour ce modèle particulier."],
  ["Catalog order", "la commande par catalogue", "La commande par catalogue prend environ deux semaines de livraison."],
  ["Tailor alteration", "les retouches", "Les retouches sur ce pantalon coûteront vingt dollars supplémentaires."],
  ["Hemming pants", "le bord de pantalon", "Il faut faire le bord de pantalon pour qu'il soit à la bonne longueur."],
  ["Shoe polish", "le cirage à chaussures", "Le cirage à chaussures noir est dans le rayon des souliers."],
  ["Shoe size chart", "le guide des pointures", "Consultez le guide des pointures avant de commander en ligne."],
  ["Ring size", "la taille de la bague", "Connaissez-vous la taille de la bague que vous désirez acheter ?"],
  ["Jewelry counter", "le comptoir des bijoux", "Le comptoir des bijoux se trouve près de l'entrée principale."],
  ["Perfume tester", "le testeur de parfum", "Utilisez le testeur de parfum pour découvrir cette nouvelle fragrance."],
  ["Makeup remover", "le démaquillant", "Le démaquillant pour les yeux est en vente cette semaine."],
  ["Tent sale", "la vente de tentes", "La grande vente de tentes se déroule dans le stationnement."],
  ["Fishing license", "le permis de pêche", "Il faut un permis de pêche pour pêcher sur ce lac."],
  ["Stroller parking", "le stationnement pour poussettes", "Veuillez utiliser le stationnement pour poussettes près de l'accueil."],
  ["Greeting card rack", "le présentoir à cartes de souhaits", "Le présentoir à cartes de souhaits est près de la caisse."],
  ["Wrapping paper roll", "le rouleau de papier d'emballage", "Achetez un rouleau de papier d'emballage pour vos cadeaux de Noël."],
  ["Store playlist", "la musique du magasin", "La musique du magasin est un peu trop forte aujourd'hui."],
  ["Shoplifting alarm", "l'alarme antivol", "L'alarme antivol a sonné quand il est sorti du magasin."],
  ["Wheelchair cart", "le chariot pour fauteuil roulant", "Ce magasin dispose d'un chariot pour fauteuil roulant pour ses clients."],
  ["Motorized scooter", "le triporteur", "Le magasin prête un triporteur pour les personnes à mobilité réduite."],
  ["Shopping companion", "l'accompagnateur pour les courses", "L'accompagnateur pour les courses aide la cliente à trouver ses articles."],
  ["Heavy item help", "l'aide pour objets lourds", "Demandez l'aide pour objets lourds si vous achetez un meuble."],
  ["Parking validation machine", "la machine à valider le stationnement", "La machine à valider le stationnement est près de la porte de sortie."],
  ["Receipt survey", "le sondage sur le reçu", "Participez au sondage sur le reçu pour courir la chance de gagner."],
  ["Charity donation box", "la boîte de dons", "Mettez votre petite monnaie dans la boîte de dons près de la caisse."],
  ["Unit conversion", "la conversion des unités", "Utilisez l'application pour la conversion des unités de mesure."],
  ["Metric label", "l'étiquette métrique", "Au Canada, l'étiquette métrique est obligatoire sur les emballages."],
  ["Imperial label", "l'étiquette impériale", "Certains vieux produits ont encore l'étiquette impériale en onces."],
  ["Multipack", "l'emballage multiple", "L'emballage multiple est plus économique pour les familles nombreuses."],
  ["Family pack", "le format familial", "Le format familial de céréales durera toute la semaine pour les enfants."],
  ["Economy size", "le format économique", "Achetez le format économique pour payer moins cher à long terme."],
  ["Travel size", "le format voyage", "Le format voyage du shampoing est idéal pour prendre l'avion."],
  ["Refill pack", "la recharge", "Achetez la recharge de savon pour les mains au lieu d'une nouvelle bouteille."],
  ["Generic brand", "la marque générique", "La marque générique de ce médicament est moins dispendieuse à la pharmacie."],
  ["Limited edition", "l'édition limitée", "Ce chandail est une édition limitée qui ne sera plus disponible bientôt."],
  ["Collector item", "l'article de collection", "Cette carte de baseball est un article de collection très recherché."],
  ["Handmade goods", "les produits artisanaux", "Le marché vend de nombreux produits artisanaux fabriqués dans la région."],
  ["Street vendor", "le vendeur de rue", "Le vendeur de rue offre des hot-dogs et des boissons fraîches."],
  ["Pawn shop", "le prêteur sur gages", "Le prêteur sur gages vend des guitares usagées à bon prix."],
  ["Auction house", "la salle des ventes", "La salle des ventes propose des meubles anciens de grande valeur."],
  ["Estate sale", "la vente de succession", "J'ai trouvé une belle lampe antique à la vente de succession."],
  ["Garage sale", "la vente de débarras", "Je vais chercher de vieux livres à la vente de débarras de mon voisin."],
  ["Yard sale sign", "l'affiche de la vente-débarras", "L'affiche de la vente-débarras est collée sur le poteau de téléphone."],
  ["Bargain hunter", "le chasseur d'aubaines", "Ce chasseur d'aubaines arrive toujours très tôt au marché aux puces."],
  ["Impulse buy", "l'achat impulsif", "Cette barre de chocolat près de la caisse était un achat impulsif."],
  ["Shopping budget", "le budget de magasinage", "Il faut respecter son budget de magasinage pour ne pas s'endetter."],
  ["Price ceiling", "le prix plafond", "Le gouvernement a fixé un prix plafond pour ce médicament essentiel."],
  ["Duty charge", "les frais de douane", "Vous devrez payer les frais de douane pour recevoir ce colis de l'étranger."],
  ["Import fee", "les frais d'importation", "Les frais d'importation s'ajoutent au prix de votre commande internationale."],
  ["Travel money card", "la carte prépayée pour le voyage", "Utilisez une carte prépayée pour le voyage pour plus de sécurité."],
  ["Foreign coins", "la monnaie étrangère", "Le bureau de change n'accepte pas la monnaie étrangère, seulement les billets."],
  ["Souvenir magnet", "l'aimant souvenir", "J'achète toujours un aimant souvenir pour le réfrigérateur de ma mère."],
  ["Postcard stamp", "le timbre pour carte postale", "Combien coûte un timbre pour carte postale pour envoyer en France ?"],
  ["Map souvenir", "la carte souvenir", "Cette carte souvenir montre les principales attractions touristiques de la ville."],
  ["Weekly transit pass", "le laissez-passer hebdomadaire", "Le laissez-passer hebdomadaire est très pratique pour les touristes en ville."],
  ["Turnstile gate", "le tourniquet", "Passez votre carte de métro sur le lecteur du tourniquet pour entrer."],
  ["Transit fine", "l'amende", "Vous risquez une grosse amende si vous voyagez sans billet valide."],
  ["Park and ride lot", "le stationnement incitatif", "Garez-vous au stationnement incitatif et prenez l'autobus pour aller au centre-ville."],
  ["Bike share station", "la station de vélos en libre-service", "Prenez un vélo à la station de vélos en libre-service près du parc."],
  ["Scooter rental", "la location de trottinettes", "La location de trottinettes électriques est disponible au centre-ville."],
  ["Flat taxi fare", "le tarif fixe", "Il y a un tarif fixe pour aller de l'aéroport au centre-ville."],
  ["Night bus route", "le circuit d'autobus de nuit", "Le circuit d'autobus de nuit circule entre une heure et cinq heures du matin."],
  ["Express route", "le circuit express", "Le circuit express fait moins d'arrêts et arrive plus rapidement à destination."],
  ["Request stop", "l'arrêt sur demande", "La nuit, certaines lignes offrent l'arrêt sur demande entre deux arrêts réguliers."],
  ["Pull the cord", "tirer la corde", "N'oubliez pas de tirer la corde pour signaler votre arrêt au chauffeur."],
  ["Red light camera", "la caméra au feu rouge", "La caméra au feu rouge prend en photo les voitures qui ne s'arrêtent pas."],
  ["Jaywalking ticket", "la contravention pour traversée illégale", "Il a reçu une contravention pour traversée illégale en dehors du passage piéton."],
  ["Bicycle helmet law", "la loi sur le port du casque", "La loi sur le port du casque est stricte pour les enfants à vélo."],
  ["Mileage limit", "la limite de kilométrage", "Vérifiez la limite de kilométrage incluse dans votre contrat de location d'auto."],
  ["Windshield wipers", "les essuie-glaces", "Les essuie-glaces de ma voiture sont vieux et ne nettoient plus bien."],
  ["Empty gas tank", "le réservoir vide", "Il faut trouver une station-service, nous roulons sur le réservoir vide."],
  ["Diesel pump", "la pompe de diesel", "Utilisez la pompe de diesel pour ce camion, ne mettez pas d'essence régulière."],
  ["Flat tire", "le pneu crevé", "Nous devons nous arrêter sur l'accotement à cause d'un pneu crevé."],
  ["Spare tire", "le pneu de secours", "Le pneu de secours se trouve sous le plancher du coffre arrière."],
  ["Roadside assistance", "l'assistance routière", "J'appelle l'assistance routière pour venir remorquer ma voiture en panne."],
  ["Highway rest stop", "la halte routière", "Nous ferons une pause pour manger à la prochaine halte routière."],
  ["Speed camera", "le radar photo", "Faites attention à votre vitesse, il y a un radar photo dans cette zone."],
  ["Pedestrian zone", "la zone piétonnière", "Cette rue du Vieux-Montréal est une zone piétonnière fermée aux voitures l'été."],
  ["Bike path sign", "le panneau de piste cyclable", "Suivez le panneau de piste cyclable pour vous rendre au bord du canal."],
  ["Ferry schedule board", "le tableau de l'horaire du traversier", "Consultez le tableau de l'horaire du traversier avant d'acheter votre billet de bateau."],
  ["Harbor pier", "le quai", "Le traversier arrivera au quai dans moins de quinze minutes."],
  ["Cruise ship terminal", "le terminal des navires de croisière", "Le bateau de croisière part du terminal des navires de croisière de Québec."],
  ["Flight gate change", "le changement de porte d'embarquement", "Il y a un changement de porte d'embarquement pour le vol vers Paris."],
  ["Boarding group", "le groupe d'embarquement", "Les passagers du groupe d'embarquement numéro trois peuvent se présenter à la porte."],
  ["Overhead bin", "le compartiment à bagages", "Rangez votre petite valise dans le compartiment à bagages au-dessus de votre siège."],
  ["Seat assignment", "l'assignation des sièges", "L'assignation des sièges se fait automatiquement lors de l'achat de votre billet d'avion."],
  ["Train platform screen", "l'écran sur le quai", "Regardez l'écran sur le quai pour savoir quand le prochain métro arrivera."],
  ["Missed connection", "la correspondance manquée", "Le vol était en retard et nous avons eu une correspondance manquée à Toronto."],
  ["Busy tone", "la tonalité de ligne occupée", "Je n'arrive pas à le joindre, j'entends toujours la tonalité de ligne occupée."],
];
