import type { LemmaRow } from "./tcf-exam-lexique-batch2";

/** Batch 6 — everyday + exam-theme lexique (forms, community, opinion language). */
export const BATCH6_A: LemmaRow[] = [
  ["Morning shift", "le quart de jour", "Le quart de jour commence à six heures."],
  ["Evening shift", "le quart de soir", "Le quart de soir se termine à vingt-deux heures."],
  ["Night shift", "le quart de nuit", "Le quart de nuit paie un supplément."],
  ["Break time", "la pause", "La pause dure quinze minutes à dix heures."],
  ["Lunch break", "la pause-dîner", "La pause-dîner est de une heure."],
  ["Time slot", "le créneau horaire", "Choisissez un créneau horaire sur le site."],
  ["Office hours", "les heures de bureau", "Les heures de bureau sont de neuf à seize heures."],
  ["Extended hours", "les heures prolongées", "Des heures prolongées sont offertes le samedi."],
  ["Holiday schedule", "l'horaire des fêtes", "L'horaire des fêtes est affiché à l'entrée."],
  ["Weekly schedule", "l'horaire hebdomadaire", "Consultez l'horaire hebdomadaire des cours."],
  ["Monthly calendar", "le calendrier mensuel", "Le calendrier mensuel est envoyé par courriel."],
  ["To postpone", "reporter", "Nous devons reporter la réunion à vendredi."],
  ["To reschedule", "fixer un nouveau rendez-vous", "Appelez pour fixer un nouveau rendez-vous."],
  ["To confirm", "confirmer", "Merci de confirmer votre présence avant midi."],
  ["To cancel", "annuler", "Vous pouvez annuler sans frais avant vingt-quatre heures."],
  ["No-show", "l'absence sans préavis", "Une absence sans préavis peut entraîner des frais."],
  ["Walk-in hours", "les heures sans rendez-vous", "Les heures sans rendez-vous sont le mercredi après-midi."],
  ["Service window", "la plage de service", "La plage de service se termine à seize heures trente."],
  ["Peak period", "la période de pointe", "Évitez la période de pointe entre seize et dix-huit heures."],
  ["Off-peak", "heures creuses", "Les tarifs heures creuses sont moins élevés."],
  ["Application form", "le formulaire de demande", "Remplissez le formulaire de demande en ligne."],
  ["Consent form", "le formulaire de consentement", "Signez le formulaire de consentement pour votre enfant."],
  ["Checkbox", "la case à cocher", "Cochez la case à cocher si vous acceptez."],
  ["Mandatory field", "le champ obligatoire", "Tous les champs obligatoires doivent être remplis."],
  ["Attachment", "la pièce jointe", "Joignez la pièce jointe au courriel."],
  ["Printed copy", "la copie papier", "Une copie papier est exigée pour le dossier."],
  ["Original document", "le document original", "Présentez le document original au guichet."],
  ["Certified copy", "la copie certifiée conforme", "Une copie certifiée conforme est acceptée."],
  ["Stamp", "le cachet", "Le cachet officiel apparaît en bas de page."],
  ["Initials", "les initiales", "Mettez vos initiales sur chaque page."],
  ["Full name", "le nom complet", "Écrivez votre nom complet en lettres moulées."],
  ["Date of birth", "la date de naissance", "Indiquez votre date de naissance au format AAAA-MM-JJ."],
  ["Mailing address", "l'adresse postale", "Vérifiez que l'adresse postale est à jour."],
  ["Unit number", "le numéro d'appartement", "N'oubliez pas le numéro d'appartement dans l'adresse."],
  ["Postal code", "le code postal", "Le code postal facilite la livraison."],
  ["Province", "la province", "Sélectionnez votre province dans la liste."],
  ["Country of origin", "le pays d'origine", "Le pays d'origine figure sur le passeport."],
  ["Phone extension", "le poste téléphonique", "Composez le poste téléphonique trois-cent-quatre."],
  ["Mobile phone", "le téléphone cellulaire", "Laissez votre numéro de téléphone cellulaire."],
  ["Landline", "le téléphone fixe", "Le téléphone fixe reste utile pour les urgences."],
  ["Text message", "le texto", "Vous recevrez un texto de confirmation."],
  ["Voice message", "le message vocal", "Laissez un message vocal clair et bref."],
  ["Callback", "le rappel", "Demandez un rappel dans l'après-midi."],
  ["Hold music", "la musique d'attente", "Patientez pendant la musique d'attente."],
  ["Support hotline", "la ligne d'assistance", "La ligne d'assistance répond de huit à vingt heures."],
  ["Complaint line", "la ligne de plaintes", "La ligne de plaintes est gratuite."],
  ["Information desk", "le bureau d'information", "Le bureau d'information se trouve au hall principal."],
  ["Reception desk", "l'accueil", "Présentez-vous à l'accueil avec votre pièce d'identité."],
  ["Waiting number", "le numéro de file", "Votre numéro de file s'affiche sur l'écran."],
  ["Turn", "le tour", "C'est votre tour, approchez-vous du guichet."],
  ["Service counter", "le guichet", "Le guichet trois traite les remboursements."],
  ["ATM", "le guichet automatique", "Le guichet automatique est à l'extérieur."],
  ["Deposit", "le dépôt", "Le dépôt apparaît sur votre compte en deux jours."],
  ["Transfer (bank)", "le virement", "Le virement interac est instantané."],
  ["Bank branch", "la succursale bancaire", "La succursale bancaire ferme à dix-sept heures."],
  ["Account number", "le numéro de compte", "Ne communiquez jamais votre numéro de compte par texto."],
  ["Transaction fee", "les frais de transaction", "Des frais de transaction s'appliquent aux retraits."],
  ["Grocery cart", "le chariot d'épicerie", "Rangez le chariot d'épicerie près de la sortie."],
  ["Shopping basket", "le panier", "Le panier est limité à vingt articles."],
  ["Self-checkout", "la caisse libre-service", "La caisse libre-service accepte carte et argent comptant."],
  ["Barcode", "le code-barres", "Scannez le code-barres sous le laser."],
  ["Unit price", "le prix unitaire", "Le prix unitaire est indiqué sous le produit."],
  ["Bulk purchase", "l'achat en vrac", "L'achat en vrac réduit le gaspillage."],
  ["Loyalty card", "la carte de fidélité", "Présentez votre carte de fidélité à la caisse."],
  ["Coupon", "le coupon-rabais", "Ce coupon-rabais expire dimanche."],
  ["Flyer", "la circulaire", "La circulaire annonce les spéciaux de la semaine."],
  ["Aisle end", "la tête de gondole", "La promotion est à la tête de gondole."],
  ["Frozen foods", "les aliments surgelés", "Les aliments surgelés sont dans l'allée huit."],
  ["Dairy section", "le rayon laitier", "Le rayon laitier est près de l'entrée."],
  ["Bakery", "la boulangerie", "La boulangerie prépare le pain chaque matin."],
  ["Deli counter", "le comptoir de charcuterie", "Commandez au comptoir de charcuterie."],
  ["Produce section", "le rayon des fruits et légumes", "Le rayon des fruits et légumes est réapprovisionné tôt."],
  ["Checkout line", "la file à la caisse", "La file à la caisse avance lentement."],
  ["Bag fee", "les frais de sac", "Des frais de sac s'appliquent aux sacs en plastique."],
  ["Reusable bag", "le sac réutilisable", "Apportez un sac réutilisable pour éviter les frais."],
  ["Receipt total", "le total sur le reçu", "Vérifiez le total sur le reçu avant de partir."],
  ["Price match", "l'ajustement de prix", "Demandez l'ajustement de prix avec la preuve."],
  ["Clearance rack", "le rack de débarras", "Le rack de débarras offre des rabais importants."],
  ["Clothing rack", "le portant", "Cherchez votre taille sur le portant."],
  ["Shoe size", "la pointure", "Quelle pointure cherchez-vous?"],
  ["Fitting", "l'essayage", "L'essayage est gratuit en magasin."],
  ["Alterations desk", "le comptoir de retouches", "Déposez le pantalon au comptoir de retouches."],
  ["Gift wrap", "l'emballage-cadeau", "L'emballage-cadeau est offert en décembre."],
  ["Shopping mall", "le centre commercial", "Le centre commercial ouvre à dix heures."],
  ["Food court", "l'aire de restauration", "L'aire de restauration ferme à vingt et une heures."],
  ["Escalator", "l'escalier roulant", "Prenez l'escalier roulant jusqu'au deuxième étage."],
  ["Shopping hours", "les heures d'achat", "Les heures d'achat sont prolongées pendant les fêtes."],
  ["Store locator", "le localisateur de magasin", "Utilisez le localisateur de magasin sur le site."],
  ["Home delivery", "la livraison à domicile", "La livraison à domicile est gratuite au-dessus de cinquante dollars."],
  ["Pickup point", "le point de cueillette", "Le point de cueillette est derrière le magasin."],
  ["Bus route", "la ligne d'autobus", "La ligne d'autobus cinquante-deux passe toutes les quinze minutes."],
  ["Bus shelter", "l'abribus", "Attendez sous l'abribus par temps de pluie."],
  ["Fare card", "la carte de transport", "Rechargez votre carte de transport en ligne."],
  ["Single fare", "le titre de transport", "Achetez un titre de transport au distributeur."],
  ["Monthly pass", "la carte mensuelle", "La carte mensuelle coûte moins cher pour les trajets quotidiens."],
  ["Student fare", "le tarif étudiant", "Le tarif étudiant exige une carte valide."],
  ["Senior fare", "le tarif senior", "Le tarif senior s'applique aux soixante-cinq ans et plus."],
  ["Metro station", "la station de métro", "Descendez à la station de métro Berri-UQAM."],
  ["Train schedule", "l'horaire des trains", "L'horaire des trains change l'été."],
  ["Commuter train", "le train de banlieue", "Le train de banlieue est en retard ce matin."],
  ["Last departure", "le dernier départ", "Le dernier départ est à vingt-trois heures quinze."],
  ["First departure", "le premier départ", "Le premier départ part à cinq heures trente."],
  ["Real-time tracking", "le suivi en temps réel", "Consultez le suivi en temps réel sur l'application."],
  ["Service alert", "l'alerte de service", "Une alerte de service annonce un détour."],
  ["Step-free access", "l'accès sans escalier", "L'accès sans escalier est indiqué par un pictogramme bleu."],
  ["Bike rack (bus)", "le porte-vélo", "Le porte-vélo est à l'avant de l'autobus."],
  ["Taxi stand", "la station de taxi", "La station de taxi est devant la gare."],
  ["Ride-share", "le service de transport à la demande", "Le service de transport à la demande arrive en cinq minutes."],
  ["Carpool lane", "la voie de covoiturage", "La voie de covoiturage est réservée aux véhicules à deux passagers."],
  ["Parking meter", "le parcomètre", "Le parcomètre accepte carte et application."],
  ["Parking ticket", "la contravention de stationnement", "Une contravention de stationnement coûte cinquante dollars."],
  ["Tow zone", "la zone de remorquage", "Ne stationnez pas dans la zone de remorquage."],
  ["Handicap parking", "le stationnement handicapé", "Le stationnement handicapé exige un permis valide."],
  ["One-way street", "la rue à sens unique", "La rue à sens unique change de direction le matin."],
  ["No parking", "défense de stationner", "Le panneau indique défense de stationner."],
  ["Road work", "les travaux routiers", "Les travaux routiers ralentissent la circulation."],
  ["Lane closure", "la fermeture de voie", "Une fermeture de voie est prévue ce week-end."],
  ["Winter tires", "les pneus d'hiver", "Les pneus d'hiver sont obligatoires du premier décembre au quinze mars."],
  ["Snow brush", "la brosse à neige", "Gardez une brosse à neige dans le coffre."],
  ["Defrost", "dégivrer", "Dégivrez les vitres avant de partir."],
  ["Car wash", "le lavage auto", "Le lavage auto est fermé par grand froid."],
  ["Gas pump", "la pompe à essence", "La pompe à essence numéro quatre est hors service."],
  ["Oil change", "la vidange d'huile", "Prévoyez une vidange d'huile tous les cinq mille kilomètres."],
  ["Tire pressure", "la pression des pneus", "Vérifiez la pression des pneus en hiver."],
  ["Driver's manual", "le manuel du conducteur", "Le manuel du conducteur explique les panneaux routiers."],
  ["Road test", "l'examen de conduite", "L'examen de conduite dure environ quarante-cinq minutes."],
  ["License renewal", "le renouvellement du permis", "Le renouvellement du permis se fait en ligne."],
  ["Registration renewal", "le renouvellement d'immatriculation", "Le renouvellement d'immatriculation se fait en ligne chaque année."],
  ["License plate", "la plaque d'immatriculation", "Fixez la plaque d'immatriculation à l'arrière."],
  ["Speed bump", "le ralentisseur", "Ralentissez au ralentisseur devant l'école."],
  ["School zone", "la zone scolaire", "La limite est de trente km/h dans la zone scolaire."],
  ["Pedestrian crossing", "le passage pour piétons", "Arrêtez-vous au passage pour piétons."],
  ["Roundabout", "le rond-point", "Cédez le passage à gauche au rond-point."],
  ["Merge lane", "la voie d'insertion", "Utilisez la voie d'insertion pour rejoindre l'autoroute."],
  ["Rest area", "l'aire de repos", "Faites une pause à l'aire de repos dans trente kilomètres."],
  ["Toll road", "la route à péage", "La route à péage accepte le paiement sans contact."],
  ["Ferry terminal", "le terminal de traversier", "Le terminal de traversier ouvre à six heures."],
  ["Boarding time", "l'heure d'embarquement", "L'heure d'embarquement est indiquée sur votre billet."],
  ["Found items desk", "le bureau des objets trouvés", "Le bureau des objets trouvés est au comptoir central."],
  ["Luggage cart", "le chariot à bagages", "Déposez le chariot à bagages à la sortie."],
  ["Shuttle bus", "l'autobus navette", "L'autobus navette relie l'aéroport au métro."],
  ["Airport terminal", "le terminal aéroportuaire", "Le vol part du terminal aéroportuaire B."],
  ["Check-in kiosk", "la borne d'enregistrement", "Enregistrez-vous à la borne d'enregistrement."],
  ["Baggage claim", "la récupération des bagages", "Dirigez-vous vers la récupération des bagages."],
  ["Connecting flight", "la correspondance aérienne", "Votre correspondance aérienne part de la porte vingt."],
  ["Customs officer", "l'agent des douanes", "L'agent des douanes pose quelques questions."],
  ["Declaration card", "la carte de déclaration", "Remplissez la carte de déclaration avant l'atterrissage."],
  ["Duty-free shop", "la boutique hors taxes", "La boutique hors taxes ferme à vingt-deux heures."],
  ["Travel adapter", "l'adaptateur de voyage", "Apportez un adaptateur de voyage pour vos appareils."],
  ["Laundromat token", "le jeton de laverie", "Achetez des jetons de laverie à la réception."],
  ["Dryer", "la sécheuse", "La sécheuse met environ quarante minutes."],
  ["Washing machine", "la laveuse", "La laveuse est libre au troisième étage."],
  ["House key", "la clé de logement", "Ne perdez pas la clé de logement."],
  ["Mailbox key", "la clé de boîte aux lettres", "La clé de boîte aux lettres est dans l'enveloppe."],
  ["Garbage day", "le jour des ordures", "Le jour des ordures est le mardi matin."],
  ["Recycling day", "le jour du recyclage", "Sortez le bac le jour du recyclage."],
  ["Building notice", "l'avis aux résidents", "Un avis aux résidents annonce l'inspection des détecteurs."],
  ["Elevator outage", "la panne d'ascenseur", "La panne d'ascenseur devrait être réparée demain."],
  ["Water shutoff", "la coupure d'eau", "Une coupure d'eau est prévue jeudi de huit à midi."],
  ["Package locker", "le casier de colis", "Votre code ouvre le casier de colis au hall."],
  ["Delivery notice", "l'avis de livraison", "Un avis de livraison est collé à votre porte."],
  ["Signature on delivery", "la signature à la livraison", "Ce colis exige une signature à la livraison."],
];

export const BATCH6_B: LemmaRow[] = [
  ["Skilled trade", "le métier spécialisé", "Le métier spécialisé demande une formation pratique."],
  ["Job fair", "le salon de l'emploi", "Le salon de l'emploi aura lieu samedi au centre des congrès."],
  ["Networking event", "l'événement de réseautage", "L'événement de réseautage commence à dix-huit heures."],
  ["Professional reference", "la référence professionnelle", "Fournissez deux références professionnelles."],
  ["Skills assessment", "l'évaluation des compétences", "L'évaluation des compétences dure une demi-journée."],
  ["Performance review", "l'évaluation de rendement", "L'évaluation de rendement se tient en mars."],
  ["Promotion", "la promotion", "Elle a obtenu une promotion au poste de superviseure."],
  ["Resignation letter", "la lettre de démission", "Remettez votre lettre de démission à votre gestionnaire."],
  ["Job description", "la description de poste", "Lisez la description de poste avant de postuler."],
  ["Shift swap", "l'échange de quart", "Demandez un échange de quart avec un collègue."],
  ["Time sheet", "la feuille de temps", "Soumettez la feuille de temps chaque vendredi."],
  ["Payroll", "la paie", "La paie est déposée les jeudis."],
  ["Direct deposit", "le dépôt direct", "Inscrivez-vous au dépôt direct pour recevoir votre salaire."],
  ["Gross pay", "le salaire brut", "Le salaire brut apparaît avant les retenues."],
  ["Net pay", "le salaire net", "Le salaire net est versé sur votre compte."],
  ["Commission", "la commission", "La commission dépend des ventes du mois."],
  ["Tip income", "les pourboires", "Déclarez vos pourboires à la fin de l'année."],
  ["Union dues", "les cotisations syndicales", "Les cotisations syndicales sont prélevées sur la paie."],
  ["Workplace safety", "la sécurité au travail", "La sécurité au travail est la responsabilité de tous."],
  ["Protective equipment", "l'équipement de protection", "Portez l'équipement de protection en entrepôt."],
  ["First day on the job", "le premier jour de travail", "Le premier jour de travail, présentez-vous quinze minutes à l'avance."],
  ["Probation review", "l'examen de période d'essai", "L'examen de période d'essai confirme l'embauche."],
  ["Remote onboarding", "l'intégration à distance", "L'intégration à distance inclut une visite virtuelle."],
  ["Coworking space", "l'espace de coworking", "L'espace de coworking loue des bureaux à la journée."],
  ["Open office", "le bureau ouvert", "Le bureau ouvert favorise les échanges rapides."],
  ["Break room", "la salle de pause", "Rangez vos assiettes dans la salle de pause."],
  ["Staff lounge", "le local du personnel", "Le local du personnel est au sous-sol."],
  ["Company policy", "la politique d'entreprise", "La politique d'entreprise encadre l'utilisation du courriel."],
  ["Dress code", "le code vestimentaire", "Le code vestimentaire exige des chaussures fermées."],
  ["Name tag", "le badge nominatif", "Portez votre badge nominatif en tout temps."],
  ["Job shadowing", "l'observation en milieu de travail", "L'observation en milieu de travail dure une semaine."],
  ["Mentorship", "le mentorat", "Le mentorat aide les nouveaux employés."],
  ["Career change", "la reconversion professionnelle", "La reconversion professionnelle demande du temps."],
  ["Volunteer work", "le bénévolat", "Le bénévolat enrichit votre CV et votre réseau."],
  ["Municipal community hall", "la salle communautaire municipale", "La salle communautaire municipale offre des cours gratuits."],
  ["Settlement agency", "l'organisme d'établissement", "L'organisme d'établissement oriente les nouveaux arrivants."],
  ["Newcomer", "le nouvel arrivant", "Le nouvel arrivant peut suivre un cours de français gratuit."],
  ["Family reunification", "le regroupement familial", "Le regroupement familial suit des règles précises."],
  ["Cultural association", "l'association culturelle", "L'association culturelle organise un festival chaque été."],
  ["Heritage festival", "le festival du patrimoine", "Le festival du patrimoine met en vedette la musique locale."],
  ["Winter festival", "le festival d'hiver", "Le festival d'hiver propose du patinage sur le canal."],
  ["Ice skating", "le patinage", "Le patinage sur la patinoire extérieure est gratuit ce soir."],
  ["Community garden", "le jardin communautaire", "Le jardin communautaire accepte de nouveaux membres au printemps."],
  ["Emergency food pantry", "l'épicerie solidaire", "L'épicerie solidaire recherche des bénévoles le samedi."],
  ["Donation drive", "la collecte de dons", "La collecte de dons se termine vendredi."],
  ["Neighbourhood watch", "la surveillance de quartier", "La surveillance de quartier renforce la sécurité locale."],
  ["Town hall meeting", "l'assemblée publique", "L'assemblée publique discute du budget municipal."],
  ["Local newspaper", "le journal local", "Le journal local couvre les élections scolaires."],
  ["Community radio", "la radio communautaire", "La radio communautaire diffuse en français et en anglais."],
  ["Public library branch", "la succursale de bibliothèque", "La succursale de bibliothèque prête des ordinateurs."],
  ["After-school program", "le programme parascolaire", "Le programme parascolaire accueille les enfants jusqu'à dix-sept heures."],
  ["Youth centre", "la maison des jeunes", "La maison des jeunes organise des ateliers d'art."],
  ["Senior centre", "le centre pour aînés", "Le centre pour aînés propose des cours de danse."],
  ["Affordable rent", "le loyer abordable", "Trouver un loyer abordable reste difficile en ville."],
  ["Rental listing", "l'annonce de location", "L'annonce de location précise si les animaux sont acceptés."],
  ["Credit check (rental)", "la vérification de crédit", "Le propriétaire demande une vérification de crédit."],
  ["Rental application", "la demande de location", "Joignez vos talons de paie à la demande de location."],
  ["Lease start date", "la date de début du bail", "La date de début du bail est le premier juillet."],
  ["Move-in inspection", "l'état des lieux d'entrée", "L'état des lieux d'entrée documente l'état de l'appartement."],
  ["Move-out inspection", "l'état des lieux de sortie", "L'état des lieux de sortie compare avec les photos initiales."],
  ["Security deposit return", "le remboursement du dépôt", "Le remboursement du dépôt suit l'état des lieux de sortie."],
  ["Excessive noise report", "le signalement de bruit excessif", "Déposez un signalement de bruit excessif auprès de la gestion."],
  ["Quiet hours", "les heures de silence", "Les heures de silence commencent à vingt-deux heures."],
  ["Shared laundry", "la buanderie commune", "La buanderie commune fonctionne avec des pièces."],
  ["Storage locker", "le casier de rangement", "Le casier de rangement est au sous-sol."],
  ["Balcony", "le balcon", "Le balcon donne sur la cour intérieure."],
  ["Basement apartment", "le sous-sol locatif", "Le sous-sol locatif a sa propre entrée."],
  ["Condo fees", "les frais de condo", "Les frais de condo couvrent l'entretien des parties communes."],
  ["Property manager", "le gestionnaire immobilier", "Le gestionnaire immobilier répond sous quarante-huit heures."],
  ["Housing cooperative", "la coopérative d'habitation", "La coopérative d'habitation fonctionne sans but lucratif."],
  ["Social housing", "le logement social", "Le logement social est attribué selon des critères de revenu."],
  ["Home inspection", "l'inspection préachat", "L'inspection préachat révèle des problèmes de toiture."],
  ["Mortgage preapproval", "la préapprobation hypothécaire", "Obtenez une préapprobation hypothécaire avant de visiter."],
  ["Down payment", "la mise de fonds", "La mise de fonds représente au moins cinq pour cent du prix."],
  ["Closing costs", "les frais de clôture", "Prévoyez les frais de clôture en plus du prix d'achat."],
  ["Home insurance", "l'assurance habitation", "L'assurance habitation est exigée par la banque."],
  ["Furnace repair", "la réparation de fournaise", "La réparation de fournaise est urgente en janvier."],
  ["Roof leak", "la fuite de toit", "Signalez la fuite de toit dès les premières gouttes."],
  ["Mould", "la moisissure", "La moisissure peut causer des problèmes respiratoires."],
  ["Ventilation", "la ventilation", "Une bonne ventilation réduit l'humidité."],
  ["Energy audit", "la vérification énergétique", "La vérification énergétique suggère d'isoler les fenêtres."],
  ["Heat pump", "la thermopompe", "La thermopompe chauffe et climatise la maison."],
  ["Smart thermostat", "le thermostat intelligent", "Le thermostat intelligent baisse la température la nuit."],
  ["Family clinic", "la clinique familiale", "La clinique familiale accepte les nouveaux patients en septembre."],
  ["Nurse practitioner", "l'infirmière praticienne", "L'infirmière praticienne peut renouveler certaines ordonnances."],
  ["Telehealth", "la télésanté", "La télésanté permet une consultation par vidéo."],
  ["Medical appointment reminder", "le rappel de rendez-vous médical", "Vous recevrez un rappel de rendez-vous médical par texto."],
  ["Lab results", "les résultats d'analyse", "Les résultats d'analyse seront disponibles en ligne."],
  ["Pharmacy pickup", "le ramassage à la pharmacie", "Le ramassage à la pharmacie est prêt après quinze heures."],
  ["Flu shot", "le vaccin contre la grippe", "Le vaccin contre la grippe est offert gratuitement."],
  ["Dental hygiene visit", "la visite d'hygiène dentaire", "Prenez un rendez-vous pour une visite d'hygiène dentaire."],
  ["Vision test", "l'examen de la vue", "L'examen de la vue est recommandé tous les deux ans."],
  ["Rehabilitation therapy", "la thérapie de réadaptation", "La thérapie de réadaptation aide à récupérer après une entorse."],
  ["Chronic condition", "la maladie chronique", "Une maladie chronique exige un suivi régulier."],
  ["Pain relief", "le soulagement de la douleur", "Le soulagement de la douleur ne remplace pas un diagnostic."],
  ["Sleep disorder", "le trouble du sommeil", "Un trouble du sommeil affecte la concentration au travail."],
  ["Stress management", "la gestion du stress", "La gestion du stress fait partie du programme bien-être."],
  ["Support group", "le groupe de soutien", "Le groupe de soutien se réunit chaque mercredi soir."],
  ["Crisis line", "la ligne de crise", "La ligne de crise répond vingt-quatre heures sur vingt-quatre."],
  ["Kindergarten", "la maternelle", "L'inscription à la maternelle commence en février."],
  ["Elementary teacher", "l'enseignant du primaire", "L'enseignant du primaire envoie un message aux parents."],
  ["High school diploma", "le diplôme d'études secondaires", "Le diplôme d'études secondaires est requis pour le cégep."],
  ["College program", "le programme collégial", "Le programme collégial dure trois ans."],
  ["University admission", "l'admission universitaire", "L'admission universitaire exige un dossier complet."],
  ["Orientation week", "la semaine d'accueil", "La semaine d'accueil aide les étudiants à s'orienter."],
  ["Student loan", "le prêt étudiant", "Le prêt étudiant se rembourse après les études."],
  ["Study group", "le groupe d'étude", "Le groupe d'étude se réunit à la bibliothèque."],
  ["Exam period", "la période d'examens", "La période d'examens commence dans deux semaines."],
  ["Plagiarism", "le plagiat", "Le plagiat entraîne une sanction disciplinaire."],
  ["Academic advisor", "le conseiller pédagogique", "Rencontrez le conseiller pédagogique pour choisir vos cours."],
  ["Internship placement", "le stage en milieu de travail", "Le stage en milieu de travail compte pour trois crédits."],
  ["Literacy program", "le programme d'alphabétisation", "Le programme d'alphabétisation est gratuit pour les adultes."],
  ["Bilingual immersion program", "le programme d'immersion bilingue", "Le programme d'immersion bilingue commence en maternelle."],
  ["ESL class", "le cours de français langue seconde", "Le cours de français langue seconde est offert le soir."],
  ["After-school study hall", "la salle d'étude parascolaire", "La salle d'étude parascolaire aide les élèves après l'école."],
  ["School bus route", "la tournée d'autobus scolaire", "La tournée d'autobus scolaire passe à sept heures quinze."],
  ["Parent council", "le conseil d'établissement", "Le conseil d'établissement se réunit le premier mardi du mois."],
  ["Biodiversity", "la biodiversité", "La biodiversité du parc urbain attire les ornithologues."],
  ["To reduce (emissions)", "réduire", "La ville veut réduire les émissions de gaz à effet de serre."],
  ["Reusable container", "le contenant réutilisable", "Apportez un contenant réutilisable au marché."],
  ["Composting program", "le programme de compostage", "Le programme de compostage distribue des bacs gratuits."],
  ["Tree planting", "la plantation d'arbres", "La plantation d'arbres aura lieu samedi au parc."],
  ["Urban forest", "la forêt urbaine", "La forêt urbaine rafraîchit les quartiers en été."],
  ["Green space", "l'espace vert", "L'espace vert est ouvert au public jusqu'à vingt heures."],
  ["Wildfire smoke", "la fumée de feux de forêt", "La fumée de feux de forêt dégrade la qualité de l'air."],
  ["Flood warning", "l'avertissement d'inondation", "Un avertissement d'inondation est émis pour la rivière."],
  ["Drought", "la sécheresse", "La sécheresse limite l'arrosage des pelouses."],
  ["Water conservation", "la conservation de l'eau", "La conservation de l'eau est essentielle en période sèche."],
  ["Solar panel", "le panneau solaire", "Le panneau solaire réduit la facture d'électricité."],
  ["Wind farm", "le parc éolien", "Le parc éolien alimente plusieurs municipalités."],
  ["Electric vehicle", "le véhicule électrique", "Le véhicule électrique se recharge à la borne du stationnement."],
  ["Charging station", "la borne de recharge", "La borne de recharge est occupée, attendez cinq minutes."],
  ["Public transit expansion", "l'élargissement du transport en commun", "L'élargissement du transport en commun réduit la congestion."],
  ["Bike sharing", "le service de vélos partagés", "Le service de vélos partagés coûte trois dollars la demi-heure."],
  ["Pedestrian bridge", "la passerelle piétonne", "La passerelle piétonne enjambe l'autoroute."],
  ["Noise pollution", "la pollution sonore", "La pollution sonore perturbe les résidents la nuit."],
  ["Waste sorting", "le tri des déchets", "Le tri des déchets est obligatoire dans cet immeuble."],
  ["Landfill", "le site d'enfouissement", "Le site d'enfouissement atteint bientôt sa capacité."],
  ["Recycling depot", "le centre de recyclage", "Apportez le verre au centre de recyclage samedi."],
  ["Hazardous waste", "les déchets dangereux", "Les déchets dangereux ne vont pas dans les ordures."],
  ["Local news", "l'actualité locale", "L'actualité locale couvre la fermeture de la piscine."],
  ["Breaking news", "la nouvelle de dernière heure", "La nouvelle de dernière heure s'affiche en bannière."],
  ["Investigative report", "le reportage d'enquête", "Le reportage d'enquête révèle des pratiques douteuses."],
  ["Opinion column", "la chronique d'opinion", "La chronique d'opinion défend la liberté d'expression."],
  ["Freedom of expression", "la liberté d'expression", "La liberté d'expression comporte aussi des responsabilités."],
  ["Editorial board", "le comité de rédaction", "Le comité de rédaction valide chaque éditorial."],
  ["Podcast episode", "l'épisode de balado", "Le nouvel épisode de balado sort chaque mardi."],
  ["Streaming platform", "la plateforme de diffusion", "La plateforme de diffusion propose des documentaires."],
  ["Documentary film", "le documentaire", "Le documentaire traite du changement climatique."],
  ["Cultural diversity", "la diversité culturelle", "La diversité culturelle enrichit la programmation du festival."],
  ["Multicultural event", "l'événement multiculturel", "L'événement multiculturel propose des dégustations gratuites."],
  ["Community involvement", "l'implication communautaire", "L'implication communautaire passe aussi par le bénévolat."],
  ["Youth vote", "le vote des jeunes", "Le vote des jeunes a augmenté lors de la dernière élection."],
  ["Municipal council", "le conseil municipal", "Le conseil municipal adopte le budget demain soir."],
  ["By-law", "le règlement municipal", "Le règlement municipal interdit les feux de joie en ville."],
  ["Public square", "la place publique", "La place publique accueille un marché fermier le dimanche."],
  ["Farmers market", "le marché fermier", "Le marché fermier ouvre à huit heures le samedi."],
  ["Local business", "l'entreprise locale", "Soutenez l'entreprise locale en achetant près de chez vous."],
  ["Small business", "la petite entreprise", "La petite entreprise emploie moins de cinquante personnes."],
  ["Startup", "la jeune entreprise", "La jeune entreprise cherche des investisseurs."],
  ["Chamber of commerce", "la chambre de commerce", "La chambre de commerce organise un déjeuner réseautage."],
  ["Consumer protection", "la protection du consommateur", "La protection du consommateur encadre la publicité trompeuse."],
  ["Product recall", "le rappel de produit", "Un rappel de produit concerne ce modèle de chauffe-eau."],
  ["Online review", "l'avis en ligne", "L'avis en ligne influence le choix des clients."],
  ["Data breach", "la fuite de données", "Une fuite de données oblige à changer vos mots de passe."],
  ["Password manager", "le gestionnaire de mots de passe", "Un gestionnaire de mots de passe renforce la sécurité."],
  ["Two-factor authentication", "l'authentification à deux facteurs", "Activez l'authentification à deux facteurs sur votre compte."],
  ["Digital literacy", "la littératie numérique", "La littératie numérique est enseignée en bibliothèque."],
  ["Elder abuse", "la maltraitance des aînés", "Signalez la maltraitance des aînés à la ligne d'aide."],
  ["Food insecurity", "l'insécurité alimentaire", "L'insécurité alimentaire touche de nombreuses familles."],
  ["Homelessness", "l'itinérance", "Des programmes visent à réduire l'itinérance en hiver."],
  ["Affordable childcare", "la garde abordable", "La garde abordable reste une priorité pour les parents."],
  ["Gender equality", "l'égalité des genres", "L'égalité des genres progresse, mais des écarts persistent."],
  ["Accessibility ramp", "la rampe d'accès", "La rampe d'accès facilite l'entrée du bâtiment."],
  ["Sign language interpreter", "l'interprète en langue des signes", "Un interprète en langue des signes est prévu à l'événement."],
  ["Anti-discrimination", "la lutte contre la discrimination", "La lutte contre la discrimination est inscrite dans la politique."],
  ["Human rights complaint", "la plainte en droits de la personne", "Déposez une plainte en droits de la personne si nécessaire."],
  ["Public health order", "l'ordonnance de santé publique", "L'ordonnance de santé publique limite les rassemblements."],
  ["Vaccination clinic", "la clinique de vaccination", "La clinique de vaccination accepte les sans rendez-vous."],
  ["Heat alert", "l'alerte chaleur", "Une alerte chaleur est en vigueur pour les personnes vulnérables."],
  ["Cooling centre", "le centre de refroidissement", "Le centre de refroidissement ouvre lors des canicules."],
  ["Snow clearing", "le déneigement des rues", "Le déneigement des rues commence à minuit."],
  ["Salt truck", "le camion à sel", "Le camion à sel traite les côtes glissantes."],
  ["Pothole repair", "la réparation de nids-de-poule", "La réparation de nids-de-poule est prévue sur l'avenue principale."],
  ["Street lighting", "l'éclairage public", "L'éclairage public sera modernisé au printemps."],
  ["Cycling infrastructure", "l'infrastructure cyclable", "L'infrastructure cyclable se développe dans le centre-ville."],
  ["Transit strike", "la grève du transport", "La grève du transport perturbe les trajets matinaux."],
  ["Fare increase", "l'augmentation du tarif", "L'augmentation du tarif sera débattue en conseil."],
  ["Monthly transit pass", "la passe mensuelle", "La passe mensuelle est moins chère pour les étudiants."],
  ["Park permit", "le permis de parc", "Le permis de parc autorise le camping trois nuits."],
  ["Wildlife crossing", "le passage faunique", "Ralentissez près du passage faunique la nuit."],
  ["Nature reserve", "la réserve naturelle", "La réserve naturelle interdit les chiens non tenus."],
  ["Guided hike", "la randonnée guidée", "La randonnée guidée part à neuf heures du poste d'accueil."],
  ["Canoe rental", "la location de canot", "La location de canot est disponible jusqu'en septembre."],
  ["Swimming lessons", "les cours de natation", "Inscrivez vos enfants aux cours de natation en avril."],
  ["Public pool", "la piscine publique", "La piscine publique ferme pour l'entretien en août."],
  ["Arena schedule", "l'horaire de l'aréna", "L'horaire de l'aréna affiche les heures de patinage libre."],
  ["Recreation program", "le programme de loisirs", "Le programme de loisirs propose du yoga gratuit."],
  ["Library workshop", "l'atelier en bibliothèque", "L'atelier en bibliothèque enseigne la recherche d'emploi."],
  ["Job search workshop", "l'atelier de recherche d'emploi", "L'atelier de recherche d'emploi aide à rédiger le CV."],
  ["Resume clinic", "la clinique de CV", "La clinique de CV a lieu jeudi après-midi."],
  ["Interview practice", "la simulation d'entrevue", "La simulation d'entrevue se fait avec un bénévole."],
  ["Language exchange", "l'échange linguistique", "L'échange linguistique réunit francophones et anglophones."],
  ["Conversation circle", "le cercle de conversation", "Le cercle de conversation se tient chaque mercredi."],
  ["Citizenship ceremony", "la cérémonie de citoyenneté", "La cérémonie de citoyenneté accueille cent nouveaux citoyens."],
  ["Oath of citizenship", "le serment de citoyenneté", "Le serment de citoyenneté est prononcé en français et en anglais."],
  ["Cultural integration", "l'intégration culturelle", "L'intégration culturelle passe par la participation locale."],
  ["Intercultural dialogue", "le dialogue interculturel", "Le dialogue interculturel réduit les préjugés."],
  ["Heritage month", "le mois du patrimoine", "Le mois du patrimoine met en lumière les traditions locales."],
  ["Indigenous culture", "la culture autochtone", "La culture autochtone est célébrée lors du pow-wow."],
  ["Truth and reconciliation", "la vérité et la réconciliation", "La vérité et la réconciliation exigent l'écoute des survivants."],
  ["Land acknowledgment", "la reconnaissance territoriale", "La reconnaissance territoriale ouvre l'événement officiel."],
  ["Francophone community", "la communauté francophone", "La communauté francophone organise des activités en français."],
  ["Anglophone minority", "la minorité anglophone", "La minorité anglophone maintient ses écoles et ses médias."],
  ["Bilingual service", "le service bilingue", "Le service bilingue est offert au comptoir."],
  ["Translation service", "le service de traduction", "Le service de traduction est gratuit pour les formulaires essentiels."],
  ["Interpretation service", "le service d'interprétation", "Réservez le service d'interprétation avant votre rendez-vous."],
  ["Legal aid clinic", "la clinique d'aide juridique", "La clinique d'aide juridique conseille les locataires."],
  ["Tenant hotline", "la ligne d'aide aux locataires", "La ligne d'aide aux locataires répond en soirée."],
  ["Women's shelter", "le refuge pour femmes", "Le refuge pour femmes offre un hébergement temporaire."],
  ["Youth shelter", "le refuge pour jeunes", "Le refuge pour jeunes accueille les dix-huit à vingt-quatre ans."],
  ["Addiction support", "le soutien en dépendance", "Le soutien en dépendance est confidentiel et gratuit."],
  ["Gambling help line", "la ligne d'aide au jeu", "La ligne d'aide au jeu est anonyme."],
  ["Financial counselling", "le conseil en finances", "Le conseil en finances aide à établir un budget réaliste."],
  ["Debt repayment plan", "le plan de remboursement", "Un plan de remboursement évite les appels de recouvrement."],
  ["Credit counselling", "le counselling de crédit", "Le counselling de crédit explique comment améliorer votre cote."],
  ["Microloan", "le microprêt", "Le microprêt aide à lancer une petite entreprise."],
  ["Cooperative store", "la coopérative", "La coopérative vend des produits locaux à prix justes."],
  ["Fair trade", "le commerce équitable", "Le commerce équitable garantit un salaire décent aux producteurs."],
  ["Organic farming", "l'agriculture biologique", "L'agriculture biologique évite certains pesticides."],
  ["Local producer", "le producteur local", "Achetez directement chez le producteur local."],
  ["Seasonal work", "le travail saisonnier", "Le travail saisonnier en agriculture commence en juin."],
  ["Harvest festival", "la fête des récoltes", "La fête des récoltes propose de la musique et des tartes."],
  ["Craft fair", "le marché artisanal", "Le marché artisanal vend des bijoux faits main."],
  ["Book fair", "le salon du livre", "Le salon du livre accueille des auteurs québécois."],
  ["Film festival", "le festival du cinéma", "Le festival du cinéma projette des courts métrages gratuits."],
  ["Street performance", "le spectacle de rue", "Le spectacle de rue attire une foule au centre-ville."],
  ["Public art", "l'art public", "L'art public colore la nouvelle place publique."],
  ["Museum admission", "l'admission au musée", "L'admission au musée est gratuite le premier dimanche."],
  ["Library membership", "l'abonnement à la bibliothèque", "L'abonnement à la bibliothèque est gratuit pour les résidents."],
  ["Reading club", "le club de lecture", "Le club de lecture discute d'un roman ce mois-ci."],
  ["Writing workshop", "l'atelier d'écriture", "L'atelier d'écriture aide à rédiger une lettre de motivation."],
  ["Public speaking", "la prise de parole en public", "La prise de parole en public se travaille en atelier."],
  ["Debate club", "le club de débat", "Le club de débat prépare les élèves aux concours."],
  ["Science fair", "l'expo-sciences", "L'expo-sciences présente des projets d'élèves du secondaire."],
  ["Math tutoring", "le soutien en mathématiques", "Le soutien en mathématiques est offert deux soirs par semaine."],
  ["Adult education", "la formation des adultes", "La formation des adultes permet d'obtenir un diplôme."],
  ["Night school", "les cours du soir", "Les cours du soir conviennent aux travailleurs."],
  ["Distance learning", "la formation à distance", "La formation à distance exige une bonne connexion Internet."],
  ["Online forum", "le forum en ligne", "Le forum en ligne modère les commentaires offensants."],
  ["Community bulletin", "le bulletin communautaire", "Le bulletin communautaire annonce les activités du mois."],
  ["Neighbourhood association", "l'association de quartier", "L'association de quartier organise un nettoyage du parc."],
  ["Block party", "la fête de quartier", "La fête de quartier réunit les voisins en septembre."],
  ["Garage sale", "la vente-débarras", "La vente-débarras a lieu samedi sur la rue des Érables."],
  ["Donation receipt", "le reçu de don", "Demandez un reçu de don pour vos impôts."],
  ["Charity run", "la course caritative", "La course caritative finance la recherche sur le cancer."],
  ["Blood drive", "la collecte de sang", "La collecte de sang cherche des donneurs cette semaine."],
  ["Organ donor", "le don d'organes", "Inscrivez-vous au don d'organes sur le registre provincial."],
  ["Palliative care", "les soins palliatifs", "Les soins palliatifs accompagnent la fin de vie avec dignité."],
  ["Home care", "les soins à domicile", "Les soins à domicile permettent de vieillir chez soi."],
  ["Meals on wheels", "les repas à domicile", "Les repas à domicile livrent le dîner aux aînés."],
  ["Respite care", "le répit pour aidants", "Le répit pour aidants offre quelques heures de soulagement."],
  ["Caregiver support", "le soutien aux proches aidants", "Le soutien aux proches aidants inclut des groupes de discussion."],
];

export const BATCH6_C: LemmaRow[] = [
  ["Even so", "néanmoins", "Néanmoins, les résultats ne sont pas encore concluants."],
  ["Hence", "dès lors", "Dès lors, il faut revoir la stratégie proposée."],
  ["Moreover", "en outre", "En outre, le coût social demeure élevé."],
  ["In addition", "en plus", "En plus, plusieurs experts restent sceptiques."],
  ["On the flip side", "du côté positif", "Du côté positif, la mesure protège les plus vulnérables."],
  ["First of all", "tout d'abord", "Tout d'abord, clarifions les objectifs du projet."],
  ["Finally", "enfin", "Enfin, il convient de saluer l'effort des bénévoles."],
  ["In short", "en bref", "En bref, la réforme est nécessaire mais incomplète."],
  ["That is to say", "c'est-à-dire", "Le délai est court, c'est-à-dire deux semaines."],
  ["In other words", "autrement dit", "Autrement dit, la ville manque de ressources."],
  ["For instance", "par exemple", "Par exemple, plusieurs villes ont adopté le même règlement."],
  ["Above all", "surtout", "Surtout, il faut écouter les citoyens concernés."],
  ["In spite of", "malgré", "Malgré les critiques, le projet avance."],
  ["Because of", "en raison de", "En raison de la pluie, le festival est reporté."],
  ["As long as", "tant que", "Tant que les règles sont respectées, l'activité continue."],
  ["As soon as", "dès que", "Dès que les résultats seront connus, nous communiquerons."],
  ["Unless", "à moins que", "Le marché restera fermé à moins que la météo s'améliore."],
  ["Even though", "quoique", "Quoique coûteux, le programme semble efficace."],
  ["Whereas", "alors que", "Alors que la ville investit, le village attend."],
  ["While", "tandis que", "Tandis que l'un propose, l'autre conteste."],
  ["To believe", "croire", "Je crois que la concertation est indispensable."],
  ["To think", "penser", "Il pense que la mesure arrive trop tard."],
  ["To consider", "considérer", "Nous considérons que l'offre est raisonnable."],
  ["To deem", "juger", "Le comité juge la proposition acceptable."],
  ["To assert", "affirmer", "Elle affirme que les données sont fiables."],
  ["To claim", "prétendre", "Il prétend que le service s'est amélioré."],
  ["To admit", "admettre", "Le maire admet que le délai était trop court."],
  ["To deny", "nier", "L'entreprise nie toute responsabilité dans l'incident."],
  ["To doubt", "douter", "Je doute que cette solution soit durable."],
  ["To suspect", "soupçonner", "On soupçonne une erreur dans le rapport."],
  ["To assume", "supposer", "Ne supposons pas que tout le monde est d'accord."],
  ["To estimate", "estimer", "Les analystes estiment une hausse modérée."],
  ["To predict", "prévoir", "Les météorologues prévoient un hiver rigoureux."],
  ["To recommend", "recommander", "Le médecin recommande plus de repos."],
  ["To suggest", "suggérer", "Le rapport suggère trois pistes de solution."],
  ["To propose", "proposer", "Elle propose un compromis réaliste."],
  ["To oppose", "s'opposer", "Plusieurs citoyens s'opposent au projet."],
  ["To support", "soutenir", "L'association soutient la liberté d'expression."],
  ["To approve", "approuver", "Le conseil approuve le budget révisé."],
  ["To reject", "rejeter", "L'assemblée rejette la motion à la majorité."],
  ["To criticize", "critiquer", "Les voisins critiquent le bruit nocturne."],
  ["To praise", "saluer", "La presse salue l'initiative communautaire."],
  ["To regret", "regretter", "Je regrette que la réunion ait été annulée."],
  ["To worry", "s'inquiéter", "Les parents s'inquiètent de la sécurité routière."],
  ["To hope", "espérer", "Nous espérons une entente avant la fin du mois."],
  ["To fear", "craindre", "Les commerçants craignent une baisse de fréquentation."],
  ["To insist", "insister", "Il insiste sur la transparence du processus."],
  ["To emphasize", "mettre l'accent sur", "Le document met l'accent sur la participation citoyenne."],
  ["To clarify", "clarifier", "Merci de clarifier votre position dans le débat."],
  ["To explain", "expliquer", "Le porte-parole explique les motifs de la décision."],
  ["To justify", "justifier", "Comment justifiez-vous ce retard?"],
  ["To compare", "comparer", "Comparez les deux offres avant de choisir."],
  ["To contrast", "opposer", "L'auteur oppose la ville dense à la banlieue."],
  ["To illustrate", "illustrer", "Cet exemple illustre bien le problème."],
  ["To demonstrate", "démontrer", "Les chiffres démontrent une tendance claire."],
  ["To prove", "prouver", "Rien ne prouve encore un lien direct."],
  ["To show", "montrer", "L'enquête montre une amélioration graduelle."],
  ["To reveal", "révéler", "Le sondage révèle un changement d'opinion."],
  ["To indicate", "indiquer", "Les résultats indiquent un besoin de formation."],
  ["To imply", "laisser entendre", "Son ton laisse entendre un désaccord."],
  ["To mean", "signifier", "Qu'est-ce que cela signifie pour les résidents?"],
  ["To influence", "influencer", "Les médias influencent parfois le débat public."],
  ["To affect", "affecter", "La sécheresse affecte les agriculteurs locaux."],
  ["To impact", "avoir un impact sur", "La décision aura un impact sur les tarifs."],
  ["To contribute", "contribuer", "Chacun peut contribuer à réduire les déchets."],
  ["To participate", "participer", "Invitez les jeunes à participer à la consultation."],
  ["To involve", "impliquer", "Le projet implique plusieurs partenaires."],
  ["To depend on", "dépendre de", "Le succès dépend de la mobilisation locale."],
  ["To result from", "résulter de", "Le retard résulte d'une panne technique."],
  ["To lead to", "mener à", "Cette politique peut mener à de nouveaux abus."],
  ["To prevent", "empêcher", "Des mesures simples empêchent les accidents."],
  ["To allow", "permettre", "La loi permet un recours en appel."],
  ["To forbid", "interdire", "Le règlement interdit de fumer sur le terrain."],
  ["To require", "exiger", "Le formulaire exige une signature manuscrite."],
  ["To deserve", "mériter", "Ce dossier mérite une attention particulière."],
  ["To lack", "manquer de", "Le quartier manque d'espaces verts."],
  ["To improve", "améliorer", "Il faut améliorer l'accès aux soins."],
  ["To worsen", "aggraver", "L'inaction pourrait aggraver la situation."],
  ["To maintain", "maintenir", "La ville maintient le service malgré les coupes."],
  ["To strengthen", "renforcer", "Renforcer la biodiversité passe par la protection des milieux."],
  ["To weaken", "affaiblir", "La rumeur affaiblit la confiance du public."],
  ["To preserve", "préserver", "Nous devons préserver les terres agricoles."],
  ["To protect", "protéger", "La loi protège les locataires contre les expulsions abusives."],
  ["To threaten", "menacer", "La pollution menace la qualité de l'eau."],
  ["To encourage", "encourager", "Le programme encourage le bénévolat chez les jeunes."],
  ["To discourage", "décourager", "Les frais élevés découragent certains candidats."],
  ["To promote", "promouvoir", "L'école promouvoit l'égalité entre les élèves."],
  ["To raise (a question)", "soulever", "Le rapport soulève une question éthique."],
  ["To address (an issue)", "aborder", "Le débat aborde le coût de la vie."],
  ["To tackle", "s'attaquer à", "Il est temps de s'attaquer au problème du logement."],
  ["To deal with", "traiter", "Le service traite les plaintes sous dix jours."],
  ["To handle", "gérer", "Elle sait gérer les situations difficiles."],
  ["To resolve", "résoudre", "La médiation aide à résoudre le conflit."],
  ["To settle", "régler", "Les parties ont réglé le différend à l'amiable."],
  ["To negotiate", "négocier", "Les syndicats négocient une nouvelle convention."],
  ["To compromise", "faire un compromis", "Les élus doivent faire un compromis acceptable."],
  ["To agree", "être d'accord", "Je suis d'accord avec l'idée générale."],
  ["To disagree", "ne pas être d'accord", "Nous ne sommes pas d'accord sur les priorités."],
  ["To debate", "débattre", "Le conseil débattra du budget demain."],
  ["To discuss", "discuter", "Discutons des avantages et des risques."],
  ["To argue", "faire valoir", "Elle fait valoir que le délai est irréaliste."],
  ["To persuade", "convaincre", "Les faits peuvent convaincre les indécis."],
  ["To convince", "persuader", "Il a réussi à persuader son équipe."],
  ["Uncertainty", "l'incertitude", "L'incertitude entoure encore l'échéancier."],
  ["Likelihood", "la probabilité", "La probabilité d'un accord augmente chaque jour."],
  ["Relevance", "la pertinence", "La pertinence de la mesure fait débat."],
  ["Validity", "la validité", "La validité de l'argument repose sur des sources fiables."],
  ["Credibility", "la crédibilité", "La crédibilité de l'organisme est en jeu."],
  ["Legitimacy", "la légitimité", "La légitimité du processus rassure les citoyens."],
  ["Responsibility", "la responsabilité", "La responsabilité incombe à l'employeur."],
  ["Accountability (noun)", "la reddition de comptes", "La reddition de comptes renforce la confiance."],
  ["Consequence", "la conséquence", "Chaque décision a une conséquence sociale."],
  ["Balancing act", "l'arbitrage", "L'arbitrage équilibre coût et qualité."],
  ["Priority", "la priorité", "La priorité demeure l'accès aux soins."],
  ["Constraint", "la contrainte", "Le budget impose une contrainte majeure."],
  ["Opportunity", "l'occasion", "C'est l'occasion de moderniser les services."],
  ["Challenge (noun)", "le défi", "Le vieillissement de la population est un défi."],
  ["Progress", "le progrès", "Le progrès reste lent mais visible."],
  ["Setback", "le revers", "Le revers n'empêche pas la poursuite du projet."],
  ["Trend", "la tendance", "La tendance favorise le travail hybride."],
  ["Gap (difference)", "l'écart", "L'écart entre les régions persiste."],
  ["Inequality", "l'inégalité", "L'inégalité touche surtout les familles monoparentales."],
  ["Solidarity", "la solidarité", "La solidarité s'exprime par le bénévolat local."],
  ["Cohesion", "la cohésion", "La cohésion sociale dépend du dialogue."],
  ["Tolerance", "la tolérance", "La tolérance favorise le vivre-ensemble."],
  ["Respect", "le respect", "Le respect mutuel est essentiel en milieu de travail."],
  ["Trust", "la confiance", "La confiance se reconstruit avec la transparence."],
  ["Distrust", "la méfiance", "La méfiance envers les institutions a augmenté."],
  ["Skepticism", "le scepticisme", "Le scepticisme des experts est compréhensible."],
  ["Enthusiasm", "l'enthousiasme", "L'enthousiasme des bénévoles est contagieux."],
  ["Concern", "la préoccupation", "La préoccupation principale concerne le logement."],
  ["Awareness", "la sensibilisation", "La sensibilisation à la biodiversité commence à l'école."],
  ["Commitment", "l'engagement", "L'engagement des partenaires est total."],
  ["Initiative (noun)", "l'initiative", "Cette initiative réduit le gaspillage alimentaire."],
  ["Reform (noun)", "la réforme", "La réforme vise à simplifier les démarches."],
  ["Regulation (noun)", "la réglementation", "La réglementation encadre les locations court terme."],
  ["Framework", "le cadre", "Le cadre juridique évolue lentement."],
  ["Principle", "le principe", "Le principe d'équité guide la politique."],
  ["Value (belief)", "la valeur", "La valeur de la liberté d'expression est centrale."],
  ["Right (entitlement)", "le droit", "Chaque citoyen a le droit de participer."],
  ["Duty", "le devoir", "Le devoir civique inclut le vote."],
  ["Freedom", "la liberté", "La liberté s'exerce dans le respect des autres."],
  ["Equality", "l'égalité", "L'égalité devant la loi est un fondement démocratique."],
  ["Justice", "la justice", "La justice doit être accessible à tous."],
  ["Fairness", "l'équité", "L'équité exige des règles claires pour tous."],
  ["Welfare", "le bien-être", "Le bien-être des enfants prime dans la décision."],
  ["Quality of life", "la qualité de vie", "La qualité de vie attire de nouveaux résidents."],
  ["Standard of living", "le niveau de vie", "Le niveau de vie varie d'une région à l'autre."],
  ["Perspective", "la perspective", "Changeons de perspective pour mieux comprendre."],
  ["Viewpoint", "le point de vue", "Son point de vue mérite d'être entendu."],
  ["Argument", "l'argument", "L'argument principal repose sur des faits."],
  ["Evidence", "la preuve", "La preuve présentée reste insuffisante."],
  ["Assumption (noun)", "la supposition", "Cette supposition n'est pas démontrée."],
  ["Conclusion (noun)", "la conclusion", "La conclusion du rapport surprend les lecteurs."],
  ["Summary (noun)", "le résumé", "Le résumé reprend les points essentiels."],
  ["Analysis (noun)", "l'analyse", "L'analyse montre des écarts régionaux."],
  ["Debate (noun)", "le débat", "Le débat public se poursuit en ligne."],
  ["Discussion (noun)", "la discussion", "La discussion reste respectueuse malgré les désaccords."],
  ["Shared agreement", "l'accord commun", "Un accord commun se dessine autour de la mesure."],
  ["Division", "la division", "La division politique complique l'adoption du texte."],
  ["Majority", "la majorité", "La majorité a voté en faveur du projet."],
  ["Minority (group)", "la minorité", "La minorité a déposé un amendement."],
  ["Compromise (noun)", "l'entente", "L'entente satisfait partiellement chaque camp."],
  ["Balance", "l'équilibre", "Trouver l'équilibre entre croissance et environnement est difficile."],
  ["Harmony", "l'harmonie", "L'harmonie entre voisins évite les conflits."],
  ["Conflict", "le conflit", "Le conflit oppose résidents et promoteur."],
  ["Tension", "la tension", "La tension monte autour du nouveau règlement."],
  ["Crisis", "la crise", "La crise du logement touche plusieurs villes."],
  ["Recovery", "la reprise", "La reprise économique reste fragile."],
  ["Stability", "la stabilité", "La stabilité financière rassure les locataires."],
  ["Change (noun)", "le changement", "Le changement demande du temps et de la patience."],
  ["Tradition", "la tradition", "La tradition se perpétue lors du festival d'hiver."],
  ["Innovation", "l'innovation", "L'innovation peut améliorer les services publics."],
  ["Heritage (legacy)", "le patrimoine", "Le patrimoine architectural mérite d'être protégé."],
  ["Identity", "l'identité", "L'identité culturelle se transmet par la langue."],
  ["Belonging", "le sentiment d'appartenance", "Le sentiment d'appartenance renforce la communauté."],
  ["Integration (noun)", "l'intégration", "L'intégration des nouveaux arrivants est une priorité locale."],
  ["Participation (noun)", "la participation", "La participation aux consultations reste faible."],
  ["Representation", "la représentation", "La représentation des jeunes au conseil est limitée."],
  ["Influence (noun)", "l'influence", "L'influence des réseaux sociaux est indéniable."],
  ["Impact (noun)", "l'effet", "L'effet sur l'environnement sera évalué."],
  ["Benefit", "l'avantage", "L'avantage principal est la réduction des délais."],
  ["Drawback", "l'inconvénient", "L'inconvénient majeur est le coût initial."],
  ["Risk", "le risque", "Le risque d'inondation augmente avec les pluies violentes."],
  ["Safety", "la sécurité", "La sécurité des piétons est une préoccupation constante."],
  ["Well-being (alt)", "le bien-être collectif", "Le bien-être collectif passe par des services accessibles."],
];
