import type { TCFReadingQuestion } from "./tcf-reading";
export type { TCFLevel } from "./tcf-listening";

export const TCF_READING_P3: TCFReadingQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    passageType: "Affiche",
    passage: "COURS DE YOGA\nTous les mardis et jeudis · 19h–20h30\nSalle 3, Centre sportif municipal\nDébutants bienvenus\nApportez votre tapis",
    question: "Que faut-il apporter au cours de yoga ?",
    options: ["Des chaussures de sport.", "Son tapis.", "Une bouteille d'eau.", "Des vêtements de rechange."],
    correctIndex: 1,
    explanation: "L'affiche indique d'apporter son tapis au cours de yoga.",
  },
  {
    id: 2,
    level: "A1",
    passageType: "Email",
    passage: "Bonjour Jean-Pierre,\nJ'ai bien reçu ton colis hier. Le livre était en parfait état. Merci beaucoup ! Je t'envoie le paiement par virement ce soir.\nÀ bientôt,\nSophie",
    question: "Pourquoi Sophie écrit-elle à Jean-Pierre ?",
    options: ["Pour commander un livre.", "Pour remercier de l'envoi du colis.", "Pour signaler un problème avec le paiement.", "Pour annuler une commande."],
    correctIndex: 1,
    explanation: "Sophie écrit pour remercier Jean-Pierre d'avoir envoyé un livre en parfait état.",
  },
  {
    id: 3,
    level: "A1",
    passageType: "Panneau",
    passage: "MAIRIE DE SAINT-CLOUD\nServices ouverts au public :\nLundi, mercredi, vendredi : 9h–17h\nMardi, jeudi : 9h–19h\nSamedi : 9h–12h\nFermé le dimanche",
    question: "Quand la mairie ferme-t-elle à 19h ?",
    options: ["Le lundi et vendredi.", "Le samedi.", "Le mardi et jeudi.", "Tous les jours."],
    correctIndex: 2,
    explanation: "La mairie est ouverte jusqu'à 19h le mardi et le jeudi.",
  },
  {
    id: 4,
    level: "A1",
    passageType: "Annonce",
    passage: "Recherche collocataire pour partager appartement 3 pièces\n• Loyer : 450 €/mois charges comprises\n• Quartier Plateau-Mont-Royal, Montréal\n• Disponible : 1er septembre\nContact : pierre.tremblay@courriel.com",
    question: "Quand l'appartement est-il disponible ?",
    options: ["Le 1er août.", "Le 1er septembre.", "Le 1er octobre.", "Immédiatement."],
    correctIndex: 1,
    explanation: "L'appartement est disponible à partir du 1er septembre.",
  },
  {
    id: 5,
    level: "A1",
    passageType: "Message",
    passage: "RAPPEL IMPORTANT\nVotre rendez-vous chez le dentiste est le\njeudi 23 mai à 11h00\nCabinet Leclair, 14 rue des Fleurs\nEn cas d'empêchement, annulez 24h avant",
    question: "Combien de temps à l'avance faut-il annuler le rendez-vous chez le dentiste ?",
    options: ["1 heure avant.", "12 heures avant.", "24 heures avant.", "48 heures avant."],
    correctIndex: 2,
    explanation: "Le rappel demande d'annuler 24 heures avant en cas d'empêchement.",
  },
  {
    id: 6,
    level: "A2",
    passageType: "Lettre",
    passage: "Chère Mme Petit,\nNous vous informons que votre candidature pour le logement social au 12 allée des Pins a été retenue. Vous disposez de 10 jours pour confirmer votre accord. Sans réponse de votre part, l'offre sera transmise au candidat suivant.\nService logement de la ville",
    question: "Que doit faire Mme Petit pour obtenir le logement ?",
    options: ["Payer un dépôt de garantie.", "Confirmer son accord dans les 10 jours.", "Fournir de nouveaux documents.", "Se présenter en personne au bureau."],
    correctIndex: 1,
    explanation: "Mme Petit doit confirmer son accord dans les 10 jours, sinon l'offre sera transmise au candidat suivant.",
  },
  {
    id: 7,
    level: "A2",
    passageType: "Article court",
    passage: "Les Français consomment en moyenne 340 œufs par an. L'œuf est une source de protéines complètes à faible coût. Pour savoir si un œuf est frais, plongez-le dans l'eau : s'il coule, il est frais ; s'il flotte, il est périmé.",
    question: "Comment savoir si un œuf est frais selon le texte ?",
    options: ["En le cassant et en sentant l'odeur.", "En lisant la date inscrite sur la coquille.", "En le plongeant dans l'eau : s'il coule, il est frais.", "En le secouant pour entendre un bruit."],
    correctIndex: 2,
    explanation: "Un œuf frais coule dans l'eau, tandis qu'un œuf périmé flotte.",
  },
  {
    id: 8,
    level: "A2",
    passageType: "Email",
    passage: "Objet : Cours annulé\n\nChers étudiants,\nJe suis dans l'obligation d'annuler le cours de mardi prochain pour raisons personnelles. Le cours sera rattrapé le vendredi 8 à 14h dans la salle habituelle. Merci de votre compréhension.",
    question: "Quand le cours annulé sera-t-il rattrapé ?",
    options: ["Le vendredi 8 à 14h.", "Le mercredi 8 à 14h.", "La semaine prochaine à la même heure.", "Date non encore fixée."],
    correctIndex: 0,
    explanation: "Le cours sera rattrapé le vendredi 8 à 14h dans la salle habituelle.",
  },
  {
    id: 9,
    level: "A2",
    passageType: "Affiche",
    passage: "VIDE-GRENIERS DE PRINTEMPS\nDimanche 5 mai · 8h–17h\nPlace du marché\n⚠ Inscription obligatoire avant le 30 avril\nEmplacement : 15 € pour 6 mètres linéaires",
    question: "Quelle est la date limite d'inscription au vide-greniers ?",
    options: ["Le 5 mai.", "Le 30 avril.", "Le 1er mai.", "Le 15 avril."],
    correctIndex: 1,
    explanation: "L'inscription est obligatoire avant le 30 avril pour participer au vide-greniers du 5 mai.",
  },
  {
    id: 10,
    level: "A2",
    passageType: "Guide",
    passage: "COMMENT RECYCLER CORRECTEMENT :\n🟡 Bac jaune : plastiques, cartons, métaux\n🟢 Bac vert : verre uniquement\n⚫ Bac noir : déchets non recyclables\n🍃 Bac marron : déchets alimentaires et végétaux\nErreur de tri = amende possible",
    question: "Dans quel bac doit-on mettre les cartons ?",
    options: ["Bac noir.", "Bac marron.", "Bac vert.", "Bac jaune."],
    correctIndex: 3,
    explanation: "Les cartons vont dans le bac jaune, avec les plastiques et les métaux.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    passageType: "Article",
    passage: "En France, les « déserts médicaux » touchent désormais près de 30 % de la population. Ces zones, rurales ou périurbaines, manquent cruellement de médecins généralistes. Face à cette situation, certaines communes offrent des aides à l'installation — logements gratuits, primes, subventions de cabinet — pour attirer les jeunes praticiens.",
    question: "Que font certaines communes pour attirer des médecins ?",
    options: ["Elles construisent des hôpitaux régionaux.", "Elles proposent des aides à l'installation : logements, primes, subventions.", "Elles imposent aux étudiants en médecine de s'installer en zone rurale.", "Elles développent la télémédecine à la place."],
    correctIndex: 1,
    explanation: "Certaines communes offrent des logements gratuits, des primes et des subventions pour attirer les médecins en zones rurales.",
  },
  {
    id: 12,
    level: "B1",
    passageType: "Article",
    passage: "Le micro-crédit, popularisé par Muhammad Yunus au Bangladesh, consiste à accorder de très petits prêts à des personnes exclues du système bancaire traditionnel. Les bénéficiaires, souvent des femmes en situation de pauvreté, utilisent ces fonds pour créer de petites activités génératrices de revenus. Malgré ses succès, le micro-crédit est critiqué pour ses taux d'intérêt parfois élevés.",
    question: "Quelle critique est adressée au micro-crédit ?",
    options: ["Il ne cible pas les populations les plus pauvres.", "Ses taux d'intérêt sont parfois élevés.", "Il profite surtout aux hommes.", "Il ne fonctionne que dans les pays asiatiques."],
    correctIndex: 1,
    explanation: "Malgré ses succès, le micro-crédit est critiqué pour ses taux d'intérêt parfois élevés.",
  },
  {
    id: 13,
    level: "B1",
    passageType: "Article",
    passage: "La retraite progressive permet aux salariés de travailler à temps partiel tout en percevant une fraction de leur retraite. Ce dispositif, méconnu, offre une transition douce entre vie active et retraite totale. Il présente l'avantage de maintenir les seniors dans l'emploi, de réduire la pénibilité et de préserver le lien social.",
    question: "Quel est l'avantage principal de la retraite progressive ?",
    options: ["Elle permet de cotiser davantage pour une meilleure retraite finale.", "Elle offre une transition douce entre activité et retraite complète.", "Elle est obligatoire pour les emplois pénibles.", "Elle augmente le salaire des travailleurs seniors."],
    correctIndex: 1,
    explanation: "La retraite progressive permet une transition douce entre vie active et retraite totale tout en maintenant les seniors dans l'emploi.",
  },
  {
    id: 14,
    level: "B1",
    passageType: "Lettre ouverte",
    passage: "Monsieur le Directeur,\nEn tant que parent d'élève, je m'interroge sur la réduction des heures d'éducation physique au collège. Le sport scolaire est essentiel pour le développement moteur, la santé mentale et l'apprentissage du travail en équipe. Réduire ces heures risque d'aggraver la sédentarité chez les adolescents.\nCordialement, Arnaud Leconte",
    question: "Quelle est la préoccupation principale de l'auteur de cette lettre ?",
    options: ["La qualité des repas à la cantine.", "La réduction des heures d'EPS et ses conséquences sur la santé des élèves.", "Le manque d'équipements sportifs dans le collège.", "La sécurité dans la cour de récréation."],
    correctIndex: 1,
    explanation: "L'auteur s'inquiète de la réduction des heures d'EPS et de ses effets négatifs sur la santé des adolescents.",
  },
  {
    id: 15,
    level: "B1",
    passageType: "Article",
    passage: "Les travailleurs saisonniers représentent une main-d'œuvre indispensable dans les secteurs de l'agriculture, du tourisme et de la restauration. Malgré leur rôle crucial, ils bénéficient souvent de protections sociales réduites : accès difficile au logement, conditions précaires et difficultés à faire valoir leurs droits. Des associations militent pour une meilleure reconnaissance de leurs contributions.",
    question: "Quel problème principal les travailleurs saisonniers rencontrent-ils ?",
    options: ["Ils sont mal formés pour leurs tâches.", "Ils ont des protections sociales réduites et des conditions précaires.", "Ils ne peuvent pas adhérer aux syndicats.", "Ils sont trop nombreux pour trouver du travail."],
    correctIndex: 1,
    explanation: "Les travailleurs saisonniers souffrent de protections sociales réduites, de difficultés de logement et de conditions précaires.",
  },
  {
    id: 16,
    level: "B2",
    passageType: "Article",
    passage: "La gamification de l'éducation consiste à intégrer des mécaniques ludiques — points, badges, classements — dans les processus d'apprentissage. Si elle peut augmenter la motivation à court terme, des recherches montrent que la récompense extrinsèque peut à terme réduire la motivation intrinsèque. Les pédagogues mettent en garde contre une confusion entre engagement superficiel et apprentissage profond.",
    question: "Quel risque la gamification de l'éducation présente-t-elle ?",
    options: ["Elle rend les élèves dépendants aux jeux vidéo.", "La récompense extrinsèque peut éroder la motivation intrinsèque.", "Elle creuse les inégalités entre bons et mauvais élèves.", "Elle nuit à la concentration et à la mémorisation."],
    correctIndex: 1,
    explanation: "La gamification peut réduire la motivation intrinsèque en remplaçant le goût d'apprendre par la recherche de récompenses.",
  },
  {
    id: 17,
    level: "B2",
    passageType: "Éditorial",
    passage: "La prolifération des populismes en Europe pose une question fondamentale : ces mouvements sont-ils le symptôme d'un dysfonctionnement de la démocratie représentative ou une menace existentielle pour elle ? Certains théoriciens comme Ernesto Laclau voient dans le populisme une logique politique légitime par laquelle le « peuple » se constitue comme sujet. D'autres y lisent une dangereuse dérive vers le démos excluant et l'homme providentiel.",
    question: "Quel débat théorique le populisme suscite-t-il selon cet éditorial ?",
    options: ["S'il est une forme légitime de politique démocratique ou une menace pour la démocratie.", "S'il est plus fort à gauche ou à droite.", "S'il est le produit des réseaux sociaux ou de la crise économique.", "S'il faut l'interdire ou l'encadrer légalement."],
    correctIndex: 0,
    explanation: "Le débat théorique oppose ceux qui voient le populisme comme une logique politique légitime à ceux qui le considèrent comme une menace.",
  },
  {
    id: 18,
    level: "B2",
    passageType: "Article scientifique",
    passage: "Le microbiome intestinal, composé de milliards de micro-organismes, joue un rôle crucial dans l'immunité, la digestion et même la santé mentale. Des recherches récentes suggèrent que la dysbiose intestinale — déséquilibre de ce microbiome — est associée à des troubles comme l'autisme, la dépression et les maladies inflammatoires. Les probiotiques et prébiotiques sont étudiés comme interventions thérapeutiques.",
    question: "À quels troubles la dysbiose intestinale est-elle associée ?",
    options: ["Aux maladies cardio-vasculaires uniquement.", "À l'autisme, la dépression et les maladies inflammatoires.", "Aux allergies alimentaires et au diabète.", "Aux maladies respiratoires et au cancer."],
    correctIndex: 1,
    explanation: "La dysbiose intestinale est associée à l'autisme, la dépression et les maladies inflammatoires.",
  },
  {
    id: 19,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement des femmes rurales au Québec, porté par les Cercles de fermières depuis plus d'un siècle, illustre comment des femmes ont développé des espaces d'autonomie et de solidarité en dehors des structures institutionnelles masculines. Ce réseau a joué un rôle crucial dans la transmission du patrimoine artisanal, l'émancipation économique des femmes et la vitalité des communautés rurales.",
    question: "Quel rôle les Cercles de fermières ont-ils joué ?",
    options: ["Syndicat agricole féminin de défense des droits du travail.", "Espace d'autonomie féminine, de transmission artisanale et de vitalité communautaire.", "Association politique pour le droit de vote des femmes.", "Organisation d'aide alimentaire pour les familles rurales."],
    correctIndex: 1,
    explanation: "Les Cercles de fermières ont constitué des espaces d'autonomie féminine, de transmission artisanale et de renforcement des communautés rurales.",
  },
  {
    id: 20,
    level: "B2",
    passageType: "Article",
    passage: "La notion de précarité énergétique désigne la situation des ménages qui consacrent plus de 10 % de leur budget aux dépenses d'énergie ou qui souffrent de logements mal isolés. En France, 12 millions de personnes seraient concernées. Ce phénomène aggrave les inégalités sociales et a des conséquences sur la santé, notamment respiratoires chez les enfants vivant dans des logements humides.",
    question: "Quels sont les effets de la précarité énergétique sur la santé ?",
    options: ["Des maladies cardio-vasculaires chez les adultes.", "Des problèmes respiratoires, notamment chez les enfants en logements humides.", "Une augmentation de la dépression due au froid.", "Des troubles alimentaires liés au manque de chauffage."],
    correctIndex: 1,
    explanation: "La précarité énergétique cause des problèmes respiratoires, notamment chez les enfants vivant dans des logements mal isolés et humides.",
  },
  {
    id: 21,
    level: "B2",
    passageType: "Article",
    passage: "Le commerce équitable garantit aux producteurs des pays du Sud un prix minimum pour leurs produits, indépendamment des fluctuations du marché mondial. Il impose également des standards sociaux et environnementaux. Mais certains économistes critiquent ses effets réels : le surcoût payé par le consommateur atteint rarement les producteurs, capturé en partie par les intermédiaires.",
    question: "Quelle critique économique est formulée à l'égard du commerce équitable ?",
    options: ["Il nuit aux producteurs des pays riches.", "Le surcoût payé par les consommateurs n'atteint pas pleinement les producteurs.", "Il favorise les grandes entreprises au détriment des petits producteurs.", "Il ralentit le développement industriel des pays du Sud."],
    correctIndex: 1,
    explanation: "Les économistes critiquent le fait que la prime payée par les consommateurs est souvent capturée par les intermédiaires.",
  },
  {
    id: 22,
    level: "B2",
    passageType: "Article",
    passage: "Le mouvement slow food, fondé en Italie par Carlo Petrini en 1989 en réaction au fast food, défend la diversité alimentaire, les savoir-faire artisanaux et le plaisir de manger partagé. Il promeut l'idée que bien manger n'est pas un luxe mais un droit, et que la préservation des variétés menacées de fruits, légumes et races animales est un enjeu de biodiversité majeur.",
    question: "Que défend le mouvement slow food ?",
    options: ["Une alimentation végétarienne exclusive.", "La diversité alimentaire, les savoir-faire artisanaux et la préservation de la biodiversité.", "La production industrielle de qualité à prix accessible.", "L'interdiction du fast food dans les pays membres."],
    correctIndex: 1,
    explanation: "Slow food défend la diversité alimentaire, les traditions artisanales et la préservation de la biodiversité comme enjeu majeur.",
  },
  {
    id: 23,
    level: "B2",
    passageType: "Article",
    passage: "La littérature jeunesse connaît un essor remarquable, avec des albums qui abordent des sujets autrefois tabous : la mort, le divorce, la maladie, le racisme, la diversité des familles. Ces livres permettent aux enfants de mettre des mots sur des émotions complexes et aux adultes d'entamer des conversations difficiles. Ils jouent un rôle thérapeutique reconnu par les psychologues.",
    question: "Quel rôle joue la littérature jeunesse contemporaine selon cet article ?",
    options: ["Divertir les enfants avec des histoires fantastiques.", "Aborder des sujets difficiles pour aider les enfants à comprendre leurs émotions.", "Remplacer les thérapies psychologiques pour les enfants.", "Transmettre des valeurs religieuses et morales."],
    correctIndex: 1,
    explanation: "La littérature jeunesse contemporaine aide les enfants à mettre des mots sur leurs émotions et facilite les conversations difficiles.",
  },
  {
    id: 24,
    level: "B2",
    passageType: "Article",
    passage: "Les étudiants internationaux représentent une ressource économique et intellectuelle considérable pour les pays hôtes. En France, ils injectent plusieurs milliards d'euros dans l'économie locale. Pourtant, les politiques d'accueil restent insuffisantes : difficultés d'obtention de visa, logement précaire, reconnaissance difficile des diplômes étrangers freinant leur insertion après les études.",
    question: "Malgré leur apport, quels obstacles les étudiants étrangers en France rencontrent-ils ?",
    options: ["Des droits de scolarité trop élevés.", "Difficultés de visa, logement précaire et reconnaissance limitée des diplômes.", "L'absence de cours en anglais dans les universités.", "Un manque d'associations d'accueil."],
    correctIndex: 1,
    explanation: "Les étudiants étrangers font face à des difficultés de visa, de logement et de reconnaissance de leurs diplômes.",
  },
  {
    id: 25,
    level: "B2",
    passageType: "Article",
    passage: "La crise de la masculinité fait l'objet de nombreuses analyses depuis une décennie. Face aux transformations du marché du travail et à l'émancipation des femmes, certains hommes peinent à redéfinir leur identité. Des mouvements contradictoires émergent : certains embrassent une masculinité plus flexible et empathique, d'autres se réfugient dans un backlash contre le féminisme.",
    question: "Quelles sont les deux réponses masculines à la crise d'identité décrites ?",
    options: ["Isolement et violence.", "Masculinité flexible et empathique vs. réaction contre le féminisme.", "Engagement politique et désengagement.", "Reconversion professionnelle et émigration."],
    correctIndex: 1,
    explanation: "Certains hommes adoptent une masculinité plus flexible et empathique, d'autres réagissent par un backlash contre le féminisme.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    passageType: "Extrait philosophique",
    passage: "La liberté négative, théorisée par Isaiah Berlin, consiste en l'absence d'interférence d'autrui dans notre sphère d'action. La liberté positive, en revanche, est la capacité effective à être maître de sa propre vie, à réaliser son potentiel. Berlin s'inquiète que la liberté positive puisse être détournée par des États qui prétendent « libérer » leurs citoyens de leurs propres désirs au nom d'un idéal collectif supérieur.",
    question: "Quelle est la différence entre liberté négative et liberté positive selon Berlin ?",
    options: ["La liberté négative est celle des minorités ; la positive, celle de la majorité.", "La liberté négative est l'absence d'interférence ; la positive, la capacité effective à se réaliser.", "La liberté négative est économique ; la positive, politique.", "La liberté négative est individuelle ; la positive, collective."],
    correctIndex: 1,
    explanation: "Pour Berlin, la liberté négative est l'absence d'interférences, tandis que la liberté positive est la capacité de se réaliser.",
  },
  {
    id: 27,
    level: "C1",
    passageType: "Article académique",
    passage: "La ville de demain, selon les urbanistes, devra réconcilier densité et qualité de vie. La densification douce — ajouter des logements dans les tissus existants sans rompre l'harmonie architecturale — est préférée à l'étalement urbain destructeur des espaces naturels. Des villes comme Barcelone ou Zurich expérimentent des cités-jardins verticales intégrant la biodiversité au cœur même du bâti.",
    question: "Qu'est-ce que la « densification douce » selon cet article ?",
    options: ["La construction de tours résidentielles en périphérie.", "L'ajout de logements dans les tissus existants sans rompre l'harmonie architecturale.", "La réhabilitation d'anciens bâtiments industriels.", "La création de nouveaux quartiers écologiques ex nihilo."],
    correctIndex: 1,
    explanation: "La densification douce intègre de nouveaux logements dans les tissus urbains existants en préservant leur harmonie.",
  },
  {
    id: 28,
    level: "C1",
    passageType: "Extrait littéraire — Assia Djebar",
    passage: "Écrire en français pour une Algérienne, c'était à la fois une conquête et une blessure. Conquête parce que cette langue offrait la visibilité, l'accès à un lectorat mondial, la possibilité de témoigner de l'indicible. Blessure parce qu'elle portait en elle les traces du colonisateur, cette voix qui avait longtemps imposé le silence aux voix que je voulais faire entendre.",
    question: "Comment l'auteure décrit-elle son rapport à la langue française ?",
    options: ["Comme un instrument de domination qu'elle refuse.", "Comme une conquête et une blessure simultanées.", "Comme une langue neutre et universelle.", "Comme une langue d'adoption qu'elle préfère à sa langue maternelle."],
    correctIndex: 1,
    explanation: "L'auteure vit la langue française comme une conquête (visibilité, témoignage) et une blessure (traces du colonisateur).",
  },
  {
    id: 29,
    level: "C1",
    passageType: "Article académique",
    passage: "Le genre, pour Judith Butler, n'est pas une identité stable mais une performance : nous ne sommes pas d'abord femmes ou hommes pour ensuite nous comporter en conséquence — nous devenons ce que nous sommes par la répétition ritualisée d'actes genrés. Cette conception performative du genre subvertit l'idée d'une nature biologique qui déterminerait les comportements sexuels et sociaux.",
    question: "Que signifie la conception performative du genre chez Judith Butler ?",
    options: ["Le genre est biologiquement déterminé et exprimé naturellement.", "Le genre se constitue par la répétition d'actes, non par une identité préalable.", "Le genre est une construction sociale que chacun peut choisir librement.", "Le genre est une fiction utile pour organiser la société."],
    correctIndex: 1,
    explanation: "Pour Butler, le genre se construit par la répétition d'actes genrés — ce n'est pas une identité préalable mais une performance.",
  },
  {
    id: 30,
    level: "C1",
    passageType: "Article académique",
    passage: "La diplomatie des droits de l'homme soulève la question de l'universalisme versus le relativisme culturel. Les défenseurs de l'universalisme soutiennent que certains droits transcendent les cultures. Leurs adversaires relativistes arguent que les droits de l'homme sont une construction occidentale imposée aux autres civilisations sous couvert d'universalité, ce qui constituerait une forme de néo-colonialisme culturel.",
    question: "Sur quel débat fondamental repose la diplomatie des droits de l'homme ?",
    options: ["Sur l'efficacité des sanctions internationales.", "Sur l'opposition entre universalisme des droits et relativisme culturel.", "Sur le financement des institutions internationales.", "Sur la priorité à donner aux droits civils ou sociaux."],
    correctIndex: 1,
    explanation: "Le débat oppose ceux qui affirment l'universalité des droits à ceux qui y voient un relativisme culturel ou un néo-colonialisme.",
  },
  {
    id: 31,
    level: "C1",
    passageType: "Article",
    passage: "Les mouvements de désobéissance civile, de Gandhi à Martin Luther King en passant par les suffragettes, ont contribué à des transformations sociales majeures. Leur efficacité repose sur trois conditions identifiées par les théoriciens : la non-violence, la publicité de l'acte, et l'acceptation des conséquences légales. Ces critères distinguent la désobéissance civile de la simple infraction ou de la résistance violente.",
    question: "Quelles conditions définissent la désobéissance civile selon les théoriciens ?",
    options: ["Violence limitée, clandestinité et refus des conséquences.", "Non-violence, publicité de l'acte et acceptation des conséquences légales.", "Soutien de la majorité, médiatisation et dialogue avec l'État.", "Légitimité historique, soutien international et cohérence idéologique."],
    correctIndex: 1,
    explanation: "La désobéissance civile se définit par la non-violence, le caractère public de l'acte et l'acceptation des conséquences légales.",
  },
  {
    id: 32,
    level: "C2",
    passageType: "Extrait philosophique — Levinas",
    passage: "Pour Emmanuel Levinas, l'éthique précède l'ontologie : avant toute question sur l'être, il y a la rencontre avec le visage de l'autre. Ce visage, dans sa nudité et sa vulnérabilité, m'adresse une injonction absolue : « Tu ne tueras point. » La responsabilité envers l'autre n'est pas choisie — elle est originaire, infinie, asymétrique. Je suis d'emblée responsable de l'autre avant même d'avoir accepté de l'être.",
    question: "Qu'est-ce que le « visage » chez Levinas ?",
    options: ["L'expression physique qui révèle l'intériorité d'une personne.", "La rencontre avec l'autre qui impose une responsabilité éthique infinie et originaire.", "L'identité sociale et culturelle d'un individu.", "Un symbole du dialogue entre cultures."],
    correctIndex: 1,
    explanation: "Le visage chez Levinas est la rencontre avec l'autre dans sa vulnérabilité, qui impose une responsabilité éthique absolue et originaire.",
  },
  {
    id: 33,
    level: "C2",
    passageType: "Article académique",
    passage: "La psychanalyse lacanienne réinterprète Freud à travers la linguistique structurale : l'inconscient est structuré comme un langage. Pour Lacan, le sujet se constitue dans l'ordre symbolique du langage, irréductiblement marqué par le manque et la méconnaissance de lui-même. Le désir est toujours désir de l'Autre, inscrit dans un réseau signifiant qui précède et excède le sujet.",
    question: "Quelle est la thèse centrale de Lacan sur l'inconscient ?",
    options: ["L'inconscient est un réservoir de pulsions biologiques.", "L'inconscient est structuré comme un langage et le sujet se constitue dans l'ordre symbolique.", "L'inconscient est inaccessible à toute forme d'analyse.", "L'inconscient est le produit de traumatismes infantiles refoulés."],
    correctIndex: 1,
    explanation: "Pour Lacan, l'inconscient est structuré comme un langage et le sujet se constitue dans l'ordre symbolique, marqué par le manque.",
  },
  {
    id: 34,
    level: "C2",
    passageType: "Essai",
    passage: "La notion d'espace public, théorisée par Habermas, désigne la sphère de la vie sociale où les citoyens peuvent débattre des affaires communes sur un pied d'égalité. Cet espace, apparu au XVIIIe siècle dans les cafés et gazettes, est aujourd'hui profondément reconfiguré par les réseaux sociaux — à la fois amplificateurs de voix marginalisées et producteurs de chambres d'écho qui fragmentent le débat démocratique.",
    question: "Comment les réseaux sociaux ont-ils reconfiguré l'espace public habermasien ?",
    options: ["Ils ont rendu le débat plus rationnel et informé.", "Ils amplifient des voix marginales mais produisent aussi des chambres d'écho fragmentant le débat.", "Ils ont remplacé les institutions politiques traditionnelles.", "Ils ont uniformisé les opinions à l'échelle mondiale."],
    correctIndex: 1,
    explanation: "Les réseaux sociaux amplifient des voix marginalisées mais fragmentent le débat démocratique par les chambres d'écho.",
  },
  {
    id: 35,
    level: "C2",
    passageType: "Article académique",
    passage: "La notion foucaldienne de dispositif désigne un ensemble hétérogène d'éléments — discours, institutions, lois, pratiques — qui répondent à une urgence historique. Le dispositif est toujours une stratégie de pouvoir-savoir : il produit les sujets qu'il est censé gouverner. Giorgio Agamben a prolongé cette analyse en montrant que les dispositifs modernes ont tendance à produire des sujets de plus en plus incapables d'expérience authentique.",
    question: "Que désigne le « dispositif » chez Foucault ?",
    options: ["Un appareil technique utilisé dans les institutions.", "Un ensemble de discours, institutions et pratiques répondant à une urgence de pouvoir-savoir.", "Un règlement intérieur d'une institution.", "Un mécanisme de contrôle policier."],
    correctIndex: 1,
    explanation: "Le dispositif foucaldien est un ensemble hétérogène (discours, institutions, lois) articulé autour d'une stratégie de pouvoir-savoir.",
  },
  {
    id: 36,
    level: "C2",
    passageType: "Essai",
    passage: "Le contrat social, tel que Rousseau le conçoit dans Du contrat social, n'est pas un événement historique mais un principe normatif : il fonde la légitimité de l'autorité politique dans l'aliénation de la liberté naturelle de chacun au profit d'une volonté générale qui transcende les intérêts particuliers. La volonté générale n'est pas la somme des volontés individuelles — elle est ce que la communauté politique veut en tant que telle.",
    question: "Comment Rousseau distingue-t-il la volonté générale des volontés individuelles ?",
    options: ["La volonté générale est la majorité des volontés individuelles.", "La volonté générale transcende les intérêts particuliers et exprime ce que veut la communauté en tant que telle.", "La volonté générale est imposée par un gouvernement éclairé.", "La volonté générale et les volontés individuelles sont identiques dans une démocratie saine."],
    correctIndex: 1,
    explanation: "La volonté générale n'est pas la somme des volontés individuelles mais ce que la communauté politique veut dans son intérêt commun.",
  },
  {
    id: 37,
    level: "C2",
    passageType: "Article académique",
    passage: "Le translinguisme désigne les pratiques communicatives qui dépassent les frontières des langues individuelles, en mobilisant un répertoire langagier fluide et intégré. Cette conception, développée par Ofelia García et Li Wei, s'oppose à la vision du bilingue comme deux monolingues dans un même cerveau. Le translinguisme est particulièrement pertinent pour comprendre les pratiques des jeunes dans les contextes migratoires.",
    question: "Que remet en cause le concept de translinguisme ?",
    options: ["L'idée que le bilinguisme est une compétence acquise à l'école.", "La vision du bilingue comme deux monolingues séparés dans un même cerveau.", "La nécessité d'apprendre une langue standard.", "L'importance de la langue maternelle dans le développement cognitif."],
    correctIndex: 1,
    explanation: "Le translinguisme s'oppose à l'idée que le bilingue serait deux monolingues séparés, proposant une vision d'un répertoire langagier fluide et intégré.",
  },
  {
    id: 38,
    level: "C2",
    passageType: "Extrait littéraire — Emile Ollivier",
    passage: "L'exil n'est pas seulement la distance géographique qui sépare du pays natal : c'est une fracture dans le temps intérieur, une brisure entre ce que l'on était et ce que l'on est devenu. Ceux qui rentrent au pays ne rentrent pas — ils arrivent dans un lieu qui a continué à vivre sans eux et qu'ils ne reconnaissent plus. L'exil est irréversible non parce qu'on ne peut pas retourner, mais parce que le retour est impossible.",
    question: "Quel paradoxe sur le retour ce texte exprime-t-il ?",
    options: ["Le retour est physiquement dangereux pour les exilés.", "On peut revenir géographiquement mais non retrouver ce qu'on a quitté, car le lieu a changé.", "Le retour est impossible en raison des obstacles politiques.", "Les exilés idéalisent leur pays au point de ne plus vouloir y retourner."],
    correctIndex: 1,
    explanation: "Le retour est impossible non géographiquement mais parce que le lieu et l'être ont changé — on ne revient pas, on arrive dans un pays étranger.",
  },
  {
    id: 39,
    level: "C2",
    passageType: "Article académique",
    passage: "L'économie des tokens, dans les systèmes de monnaie complémentaire locale, illustre comment des communautés peuvent créer leurs propres instruments d'échange pour renforcer l'économie locale et les circuits courts. Ces expériences, des SEL aux monnaies locales comme le Sol Violette, questionnent le monopole étatique sur la monnaie et les fondements philosophiques de la valeur économique.",
    question: "Que questionnent les monnaies locales et complémentaires selon cet article ?",
    options: ["La légitimité des banques commerciales.", "Le monopole étatique sur la monnaie et les fondements de la valeur économique.", "La faisabilité du commerce international.", "La pertinence des politiques monétaires de la BCE."],
    correctIndex: 1,
    explanation: "Les monnaies locales questionnent le monopole étatique sur la monnaie et les fondements philosophiques de la valeur économique.",
  },
];
