import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

export const TCF_LISTENING_P2: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "Météo",
    audioScript: "Bonjour, ici la météo pour aujourd'hui. Il fait beau ce matin, mais cet après-midi il va pleuvoir. Prenez votre parapluie !",
    question: "Quel temps fera-t-il cet après-midi ?",
    options: ["Il fera beau.", "Il va pleuvoir.", "Il va neiger.", "Il y aura du vent."],
    correctIndex: 1,
    explanation: "Le bulletin météo annonce de la pluie pour l'après-midi.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Rendez-vous bancaire",
    audioScript: "Allô, bonjour. Je voudrais prendre un rendez-vous avec un conseiller. Est-ce que lundi à dix heures, c'est possible ? Merci.",
    question: "Pourquoi cette personne appelle-t-elle ?",
    options: ["Pour annuler un rendez-vous.", "Pour prendre un rendez-vous.", "Pour demander un remboursement.", "Pour ouvrir un compte."],
    correctIndex: 1,
    explanation: "La personne appelle pour prendre un rendez-vous avec un conseiller bancaire.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Réservation au restaurant",
    audioScript: "Bonsoir, restaurant Le Jardin. Je voudrais réserver une table pour deux personnes, samedi soir à dix-neuf heures trente. C'est au nom de Dupont.",
    question: "Pour combien de personnes cette réservation est-elle faite ?",
    options: ["Pour une personne.", "Pour deux personnes.", "Pour trois personnes.", "Pour quatre personnes."],
    correctIndex: 1,
    explanation: "La réservation est pour deux personnes, samedi soir.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Objets perdus",
    audioScript: "Excusez-moi, j'ai perdu mon sac rouge dans le bus numéro sept. Il y a mon portefeuille et mes clés dedans. Où est le bureau des objets trouvés ?",
    question: "Qu'est-ce que la personne a perdu ?",
    options: ["Ses lunettes.", "Son téléphone.", "Son sac rouge.", "Son manteau."],
    correctIndex: 2,
    explanation: "La personne a perdu son sac rouge dans le bus numéro 7.",
  },
  {
    id: 5,
    level: "A1",
    topic: "Horaires de bus",
    audioScript: "Le prochain bus pour le centre-ville part à quatorze heures vingt. Le suivant est à quinze heures. Comptez environ vingt minutes de trajet.",
    question: "À quelle heure part le prochain bus pour le centre-ville ?",
    options: ["À 13h20.", "À 14h20.", "À 15h00.", "À 15h20."],
    correctIndex: 1,
    explanation: "Le prochain bus part à 14h20 et le trajet dure environ 20 minutes.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Fête d'anniversaire",
    audioScript: "Salut Thomas ! Je t'invite à ma fête d'anniversaire samedi prochain. On commence à dix-huit heures chez moi. Apporte quelque chose à manger si tu veux, mais ce n'est pas obligatoire.",
    question: "Quelle est l'heure de début de la fête ?",
    options: ["À 16 heures.", "À 17 heures.", "À 18 heures.", "À 19 heures."],
    correctIndex: 2,
    explanation: "La fête commence à dix-huit heures (18h) chez l'hôte.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Pharmacie",
    audioScript: "Bonjour. J'ai une ordonnance de mon médecin. Il m'a prescrit des antibiotiques et un sirop pour la toux. Est-ce que vous avez ces médicaments en stock ?",
    question: "Qu'est-ce que le médecin a prescrit à cette personne ?",
    options: ["Des vitamines et un sirop.", "Des antibiotiques et un sirop.", "Des antibiotiques et des comprimés.", "Un sirop et de la crème."],
    correctIndex: 1,
    explanation: "Le médecin a prescrit des antibiotiques et un sirop pour la toux.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Centre sportif",
    audioScript: "Le centre sportif est ouvert du lundi au samedi, de sept heures à vingt-deux heures. Le dimanche, il ferme à dix-huit heures. L'abonnement mensuel coûte quarante euros.",
    question: "Jusqu'à quelle heure le centre sportif est-il ouvert le dimanche ?",
    options: ["Jusqu'à 17h.", "Jusqu'à 18h.", "Jusqu'à 20h.", "Jusqu'à 22h."],
    correctIndex: 1,
    explanation: "Le dimanche, le centre sportif ferme à dix-huit heures.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Bureau de poste",
    audioScript: "Pour envoyer ce colis en France, il faut compter cinq à sept jours ouvrables. Le tarif est de douze euros cinquante. Voulez-vous un accusé de réception ?",
    question: "Combien de temps faut-il pour envoyer le colis en France ?",
    options: ["Deux à trois jours.", "Cinq à sept jours.", "Une à deux semaines.", "Dix jours exactement."],
    correctIndex: 1,
    explanation: "L'envoi du colis prend cinq à sept jours ouvrables pour atteindre la France.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Épicerie",
    audioScript: "Bonjour madame. Les pommes sont en promotion aujourd'hui, deux kilos pour trois euros. On a aussi du fromage frais qui vient d'arriver ce matin.",
    question: "Quelle est la promotion sur les pommes ?",
    options: ["Un kilo pour deux euros.", "Deux kilos pour trois euros.", "Trois kilos pour cinq euros.", "Un kilo pour un euro."],
    correctIndex: 1,
    explanation: "La promotion est de deux kilos de pommes pour trois euros.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Offre d'emploi",
    audioScript: "Nous recherchons un assistant administratif bilingue français-anglais. Le poste est à temps plein, avec un salaire de départ de deux mille deux cents euros par mois. Les candidats doivent avoir au moins deux ans d'expérience dans un poste similaire. Envoyez votre CV avant le trente novembre.",
    question: "Quelle est la condition principale pour ce poste ?",
    options: ["Avoir un diplôme universitaire.", "Parler trois langues.", "Avoir deux ans d'expérience.", "Habiter en France."],
    correctIndex: 2,
    explanation: "Les candidats doivent avoir au moins deux ans d'expérience dans un poste similaire.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Contrat de location",
    audioScript: "Le contrat de location commence le premier du mois prochain. Le loyer est de huit cent cinquante euros, charges comprises. Le dépôt de garantie équivaut à deux mois de loyer. Vous devez également fournir une assurance habitation avant l'entrée dans les lieux.",
    question: "Que représente le dépôt de garantie ?",
    options: ["Un mois de loyer.", "Deux mois de loyer.", "Trois mois de loyer.", "La moitié du loyer mensuel."],
    correctIndex: 1,
    explanation: "Le dépôt de garantie équivaut à deux mois de loyer.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Réunion de quartier",
    audioScript: "La prochaine réunion de quartier aura lieu jeudi soir à la mairie. Nous discuterons du nouveau projet de parc communautaire et des travaux prévus sur la rue principale. Tous les résidents sont invités à participer et à exprimer leurs opinions.",
    question: "Quel est le sujet principal de la réunion ?",
    options: ["Le budget municipal.", "Les élections locales.", "Le parc communautaire et les travaux.", "La sécurité dans le quartier."],
    correctIndex: 2,
    explanation: "La réunion portera sur le projet de parc communautaire et les travaux de la rue principale.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Assurance maladie",
    audioScript: "Suite à votre demande d'affiliation, nous sommes heureux de vous informer que votre dossier a été accepté. Votre carte Vitale sera envoyée dans les quinze jours. En attendant, conservez précieusement vos feuilles de soins pour être remboursé.",
    question: "Que doit faire la personne en attendant sa carte Vitale ?",
    options: ["Rappeler la caisse d'assurance maladie.", "Payer tous ses soins sans remboursement.", "Garder ses feuilles de soins.", "Aller chercher sa carte au bureau."],
    correctIndex: 2,
    explanation: "La personne doit conserver ses feuilles de soins pour obtenir un remboursement ultérieur.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Orientation professionnelle",
    audioScript: "Dans notre société en mutation, il est essentiel de se reconvertir professionnellement si nécessaire. De nombreux dispositifs existent : le compte formation personnel, les bilans de compétences, ou encore les formations en alternance. N'hésitez pas à consulter un conseiller Pôle emploi pour vous orienter.",
    question: "Qu'est-ce que le compte formation personnel permet de faire ?",
    options: ["Recevoir des allocations chômage.", "Financer une formation professionnelle.", "Obtenir un emploi garanti.", "Payer les charges sociales."],
    correctIndex: 1,
    explanation: "Le compte formation personnel (CPF) permet de financer des formations professionnelles.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Barrière linguistique",
    audioScript: "Beaucoup d'immigrants rencontrent des difficultés liées à la langue dans leur quotidien. Cela peut affecter leur accès aux soins, à l'emploi, et aux services publics. Des associations proposent des cours de français gratuits pour faciliter l'intégration sociale et professionnelle.",
    question: "Comment les associations aident-elles les immigrants face à la barrière linguistique ?",
    options: ["En leur trouvant un emploi.", "En offrant des cours de français gratuits.", "En traduisant tous les documents officiels.", "En les logeant gratuitement."],
    correctIndex: 1,
    explanation: "Des associations proposent des cours de français gratuits pour faciliter l'intégration.",
  },
  {
    id: 17,
    level: "B2",
    topic: "Grève des transports",
    audioScript: "La grève nationale des transports en commun, prévue pour jeudi, devrait perturber les déplacements dans toute la région. Les syndicats revendiquent une hausse des salaires de quatre pour cent et de meilleures conditions de travail. Les usagers sont invités à privilégier le télétravail ou le covoiturage.",
    question: "Quelle est la principale revendication des grévistes ?",
    options: ["Réduire les horaires de travail.", "Obtenir plus de congés payés.", "Augmenter les salaires de 4%.", "Améliorer les équipements."],
    correctIndex: 2,
    explanation: "Les syndicats réclament une hausse des salaires de 4% en plus de meilleures conditions de travail.",
  },
  {
    id: 18,
    level: "B2",
    topic: "Initiative environnementale",
    audioScript: "La ville de Montréal a lancé un programme ambitieux visant à réduire ses émissions de CO₂ de quarante pour cent d'ici deux mille trente. Ce plan inclut l'extension du réseau cyclable, la végétalisation des toits, et la conversion du parc automobile municipal vers l'électrique.",
    question: "Quel est l'objectif de réduction de CO₂ fixé par la ville de Montréal d'ici 2030 ?",
    options: ["20%", "30%", "40%", "50%"],
    correctIndex: 2,
    explanation: "La ville vise une réduction de 40% de ses émissions de CO₂ d'ici 2030.",
  },
  {
    id: 19,
    level: "B2",
    topic: "Engagement civique",
    audioScript: "La participation citoyenne est au cœur du renouveau démocratique. Les assemblées citoyennes tirées au sort, expérimentées en France et en Irlande, montrent que des citoyens ordinaires peuvent produire des recommandations nuancées sur des sujets complexes comme le climat ou la bioéthique.",
    question: "Qu'est-ce qui caractérise les assemblées citoyennes décrites ?",
    options: ["Elles sont composées de politiciens élus.", "Les membres sont volontaires.", "Les membres sont tirés au sort.", "Elles sont réservées aux experts."],
    correctIndex: 2,
    explanation: "Les assemblées citoyennes sont composées de citoyens ordinaires tirés au sort.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Services sociaux",
    audioScript: "Pour bénéficier de l'aide au logement, vous devez déposer un dossier complet auprès de la CAF. Les pièces requises incluent vos trois dernières fiches de paie, votre contrat de bail, et un justificatif d'identité. Le traitement prend généralement trois à quatre semaines.",
    question: "Combien de fiches de paie faut-il fournir pour l'aide au logement ?",
    options: ["Une.", "Deux.", "Trois.", "Six."],
    correctIndex: 2,
    explanation: "Il faut fournir les trois dernières fiches de paie avec le dossier d'aide au logement.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Événement culturel",
    audioScript: "Le Festival de la Francophonie de cette année se tiendra du quinze au vingt-deux octobre. Plus de cinquante artistes venus de vingt pays francophones seront présents. Les billets sont disponibles en ligne ou à l'office de tourisme. Les moins de dix-huit ans bénéficient d'une entrée gratuite.",
    question: "Qui bénéficie de l'entrée gratuite au festival ?",
    options: ["Les seniors de plus de 65 ans.", "Les étudiants.", "Les moins de 18 ans.", "Les membres des associations culturelles."],
    correctIndex: 2,
    explanation: "Les moins de dix-huit ans ont accès gratuitement au Festival de la Francophonie.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Santé mentale",
    audioScript: "Les troubles anxieux touchent environ un Québécois sur cinq au cours de sa vie. Les professionnels de la santé insistent sur l'importance de déstigmatiser la maladie mentale et d'encourager les personnes concernées à consulter un professionnel. Des ressources d'aide sont disponibles vingt-quatre heures sur vingt-quatre.",
    question: "Selon ce reportage, quelle proportion de Québécois souffre de troubles anxieux ?",
    options: ["Un sur dix.", "Un sur cinq.", "Un sur trois.", "Un sur deux."],
    correctIndex: 1,
    explanation: "Environ un Québécois sur cinq souffre de troubles anxieux au cours de sa vie.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Marché locatif",
    audioScript: "La crise du logement au Canada touche particulièrement les grandes villes. À Vancouver et Toronto, les loyers ont augmenté de plus de vingt pour cent en deux ans. Des experts préconisent la construction de logements sociaux et une meilleure réglementation des locations à court terme.",
    question: "Quelle solution préconisent les experts pour la crise du logement ?",
    options: ["Augmenter les impôts fonciers.", "Limiter l'immigration.", "Construire des logements sociaux.", "Interdire les achats immobiliers étrangers."],
    correctIndex: 2,
    explanation: "Les experts recommandent la construction de logements sociaux et une meilleure réglementation.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Semaine de travail",
    audioScript: "Plusieurs entreprises européennes ont testé la semaine de quatre jours sans réduction de salaire. Les résultats sont encourageants : la productivité a maintenu, l'absentéisme a baissé, et le bien-être des employés s'est amélioré. Certains experts restent toutefois sceptiques quant à l'applicabilité universelle de ce modèle.",
    question: "Quel impact la semaine de quatre jours a-t-elle eu sur l'absentéisme ?",
    options: ["Il a augmenté.", "Il n'a pas changé.", "Il a baissé.", "Il a doublé."],
    correctIndex: 2,
    explanation: "L'absentéisme a baissé dans les entreprises ayant testé la semaine de quatre jours.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Réforme scolaire",
    audioScript: "Le ministère de l'Éducation a annoncé une refonte du programme de mathématiques au secondaire. L'accent sera mis sur le raisonnement logique et la résolution de problèmes concrets plutôt que sur la mémorisation de formules. Ces changements entrent en vigueur à la prochaine rentrée scolaire.",
    question: "Sur quoi le nouveau programme de mathématiques met-il l'accent ?",
    options: ["La mémorisation de formules.", "Le calcul mental.", "Le raisonnement logique et la résolution de problèmes.", "L'histoire des mathématiques."],
    correctIndex: 2,
    explanation: "Le nouveau programme privilégie le raisonnement logique et la résolution de problèmes concrets.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    topic: "Philosophie du langage",
    audioScript: "Pour Ludwig Wittgenstein, les limites de mon langage sont les limites de mon monde. Cette formule, tirée du Tractatus, invite à réfléchir sur le rapport intime entre pensée et expression. Si nous ne pouvons penser que ce que notre langue nous permet d'articuler, alors apprendre une nouvelle langue, c'est en quelque sorte étendre notre horizon cognitif.",
    question: "Que signifie l'idée de Wittgenstein selon laquelle « les limites de mon langage sont les limites de mon monde » ?",
    options: ["Le langage ne peut pas exprimer toutes les émotions.", "Notre pensée est structurée par notre langue.", "Certaines langues sont supérieures à d'autres.", "Le multilinguisme est une source de confusion."],
    correctIndex: 1,
    explanation: "Wittgenstein affirme que notre univers mental est délimité par ce que notre langue permet d'articuler.",
  },
  {
    id: 27,
    level: "C1",
    topic: "Politique linguistique au Québec",
    audioScript: "La Loi sur la langue officielle et commune du Québec, adoptée en deux mille vingt-deux, renforce les exigences en matière de francisation dans les entreprises de plus de vingt-cinq employés. Cette législation reflète la volonté de préserver le visage français de la province face à la pression de l'anglais, notamment dans la région métropolitaine de Montréal.",
    question: "À quel type d'entreprises la nouvelle loi linguistique québécoise s'applique-t-elle prioritairement ?",
    options: ["Aux multinationales uniquement.", "Aux entreprises de plus de 25 employés.", "Aux services publics seulement.", "Aux entreprises exportatrices."],
    correctIndex: 1,
    explanation: "La loi cible les entreprises ayant plus de 25 employés, abaissant le seuil par rapport à la législation précédente.",
  },
  {
    id: 28,
    level: "C1",
    topic: "Identité et intégration",
    audioScript: "L'identité des migrants est souvent décrite comme hybride, oscillant entre la culture d'origine et celle du pays d'accueil. Ce que les sociologues nomment l'acculturation sélective permet de comprendre comment des individus adoptent certains éléments de la culture majoritaire tout en préservant des pratiques héritées. Cette navigation identitaire, loin d'être une source de déchirement, peut constituer une véritable ressource.",
    question: "Que signifie l'acculturation sélective selon le passage ?",
    options: ["L'abandon complet de la culture d'origine.", "L'adoption partielle d'éléments de la culture d'accueil.", "Le refus de s'intégrer à la société d'accueil.", "La création d'une culture totalement nouvelle."],
    correctIndex: 1,
    explanation: "L'acculturation sélective désigne l'adoption de certains éléments de la culture majoritaire tout en préservant des pratiques d'origine.",
  },
  {
    id: 29,
    level: "C1",
    topic: "Conférence scientifique",
    audioScript: "Les récentes avancées en neurosciences cognitives révèlent que le cerveau humain possède une plasticité remarquable tout au long de la vie. Contrairement aux croyances antérieures, l'apprentissage ne se cantonne pas à l'enfance : des études longitudinales montrent que l'acquisition de nouvelles langues à l'âge adulte entraîne des modifications structurelles mesurables dans le cortex préfrontal.",
    question: "Quelle idée reçue les neurosciences remettent-elles en question selon cet extrait ?",
    options: ["Que le cerveau adulte ne peut pas apprendre.", "Que les langues se localisent dans l'hémisphère gauche.", "Que l'apprentissage est réservé à l'enfance.", "Que le cortex préfrontal contrôle le langage."],
    correctIndex: 2,
    explanation: "Les études montrent que l'apprentissage des langues est possible à l'âge adulte avec des modifications cérébrales mesurables.",
  },
  {
    id: 30,
    level: "C1",
    topic: "Essai sur l'éducation",
    audioScript: "La pédagogie critique développée par Paulo Freire s'oppose au modèle de l'éducation bancaire, dans lequel le savoir est déposé dans l'esprit de l'élève comme de l'argent dans un coffre. Pour Freire, l'éducation authentique est un acte de connaissance, un processus dialogique qui transforme simultanément l'enseignant et l'apprenant.",
    question: "Que critique Freire dans le modèle de l'éducation bancaire ?",
    options: ["Le coût excessif de l'enseignement.", "La transmission passive du savoir à des élèves récepteurs.", "L'utilisation des nouvelles technologies en classe.", "L'absence de culture générale dans les programmes."],
    correctIndex: 1,
    explanation: "Freire critique le modèle où l'élève est un récepteur passif de connaissances déposées par l'enseignant.",
  },
  {
    id: 31,
    level: "C1",
    topic: "Urbanisme et inégalités",
    audioScript: "La gentrification des centres urbains soulève des questions profondes d'équité spatiale. À Montréal, des quartiers historiquement populaires comme le Plateau ou Rosemont ont subi une transformation démographique et économique qui a chassé les résidents les moins aisés vers la périphérie. Ce phénomène interroge la capacité des villes à maintenir une mixité sociale.",
    question: "Quelle conséquence principale de la gentrification est évoquée ici ?",
    options: ["L'amélioration des transports en commun.", "Le déplacement des résidents modestes vers la périphérie.", "L'augmentation du nombre d'emplois locaux.", "La création de nouveaux espaces verts."],
    correctIndex: 1,
    explanation: "La gentrification entraîne le déplacement des résidents à faibles revenus vers la banlieue.",
  },
  {
    id: 32,
    level: "C2",
    topic: "Théorie politique — Habermas",
    audioScript: "Jürgen Habermas distingue le système — régulé par la logique du marché et de l'État — et le monde vécu, espace de la communication authentique et du consensus normatif. Sa thèse centrale est que la modernité souffre d'une colonisation du monde vécu par les impératifs systémiques, réduisant les individus à des fonctions économiques et administratives au détriment de leur autonomie communicationnelle.",
    question: "Qu'est-ce qu'Habermas entend par la « colonisation du monde vécu » ?",
    options: ["L'expansion géographique des marchés mondiaux.", "L'imposition de la logique marchande et étatique sur les rapports humains.", "La disparition des langues minoritaires.", "L'influence des médias sur l'opinion publique."],
    correctIndex: 1,
    explanation: "Habermas désigne par là l'envahissement des sphères de la vie quotidienne par la logique du marché et de la bureaucratie.",
  },
  {
    id: 33,
    level: "C2",
    topic: "Francophonie nord-américaine",
    audioScript: "L'Acadie, ce territoire imaginaire et politique autant que géographique, incarne la résilience d'un peuple dont la déportation de mille sept cent cinquante-cinq a failli effacer l'existence. La littérature acadienne contemporaine, portée par des auteurs comme France Daigle, interroge les tensions entre la mémoire collective du Grand Dérangement et les aspirations d'une identité post-traumatique ouverte sur la modernité.",
    question: "Qu'est-ce que le Grand Dérangement dans le contexte acadien ?",
    options: ["Un mouvement de résistance militaire.", "La déportation du peuple acadien en 1755.", "Un conflit linguistique avec les anglophones.", "Une crise économique du XVIIIe siècle."],
    correctIndex: 1,
    explanation: "Le Grand Dérangement désigne la déportation des Acadiens par les Britanniques en 1755.",
  },
  {
    id: 34,
    level: "C2",
    topic: "Tocqueville et la démocratie",
    audioScript: "Dans De la démocratie en Amérique, Tocqueville distingue la liberté civile, garantie par les institutions, de ce qu'il nomme le despotisme doux : un régime bienveillant qui, sans tyranniser, enveloppe les citoyens dans un réseau de petites règles compliquées, les rendant incapables d'exercer leur jugement. Cette analyse préfigure les réflexions contemporaines sur le paternalisme étatique.",
    question: "Comment Tocqueville décrit-il le « despotisme doux » ?",
    options: ["Un régime qui opprime par la force.", "Une forme subtile de contrôle qui atrophie le jugement citoyen.", "Un système de lois qui protège les libertés individuelles.", "Un gouvernement corrompu par l'argent."],
    correctIndex: 1,
    explanation: "Le despotisme doux est une forme de tutelle bienveillante qui affaiblit l'autonomie des citoyens sans les contraindre ouvertement.",
  },
  {
    id: 35,
    level: "C2",
    topic: "Économie de l'immigration",
    audioScript: "Les travaux économétriques de George Borjas et de David Card illustrent un débat fondamental : l'immigration augmente-t-elle le chômage des natifs ou stimule-t-elle la croissance globale ? Card, lauréat du prix Nobel, montre que les effets négatifs sur les salaires sont quasi inexistants, tandis que Borjas, en segmentant le marché du travail, identifie des impacts différenciés selon le niveau de qualification.",
    question: "Sur quoi porte le désaccord principal entre Borjas et Card ?",
    options: ["Sur la vitesse d'intégration des immigrants.", "Sur l'impact de l'immigration sur les salaires et l'emploi des natifs.", "Sur les politiques de naturalisation.", "Sur le rôle de l'immigration dans le vieillissement démographique."],
    correctIndex: 1,
    explanation: "Le débat entre Borjas et Card porte sur les effets de l'immigration sur le marché du travail et les salaires des natifs.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Intelligence artificielle et droit d'auteur",
    audioScript: "L'émergence des grands modèles de langage soulève des questions inédites en matière de propriété intellectuelle. Lorsqu'un système d'IA génère un texte à partir d'un corpus protégé, s'agit-il d'une transformation créative au sens du droit ou d'une forme de reproduction non autorisée ? Les tribunaux américains et européens commencent à se prononcer, mais le cadre juridique reste profondément lacunaire.",
    question: "Quel est le défi juridique principal posé par les IA génératives selon cet extrait ?",
    options: ["La responsabilité des développeurs en cas de préjudice.", "La question de la paternité des textes générés.", "L'utilisation de corpus protégés pour l'entraînement des modèles.", "La fiscalité des entreprises technologiques."],
    correctIndex: 2,
    explanation: "La question centrale est de savoir si l'entraînement sur des corpus protégés constitue une violation des droits d'auteur.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Révolution tranquille",
    audioScript: "La Révolution tranquille au Québec, amorcée avec l'élection du gouvernement Lesage en mille neuf cent soixante, représente une rupture décisive avec le cléricalisme duplessiste. En nationalisant Hydro-Québec, en créant un réseau d'éducation publique laïc et en professionnalisant la fonction publique, le Québec est passé d'une société traditionnelle à une modernité assumée en moins d'une décennie.",
    question: "Quelle nationalisation symbolise la Révolution tranquille ?",
    options: ["La nationalisation des chemins de fer.", "La nationalisation d'Hydro-Québec.", "La nationalisation des banques.", "La nationalisation de l'industrie forestière."],
    correctIndex: 1,
    explanation: "La nationalisation d'Hydro-Québec est l'une des mesures phares de la Révolution tranquille sous Lesage.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Bourdieu et le capital symbolique",
    audioScript: "Pierre Bourdieu a montré que les inégalités sociales se reproduisent non seulement par la transmission du capital économique, mais aussi via le capital symbolique : prestige, reconnaissance, légitimité culturelle. Dans le champ linguistique, les locuteurs dotés d'un accent légitime ou d'une maîtrise de la langue soutenue bénéficient d'une autorité symbolique qui renforce leur position sociale.",
    question: "Comment le capital symbolique contribue-t-il à la reproduction des inégalités selon Bourdieu ?",
    options: ["En donnant accès aux ressources matérielles.", "En conférant une autorité et une légitimité qui renforcent les positions sociales.", "En permettant la mobilité géographique.", "En favorisant l'accès à l'éducation formelle."],
    correctIndex: 1,
    explanation: "Le capital symbolique opère en accordant prestige et légitimité à certains individus, ce qui consolide leur domination sociale.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Francophonie internationale",
    audioScript: "L'Organisation internationale de la Francophonie regroupe quatre-vingt-huit États et gouvernements, représentant plus de trois cents millions de locuteurs. Pourtant, la vitalité du français sur la scène internationale fait l'objet de débats : si la démographie africaine promet une expansion numérique considérable, la question de la qualité et du statut du français comme langue scientifique de premier rang reste posée face à la domination de l'anglais.",
    question: "Quelle tension centrale est évoquée concernant l'avenir du français dans le monde ?",
    options: ["Entre le français parlé et le français écrit.", "Entre expansion démographique en Afrique et statut scientifique face à l'anglais.", "Entre les pays fondateurs et les nouveaux membres.", "Entre le français standard et les créoles."],
    correctIndex: 1,
    explanation: "L'extrait oppose l'essor démographique du français en Afrique à la question de son rayonnement scientifique face à l'anglais.",
  },
];
