import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

export const TCF_LISTENING_P3: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "Annonce d'aéroport",
    audioScript: "Attention passagers. Le vol Air France deux cent quarante à destination de Paris est maintenant en embarquement à la porte dix-sept. Présentez votre carte d'embarquement et votre passeport.",
    question: "À quelle porte se fait l'embarquement du vol pour Paris ?",
    options: ["Porte 7.", "Porte 14.", "Porte 17.", "Porte 27."],
    correctIndex: 2,
    explanation: "L'annonce indique l'embarquement à la porte 17 pour Paris.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Commande au café",
    audioScript: "Bonjour monsieur. Je voudrais un café crème et un croissant, s'il vous plaît. C'est combien ? Cinq euros vingt ? Voilà, merci.",
    question: "Qu'est-ce que le client commande ?",
    options: ["Un café et un pain au chocolat.", "Un thé et un croissant.", "Un café crème et un croissant.", "Un cappuccino et une brioche."],
    correctIndex: 2,
    explanation: "Le client commande un café crème et un croissant pour 5,20 euros.",
  },
  {
    id: 3,
    level: "A1",
    topic: "Demande d'adresse",
    audioScript: "Excusez-moi. Je cherche la bibliothèque municipale. Vous allez tout droit, vous tournez à gauche au feu, et c'est le grand bâtiment gris sur votre droite.",
    question: "Où se trouve la bibliothèque municipale ?",
    options: ["À droite du feu.", "À gauche tout de suite.", "Tout droit puis à gauche au feu, sur la droite.", "Derrière la mairie."],
    correctIndex: 2,
    explanation: "Il faut aller tout droit, tourner à gauche au feu, et la bibliothèque est le grand bâtiment gris à droite.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Hôtel — réservation",
    audioScript: "Bonjour. J'ai une réservation pour trois nuits, du vingt au vingt-trois mars. C'est au nom de Martin, chambre double.",
    question: "Combien de nuits dure la réservation ?",
    options: ["Deux nuits.", "Trois nuits.", "Quatre nuits.", "Cinq nuits."],
    correctIndex: 1,
    explanation: "La réservation est pour trois nuits, du 20 au 23 mars.",
  },
  {
    id: 5,
    level: "A1",
    topic: "Message vocal",
    audioScript: "Bonjour, c'est Élodie. Je serai en retard ce soir, j'arrive vers vingt heures au lieu de dix-neuf heures. Tu peux commencer à dîner sans moi. À tout à l'heure !",
    question: "À quelle heure Élodie va-t-elle arriver ?",
    options: ["À 18h.", "À 19h.", "À 20h.", "À 21h."],
    correctIndex: 2,
    explanation: "Élodie arrivera vers 20h au lieu de 19h.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Location de voiture",
    audioScript: "Pour louer une voiture, vous devez avoir au moins vingt et un ans, un permis de conduire valide depuis au moins un an, et une carte de crédit. Le tarif journalier est de trente-cinq euros, assurance comprise.",
    question: "Quel âge minimum faut-il avoir pour louer une voiture ?",
    options: ["18 ans.", "19 ans.", "21 ans.", "25 ans."],
    correctIndex: 2,
    explanation: "Il faut avoir au minimum 21 ans pour louer une voiture avec ce service.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Programme de télévision",
    audioScript: "Ce soir sur France Deux : à vingt heures, le journal télévisé ; à vingt heures quarante-cinq, un documentaire sur la faune arctique ; et à vingt-deux heures trente, un film policier avec Isabelle Adjani.",
    question: "À quelle heure commence le documentaire sur la faune arctique ?",
    options: ["À 20h.", "À 20h30.", "À 20h45.", "À 22h30."],
    correctIndex: 2,
    explanation: "Le documentaire sur la faune arctique commence à 20h45 sur France Deux.",
  },
  {
    id: 8,
    level: "A2",
    topic: "École — permission de sortie",
    audioScript: "Monsieur et Madame Lefebvre, votre fils Antoine participera à une sortie scolaire au musée des sciences le jeudi douze novembre. Le coût est de douze euros. Veuillez signer et retourner ce formulaire avant le cinq novembre.",
    question: "Quelle est la date limite pour retourner le formulaire signé ?",
    options: ["Le 5 novembre.", "Le 7 novembre.", "Le 12 novembre.", "Le 15 novembre."],
    correctIndex: 0,
    explanation: "Il faut retourner le formulaire signé avant le 5 novembre.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Marché local",
    audioScript: "Le marché du village a lieu tous les dimanches matin de huit heures à treize heures. On y trouve des fruits et légumes frais, du fromage artisanal, et du miel local. L'entrée est gratuite.",
    question: "Quand a lieu le marché du village ?",
    options: ["Le samedi matin.", "Le dimanche matin.", "Le jeudi et dimanche.", "Tous les jours matin."],
    correctIndex: 1,
    explanation: "Le marché a lieu le dimanche matin de 8h à 13h.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Cours de langue",
    audioScript: "Notre école propose des cours de français intensifs pour débutants et intermédiaires. Les cours ont lieu le lundi, mercredi et vendredi matin de neuf heures à douze heures. L'inscription coûte cent quatre-vingt euros par mois.",
    question: "Quels jours ont lieu les cours de français ?",
    options: ["Lundi, mardi et jeudi.", "Mardi, jeudi et samedi.", "Lundi, mercredi et vendredi.", "Tous les jours de la semaine."],
    correctIndex: 2,
    explanation: "Les cours ont lieu le lundi, mercredi et vendredi matin.",
  },

  // ── B1–B2 (Q11–25) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Entretien d'embauche",
    audioScript: "Lors d'un entretien d'embauche, il est important de se préparer en amont. Renseignez-vous sur l'entreprise, anticipez les questions classiques comme vos points forts et vos points faibles, et préparez des exemples concrets tirés de vos expériences professionnelles. N'oubliez pas : la première impression est souvent déterminante.",
    question: "Que conseille-t-on de faire avant un entretien d'embauche ?",
    options: ["Mémoriser son CV mot pour mot.", "Se renseigner sur l'entreprise et préparer des exemples.", "Arriver avec des recommandations de collègues.", "Demander le salaire dès le début."],
    correctIndex: 1,
    explanation: "Il est recommandé de se renseigner sur l'entreprise et de préparer des exemples concrets de ses expériences.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Bénévolat",
    audioScript: "Notre association cherche des bénévoles pour accompagner des personnes âgées lors de sorties culturelles le week-end. Aucune formation spécifique n'est requise, mais un sens de l'écoute et de la patience sont indispensables. Pour vous inscrire, contactez notre coordinatrice Marie-Hélène.",
    question: "Quelles qualités sont indispensables pour ce bénévolat ?",
    options: ["Une formation médicale et la conduite.", "L'écoute et la patience.", "La maîtrise d'une langue étrangère.", "Des compétences en informatique."],
    correctIndex: 1,
    explanation: "Les qualités requises pour cet accompagnement bénévole sont l'écoute et la patience.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Transport durable",
    audioScript: "La ville a inauguré un nouveau système de vélos en libre-service avec trois cents stations réparties dans tout l'agglomération. L'abonnement annuel est de vingt-neuf euros. Ce projet s'inscrit dans la stratégie municipale de réduction des émissions de gaz à effet de serre de trente pour cent d'ici deux mille trente.",
    question: "Quel est l'objectif environnemental de ce projet selon la ville ?",
    options: ["Éliminer totalement les voitures.", "Réduire les émissions de GES de 30% d'ici 2030.", "Doubler le nombre de pistes cyclables.", "Fermer le centre-ville aux véhicules."],
    correctIndex: 1,
    explanation: "Ce projet vise à réduire les émissions de gaz à effet de serre de 30% d'ici 2030.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Alimentation équilibrée",
    audioScript: "Les nutritionnistes recommandent de consommer au moins cinq portions de fruits et légumes par jour. Il est également conseillé de limiter les aliments ultra-transformés, riches en sucres ajoutés et en graisses saturées. Une alimentation variée et équilibrée contribue à prévenir les maladies cardiovasculaires et le diabète de type deux.",
    question: "Que préviennent une alimentation variée et équilibrée selon les nutritionnistes ?",
    options: ["Les maladies respiratoires.", "Les maladies cardiovasculaires et le diabète.", "Les maladies infectieuses.", "Les troubles musculaires."],
    correctIndex: 1,
    explanation: "Une alimentation équilibrée aide à prévenir les maladies cardiovasculaires et le diabète de type 2.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Logement étudiant",
    audioScript: "Les Cités Universitaires proposent des chambres à tarif modéré pour les étudiants boursiers. Pour faire une demande, vous devez vous connecter au portail de votre université avant le quinze avril. Les résultats d'attribution sont communiqués en juillet. Les places sont limitées et les critères sociaux sont prioritaires.",
    question: "Quelle est la date limite pour demander un logement en Cité Universitaire ?",
    options: ["Le 1er avril.", "Le 15 avril.", "Le 1er mai.", "Le 15 juillet."],
    correctIndex: 1,
    explanation: "Les demandes de logement universitaire doivent être déposées avant le 15 avril.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Médiation culturelle",
    audioScript: "Les médiateurs culturels jouent un rôle essentiel dans les musées et les centres culturels. Ils rendent les œuvres accessibles à tous les publics, notamment aux personnes éloignées de la culture. Leur mission est de créer du lien entre le patrimoine artistique et les visiteurs, quel que soit leur niveau de connaissance.",
    question: "Quel est le rôle principal des médiateurs culturels ?",
    options: ["Vendre des billets d'entrée.", "Sécuriser les œuvres d'art.", "Rendre les œuvres accessibles à tous.", "Former les artistes en résidence."],
    correctIndex: 2,
    explanation: "Les médiateurs culturels ont pour mission de rendre les œuvres accessibles à tous les publics.",
  },
  {
    id: 17,
    level: "B2",
    topic: "Inégalités numériques",
    audioScript: "La fracture numérique ne se résume plus à l'accès à internet mais s'étend aux compétences pour utiliser les outils numériques de manière efficace. Des études montrent que les personnes âgées, les peu qualifiés et les habitants de zones rurales sont les plus touchés. Cette exclusion numérique aggrave les inégalités sociales préexistantes.",
    question: "Comment la fracture numérique est-elle définie dans ce reportage ?",
    options: ["Uniquement comme un manque d'accès à internet.", "Comme un problème touchant seulement les zones rurales.", "Comme une exclusion qui dépasse l'accès et inclut les compétences.", "Comme un problème propre aux pays en développement."],
    correctIndex: 2,
    explanation: "La fracture numérique englobe à la fois l'accès et les compétences nécessaires pour utiliser les outils numériques.",
  },
  {
    id: 18,
    level: "B2",
    topic: "Tourisme responsable",
    audioScript: "Le tourisme de masse menace les écosystèmes fragiles et les cultures locales. Des initiatives de tourisme responsable encouragent les voyageurs à séjourner plus longtemps dans moins de destinations, à consommer local, et à respecter les modes de vie des communautés visitées. Certains pays ont même instauré des quotas de visiteurs pour préserver leur patrimoine naturel.",
    question: "Que recommande le tourisme responsable aux voyageurs ?",
    options: ["Visiter un maximum de pays en peu de temps.", "Séjourner plus longtemps dans moins d'endroits et consommer local.", "Éviter les pays fragiles écologiquement.", "Préférer les hôtels de luxe pour soutenir l'économie locale."],
    correctIndex: 1,
    explanation: "Le tourisme responsable recommande de rester plus longtemps dans moins de destinations et de consommer localement.",
  },
  {
    id: 19,
    level: "B2",
    topic: "Mentorat professionnel",
    audioScript: "Le mentorat constitue un levier puissant d'insertion professionnelle pour les jeunes issus de milieux défavorisés. En mettant en relation un professionnel expérimenté avec un jeune en début de parcours, le programme permet de transmettre non seulement des compétences techniques mais aussi le capital social et les codes informels du monde du travail.",
    question: "Quel avantage particulier le mentorat apporte-t-il aux jeunes défavorisés ?",
    options: ["Un accès direct à un emploi garanti.", "L'acquisition de diplômes reconnus.", "Le transfert de compétences et de codes sociaux du monde du travail.", "Un soutien financier pendant les études."],
    correctIndex: 2,
    explanation: "Le mentorat transmet à la fois des compétences techniques et le capital social nécessaire à l'intégration professionnelle.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Réforme de la retraite",
    audioScript: "La réforme des retraites proposée par le gouvernement vise à repousser l'âge légal de départ de soixante-deux à soixante-quatre ans. Les opposants font valoir que cette mesure pénalise les travailleurs aux carrières longues et les emplois pénibles. Les syndicats ont appelé à des mobilisations nationales.",
    question: "Que reprochent les opposants à la réforme des retraites ?",
    options: ["Elle augmente les cotisations de manière disproportionnée.", "Elle pénalise ceux qui ont commencé à travailler tôt et ceux aux emplois pénibles.", "Elle favorise les fonctionnaires au détriment du secteur privé.", "Elle supprime les régimes spéciaux sans compensation."],
    correctIndex: 1,
    explanation: "Les opposants estiment que la réforme pénalise les travailleurs à carrière longue et ceux exerçant des métiers pénibles.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Économie circulaire",
    audioScript: "L'économie circulaire cherche à rompre avec le modèle linéaire produire-utiliser-jeter. Elle repose sur la réutilisation, la réparation, et le recyclage des produits. Certaines entreprises innovantes ont développé des modèles économiques fondés non pas sur la vente de biens mais sur leur location ou leur usage mutualisé.",
    question: "Qu'est-ce qui distingue fondamentalement l'économie circulaire du modèle linéaire ?",
    options: ["Elle privilégie la production locale.", "Elle élimine la notion de déchet en favorisant la réutilisation et le recyclage.", "Elle réduit le nombre de produits disponibles.", "Elle interdit l'importation de produits étrangers."],
    correctIndex: 1,
    explanation: "L'économie circulaire rompt avec le modèle linéaire en prolongeant la vie des produits via réutilisation, réparation et recyclage.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Sécurité alimentaire",
    audioScript: "La sécurité alimentaire mondiale est menacée par la convergence de plusieurs crises : changement climatique, conflits armés, effondrement de la biodiversité et volatilité des prix des matières premières. La FAO estime que huit cent millions de personnes souffrent de sous-alimentation chronique dans le monde.",
    question: "Combien de personnes souffrent de sous-alimentation chronique selon la FAO ?",
    options: ["400 millions.", "600 millions.", "800 millions.", "Un milliard."],
    correctIndex: 2,
    explanation: "La FAO estime que 800 millions de personnes souffrent de sous-alimentation chronique dans le monde.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Réseaux sociaux et adolescents",
    audioScript: "Une étude publiée dans The Lancet établit un lien entre l'utilisation intensive des réseaux sociaux et la dégradation de la santé mentale des adolescentes. Les chercheurs soulignent que l'exposition aux images idéalisées et au cyberharcèlement amplifie les troubles anxieux et dépressifs chez les jeunes filles.",
    question: "Quel lien cette étude établit-elle entre réseaux sociaux et santé mentale ?",
    options: ["Elle montre que les réseaux sociaux améliorent la confiance en soi.", "Elle établit un lien entre leur usage intensif et des troubles mentaux chez les adolescentes.", "Elle indique que les adolescents utilisent les réseaux pour s'entraider.", "Elle ne conclut pas de causalité directe."],
    correctIndex: 1,
    explanation: "L'étude lie l'usage intensif des réseaux sociaux à des troubles anxieux et dépressifs chez les adolescentes.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Accès à la culture",
    audioScript: "Le « pass culture » mis en place pour les jeunes de dix-huit ans permet de bénéficier de trois cents euros à dépenser dans des activités culturelles : cinéma, concerts, livres, théâtre ou musées. L'objectif est de démocratiser l'accès à la culture et de réduire les inégalités liées à l'origine sociale.",
    question: "Quel est l'objectif principal du pass culture selon ce reportage ?",
    options: ["Soutenir financièrement les artistes.", "Démocratiser l'accès à la culture pour les jeunes.", "Remplacer les subventions aux institutions culturelles.", "Encourager le tourisme culturel."],
    correctIndex: 1,
    explanation: "Le pass culture vise à démocratiser l'accès à la culture en réduisant les inégalités liées à l'origine sociale.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Télémédecine",
    audioScript: "La téléconsultation médicale a connu un essor considérable depuis la pandémie. Elle permet de réduire les délais d'attente, particulièrement dans les zones sous-médicalisées dites déserts médicaux. Cependant, certains praticiens soulignent ses limites pour les examens cliniques qui nécessitent une présence physique.",
    question: "Quelle limite est mentionnée concernant la téléconsultation ?",
    options: ["Elle est trop coûteuse pour les patients.", "Elle ne peut pas remplacer l'examen clinique physique.", "Elle n'est pas remboursée par l'assurance maladie.", "Elle est réservée aux grandes villes."],
    correctIndex: 1,
    explanation: "La téléconsultation est limitée pour les examens cliniques qui requièrent une présence physique.",
  },

  // ── C1–C2 (Q26–39) ─────────────────────────────────────────────
  {
    id: 26,
    level: "C1",
    topic: "Neurolinguistique",
    audioScript: "Les recherches en neurolinguistique ont mis en évidence que les locuteurs bilingues précoces, ayant acquis deux langues simultanément avant l'âge de cinq ans, activent les mêmes zones cérébrales pour les deux langues. En revanche, les bilingues tardifs présentent des activations distinctes, le cerveau traitant la langue seconde dans des régions légèrement différentes du cortex frontal inférieur.",
    question: "Quelle est la différence entre bilingues précoces et tardifs selon les neurosciences ?",
    options: ["Les bilingues précoces apprennent plus vite.", "Les bilingues tardifs sont plus créatifs.", "Les bilingues précoces activent les mêmes zones pour les deux langues ; les tardifs activent des zones distinctes.", "Les bilingues tardifs ont un meilleur vocabulaire."],
    correctIndex: 2,
    explanation: "Les bilingues précoces utilisent les mêmes zones cérébrales pour les deux langues, contrairement aux bilingues tardifs.",
  },
  {
    id: 27,
    level: "C1",
    topic: "Droit et numérique",
    audioScript: "Le Règlement général sur la protection des données, entré en vigueur en deux mille dix-huit, a transformé la relation entre les entreprises et les données personnelles de leurs utilisateurs. Il impose notamment un droit à l'oubli, un droit d'accès et de rectification, et des obligations de transparence sur l'utilisation des données. Les violations peuvent entraîner des amendes pouvant aller jusqu'à quatre pour cent du chiffre d'affaires mondial.",
    question: "Quel droit le RGPD accorde-t-il aux individus concernant leurs données personnelles ?",
    options: ["Le droit de contrôler les prix des services numériques.", "Le droit à l'oubli, d'accès et de rectification.", "Le droit d'interdire toute collecte de données.", "Le droit à une compensation financière systématique."],
    correctIndex: 1,
    explanation: "Le RGPD consacre notamment le droit à l'oubli, le droit d'accès et la rectification des données personnelles.",
  },
  {
    id: 28,
    level: "C1",
    topic: "Sociologie de la migration",
    audioScript: "Les théories néoclassiques de la migration postulent que les individus migrent rationnellement en évaluant le différentiel de revenus entre pays d'origine et pays de destination. La nouvelle économie des migrations remet en question cette approche individualiste en soulignant le rôle des décisions familiales et des stratégies collectives dans les trajectoires migratoires.",
    question: "Sur quoi la nouvelle économie des migrations insiste-t-elle, contrairement aux théories néoclassiques ?",
    options: ["Sur la contribution économique des migrants.", "Sur les décisions collectives et familiales plutôt qu'individuelles.", "Sur l'importance des politiques d'accueil.", "Sur les obstacles administratifs à la migration."],
    correctIndex: 1,
    explanation: "La nouvelle économie des migrations met en avant les stratégies familiales et collectives, dépassant l'approche individuelle néoclassique.",
  },
  {
    id: 29,
    level: "C1",
    topic: "Littérature africaine francophone",
    audioScript: "La littérature africaine d'expression française a connu une évolution remarquable depuis les pionniers de la Négritude comme Senghor et Césaire. Les voix contemporaines, de Léonora Miano à Alain Mabanckou, explorent la complexité des identités postcoloniales, le rapport à la mémoire collective, et la violence ordinaire des sociétés africaines, sans chercher à répondre aux attentes exotiques d'un lectorat occidental.",
    question: "Que caractérise la littérature africaine francophone contemporaine selon cet extrait ?",
    options: ["Elle célèbre les traditions africaines précoloniales.", "Elle explore les identités postcoloniales sans chercher à satisfaire les attentes occidentales.", "Elle est principalement produite par des auteurs vivant en Afrique.", "Elle s'inspire exclusivement de la Négritude."],
    correctIndex: 1,
    explanation: "La littérature africaine contemporaine interroge les identités postcoloniales de manière autonome, sans répondre aux attentes exotiques occidentales.",
  },
  {
    id: 30,
    level: "C1",
    topic: "Philosophie morale — Rawls",
    audioScript: "John Rawls propose dans sa Théorie de la justice une expérience de pensée fondatrice : le voile d'ignorance. Placés derrière ce voile, les individus ignorent leur position dans la société, leurs talents, et leurs préférences. Rawls postule que dans cette situation, ils choisiraient des principes de justice qui protègent les plus défavorisés, car ils ne savent pas s'ils en feront partie.",
    question: "Quel est le principe fondamental du voile d'ignorance de Rawls ?",
    options: ["Les individus doivent ignorer l'histoire pour penser l'avenir.", "Ne pas connaître sa position sociale conduit à choisir des principes protégeant les plus défavorisés.", "La justice est relative à chaque culture.", "L'équité nécessite une égalité absolue des conditions."],
    correctIndex: 1,
    explanation: "Le voile d'ignorance amène les individus à choisir des principes protégeant les défavorisés, ignorant leur future position sociale.",
  },
  {
    id: 31,
    level: "C1",
    topic: "Changement climatique et justice",
    audioScript: "La notion de justice climatique reconnaît que les pays les plus vulnérables aux effets du changement climatique sont souvent ceux qui ont le moins contribué aux émissions historiques de gaz à effet de serre. Cette asymétrie entre responsabilité et vulnérabilité est au cœur des négociations internationales, notamment sur les mécanismes de compensation des pays en développement.",
    question: "Quelle asymétrie la justice climatique cherche-t-elle à corriger ?",
    options: ["Entre les pays riches et les entreprises polluantes.", "Entre les plus vulnérables au changement climatique et ceux qui en sont les plus responsables.", "Entre les générations actuelles et futures.", "Entre les émissions industrielles et agricoles."],
    correctIndex: 1,
    explanation: "La justice climatique vise à corriger l'asymétrie entre les pays très vulnérables au changement climatique mais peu responsables des émissions historiques.",
  },
  {
    id: 32,
    level: "C2",
    topic: "Épistémologie — vérité et science",
    audioScript: "Karl Popper proposait de distinguer la science de la pseudo-science par le critère de réfutabilité : une théorie est scientifique si elle peut en principe être infirmée par l'expérience. Cette conception du falsificationnisme a profondément influencé la philosophie des sciences, bien que des épistémologues comme Thomas Kuhn aient montré que les révolutions scientifiques s'opèrent rarement par simple réfutation mais par ruptures paradigmatiques.",
    question: "Que distingue le critère de réfutabilité de Popper ?",
    options: ["Les théories vraies des théories fausses.", "La science de la pseudo-science.", "Les sciences dures des sciences humaines.", "Les faits des interprétations."],
    correctIndex: 1,
    explanation: "Pour Popper, une théorie est scientifique si elle peut être infirmée par l'expérience — ce critère distingue la science de la pseudo-science.",
  },
  {
    id: 33,
    level: "C2",
    topic: "Politique linguistique comparée",
    audioScript: "Les modèles de gestion du plurilinguisme varient considérablement : la Suisse a opté pour un fédéralisme territorial assignant une langue à chaque canton, tandis que le Canada a développé un bilinguisme officiel institutionnel. L'Inde, avec ses vingt-deux langues officielles, illustre une troisième voie. Ces choix reflètent des philosophies politiques profondes sur les droits collectifs et individuels.",
    question: "Qu'illustre le modèle suisse de gestion du plurilinguisme ?",
    options: ["Un bilinguisme institutionnel à l'échelle nationale.", "Un fédéralisme territorial associant une langue à chaque canton.", "Un multilinguisme sans politique officielle.", "Un système de traduction universelle."],
    correctIndex: 1,
    explanation: "La Suisse pratique un fédéralisme territorial où chaque canton est associé à une langue officielle.",
  },
  {
    id: 34,
    level: "C2",
    topic: "Théorie critique de l'École de Francfort",
    audioScript: "L'industrie culturelle, concept forgé par Adorno et Horkheimer dans la Dialectique de la Raison, désigne la soumission de la production culturelle aux logiques marchandes et à la standardisation. Elle ne produit pas seulement des divertissements mais fabrique une docilité sociale, habituant les consommateurs à des formats prévisibles qui étouffent la pensée critique et le désir d'émancipation.",
    question: "Quelle est la thèse principale d'Adorno et Horkheimer sur l'industrie culturelle ?",
    options: ["La culture populaire est supérieure à la culture élitiste.", "La standardisation culturelle engendre une docilité sociale et étouffe la pensée critique.", "L'industrie culturelle améliore l'accès de tous à la culture.", "La culture de masse stimule l'imagination des individus."],
    correctIndex: 1,
    explanation: "Pour Adorno et Horkheimer, l'industrie culturelle marchandise la culture et produit de la conformité sociale en inhibant la pensée critique.",
  },
  {
    id: 35,
    level: "C2",
    topic: "Démocratie délibérative",
    audioScript: "La démocratie délibérative, théorisée notamment par Habermas et Amy Gutmann, postule que la légitimité politique découle non du simple agrégat des préférences individuelles comme dans les modèles électoraux classiques, mais de la qualité des délibérations publiques. Des citoyens informés, capables d'écouter des arguments contraires et de réviser leurs positions, sont la condition d'une démocratie authentique.",
    question: "Qu'est-ce qui fonde la légitimité politique dans la démocratie délibérative ?",
    options: ["La majorité absolue des voix.", "La qualité des délibérations publiques et la capacité à réviser ses positions.", "La compétence technique des gouvernants.", "L'accord unanime de tous les citoyens."],
    correctIndex: 1,
    explanation: "La légitimité délibérative repose sur la qualité du débat public et la capacité des citoyens à s'informer et à reconsidérer leurs positions.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Biodiversité et extinction",
    audioScript: "Les scientifiques parlent d'une sixième extinction de masse, provoquée non par un astéroïde mais par l'activité humaine : destruction des habitats, surexploitation des ressources, pollution et changement climatique. Le rythme actuel d'extinction des espèces est estimé cent à mille fois supérieur au rythme naturel. Cette crise silencieuse menace les services écosystémiques dont dépend notre civilisation.",
    question: "Qu'est-ce qui distingue la sixième extinction de masse des précédentes ?",
    options: ["Elle est plus rapide que toutes les précédentes.", "Elle est causée par l'activité humaine plutôt que par des phénomènes naturels.", "Elle touche uniquement les espèces marines.", "Elle est réversible grâce à la technologie."],
    correctIndex: 1,
    explanation: "La sixième extinction est unique car elle est provoquée par l'activité humaine, pas par des causes naturelles comme les extinctions précédentes.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Postcolonialisme et mémoire",
    audioScript: "Les études postcoloniales, initiées par des penseurs comme Edward Saïd, Homi Bhabha et Gayatri Spivak, interrogent les persistances symboliques du colonialisme dans les structures de pouvoir contemporaines, les représentations culturelles et les epistémologies dominantes. La question du subalterne — qui peut parler, comment, et depuis quelle position — reste centrale dans ce champ intellectuel.",
    question: "Quelle question fondamentale posent les études postcoloniales selon cet extrait ?",
    options: ["Comment accélérer le développement économique des anciennes colonies ?", "Qui peut parler, comment, et depuis quelle position sociale et culturelle ?", "Faut-il des réparations financières pour la colonisation ?", "Comment préserver les cultures indigènes menacées ?"],
    correctIndex: 1,
    explanation: "Les études postcoloniales questionnent qui a la légitimité de la parole et depuis quelle position — la question du subalterne.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Bioéthique — intelligence artificielle médicale",
    audioScript: "L'utilisation des algorithmes d'intelligence artificielle dans le diagnostic médical soulève des enjeux bioéthiques majeurs : le consentement éclairé du patient, la responsabilité juridique en cas d'erreur, et le risque de perpétuation des biais discriminatoires présents dans les données d'entraînement. Un algorithme entraîné sur des données sous-représentant certaines populations peut reproduire et amplifier des inégalités médicales.",
    question: "Quel risque spécifique lié aux données d'entraînement est mentionné ?",
    options: ["La divulgation de données privées des patients.", "La reproduction de discriminations si certaines populations sont sous-représentées.", "Un coût de déploiement trop élevé.", "Un rejet par les médecins traditionnels."],
    correctIndex: 1,
    explanation: "Un algorithme entraîné sur des données non représentatives peut perpétuer et amplifier des inégalités médicales existantes.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Paradoxe de la tolérance",
    audioScript: "Karl Popper a formulé le paradoxe de la tolérance : une société tolérante doit être intolérante envers l'intolérance. Si elle tolère sans limites les manifestations intolérantes, elle finit par être détruite. Mais les démocraties contemporaines peinent à tracer cette ligne, craignant que restreindre certaines formes d'expression ne constitue elle-même une atteinte aux libertés fondamentales.",
    question: "En quoi consiste le paradoxe de la tolérance selon Popper ?",
    options: ["La tolérance est impossible dans une société plurielle.", "Une société trop tolérante pourrait être détruite par l'intolérance qu'elle tolère.", "La démocratie ne peut survivre qu'en imposant ses valeurs.", "La liberté d'expression doit être absolue pour être authentique."],
    correctIndex: 1,
    explanation: "Popper montre qu'une tolérance sans limites est auto-destructrice : elle doit être intolérante envers ceux qui menacent la tolérance elle-même.",
  },
];
