import type { TCFListeningQuestion } from "./tcf-listening";
export type { TCFLevel } from "./tcf-listening";

/**
 * Paper 10 — Compréhension orale. Theme: culture, leisure and social integration in Canada.
 *
 * `audioScript` is rendered by Edge TTS, so each script is written to be read
 * aloud cleanly: no bullet points, numbers spelled where ambiguous, and
 * dialogue turns separated by em dashes.
 */
export const TCF_LISTENING_P10: TCFListeningQuestion[] = [
  // ── A1–A2 (Q1–10) ──────────────────────────────────────────────
  {
    id: 1,
    level: "A1",
    topic: "À la billetterie",
    audioScript: "— Bonjour, je voudrais deux billets pour le concert de ce soir. — Il reste des places debout seulement, à quinze dollars chacune. — D'accord. — Voici vos billets, la scène est côté est.",
    question: "Combien coûte un billet ?",
    options: ["Dix dollars.", "Quinze dollars.", "Vingt dollars.", "Gratuit."],
    correctIndex: 1,
    explanation: "Standing tickets are fifteen dollars each.",
  },
  {
    id: 2,
    level: "A1",
    topic: "Annonce à la patinoire",
    audioScript: "Votre attention, s'il vous plaît. La séance de patinage libre de quatorze heures est complète. La prochaine plage disponible commence à seize heures trente. Merci.",
    question: "Quand commence la prochaine séance libre ?",
    options: ["À quatorze heures.", "À quinze heures.", "À seize heures trente.", "À dix-huit heures."],
    correctIndex: 2,
    explanation: "The next free-skate slot starts at four thirty p.m.",
  },
  {
    id: 3,
    level: "A1",
    topic: "À l'accueil du centre sportif",
    audioScript: "— Où est la salle de yoga ? — Au sous-sol, porte B trois. Prenez l'escalier à gauche après les vestiaires. — Merci.",
    question: "Où se trouve la salle de yoga ?",
    options: ["Au premier étage.", "Au sous-sol.", "Dehors, près du terrain.", "À la bibliothèque voisine."],
    correctIndex: 1,
    explanation: "Yoga is in the basement, door B3.",
  },
  {
    id: 4,
    level: "A1",
    topic: "Message radio",
    audioScript: "Ce week-end, le festival des neiges offre la patinoire et les sculptures gratuites au parc central. Le feu d'artifice est prévu samedi à vingt heures. Habillez-vous chaudement.",
    question: "Qu'est-ce qui est gratuit selon l'annonce ?",
    options: ["Le feu d'artifice uniquement.", "La patinoire et les sculptures.", "Tous les concerts payants.", "Le stationnement souterrain."],
    correctIndex: 1,
    explanation: "The rink and snow sculptures at the central park are free.",
  },
  {
    id: 5,
    level: "A2",
    topic: "Bibliothèque",
    audioScript: "— Je voudrais m'inscrire au club de lecture bilingue. — Parfait, il faut votre carte de membre. Les séances sont le mardi à dix-huit heures ou le jeudi à dix-neuf heures. — Je choisis le jeudi.",
    question: "Quel jour la personne choisit-elle ?",
    options: ["Le lundi.", "Le mardi.", "Le jeudi.", "Le samedi."],
    correctIndex: 2,
    explanation: "She chooses the Thursday session at seven p.m.",
  },
  {
    id: 6,
    level: "A2",
    topic: "Centre communautaire",
    audioScript: "— Le cours d'initiation au ski de fond est complet samedi. — Y a-t-il une autre date ? — Oui, le groupe du dimanche a encore trois places. L'équipement se réserve en ligne avant vendredi midi.",
    question: "Que doit faire la personne pour l'équipement ?",
    options: ["L'acheter à la boutique du centre.", "Le réserver en ligne avant vendredi midi.", "Demander à un moniteur sur place.", "Apporter uniquement ses bâtons."],
    correctIndex: 1,
    explanation: "Equipment must be reserved online before Friday noon.",
  },
  {
    id: 7,
    level: "A2",
    topic: "Bénévolat",
    audioScript: "— Bonjour, je voudrais aider au festival d'été. — Super. La formation obligatoire est le cinq juin à dix heures. Vous serez au stand d'information l'après-midi. — Est-ce payé ? — Non, mais un repas et un t-shirt sont offerts.",
    question: "Que reçoit le bénévole ?",
    options: ["Un salaire horaire.", "Un repas et un t-shirt.", "Un billet pour tous les concerts.", "Un certificat de citoyenneté."],
    correctIndex: 1,
    explanation: "Volunteers get a meal and a T-shirt, not pay.",
  },
  {
    id: 8,
    level: "A2",
    topic: "Club de course",
    audioScript: "Rappel pour les coureurs : l'entraînement du samedi est avancé à sept heures à cause de la chaleur prévue l'après-midi. Rendez-vous au pavillon du parc Maple. Apportez de l'eau.",
    question: "Pourquoi l'horaire change-t-il ?",
    options: ["Par manque d'entraîneurs.", "À cause de la chaleur de l'après-midi.", "Pour cause de travaux sur la piste.", "Parce que le parc est fermé le soir."],
    correctIndex: 1,
    explanation: "Training moves to 7 a.m. because of afternoon heat.",
  },
  {
    id: 9,
    level: "A2",
    topic: "Soirée bilingue",
    audioScript: "— La soirée contes et musique est presque pleine. — Puis-je venir avec mes enfants ? — Oui, l'activité est familiale. Inscrivez-vous sur le site ; l'entrée est gratuite, mais les places sont comptées.",
    question: "Que faut-il faire pour participer ?",
    options: ["Payer à la porte sans inscription.", "S'inscrire sur le site.", "Apporter un instrument de musique.", "Parler uniquement en anglais."],
    correctIndex: 1,
    explanation: "Registration on the website is required though entry is free.",
  },
  {
    id: 10,
    level: "A2",
    topic: "Location de patins",
    audioScript: "— Je voudrais louer des patins pour mon fils, pointure trente-deux. — Voici la paire. C'est cinq dollars pour une heure, dix dollars pour la journée. — Je prends une heure. — Rendez-les avant dix-sept heures trente.",
    question: "Quand doit-on rendre les patins pour une location d'une heure ?",
    options: ["Avant seize heures.", "Avant dix-sept heures trente.", "Le lendemain matin.", "Après la patinoire seulement."],
    correctIndex: 1,
    explanation: "One-hour rentals must be returned before 5:30 p.m.",
  },

  // ── B1–B2 (Q11–30) ─────────────────────────────────────────────
  {
    id: 11,
    level: "B1",
    topic: "Festival d'hiver",
    audioScript: "— Est-ce que la navette gratuite passe par notre quartier ? — Oui, départ toutes les heures depuis l'arrêt Riverview entre dix-huit heures et vingt-trois heures. — Et le retour ? — Même arrêt, dernière navette à vingt-trois heures trente.",
    question: "Jusqu'à quelle heure peut-on prendre la navette aller ?",
    options: ["Jusqu'à vingt et une heures.", "Jusqu'à vingt-trois heures.", "Jusqu'à minuit.", "Seulement l'après-midi."],
    correctIndex: 1,
    explanation: "Shuttles run hourly until eleven p.m.",
  },
  {
    id: 12,
    level: "B1",
    topic: "Bibliothèque",
    audioScript: "La bibliothèque propose un atelier « premiers pas au hockey » samedi : vocabulaire, règles de base, visite de l'aréna voisin. C'est gratuit, mais il faut s'inscrire car les places sont limitées à vingt familles.",
    question: "Quel est l'objectif de l'atelier ?",
    options: [
      "Former des joueurs professionnels.",
      "Initier les familles à la culture du hockey local.",
      "Vendre des billets pour la LNH.",
      "Remplacer les cours de français.",
    ],
    correctIndex: 1,
    explanation: "The workshop introduces hockey vocabulary and rules for families.",
  },
  {
    id: 13,
    level: "B1",
    topic: "Entre amis",
    audioScript: "— Tu viens au tournoi de soccer amateur dimanche ? — Oui, je fais l'accueil des équipes de dix heures à midi. — Cool, moi je joue à quatorze heures. On pourra déjeuner ensemble au stand communautaire.",
    question: "Que fera la première personne le matin ?",
    options: [
      "Elle jouera le premier match.",
      "Elle accueillera les équipes de dix heures à midi.",
      "Elle arbitrera la finale.",
      "Elle organisera le concert du soir.",
    ],
    correctIndex: 1,
    explanation: "She greets teams from ten a.m. to noon.",
  },
  {
    id: 14,
    level: "B1",
    topic: "Reportage",
    audioScript: "Dans plusieurs villes, les bibliothèques prêtent désormais des raquettes et des luges en plus des livres. L'objectif est de rendre les loisirs d'hiver accessibles sans gros achat initial, surtout pour les familles récemment installées.",
    question: "Pourquoi ces prêts existent-ils ?",
    options: [
      "Pour remplacer les libraires par des moniteurs de ski.",
      "Pour rendre les loisirs hivernaux plus accessibles financièrement.",
      "Pour interdire les livres papier.",
      "Pour financer les équipes professionnelles.",
    ],
    correctIndex: 1,
    explanation: "Winter gear loans avoid large upfront costs for families.",
  },
  {
    id: 15,
    level: "B1",
    topic: "Guichet des loisirs",
    audioScript: "— Je voudrais une carte loisirs famille. — Il faut une preuve de revenu et deux pièces d'identité. Le rabais s'applique aux piscines, patinoires et camps d'été municipaux. Le délai de traitement est de dix jours ouvrables.",
    question: "Sur quoi s'applique le rabais ?",
    options: [
      "Uniquement sur les billets de cinéma privés.",
      "Sur les activités municipales comme piscines et patinoires.",
      "Sur les voyages à l'étranger.",
      "Sur les frais de citoyenneté.",
    ],
    correctIndex: 1,
    explanation: "The discount applies to municipal pools, rinks, and summer camps.",
  },
  {
    id: 16,
    level: "B1",
    topic: "Organisme communautaire",
    audioScript: "Notre programme jumelle un nouvel arrivant avec un résident pour assister ensemble à un match ou une séance de patinage. Ce n'est pas un cours de langue formel, mais beaucoup pratiquent le français en situation réelle.",
    question: "Que propose le programme ?",
    options: [
      "Des leçons magistrales de grammaire.",
      "Des sorties loisirs accompagnées pour créer des liens.",
      "Un emploi garanti dans le sport.",
      "Un certificat de hockey obligatoire.",
    ],
    correctIndex: 1,
    explanation: "Buddy outings to games or skating build links and informal French practice.",
  },
  {
    id: 17,
    level: "B1",
    topic: "Interview",
    audioScript: "— Pourquoi faites-vous du bénévolat à la bibliothèque ? — Parce que quand je suis arrivée, quelqu'un m'a aidée à m'inscrire aux activités. Je veux faire pareil pour d'autres. Une heure par semaine suffit pour accueillir au club de lecture.",
    question: "Pourquoi la personne fait-elle du bénévolat ?",
    options: [
      "Pour obtenir un salaire complémentaire.",
      "Pour rendre l'aide qu'elle a reçue à son arrivée.",
      "Pour éviter de payer sa carte de bibliothèque.",
      "Pour suivre une formation d'infirmière.",
    ],
    correctIndex: 1,
    explanation: "She volunteers because someone helped her register for activities when she arrived.",
  },
  {
    id: 18,
    level: "B1",
    topic: "Marche nordique",
    audioScript: "— La séance de jeudi est maintenue malgré le vent. — On se retrouve au pavillon ? — Oui, sauf si la pluie commence ; dans ce cas, courriel avant dix-sept heures et on va au gymnase. N'oubliez pas vos bâtons.",
    question: "Où iront-ils s'il pleut ?",
    options: ["Au pavillon du parc.", "Au gymnase.", "À la patinoire.", "À la mairie."],
    correctIndex: 1,
    explanation: "Rain moves the session to the gym with email notice before 5 p.m.",
  },
  {
    id: 19,
    level: "B1",
    topic: "Conseil municipal",
    audioScript: "— Cette séance sur le budget des loisirs est ouverte au public. Les interventions durent trois minutes. — Puis-je parler en français ? — Oui, un interprète est disponible si vous prévenez vingt-quatre heures à l'avance.",
    question: "Que faut-il faire pour un interprète ?",
    options: [
      "Payer un supplément à l'entrée.",
      "Prévenir vingt-quatre heures à l'avance.",
      "Écrire son discours uniquement en anglais.",
      "Arriver une heure avant la séance.",
    ],
    correctIndex: 1,
    explanation: "An interpreter is available with twenty-four hours' notice.",
  },
  {
    id: 20,
    level: "B2",
    topic: "Débat radiophonique",
    audioScript: "— Les festivals gratuits attirent tout le monde dans la rue. — Oui, mais si la nourriture coûte cher et que les annonces sont seulement en anglais, beaucoup de nouveaux résidents regardent de loin. L'intégration ne se mesure pas au nombre de flyers distribués.",
    question: "Quel argument le second intervenant développe-t-il ?",
    options: [
      "Les festivals devraient être payants.",
      "Un événement gratuit peut rester socialement exclusif.",
      "Les nouveaux résidents détestent la musique.",
      "Il faut supprimer les stands de nourriture.",
    ],
    correctIndex: 1,
    explanation: "Free entry does not guarantee inclusion if costs and language exclude people.",
  },
  {
    id: 21,
    level: "B2",
    topic: "Conférence",
    audioScript: "Les bibliothèques ne sont plus seulement des entrepôts de livres : elles accueillent des clubs de conversation, prêtent des outils et servent de refuges thermiques. Pour beaucoup d'immigrants, la carte de bibliothèque est la première clé d'accès à la vie sociale locale sans réseau professionnel.",
    question: "Quel rôle social la conférencière attribue-t-elle aux bibliothèques ?",
    options: [
      "Remplacer les centres d'emploi.",
      "Ouvrir la vie sociale locale aux personnes sans réseau.",
      "Former uniquement des bibliothécaires.",
      "Interdire les activités en anglais.",
    ],
    correctIndex: 1,
    explanation: "Library cards open local social life without needing a professional network.",
  },
  {
    id: 22,
    level: "B2",
    topic: "Ligue amateur",
    audioScript: "— Notre ligue mélange les équipes par tirage au sort pour éviter que les amis restent toujours ensemble. — Certains parents se plaignent. — Peut-être, mais les enfants nouveaux au pays trouvent plus vite des coéquipiers qui leur parlent.",
    question: "Pourquoi la ligue utilise-t-elle un tirage au sort ?",
    options: [
      "Pour réduire le coût des maillots.",
      "Pour favoriser des équipes mixtes et inclure les nouveaux joueurs.",
      "Pour interdire les entraîneurs bénévoles.",
      "Pour copier les règles professionnelles.",
    ],
    correctIndex: 1,
    explanation: "Random teams help newcomers find teammates instead of closed cliques.",
  },
  {
    id: 23,
    level: "B2",
    topic: "Chronique culturelle",
    audioScript: "Une soirée slam bilingue au centre communautaire peut être la première fois qu'un adolescent immigrant monte sur scène. Ce n'est pas le théâtre municipal, mais c'est souvent la porte d'entrée. Mépriser ces formats populaires, c'est fermer l'échelle des intégrations culturelles.",
    question: "Quel lien la chronique établit-elle ?",
    options: [
      "Entre sport professionnel et théâtre.",
      "Entre événements communautaires populaires et participation culturelle plus large.",
      "Entre bibliothèques et écoles privées.",
      "Entre festivals d'été et impôts municipaux.",
    ],
    correctIndex: 1,
    explanation: "Community slam can lead toward broader cultural participation.",
  },
  {
    id: 24,
    level: "B2",
    topic: "Table ronde",
    audioScript: "— Imposer des heures de bénévolat pour inscrire un enfant au soccer subventionné valorise l'engagement. — Oui, mais les parents à horaires tournants ne peuvent jamais être présents aux réunions. On exclut ceux qu'on prétend intégrer par le sport.",
    question: "Quelle critique est formulée ?",
    options: [
      "Le soccer coûte trop cher pour la ville.",
      "Les exigences de bénévolat pénalisent les horaires imprévisibles.",
      "Les enfants immigrants ne veulent pas jouer.",
      "Les clubs professionnels refusent les bénévoles.",
    ],
    correctIndex: 1,
    explanation: "Volunteer-hour rules exclude parents with shift work.",
  },
  {
    id: 25,
    level: "B2",
    topic: "Reportage social",
    audioScript: "À Calgary, une ligne téléphonique oriente les familles vers les patinoires avec prêt de patins et vers les clubs de lecture bilingues. Les appels augmentent en janvier, quand la solitude hivernale se combine au choc culturel. Les opérateurs ne remplacent pas les psychologues, mais ils réduisent le temps perdu à chercher le bon service.",
    question: "Quel est l'objectif principal de cette ligne ?",
    options: [
      "Offrir des séances de thérapie gratuites.",
      "Diriger vers les bons loisirs et services communautaires.",
      "Vendre des abonnements sportifs.",
      "Remplacer les bibliothèques municipales.",
    ],
    correctIndex: 1,
    explanation: "Operators route families to rinks, gear loans, and reading clubs.",
  },
  {
    id: 26,
    level: "B2",
    topic: "Documentaire",
    audioScript: "Le film suit trois familles qui découvrent l'hiver canadien : première patinoire, premier match de curling, première randonnée en raquettes. La mère philippine dit que le froid était moins effrayant une fois qu'un voisin leur a prêté des mitaines et expliqué comment s'habiller en couches.",
    question: "Qu'est-ce qui a aidé la famille à accepter l'hiver ?",
    options: [
      "Un cours théorique en ligne uniquement.",
      "L'aide concrète d'un voisin avec vêtements et conseils.",
      "L'achat obligatoire d'un chalet.",
      "Le refus de sortir de décembre à mars.",
    ],
    correctIndex: 1,
    explanation: "A neighbour's mittens and layering advice made winter less frightening.",
  },
  {
    id: 27,
    level: "B2",
    topic: "Interview",
    audioScript: "— Pourquoi les jeunes immigrants utilisent-ils peu les bibliothèques au début ? — Souvent parce qu'ils ne savent pas qu'on peut y passer sans acheter quelque chose. Une invitation d'un camarade de classe change tout. Les statistiques de fréquentation ignorent cette première peur de franchir la porte.",
    question: "Selon l'interviewé, qu'est-ce qui fait changer l'usage ?",
    options: [
      "Une amende municipale.",
      "Une invitation personnelle d'un pair.",
      "Un examen obligatoire de lecture.",
      "La fermeture des centres commerciaux.",
    ],
    correctIndex: 1,
    explanation: "A classmate's invitation overcomes fear of entering the library.",
  },
  {
    id: 28,
    level: "B2",
    topic: "Débat municipal",
    audioScript: "— Prolonger les heures de bibliothèque le soir aide les parents qui travaillent tard. — D'accord, mais cela coûte du personnel. Les budgets participatifs votent plutôt pour des murals visibles. Les besoins invisibles passent après.",
    question: "Quel argument le second orateur utilise-t-il ?",
    options: [
      "Les bibliothèques sont inutiles le soir.",
      "Les projets visibles l'emportent souvent sur des services discrets dans les votes.",
      "Les parents ne lisent plus de livres.",
      "Les murals sont interdits par la province.",
    ],
    correctIndex: 1,
    explanation: "Participatory budgets favour visible murals over evening library hours.",
  },
  {
    id: 29,
    level: "B2",
    topic: "Chronique",
    audioScript: "Servir le café lors d'un festival m'a appris plus sur mon quartier que n'importe quelle brochure. J'ai entendu quelles patinoires sont vraiment accueillantes, quels clubs cherchent des bénévoles. Le loisir bénévole devient une carte informelle de la vie locale.",
    question: "Qu'apprend l'auteur en faisant du bénévolat festif ?",
    options: [
      "Que les brochures sont toujours fausses.",
      "Comment repérer les lieux et clubs accueillants du quartier.",
      "Que les festivals ne servent à rien.",
      "Qu'il faut éviter de parler aux visiteurs.",
    ],
    correctIndex: 1,
    explanation: "Volunteering reveals which rinks and clubs are welcoming.",
  },
  {
    id: 30,
    level: "B2",
    topic: "Analyse institutionnelle",
    audioScript: "Quand on parle d'intégration par le sport, on oublie souvent qui dirige les ligues : des bénévoles installés depuis des années. Sans places à la table des décisions, la participation des nouveaux reste décorative, limitée à servir les collations plutôt qu'à choisir la programmation.",
    question: "Quel problème le commentateur décrit-il ?",
    options: [
      "Le manque total de clubs sportifs.",
      "Une participation sans pouvoir sur les décisions.",
      "L'interdiction du soccer pour les enfants.",
      "La suppression des festivals d'hiver.",
    ],
    correctIndex: 1,
    explanation: "Newcomers serve food but lack decision-making power in leagues.",
  },

  // ── C1–C2 (Q31–39) ─────────────────────────────────────────────
  {
    id: 31,
    level: "C1",
    topic: "Conférence universitaire",
    audioScript: "Mesurer l'intégration par la fréquentation des festivals confond audience et lien social. Dix mille personnes peuvent traverser un site sans échanger un mot. Les politiques devraient financer les espaces de répétition — clubs, bibliothèques, patinoires — où les rencontres s'accumulent dans le temps.",
    question: "Quelle distinction la conférencière établit-elle ?",
    options: [
      "Entre sport d'été et sport d'hiver.",
      "Entre foule spectatrice et relations sociales durables.",
      "Entre français et anglais dans les festivals.",
      "Entre bibliothèques urbaines et rurales.",
    ],
    correctIndex: 1,
    explanation: "Large crowds are not the same as lasting social ties.",
  },
  {
    id: 32,
    level: "C1",
    topic: "Séminaire de sociologie",
    audioScript: "Le bénévolat sportif est présenté comme universel, mais il suppose du temps libre synchronisé avec les réunions de club. Les travailleurs précaires y sont sous-représentés, non par manque de générosité, mais parce que leurs horaires ne coïncident pas. Ignorer cette variable fausse les politiques d'intégration.",
    question: "Quel biais l'intervenant souligne-t-il ?",
    options: [
      "Les clubs refusent les immigrants.",
      "L'engagement bénévole est mesuré sans tenir compte des horaires de travail.",
      "Le sport amateur est interdit le soir.",
      "Les femmes ne peuvent pas être bénévoles.",
    ],
    correctIndex: 1,
    explanation: "Precarious schedules keep workers from volunteer meetings.",
  },
  {
    id: 33,
    level: "C1",
    topic: "Débat culturel",
    audioScript: "— Les soirées bilingues montrent l'ouverture de la ville. — Si les annonces principales restent en anglais et le français est relégué aux ateliers secondaires, on célèbre la diversité sans partager le temps de parole. L'intégration linguistique ne se résume pas à un drapeau sur la scène.",
    question: "Quel argument le second intervenant développe-t-il ?",
    options: [
      "Les soirées bilingues coûtent trop cher.",
      "La répartition du temps de parole peut rester inégale entre langues.",
      "Il faut interdire l'anglais dans les festivals.",
      "Les ateliers secondaires sont inutiles.",
    ],
    correctIndex: 1,
    explanation: "Bilingual branding can mask unequal speaking time on stage.",
  },
  {
    id: 34,
    level: "C1",
    topic: "Cours de politiques publiques",
    audioScript: "Les tarifs sociaux pour les patinoires réduisent la barrière financière, mais pas toujours la barrière symbolique. Se sentir attendu plutôt que toléré demande une médiation humaine : un accueil nommé, des animateurs formés à l'interculturalité. Sans cela, les indicateurs de fréquentation masquent des silences.",
    question: "Quel obstacle reste selon l'intervenant ?",
    options: [
      "Le manque de patinoires au Canada.",
      "Le sentiment de ne pas être vraiment accueilli malgré un prix réduit.",
      "L'interdiction des activités familiales.",
      "La fermeture des bibliothèques l'hiver.",
    ],
    correctIndex: 1,
    explanation: "Social pricing does not fix symbolic exclusion without welcoming mediation.",
  },
  {
    id: 35,
    level: "C1",
    topic: "Exposé économique",
    audioScript: "Comparer deux villes sur leurs dépenses culturelles sans regarder qui ose entrer dans les lieux produit des classements trompeurs. Une médiation initiale — visite guidée, buddy program — coûte moins qu'un festival supplémentaire, mais change la composition réelle du public.",
    question: "Quel obstacle méthodologique l'intervenant décrit-il ?",
    options: [
      "L'absence de statistiques sur les festivals.",
      "Les classements ignorent les barrières à la première visite.",
      "Les musées sont toujours gratuits.",
      "Les buddy programs sont illégaux.",
    ],
    correctIndex: 1,
    explanation: "Spending comparisons miss first-visit barriers mediation addresses.",
  },
  {
    id: 36,
    level: "C2",
    topic: "Conférence de philosophie",
    audioScript: "Jouer dans une équipe amateur expose à la défaite, à la règle commune et à l'autre qui performe mieux. C'est une école informelle de coexistence. Réduire le sport à la consommation télévisée, c'est retirer ce laboratoire civique du quotidien.",
    question: "Quel lien le philosophe établit-il ?",
    options: [
      "Entre hockey professionnel et monarchie.",
      "Entre pratique sportive partagée et apprentissage de la coexistence.",
      "Entre bibliothèques et tribunaux.",
      "Entre festivals et impôts fédéraux.",
    ],
    correctIndex: 1,
    explanation: "Amateur team play teaches coexistence; TV sport removes that lab.",
  },
  {
    id: 37,
    level: "C2",
    topic: "Séminaire d'urbanisme",
    audioScript: "Le design hivernal — lumières, abris, boissons chaudes — se présente comme neutre, mais oriente qui sort après le travail. Tant que certaines familles évitent les parcs glacés par crainte ou par habitudes différentes, le confort urbain reste une promesse inégalement reçue.",
    question: "Quelle tension le séminariste souligne-t-il ?",
    options: [
      "Entre ski alpin et ski de fond.",
      "Entre aménagements prétendus neutres et usages sociaux inégaux.",
      "Entre français et anglais sur les panneaux.",
      "Entre bibliothèques et arénas.",
    ],
    correctIndex: 1,
    explanation: "Winter design claims neutrality yet some groups still avoid icy parks.",
  },
  {
    id: 38,
    level: "C2",
    topic: "Colloque sur l'intégration",
    audioScript: "Demander aux nouveaux résidents de participer aux festivals tout en réservant la programmation aux bénévoles de longue date crée deux registres : accueil chaleureux et pouvoir de décision. Sans transfert réel de responsabilités, l'intégration reste sentimentale, pas politique.",
    question: "Quel paradoxe est présenté ?",
    options: [
      "Les festivals sont trop nombreux en hiver.",
      "On invite à participer sans partager le pouvoir de programmer.",
      "Les bénévoles sont tous payés.",
      "Les nouveaux résidents refusent le bénévolat.",
    ],
    correctIndex: 1,
    explanation: "Warm welcome coexists with exclusion from programming decisions.",
  },
  {
    id: 39,
    level: "C2",
    topic: "Conférence sur les loisirs publics",
    audioScript: "L'intégration ne se réduit pas aux documents : elle se joue dans le temps libre partagé. Refuser des places abordables au sport ou des horaires de bibliothèque adaptés, c'est laisser des résidents permanents vivre à côté de la communauté sans en être pleinement membres.",
    question: "Quelle conception de l'intégration l'intervenant défend-il ?",
    options: [
      "Une intégration limitée aux formalités administratives.",
      "Une intégration qui inclut l'accès aux loisirs et au temps libre collectif.",
      "Une intégration réservée aux sportifs professionnels.",
      "Une intégration fondée uniquement sur le marché du travail.",
    ],
    correctIndex: 1,
    explanation: "Integration includes affordable sport and library access, not only paperwork.",
  },
];
